with upsert_data as(
SELECT DISTINCT
DM.PRDR_INVL_DURB_ID,
DM.DATA_EFF_STRT_DT,
DM.PRDR_INVL_CD,
DM.PRDR_INVL_DESC 
FROM (
SELECT
PH.DURB_ID PRDR_INVL_DURB_ID,
coalesce(PR.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) DATA_EFF_STRT_DT,
PR.PRDR_INVL_CD PRDR_INVL_CD,
PR.PRDR_INVL_DESC  PRDR_INVL_DESC,
ROW_NUMBER() OVER ( PARTITION BY coalesce(PR.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')), PR.PRDR_INVL_CD ORDER BY PR.DATA_EFF_STRT_DT DESC) AS ROW_NUM_PART
FROM EBV.PRDR_INVL_RS PR 
LEFT JOIN EBV.PRDR_INVL_RH PH ON ( PH.PRDR_INVL_CD = coalesce(PR.PRDR_INVL_CD,'[NULL IN SOURCE]'))
WHERE cast(PR.DATA_EFF_STRT_DT as date) <=  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 
AND EXISTS ( SELECT '1' FROM EBV.PRDR_INVL_RS PR_IN
             WHERE PR.PRDR_INVL_CD = PR_IN.PRDR_INVL_CD
              AND cast(PR_IN.DATA_EFF_END_DT as date) = TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')) 
AND PH.DURB_ID IS NOT NULL              
) DM
WHERE DM.ROW_NUM_PART = 1
)
select ud.prdr_invl_durb_id,
	'0' as cur_rcd_ind,
	ud.data_eff_strt_dt,
	(CURRENT_DATE) as data_eff_end_dt, 
	(CURRENT_DATE) as cre_dt, 
	ud.prdr_invl_cd,
	ud.prdr_invl_desc
from upsert_data ud







