with del_data as 
( select sub1.*
from (
SELECT
PGM_YR, 
PRNT_FARM_SRGT_ID,
RSLT_FARM_SRGT_ID, 
PRNT_FARM_DURB_ID,
RSLT_FARM_DURB_ID,
PRNT_FSA_ST_CNTY_SRGT_ID,
PRNT_FSA_ST_CNTY_DURB_ID,
RSLT_FSA_ST_CNTY_SRGT_ID,
RSLT_FSA_ST_CNTY_DURB_ID,
XFR_CRE_DT,
XFR_CRE_USER_NM,
XFR_LAST_CHG_DT,
XFR_LAST_CHG_USER_NM,
SRC_DATA_STAT_CD,
XFR_CRE_DT_ID,
XFR_CRE_TM_ID,
XFR_LAST_CHG_DT_ID,
XFR_LAST_CHG_TM_ID,
DATA_EFF_STRT_DT
FROM (
SELECT  DISTINCT COALESCE(CAST(MFX.TM_PRD_NM AS INTEGER), FIRST_VALUE(FS.PGM_YR) OVER (PARTITION BY MFX.RSLT_ST_FSA_CD,MFX.RSLT_CNTY_FSA_CD ,MFX.RSLT_FARM_NBR ORDER BY FS.PGM_YR ASC )) AS PGM_YR, 
COALESCE(FD_PRNT.FARM_SRGT_ID,-3) AS PRNT_FARM_SRGT_ID,
COALESCE(FD_RSLT.FARM_SRGT_ID,-3) RSLT_FARM_SRGT_ID, 
FD_PRNT.FARM_DURB_ID  PRNT_FARM_DURB_ID,
FD_RSLT.FARM_DURB_ID  RSLT_FARM_DURB_ID,
COALESCE(FSD_PRNT.FSA_ST_CNTY_SRGT_ID,-3) PRNT_FSA_ST_CNTY_SRGT_ID,
COALESCE(FSD_PRNT.FSA_ST_CNTY_DURB_ID,-3) PRNT_FSA_ST_CNTY_DURB_ID,
COALESCE(FSD_RSLT.FSA_ST_CNTY_SRGT_ID,-3) RSLT_FSA_ST_CNTY_SRGT_ID,
COALESCE(FSD_RSLT.FSA_ST_CNTY_DURB_ID,-3) RSLT_FSA_ST_CNTY_DURB_ID,
MFX.SRC_CRE_DT XFR_CRE_DT,
MFX.SRC_CRE_USER_NM XFR_CRE_USER_NM,
MFX.SRC_LAST_CHG_DT XFR_LAST_CHG_DT,
MFX.SRC_LAST_CHG_USER_NM XFR_LAST_CHG_USER_NM,
MFX.DATA_STAT_CD SRC_DATA_STAT_CD,
COALESCE(CAST(TO_CHAR(MFX.SRC_CRE_DT, 'YYYYMMDD') AS INTEGER), -1) AS XFR_CRE_DT_ID,
COALESCE(CAST(TO_CHAR(MFX.SRC_CRE_DT, 'HH24MISS') AS INTEGER), -1) AS XFR_CRE_TM_ID,
COALESCE(CAST(TO_CHAR(MFX.SRC_LAST_CHG_DT, 'YYYYMMDD') AS INTEGER), -1) AS XFR_LAST_CHG_DT_ID,
COALESCE(CAST(TO_CHAR(MFX.SRC_LAST_CHG_DT, 'HH24MISS') AS INTEGER), -1) AS XFR_LAST_CHG_TM_ID,
GREATEST(
COALESCE(MFX.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),
COALESCE(FS.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),
COALESCE(LAS_PRNT.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),
COALESCE(LAS_RSLT.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD'))
) DATA_EFF_STRT_DT,
ROW_NUMBER() OVER (PARTITION BY PGM_YR,FD_PRNT.FARM_DURB_ID,FD_RSLT.FARM_DURB_ID ORDER BY MFX.DATA_EFF_STRT_DT DESC,FS.DATA_EFF_STRT_DT DESC,
LAS_PRNT.DATA_EFF_STRT_DT DESC,LAS_RSLT.DATA_EFF_STRT_DT DESC ) AS  ROW_NUM_PART
 FROM EDV.MIDAS_FARM_XFR_LS MFX  
 LEFT JOIN  EDV.FARM_H FH_PRNT ON (COALESCE(MFX.PRNT_ST_FSA_CD,'--') = FH_PRNT.ST_FSA_CD 
                           AND COALESCE(MFX.PRNT_CNTY_FSA_CD,'--') = FH_PRNT.CNTY_FSA_CD 
                           AND COALESCE(MFX.PRNT_FARM_NBR,'--') =FH_PRNT.FARM_NBR )
 LEFT JOIN CMN_DIM_DM_STG.FARM_DIM FD_PRNT ON (FH_PRNT.DURB_ID = COALESCE(FD_PRNT.FARM_DURB_ID,-1) AND FD_PRNT.CUR_RCD_IND = 1) 
 LEFT JOIN EDV.FARM_H FH_RSLT ON (COALESCE(MFX.RSLT_ST_FSA_CD,'--')  = FH_RSLT.ST_FSA_CD 
                           AND COALESCE(MFX.RSLT_CNTY_FSA_CD,'--') = FH_RSLT.CNTY_FSA_CD 
                           AND COALESCE(MFX.RSLT_FARM_NBR,'--')  =FH_RSLT.FARM_NBR )
 LEFT JOIN CMN_DIM_DM_STG.FARM_DIM FD_RSLT ON (FH_RSLT.DURB_ID = COALESCE(FD_RSLT.FARM_DURB_ID,-1) AND FD_RSLT.CUR_RCD_IND = 1)                           
 LEFT JOIN EDV.FARM_RCON_L FR ON (COALESCE(MFX.FARM_RCON_L_ID,'6bb61e3b7bce0931da574d19d1d82c88') = FR.FARM_RCON_L_ID )
 LEFT JOIN EDV.FARM_H FH ON ( COALESCE(FR.RSLT_FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = FH.FARM_H_ID) 
 LEFT JOIN EDV.FARM_YR_HS FS ON (FH.FARM_H_ID = COALESCE(FS.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd'))
 LEFT JOIN EDV.LOC_AREA_MRT_SRC_RS LAS_PRNT ON ( MFX.PRNT_ST_FSA_CD  = LAS_PRNT.CTRY_DIV_MRT_CD
                           AND MFX.PRNT_CNTY_FSA_CD = LAS_PRNT.LOC_AREA_MRT_CD 
                           AND LAS_PRNT.LOC_AREA_MRT_CD_SRC_ACRO = 'FSA')
 LEFT JOIN EDV.LOC_AREA_RH LAH_PRNT ON  ( COALESCE(LAS_PRNT.LOC_AREA_CAT_NM,'[NULL IN SOURCE]') = LAH_PRNT.LOC_AREA_CAT_NM 
                           AND COALESCE(LAS_PRNT.LOC_AREA_NM,'[NULL IN SOURCE]') = LAH_PRNT.LOC_AREA_NM 
                           AND COALESCE(LAS_PRNT.CTRY_DIV_NM,'[NULL IN SOURCE]') = LAH_PRNT.CTRY_DIV_NM
                           AND TRIM(LAS_PRNT.LOC_AREA_MRT_CD_SRC_ACRO) = 'FSA')
 LEFT JOIN CMN_DIM_DM_STG.FSA_ST_CNTY_DIM FSD_PRNT ON (LAH_PRNT.DURB_ID = COALESCE(FSD_PRNT.FSA_ST_CNTY_DURB_ID,-1)
                           AND FSD_PRNT.CUR_RCD_IND = 1 )
 LEFT JOIN EDV.LOC_AREA_MRT_SRC_RS LAS_RSLT ON (MFX.RSLT_ST_FSA_CD  = LAS_RSLT.CTRY_DIV_MRT_CD
                           AND MFX.RSLT_CNTY_FSA_CD = LAS_RSLT.LOC_AREA_MRT_CD 
                           AND LAS_RSLT.LOC_AREA_MRT_CD_SRC_ACRO = 'FSA' )
 LEFT JOIN EDV.LOC_AREA_RH LAH_RSLT ON  ( COALESCE(LAS_RSLT.LOC_AREA_CAT_NM,'[NULL IN SOURCE]') = LAH_RSLT.LOC_AREA_CAT_NM 
                           AND COALESCE(LAS_RSLT.LOC_AREA_NM,'[NULL IN SOURCE]') = LAH_RSLT.LOC_AREA_NM 
                           AND COALESCE(LAS_RSLT.CTRY_DIV_NM,'[NULL IN SOURCE]') = LAH_RSLT.CTRY_DIV_NM
                           AND TRIM(LAS_RSLT.LOC_AREA_MRT_CD_SRC_ACRO) = 'FSA')
 LEFT JOIN CMN_DIM_DM_STG.FSA_ST_CNTY_DIM FSD_RSLT ON (LAH_RSLT.DURB_ID = COALESCE(FSD_RSLT.FSA_ST_CNTY_DURB_ID,-1)
                           AND FSD_RSLT.CUR_RCD_IND = 1 )          
 WHERE 
 (
 (
 CAST(MFX.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
 )
 OR
 (
 CAST(FS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
 )
 OR
 (
 CAST(LAS_PRNT.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
 )
 OR
 (
 CAST(LAS_RSLT.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
 ) 
 )
 AND CAST(MFX.DATA_EFF_STRT_DT AS DATE) <=  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
 AND CAST(FS.DATA_EFF_STRT_DT AS DATE)  <=  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
 AND CAST(LAS_PRNT.DATA_EFF_STRT_DT AS DATE)  <=  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
 AND CAST(LAS_RSLT.DATA_EFF_STRT_DT AS DATE)  <=  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 
 AND FS.PGM_YR IS NOT NULL
 AND FD_PRNT.FARM_DURB_ID  IS NOT NULL
 AND FD_RSLT.FARM_DURB_ID IS NOT NULL
 )DM
 WHERE DM.ROW_NUM_PART = 1
 ) sub1
)
SELECT (current_date) as cre_dt,
	(current_date) as last_chg_dt, 
	'I' as data_stat_cd,  
	pgm_yr, 
	prnt_farm_srgt_id, 
	rslt_farm_srgt_id, 
	prnt_farm_durb_id, 
	rslt_farm_durb_id, 
	prnt_fsa_st_cnty_srgt_id, 
	prnt_fsa_st_cnty_durb_id, 
	rslt_fsa_st_cnty_srgt_id, 
	rslt_fsa_st_cnty_durb_id, 
	xfr_cre_dt, 
	xfr_cre_user_nm, 
	xfr_last_chg_dt, 
	xfr_last_chg_user_nm, 
	src_data_stat_cd, 
	xfr_cre_dt_id, 
	xfr_cre_tm_id, 
	xfr_last_chg_dt_id, 
	xfr_last_chg_tm_id
from del_data 
where prnt_farm_srgt_id > 0
order by prnt_farm_srgt_id asc