-- =============================================================================
-- Julia Lu - 2026-01-22
-- Stage SQL: CCMS_CTR_DET_EXTN (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/STG/CCMS_CTR_DET_EXTN/incremental/CCMS_CTR_DET_EXTN.sql
-- Date Logic:
--   ETL_START_DATE = User provided start_date
--   ETL_END_DATE   = Today (automatically set by Glue job)
--
-- Examples:
--   start_date=2025-01-12 (today is 2025-01-12) → Single day
--   start_date=2025-01-10 (today is 2025-01-12) → 3 days catch-up
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_NM,
SGNP_SUB_CAT_NM,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
CTR_NBR,
CTR_SFX_NBR,
EXTN_TYPE_DESC,
PYMT_LMT_PVSN_CD,
PYMT_LMT_PVSN_CD_YR,
CTR_DET_EXTN_ID,
EXTN_TYPE_CD,
CTR_DET_ID,
EFF_STRT_DT,
EFF_END_DT,
EXTN_RT,
CTR_ANL_PYMT_AMT,
PYMT_LMT_TYPE_ID,
DATA_STAT_CD,
CRE_DT,
CRE_USER_NM,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CTR_DET_EXTN_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
EXTENSION_TYPE.EXTENSION_TYPE_DESCRIPTION EXTN_TYPE_DESC,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_EXTENSION_IDENTIFIER CTR_DET_EXTN_ID,
CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE EXTN_TYPE_CD,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_START_DATE EFF_STRT_DT,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_END_DATE EFF_END_DT,
CONTRACT_DETAIL_EXTENSION.EXTENSION_RATE EXTN_RT,
CONTRACT_DETAIL_EXTENSION.Contract_Annual_Payment_Amount CTR_ANL_PYMT_AMT,
CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
CONTRACT_DETAIL_EXTENSION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_DETAIL_EXTENSION.CREATION_DATE CRE_DT,
CONTRACT_DETAIL_EXTENSION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_DETAIL_EXTENSION.op,
1 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".CONTRACT_DETAIL_EXTENSION 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER) 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE ) 
LEFT JOIN "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE 
ON ( PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID = CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID ) 
LEFT JOIN "fsa-{env}-ccms-cdc".EXTENSION_TYPE 
ON ( EXTENSION_TYPE.EXTENSION_TYPE_CODE = CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE )  
WHERE CONTRACT_DETAIL_EXTENSION.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
EXTENSION_TYPE.EXTENSION_TYPE_DESCRIPTION EXTN_TYPE_DESC,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_EXTENSION_IDENTIFIER CTR_DET_EXTN_ID,
CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE EXTN_TYPE_CD,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_START_DATE EFF_STRT_DT,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_END_DATE EFF_END_DT,
CONTRACT_DETAIL_EXTENSION.EXTENSION_RATE EXTN_RT,
CONTRACT_DETAIL_EXTENSION.Contract_Annual_Payment_Amount CTR_ANL_PYMT_AMT,
CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
CONTRACT_DETAIL_EXTENSION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_DETAIL_EXTENSION.CREATION_DATE CRE_DT,
CONTRACT_DETAIL_EXTENSION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_DETAIL.op,
2 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL_EXTENSION 
ON (CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER) 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE ) 
LEFT JOIN "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE 
ON ( PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID = CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID ) 
LEFT JOIN "fsa-{env}-ccms-cdc".EXTENSION_TYPE 
ON ( EXTENSION_TYPE.EXTENSION_TYPE_CODE = CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE )  
WHERE CONTRACT_DETAIL.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
EXTENSION_TYPE.EXTENSION_TYPE_DESCRIPTION EXTN_TYPE_DESC,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_EXTENSION_IDENTIFIER CTR_DET_EXTN_ID,
CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE EXTN_TYPE_CD,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_START_DATE EFF_STRT_DT,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_END_DATE EFF_END_DT,
CONTRACT_DETAIL_EXTENSION.EXTENSION_RATE EXTN_RT,
CONTRACT_DETAIL_EXTENSION.Contract_Annual_Payment_Amount CTR_ANL_PYMT_AMT,
CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
CONTRACT_DETAIL_EXTENSION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_DETAIL_EXTENSION.CREATION_DATE CRE_DT,
CONTRACT_DETAIL_EXTENSION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
MASTER_CONTRACT.op,
3 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL_EXTENSION 
ON (CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE ) 
LEFT JOIN "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE 
ON ( PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID = CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID ) 
LEFT JOIN "fsa-{env}-ccms-cdc".EXTENSION_TYPE 
ON ( EXTENSION_TYPE.EXTENSION_TYPE_CODE = CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE )  
WHERE MASTER_CONTRACT.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
EXTENSION_TYPE.EXTENSION_TYPE_DESCRIPTION EXTN_TYPE_DESC,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_EXTENSION_IDENTIFIER CTR_DET_EXTN_ID,
CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE EXTN_TYPE_CD,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_START_DATE EFF_STRT_DT,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_END_DATE EFF_END_DT,
CONTRACT_DETAIL_EXTENSION.EXTENSION_RATE EXTN_RT,
CONTRACT_DETAIL_EXTENSION.Contract_Annual_Payment_Amount CTR_ANL_PYMT_AMT,
CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
CONTRACT_DETAIL_EXTENSION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_DETAIL_EXTENSION.CREATION_DATE CRE_DT,
CONTRACT_DETAIL_EXTENSION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP.op,
4 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".SIGNUP 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL_EXTENSION 
ON (CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE ) 
LEFT JOIN "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE 
ON ( PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID = CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID ) 
LEFT JOIN "fsa-{env}-ccms-cdc".EXTENSION_TYPE 
ON ( EXTENSION_TYPE.EXTENSION_TYPE_CODE = CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE )  
WHERE SIGNUP.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
EXTENSION_TYPE.EXTENSION_TYPE_DESCRIPTION EXTN_TYPE_DESC,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_EXTENSION_IDENTIFIER CTR_DET_EXTN_ID,
CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE EXTN_TYPE_CD,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_START_DATE EFF_STRT_DT,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_END_DATE EFF_END_DT,
CONTRACT_DETAIL_EXTENSION.EXTENSION_RATE EXTN_RT,
CONTRACT_DETAIL_EXTENSION.Contract_Annual_Payment_Amount CTR_ANL_PYMT_AMT,
CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
CONTRACT_DETAIL_EXTENSION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_DETAIL_EXTENSION.CREATION_DATE CRE_DT,
CONTRACT_DETAIL_EXTENSION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP_TYPE.op,
5 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE ) 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL_EXTENSION 
ON (CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE 
ON ( PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID = CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID ) 
LEFT JOIN "fsa-{env}-ccms-cdc".EXTENSION_TYPE 
ON ( EXTENSION_TYPE.EXTENSION_TYPE_CODE = CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE )  
WHERE SIGNUP_TYPE.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
EXTENSION_TYPE.EXTENSION_TYPE_DESCRIPTION EXTN_TYPE_DESC,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_EXTENSION_IDENTIFIER CTR_DET_EXTN_ID,
CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE EXTN_TYPE_CD,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_START_DATE EFF_STRT_DT,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_END_DATE EFF_END_DT,
CONTRACT_DETAIL_EXTENSION.EXTENSION_RATE EXTN_RT,
CONTRACT_DETAIL_EXTENSION.Contract_Annual_Payment_Amount CTR_ANL_PYMT_AMT,
CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
CONTRACT_DETAIL_EXTENSION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_DETAIL_EXTENSION.CREATION_DATE CRE_DT,
CONTRACT_DETAIL_EXTENSION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP_SUB_CATEGORY.op,
6 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE ) 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL_EXTENSION 
ON (CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER) 
LEFT JOIN "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE 
ON ( PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID = CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID ) 
LEFT JOIN "fsa-{env}-ccms-cdc".EXTENSION_TYPE 
ON ( EXTENSION_TYPE.EXTENSION_TYPE_CODE = CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE )  
WHERE SIGNUP_SUB_CATEGORY.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
EXTENSION_TYPE.EXTENSION_TYPE_DESCRIPTION EXTN_TYPE_DESC,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_EXTENSION_IDENTIFIER CTR_DET_EXTN_ID,
CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE EXTN_TYPE_CD,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_START_DATE EFF_STRT_DT,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_END_DATE EFF_END_DT,
CONTRACT_DETAIL_EXTENSION.EXTENSION_RATE EXTN_RT,
CONTRACT_DETAIL_EXTENSION.Contract_Annual_Payment_Amount CTR_ANL_PYMT_AMT,
CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
CONTRACT_DETAIL_EXTENSION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_DETAIL_EXTENSION.CREATION_DATE CRE_DT,
CONTRACT_DETAIL_EXTENSION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
PYMT_LMT_TYPE.op,
7 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE 
JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL_EXTENSION 
ON ( PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID = CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID ) 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER) 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE ) 
LEFT JOIN "fsa-{env}-ccms-cdc".EXTENSION_TYPE 
ON ( EXTENSION_TYPE.EXTENSION_TYPE_CODE = CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE )  
WHERE PYMT_LMT_TYPE.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
EXTENSION_TYPE.EXTENSION_TYPE_DESCRIPTION EXTN_TYPE_DESC,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_EXTENSION_IDENTIFIER CTR_DET_EXTN_ID,
CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE EXTN_TYPE_CD,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_START_DATE EFF_STRT_DT,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_END_DATE EFF_END_DT,
CONTRACT_DETAIL_EXTENSION.EXTENSION_RATE EXTN_RT,
CONTRACT_DETAIL_EXTENSION.Contract_Annual_Payment_Amount CTR_ANL_PYMT_AMT,
CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
CONTRACT_DETAIL_EXTENSION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_DETAIL_EXTENSION.CREATION_DATE CRE_DT,
CONTRACT_DETAIL_EXTENSION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
EXTENSION_TYPE.op,
8 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".EXTENSION_TYPE 
JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL_EXTENSION 
ON ( EXTENSION_TYPE.EXTENSION_TYPE_CODE = CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE ) 
LEFT JOIN "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE 
ON ( PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID = CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID ) 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER) 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE ) 
WHERE EXTENSION_TYPE.op <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
  AND CONTRACT_DETAIL_EXTENSION,dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
NULL ADM_ST_FSA_CD,
NULL ADM_CNTY_FSA_CD,
NULL SGNP_TYPE_NM,
NULL SGNP_SUB_CAT_NM,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL CTR_NBR,
NULL CTR_SFX_NBR,
NULL EXTN_TYPE_DESC,
NULL PYMT_LMT_PVSN_CD,
NULL PYMT_LMT_PVSN_CD_YR,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_EXTENSION_IDENTIFIER CTR_DET_EXTN_ID,
CONTRACT_DETAIL_EXTENSION.EXTENSION_TYPE_CODE EXTN_TYPE_CD,
CONTRACT_DETAIL_EXTENSION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_START_DATE EFF_STRT_DT,
CONTRACT_DETAIL_EXTENSION.EFFECTIVE_END_DATE EFF_END_DT,
CONTRACT_DETAIL_EXTENSION.EXTENSION_RATE EXTN_RT,
CONTRACT_DETAIL_EXTENSION.Contract_Annual_Payment_Amount CTR_ANL_PYMT_AMT,
CONTRACT_DETAIL_EXTENSION.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
CONTRACT_DETAIL_EXTENSION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_DETAIL_EXTENSION.CREATION_DATE CRE_DT,
CONTRACT_DETAIL_EXTENSION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_DETAIL_EXTENSION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-ccms-cdc".CONTRACT_DETAIL_EXTENSION
WHERE CONTRACT_DETAIL_EXTENSION.op = 'D'