INSERT into 
EDV.FSA_CNTY_RH
(ST_FSA_CD,
CNTY_FSA_CD,
DATA_SRC_NM,
LOAD_DT)
(
SELECT 
stg.ST_FSA_CD,
stg.CNTY_FSA_CD,
stg.DATA_SRC_NM,
stg.LOAD_DT
from (
SELECT DISTINCT
nvl (TR.LOC_ST_FSA_CD, '--') ST_FSA_CD,
nvl (TR.LOC_CNTY_FSA_CD, '--') CNTY_FSA_CD,
TR.DATA_SRC_NM DATA_SRC_NM,
TR.LOAD_DT LOAD_DT,
ROW_NUMBER () OVER (PARTITION BY TR.LOC_ST_FSA_CD,TR.LOC_CNTY_FSA_CD ORDER BY TR.CDC_DT desc, TR.LOAD_DT desc) STG_EFF_DT_RANK
FROM CARS_STG.TR
) stg 
LEFT JOIN  EDV.FSA_CNTY_RH dv
 on (
stg.ST_FSA_CD = dv.ST_FSA_CD
and stg.CNTY_FSA_CD = dv.CNTY_FSA_CD
)
where
(
dv.ST_FSA_CD IS NULL
OR dv.CNTY_FSA_CD IS NULL
)
and stg.STG_EFF_DT_RANK = 1
)
