SELECT DISTINCT
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
PYMT_LMT_TYPE.AGI_THLD_AMT AGI_THLD_AMT,
PYMT_LMT_TYPE.DATA_STAT_CD DATA_STAT_CD,
PYMT_LMT_TYPE.CRE_DT CRE_DT,
PYMT_LMT_TYPE.CRE_USER_NM CRE_USER_NM,
PYMT_LMT_TYPE.LAST_CHANGE_DATE LAST_CHG_DT,
PYMT_LMT_TYPE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
OP AS CDC_OPER_CD,
1 AS row_num_part
FROM PYMT_LMT_TYPE
WHERE OP <> 'D'
UNION
SELECT DISTINCT
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
PYMT_LMT_TYPE.AGI_THLD_AMT AGI_THLD_AMT,
PYMT_LMT_TYPE.DATA_STAT_CD DATA_STAT_CD,
PYMT_LMT_TYPE.CRE_DT CRE_DT,
PYMT_LMT_TYPE.CRE_USER_NM CRE_USER_NM,
PYMT_LMT_TYPE.LAST_CHANGE_DATE LAST_CHG_DT,
PYMT_LMT_TYPE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM PYMT_LMT_TYPE
WHERE OP = 'D'