-- Julia Lu edition - will update this paragraph and query when (cnsv/ccms)-cdc is ready
-- Stage SQL: CCMS_CTR_RDN (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CCMS_CTR_RDN/incremental/CCMS_CTR_RDN.sql
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT FSCL_YR,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_NM,
SGNP_SUB_CAT_NM,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
CTR_NBR,
CTR_SFX_NBR,
RDN_CD,
CTR_RDN_ID,
CTR_DET_ID,
RDN_AMT,
DATA_STAT_CD,
CRE_DT,
CRE_USER_NM,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CTR_RDN_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
CONTRACT_REDUCTION.FISCAL_YEAR FSCL_YR,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_REDUCTION.REDUCTION_CODE RDN_CD,
CONTRACT_REDUCTION.CONTRACT_REDUCTION_IDENTIFIER CTR_RDN_ID,
CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_REDUCTION.REDUCTION_AMOUNT RDN_AMT,
CONTRACT_REDUCTION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_REDUCTION.CREATION_DATE CRE_DT,
CONTRACT_REDUCTION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_REDUCTION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_REDUCTION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_REDUCTION.op,
1 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".CONTRACT_REDUCTION 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE )  
WHERE CONTRACT_REDUCTION.op <> 'D'

UNION
SELECT 
CONTRACT_REDUCTION.FISCAL_YEAR FSCL_YR,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_REDUCTION.REDUCTION_CODE RDN_CD,
CONTRACT_REDUCTION.CONTRACT_REDUCTION_IDENTIFIER CTR_RDN_ID,
CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_REDUCTION.REDUCTION_AMOUNT RDN_AMT,
CONTRACT_REDUCTION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_REDUCTION.CREATION_DATE CRE_DT,
CONTRACT_REDUCTION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_REDUCTION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_REDUCTION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_DETAIL.op,
2 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
 JOIN "fsa-{env}-ccms-cdc".CONTRACT_REDUCTION 
ON (CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE )  
WHERE CONTRACT_DETAIL.op <> 'D'

UNION
SELECT 
CONTRACT_REDUCTION.FISCAL_YEAR FSCL_YR,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_REDUCTION.REDUCTION_CODE RDN_CD,
CONTRACT_REDUCTION.CONTRACT_REDUCTION_IDENTIFIER CTR_RDN_ID,
CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_REDUCTION.REDUCTION_AMOUNT RDN_AMT,
CONTRACT_REDUCTION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_REDUCTION.CREATION_DATE CRE_DT,
CONTRACT_REDUCTION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_REDUCTION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_REDUCTION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
MASTER_CONTRACT.op,
3 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
 JOIN "fsa-{env}-ccms-cdc".CONTRACT_REDUCTION 
ON (CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE )  
WHERE MASTER_CONTRACT.op <> 'D'

UNION
SELECT 
CONTRACT_REDUCTION.FISCAL_YEAR FSCL_YR,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_REDUCTION.REDUCTION_CODE RDN_CD,
CONTRACT_REDUCTION.CONTRACT_REDUCTION_IDENTIFIER CTR_RDN_ID,
CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_REDUCTION.REDUCTION_AMOUNT RDN_AMT,
CONTRACT_REDUCTION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_REDUCTION.CREATION_DATE CRE_DT,
CONTRACT_REDUCTION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_REDUCTION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_REDUCTION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP.op,
4 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".SIGNUP 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE ) 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
JOIN "fsa-{env}-ccms-cdc".CONTRACT_REDUCTION 
ON (CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  )  
WHERE SIGNUP.op <> 'D'

UNION
SELECT 
CONTRACT_REDUCTION.FISCAL_YEAR FSCL_YR,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_REDUCTION.REDUCTION_CODE RDN_CD,
CONTRACT_REDUCTION.CONTRACT_REDUCTION_IDENTIFIER CTR_RDN_ID,
CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_REDUCTION.REDUCTION_AMOUNT RDN_AMT,
CONTRACT_REDUCTION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_REDUCTION.CREATION_DATE CRE_DT,
CONTRACT_REDUCTION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_REDUCTION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_REDUCTION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP_SUB_CATEGORY.op,
5 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE ) 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
JOIN "fsa-{env}-ccms-cdc".CONTRACT_REDUCTION 
ON (CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER  )  
WHERE SIGNUP_SUB_CATEGORY .op <> 'D'

UNION
SELECT 
CONTRACT_REDUCTION.FISCAL_YEAR FSCL_YR,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_REDUCTION.REDUCTION_CODE RDN_CD,
CONTRACT_REDUCTION.CONTRACT_REDUCTION_IDENTIFIER CTR_RDN_ID,
CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_REDUCTION.REDUCTION_AMOUNT RDN_AMT,
CONTRACT_REDUCTION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_REDUCTION.CREATION_DATE CRE_DT,
CONTRACT_REDUCTION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_REDUCTION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_REDUCTION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP_TYPE.op,
6 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE ) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
ON (SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER  ) 
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER  ) 
JOIN "fsa-{env}-ccms-cdc".CONTRACT_REDUCTION 
ON (CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER  )  
WHERE SIGNUP_TYPE.op <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND CONTRACT_REDUCTION.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
CONTRACT_REDUCTION.FISCAL_YEAR FSCL_YR,
NULL ADM_ST_FSA_CD,
NULL ADM_CNTY_FSA_CD,
NULL SGNP_TYPE_NM,
NULL SGNP_SUB_CAT_NM,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL CTR_NBR,
NULL CTR_SFX_NBR,
CONTRACT_REDUCTION.REDUCTION_CODE RDN_CD,
CONTRACT_REDUCTION.CONTRACT_REDUCTION_IDENTIFIER CTR_RDN_ID,
CONTRACT_REDUCTION.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_REDUCTION.REDUCTION_AMOUNT RDN_AMT,
CONTRACT_REDUCTION.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_REDUCTION.CREATION_DATE CRE_DT,
CONTRACT_REDUCTION.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_REDUCTION.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_REDUCTION.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-ccms-cdc".CONTRACT_REDUCTION
WHERE CONTRACT_REDUCTION.op = 'D'