MERGE into
EDV.FRS_DMN_VAL_RS dv
 using( select distinct
coalesce(DMN_VAL.DMN_CHAR_VAL, '[NULL IN SOURCE]') DMN_CHAR_VAL,
DMN_VAL.CDC_DT DATA_EFF_STRT_DT,
DMN_VAL.DATA_SRC_NM DATA_SRC_NM,
DMN_VAL.DFLT_VAL_IND DFLT_VAL_IND,
DMN_VAL.DMN_ID DMN_ID,
coalesce(coalesce(DMN.DMN_NM, FRS_DMN_RS.DMN_NM),  '[NULL IN SOURCE]') DMN_NM,
DMN_VAL.DMN_VAL_DESC DMN_VAL_DESC,
DMN_VAL.DMN_VAL_ID DMN_VAL_ID,
coalesce(DMN_VAL.DMN_VAL_NM, '[NULL IN SOURCE]') DMN_VAL_NM,
DMN_VAL.DPLY_SEQ_NBR DPLY_SEQ_NBR,
DMN_VAL.LOAD_DT LOAD_DT,
DMN_VAL.CRE_DT SRC_CRE_DT,
DMN_VAL.LAST_CHG_DT SRC_LAST_CHG_DT,
DMN_VAL.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
MD5(trim(both DMN_VAL.DMN_CHAR_VAL)||'~~'||trim(both DMN_VAL.DFLT_VAL_IND)||'~~'||DMN_VAL.DMN_ID||'~~'||trim(both DMN.DMN_NM)||'~~'||trim(both DMN_VAL.DMN_VAL_DESC)||'~~'||DMN_VAL.DMN_VAL_ID||'~~'||trim(both DMN_VAL.DMN_VAL_NM)||'~~'||DMN_VAL.DPLY_SEQ_NBR||'~~'||to_char(DMN_VAL.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(DMN_VAL.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both DMN_VAL.LAST_CHG_USER_NM)) HASH_DIF
FROM SQL_FARM_RCD_STG.DMN_VAL LEFT JOIN SQL_FARM_RCD_STG.DMN ON (DMN.DMN_ID = DMN_VAL.DMN_ID)
LEFT JOIN(select * from EDV.FRS_DMN_RS where data_eff_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') ) FRS_DMN_RS
ON (FRS_DMN_RS.DMN_ID = DMN_VAL.DMN_ID) 
WHERE DMN_VAL.DMN_ID NOT IN (16, 18, 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 33, 35)
and DMN_VAL.cdc_oper_cd = 'D'
order by DMN_VAL.CDC_DT
) stg 
 on ( 
coalesce(stg.DMN_VAL_ID,0) = coalesce(dv.DMN_VAL_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN INSERT(DMN_CHAR_VAL,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DFLT_VAL_IND,
DMN_ID,
DMN_NM,
DMN_VAL_DESC,
DMN_VAL_ID,
DMN_VAL_NM,
DPLY_SEQ_NBR,
LOAD_DT,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM, 
DATA_EFF_END_DT,
LOAD_END_DT,
HASH_DIF
) VALUES (
stg.DMN_CHAR_VAL,
stg.DATA_EFF_STRT_DT,
stg.DATA_SRC_NM,
stg.DFLT_VAL_IND,
stg.DMN_ID,
stg.DMN_NM,
stg.DMN_VAL_DESC,
stg.DMN_VAL_ID,
stg.DMN_VAL_NM,
stg.DPLY_SEQ_NBR,
stg.LOAD_DT,
stg.SRC_CRE_DT,
stg.SRC_LAST_CHG_DT,
stg.SRC_LAST_CHG_USER_NM ,
stg.DATA_EFF_STRT_DT,stg.LOAD_DT,stg.HASH_DIF
);