INSERT into
EDV.LAND_CLS_RH(LAND_CLS_ID,
DATA_SRC_NM,
LOAD_DT)
(
SELECT 
stg.LAND_CLS_ID,
stg.DATA_SRC_NM,
stg.LOAD_DT
from (
SELECT DISTINCT
coalesce(DMN_VAL.DMN_CHAR_VAL, '[NULL IN SOURCE]') LAND_CLS_ID,
DMN_VAL.DATA_SRC_NM DATA_SRC_NM,
DMN_VAL.LOAD_DT LOAD_DT,
ROW_NUMBER() OVER (PARTITION BY DMN_VAL.DMN_CHAR_VAL ORDER BY DMN_VAL.CDC_DT desc, DMN_VAL.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.DMN_VAL
WHERE DMN_VAL.DMN_ID =41
and DMN_VAL.cdc_oper_cd IN ('I','UN','D')
) stg 
LEFT JOIN  EDV.LAND_CLS_RH dv
 ON (
stg.LAND_CLS_ID = dv.LAND_CLS_ID
)
where (
dv.LAND_CLS_ID IS NULL
)
and stg.STG_EFF_DT_RANK = 1
);