SELECT DISTINCT
PROPOSED_PAYMENT_STATUS.PROPOSED_PAYMENT_STATUS_CODE PRPS_PYMT_STAT_CD,
PROPOSED_PAYMENT_STATUS.PROPOSED_PAYMENT_STATUS_DESCRIPTION PRPS_PYMT_STAT_DESC,
OP AS CDC_OPER_CD,
1 AS row_num_part
FROM PROPOSED_PAYMENT_STATUS
WHERE OP <> 'D'
UNION
SELECT DISTINCT
PROPOSED_PAYMENT_STATUS.PROPOSED_PAYMENT_STATUS_CODE PRPS_PYMT_STAT_CD,
PROPOSED_PAYMENT_STATUS.PROPOSED_PAYMENT_STATUS_DESCRIPTION PRPS_PYMT_STAT_DESC,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM PROPOSED_PAYMENT_STATUS
WHERE OP = 'D'