with insert_data as (
select sub1.*
from (
SELECT DISTINCT
DM.HEL_STAT_DURB_ID ,
DM.DATA_EFF_STRT_DT,
DM.HEL_STAT_CD,
DM.HEL_STAT_NM,
DM.HEL_STAT_DESC
FROM (
SELECT 
FRH.DURB_ID AS HEL_STAT_DURB_ID ,
GREATEST(COALESCE(FHS.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD'))) DATA_EFF_STRT_DT,
FHS.FLD_HEL_STAT_CD AS HEL_STAT_CD,
FHS.DMN_VAL_NM AS HEL_STAT_NM,
FHS.DMN_VAL_DESC AS HEL_STAT_DESC,
ROW_NUMBER() OVER ( PARTITION BY COALESCE(FHS.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')), FHS.FLD_HEL_STAT_CD ORDER BY FHS.DATA_EFF_STRT_DT DESC) AS ROW_NUM_PART
FROM EDV.FLD_HEL_STAT_RS FHS
LEFT JOIN  EDV.FLD_HEL_STAT_RH  FRH  ON (COALESCE(FHS.FLD_HEL_STAT_CD,'[NULL IN SOURCE]') = FRH.FLD_HEL_STAT_CD)
WHERE CAST(FHS.DATA_EFF_STRT_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 
AND EXISTS ( SELECT '1' FROM EDV.FLD_HEL_STAT_RS FHS_IN
             WHERE FHS.FLD_HEL_STAT_CD = FHS.FLD_HEL_STAT_CD
              AND CAST(FHS_IN.DATA_EFF_END_DT AS DATE) > TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')) 
AND FRH.DURB_ID IS NOT NULL              
) DM
WHERE DM.ROW_NUM_PART = 1
) sub1
)
select  
		hel_stat_durb_id, 
		'1' as cur_rcd_ind, 
		data_eff_strt_dt, 
		cast('9999-12-31' as DATE) as data_eff_end_dt, 
		(current_date) as cre_dt, 
		hel_stat_cd, 
		hel_stat_nm, 
		hel_stat_desc
from insert_data;