SELECT DISTINCT
ewt12pract.CNSV_PRAC_CD CNSV_PRAC_CD,
ewt12pract.CNSV_PGM_CD CNSV_PGM_CD,
ewt12pract.COST_SHR_ELG_IND COST_SHR_ELG_IND,
ewt12pract.PRAC_MAX_LFSP_CT PRAC_MAX_LFSP_CT,
ewt12pract.PRAC_MIN_LFSP_CT PRAC_MIN_LFSP_CT,
ewt12pract.PRAC_NM PRAC_NM,
ewt12pract.PRAC_STAT_DESC PRAC_STAT_DESC,
ewt12pract.ACRG_EXT_IND ACRG_EXT_IND,
ewt12pract.ACRG_SRV_EXT_IND ACRG_SRV_EXT_IND,
ewt12pract.NBR_EXT_IND NBR_EXT_IND,
ewt12pract.DATA_STAT_CD DATA_STAT_CD,
ewt12pract.CRE_DT CRE_DT,
ewt12pract.LAST_CHG_DT LAST_CHG_DT,
ewt12pract.LAST_CHG_USER_NM LAST_CHG_USER_NM,
--OP AS CDC_OPER_CD,
1 AS row_num_part
FROM ewt12pract
--WHERE OP <> 'D'
UNION
SELECT DISTINCT
ewt12pract.CNSV_PRAC_CD CNSV_PRAC_CD,
ewt12pract.CNSV_PGM_CD CNSV_PGM_CD,
ewt12pract.COST_SHR_ELG_IND COST_SHR_ELG_IND,
ewt12pract.PRAC_MAX_LFSP_CT PRAC_MAX_LFSP_CT,
ewt12pract.PRAC_MIN_LFSP_CT PRAC_MIN_LFSP_CT,
ewt12pract.PRAC_NM PRAC_NM,
ewt12pract.PRAC_STAT_DESC PRAC_STAT_DESC,
ewt12pract.ACRG_EXT_IND ACRG_EXT_IND,
ewt12pract.ACRG_SRV_EXT_IND ACRG_SRV_EXT_IND,
ewt12pract.NBR_EXT_IND NBR_EXT_IND,
ewt12pract.DATA_STAT_CD DATA_STAT_CD,
ewt12pract.CRE_DT CRE_DT,
ewt12pract.LAST_CHG_DT LAST_CHG_DT,
ewt12pract.LAST_CHG_USER_NM LAST_CHG_USER_NM,
--'D' CDC_OPER_CD,
1 AS row_num_part
FROM ewt12pract
--WHERE OP = 'D'