with fld_prdr_fact_temp as 
(
SELECT  DISTINCT CLU_PRDR_L_ID INCR_DR_ID, CLU_PRDR_YR_ID
    FROM        EDV.CLU_PRDR_YR_LS
    WHERE       CAST(DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}', 'YYYY-MM-DD')  
   
   UNION
   
   SELECT  DISTINCT CLS.CLU_PRDR_L_ID INCR_DR_ID, CLS.CLU_PRDR_YR_ID
    FROM   EDV.CLU_PRDR_YR_LS CLS ,    EDV.FLD_CLU_YR_HS FLDS
    WHERE       CAST(FLDS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}', 'YYYY-MM-DD')
    And ( COALESCE(CLS.CLU_YR_ID ,-1)= COALESCE(FLDS.CLU_YR_ID,'-1') )
   
   UNION
   
   SELECT  DISTINCT CLU_PRDR_YR_LS.CLU_PRDR_L_ID INCR_DR_ID, CLU_PRDR_YR_ID
    FROM        EDV.FLD_PRDR_CW_EXCP_RS ,EDV.CLU_PRDR_YR_LS 
    WHERE       (CAST(FLD_PRDR_CW_EXCP_RS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}', 'YYYY-MM-DD')
                ) AND     FLD_PRDR_CW_EXCP_RS.DMN_VAL_ID = CLU_PRDR_YR_LS.SRC_CLU_PRDR_CW_EXCP_CD 
   
   UNION
   
   SELECT  DISTINCT CLU_PRDR_YR_LS.CLU_PRDR_L_ID INCR_DR_ID, CLU_PRDR_YR_ID
    FROM        EDV.FLD_PRDR_PCW_EXCP_RS
                ,EDV.CLU_PRDR_YR_LS
    WHERE       (
                    CAST(FLD_PRDR_PCW_EXCP_RS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}', 'YYYY-MM-DD')
                )    AND     FLD_PRDR_PCW_EXCP_RS.DMN_VAL_ID = CLU_PRDR_YR_LS.SRC_CLU_PRDR_PCW_EXCP_CD
   
   UNION
   
   SELECT  DISTINCT CLU_PRDR_YR_LS.CLU_PRDR_L_ID INCR_DR_ID, CLU_PRDR_YR_ID
    FROM        EDV.FLD_PRDR_HEL_EXCP_RS ,EDV.CLU_PRDR_YR_LS
    WHERE       (
                    CAST(FLD_PRDR_HEL_EXCP_RS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}', 'YYYY-MM-DD')
                )   AND     FLD_PRDR_HEL_EXCP_RS.DMN_VAL_ID = CLU_PRDR_YR_LS.SRC_CLU_PRDR_HEL_EXCP_CD
   
   UNION
   
   SELECT  DISTINCT CLU_PRDR_YR_LS.CLU_PRDR_L_ID INCR_DR_ID, CLU_PRDR_YR_ID
    FROM        EDV.RMA_CW_EXCP_RS  ,EDV.CLU_PRDR_YR_LS
    WHERE       (
                    CAST(RMA_CW_EXCP_RS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}', 'YYYY-MM-DD')
                )   AND     RMA_CW_EXCP_RS.DMN_VAL_ID = CLU_PRDR_YR_LS.CLU_PRDR_RMA_CW_EXCP_CD
    
	UNION
    
	SELECT  DISTINCT CLU_PRDR_YR_LS.CLU_PRDR_L_ID INCR_DR_ID, CLU_PRDR_YR_ID
     FROM        EDV.RMA_HEL_EXCP_RS  ,EDV.CLU_PRDR_YR_LS
    WHERE  (
            CAST(RMA_HEL_EXCP_RS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}', 'YYYY-MM-DD')
           )  AND RMA_HEL_EXCP_RS.DMN_VAL_ID = CLU_PRDR_YR_LS.CLU_PRDR_RMA_HEL_EXCP_CD
    
	UNION
    
	SELECT  DISTINCT CLU_PRDR_YR_LS.CLU_PRDR_L_ID INCR_DR_ID, CLU_PRDR_YR_ID
    FROM  EDV.RMA_PCW_EXCP_RS ,EDV.CLU_PRDR_YR_LS
    WHERE  (
            CAST(RMA_PCW_EXCP_RS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}', 'YYYY-MM-DD')
          )   AND     RMA_PCW_EXCP_RS.DMN_VAL_ID = CLU_PRDR_YR_LS.CLU_PRDR_RMA_PCW_EXCP_CD
)
,del_data as (
select sub_1.*
from (
Select 
DV.CLU_PRDR_YR_ID,
DV.ADM_FSA_ST_CNTY_DURB_ID,
DV.ADM_FSA_ST_CNTY_SRGT_ID,
DV.CUST_DURB_ID,
DV.CUST_SRGT_ID,
DV.FARM_DURB_ID,
DV.FARM_SRGT_ID,
DV.FLD_DURB_ID,
DV.FLD_YR_SRGT_ID,
DV.FLD_PRDR_CW_EXCP_DURB_ID,
DV.FLD_PRDR_HEL_EXCP_DURB_ID,
DV.FLD_PRDR_PCW_EXCP_DURB_ID,
DV.PGM_YR,
DV.PRDR_INVL_DURB_ID,
DV.PRDR_INVL_SRGT_ID,
DV.RMA_FLD_PRDR_CW_EXCP_DURB_ID,
DV.RMA_FLD_PRDR_HEL_EXCP_DURB_ID,
DV.RMA_FLD_PRDR_PCW_EXCP_DURB_ID,
DV.SRC_DATA_STAT_CD,
DV.TR_DURB_ID,
DV.TR_SRGT_ID,
DV.CW_APLS_EXHST_DT,
DV.HEL_APLS_EXHST_DT,
DV.PCW_APLS_EXHST_DT,
BUS_KEY,
CASE    WHEN DV.CUST_DURB_ID IS NOT NULL
    AND DV.FLD_DURB_ID IS NOT NULL
    AND DV.PRDR_INVL_DURB_ID IS NOT NULL
    AND DV.PGM_YR IS NOT NULL
   THEN 0
   ELSE 1 
   END DEF_ERR_IND , 
  ('CUST_DURB_ID:'||DV.CUST_DURB_ID||'~~'||'FLD_DURB_ID:'||DV.FLD_DURB_ID||'~~'||'PRDR_INVL_DURB_ID:'||DV.PRDR_INVL_DURB_ID||'~~'||'PGM_YR:'||DV.PGM_YR ) BUS_KEY_ERR
From (
Select
CLU_PRDR_YR_ID,
ADM_FSA_ST_CNTY_DURB_ID,
ADM_FSA_ST_CNTY_SRGT_ID,
CUST_DURB_ID,
CUST_SRGT_ID,
FARM_DURB_ID,
FARM_SRGT_ID,
FLD_DURB_ID,
FLD_PRDR_CW_EXCP_DURB_ID,
FLD_PRDR_HEL_EXCP_DURB_ID,
FLD_PRDR_PCW_EXCP_DURB_ID,
FLD_YR_SRGT_ID,
PGM_YR,
PRDR_INVL_DURB_ID,
PRDR_INVL_SRGT_ID,
RMA_FLD_PRDR_CW_EXCP_DURB_ID,
RMA_FLD_PRDR_HEL_EXCP_DURB_ID,
RMA_FLD_PRDR_PCW_EXCP_DURB_ID,
SRC_DATA_STAT_CD,
TR_DURB_ID,
TR_SRGT_ID ,
CW_APLS_EXHST_DT,
HEL_APLS_EXHST_DT,
PCW_APLS_EXHST_DT,
md5(CUST_DURB_ID||'~~'||FLD_DURB_ID||'~~'||PRDR_INVL_DURB_ID||'~~'||PGM_YR) BUS_KEY
from (
select CLS.CLU_PRDR_L_ID , 
  COALESCE(CLS.CLU_PRDR_YR_ID,-1) CLU_PRDR_YR_ID,
  COALESCE(CAST(TO_CHAR(CLS.CW_APLS_EXHST_DT,'YYYYMMDD') AS INTEGER),-1) CW_APLS_EXHST_DT,
  COALESCE(CAST(TO_CHAR(CLS.HEL_APLS_EXHST_DT,'YYYYMMDD') AS INTEGER),-1) HEL_APLS_EXHST_DT,
  COALESCE(CAST(TO_CHAR(CLS.PCW_APLS_EXHST_DT,'YYYYMMDD') AS INTEGER ),-1) PCW_APLS_EXHST_DT,
  CLS.PGM_YR,
  CLS.DATA_STAT_CD SRC_DATA_STAT_CD,
  CLS.SRC_LAST_CHG_DT,
  COALESCE(TD.TR_DURB_ID,-3)  TR_DURB_ID,
  COALESCE(TD.TR_SRGT_ID, -3) TR_SRGT_ID ,
  COALESCE(FD.FARM_DURB_ID,-3)  FARM_DURB_ID,
  COALESCE(FD.FARM_SRGT_ID, -3) FARM_SRGT_ID ,
  COALESCE(CCD.CUST_SRGT_ID,-3)  CUST_SRGT_ID,
  COALESCE(CCD.CUST_DURB_ID,-3)  CUST_DURB_ID ,
  COALESCE(FSD_ADM.FSA_ST_CNTY_SRGT_ID,-3) ADM_FSA_ST_CNTY_SRGT_ID,
  COALESCE(FSD_ADM.FSA_ST_CNTY_DURB_ID,-3) ADM_FSA_ST_CNTY_DURB_ID,
  COALESCE(FLD_DM.FLD_YR_SRGT_ID,-3) FLD_YR_SRGT_ID,
  COALESCE(FLD_DM.FLD_DURB_ID,-3) FLD_DURB_ID,
  COALESCE(CWH.DURB_ID,-3) FLD_PRDR_CW_EXCP_DURB_ID,
  COALESCE(HEH.DURB_ID,-3) FLD_PRDR_HEL_EXCP_DURB_ID,
  COALESCE(PEH.DURB_ID,-3) FLD_PRDR_PCW_EXCP_DURB_ID,  
  COALESCE(RCWH.DURB_ID,-3) RMA_FLD_PRDR_CW_EXCP_DURB_ID,
  COALESCE(RHEH.DURB_ID,-3)   RMA_FLD_PRDR_HEL_EXCP_DURB_ID,
  COALESCE(RPEH.DURB_ID,-3)   RMA_FLD_PRDR_PCW_EXCP_DURB_ID,
  COALESCE(PID.PRDR_INVL_DURB_ID,-3) PRDR_INVL_DURB_ID,
  COALESCE(PID.PRDR_INVL_SRGT_ID,-3) PRDR_INVL_SRGT_ID,
  'A' DATA_STAT_CD,
   ROW_NUMBER () OVER (PARTITION BY CCD.CUST_DURB_ID, FLD_DM.FLD_DURB_ID ,PID.PRDR_INVL_DURB_ID , CLS.PGM_YR ORDER BY CLS.SRC_LAST_CHG_DT DESC,
   CASE CLS.DATA_STAT_CD
         WHEN 'A' THEN 1
         WHEN 'I' THEN 2
         WHEN 'D' THEN 3
         ELSE 4
         END ASC,
      CLS.SRC_CRE_DT DESC NULLS LAST
       )  as Rank_Part
FROM    
  ( select * from    EDV.CLU_PRDR_YR_LS  
   WHERE       DATA_STAT_CD = 'A' 
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(data_eff_strt_dt AS DATE)
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') = CAST(data_eff_end_dt AS DATE)                                   
   AND     PGM_YR IS NOT NULL
   And (CLU_PRDR_L_ID, CLU_PRDR_YR_ID) IN ( SELECT INCR_DR_ID, CLU_PRDR_YR_ID FROM  FLD_PRDR_FACT_TEMP )
 ) CLS
LEFT JOIN  EDV.CLU_PRDR_L CL
on (CLS.CLU_PRDR_L_ID = CL.CLU_PRDR_L_ID )
 LEFT JOIN EDV.FARM_H FH ON ( COALESCE(CL.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = FH.FARM_H_ID )
 LEFT JOIN EDV.TR_H TRH ON ( COALESCE(CL.TR_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = TRH.TR_H_ID )
LEFT JOIN EDV.FLD_CLU_YR_HS FLDS
 ON (  COALESCE(CLS.CLU_YR_ID ,-1)= COALESCE(FLDS.CLU_YR_ID,'-1')
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(FLDS.data_eff_strt_dt AS DATE)
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') = CAST(FLDS.data_eff_end_dt AS DATE)
 )
 LEFT JOIN EDV.FLD_H FLH ON ( COALESCE(FLDS.FLD_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = FLH.FLD_H_ID )
  LEFT JOIN CMN_DIM_DM_STG.CUST_DIM CCD
ON  ( COALESCE(CL.CORE_CUST_ID,-1) = COALESCE(CCD.CORE_CUST_ID,-1) 
AND CCD.CUR_RCD_IND = 1   )
LEFT JOIN EDV.FLD_PRDR_INVL_RS PRS ON (CLS.SRC_PRDR_INVL_CD = PRS.DMN_VAL_ID 
 And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(PRS.data_eff_strt_dt AS DATE)
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') = CAST(PRS.data_eff_end_dt AS DATE)) 
LEFT JOIN EBV.PRDR_INVL_RH PLH
ON (COALESCE(PLH.PRDR_INVL_CD ,'[NULL IN SOURCE]')   = COALESCE(PRS.FLD_PRDR_INVL_CD ,'[NULL IN SOURCE]') )
Left join FARM_DM_STG.PRDR_INVL_DIM PID ON (COALESCE(PID.PRDR_INVL_CD,'[NULL IN SOURCE]') = COALESCE(PLH.PRDR_INVL_CD,'[NULL IN SOURCE]') AND PID.CUR_RCD_IND = 1 ) 
LEFT JOIN CMN_DIM_DM_STG.TR_DIM TD
 ON ( TRH.DURB_ID = COALESCE(TD.TR_DURB_ID,-1) AND TD.CUR_RCD_IND = 1 )   
 LEFT JOIN CMN_DIM_DM_STG.FARM_DIM FD ON (COALESCE(FD.FARM_DURB_ID,-1) = FH.DURB_ID AND FD.CUR_RCD_IND = 1)
 LEFT JOIN CMN_DIM_DM_STG.FSA_ST_CNTY_DIM FSD_ADM
     ON  (  COALESCE(FLH.ST_FSA_CD,'-1') = COALESCE(FSD_ADM.ST_FSA_CD,'-1') and COALESCE(FLH.CNTY_FSA_CD,'-1') = COALESCE(FSD_ADM.CNTY_FSA_CD,'-1')
   AND FSD_ADM.CUR_RCD_IND = 1      ) 
   Left join CMN_DIM_DM_STG.FLD_YR_DIM FLD_DM
   ON ( COALESCE(FLD_DM.FLD_DURB_ID,-1) = COALESCE(FLH.DURB_ID,-1)
        AND FLD_DM.PGM_YR =  CLS.PGM_YR
        AND CAST(FLD_DM.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') 
     )
 LEFT JOIN EDV.FLD_PRDR_CW_EXCP_RS CWE ON (CLS.SRC_CLU_PRDR_CW_EXCP_CD = CWE.DMN_VAL_ID 
 And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(CWE.data_eff_strt_dt AS DATE)
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') = CAST(CWE.data_eff_end_dt AS DATE)) 
 LEFT JOIN EDV.FLD_PRDR_CW_EXCP_RH  CWH ON ( COALESCE(CWE.FLD_PRDR_CW_EXCP_CD,'[NULL IN SOURCE]') = CWH.FLD_PRDR_CW_EXCP_CD )
 LEFT JOIN FARM_DM_STG.FLD_PRDR_CW_EXCP_DIM CWD ON ( CWH.DURB_ID = CWD.FLD_PRDR_CW_EXCP_DURB_ID AND CWD.DATA_STAT_CD = 'A')
  LEFT JOIN EDV.FLD_PRDR_HEL_EXCP_RS HES ON (CLS.SRC_CLU_PRDR_HEL_EXCP_CD = HES.DMN_VAL_ID
 And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(HES.data_eff_strt_dt AS DATE)
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') = CAST(HES.data_eff_end_dt AS DATE))               
 LEFT JOIN EDV.FLD_PRDR_HEL_EXCP_RH HEH ON ( COALESCE(HES.FLD_PRDR_HEL_EXCP_CD,'[NULL IN SOURCE]') = HEH.FLD_PRDR_HEL_EXCP_CD)
 LEFT JOIN FARM_DM_STG.FLD_PRDR_HEL_EXCP_DIM HED ON (COALESCE(HED.FLD_PRDR_HEL_EXCP_DURB_ID,-1) = HEH.DURB_ID AND HED.DATA_STAT_CD = 'A' ) 
  LEFT JOIN EDV.FLD_PRDR_PCW_EXCP_RS PES ON (CLS.SRC_CLU_PRDR_PCW_EXCP_CD = PES.DMN_VAL_ID
 And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(PES.data_eff_strt_dt AS DATE)
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') = CAST(PES.data_eff_end_dt AS DATE))               
 LEFT JOIN EDV.FLD_PRDR_PCW_EXCP_RH  PEH ON ( COALESCE(PES.FLD_PRDR_PCW_EXCP_CD,'[NULL IN SOURCE]') = PEH.FLD_PRDR_PCW_EXCP_CD )
 LEFT JOIN FARM_DM_STG.FLD_PRDR_PCW_EXCP_DIM PED ON (PEH.DURB_ID = PED.FLD_PRDR_PCW_EXCP_DURB_ID AND PED.DATA_STAT_CD = 'A' )
 
LEFT JOIN EDV.RMA_CW_EXCP_RS RCWE ON (CLS.CLU_PRDR_RMA_CW_EXCP_CD = RCWE.DMN_VAL_ID 
 And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(RCWE.data_eff_strt_dt AS DATE)
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') = CAST(RCWE.data_eff_end_dt AS DATE))
 LEFT JOIN EDV.RMA_CW_EXCP_RH  RCWH ON ( COALESCE(RCWE.RMA_CW_EXCP_CD,'[NULL IN SOURCE]') = RCWH.RMA_CW_EXCP_CD )
 LEFT JOIN FARM_DM_STG.RMA_FLD_PRDR_CW_EXCP_DIM RCWD ON ( RCWH.DURB_ID = RCWD.RMA_FLD_PRDR_CW_EXCP_DURB_ID AND RCWD.DATA_STAT_CD = 'A') 
 LEFT JOIN EDV.RMA_HEL_EXCP_RS RHES ON (CLS.CLU_PRDR_RMA_HEL_EXCP_CD = RHES.DMN_VAL_ID
 And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(RHES.data_eff_strt_dt AS DATE)
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') = CAST(RHES.data_eff_end_dt AS DATE))     
 LEFT JOIN EDV.RMA_HEL_EXCP_RH RHEH ON ( COALESCE(RHES.RMA_HEL_EXCP_CD,'[NULL IN SOURCE]') = RHEH.RMA_HEL_EXCP_CD)
 LEFT JOIN FARM_DM_STG.RMA_FLD_PRDR_HEL_EXCP_DIM RHED ON (COALESCE(RHED.RMA_FLD_PRDR_HEL_EXCP_DURB_ID,-1) = RHEH.DURB_ID AND RHED.DATA_STAT_CD = 'A' )
 LEFT JOIN EDV.RMA_PCW_EXCP_RS RPES ON (CLS.CLU_PRDR_RMA_PCW_EXCP_CD = RPES.DMN_VAL_ID
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(RPES.data_eff_strt_dt AS DATE)
  And TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') = CAST(RPES.data_eff_end_dt AS DATE))                   
  LEFT JOIN EDV.RMA_PCW_EXCP_RH  RPEH ON ( COALESCE(RPES.RMA_PCW_EXCP_CD,'[NULL IN SOURCE]') = RPEH.RMA_PCW_EXCP_CD )
  LEFT JOIN FARM_DM_STG.RMA_FLD_PRDR_PCW_EXCP_DIM RPED ON (RPEH.DURB_ID = RPED.RMA_FLD_PRDR_PCW_EXCP_DURB_ID AND RPED.DATA_STAT_CD = 'A' )  
  WHERE  CCD.CUST_DURB_ID IS NOT NULL 
  AND CLS.PGM_YR IS NOT NULL
  AND FLD_DM.FLD_DURB_ID IS NOT NULL
  AND PID.PRDR_INVL_DURB_ID IS NOT NULL
 ) sub where Rank_Part = 1 ) DV
 ORDER BY BUS_KEY  asc
) sub_1
)
select 
    (current_date) as cre_dt,
	(current_date) as last_chg_dt, 
    'I' as data_stat_cd, 
	src_data_stat_cd, 
	clu_prdr_yr_id, 
	pgm_yr, 
	adm_fsa_st_cnty_srgt_id, 
	adm_fsa_st_cnty_durb_id, 
	farm_srgt_id, 
	farm_durb_id, 
	tr_srgt_id, 
	tr_durb_id, 
	fld_yr_srgt_id, 
	fld_durb_id, 
	cust_srgt_id, 
	cust_durb_id, 
	prdr_invl_srgt_id, 
	prdr_invl_durb_id, 
	fld_prdr_hel_excp_durb_id, 
	fld_prdr_cw_excp_durb_id, 
	fld_prdr_pcw_excp_durb_id, 
	rma_fld_prdr_hel_excp_durb_id, 
	rma_fld_prdr_cw_excp_durb_id, 
	rma_fld_prdr_pcw_excp_durb_id, 
	hel_apls_exhst_dt, 
	cw_apls_exhst_dt, 
	pcw_apls_exhst_dt
from del_data
where CLU_PRDR_YR_ID > 0
order by CLU_PRDR_YR_ID asc