Select  /*+ parallel (12) */
 DV.PYMT_ATRB_ID,  
 DV.PRPS_PYMT_ID,  
 DV.CMDY_CD , 
 DV.OBL_CNFRM_NBR, 
 DV.OVRRD_SBSD_PRD_STRT_YR, 
 DV.PROC_RQST_REF_NBR, 
 DV.PRPS_PYMT_AMT, 
 DV.PYMT_ATRB_RVRS_DT,
 DV.APP_3_OWNSHP_LVL_LMT_IND,
 DV.HRCH_PYMT_LMT_IND, 
 DV.PRST_OPYMT_ATRB_IND,
 DV.PYMT_LMT_IND,
 DV.AGI_ELG_IND,
 DV.MBR_CTRB_ELG_IND,
 DV.SBST_CHG_ELG_IND,
 DV.PMIT_ENTY_ELG_IND,
 DV.FGN_PRSN_ELG_IND,
 DV.PYMT_LMT_YR,
 DV.RCD_REF_PRIM_ID,
 DV.RCD_REF_SCND_ID,
 DV.SBSD_PRD_STRT_YR,
 DV.NET_PYMT_AMT,
 DV.PYMT_ATRB_AMT,
 DV.RDN_AMT,
 DV.TAX_ID_TYPE_CD,
 DV.BUS_TYPE_CD,
 DV.PYMT_ATRB_BUS_CAT_CD,
 DV.PGM_INELG_RSN_TYPE_CD,
 DV.PYMT_PTY_RLT_CD,
 DV.CASH_RENT_CPLD_FCTR,
 DV.PYMT_ATRB_SHR_PCT,
 DV.CMB_PTY_PYMT_SHR_PCT,
 DV.PAID_PTY_SHR_PCT,
 DV.MBR_SHR_PCT,
 DV.MBR_CTRB_SHR_PCT,
 DV.OWNSHP_HRCH_LVL_SHR_PCT,
 DV.PRPS_PYMT_CRE_DT,
 DV.PRPS_PYMT_LAST_CHG_DT,
 DV.ACCT_PGM_DURB_ID,
 DV.ACCT_REF_PRIM_ID_TYPE_DURB_ID,
 DV.ACCT_REF_SCND_ID_TYPE_DURB_ID,
 DV.FSA_ST_CNTY_DURB_ID,
 DV.FSA_ST_CNTY_SRGT_ID,
 DV.MBR_CUST_DURB_ID,
 DV.MBR_CUST_SRGT_ID,
 DV.PRIM_CUST_DURB_ID,
 DV.PRIM_CUST_SRGT_ID,
 DV.PRNT_MBR_CUST_DURB_ID,
 DV.PRNT_MBR_CUST_SRGT_ID,
 DV.MBR_RPT_FSA_ST_CNTY_SRGT_ID,
 DV.MBR_RPT_FSA_ST_CNTY_DURB_ID,
 DV.LTD_PYMT_PGM_SRGT_ID,
 DV.LTD_PYMT_PGM_DURB_ID,
 DV.PRPS_PYMT_DATA_STAT_CD,
 DV.CRE_DT ,
 DV.LAST_CHG_DT,
 'A' DATA_STAT_CD,
 CASE
   WHEN 
        DV.PYMT_ATRB_ID IS NOT NULL
        AND DV.PRPS_PYMT_ID IS NOT NULL
   THEN 0
   ELSE 1 
   END DEF_ERR_IND,
MD5(DV.PYMT_ATRB_ID||'~~'||DV.PRPS_PYMT_ID) BUS_KEY,
 /*used by DS job to detect multiple BK records (for single AK field, no hashing required) */
 ('PYMT_ATRB_ID:'||DV.PYMT_ATRB_ID||'~~'||'PRPS_PYMT_ID:'||DV.PRPS_PYMT_ID) BUS_KEY_ERR
 From (
 SELECT DV_ALL.* FROM (
     Select  
     DV_DR.PYMT_ATRB_ID,  
     DV_DR.PRPS_PYMT_ID,  
     DIR_ATRB_PRPS_PYMT_LS.CMDY_CD , 
     DIR_ATRB_PRPS_PYMT_LS.OBL_CNFRM_NBR, 
     DIR_ATRB_PRPS_PYMT_LS.OVRRD_SBSD_PRD_STRT_YR, 
     DIR_ATRB_PRPS_PYMT_LS.PROC_RQST_REF_NBR, 
     DIR_ATRB_PRPS_PYMT_LS.PYMT_AMT PRPS_PYMT_AMT, 
     DIR_ATRB_PRPS_PYMT_LS.PYMT_ATRB_RVRS_DT,
     Case UPPER(DIR_ATRB_PRPS_PYMT_LS.APP_3_OWNSHP_LVL_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS APP_3_OWNSHP_LVL_LMT_IND,
     Case  UPPER(DIR_ATRB_PRPS_PYMT_LS.HRCH_PYMT_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS HRCH_PYMT_LMT_IND,
     Case  UPPER(DIR_ATRB_PRPS_PYMT_LS.PRST_OPYMT_ATRB_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS PRST_OPYMT_ATRB_IND,
     Case  UPPER(DIR_ATRB_PRPS_PYMT_LS.PYMT_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS PYMT_LMT_IND,
     Case UPPER(DV_DR.AGI_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS AGI_ELG_IND,
     Case UPPER(DV_DR.MBR_CTRB_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS MBR_CTRB_ELG_IND,
     Case UPPER(DV_DR.SBST_CHG_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS SBST_CHG_ELG_IND,
     Case UPPER(DV_DR.PMIT_ENTY_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS PMIT_ENTY_ELG_IND,
     Case UPPER(DV_DR.FGN_PRSN_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS FGN_PRSN_ELG_IND,
     DIR_ATRB_PRPS_PYMT_LS.PYMT_LMT_YR,
     DIR_ATRB_PRPS_PYMT_LS.RCD_REF_PRIM_ID,
     DIR_ATRB_PRPS_PYMT_LS.RCD_REF_SCND_ID,
     COALESCE(PGM_YR_DIM.PGM_YR,-1) as SBSD_PRD_STRT_YR,
     DIR_ATRB_PRPS_PYMT_LS.DATA_STAT_CD PRPS_PYMT_DATA_STAT_CD,
     PYMT_ATRB.NET_PYMT_AMT,
     PYMT_ATRB.PYMT_ATRB_AMT,
     PYMT_ATRB_RDN.PYMT_ATRB_RDN_AMT RDN_AMT,
     DV_DR.TAX_ID_TYPE_CD,
     DV_DR.BUS_TYPE_CD,
     DV_DR.PYMT_ATRB_BUS_CAT_CD,
     DV_DR.PGM_INELG_RSN_TYPE_CD,
     DV_DR.PYMT_PTY_RLT_CD,
     DV_DR.CASH_RENT_CPLD_FCTR,
     DV_DR.PYMT_ATRB_SHR_PCT,
     DV_DR.CMB_PTY_PYMT_SHR_PCT,
     DV_DR.PAID_PTY_SHR_PCT,
     DV_DR.MBR_SHR_PCT,
     DV_DR.MBR_CTRB_SHR_PCT,
     DV_DR.OWNSHP_HRCH_LVL_SHR_PCT,
     DIR_ATRB_PRPS_PYMT_LS.SRC_CRE_DT PRPS_PYMT_CRE_DT,
     DIR_ATRB_PRPS_PYMT_LS.SRC_LAST_CHG_DT PRPS_PYMT_LAST_CHG_DT,
     COALESCE(ACCT_PGM_DIM.ACCT_PGM_DURB_ID,-3) as ACCT_PGM_DURB_ID,
     COALESCE(ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_TYPE_DURB_ID,-3) as ACCT_REF_PRIM_ID_TYPE_DURB_ID,
     COALESCE(ACCT_REF_TYPE_SCND_DIM.ACCT_REF_TYPE_DURB_ID,-3) as ACCT_REF_SCND_ID_TYPE_DURB_ID,
     COALESCE(FSA_ST_CNTY_DIM.FSA_ST_CNTY_DURB_ID,-3) as FSA_ST_CNTY_DURB_ID,
     COALESCE(FSA_ST_CNTY_DIM.FSA_ST_CNTY_SRGT_ID,-3) AS FSA_ST_CNTY_SRGT_ID,
     COALESCE(MBR_CUST_DM.CUST_DURB_ID,-3) as MBR_CUST_DURB_ID,
     COALESCE(MBR_CUST_DM.CUST_SRGT_ID,-3) as MBR_CUST_SRGT_ID,
     COALESCE(CUST_DIM.CUST_DURB_ID,-3) as PRIM_CUST_DURB_ID,
     COALESCE(CUST_DIM.CUST_SRGT_ID,-3) as PRIM_CUST_SRGT_ID,
     COALESCE(PRNT_MBR_CUST_DM.CUST_DURB_ID,-3) as PRNT_MBR_CUST_DURB_ID,
     COALESCE(PRNT_MBR_CUST_DM.CUST_SRGT_ID,-3) as PRNT_MBR_CUST_SRGT_ID,
     COALESCE(MBR_RPT_FSA_ST_CNTY_DIM.RPT_FSA_ST_CNTY_DURB_ID,-3) as MBR_RPT_FSA_ST_CNTY_DURB_ID,
     COALESCE(MBR_RPT_FSA_ST_CNTY_DIM.RPT_FSA_ST_CNTY_SRGT_ID,-3) as MBR_RPT_FSA_ST_CNTY_SRGT_ID,
     COALESCE(LTD_PYMT_PGM_DIM.LTD_PYMT_PGM_DURB_ID,-3) as LTD_PYMT_PGM_DURB_ID,
     COALESCE(LTD_PYMT_PGM_DIM.LTD_PYMT_PGM_SRGT_ID,-3) as LTD_PYMT_PGM_SRGT_ID,
     TO_TIMESTAMP ('{ETL_START_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF') CRE_DT ,
     TO_TIMESTAMP ('{ETL_START_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF') LAST_CHG_DT,
  RANK() over ( partition by   DV_DR.PYMT_ATRB_ID,   DV_DR.PRPS_PYMT_ID     order by DV_DR.PRPS_PYMT_ID asc,
         CASE DV_DR.DATA_STAT_CD
         WHEN 'A' THEN 1
         WHEN 'I' THEN 2
         WHEN 'D' THEN 3
         ELSE 4
         END ASC,
      DIR_ATRB_PRPS_PYMT_LS.SRC_CRE_DT DESC NULLS LAST
       )  as Rank_Part      
 From  (  
 Select * From (
 SELECT   PYMT_ATRB_UNION.*, ROW_NUMBER () OVER (PARTITION BY PYMT_ATRB_ID,PRPS_PYMT_ID ORDER BY SRC_LAST_CHG_DT DESC) AS PRECEDENCE
  FROM   (SELECT   PYMT_ATRB_ID,PRPS_PYMT_ID,
                   TAX_ID_TYPE_CD,
                   BUS_TYPE_CD,
                   PYMT_ATRB_BUS_CAT_CD,
                   PGM_INELG_RSN_TYPE_CD,
                   PYMT_PTY_RLT_CD,
                   AGI_ELG_IND,
                   MBR_CTRB_ELG_IND,
                   SBST_CHG_ELG_IND,
                   PMIT_ENTY_ELG_IND,
                   FGN_PRSN_ELG_IND,
                   CASH_RENT_CPLD_FCTR,
                   PYMT_ATRB_SHR_PCT,
                   CMB_PTY_PYMT_SHR_PCT,
                   PAID_PTY_SHR_PCT,
                   MBR_SHR_PCT,MBR_CTRB_SHR_PCT,
                   OWNSHP_HRCH_LVL_SHR_PCT,
                   MBR_CORE_CUST_ID,PRNT_PYMT_ATRB_CORE_CUST_ID,
                   SRC_LAST_CHG_DT, DATA_STAT_CD
            FROM   EDV.PYMT_ATRB_MBR_HLS
           WHERE   DATA_STAT_CD <> 'B'
                   AND (DATA_EFF_END_DT) = TO_TIMESTAMP ('9999-12-31', 'YYYY-MM-DD')
                   AND (DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
                   --And PRPS_PYMT_ID in (985150,100000102,16896906,100000275)
          UNION ALL
          SELECT   PYMT_ATRB_ID,PRPS_PYMT_ID,
                   TAX_ID_TYPE_CD,
                   BUS_TYPE_CD,
                   PYMT_ATRB_BUS_CAT_CD,
                   PGM_INELG_RSN_TYPE_CD,
                   PYMT_PTY_RLT_CD,
                   AGI_ELG_IND,
                   MBR_CTRB_ELG_IND,
                   SBST_CHG_ELG_IND,
                   PMIT_ENTY_ELG_IND,
                   FGN_PRSN_ELG_IND,
                   CASH_RENT_CPLD_FCTR,
                   PYMT_ATRB_SHR_PCT,
                   CMB_PTY_PYMT_SHR_PCT,
                   PAID_PTY_SHR_PCT,
                   MBR_SHR_PCT,MBR_CTRB_SHR_PCT,
                   OWNSHP_HRCH_LVL_SHR_PCT,
                   MBR_CORE_CUST_ID,PRNT_PYMT_ATRB_CORE_CUST_ID,
                   SRC_LAST_CHG_DT, DATA_STAT_CD
            FROM   EDV.PR_PYMT_ATRB_MBR_HLS
           WHERE   DATA_STAT_CD <> 'B'
                   AND (DATA_EFF_END_DT) = TO_TIMESTAMP ('9999-12-31', 'YYYY-MM-DD')
                   AND (DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
                  -- And PRPS_PYMT_ID in (985150,100000102,16896906,100000275)
          )  PYMT_ATRB_UNION
    ) as t1 where t1.PRECEDENCE =1
 ) DV_DR
 Join
 (Select * From EDV.DIR_ATRB_PRPS_PYMT_LS  
        where (DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
        AND (DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
        ) DIR_ATRB_PRPS_PYMT_LS
 ON ( DV_DR.PRPS_PYMT_ID = DIR_ATRB_PRPS_PYMT_LS.PRPS_PYMT_ID )
  
 Join 
      (
          Select PYMT_ATRB_ID, PRPS_PYMT_ID, SUM(COALESCE(NET_PYMT_AMT,0)) NET_PYMT_AMT, SUM(COALESCE(PYMT_ATRB_AMT,0)) PYMT_ATRB_AMT  From (
            Select DV2.PYMT_ATRB_ID, DV2.PRPS_PYMT_ID, SUM(COALESCE(DV2.NET_PYMT_AMT,0)) NET_PYMT_AMT ,SUM(COALESCE(PYMT_ATRB_AMT,0)) PYMT_ATRB_AMT  from  EDV.PYMT_ATRB_MBR_HLS DV2 where DV2.DATA_STAT_CD <>'B'
             And (DV2.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') 
             AND (DV2.DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
             Group by DV2.PYMT_ATRB_ID, DV2.PRPS_PYMT_ID
         UNION ALL
            Select DV3.PYMT_ATRB_ID, DV3.PRPS_PYMT_ID, SUM(COALESCE(DV3.NET_PYMT_AMT,0)) NET_PYMT_AMT ,SUM(COALESCE(PYMT_ATRB_AMT,0)) PYMT_ATRB_AMT  from  EDV.PR_PYMT_ATRB_MBR_HLS DV3 where   DV3.DATA_STAT_CD <>'B'
             And (DV3.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') 
             AND (DV3.DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
             Group by DV3.PYMT_ATRB_ID, DV3.PRPS_PYMT_ID
           ) as t2 Group by t2.PYMT_ATRB_ID, t2.PRPS_PYMT_ID
      ) PYMT_ATRB
 On ( DV_DR.PYMT_ATRB_ID = PYMT_ATRB.PYMT_ATRB_ID And DV_DR.PRPS_PYMT_ID = PYMT_ATRB.PRPS_PYMT_ID)
 
 Left Join 
 (
     Select  PYMT_ATRB_ID ,PRPS_PYMT_ID, SUM(COALESCE(PYMT_ATRB_RDN_AMT,0)) PYMT_ATRB_RDN_AMT  From 
     (
            Select DV4.PYMT_ATRB_ID,DV4.PRPS_PYMT_ID, SUM(COALESCE(DV4.PYMT_ATRB_RDN_AMT,0)) PYMT_ATRB_RDN_AMT  from  EDV.PYMT_ATRB_RDN_LS DV4 where DV4.DATA_STAT_CD <>'B'
             And (DV4.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') 
             AND (DV4.DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
             group by DV4.PYMT_ATRB_ID,DV4.PRPS_PYMT_ID
            UNION ALL
            Select DV5.PYMT_ATRB_ID,DV5.PRPS_PYMT_ID, SUM(COALESCE(DV5.PYMT_ATRB_RDN_AMT,0)) PYMT_ATRB_RDN_AMT  from  EDV.PR_PYMT_ATRB_RDN_LS DV5 where   DV5.DATA_STAT_CD <>'B'
             And (DV5.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') 
             AND (DV5.DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
             group by DV5.PYMT_ATRB_ID, DV5.PRPS_PYMT_ID
     ) as t3 group by t3.PYMT_ATRB_ID, t3.PRPS_PYMT_ID
 ) PYMT_ATRB_RDN
 On ( DV_DR.PYMT_ATRB_ID = PYMT_ATRB_RDN.PYMT_ATRB_ID And DV_DR.PRPS_PYMT_ID = PYMT_ATRB_RDN.PRPS_PYMT_ID )
 
  Left Join EDV.PYMT_PGM_RS
   ON ( DIR_ATRB_PRPS_PYMT_LS.PYMT_PGM_ID = PYMT_PGM_RS.PYMT_PGM_ID And  (PYMT_PGM_RS.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )
   
  Left Join PYMT_DM_STG.LTD_PYMT_PGM_DIM
   ON ( PYMT_PGM_RS.PYMT_PGM_NM = LTD_PYMT_PGM_NM And  (LTD_PYMT_PGM_DIM.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )
   
  Left Join CMN_DIM_DM_STG.PGM_YR_DIM
   on ( DIR_ATRB_PRPS_PYMT_LS.SBSD_PRD_STRT_YR = PGM_YR_DIM.PGM_YR And PGM_YR_DIM.DATA_STAT_CD ='A')
 
  
 Left Join CMN_DIM_DM_STG.ACCT_PGM_DIM
 ON  ( DIR_ATRB_PRPS_PYMT_LS.ACCT_PGM_CD = ACCT_PGM_DIM.ACCT_PGM_CD And ACCT_PGM_DIM.DATA_STAT_CD ='A')
 
   
 Left Join PYMT_DM_STG.ACCT_REF_TYPE_DIM  ACCT_REF_TYPE_PRIM_DIM
  ON (DIR_ATRB_PRPS_PYMT_LS.RCD_REF_PRIM_ID_TYPE_CD =ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_CD And ACCT_REF_TYPE_PRIM_DIM.DATA_STAT_CD ='A' And ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_TYPE_DURB_ID > 0 )
  
  
 Left Join PYMT_DM_STG.ACCT_REF_TYPE_DIM  ACCT_REF_TYPE_SCND_DIM
  ON( DIR_ATRB_PRPS_PYMT_LS.RCD_REF_SCND_ID_TYPE_CD =ACCT_REF_TYPE_SCND_DIM.ACCT_REF_CD And ACCT_REF_TYPE_SCND_DIM.DATA_STAT_CD ='A' And ACCT_REF_TYPE_SCND_DIM.ACCT_REF_TYPE_DURB_ID > 0)
  
LEFT  JOIN 
  (
        SELECT FSA_ST_CNTY_SRGT_ID,FSA_ST_CNTY_DURB_ID ,ST_FSA_CD ,CNTY_FSA_CD,ST_NM,CNTY_NM
        ,ROW_NUMBER() OVER ( PARTITION BY ST_FSA_CD  ,CNTY_FSA_CD ORDER BY CRE_DT DESC
        ) AS PRECEDENCE
        FROM CMN_DIM_DM_STG.FSA_ST_CNTY_DIM
        WHERE CUR_RCD_IND = 1
  ) FSA_ST_CNTY_DIM 
ON ( DIR_ATRB_PRPS_PYMT_LS.ST_FSA_CD=FSA_ST_CNTY_DIM.ST_FSA_CD   And DIR_ATRB_PRPS_PYMT_LS.CNTY_FSA_CD = FSA_ST_CNTY_DIM.CNTY_FSA_CD AND FSA_ST_CNTY_DIM.PRECEDENCE = 1 )  
    
  
 Left Join 
   (
           Select * from (
        SELECT FSA_ST_CNTY_SRGT_ID RPT_FSA_ST_CNTY_SRGT_ID ,FSA_ST_CNTY_DURB_ID RPT_FSA_ST_CNTY_DURB_ID ,ST_FSA_CD ,CNTY_FSA_CD,ST_NM,CNTY_NM
        ,ROW_NUMBER() OVER ( PARTITION BY ST_FSA_CD  ,CNTY_FSA_CD ORDER BY CRE_DT DESC) AS PRECEDENCE
        FROM CMN_DIM_DM_STG.FSA_ST_CNTY_DIM
        WHERE CUR_RCD_IND = 1   ) FSA_ST_CNTY_DIM JOIN CMN_DIM_DM_STG.CUST_DIM  
                ON (FSA_ST_CNTY_DIM.ST_FSA_CD = CUST_DIM.RPT_ST_FSA_CD And FSA_ST_CNTY_DIM.CNTY_FSA_CD = CUST_DIM.RPT_CNTY_FSA_CD
                And   (CUST_DIM.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')                 And  FSA_ST_CNTY_DIM.PRECEDENCE=1 
                    )
     ) MBR_RPT_FSA_ST_CNTY_DIM
  On (DV_DR.MBR_CORE_CUST_ID = MBR_RPT_FSA_ST_CNTY_DIM.CORE_CUST_ID) 
 
   Left join CMN_DIM_DM_STG.CUST_DIM 
  On ( DIR_ATRB_PRPS_PYMT_LS.PAID_CORE_CUST_ID = CUST_DIM.CORE_CUST_ID
       And CUST_DIM.CUR_RCD_IND =1 And (CUST_DIM.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') 
        
      ) 
    
  Left join CMN_DIM_DM_STG.CUST_DIM MBR_CUST_DM
  On ( DV_DR.MBR_CORE_CUST_ID = MBR_CUST_DM.CORE_CUST_ID  And MBR_CUST_DM.CUR_RCD_IND =1 And (MBR_CUST_DM.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )
  
    Left join CMN_DIM_DM_STG.CUST_DIM PRNT_MBR_CUST_DM
  On ( DV_DR.PRNT_PYMT_ATRB_CORE_CUST_ID = PRNT_MBR_CUST_DM.CORE_CUST_ID  And PRNT_MBR_CUST_DM.CUR_RCD_IND =1 And (PRNT_MBR_CUST_DM.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )
  
   ) DV_ALL
 WHERE DV_ALL.Rank_Part = 1 
 ) dv 
  
/* LEFT JOIN  PYMT_DM_STG.DA_MBR_CUST_ATRB_FACT dm
 ON (  (dv.PYMT_ATRB_ID,0) = (dm.PYMT_ATRB_ID,0)
       And  (dv.PRPS_PYMT_ID,0) = (dm.PRPS_PYMT_ID,0)
       And dm.DATA_STAT_CD = 'A' 
 ) 
 where
  (
   dm.PYMT_ATRB_ID IS NULL 
   And  dm.PRPS_PYMT_ID IS NULL
 ) */
 ORDER BY BUS_KEY  asc