Merge into
EDV.RCON_CROP_LS dv
using(select DISTINCT MD5(upper(coalesce(trim(both RCON_CROP.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both RCON_CROP.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both RCON_CROP.FSA_CROP_TYPE_CD), '--')) ||'~~'||upper(coalesce(trim(both RCON_CROP.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both RCON_CROP.CNTY_FSA_CD), '--')) ) as RCON_CROP_L_ID,coalesce(RCON_CROP.RCON_CROP_ID, '-1') RCON_CROP_ID,RCON_CROP.LOAD_DT LOAD_DT,RCON_CROP.CDC_DT DATA_EFF_STRT_DT,RCON_CROP.DATA_SRC_NM DATA_SRC_NM,RCON_CROP.DATA_STAT_CD DATA_STAT_CD,RCON_CROP.CRE_DT SRC_CRE_DT,RCON_CROP.LAST_CHG_DT SRC_LAST_CHG_DT,RCON_CROP.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,RCON_CROP.RCON_ID RCON_ID,RCON_CROP.CROP_ID CROP_ID,RCON_CROP.RCON_DIV_MTHD_CD SRC_RCON_DIV_MTHD_CD,DIV_MTHD_TYPE_RS.DMN_VAL_NM RCON_DIV_MTHD_NM ,
RCON_CROP.CDC_OPER_CD,
MD5(trim(both RCON_CROP.PGM_ABR)||'~~'||trim(both RCON_CROP.FSA_CROP_CD)||'~~'||trim(both RCON_CROP.FSA_CROP_TYPE_CD)||'~~'||trim(both RCON_CROP.ST_FSA_CD)||'~~'||trim(both RCON_CROP.CNTY_FSA_CD)||'~~'||RCON_CROP.RCON_CROP_ID||'~~'||trim(both RCON_CROP.DATA_STAT_CD)||'~~'||to_char(RCON_CROP.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(RCON_CROP.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both RCON_CROP.LAST_CHG_USER_NM)||'~~'||RCON_CROP.RCON_ID||'~~'||RCON_CROP.CROP_ID||'~~'||RCON_CROP.RCON_DIV_MTHD_CD||'~~'||trim(both DIV_MTHD_TYPE_RS.DMN_VAL_NM)) HASH_DIF
FROM SQL_FARM_RCD_STG.RCON_CROP 
LEFT JOIN(select * from EDV.DIV_MTHD_TYPE_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) DIV_MTHD_TYPE_RS 
ON ( RCON_CROP.RCON_DIV_MTHD_CD = DIV_MTHD_TYPE_RS.DMN_VAL_ID )
 where RCON_CROP.CDC_OPER_CD IN ('I','UN')
order by RCON_CROP.CDC_DT)
stg
 on ( 
coalesce(stg.RCON_CROP_ID,0) = coalesce(dv.RCON_CROP_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;