SELECT DISTINCT
TH.DURB_ID TR_DURB_ID,
THS.DATA_EFF_END_DT DATA_EFF_END_DT,
0 AS CUR_RCD_IND
FROM EDV.TR_HS THS
JOIN EDV.TR_H TH ON ( TH.TR_H_ID = THS.TR_H_ID)
where (CAST(THS.DATA_EFF_END_DT as DATE) =  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')  
      AND NOT EXISTS ( SELECT '1' FROM EDV.TR_HS THS_IN
                    WHERE THS.TR_ID = THS_IN.TR_ID   
                    AND CAST(THS_IN.DATA_EFF_END_DT as DATE)=  TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')  
                 )) 
 AND TH.DURB_ID  IS NOT NULL;