MERGE INTO EDV.TR_PRDR_YR_LS DV
USING(SELECT DISTINCT MD5(coalesce(TR_PRDR_YR.CORE_CUST_ID,'-1') ||'~~'||MD5(UPPER(coalesce(TR_PRDR_YR.ST_FSA_CD,'--')||'~~'||coalesce(TR_PRDR_YR.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_PRDR_YR.FARM_NBR,'--')))||'~~'||MD5(UPPER(coalesce(TR_PRDR_YR.ST_FSA_CD,'--')||'~~'||coalesce(TR_PRDR_YR.CNTY_FSA_CD,'--')||'~~'||coalesce((TR_PRDR_YR.TR_NBR)::numeric ,-1)))) AS TR_PRDR_L_ID,coalesce(TR_PRDR_YR.TR_PRDR_YR_ID, '-1') TR_PRDR_YR_ID,
TR_PRDR_YR.LOAD_DT LOAD_DT,TR_PRDR_YR.CDC_DT DATA_EFF_STRT_DT,TR_PRDR_YR.DATA_SRC_NM DATA_SRC_NM,TR_PRDR_YR.DATA_STAT_CD DATA_STAT_CD,TR_PRDR_YR.CRE_DT SRC_CRE_DT,TR_PRDR_YR.LAST_CHG_DT SRC_LAST_CHG_DT,TR_PRDR_YR.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_PRDR_YR.CORE_CUST_ID CORE_CUST_ID,TR_PRDR_YR.TR_YR_ID TR_YR_ID,TR_PRDR_YR.PRDR_INVL_CD SRC_PRDR_INVL_CD,PRDR_INVL_RS.DMN_VAL_NM PRDR_INVL_NM,TR_PRDR_YR.PRDR_INVL_STRT_DT PRDR_INVL_STRT_DT,TR_PRDR_YR.PRDR_INVL_END_DT PRDR_INVL_END_DT,TR_PRDR_YR.PRDR_INVL_INTRPT_IND PRDR_INVL_INTRPT_IND,TR_PRDR_YR.TR_PRDR_HEL_EXCP_CD SRC_TR_PRDR_HEL_EXCP_CD,TR_PRDR_HEL_EXCP_RS.DMN_VAL_NM TR_PRDR_HEL_EXCP_NM,TR_PRDR_YR.TR_PRDR_CW_EXCP_CD SRC_TR_PRDR_CW_EXCP_CD,TR_PRDR_CW_EXCP_RS.DMN_VAL_NM TR_PRDR_CW_EXCP_NM,TR_PRDR_YR.TR_PRDR_PCW_EXCP_CD SRC_TR_PRDR_PCW_EXCP_CD,TR_PRDR_PCW_EXCP_RS.DMN_VAL_NM TR_PRDR_PCW_EXCP_NM,TR_PRDR_YR.TM_PRD_ID TM_PRD_ID,TR_PRDR_YR.PGM_YR PGM_YR,TR_PRDR_YR.ST_FSA_CD ST_FSA_CD,TR_PRDR_YR.CNTY_FSA_CD CNTY_FSA_CD,TR_PRDR_YR.FARM_ID FARM_ID,TR_PRDR_YR.FARM_NBR FARM_NBR,TR_PRDR_YR.TR_NBR TR_NBR ,
TR_PRDR_YR.CDC_OPER_CD,
MD5(TR_PRDR_YR.CORE_CUST_ID||'~~'||UPPER(coalesce(TR_PRDR_YR.ST_FSA_CD,'--')||'~~'||coalesce(TR_PRDR_YR.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_PRDR_YR.FARM_NBR,'--'))||'~~'||UPPER(coalesce(TR_PRDR_YR.ST_FSA_CD,'--')||'~~'||coalesce(TR_PRDR_YR.CNTY_FSA_CD,'--')||'~~'||coalesce((TR_PRDR_YR.TR_NBR)::numeric ,-1))||'~~'||TR_PRDR_YR.TR_PRDR_YR_ID||'~~'||trim(both TR_PRDR_YR.DATA_STAT_CD)||'~~'||TO_CHAR(TR_PRDR_YR.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(TR_PRDR_YR.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_PRDR_YR.LAST_CHG_USER_NM)||'~~'||TR_PRDR_YR.CORE_CUST_ID||'~~'||TR_PRDR_YR.TR_YR_ID||'~~'||TR_PRDR_YR.PRDR_INVL_CD||'~~'||trim(both PRDR_INVL_RS.DMN_VAL_NM)||'~~'||TO_CHAR(TR_PRDR_YR.PRDR_INVL_STRT_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(TR_PRDR_YR.PRDR_INVL_END_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_PRDR_YR.PRDR_INVL_INTRPT_IND)||'~~'||TR_PRDR_YR.TR_PRDR_HEL_EXCP_CD||'~~'||trim(both TR_PRDR_HEL_EXCP_RS.DMN_VAL_NM)||'~~'||TR_PRDR_YR.TR_PRDR_CW_EXCP_CD||'~~'||trim(both TR_PRDR_CW_EXCP_RS.DMN_VAL_NM)||'~~'||TR_PRDR_YR.TR_PRDR_PCW_EXCP_CD||'~~'||trim(both TR_PRDR_PCW_EXCP_RS.DMN_VAL_NM)||'~~'||TR_PRDR_YR.TM_PRD_ID||'~~'||TR_PRDR_YR.PGM_YR||'~~'||trim(both TR_PRDR_YR.ST_FSA_CD)||'~~'||trim(both TR_PRDR_YR.CNTY_FSA_CD)||'~~'||TR_PRDR_YR.FARM_ID||'~~'||trim(both TR_PRDR_YR.FARM_NBR)||'~~'||(trim(both TR_PRDR_YR.TR_NBR))::numeric ||'~~'||TO_CHAR(TR_PRDR_YR.HEL_APLS_EXHST_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(TR_PRDR_YR.CW_APLS_EXHST_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(TR_PRDR_YR.PCW_APLS_EXHST_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TR_PRDR_YR.TR_PRDR_RMA_HEL_EXCP_CD||'~~'||TR_PRDR_YR.TR_PRDR_RMA_CW_EXCP_CD||'~~'||TR_PRDR_YR.TR_PRDR_RMA_PCW_EXCP_CD) HASH_DIF,TR_PRDR_YR.HEL_APLS_EXHST_DT,TR_PRDR_YR.CW_APLS_EXHST_DT,TR_PRDR_YR.PCW_APLS_EXHST_DT,TR_PRDR_YR.TR_PRDR_RMA_HEL_EXCP_CD,TR_PRDR_YR.TR_PRDR_RMA_CW_EXCP_CD,TR_PRDR_YR.TR_PRDR_RMA_PCW_EXCP_CD
FROM SQL_FARM_RCD_STG.TR_PRDR_YR
LEFT JOIN(SELECT * FROM EDV.PRDR_INVL_RS
WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) PRDR_INVL_RS 
ON (TR_PRDR_YR.PRDR_INVL_CD=PRDR_INVL_RS.DMN_VAL_ID) 
LEFT JOIN(SELECT * FROM EDV.TR_PRDR_CW_EXCP_RS
WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) TR_PRDR_CW_EXCP_RS 
ON (TR_PRDR_YR.TR_PRDR_CW_EXCP_CD=TR_PRDR_CW_EXCP_RS.DMN_VAL_ID) 
LEFT JOIN(SELECT * FROM EDV.TR_PRDR_HEL_EXCP_RS
WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) TR_PRDR_HEL_EXCP_RS 
ON (TR_PRDR_YR.TR_PRDR_HEL_EXCP_CD=TR_PRDR_HEL_EXCP_RS.DMN_VAL_ID)  
LEFT JOIN(SELECT * FROM EDV.TR_PRDR_PCW_EXCP_RS
WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) TR_PRDR_PCW_EXCP_RS 
ON (TR_PRDR_YR.TR_PRDR_PCW_EXCP_CD=TR_PRDR_PCW_EXCP_RS.DMN_VAL_ID)
 WHERE TR_PRDR_YR.CDC_OPER_CD='D'
--AND date_trunc('day', TR_PRDR_YR.CDC_DT) = date_trunc('day', TO_TIMESTAMP('<DATA_EFF_STRT_DT>', 'YYYY-MM-DD HH24:MI:SS.FF'))
--AND TR_PRDR_YR.LOAD_DT = TO_TIMESTAMP('<LOAD_DT>', 'YYYY-MM-DD HH24:MI:SS.FF')
ORDER BY TR_PRDR_YR.CDC_DT)  STG
 ON ( 
coalesce(STG.TR_PRDR_YR_ID,0) = coalesce(DV.TR_PRDR_YR_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
SET LOAD_END_DT = STG.LOAD_DT,
DATA_EFF_END_DT = STG.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN
INSERT(
TR_PRDR_L_ID,TR_PRDR_YR_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
CORE_CUST_ID,
TR_YR_ID,
SRC_PRDR_INVL_CD,
PRDR_INVL_NM,
PRDR_INVL_STRT_DT,
PRDR_INVL_END_DT,
PRDR_INVL_INTRPT_IND,
SRC_TR_PRDR_HEL_EXCP_CD,
TR_PRDR_HEL_EXCP_NM,
SRC_TR_PRDR_CW_EXCP_CD,
TR_PRDR_CW_EXCP_NM,
SRC_TR_PRDR_PCW_EXCP_CD,
TR_PRDR_PCW_EXCP_NM,
TM_PRD_ID,
PGM_YR,
ST_FSA_CD,
CNTY_FSA_CD,
FARM_ID,
FARM_NBR,
TR_NBR, 
DATA_EFF_END_DT,LOAD_END_DT,HASH_DIF,HEL_APLS_EXHST_DT,CW_APLS_EXHST_DT,PCW_APLS_EXHST_DT,TR_PRDR_RMA_HEL_EXCP_CD,TR_PRDR_RMA_CW_EXCP_CD,TR_PRDR_RMA_PCW_EXCP_CD)
VALUES (
STG.TR_PRDR_L_ID,STG.TR_PRDR_YR_ID,STG.LOAD_DT,STG.DATA_EFF_STRT_DT,STG.DATA_SRC_NM,STG.DATA_STAT_CD,STG.SRC_CRE_DT,STG.SRC_LAST_CHG_DT,STG.SRC_LAST_CHG_USER_NM,STG.CORE_CUST_ID,STG.TR_YR_ID,STG.SRC_PRDR_INVL_CD,STG.PRDR_INVL_NM,STG.PRDR_INVL_STRT_DT,STG.PRDR_INVL_END_DT,STG.PRDR_INVL_INTRPT_IND,STG.SRC_TR_PRDR_HEL_EXCP_CD,STG.TR_PRDR_HEL_EXCP_NM,STG.SRC_TR_PRDR_CW_EXCP_CD,STG.TR_PRDR_CW_EXCP_NM,STG.SRC_TR_PRDR_PCW_EXCP_CD,STG.TR_PRDR_PCW_EXCP_NM,STG.TM_PRD_ID,STG.PGM_YR,STG.ST_FSA_CD,STG.CNTY_FSA_CD,STG.FARM_ID,STG.FARM_NBR,STG.TR_NBR,STG.DATA_EFF_STRT_DT,STG.LOAD_DT,
STG.HASH_DIF,STG.HEL_APLS_EXHST_DT,STG.CW_APLS_EXHST_DT,STG.PCW_APLS_EXHST_DT,STG.TR_PRDR_RMA_HEL_EXCP_CD,STG.TR_PRDR_RMA_CW_EXCP_CD,STG.TR_PRDR_RMA_PCW_EXCP_CD
);