-- Julia Lu edition - will update this paragraph and query when cnsv-cdc is ready
-- Stage SQL: CNSV_EWT85SEBI (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_EWT85SEBI/incremental/CNSV_EWT85SEBI.sql
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT SGNP_NBR,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_STYPE_AGR_NM,
NTL_EBI_NM,
NTL_EBI_FCTR_ID,
NTL_EBI_SFCTR_ID,
EBI_SFCTR_NM,
SGNP_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
-- op,
ROW_NUMBER() over ( partition by 
NTL_EBI_FCTR_ID,
NTL_EBI_SFCTR_ID,
SGNP_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt94nebi.NTL_EBI_NM NTL_EBI_NM,
ewt85sebi.NTL_EBI_FCTR_ID NTL_EBI_FCTR_ID,
ewt85sebi.NTL_EBI_SFCTR_ID NTL_EBI_SFCTR_ID,
ewt85sebi.EBI_SFCTR_NM EBI_SFCTR_NM,
ewt85sebi.SGNP_ID SGNP_ID,
ewt85sebi.DATA_STAT_CD DATA_STAT_CD,
ewt85sebi.CRE_DT CRE_DT,
ewt85sebi.LAST_CHG_DT LAST_CHG_DT,
ewt85sebi.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
1 AS TBL_PRIORITY
FROM "fsa-prod-cnsv".EWT85SEBI 
LEFT JOIN "fsa-prod-cnsv".EWT94NEBI 
     ON (EWT85SEBI.NTL_EBI_FCTR_ID = EWT94NEBI.NTL_EBI_FCTR_ID 
     AND EWT85SEBI.NTL_EBI_SFCTR_ID = EWT94NEBI.NTL_EBI_SFCTR_ID) 
LEFT JOIN "fsa-prod-cnsv".EWT14SGNP 
     ON (EWT85SEBI.SGNP_ID = EWT14SGNP.SGNP_ID)
--WHERE __CDC_OPERATION <> 'D'

UNION
SELECT 
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt94nebi.NTL_EBI_NM NTL_EBI_NM,
ewt85sebi.NTL_EBI_FCTR_ID NTL_EBI_FCTR_ID,
ewt85sebi.NTL_EBI_SFCTR_ID NTL_EBI_SFCTR_ID,
ewt85sebi.EBI_SFCTR_NM EBI_SFCTR_NM,
ewt85sebi.SGNP_ID SGNP_ID,
ewt85sebi.DATA_STAT_CD DATA_STAT_CD,
ewt85sebi.CRE_DT CRE_DT,
ewt85sebi.LAST_CHG_DT LAST_CHG_DT,
ewt85sebi.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
2 AS TBL_PRIORITY
FROM "fsa-prod-cnsv".EWT94NEBI 
   JOIN "fsa-prod-cnsv".EWT85SEBI 
     ON (EWT94NEBI.NTL_EBI_FCTR_ID = EWT85SEBI.NTL_EBI_FCTR_ID AND EWT94NEBI.NTL_EBI_SFCTR_ID = EWT85SEBI.NTL_EBI_SFCTR_ID) 
   LEFT JOIN "fsa-prod-cnsv".EWT14SGNP 
     ON (EWT85SEBI.SGNP_ID = EWT14SGNP.SGNP_ID)
-- WHERE __CDC_OPERATION <> 'D'

UNION
SELECT 
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt94nebi.NTL_EBI_NM NTL_EBI_NM,
ewt85sebi.NTL_EBI_FCTR_ID NTL_EBI_FCTR_ID,
ewt85sebi.NTL_EBI_SFCTR_ID NTL_EBI_SFCTR_ID,
ewt85sebi.EBI_SFCTR_NM EBI_SFCTR_NM,
ewt85sebi.SGNP_ID SGNP_ID,
ewt85sebi.DATA_STAT_CD DATA_STAT_CD,
ewt85sebi.CRE_DT CRE_DT,
ewt85sebi.LAST_CHG_DT LAST_CHG_DT,
ewt85sebi.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
3 AS TBL_PRIORITY
FROM "fsa-prod-cnsv".EWT14SGNP 
   JOIN "fsa-prod-cnsv".EWT85SEBI ON (EWT14SGNP.SGNP_ID = EWT85SEBI.SGNP_ID) 
   LEFT JOIN "fsa-prod-cnsv".EWT94NEBI ON (EWT85SEBI.NTL_EBI_FCTR_ID = EWT94NEBI.NTL_EBI_FCTR_ID 
                           AND EWT85SEBI.NTL_EBI_SFCTR_ID = EWT94NEBI.NTL_EBI_SFCTR_ID)
--WHERE __CDC_OPERATION <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('2025-07-01' AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('2025-07-01' AS DATE))
)

UNION
SELECT DISTINCT
NULL SGNP_NBR,
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_STYPE_AGR_NM,
NULL NTL_EBI_NM,
ewt85sebi.NTL_EBI_FCTR_ID NTL_EBI_FCTR_ID,
ewt85sebi.NTL_EBI_SFCTR_ID NTL_EBI_SFCTR_ID,
ewt85sebi.EBI_SFCTR_NM EBI_SFCTR_NM,
ewt85sebi.SGNP_ID SGNP_ID,
ewt85sebi.DATA_STAT_CD DATA_STAT_CD,
ewt85sebi.CRE_DT CRE_DT,
ewt85sebi.LAST_CHG_DT LAST_CHG_DT,
ewt85sebi.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
1 AS row_num_part
FROM "fsa-prod-cnsv".ewt85sebi
--WHERE __CDC_OPERATION = 'D'
