SELECT DISTINCT
EWT100SOILLANDTYPE.SOIL_GRP_NM SOIL_GRP_NM,
EWT100SOILLANDTYPE.CPLD_IND CPLD_IND,
EWT100SOILLANDTYPE.EXPR_LAND_IND EXPR_LAND_IND,
EWT100SOILLANDTYPE.WBP_NONCROPLAND WBP_NON_CPLD_IND,
EWT100SOILLANDTYPE.LONG_LEAF_PINE_IND LONG_LEAF_PINE_PRAC_IND,
EWT100SOILLANDTYPE.AGGR_LAND_TYPE_IND AGRT_LAND_TYPE_IND,
EWT100SOILLANDTYPE.MULT_SOIL_CALC_CD MULT_SOIL_CALC_CD,
EWT100SOILLANDTYPE.OFR_TYPE_CD OFR_TYPE_CD,
EWT100SOILLANDTYPE.DATA_STAT_CD DATA_STAT_CD,
EWT100SOILLANDTYPE.CRE_DT CRE_DT,
EWT100SOILLANDTYPE.LAST_CHG_DT LAST_CHG_DT,
EWT100SOILLANDTYPE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
--OP AS CDC_OPER_CD,
1 AS row_num_part
FROM EWT100SOILLANDTYPE
--WHERE OP <> 'D'
UNION
SELECT DISTINCT
EWT100SOILLANDTYPE.SOIL_GRP_NM SOIL_GRP_NM,
EWT100SOILLANDTYPE.CPLD_IND CPLD_IND,
EWT100SOILLANDTYPE.EXPR_LAND_IND EXPR_LAND_IND,
EWT100SOILLANDTYPE.WBP_NONCROPLAND WBP_NON_CPLD_IND,
EWT100SOILLANDTYPE.LONG_LEAF_PINE_IND LONG_LEAF_PINE_PRAC_IND,
EWT100SOILLANDTYPE.AGGR_LAND_TYPE_IND AGRT_LAND_TYPE_IND,
EWT100SOILLANDTYPE.MULT_SOIL_CALC_CD MULT_SOIL_CALC_CD,
EWT100SOILLANDTYPE.OFR_TYPE_CD OFR_TYPE_CD,
EWT100SOILLANDTYPE.DATA_STAT_CD DATA_STAT_CD,
EWT100SOILLANDTYPE.CRE_DT CRE_DT,
EWT100SOILLANDTYPE.LAST_CHG_DT LAST_CHG_DT,
EWT100SOILLANDTYPE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
--'D' CDC_OPER_CD,
1 AS row_num_part
FROM EWT100SOILLANDTYPE
--WHERE OP = 'D'