insert into
EDV.FARM_YR_DCP_HS(FARM_H_ID,FARM_YR_DCP_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
FARM_YR_ID,
DCP_DBL_CROP_ACRG,
PGM_YR, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(SELECT stg.* from
(SELECT /*+ parallel (FARM_YR_DCP, 4) */ DISTINCT 
MD5(upper(coalesce(trim(both FARM_YR_DCP.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_DCP.CNTY_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_DCP.FARM_NBR), '--')) ) FARM_H_ID,
FARM_YR_DCP.FARM_YR_DCP_ID FARM_YR_DCP_ID,FARM_YR_DCP.LOAD_DT LOAD_DT,FARM_YR_DCP.CDC_DT DATA_EFF_STRT_DT,FARM_YR_DCP.DATA_SRC_NM DATA_SRC_NM,FARM_YR_DCP.DATA_STAT_CD DATA_STAT_CD,FARM_YR_DCP.CRE_DT SRC_CRE_DT,FARM_YR_DCP.LAST_CHG_DT SRC_LAST_CHG_DT,FARM_YR_DCP.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,FARM_YR_DCP.FARM_YR_ID FARM_YR_ID,FARM_YR_DCP.DCP_DBL_CROP_ACRG DCP_DBL_CROP_ACRG,FARM_YR_DCP.PGM_YR PGM_YR ,
to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(trim(both FARM_YR_DCP.ST_FSA_CD)||'~~'||trim(both FARM_YR_DCP.CNTY_FSA_CD)||'~~'||trim(both FARM_YR_DCP.FARM_NBR)||'~~'||FARM_YR_DCP.FARM_YR_DCP_ID||'~~'||trim(both FARM_YR_DCP.DATA_STAT_CD)||'~~'||to_char(FARM_YR_DCP.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(FARM_YR_DCP.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both FARM_YR_DCP.LAST_CHG_USER_NM)||'~~'||FARM_YR_DCP.FARM_YR_ID||'~~'||FARM_YR_DCP.DCP_DBL_CROP_ACRG||'~~'||FARM_YR_DCP.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.FARM_YR_DCP  FARM_YR_DCP
 where FARM_YR_DCP.CDC_OPER_CD IN ('I','UN')
And MD5(upper(coalesce(trim(both FARM_YR_DCP.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_DCP.CNTY_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_DCP.FARM_NBR), '--')) )
IN (Select FARM_H_ID from EDV.FARM_H)

UNION

SELECT /*+ parallel (FARM_YR_DCP, 4) */ DISTINCT 
MD5(('--')||'~~'||('--')||'~~'||('--')) FARM_H_ID,
FARM_YR_DCP.FARM_YR_DCP_ID FARM_YR_DCP_ID,FARM_YR_DCP.LOAD_DT LOAD_DT,FARM_YR_DCP.CDC_DT DATA_EFF_STRT_DT,FARM_YR_DCP.DATA_SRC_NM DATA_SRC_NM,FARM_YR_DCP.DATA_STAT_CD DATA_STAT_CD,FARM_YR_DCP.CRE_DT SRC_CRE_DT,FARM_YR_DCP.LAST_CHG_DT SRC_LAST_CHG_DT,FARM_YR_DCP.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,FARM_YR_DCP.FARM_YR_ID FARM_YR_ID,FARM_YR_DCP.DCP_DBL_CROP_ACRG DCP_DBL_CROP_ACRG,FARM_YR_DCP.PGM_YR PGM_YR ,
to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(trim(both FARM_YR_DCP.ST_FSA_CD)||'~~'||trim(both FARM_YR_DCP.CNTY_FSA_CD)||'~~'||trim(both FARM_YR_DCP.FARM_NBR)||'~~'||FARM_YR_DCP.FARM_YR_DCP_ID||'~~'||trim(both FARM_YR_DCP.DATA_STAT_CD)||'~~'||to_char(FARM_YR_DCP.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(FARM_YR_DCP.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both FARM_YR_DCP.LAST_CHG_USER_NM)||'~~'||FARM_YR_DCP.FARM_YR_ID||'~~'||FARM_YR_DCP.DCP_DBL_CROP_ACRG||'~~'||FARM_YR_DCP.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.FARM_YR_DCP  FARM_YR_DCP
 where FARM_YR_DCP.CDC_OPER_CD IN ('I','UN')
And MD5(upper(coalesce(trim(both FARM_YR_DCP.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_DCP.CNTY_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_DCP.FARM_NBR), '--')) )
Not IN (Select FARM_H_ID from EDV.FARM_H)
) stg
 LEFT JOIN  EDV.FARM_YR_DCP_HS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.FARM_YR_DCP_HS hs
                where stg.FARM_H_ID = hs.FARM_H_ID
				and stg.FARM_YR_DCP_ID = hs.FARM_YR_DCP_ID
				and stg.LOAD_DT = hs.LOAD_DT
			  )
)
;