Merge into
EDV.FARM_YR_DCP_HS dv
using(select DISTINCT 
MD5(upper(coalesce(trim(both FARM_YR_DCP.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_DCP.CNTY_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_DCP.FARM_NBR), '--')) ) FARM_H_ID,
FARM_YR_DCP.FARM_YR_DCP_ID FARM_YR_DCP_ID,FARM_YR_DCP.LOAD_DT LOAD_DT,FARM_YR_DCP.CDC_DT DATA_EFF_STRT_DT,FARM_YR_DCP.DATA_SRC_NM DATA_SRC_NM,FARM_YR_DCP.DATA_STAT_CD DATA_STAT_CD,FARM_YR_DCP.CRE_DT SRC_CRE_DT,FARM_YR_DCP.LAST_CHG_DT SRC_LAST_CHG_DT,FARM_YR_DCP.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,FARM_YR_DCP.FARM_YR_ID FARM_YR_ID,FARM_YR_DCP.DCP_DBL_CROP_ACRG DCP_DBL_CROP_ACRG,FARM_YR_DCP.PGM_YR PGM_YR ,
FARM_YR_DCP.CDC_OPER_CD,
MD5(trim(both FARM_YR_DCP.ST_FSA_CD)||'~~'||trim(both FARM_YR_DCP.CNTY_FSA_CD)||'~~'||trim(both FARM_YR_DCP.FARM_NBR)||'~~'||FARM_YR_DCP.FARM_YR_DCP_ID||'~~'||trim(both FARM_YR_DCP.DATA_STAT_CD)||'~~'||to_char(FARM_YR_DCP.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(FARM_YR_DCP.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both FARM_YR_DCP.LAST_CHG_USER_NM)||'~~'||FARM_YR_DCP.FARM_YR_ID||'~~'||FARM_YR_DCP.DCP_DBL_CROP_ACRG||'~~'||FARM_YR_DCP.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.FARM_YR_DCP  FARM_YR_DCP
 where FARM_YR_DCP.CDC_OPER_CD='D'
order by FARM_YR_DCP.CDC_DT)
stg
 on ( 
coalesce(stg.FARM_YR_DCP_ID,0) = coalesce(dv.FARM_YR_DCP_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN
INSERT(
FARM_H_ID,FARM_YR_DCP_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
FARM_YR_ID,
DCP_DBL_CROP_ACRG,
PGM_YR, 
DATA_EFF_END_DT,LOAD_END_DT,HASH_DIF)
VALUES (
stg.FARM_H_ID,stg.FARM_YR_DCP_ID,stg.LOAD_DT,stg.DATA_EFF_STRT_DT,stg.DATA_SRC_NM,stg.DATA_STAT_CD,stg.SRC_CRE_DT,stg.SRC_LAST_CHG_DT,stg.SRC_LAST_CHG_USER_NM,stg.FARM_YR_ID,stg.DCP_DBL_CROP_ACRG,stg.PGM_YR,stg.DATA_EFF_STRT_DT,stg.LOAD_DT,
stg.HASH_DIF
)
;