SELECT SUB_CAT_CPNT_ID,
CPNT_SUB_CAT_ID,
CPNT_ID,
CPNT_CD,
CPNT_SUB_CAT_CD,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT SUB_CAT_CPNT_ID,
CPNT_SUB_CAT_ID,
CPNT_ID,
CPNT_CD,
CPNT_SUB_CAT_CD,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
SUB_CAT_CPNT_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
SUB_CATEGORY_COMPONENT.SUB_CAT_CPNT_ID SUB_CAT_CPNT_ID,
SUB_CATEGORY_COMPONENT.CPNT_SUB_CAT_ID CPNT_SUB_CAT_ID,
SUB_CATEGORY_COMPONENT.CPNT_ID CPNT_ID,
COMPONENT.CPNT_CD CPNT_CD,
COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_CD CPNT_SUB_CAT_CD,
SUB_CATEGORY_COMPONENT.DATA_STAT_CD DATA_STAT_CD,
SUB_CATEGORY_COMPONENT.CRE_DT CRE_DT,
SUB_CATEGORY_COMPONENT.LAST_CHG_DT LAST_CHG_DT,
SUB_CATEGORY_COMPONENT.LAST_CHG_USER_NM LAST_CHG_USER_NM,
SUB_CATEGORY_COMPONENT.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."SUB_CATEGORY_COMPONENT" SUB_CATEGORY_COMPONENT
LEFT JOIN "fsa-{env}-cnsv".COMPONENT
ON (SUB_CATEGORY_COMPONENT.CPNT_ID = COMPONENT.CPNT_ID)
LEFT JOIN "fsa-{env}-cnsv".COMPONENT_SUB_CATEGORY
ON (COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_ID = SUB_CATEGORY_COMPONENT.CPNT_SUB_CAT_ID)  
WHERE SUB_CATEGORY_COMPONENT.OP <> 'D' AND
SUB_CATEGORY_COMPONENT.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
SUB_CATEGORY_COMPONENT.SUB_CAT_CPNT_ID SUB_CAT_CPNT_ID,
SUB_CATEGORY_COMPONENT.CPNT_SUB_CAT_ID CPNT_SUB_CAT_ID,
SUB_CATEGORY_COMPONENT.CPNT_ID CPNT_ID,
COMPONENT.CPNT_CD CPNT_CD,
COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_CD CPNT_SUB_CAT_CD,
SUB_CATEGORY_COMPONENT.DATA_STAT_CD DATA_STAT_CD,
SUB_CATEGORY_COMPONENT.CRE_DT CRE_DT,
SUB_CATEGORY_COMPONENT.LAST_CHG_DT LAST_CHG_DT,
SUB_CATEGORY_COMPONENT.LAST_CHG_USER_NM LAST_CHG_USER_NM,
COMPONENT.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."COMPONENT" COMPONENT
JOIN "fsa-{env}-cnsv".SUB_CATEGORY_COMPONENT
ON (SUB_CATEGORY_COMPONENT.CPNT_ID = COMPONENT.CPNT_ID)
LEFT JOIN "fsa-{env}-cnsv".COMPONENT_SUB_CATEGORY
ON (COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_ID = SUB_CATEGORY_COMPONENT.CPNT_SUB_CAT_ID)  
WHERE COMPONENT.OP <> 'D' AND
COMPONENT.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
SUB_CATEGORY_COMPONENT.SUB_CAT_CPNT_ID SUB_CAT_CPNT_ID,
SUB_CATEGORY_COMPONENT.CPNT_SUB_CAT_ID CPNT_SUB_CAT_ID,
SUB_CATEGORY_COMPONENT.CPNT_ID CPNT_ID,
COMPONENT.CPNT_CD CPNT_CD,
COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_CD CPNT_SUB_CAT_CD,
SUB_CATEGORY_COMPONENT.DATA_STAT_CD DATA_STAT_CD,
SUB_CATEGORY_COMPONENT.CRE_DT CRE_DT,
SUB_CATEGORY_COMPONENT.LAST_CHG_DT LAST_CHG_DT,
SUB_CATEGORY_COMPONENT.LAST_CHG_USER_NM LAST_CHG_USER_NM,
COMPONENT_SUB_CATEGORY.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."COMPONENT_SUB_CATEGORY" COMPONENT_SUB_CATEGORY
JOIN "fsa-{env}-cnsv".SUB_CATEGORY_COMPONENT
ON (COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_ID = SUB_CATEGORY_COMPONENT.CPNT_SUB_CAT_ID)
LEFT JOIN "fsa-{env}-cnsv".COMPONENT
ON (SUB_CATEGORY_COMPONENT.CPNT_ID = COMPONENT.CPNT_ID)  
WHERE COMPONENT_SUB_CATEGORY.OP <> 'D' AND
COMPONENT_SUB_CATEGORY.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
SUB_CATEGORY_COMPONENT.SUB_CAT_CPNT_ID SUB_CAT_CPNT_ID,
SUB_CATEGORY_COMPONENT.CPNT_SUB_CAT_ID CPNT_SUB_CAT_ID,
SUB_CATEGORY_COMPONENT.CPNT_ID CPNT_ID,
NULL CPNT_CD,
NULL CPNT_SUB_CAT_CD,
SUB_CATEGORY_COMPONENT.DATA_STAT_CD DATA_STAT_CD,
SUB_CATEGORY_COMPONENT.CRE_DT CRE_DT,
SUB_CATEGORY_COMPONENT.LAST_CHG_DT LAST_CHG_DT,
SUB_CATEGORY_COMPONENT.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".SUB_CATEGORY_COMPONENT SUB_CATEGORY_COMPONENT
WHERE OP = 'D'
AND dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}' 
)