WITH TAB_INCR_DR_ID AS
(

SELECT  DISTINCT FARM_PRDR_L_ID INCR_DR_ID, PGM_YR 
FROM EDV.FARM_PRDR_YR_LS
WHERE  CAST(DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 

UNION

SELECT  DISTINCT  FARM_PRDR_YR_LS.FARM_PRDR_L_ID INCR_DR_ID, PGM_YR
FROM EDV.LOC_AREA_MRT_SRC_RS, EDV.FARM_PRDR_YR_LS
WHERE (
       CAST(LOC_AREA_MRT_SRC_RS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 
      )
AND LOC_AREA_MRT_SRC_RS.CTRY_DIV_MRT_CD = FARM_PRDR_YR_LS.ST_FSA_CD
AND LOC_AREA_MRT_SRC_RS.LOC_AREA_MRT_CD = FARM_PRDR_YR_LS.CNTY_FSA_CD
AND LOC_AREA_MRT_SRC_RS.LOC_AREA_MRT_CD_SRC_ACRO = 'FSA'

UNION

SELECT DISTINCT  FARM_PRDR_YR_LS.FARM_PRDR_L_ID INCR_DR_ID, PGM_YR
FROM EDV.FARM_PRDR_CW_EXCP_RS, EDV.FARM_PRDR_YR_LS
WHERE (CAST(FARM_PRDR_CW_EXCP_RS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 
      )  
AND FARM_PRDR_CW_EXCP_RS.DMN_VAL_ID= FARM_PRDR_YR_LS.SRC_FARM_PRDR_CW_EXCP_CD 

UNION

SELECT DISTINCT  FARM_PRDR_YR_LS.FARM_PRDR_L_ID INCR_DR_ID, PGM_YR
FROM EDV.FARM_PRDR_PCW_EXCP_RS, EDV.FARM_PRDR_YR_LS
WHERE (CAST(FARM_PRDR_PCW_EXCP_RS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 
      )  
AND FARM_PRDR_PCW_EXCP_RS.DMN_VAL_ID= FARM_PRDR_YR_LS.SRC_FARM_PRDR_PCW_EXCP_CD 

UNION

SELECT DISTINCT  FARM_PRDR_YR_LS.FARM_PRDR_L_ID INCR_DR_ID, PGM_YR
FROM EDV.FARM_PRDR_HEL_EXCP_RS, EDV.FARM_PRDR_YR_LS
WHERE (CAST(FARM_PRDR_HEL_EXCP_RS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD'))
AND FARM_PRDR_HEL_EXCP_RS.DMN_VAL_ID= FARM_PRDR_YR_LS.SRC_FARM_PRDR_HEL_EXCP_CD 
)
SELECT
(CURRENT_DATE) AS CRE_DT,
(CURRENT_DATE) AS LAST_CHG_DT, 
'I' AS DATA_STAT_CD,
DM.PGM_YR,
DM.ADM_FSA_ST_CNTY_SRGT_ID,
DM.ADM_FSA_ST_CNTY_DURB_ID,
DM.FARM_SRGT_ID,
DM.FARM_DURB_ID,
DM.OPER_CUST_SRGT_ID,
DM.OPER_CUST_DURB_ID,
DM.FARM_PRDR_HEL_EXCP_DURB_ID,
DM.FARM_PRDR_CW_EXCP_DURB_ID,
DM.FARM_PRDR_PCW_EXCP_DURB_ID,
DM.FARM_OPER_CRE_DT,
DM.FARM_OPER_LAST_CHG_DT,
DM.FARM_OPER_LAST_CHG_USER_NM,
DM.SRC_DATA_STAT_CD,
DM.PRDR_INVL_INTRPT_IND,
DM.PRDR_INVL_STRT_DT,
DM.PRDR_INVL_END_DT,
DM.DATA_EFF_STRT_DT,
DM.RMA_FARM_PRDR_HEL_EXCP_DURB_ID,
DM.RMA_FARM_PRDR_CW_EXCP_DURB_ID,
DM.RMA_FARM_PRDR_PCW_EXCP_DURB_ID,
DM.CW_APL_EXHST_DT,
DM.HEL_APL_EXHST_DT,
DM.PCW_APL_EXHST_DT
FROM 
(SELECT 

DM_1.PGM_YR,
DM_1.ADM_FSA_ST_CNTY_SRGT_ID,
DM_1.ADM_FSA_ST_CNTY_DURB_ID,
DM_1.FARM_SRGT_ID,
DM_1.FARM_DURB_ID,
DM_1.OPER_CUST_SRGT_ID,
DM_1.OPER_CUST_DURB_ID,
DM_1.FARM_PRDR_HEL_EXCP_DURB_ID,
DM_1.FARM_PRDR_CW_EXCP_DURB_ID,
DM_1.FARM_PRDR_PCW_EXCP_DURB_ID,
DM_1.FARM_OPER_CRE_DT,
DM_1.FARM_OPER_LAST_CHG_DT,
DM_1.FARM_OPER_LAST_CHG_USER_NM,
DM_1.SRC_DATA_STAT_CD,
DM_1.PRDR_INVL_INTRPT_IND,
DM_1.PRDR_INVL_STRT_DT,
DM_1.PRDR_INVL_END_DT,
DM_1.DATA_EFF_STRT_DT,

DM_1.FS_DATA_EFF_STRT_DT,
DM_1.FS_DATA_EFF_END_DT,
DM_1.LAS_ADM_DATA_EFF_STRT_DT,
DM_1.CWE_DATA_EFF_STRT_DT,
DM_1.HES_DATA_EFF_STRT_DT,
DM_1.PES_DATA_EFF_STRT_DT,
DM_1.RMA_FARM_PRDR_HEL_EXCP_DURB_ID,
DM_1.RMA_FARM_PRDR_CW_EXCP_DURB_ID,
DM_1.RMA_FARM_PRDR_PCW_EXCP_DURB_ID,
DM_1.CW_APL_EXHST_DT,
DM_1.HEL_APL_EXHST_DT,
DM_1.PCW_APL_EXHST_DT,
   ROW_NUMBER() OVER ( PARTITION BY 
    DM_1.FARM_DURB_ID,
    DM_1.PGM_YR,
    DM_1.OPER_CUST_DURB_ID
    ORDER BY 
      FS_DATA_EFF_STRT_DT DESC,
      LAS_ADM_DATA_EFF_STRT_DT DESC, 
      CWE_DATA_EFF_STRT_DT DESC,
      HES_DATA_EFF_STRT_DT DESC,
      PES_DATA_EFF_STRT_DT DESC
        )  AS ROW_NUM_PART
FROM (
SELECT
PGM_YR,
ADM_FSA_ST_CNTY_SRGT_ID,
ADM_FSA_ST_CNTY_DURB_ID,
FARM_SRGT_ID,
FARM_DURB_ID,
OPER_CUST_SRGT_ID,
OPER_CUST_DURB_ID,
FARM_PRDR_HEL_EXCP_DURB_ID,
FARM_PRDR_CW_EXCP_DURB_ID,
FARM_PRDR_PCW_EXCP_DURB_ID,
FARM_OPER_CRE_DT,
FARM_OPER_LAST_CHG_DT,
FARM_OPER_LAST_CHG_USER_NM,
SRC_DATA_STAT_CD,
PRDR_INVL_INTRPT_IND,
PRDR_INVL_STRT_DT,
PRDR_INVL_END_DT,
DATA_EFF_STRT_DT,
FS_DATA_EFF_STRT_DT,
FS_DATA_EFF_END_DT,
LAS_ADM_DATA_EFF_STRT_DT,
CWE_DATA_EFF_STRT_DT,
HES_DATA_EFF_STRT_DT,
PES_DATA_EFF_STRT_DT,
RMA_FARM_PRDR_HEL_EXCP_DURB_ID,
RMA_FARM_PRDR_CW_EXCP_DURB_ID,
RMA_FARM_PRDR_PCW_EXCP_DURB_ID,
CW_APL_EXHST_DT,
HEL_APL_EXHST_DT,
PCW_APL_EXHST_DT
FROM (
SELECT * FROM (
SELECT   
 DISTINCT 
 ROW_NUMBER () OVER (PARTITION BY FS.FARM_PRDR_L_ID , FS.PGM_YR ORDER BY FS.DATA_EFF_STRT_DT DESC, FS.DATA_STAT_CD, FS.FARM_PRDR_YR_ID DESC) AS SRC_RANK,
FS.FARM_PRDR_L_ID FARM_PRDR_L_ID,
FS.PGM_YR  PGM_YR,
COALESCE(FSD_ADM.FSA_ST_CNTY_SRGT_ID,-3) ADM_FSA_ST_CNTY_SRGT_ID,
COALESCE(FSD_ADM.FSA_ST_CNTY_DURB_ID,-3) ADM_FSA_ST_CNTY_DURB_ID,
COALESCE(FD.FARM_SRGT_ID,-3)   FARM_SRGT_ID,
FD.FARM_DURB_ID FARM_DURB_ID,
COALESCE(CCD.CUST_SRGT_ID,-3)   OPER_CUST_SRGT_ID,
CCD.CUST_DURB_ID   OPER_CUST_DURB_ID,
COALESCE(HED.FARM_PRDR_HEL_EXCP_DURB_ID,-3)   FARM_PRDR_HEL_EXCP_DURB_ID,
COALESCE(RHED.RMA_FARM_PRDR_HEL_EXCP_DURB_ID,-3)   RMA_FARM_PRDR_HEL_EXCP_DURB_ID,
COALESCE(CWD.FARM_PRDR_CW_EXCP_DURB_ID,-3) FARM_PRDR_CW_EXCP_DURB_ID,
COALESCE(RCWD.RMA_FARM_PRDR_CW_EXCP_DURB_ID,-3) RMA_FARM_PRDR_CW_EXCP_DURB_ID,
COALESCE(PED.FARM_PRDR_PCW_EXCP_DURB_ID,-3)   FARM_PRDR_PCW_EXCP_DURB_ID,
COALESCE(RPED.RMA_FARM_PRDR_PCW_EXCP_DURB_ID,-3)   RMA_FARM_PRDR_PCW_EXCP_DURB_ID,
FS.SRC_CRE_DT  FARM_OPER_CRE_DT,
FS.SRC_LAST_CHG_DT    FARM_OPER_LAST_CHG_DT,
FS.SRC_LAST_CHG_USER_NM  FARM_OPER_LAST_CHG_USER_NM,
FS.DATA_STAT_CD  SRC_DATA_STAT_CD,
FS.PRDR_INVL_INTRPT_IND PRDR_INVL_INTRPT_IND,
FS.PRDR_INVL_STRT_DT  PRDR_INVL_STRT_DT,
FS.PRDR_INVL_END_DT PRDR_INVL_END_DT,
COALESCE(CAST(TO_CHAR(FS.CW_APLS_EXHST_DT,'YYYYMMDD') as INTEGER),-1) CW_APL_EXHST_DT,
COALESCE(cast(TO_CHAR(FS.HEL_APLS_EXHST_DT,'YYYYMMDD') as INTEGER ),-1) HEL_APL_EXHST_DT,
COALESCE(CAST(TO_CHAR(FS.PCW_APLS_EXHST_DT,'YYYYMMDD') as INTEGER ),-1) PCW_APL_EXHST_DT,
GREATEST(COALESCE(FS.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),COALESCE(LAS_ADM.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),
COALESCE(CWE.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),COALESCE(HES.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),
COALESCE(PES.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD'))) DATA_EFF_STRT_DT,
FS.DATA_EFF_STRT_DT FS_DATA_EFF_STRT_DT,
FS.DATA_EFF_END_DT FS_DATA_EFF_END_DT,
LAS_ADM.DATA_EFF_STRT_DT LAS_ADM_DATA_EFF_STRT_DT,
CWE.DATA_EFF_STRT_DT CWE_DATA_EFF_STRT_DT,
HES.DATA_EFF_STRT_DT HES_DATA_EFF_STRT_DT,
PES.DATA_EFF_STRT_DT PES_DATA_EFF_STRT_DT
 FROM EDV.FARM_PRDR_YR_LS FS
 LEFT JOIN EDV.FARM_PRDR_L FL ON (FL.FARM_PRDR_L_ID = COALESCE(FS.FARM_PRDR_L_ID,'6bb61e3b7bce0931da574d19d1d82c88') )
 LEFT JOIN EDV.LOC_AREA_MRT_SRC_RS LAS_ADM ON (FS.ST_FSA_CD = LAS_ADM.CTRY_DIV_MRT_CD
    AND FS.CNTY_FSA_CD = LAS_ADM.LOC_AREA_MRT_CD 
    AND LAS_ADM.LOC_AREA_MRT_CD_SRC_ACRO = 'FSA' )
 LEFT JOIN EDV.LOC_AREA_RH LAH_ADM ON  ( COALESCE(LAS_ADM.LOC_AREA_CAT_NM,'[NULL IN SOURCE]') = LAH_ADM.LOC_AREA_CAT_NM 
    AND COALESCE(LAS_ADM.LOC_AREA_NM,'[NULL IN SOURCE]') = LAH_ADM.LOC_AREA_NM 
    AND COALESCE(LAS_ADM.CTRY_DIV_NM,'[NULL IN SOURCE]') = LAH_ADM.CTRY_DIV_NM )
 LEFT JOIN CMN_DIM_DM_STG.FSA_ST_CNTY_DIM FSD_ADM ON (LAH_ADM.DURB_ID = COALESCE(FSD_ADM.FSA_ST_CNTY_DURB_ID,-1)
                          AND FSD_ADM.CUR_RCD_IND = 1 )
 LEFT JOIN EDV.FARM_PRDR_CW_EXCP_RS CWE ON (FS.SRC_FARM_PRDR_CW_EXCP_CD = CWE.DMN_VAL_ID )
 LEFT JOIN EDV.FARM_PRDR_CW_EXCP_RH  CWH ON ( COALESCE(CWE.FARM_PRDR_CW_EXCP_CD,'[NULL IN SOURCE]') = CWH.FARM_PRDR_CW_EXCP_CD )
 LEFT JOIN FARM_DM_STG.FARM_PRDR_CW_EXCP_DIM CWD ON ( CWH.DURB_ID = CWD.FARM_PRDR_CW_EXCP_DURB_ID AND CWD.DATA_STAT_CD= 'A')  
 LEFT JOIN EDV.FARM_H FH ON ( COALESCE(FL.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = FH.FARM_H_ID )
 LEFT JOIN CMN_DIM_DM_STG.FARM_DIM FD ON (COALESCE(FD.FARM_DURB_ID,-1) = FH.DURB_ID AND FD.CUR_RCD_IND = 1)
 LEFT JOIN EDV.FARM_PRDR_HEL_EXCP_RS HES ON (FS.SRC_FARM_PRDR_HEL_EXCP_CD = HES.DMN_VAL_ID)
 LEFT JOIN EDV.FARM_PRDR_HEL_EXCP_RH HEH ON ( COALESCE(HES.FARM_PRDR_HEL_EXCP_CD,'[NULL IN SOURCE]') = HEH.FARM_PRDR_HEL_EXCP_CD)
 LEFT JOIN FARM_DM_STG.FARM_PRDR_HEL_EXCP_DIM HED ON (COALESCE(HED.FARM_PRDR_HEL_EXCP_DURB_ID,-1) = HEH.DURB_ID AND HED.DATA_STAT_CD ='A') 
 LEFT JOIN EDV.CORE_CUST_H CCH ON ( COALESCE(FS.CORE_CUST_ID,-1) =  CCH.CORE_CUST_ID )
 LEFT JOIN  CMN_DIM_DM_STG.CUST_DIM CCD ON (CCH.DURB_ID = COALESCE(CCD.CUST_DURB_ID,-1)  AND CCD.CUR_RCD_IND = 1)
 LEFT JOIN EDV.FARM_PRDR_PCW_EXCP_RS PES ON (FS.SRC_FARM_PRDR_PCW_EXCP_CD = PES.DMN_VAL_ID)
 LEFT JOIN EDV.FARM_PRDR_PCW_EXCP_RH  PEH ON ( COALESCE(PES.FARM_PRDR_PCW_EXCP_CD,'[NULL IN SOURCE]') = PEH.FARM_PRDR_PCW_EXCP_CD )
 LEFT JOIN FARM_DM_STG.FARM_PRDR_PCW_EXCP_DIM PED ON (PEH.DURB_ID = PED.FARM_PRDR_PCW_EXCP_DURB_ID AND PED.DATA_STAT_CD= 'A' )  
 
LEFT JOIN EDV.RMA_CW_EXCP_RS RCWE ON (FS.FARM_PRDR_RMA_CW_EXCP_CD = RCWE.DMN_VAL_ID 
 AND CAST(RCWE.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') )
 LEFT JOIN EDV.RMA_CW_EXCP_RH  RCWH ON ( COALESCE(RCWE.RMA_CW_EXCP_CD,'[NULL IN SOURCE]') = RCWH.RMA_CW_EXCP_CD )
 LEFT JOIN FARM_DM_STG.RMA_FARM_PRDR_CW_EXCP_DIM RCWD ON ( RCWH.DURB_ID = RCWD.RMA_FARM_PRDR_CW_EXCP_DURB_ID AND RCWD.DATA_STAT_CD = 'A') 
LEFT JOIN EDV.RMA_HEL_EXCP_RS RHES ON (FS.FARM_PRDR_RMA_HEL_EXCP_CD = RHES.DMN_VAL_ID
 AND CAST(RHES.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') )     
 LEFT JOIN EDV.RMA_HEL_EXCP_RH RHEH ON ( COALESCE(RHES.RMA_HEL_EXCP_CD,'[NULL IN SOURCE]') = RHEH.RMA_HEL_EXCP_CD)
 LEFT JOIN FARM_DM_STG.RMA_FARM_PRDR_HEL_EXCP_DIM RHED ON (COALESCE(RHED.RMA_FARM_PRDR_HEL_EXCP_DURB_ID,-1) = RHEH.DURB_ID AND RHED.DATA_STAT_CD = 'A' )
LEFT JOIN EDV.RMA_PCW_EXCP_RS RPES ON (FS.FARM_PRDR_RMA_PCW_EXCP_CD = RPES.DMN_VAL_ID
  AND CAST(RPES.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') )                   
LEFT JOIN EDV.RMA_PCW_EXCP_RH  RPEH ON ( COALESCE(RPES.RMA_PCW_EXCP_CD,'[NULL IN SOURCE]') = RPEH.RMA_PCW_EXCP_CD )
LEFT JOIN FARM_DM_STG.RMA_FARM_PRDR_PCW_EXCP_DIM RPED ON (RPEH.DURB_ID = RPED.RMA_FARM_PRDR_PCW_EXCP_DURB_ID AND RPED.DATA_STAT_CD = 'A' ) 
 WHERE  (FS.FARM_PRDR_L_ID, FS.PGM_YR) IN (SELECT INCR_DR_ID, PGM_YR FROM TAB_INCR_DR_ID)
 AND FS.PGM_YR IS NOT NULL
 AND FD.FARM_DURB_ID IS NOT NULL
 AND CCD.CUST_DURB_ID IS NOT NULL
 AND CAST(FS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
 AND NOT EXISTS (SELECT '1' FROM EDV.FARM_PRDR_YR_LS FS_INN
                 WHERE FS.FARM_PRDR_L_ID = FS_INN.FARM_PRDR_L_ID
                 AND FS.PGM_YR = FS_INN.PGM_YR
                 AND CAST(FS_INN.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
                 AND FS_INN.DATA_STAT_CD IN ('A')
                ) 
	) sub
	WHERE SRC_RANK = 1 ) sub_1 
	) DM_1
WHERE CAST(COALESCE(FS_DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) AS DATE) <=  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
AND CAST(COALESCE(LAS_ADM_DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) AS DATE) <=  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
AND CAST(COALESCE(CWE_DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) AS DATE) <=  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
AND CAST(COALESCE(HES_DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) AS DATE) <=  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
AND CAST(COALESCE(PES_DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) AS DATE) <=  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
) DM
WHERE DM.ROW_NUM_PART = 1
order by DM.PGM_YR,DM.FARM_DURB_ID,DM.OPER_CUST_DURB_ID
