SELECT cre_dt, 
last_chg_dt, 
data_stat_cd, 
pgm_yr, 
adm_fsa_st_cnty_srgt_id, 
adm_fsa_st_cnty_durb_id, 
farm_srgt_id, 
farm_durb_id, 
oper_cust_srgt_id, 
oper_cust_durb_id, 
farm_prdr_hel_excp_durb_id, 
farm_prdr_cw_excp_durb_id, 
farm_prdr_pcw_excp_durb_id, 
farm_oper_cre_dt, 
farm_oper_last_chg_dt, 
farm_oper_last_chg_user_nm, 
src_data_stat_cd, 
prdr_invl_intrpt_ind, 
prdr_invl_strt_dt, 
prdr_invl_end_dt, 
rma_farm_prdr_hel_excp_durb_id, 
rma_farm_prdr_cw_excp_durb_id, 
rma_farm_prdr_pcw_excp_durb_id, 
hel_apl_exhst_dt, 
cw_apl_exhst_dt, 
pcw_apl_exhst_dt
FROM farm_dm_stg.farm_oper_fact
WHERE farm_durb_id > 0
order by farm_durb_id asc