MERGE  INTO EDV.FARM_PRDR_YR_LS DV
USING(
SELECT sub1.*
FROM
(	
	SELECT sub.*,
		   ROW_NUMBER() OVER (PARTITION BY FARM_PRDR_L_ID, FARM_PRDR_YR_ID ORDER BY LOAD_DT desc) FARM_PRDR_L_ID_RANK
	FROM
	(
		SELECT DISTINCT
		MD5(MD5(UPPER(coalesce(FARM_PRDR_YR.ST_FSA_CD,'--')||'~~'||coalesce(FARM_PRDR_YR.CNTY_FSA_CD,'--')||'~~'||coalesce(FARM_PRDR_YR.FARM_NBR ,'--'))) ||'~~'||coalesce(FARM_PRDR_YR.CORE_CUST_ID, '-1')) AS FARM_PRDR_L_ID
		,coalesce(FARM_PRDR_YR.FARM_PRDR_YR_ID, '-1') FARM_PRDR_YR_ID
		,FARM_PRDR_YR.LOAD_DT LOAD_DT
		,FARM_PRDR_YR.CDC_DT DATA_EFF_STRT_DT
		,FARM_PRDR_YR.DATA_SRC_NM DATA_SRC_NM
		,FARM_PRDR_YR.DATA_STAT_CD DATA_STAT_CD
		,FARM_PRDR_YR.CRE_DT SRC_CRE_DT
		,FARM_PRDR_YR.LAST_CHG_DT SRC_LAST_CHG_DT
		,FARM_PRDR_YR.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
		,FARM_PRDR_YR.CORE_CUST_ID CORE_CUST_ID
		,FARM_PRDR_YR.FARM_YR_ID FARM_YR_ID
		,FARM_PRDR_YR.PRDR_INVL_CD SRC_PRDR_INVL_CD
		,PIRS.DMN_VAL_NM PRDR_INVL_NM
		,FARM_PRDR_YR.PRDR_INVL_INTRPT_IND PRDR_INVL_INTRPT_IND
		,FARM_PRDR_YR.PRDR_INVL_STRT_DT PRDR_INVL_STRT_DT
		,FARM_PRDR_YR.PRDR_INVL_END_DT PRDR_INVL_END_DT
		,FARM_PRDR_YR.FARM_PRDR_HEL_EXCP_CD SRC_FARM_PRDR_HEL_EXCP_CD
		,FPHERS.DMN_VAL_NM FARM_PRDR_HEL_EXCP_NM
		,FARM_PRDR_YR.FARM_PRDR_CW_EXCP_CD SRC_FARM_PRDR_CW_EXCP_CD
		,FPCERS.DMN_VAL_NM FARM_PRDR_CW_EXCP_NM
		,FARM_PRDR_YR.FARM_PRDR_PCW_EXCP_CD SRC_FARM_PRDR_PCW_EXCP_CD
		,FPPERS.DMN_VAL_NM FARM_PRDR_PCW_EXCP_NM
		,FARM_PRDR_YR.TM_PRD_ID TM_PRD_ID
		,FARM_PRDR_YR.PGM_YR PGM_YR
		,FARM_PRDR_YR.ST_FSA_CD ST_FSA_CD
		,FARM_PRDR_YR.CNTY_FSA_CD CNTY_FSA_CD
		,FARM_PRDR_YR.FARM_ID FARM_ID
		,FARM_PRDR_YR.FARM_NBR FARM_NBR
		,FARM_PRDR_YR.HEL_APLS_EXHST_DT
		,FARM_PRDR_YR.CW_APLS_EXHST_DT
		,FARM_PRDR_YR.PCW_APLS_EXHST_DT
		,FARM_PRDR_YR.FARM_PRDR_RMA_HEL_EXCP_CD
		,FARM_PRDR_YR.FARM_PRDR_RMA_CW_EXCP_CD
		,FARM_PRDR_YR.FARM_PRDR_RMA_PCW_EXCP_CD
		,FARM_PRDR_YR.CDC_OPER_CD
		,MD5(UPPER(coalesce(FARM_PRDR_YR.ST_FSA_CD ,'--')||'~~'||coalesce(FARM_PRDR_YR.CNTY_FSA_CD,'--')||'~~'||coalesce(FARM_PRDR_YR.FARM_NBR ,'--'))||'~~'||FARM_PRDR_YR.CORE_CUST_ID||'~~'||FARM_PRDR_YR.FARM_PRDR_YR_ID||'~~'||trim(both FARM_PRDR_YR.DATA_STAT_CD)||'~~'||TO_CHAR(FARM_PRDR_YR.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(FARM_PRDR_YR.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both FARM_PRDR_YR.LAST_CHG_USER_NM)||'~~'||FARM_PRDR_YR.FARM_YR_ID||'~~'||FARM_PRDR_YR.PRDR_INVL_CD||'~~'||trim(both PIRS.DMN_VAL_NM)||'~~'||trim(both FARM_PRDR_YR.PRDR_INVL_INTRPT_IND)||'~~'||TO_CHAR(FARM_PRDR_YR.PRDR_INVL_STRT_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(FARM_PRDR_YR.PRDR_INVL_END_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||FARM_PRDR_YR.FARM_PRDR_HEL_EXCP_CD||'~~'||trim(both FPHERS.DMN_VAL_NM)||'~~'||FARM_PRDR_YR.FARM_PRDR_CW_EXCP_CD||'~~'||trim(both FPCERS.DMN_VAL_NM)||'~~'||FARM_PRDR_YR.FARM_PRDR_PCW_EXCP_CD||'~~'||trim(both FPPERS.DMN_VAL_NM)||'~~'||FARM_PRDR_YR.TM_PRD_ID||'~~'||FARM_PRDR_YR.PGM_YR||'~~'||trim(both FARM_PRDR_YR.ST_FSA_CD)||'~~'||trim(both FARM_PRDR_YR.CNTY_FSA_CD)||'~~'||FARM_PRDR_YR.FARM_ID||'~~'||trim(both FARM_PRDR_YR.FARM_NBR) || '~~' ||TO_CHAR(FARM_PRDR_YR.HEL_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US') || '~~' ||TO_CHAR(FARM_PRDR_YR.CW_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US') || '~~' || TO_CHAR(FARM_PRDR_YR.PCW_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US') || '~~' || FARM_PRDR_YR.FARM_PRDR_RMA_HEL_EXCP_CD || '~~' || FARM_PRDR_YR.FARM_PRDR_RMA_CW_EXCP_CD || '~~' || FARM_PRDR_YR.FARM_PRDR_RMA_PCW_EXCP_CD) HASH_DIF
		FROM SQL_FARM_RCD_STG.FARM_PRDR_YR 
		LEFT JOIN(SELECT * FROM EDV.FARM_PRDR_CW_EXCP_RS WHERE LOAD_END_DT=TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FPCERS
		ON (FARM_PRDR_YR.FARM_PRDR_CW_EXCP_CD=FPCERS.DMN_VAL_ID)
		LEFT JOIN(SELECT * FROM EDV.FARM_PRDR_HEL_EXCP_RS WHERE LOAD_END_DT=TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FPHERS
		ON (FARM_PRDR_YR.FARM_PRDR_HEL_EXCP_CD=FPHERS.DMN_VAL_ID)
		LEFT JOIN(SELECT * FROM EDV.FARM_PRDR_PCW_EXCP_RS WHERE LOAD_END_DT=TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FPPERS
		ON (FARM_PRDR_YR.FARM_PRDR_PCW_EXCP_CD=FPPERS.DMN_VAL_ID)
		LEFT JOIN(SELECT * FROM EDV.PRDR_INVL_RS WHERE LOAD_END_DT=TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) PIRS
		ON (FARM_PRDR_YR.PRDR_INVL_CD=PIRS.DMN_VAL_ID)
		WHERE FARM_PRDR_YR.CDC_OPER_CD IN ('I','UN')
		ORDER BY FARM_PRDR_YR.CDC_DT
	) sub
) sub1
WHERE sub1.FARM_PRDR_L_ID_RANK = 1
) STG ON (coalesce(STG.FARM_PRDR_YR_ID,0)=coalesce(DV.FARM_PRDR_YR_ID,0))
WHEN MATCHED and DV.LOAD_DT <> STG.LOAD_DT and DV.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and STG.HASH_DIF <> DV.HASH_DIF THEN UPDATE
    SET         LOAD_END_DT = STG.LOAD_DT,
                DATA_EFF_END_DT = STG.DATA_EFF_STRT_DT
;