INSERT into
EDV.FRS_DMN_VAL_RH(DMN_NM,
DMN_VAL_NM,
DATA_SRC_NM,
LOAD_DT)
(
SELECT 
stg.DMN_NM,
stg.DMN_VAL_NM,
stg.DATA_SRC_NM,
stg.LOAD_DT
from (
SELECT DISTINCT
COALESCE(DMN.DMN_NM, FRS_DMN_RS.DMN_NM, '[NULL IN SOURCE]') DMN_NM, /*Added New function here and in partition by clause to avoid data miss-matches 
Manokarthik Malineni 2/15/2019*/
coalesce(DMN_VAL.DMN_VAL_NM, '[NULL IN SOURCE]') DMN_VAL_NM,
DMN_VAL.DATA_SRC_NM DATA_SRC_NM,
DMN_VAL.LOAD_DT LOAD_DT,
ROW_NUMBER() OVER (PARTITION BY COALESCE(DMN.DMN_NM, FRS_DMN_RS.DMN_NM, '[NULL IN SOURCE]'), coalesce(DMN_VAL.DMN_VAL_NM, '[NULL IN SOURCE]') ORDER BY DMN_VAL.CDC_DT desc, DMN_VAL.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.DMN_VAL LEFT JOIN SQL_FARM_RCD_STG.DMN ON (DMN.DMN_ID = DMN_VAL.DMN_ID)
LEFT JOIN(select * from EDV.FRS_DMN_RS where data_eff_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') ) FRS_DMN_RS
ON (FRS_DMN_RS.DMN_ID = DMN_VAL.DMN_ID) 
WHERE DMN_VAL.DMN_ID NOT IN (16, 18, 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 33, 35)
and DMN_VAL.cdc_oper_cd IN ('I','UN','D')
) stg 
LEFT JOIN  EDV.FRS_DMN_VAL_RH dv
 ON (
stg.DMN_NM = dv.DMN_NM
and stg.DMN_VAL_NM = dv.DMN_VAL_NM
)
where (
dv.DMN_NM IS NULL
OR dv.DMN_VAL_NM IS NULL
)
and stg.STG_EFF_DT_RANK = 1
);