-- Julia Lu edition - will update this paragraph and query when cnsv-cdc is ready
-- Stage SQL: CNSV_EWT86SHLOC (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_EWT86SHLOC/incremental/CNSV_EWT86SHLOC.sql
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT SGNP_NBR,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_STYPE_AGR_NM,
ST_FIPS_CD,
CNTY_FIPS_CD,
NTL_HUC_CD,
SGNP_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
-- op,
ROW_NUMBER() over ( partition by 
ST_FIPS_CD,
CNTY_FIPS_CD,
NTL_HUC_CD,
SGNP_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt86shloc.ST_FIPS_CD ST_FIPS_CD,
ewt86shloc.CNTY_FIPS_CD CNTY_FIPS_CD,
ewt86shloc.NTL_HUC_CD NTL_HUC_CD,
ewt86shloc.SGNP_ID SGNP_ID,
ewt86shloc.DATA_STAT_CD DATA_STAT_CD,
ewt86shloc.CRE_DT CRE_DT,
ewt86shloc.LAST_CHG_DT LAST_CHG_DT,
ewt86shloc.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
1 AS TBL_PRIORITY
FROM "fsa-prod-cnsv".EWT86SHLOC 
LEFT JOIN "fsa-prod-cnsv".EWT14SGNP ON (EWT86SHLOC.SGNP_ID = EWT14SGNP.SGNP_ID)

UNION
SELECT 
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt86shloc.ST_FIPS_CD ST_FIPS_CD,
ewt86shloc.CNTY_FIPS_CD CNTY_FIPS_CD,
ewt86shloc.NTL_HUC_CD NTL_HUC_CD,
ewt86shloc.SGNP_ID SGNP_ID,
ewt86shloc.DATA_STAT_CD DATA_STAT_CD,
ewt86shloc.CRE_DT CRE_DT,
ewt86shloc.LAST_CHG_DT LAST_CHG_DT,
ewt86shloc.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
2 AS TBL_PRIORITY
FROM "fsa-prod-cnsv".EWT14SGNP 
JOIN "fsa-prod-cnsv".EWT86SHLOC ON (EWT14SGNP.SGNP_ID = EWT86SHLOC.SGNP_ID)
-- WHERE __CDC_OPERATION <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('2025-07-01' AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('2025-07-01' AS DATE))
)

UNION
SELECT DISTINCT
NULL SGNP_NBR,
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_STYPE_AGR_NM,
ewt86shloc.ST_FIPS_CD ST_FIPS_CD,
ewt86shloc.CNTY_FIPS_CD CNTY_FIPS_CD,
ewt86shloc.NTL_HUC_CD NTL_HUC_CD,
ewt86shloc.SGNP_ID SGNP_ID,
ewt86shloc.DATA_STAT_CD DATA_STAT_CD,
ewt86shloc.CRE_DT CRE_DT,
ewt86shloc.LAST_CHG_DT LAST_CHG_DT,
ewt86shloc.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
1 AS row_num_part
FROM "fsa-prod-cnsv".ewt86shloc
-- WHERE __CDC_OPERATION = 'D'