INSERT into
EDV.CROP_FARM_YR_ADJ_ARC_PLC_HS(
	FARM_H_ID
	, CROP_FARM_YR_MNG_VAL_ADJ_ID
	, YR_ARC_PLC_PTCP_ELCT_ID
	, LOAD_DT
	, DATA_EFF_STRT_DT
	, DATA_SRC_NM
	, DATA_STAT_CD
	, SRC_CRE_DT
	, SRC_CRE_USER_NM
	, SRC_LAST_CHG_DT
	, SRC_LAST_CHG_USER_NM
	, SRC_CROP_FARM_YR_ADJ_TYPE_CD
	, CROP_FARM_YR_ADJ_TYPE_NM
	, SRC_CROP_FARM_YR_ADJ_RSN_CD
	, AFT_ADJ_VAL
	, BEF_ADJ_VAL
	, PGM_YR
	, DATA_EFF_END_DT
	, LOAD_END_DT
	, HASH_DIF
)
(
SELECT 
	stg.* 
	from (
		SELECT DISTINCT 
			MD5(upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.FARM_NBR), '--')) ) as FARM_H_ID
			, CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_ID CROP_FARM_YR_MNG_VAL_ADJ_ID
			, coalesce(CROP_FARM_YR_MNG_VAL_ADJ.YR_ARC_PLC_PTCP_ELCT_ID::numeric, -1) YR_ARC_PLC_PTCP_ELCT_ID
			, CROP_FARM_YR_MNG_VAL_ADJ.LOAD_DT LOAD_DT
			, CROP_FARM_YR_MNG_VAL_ADJ.CDC_DT DATA_EFF_STRT_DT
			, CROP_FARM_YR_MNG_VAL_ADJ.DATA_SRC_NM DATA_SRC_NM
			, CROP_FARM_YR_MNG_VAL_ADJ.DATA_STAT_CD DATA_STAT_CD
			, CROP_FARM_YR_MNG_VAL_ADJ.CRE_DT SRC_CRE_DT
			, CROP_FARM_YR_MNG_VAL_ADJ.CRE_USER_NM SRC_CRE_USER_NM
			, CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_DT SRC_LAST_CHG_DT
			, CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
			, CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY SRC_CROP_FARM_YR_ADJ_TYPE_CD
			, FARM_CROP_ADJ_TYPE_RS.DMN_VAL_NM CROP_FARM_YR_ADJ_TYPE_NM
			, CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_RS SRC_CROP_FARM_YR_ADJ_RSN_CD
			, CROP_FARM_YR_MNG_VAL_ADJ.AFT_ADJ_VAL AFT_ADJ_VAL
			, CROP_FARM_YR_MNG_VAL_ADJ.BEF_ADJ_VAL BEF_ADJ_VAL
			, CROP_FARM_YR_MNG_VAL_ADJ.PGM_YR PGM_YR 
			, to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT
			, MD5(trim(both CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.FARM_NBR)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_ID||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.YR_ARC_PLC_PTCP_ELCT_ID||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.DATA_STAT_CD)||'~~'||to_char(CROP_FARM_YR_MNG_VAL_ADJ.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.CRE_USER_NM)||'~~'||to_char(CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_USER_NM)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY||'~~'||trim(both FARM_CROP_ADJ_TYPE_RS.DMN_VAL_NM)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_RS||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.AFT_ADJ_VAL||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.BEF_ADJ_VAL||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.PGM_YR) HASH_DIF
		FROM SQL_FARM_RCD_STG.CROP_FARM_YR_MNG_VAL_ADJ 
		LEFT JOIN(select * from EDV.FARM_CROP_ADJ_TYPE_RS where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FARM_CROP_ADJ_TYPE_RS 
		ON (CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY = FARM_CROP_ADJ_TYPE_RS.DMN_VAL_ID)
		WHERE CROP_FARM_YR_MNG_VAL_ADJ.YR_ARC_PLC_PTCP_ELCT_ID IS NOT NULL 
		and CROP_FARM_YR_MNG_VAL_ADJ.CDC_OPER_CD IN ('I','UN')
		order by CROP_FARM_YR_MNG_VAL_ADJ.CDC_DT
		) stg
LEFT JOIN  EDV.CROP_FARM_YR_ADJ_ARC_PLC_HS dv
ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.CROP_FARM_YR_ADJ_ARC_PLC_HS hs
				where stg.FARM_H_ID  = hs.FARM_H_ID 
				and stg.CROP_FARM_YR_MNG_VAL_ADJ_ID = hs.CROP_FARM_YR_MNG_VAL_ADJ_ID
				and stg.yr_arc_plc_ptcp_elct_id = hs.yr_arc_plc_ptcp_elct_id
				and stg.load_dt = hs.load_dt
				)
)
;