MERGE INTO EDV.ACCT_REF_TYPE_RS dv USING
  (SELECT DISTINCT COALESCE (trim(RCD_REF_ID_TYPE.RCD_REF_ID_TYPE_CD),
                        '--') ACCT_REF_TYPE_CD,
                       RCD_REF_ID_TYPE.LOAD_DT LOAD_DT,
                       RCD_REF_ID_TYPE.CDC_DT DATA_EFF_STRT_DT,
                       RCD_REF_ID_TYPE.DATA_SRC_NM DATA_SRC_NM,
                       RCD_REF_ID_TYPE.CRE_DT SRC_CRE_DT,
                       RCD_REF_ID_TYPE.CRE_USER_NM SRC_CRE_USER_NM,
                       RCD_REF_ID_TYPE.LAST_CHG_DT SRC_LAST_CHG_DT,
                       RCD_REF_ID_TYPE.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
                       RCD_REF_ID_TYPE.RCD_REF_ID_TYPE_NM RCD_REF_ID_TYPE_NM,
                       RCD_REF_ID_TYPE.REF_LVL_CD REF_LVL_CD,
                       MD5 (trim(RCD_REF_ID_TYPE.RCD_REF_ID_TYPE_CD)||'~~'||to_char(RCD_REF_ID_TYPE.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(RCD_REF_ID_TYPE.CRE_USER_NM)||'~~'||to_char(RCD_REF_ID_TYPE.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(RCD_REF_ID_TYPE.LAST_CHG_USER_NM)||'~~'||trim(RCD_REF_ID_TYPE.RCD_REF_ID_TYPE_NM)||'~~'||trim(RCD_REF_ID_TYPE.REF_LVL_CD)) HASH_DIF
   FROM SBSD_STG.RCD_REF_ID_TYPE
   WHERE RCD_REF_ID_TYPE.cdc_oper_cd IN ('I',
                                         'UN')
     AND DATE_TRUNC('day',RCD_REF_ID_TYPE.CDC_DT) = DATE_TRUNC('day',TO_TIMESTAMP ('{ETL_START_TIMESTAMP}', 'YYYY-MM-DD HH24:MI:SS.FF'))
   ORDER BY RCD_REF_ID_TYPE.CDC_DT) stg 
ON (coalesce(stg.ACCT_REF_TYPE_CD, 'DFLT') = COALESCE (dv.ACCT_REF_TYPE_CD, 'DFLT')) 
WHEN MATCHED 
  AND dv.LOAD_DT <> stg.LOAD_DT
  AND dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD')
  AND stg.HASH_DIF <> dv.HASH_DIF
THEN
UPDATE
SET LOAD_END_DT = stg.LOAD_DT,
    DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
