-- Julia Lu edition - will update this paragraph and query when (cnsv/ccms)-cdc is ready
-- Stage SQL: CNSV_BUS_RULE (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_CAT_CNFG/incremental/CNSV_CAT_CNFG.sql
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT BUS_RULE_CD,
BUS_RULE_GRP_NM,
BUS_RULE_ID,
LAST_CHG_DT,
CRE_DT,
LAST_CHG_USER_NM,
CRE_USER_NM,
DATA_STAT_CD,
BUS_RULE_GRP_ID,
BUS_RULE_DESC,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
BUS_RULE_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
BUSINESS_RULE.BUS_RULE_CD BUS_RULE_CD,
BUSINESS_RULE_GROUP.BUS_RULE_GRP_NM BUS_RULE_GRP_NM,
BUSINESS_RULE.BUS_RULE_ID BUS_RULE_ID,
BUSINESS_RULE.LAST_CHG_DT LAST_CHG_DT,
BUSINESS_RULE.CRE_DT CRE_DT,
BUSINESS_RULE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
BUSINESS_RULE.CRE_USER_NM CRE_USER_NM,
BUSINESS_RULE.DATA_STAT_CD DATA_STAT_CD,
BUSINESS_RULE.BUS_RULE_GRP_ID BUS_RULE_GRP_ID,
BUSINESS_RULE.BUS_RULE_DESC BUS_RULE_DESC,
BUSINESS_RULE.op,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".BUSINESS_RULE
LEFT JOIN "fsa-{env}-cnsv-cdc".BUSINESS_RULE_GROUP BUSINESS_RULE_GROUP
ON (BUSINESS_RULE.BUS_RULE_GRP_ID = BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID)
WHERE BUSINESS_RULE.op <> 'D'

UNION
SELECT 
BUSINESS_RULE.BUS_RULE_CD BUS_RULE_CD,
BUSINESS_RULE_GROUP.BUS_RULE_GRP_NM BUS_RULE_GRP_NM,
BUSINESS_RULE.BUS_RULE_ID BUS_RULE_ID,
BUSINESS_RULE.LAST_CHG_DT LAST_CHG_DT,
BUSINESS_RULE.CRE_DT CRE_DT,
BUSINESS_RULE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
BUSINESS_RULE.CRE_USER_NM CRE_USER_NM,
BUSINESS_RULE.DATA_STAT_CD DATA_STAT_CD,
BUSINESS_RULE.BUS_RULE_GRP_ID BUS_RULE_GRP_ID,
BUSINESS_RULE.BUS_RULE_DESC BUS_RULE_DESC,
BUSINESS_RULE_GROUP.op,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".BUSINESS_RULE_GROUP
JOIN "fsa-{env}-cnsv-cdc".BUSINESS_RULE BUSINESS_RULE
ON (BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID = BUSINESS_RULE.BUS_RULE_GRP_ID)
WHERE BUSINESS_RULE_GROUP.op <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND BUSINESS_RULE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
BUSINESS_RULE.BUS_RULE_CD BUS_RULE_CD,
NULL BUS_RULE_GRP_NM,
BUSINESS_RULE.BUS_RULE_ID BUS_RULE_ID,
BUSINESS_RULE.LAST_CHG_DT LAST_CHG_DT,
BUSINESS_RULE.CRE_DT CRE_DT,
BUSINESS_RULE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
BUSINESS_RULE.CRE_USER_NM CRE_USER_NM,
BUSINESS_RULE.DATA_STAT_CD DATA_STAT_CD,
BUSINESS_RULE.BUS_RULE_GRP_ID BUS_RULE_GRP_ID,
BUSINESS_RULE.BUS_RULE_DESC BUS_RULE_DESC,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".BUSINESS_RULE
WHERE BUSINESS_RULE.op = 'D'