-- Julia Lu edition - will update this paragraph and query when cnsv-cdc is ready
-- Stage SQL: CNSV_EWT80SCHYR (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_EWT80SCHYR/incremental/CNSV_EWT80SCHYR.sql
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT SGNP_NBR,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_STYPE_AGR_NM,
CROP_HIST_YR,
SGNP_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
-- op,
ROW_NUMBER() over ( partition by 
CROP_HIST_YR,
SGNP_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt80schyr.CROP_HIST_YR CROP_HIST_YR,
ewt80schyr.SGNP_ID SGNP_ID,
ewt80schyr.DATA_STAT_CD DATA_STAT_CD,
ewt80schyr.CRE_DT CRE_DT,
ewt80schyr.LAST_CHG_DT LAST_CHG_DT,
ewt80schyr.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
1 AS TBL_PRIORITY
FROM "fsa-prod-cnsv".EWT80SCHYR 
LEFT JOIN "fsa-prod-cnsv".EWT14SGNP ON (EWT80SCHYR.SGNP_ID = EWT14SGNP.SGNP_ID)
--WHERE __CDC_OPERATION <> 'D'

UNION
SELECT 
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt80schyr.CROP_HIST_YR CROP_HIST_YR,
ewt80schyr.SGNP_ID SGNP_ID,
ewt80schyr.DATA_STAT_CD DATA_STAT_CD,
ewt80schyr.CRE_DT CRE_DT,
ewt80schyr.LAST_CHG_DT LAST_CHG_DT,
ewt80schyr.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
2 AS TBL_PRIORITY
FROM "fsa-prod-cnsv".EWT14SGNP 
JOIN "fsa-prod-cnsv".EWT80SCHYR ON (EWT80SCHYR.SGNP_ID = EWT14SGNP.SGNP_ID)
--WHERE __CDC_OPERATION <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1

UNION
SELECT DISTINCT
NULL SGNP_NBR,
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_STYPE_AGR_NM,
ewt80schyr.CROP_HIST_YR CROP_HIST_YR,
ewt80schyr.SGNP_ID SGNP_ID,
ewt80schyr.DATA_STAT_CD DATA_STAT_CD,
ewt80schyr.CRE_DT CRE_DT,
ewt80schyr.LAST_CHG_DT LAST_CHG_DT,
ewt80schyr.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
1 AS row_num_part
FROM "fsa-prod-cnsv".ewt80schyr
--WHERE __CDC_OPERATION = 'D'
