INSERT into
EDV.FARM_HS(FARM_H_ID,FARM_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
CNTY_OFC_CTL_ID,
FARM_CMN_NM,
RCON_PEND_APVL_CD,
DATA_LOCK_DT,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(SELECT stg.* from (SELECT DISTINCT 
MD5(upper(coalesce(trim(both FARM.ST_FSA_CD), '--') ||'~~'||coalesce(trim(both FARM.CNTY_FSA_CD), '--') ||'~~'||coalesce(trim(both FARM.FARM_NBR), '--') )) as FARM_H_ID,FARM.FARM_ID FARM_ID,FARM.LOAD_DT LOAD_DT,FARM.CDC_DT DATA_EFF_STRT_DT,FARM.DATA_SRC_NM DATA_SRC_NM,FARM.CNTY_OFC_CTL_ID CNTY_OFC_CTL_ID,FARM.FARM_CMN_NM FARM_CMN_NM,FARM.RCON_PEND_APVL_CD RCON_PEND_APVL_CD,FARM.DATA_LOCK_DT DATA_LOCK_DT,FARM.DATA_STAT_CD DATA_STAT_CD,FARM.CRE_DT SRC_CRE_DT,FARM.LAST_CHG_DT SRC_LAST_CHG_DT,FARM.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM ,
to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(trim(both FARM.ST_FSA_CD)||'~~'||trim(both FARM.CNTY_FSA_CD)||'~~'||trim(both FARM.FARM_NBR)||'~~'||FARM.FARM_ID||'~~'||FARM.CNTY_OFC_CTL_ID||'~~'||trim(both FARM.FARM_CMN_NM)||'~~'||trim(both FARM.RCON_PEND_APVL_CD)||'~~'||to_char(FARM.DATA_LOCK_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both FARM.DATA_STAT_CD)||'~~'||to_char(FARM.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(FARM.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both FARM.LAST_CHG_USER_NM)) HASH_DIF
FROM SQL_FARM_RCD_STG.FARM
where FARM.CDC_OPER_CD IN ('I','UN')
order by FARM.CDC_DT
) stg
 LEFT JOIN  EDV.FARM_HS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.FARM_HS hs
				where stg.FARM_H_ID = hs.FARM_H_ID
                and stg.FARM_ID = hs.FARM_ID
				and stg.LOAD_DT = hs.LOAD_DT
			   )
);