SELECT CNSV_PYMT_TYPE,
ACCT_PGM_CD,
HRCH_LVL_NM,
FSCL_YR,
PYMT_VLD_CTL_ID,
PYMT_TYPE_ID,
ACTV_ENG_IND,
AD_1026_IND,
CASH_RENT_TNT_IND,
CNSV_CMPL_IND,
CTL_SBTNC_IND,
FCIC_FRD_IND,
FED_CROP_INS_IND,
PMIT_ENTY_IND,
PRSN_ELG_IND,
DELQ_DEBT_IND,
OBL_IND,
PYMT_LMT_IND,
AGI_WEB_SVC_CALL_IND,
AGI_IND,
PR_YR_ELG_RULE_IND,
FARM_SVC_CPLT_IND,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT CNSV_PYMT_TYPE,
ACCT_PGM_CD,
HRCH_LVL_NM,
FSCL_YR,
PYMT_VLD_CTL_ID,
PYMT_TYPE_ID,
ACTV_ENG_IND,
AD_1026_IND,
CASH_RENT_TNT_IND,
CNSV_CMPL_IND,
CTL_SBTNC_IND,
FCIC_FRD_IND,
FED_CROP_INS_IND,
PMIT_ENTY_IND,
PRSN_ELG_IND,
DELQ_DEBT_IND,
OBL_IND,
PYMT_LMT_IND,
AGI_WEB_SVC_CALL_IND,
AGI_IND,
PR_YR_ELG_RULE_IND,
FARM_SVC_CPLT_IND,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
PYMT_VLD_CTL_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PAYMENT_VALIDATION_CONTROL.FSCL_YR FSCL_YR,
PAYMENT_VALIDATION_CONTROL.PYMT_VLD_CTL_ID PYMT_VLD_CTL_ID,
PAYMENT_VALIDATION_CONTROL.PYMT_TYPE_ID PYMT_TYPE_ID,
PAYMENT_VALIDATION_CONTROL.ACTV_ENG_IND ACTV_ENG_IND,
PAYMENT_VALIDATION_CONTROL.AD_1026_IND AD_1026_IND,
PAYMENT_VALIDATION_CONTROL.CASH_RENT_TNT_IND CASH_RENT_TNT_IND,
PAYMENT_VALIDATION_CONTROL.CNSV_CMPL_IND CNSV_CMPL_IND,
PAYMENT_VALIDATION_CONTROL.CTL_SBTNC_IND CTL_SBTNC_IND,
PAYMENT_VALIDATION_CONTROL.FCIC_FRD_IND FCIC_FRD_IND,
PAYMENT_VALIDATION_CONTROL.FED_CROP_INS_IND FED_CROP_INS_IND,
PAYMENT_VALIDATION_CONTROL.PMIT_ENTY_IND PMIT_ENTY_IND,
PAYMENT_VALIDATION_CONTROL.PRSN_ELG_IND PRSN_ELG_IND,
PAYMENT_VALIDATION_CONTROL.DELQ_DEBT_IND DELQ_DEBT_IND,
PAYMENT_VALIDATION_CONTROL.OBL_IND OBL_IND,
PAYMENT_VALIDATION_CONTROL.PYMT_LMT_IND PYMT_LMT_IND,
PAYMENT_VALIDATION_CONTROL.AGI_WEB_SVC_CALL AGI_WEB_SVC_CALL_IND,
PAYMENT_VALIDATION_CONTROL.AGI_IND AGI_IND,
PAYMENT_VALIDATION_CONTROL.PR_YR_ELG_RULE PR_YR_ELG_RULE_IND,
PAYMENT_VALIDATION_CONTROL.FARM_SVC_CMPL_IND FARM_SVC_CPLT_IND,
PAYMENT_VALIDATION_CONTROL.DATA_STAT_CD DATA_STAT_CD,
PAYMENT_VALIDATION_CONTROL.CRE_DT CRE_DT,
PAYMENT_VALIDATION_CONTROL.LAST_CHG_DT LAST_CHG_DT,
PAYMENT_VALIDATION_CONTROL.LAST_CHG_USER_NM LAST_CHG_USER_NM,
PAYMENT_VALIDATION_CONTROL.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PAYMENT_VALIDATION_CONTROL" PAYMENT_VALIDATION_CONTROL 
LEFT JOIN "fsa-{env}-cnsv".PAYMENT_TYPE 
ON (PAYMENT_VALIDATION_CONTROL.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv".PYMT_IMPL 
ON (PYMT_IMPL.pymt_impl_id = PAYMENT_TYPE.PYMT_IMPL_ID  ) 
LEFT JOIN "fsa-{env}-cnsv".PROGRAM_HIERARCHY_LEVEL 
ON (PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID = PYMT_IMPL.pgm_hrch_lvl_id  )  
WHERE PAYMENT_VALIDATION_CONTROL.OP <> 'D' AND
PAYMENT_VALIDATION_CONTROL.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PAYMENT_VALIDATION_CONTROL.FSCL_YR FSCL_YR,
PAYMENT_VALIDATION_CONTROL.PYMT_VLD_CTL_ID PYMT_VLD_CTL_ID,
PAYMENT_VALIDATION_CONTROL.PYMT_TYPE_ID PYMT_TYPE_ID,
PAYMENT_VALIDATION_CONTROL.ACTV_ENG_IND ACTV_ENG_IND,
PAYMENT_VALIDATION_CONTROL.AD_1026_IND AD_1026_IND,
PAYMENT_VALIDATION_CONTROL.CASH_RENT_TNT_IND CASH_RENT_TNT_IND,
PAYMENT_VALIDATION_CONTROL.CNSV_CMPL_IND CNSV_CMPL_IND,
PAYMENT_VALIDATION_CONTROL.CTL_SBTNC_IND CTL_SBTNC_IND,
PAYMENT_VALIDATION_CONTROL.FCIC_FRD_IND FCIC_FRD_IND,
PAYMENT_VALIDATION_CONTROL.FED_CROP_INS_IND FED_CROP_INS_IND,
PAYMENT_VALIDATION_CONTROL.PMIT_ENTY_IND PMIT_ENTY_IND,
PAYMENT_VALIDATION_CONTROL.PRSN_ELG_IND PRSN_ELG_IND,
PAYMENT_VALIDATION_CONTROL.DELQ_DEBT_IND DELQ_DEBT_IND,
PAYMENT_VALIDATION_CONTROL.OBL_IND OBL_IND,
PAYMENT_VALIDATION_CONTROL.PYMT_LMT_IND PYMT_LMT_IND,
PAYMENT_VALIDATION_CONTROL.AGI_WEB_SVC_CALL AGI_WEB_SVC_CALL_IND,
PAYMENT_VALIDATION_CONTROL.AGI_IND AGI_IND,
PAYMENT_VALIDATION_CONTROL.PR_YR_ELG_RULE PR_YR_ELG_RULE_IND,
PAYMENT_VALIDATION_CONTROL.FARM_SVC_CMPL_IND FARM_SVC_CPLT_IND,
PAYMENT_VALIDATION_CONTROL.DATA_STAT_CD DATA_STAT_CD,
PAYMENT_VALIDATION_CONTROL.CRE_DT CRE_DT,
PAYMENT_VALIDATION_CONTROL.LAST_CHG_DT LAST_CHG_DT,
PAYMENT_VALIDATION_CONTROL.LAST_CHG_USER_NM LAST_CHG_USER_NM,
PAYMENT_TYPE.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PAYMENT_TYPE" PAYMENT_TYPE 
JOIN "fsa-{env}-cnsv".PAYMENT_VALIDATION_CONTROL 
ON (PAYMENT_VALIDATION_CONTROL.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv".PYMT_IMPL 
ON (PYMT_IMPL.pymt_impl_id = PAYMENT_TYPE.PYMT_IMPL_ID  ) 
LEFT JOIN "fsa-{env}-cnsv".PROGRAM_HIERARCHY_LEVEL 
ON (PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID = PYMT_IMPL.pgm_hrch_lvl_id  )  
WHERE PAYMENT_TYPE.OP <> 'D' AND
PAYMENT_TYPE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PAYMENT_VALIDATION_CONTROL.FSCL_YR FSCL_YR,
PAYMENT_VALIDATION_CONTROL.PYMT_VLD_CTL_ID PYMT_VLD_CTL_ID,
PAYMENT_VALIDATION_CONTROL.PYMT_TYPE_ID PYMT_TYPE_ID,
PAYMENT_VALIDATION_CONTROL.ACTV_ENG_IND ACTV_ENG_IND,
PAYMENT_VALIDATION_CONTROL.AD_1026_IND AD_1026_IND,
PAYMENT_VALIDATION_CONTROL.CASH_RENT_TNT_IND CASH_RENT_TNT_IND,
PAYMENT_VALIDATION_CONTROL.CNSV_CMPL_IND CNSV_CMPL_IND,
PAYMENT_VALIDATION_CONTROL.CTL_SBTNC_IND CTL_SBTNC_IND,
PAYMENT_VALIDATION_CONTROL.FCIC_FRD_IND FCIC_FRD_IND,
PAYMENT_VALIDATION_CONTROL.FED_CROP_INS_IND FED_CROP_INS_IND,
PAYMENT_VALIDATION_CONTROL.PMIT_ENTY_IND PMIT_ENTY_IND,
PAYMENT_VALIDATION_CONTROL.PRSN_ELG_IND PRSN_ELG_IND,
PAYMENT_VALIDATION_CONTROL.DELQ_DEBT_IND DELQ_DEBT_IND,
PAYMENT_VALIDATION_CONTROL.OBL_IND OBL_IND,
PAYMENT_VALIDATION_CONTROL.PYMT_LMT_IND PYMT_LMT_IND,
PAYMENT_VALIDATION_CONTROL.AGI_WEB_SVC_CALL AGI_WEB_SVC_CALL_IND,
PAYMENT_VALIDATION_CONTROL.AGI_IND AGI_IND,
PAYMENT_VALIDATION_CONTROL.PR_YR_ELG_RULE PR_YR_ELG_RULE_IND,
PAYMENT_VALIDATION_CONTROL.FARM_SVC_CMPL_IND FARM_SVC_CPLT_IND,
PAYMENT_VALIDATION_CONTROL.DATA_STAT_CD DATA_STAT_CD,
PAYMENT_VALIDATION_CONTROL.CRE_DT CRE_DT,
PAYMENT_VALIDATION_CONTROL.LAST_CHG_DT LAST_CHG_DT,
PAYMENT_VALIDATION_CONTROL.LAST_CHG_USER_NM LAST_CHG_USER_NM,
PYMT_IMPL.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PYMT_IMPL" PYMT_IMPL 
LEFT JOIN "fsa-{env}-cnsv".PAYMENT_TYPE 
ON (PYMT_IMPL.pymt_impl_id = PAYMENT_TYPE.PYMT_IMPL_ID  ) 
JOIN "fsa-{env}-cnsv".PAYMENT_VALIDATION_CONTROL 
ON (PAYMENT_VALIDATION_CONTROL.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv".PROGRAM_HIERARCHY_LEVEL 
ON (PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID = PYMT_IMPL.pgm_hrch_lvl_id  )  
WHERE PYMT_IMPL.OP <> 'D' AND
PYMT_IMPL.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PAYMENT_VALIDATION_CONTROL.FSCL_YR FSCL_YR,
PAYMENT_VALIDATION_CONTROL.PYMT_VLD_CTL_ID PYMT_VLD_CTL_ID,
PAYMENT_VALIDATION_CONTROL.PYMT_TYPE_ID PYMT_TYPE_ID,
PAYMENT_VALIDATION_CONTROL.ACTV_ENG_IND ACTV_ENG_IND,
PAYMENT_VALIDATION_CONTROL.AD_1026_IND AD_1026_IND,
PAYMENT_VALIDATION_CONTROL.CASH_RENT_TNT_IND CASH_RENT_TNT_IND,
PAYMENT_VALIDATION_CONTROL.CNSV_CMPL_IND CNSV_CMPL_IND,
PAYMENT_VALIDATION_CONTROL.CTL_SBTNC_IND CTL_SBTNC_IND,
PAYMENT_VALIDATION_CONTROL.FCIC_FRD_IND FCIC_FRD_IND,
PAYMENT_VALIDATION_CONTROL.FED_CROP_INS_IND FED_CROP_INS_IND,
PAYMENT_VALIDATION_CONTROL.PMIT_ENTY_IND PMIT_ENTY_IND,
PAYMENT_VALIDATION_CONTROL.PRSN_ELG_IND PRSN_ELG_IND,
PAYMENT_VALIDATION_CONTROL.DELQ_DEBT_IND DELQ_DEBT_IND,
PAYMENT_VALIDATION_CONTROL.OBL_IND OBL_IND,
PAYMENT_VALIDATION_CONTROL.PYMT_LMT_IND PYMT_LMT_IND,
PAYMENT_VALIDATION_CONTROL.AGI_WEB_SVC_CALL AGI_WEB_SVC_CALL_IND,
PAYMENT_VALIDATION_CONTROL.AGI_IND AGI_IND,
PAYMENT_VALIDATION_CONTROL.PR_YR_ELG_RULE PR_YR_ELG_RULE_IND,
PAYMENT_VALIDATION_CONTROL.FARM_SVC_CMPL_IND FARM_SVC_CPLT_IND,
PAYMENT_VALIDATION_CONTROL.DATA_STAT_CD DATA_STAT_CD,
PAYMENT_VALIDATION_CONTROL.CRE_DT CRE_DT,
PAYMENT_VALIDATION_CONTROL.LAST_CHG_DT LAST_CHG_DT,
PAYMENT_VALIDATION_CONTROL.LAST_CHG_USER_NM LAST_CHG_USER_NM,
PROGRAM_HIERARCHY_LEVEL.OP,
4 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL 
LEFT JOIN "fsa-{env}-cnsv".PYMT_IMPL 
ON (PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID = PYMT_IMPL.pgm_hrch_lvl_id  ) 
LEFT JOIN "fsa-{env}-cnsv".PAYMENT_TYPE 
ON (PYMT_IMPL.pymt_impl_id = PAYMENT_TYPE.PYMT_IMPL_ID  ) 
JOIN "fsa-{env}-cnsv".PAYMENT_VALIDATION_CONTROL 
ON (PAYMENT_VALIDATION_CONTROL.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID)  
WHERE PROGRAM_HIERARCHY_LEVEL.OP <> 'D' AND
PROGRAM_HIERARCHY_LEVEL.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
NULL CNSV_PYMT_TYPE,
NULL ACCT_PGM_CD,
NULL HRCH_LVL_NM,
PAYMENT_VALIDATION_CONTROL.FSCL_YR FSCL_YR,
PAYMENT_VALIDATION_CONTROL.PYMT_VLD_CTL_ID PYMT_VLD_CTL_ID,
PAYMENT_VALIDATION_CONTROL.PYMT_TYPE_ID PYMT_TYPE_ID,
PAYMENT_VALIDATION_CONTROL.ACTV_ENG_IND ACTV_ENG_IND,
PAYMENT_VALIDATION_CONTROL.AD_1026_IND AD_1026_IND,
PAYMENT_VALIDATION_CONTROL.CASH_RENT_TNT_IND CASH_RENT_TNT_IND,
PAYMENT_VALIDATION_CONTROL.CNSV_CMPL_IND CNSV_CMPL_IND,
PAYMENT_VALIDATION_CONTROL.CTL_SBTNC_IND CTL_SBTNC_IND,
PAYMENT_VALIDATION_CONTROL.FCIC_FRD_IND FCIC_FRD_IND,
PAYMENT_VALIDATION_CONTROL.FED_CROP_INS_IND FED_CROP_INS_IND,
PAYMENT_VALIDATION_CONTROL.PMIT_ENTY_IND PMIT_ENTY_IND,
PAYMENT_VALIDATION_CONTROL.PRSN_ELG_IND PRSN_ELG_IND,
PAYMENT_VALIDATION_CONTROL.DELQ_DEBT_IND DELQ_DEBT_IND,
PAYMENT_VALIDATION_CONTROL.OBL_IND OBL_IND,
PAYMENT_VALIDATION_CONTROL.PYMT_LMT_IND PYMT_LMT_IND,
PAYMENT_VALIDATION_CONTROL.AGI_WEB_SVC_CALL AGI_WEB_SVC_CALL_IND,
PAYMENT_VALIDATION_CONTROL.AGI_IND AGI_IND,
PAYMENT_VALIDATION_CONTROL.PR_YR_ELG_RULE PR_YR_ELG_RULE_IND,
PAYMENT_VALIDATION_CONTROL.FARM_SVC_CMPL_IND FARM_SVC_CPLT_IND,
PAYMENT_VALIDATION_CONTROL.DATA_STAT_CD DATA_STAT_CD,
PAYMENT_VALIDATION_CONTROL.CRE_DT CRE_DT,
PAYMENT_VALIDATION_CONTROL.LAST_CHG_DT LAST_CHG_DT,
PAYMENT_VALIDATION_CONTROL.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".PAYMENT_VALIDATION_CONTROL PAYMENT_VALIDATION_CONTROL
WHERE OP = 'D'
AND dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}' 
)