INSERT into
EDV.FARM_PRDR_PCW_EXCP_RH(FARM_PRDR_PCW_EXCP_CD,
DATA_SRC_NM,
LOAD_DT)
(
SELECT 
stg.FARM_PRDR_PCW_EXCP_CD,
stg.DATA_SRC_NM,
stg.LOAD_DT
from (
SELECT DISTINCT
coalesce(DMN_VAL.DMN_CHAR_VAL, '[NULL IN SOURCE]') FARM_PRDR_PCW_EXCP_CD,
DMN_VAL.DATA_SRC_NM DATA_SRC_NM,
DMN_VAL.LOAD_DT LOAD_DT,
ROW_NUMBER() OVER (PARTITION BY DMN_VAL.DMN_CHAR_VAL ORDER BY DMN_VAL.CDC_DT desc, DMN_VAL.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.DMN_VAL
WHERE DMN_ID = 3
and DMN_VAL.cdc_oper_cd IN ('I','UN','D')
) stg 
LEFT JOIN  EDV.FARM_PRDR_PCW_EXCP_RH dv
 ON (
stg.FARM_PRDR_PCW_EXCP_CD = dv.FARM_PRDR_PCW_EXCP_CD
)
where (
dv.FARM_PRDR_PCW_EXCP_CD IS NULL
)
and stg.STG_EFF_DT_RANK = 1
);