MERGE INTO EDV.CLU_PRDR_YR_LS DV
USING(	SELECT      DISTINCT MD5(coalesce(CPR.CORE_CUST_ID, '-1') ||'~~'||MD5(UPPER(coalesce(CPR.ST_FSA_CD,'--')||'~~'||coalesce(CPR.CNTY_FSA_CD,'--')||'~~'||coalesce(CPR.FARM_NBR,'--')))||'~~'||MD5(UPPER(coalesce(CPR.ST_FSA_CD,'--')||'~~'||coalesce(CPR.CNTY_FSA_CD,'--')||'~~'||coalesce((CPR.TR_NBR)::numeric ,-1)))) CLU_PRDR_L_ID
	            ,CPR.CLU_PRDR_YR_ID CLU_PRDR_YR_ID,CPR.LOAD_DT LOAD_DT,CPR.CDC_DT DATA_EFF_STRT_DT,CPR.DATA_SRC_NM DATA_SRC_NM,CPR.DATA_STAT_CD DATA_STAT_CD,CPR.CRE_DT SRC_CRE_DT,CPR.LAST_CHG_DT SRC_LAST_CHG_DT,CPR.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
	            ,CPR.CLU_YR_ID CLU_YR_ID,CPR.CORE_CUST_ID CORE_CUST_ID,CPR.PRDR_INVL_CD SRC_PRDR_INVL_CD,PRDR_INVL_RS.DMN_VAL_NM PRDR_INVL_NM,CPR.CLU_PRDR_HEL_EXCP_CD SRC_CLU_PRDR_HEL_EXCP_CD,FLD_PRDR_HEL_EXCP_RS.DMN_VAL_NM CLU_PRDR_HEL_EXCP_NM,CPR.CLU_PRDR_CW_EXCP_CD SRC_CLU_PRDR_CW_EXCP_CD
	            ,FLD_PRDR_CW_EXCP_RS.DMN_VAL_NM CLU_PRDR_CW_EXCP_NM,CPR.CLU_PRDR_PCW_EXCP_CD SRC_CLU_PRDR_PCW_EXCP_CD,FLD_PRDR_PCW_EXCP_RS.DMN_VAL_NM CLU_PRDR_PCW_EXCP_NM,CPR.PGM_YR PGM_YR,CPR.CDC_OPER_CD
	            ,MD5(CPR.CORE_CUST_ID||'~~'||UPPER(coalesce(CPR.ST_FSA_CD,'--')||'~~'||coalesce(CPR.CNTY_FSA_CD,'--')||'~~'||coalesce(CPR.FARM_NBR,'--'))||'~~'||UPPER(coalesce(CPR.ST_FSA_CD,'--')||'~~'||coalesce(CPR.CNTY_FSA_CD,'--')||'~~'||coalesce(CPR.TR_NBR,'-1'))||'~~'||CPR.CLU_PRDR_YR_ID||'~~'||trim(both CPR.DATA_STAT_CD)||'~~'||TO_CHAR(CPR.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(CPR.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CPR.LAST_CHG_USER_NM)||'~~'||CPR.CLU_YR_ID||'~~'||CPR.PRDR_INVL_CD||'~~'||PRDR_INVL_RS.DMN_VAL_NM||'~~'||CPR.CLU_PRDR_HEL_EXCP_CD||'~~'||FLD_PRDR_HEL_EXCP_RS.DMN_VAL_NM||'~~'||CPR.CLU_PRDR_CW_EXCP_CD||'~~'||FLD_PRDR_CW_EXCP_RS.DMN_VAL_NM||'~~'||CPR.CLU_PRDR_PCW_EXCP_CD||'~~'||FLD_PRDR_PCW_EXCP_RS.DMN_VAL_NM||'~~'||CPR.PGM_YR||'~~'||TO_CHAR(CPR.HEL_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(CPR.CW_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(CPR.PCW_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US')||'~~'||CPR.CLU_PRDR_RMA_HEL_EXCP_CD||'~~'||CPR.CLU_PRDR_RMA_CW_EXCP_CD||'~~'||CPR.CLU_PRDR_RMA_PCW_EXCP_CD) HASH_DIF
	            ,CPR.HEL_APLS_EXHST_DT,CPR.CW_APLS_EXHST_DT,CPR.PCW_APLS_EXHST_DT,CPR.CLU_PRDR_RMA_HEL_EXCP_CD,CPR.CLU_PRDR_RMA_CW_EXCP_CD,CPR.CLU_PRDR_RMA_PCW_EXCP_CD
	FROM        SQL_FARM_RCD_STG.CLU_PRDR_YR CPR
	            LEFT JOIN(SELECT * FROM EDV.FLD_PRDR_CW_EXCP_RS WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
	            ) FLD_PRDR_CW_EXCP_RS
	            ON (CPR.CLU_PRDR_CW_EXCP_CD = FLD_PRDR_CW_EXCP_RS.DMN_VAL_ID) 
	            LEFT JOIN(SELECT * FROM EDV.FLD_PRDR_HEL_EXCP_RS WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
	            ) FLD_PRDR_HEL_EXCP_RS 
	            ON (CPR.CLU_PRDR_HEL_EXCP_CD = FLD_PRDR_HEL_EXCP_RS.DMN_VAL_ID) 
	            LEFT JOIN(SELECT * FROM EDV.FLD_PRDR_PCW_EXCP_RS WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
	            ) FLD_PRDR_PCW_EXCP_RS 
	            ON (CPR.CLU_PRDR_PCW_EXCP_CD = FLD_PRDR_PCW_EXCP_RS.DMN_VAL_ID) 
	            LEFT JOIN(SELECT * FROM EDV.PRDR_INVL_RS WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
	            ) PRDR_INVL_RS 
	            ON (CPR.PRDR_INVL_CD= PRDR_INVL_RS.DMN_VAL_ID)
	WHERE       CPR.CDC_OPER_CD IN ('I','UN')
ORDER BY    CPR.CDC_DT
) STG ON ( coalesce(STG.CLU_PRDR_YR_ID,0) = coalesce(DV.CLU_PRDR_YR_ID,0) ) 
WHEN MATCHED and DV.LOAD_DT <> STG.LOAD_DT and DV.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and STG.HASH_DIF <> DV.HASH_DIF THEN UPDATE 
    SET         LOAD_END_DT = STG.LOAD_DT,
                DATA_EFF_END_DT = STG.DATA_EFF_STRT_DT
;