SELECT HRCH_LVL_NM,
PGM_HRCH_LVL_ID,
PRNT_PGM_HRCH_LVL,
PRNT_PGM_HRCH_LVL_NM,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT HRCH_LVL_NM,
PGM_HRCH_LVL_ID,
PRNT_PGM_HRCH_LVL,
PRNT_PGM_HRCH_LVL_NM,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
PGM_HRCH_LVL_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID PGM_HRCH_LVL_ID,
PROGRAM_HIERARCHY_LEVEL.PRNT_PGM_HRCH_LVL PRNT_PGM_HRCH_LVL,
PROGRAM_HIERARCHY_LEVEL_PRNT.HRCH_LVL_NM PRNT_PGM_HRCH_LVL_NM,
PROGRAM_HIERARCHY_LEVEL.DATA_STAT_CD DATA_STAT_CD,
PROGRAM_HIERARCHY_LEVEL.CRE_DT CRE_DT,
PROGRAM_HIERARCHY_LEVEL.LAST_CHG_DT LAST_CHG_DT,
PROGRAM_HIERARCHY_LEVEL.LAST_CHG_USER_NM LAST_CHG_USER_NM,
PROGRAM_HIERARCHY_LEVEL.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL 
LEFT JOIN "fsa-{env}-cnsv".PROGRAM_HIERARCHY_LEVEL  PROGRAM_HIERARCHY_LEVEL_PRNT
ON (PROGRAM_HIERARCHY_LEVEL_PRNT.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PRNT_PGM_HRCH_LVL)
WHERE PROGRAM_HIERARCHY_LEVEL.OP <> 'D' AND
PROGRAM_HIERARCHY_LEVEL.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID PGM_HRCH_LVL_ID,
PROGRAM_HIERARCHY_LEVEL.PRNT_PGM_HRCH_LVL PRNT_PGM_HRCH_LVL,
NULL PRNT_PGM_HRCH_LVL_NM,
PROGRAM_HIERARCHY_LEVEL.DATA_STAT_CD DATA_STAT_CD,
PROGRAM_HIERARCHY_LEVEL.CRE_DT CRE_DT,
PROGRAM_HIERARCHY_LEVEL.LAST_CHG_DT LAST_CHG_DT,
PROGRAM_HIERARCHY_LEVEL.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".PROGRAM_HIERARCHY_LEVEL PROGRAM_HIERARCHY_LEVEL
WHERE OP = 'D'
AND dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}' 
)