with upsert_data as(
SELECT DISTINCT
DM.RCON_TYPE_DURB_ID,
DM.DATA_EFF_STRT_DT,
DM.RCON_TYPE_CD,
DM.RCON_TYPE_NM,
DM.RCON_TYPE_DESC
FROM (
SELECT
FCH.DURB_ID RCON_TYPE_DURB_ID,
coalesce(FCT.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) DATA_EFF_STRT_DT,
FCT.FARM_CHG_TYPE_CD AS RCON_TYPE_CD,
FCT.DMN_VAL_NM AS RCON_TYPE_NM,
FCT.DMN_VAL_DESC AS RCON_TYPE_DESC,
ROW_NUMBER() OVER ( PARTITION BY coalesce(FCT.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')), FCT.FARM_CHG_TYPE_CD ORDER BY FCT.DATA_EFF_STRT_DT DESC) AS ROW_NUM_PART 
FROM EDV.FARM_CHG_TYPE_RS  FCT
LEFT JOIN EDV.FARM_CHG_TYPE_RH  FCH ON (FCH.FARM_CHG_TYPE_CD = coalesce(FCT.FARM_CHG_TYPE_CD,'[NULL IN SOURCE]'))
WHERE DMN_ID = 14
AND cast(FCT.DATA_EFF_STRT_DT as date) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 
AND EXISTS ( SELECT '1' FROM EDV.FARM_CHG_TYPE_RS  FCT_IN
             WHERE FCT_IN.FARM_CHG_TYPE_CD = FCT.FARM_CHG_TYPE_CD
             AND cast(FCT_IN.DATA_EFF_END_DT as date) = TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
		) 
AND FCH.DURB_ID IS NOT NULL              
) DM
WHERE DM.ROW_NUM_PART = 1
)
select ud.rcon_type_durb_id,
	'0' as cur_rcd_ind,
	ud.data_eff_strt_dt,
	(current_date) as data_eff_end_dt, 
    (current_date) as cre_dt, 
	ud.rcon_type_cd,
	ud.rcon_type_nm,
	ud.rcon_type_desc
from upsert_data ud
