WITH del_data AS (
SELECT DISTINCT
	 'I' AS DATA_STAT_CD
	 ,DV_DR.SRC_CRE_DT AS ARC_PLC_PTCP_ELCT_CRE_DT
     ,DV_DR.SRC_CRE_USER_NM AS ARC_PLC_PTCP_ELCT_CRE_USER_NM
     ,DV_DR.SRC_LAST_CHG_DT AS ARC_PLC_PTCP_ELCT_LAST_CHG_DT
     ,DV_DR.SRC_LAST_CHG_USER_NM AS ARC_PLC_ELCT_LAST_CHG_USER_NM
     ,DV_DR.DATA_EFF_STRT_DT DV_DR_DATA_EFF_STRT_DT
	 ,DV_DR.DATA_STAT_CD AS SRC_DATA_STAT_CD
	 ,dv_dr.PGM_YR AS PGM_YR	 
	 ,COALESCE(FR_DIM.FARM_SRGT_ID, -3) AS FARM_SRGT_ID	 
     ,FR_DIM.FARM_DURB_ID AS FARM_DURB_ID
	 ,COALESCE(FS_DIM.FSA_ST_CNTY_SRGT_ID, -3) AS ADM_FSA_ST_CNTY_SRGT_ID
     ,COALESCE(FS_DIM.FSA_ST_CNTY_DURB_ID, -3) AS ADM_FSA_ST_CNTY_DURB_ID
	 ,COALESCE(FSA_DIM.FSA_CROP_SRGT_ID, -3) AS FSA_CROP_SRGT_ID
     ,FSA_DIM.FSA_CROP_DURB_ID AS FSA_CROP_DURB_ID
	 ,COALESCE(APE_DIM.ARC_PLC_ELCT_SRGT_ID, -3) AS ARC_PLC_ELCT_SRGT_ID
	 ,APE_DIM.ARC_PLC_ELCT_DURB_ID AS ARC_PLC_ELCT_DURB_ID
     ,COALESCE(APED_DIM.ARC_PLC_ELG_DTER_DURB_ID, -3) AS ARC_PLC_ELG_DTER_DURB_ID
 FROM EDV.YR_ARC_PLC_PTCP_ELCT_LS dv_dr
 LEFT JOIN EDV.CROP_FARM_L cfl ON (COALESCE(dv_dr.CROP_FARM_L_ID,'6bb61e3b7bce0931da574d19d1d82c88') = cfl.CROP_FARM_L_ID)
 LEFT JOIN EDV.FARM_H FH ON (COALESCE(cfl.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = FH.FARM_H_ID)
 LEFT JOIN EDV.LOC_AREA_MRT_SRC_RS LAMS 
 ON (FH.ST_FSA_CD = COALESCE(LAMS.CTRY_DIV_MRT_CD, '--')
    AND FH.CNTY_FSA_CD = COALESCE(LAMS.LOC_AREA_MRT_CD, '--')
    AND LAMS.LOC_AREA_MRT_CD_SRC_ACRO = 'FSA')
                    
 LEFT JOIN EDV.LOC_AREA_RH LAH 
    ON (COALESCE(LAMS.LOC_AREA_CAT_NM, '[NULL IN SOURCE]') = LAH.LOC_AREA_CAT_NM
    AND COALESCE(LAMS.LOC_AREA_NM, '[NULL IN SOURCE]') = LAH.LOC_AREA_NM
    AND COALESCE(LAMS.CTRY_DIV_NM, '[NULL IN SOURCE]') = LAH.CTRY_DIV_NM
    AND LAMS.LOC_AREA_MRT_CD_SRC_ACRO = 'FSA')
                    
 LEFT JOIN CMN_DIM_DM_STG.FSA_ST_CNTY_DIM FS_DIM 
    ON (LAH.DURB_ID = COALESCE(FS_DIM.FSA_ST_CNTY_DURB_ID, -1)
    AND FS_DIM.CUR_RCD_IND = 1)
					
 LEFT JOIN CMN_DIM_DM_STG.FARM_DIM FR_DIM ON (
        fh.DURB_ID = COALESCE(fr_dim.FARM_DURB_ID,-1)
        AND FR_DIM.CUR_RCD_IND = 1
        )
 LEFT JOIN EBV.FSA_CROP_TYPE_RH fctrh ON (
        COALESCE(cfl.FSA_CROP_CD,'--') = fctrh.FSA_CROP_CD
        AND COALESCE(cfl.FSA_CROP_TYPE_CD,'--') = fctrh.FSA_CROP_TYPE_CD
        AND dv_dr.PGM_YR = fctrh.PGM_YR
        )
 LEFT JOIN CMN_DIM_DM_STG.FSA_CROP_TYPE_DIM FSA_DIM ON (
        fctrh.DURB_ID = COALESCE(FSA_DIM.FSA_CROP_DURB_ID,-1)
        AND FSA_DIM.CUR_RCD_IND = 1
        ) 
 LEFT JOIN EDV.ARC_PLC_ELCT_RS APERS 
        ON (DV_DR.SRC_ARC_PLC_ELCT_CHC_ID = APERS.DMN_VAL_ID)
 LEFT JOIN EDV.ARC_PLC_ELCT_RH APERH 
        ON (COALESCE(APERS.ARC_PLC_ELCT_CD, '[NULL IN SOURCE]') = APERH.ARC_PLC_ELCT_CD)
 LEFT JOIN FARM_DM_STG.ARC_PLC_ELCT_DIM APE_DIM 
        ON (APERH.DURB_ID = COALESCE(APE_DIM.ARC_PLC_ELCT_DURB_ID, -1)
        AND APE_DIM.CUR_RCD_IND = 1)
 LEFT JOIN EDV.FARM_YR_HS FYHS
        ON (COALESCE(DV_DR.FARM_YR_ID, -1) = FYHS.FARM_YR_ID)
 LEFT JOIN EDV.ARC_PLC_ELG_DTER_RH APEDRH 
        ON (COALESCE(FYHS.ARC_PLC_ELG_DTER_CD, '[NULL IN SOURCE]') = APEDRH.ARC_PLC_ELG_DTER_CD)
 LEFT JOIN EDV.ARC_PLC_ELG_DTER_RS APEDRS 
        ON (APEDRH.ARC_PLC_ELG_DTER_CD = COALESCE(APEDRS.ARC_PLC_ELG_DTER_CD, '[NULL IN SOURCE]'))
 LEFT JOIN FARM_DM_STG.ARC_PLC_ELG_DTER_DIM APED_DIM 
       ON (APEDRH.DURB_ID = COALESCE(APED_DIM.ARC_PLC_ELG_DTER_DURB_ID, -1)
       AND APED_DIM.DATA_STAT_CD = 'A')		
WHERE 
( CAST(DV_DR.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
AND NOT EXISTS (SELECT '1' FROM EDV.YR_ARC_PLC_PTCP_ELCT_LS DV_DR_INN
                 WHERE DV_DR.CROP_FARM_L_ID = DV_DR_INN.CROP_FARM_L_ID
                 AND DV_DR.YR_ARC_PLC_PTCP_ELCT_ID = DV_DR_INN.YR_ARC_PLC_PTCP_ELCT_ID
                 AND CAST(DV_DR_INN.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD'))
 )                
AND DV_DR.PGM_YR IS NOT NULL
AND FR_DIM.FARM_DURB_ID IS NOT NULL
AND FSA_DIM.FSA_CROP_DURB_ID IS NOT NULL
)
SELECT 
	   (current_date) as cre_dt,
	   (current_date) as last_chg_dt, 
       data_stat_cd,
	   farm_srgt_id, 
       farm_durb_id, 
       adm_fsa_st_cnty_srgt_id, 
       adm_fsa_st_cnty_durb_id, 
       pgm_yr, 
       fsa_crop_srgt_id, 
       fsa_crop_durb_id, 
       arc_plc_elct_srgt_id, 
       arc_plc_elct_durb_id, 
       arc_plc_ptcp_elct_cre_dt, 
       arc_plc_ptcp_elct_cre_user_nm, 
       arc_plc_ptcp_elct_last_chg_dt, 
       arc_plc_elct_last_chg_user_nm, 
       src_data_stat_cd, 
       arc_plc_elg_dter_durb_id
FROM del_data dl
