UPDATE CAR_DM_STG.CROP_ACRG_RPT_BUS_PTY_FACT mart
SET DATA_STAT_CD = 'I',
    LAST_CHG_DT = TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD HH24:MI:SS.FF')
FROM
  (SELECT DISTINCT CROP_ACRG_RPT_DIM.CROP_ACRG_RPT_DURB_ID,
                   CUST_DIM.CUST_DURB_ID
   FROM edv.CROP_ACRG_RPT_BUS_PTY_LS dv_dr
   LEFT JOIN edv.CROP_ACRG_RPT_BUS_PTY_L ON (dv_dr.CROP_ACRG_RPT_BUS_PTY_L_ID = CROP_ACRG_RPT_BUS_PTY_L.CROP_ACRG_RPT_BUS_PTY_L_ID)
   LEFT JOIN edv.CORE_CUST_H ON (COALESCE (CROP_ACRG_RPT_BUS_PTY_L.CORE_CUST_ID,
                                           '-1') = CORE_CUST_H.CORE_CUST_ID)
   LEFT JOIN edv.CROP_ACRG_RPT_H ON (COALESCE (CROP_ACRG_RPT_BUS_PTY_L.CROP_ACRG_RPT_H_ID,
                                               '1cc552b48373871758d99e3ecfe05b70') = CROP_ACRG_RPT_H.CROP_ACRG_RPT_H_ID)
   LEFT JOIN CAR_DM_STG.CROP_ACRG_RPT_DIM ON (CROP_ACRG_RPT_H.DURB_ID = CROP_ACRG_RPT_DIM.CROP_ACRG_RPT_DURB_ID
                                          AND CROP_ACRG_RPT_DIM.CUR_RCD_IND = 1)
   LEFT JOIN cmn_dim_dm_stg.CUST_DIM ON (CORE_CUST_H.DURB_ID = CUST_DIM.CUST_DURB_ID
                                         AND CUST_DIM.CUR_RCD_IND = 1)
   WHERE (DATE (DV_DR.DATA_EFF_END_DT) = TO_TIMESTAMP ('{ETL_DATE}',
                                                        'YYYY-MM-DD')
          AND NOT EXISTS
            (SELECT '1'
             FROM edv.CROP_ACRG_RPT_BUS_PTY_LS sub
             WHERE sub.BUS_PTY_ID = dv_dr.BUS_PTY_ID
               AND sub. DATA_EFF_END_DT = TO_TIMESTAMP ('9999-12-31',
                                                        'YYYY-MM-DD') ))
     AND CROP_ACRG_RPT_DIM.CROP_ACRG_RPT_DURB_ID IS NOT NULL
     AND CUST_DIM.CUST_DURB_ID IS NOT NULL ) AS vault
WHERE vault.CROP_ACRG_RPT_DURB_ID = mart.CROP_ACRG_RPT_DURB_ID
  AND vault.CUST_DURB_ID = mart.CUST_DURB_ID
  AND mart.DATA_STAT_CD = 'A'