-- =============================================================================
-- Julia Lu - 2026-01-22
-- Stage SQL: CCMS_CTR_FAM_PTCP (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/STG/CCMS_CTR_FAM_PTCP/incremental/CCMS_CTR_FAM_PTCP.sql
-- Date Logic:
--   ETL_START_DATE = User provided start_date
--   ETL_END_DATE   = Today (automatically set by Glue job)
--
-- Examples:
--   start_date=2025-01-12 (today is 2025-01-12) → Single day
--   start_date=2025-01-10 (today is 2025-01-12) → 3 days catch-up
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT CTR_FAM_PTCP_ID,
CRE_DT,
CRE_USER_NM,
LAST_CHG_DT,
LAST_CHG_USER_NM,
DATA_STAT_CD,
CTR_FAM_ID,
CORE_CUST_ID,
CTR_PTCP_STRT_YR,
CTR_PTCP_ERR_TYPE_ID,
CTR_PTCP_ERR_YR,
CTR_PTCP_ERR_CD,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CTR_FAM_PTCP_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_FAMILY_PARTICPANT_IDENTIFIER  CTR_FAM_PTCP_ID,
CONTRACT_FAMILY_PARTICIPANT.CREATION_DATE  CRE_DT,
CONTRACT_FAMILY_PARTICIPANT.CREATION_USER_NAME  CRE_USER_NM,
CONTRACT_FAMILY_PARTICIPANT.LAST_CHANGE_DATE  LAST_CHG_DT,
CONTRACT_FAMILY_PARTICIPANT.LAST_CHANGE_USER_NAME  LAST_CHG_USER_NM,
CONTRACT_FAMILY_PARTICIPANT.DATA_STATUS_CODE  DATA_STAT_CD,
CONTRACT_FAMILY_PARTICIPANT.CTR_CORE_DET_ID  CTR_FAM_ID,
CONTRACT_FAMILY_PARTICIPANT.CORE_CUSTOMER_IDENTIFIER  CORE_CUST_ID,
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_PARTICIPATION_START_YEAR  CTR_PTCP_STRT_YR,
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_PARTICIPANT_ERROR_TYPE_IDENTIFIER  CTR_PTCP_ERR_TYPE_ID,
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_PARTICIPANT_ERROR_YEAR  CTR_PTCP_ERR_YR,
CONTRACT_PARTICIPANT_ERROR_TYPE.CONTRACT_PARTICIPANT_ERROR_CODE  CTR_PTCP_ERR_CD,
CONTRACT_FAMILY_PARTICIPANT.op,
1 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".CONTRACT_FAMILY_PARTICIPANT
LEFT JOIN "fsa-{env}-ccms-cdc".CONTRACT_PARTICIPANT_ERROR_TYPE ON (CONTRACT_FAMILY_PARTICIPANT.CONTRACT_PARTICIPANT_ERROR_TYPE_IDENTIFIER = CONTRACT_PARTICIPANT_ERROR_TYPE.CONTRACT_PARTICIPANT_ERROR_TYPE_IDENTIFIER)
WHERE CONTRACT_FAMILY_PARTICIPANT.op <> 'D'

UNION
SELECT
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_FAMILY_PARTICPANT_IDENTIFIER  CTR_FAM_PTCP_ID,
CONTRACT_FAMILY_PARTICIPANT.CREATION_DATE  CRE_DT,
CONTRACT_FAMILY_PARTICIPANT.CREATION_USER_NAME  CRE_USER_NM,
CONTRACT_FAMILY_PARTICIPANT.LAST_CHANGE_DATE  LAST_CHG_DT,
CONTRACT_FAMILY_PARTICIPANT.LAST_CHANGE_USER_NAME  LAST_CHG_USER_NM,
CONTRACT_FAMILY_PARTICIPANT.DATA_STATUS_CODE  DATA_STAT_CD,
CONTRACT_FAMILY_PARTICIPANT.CTR_CORE_DET_ID  CTR_FAM_ID,
CONTRACT_FAMILY_PARTICIPANT.CORE_CUSTOMER_IDENTIFIER  CORE_CUST_ID,
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_PARTICIPATION_START_YEAR  CTR_PTCP_STRT_YR,
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_PARTICIPANT_ERROR_TYPE_IDENTIFIER  CTR_PTCP_ERR_TYPE_ID,
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_PARTICIPANT_ERROR_YEAR  CTR_PTCP_ERR_YR,
CONTRACT_PARTICIPANT_ERROR_TYPE.CONTRACT_PARTICIPANT_ERROR_CODE  CTR_PTCP_ERR_CD,
CONTRACT_PARTICIPANT_ERROR_TYPE.op,
2 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".CONTRACT_PARTICIPANT_ERROR_TYPE
JOIN "fsa-{env}-ccms-cdc".CONTRACT_FAMILY_PARTICIPANT ON (CONTRACT_FAMILY_PARTICIPANT.CONTRACT_PARTICIPANT_ERROR_TYPE_IDENTIFIER = CONTRACT_PARTICIPANT_ERROR_TYPE.CONTRACT_PARTICIPANT_ERROR_TYPE_IDENTIFIER)
WHERE CONTRACT_PARTICIPANT_ERROR_TYPE.op <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND CONTRACT_FAMILY_PARTICIPANT.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_FAMILY_PARTICPANT_IDENTIFIER  CTR_FAM_PTCP_ID,
CONTRACT_FAMILY_PARTICIPANT.CREATION_DATE  CRE_DT,
CONTRACT_FAMILY_PARTICIPANT.CREATION_USER_NAME  CRE_USER_NM,
CONTRACT_FAMILY_PARTICIPANT.LAST_CHANGE_DATE  LAST_CHG_DT,
CONTRACT_FAMILY_PARTICIPANT.LAST_CHANGE_USER_NAME  LAST_CHG_USER_NM,
CONTRACT_FAMILY_PARTICIPANT.DATA_STATUS_CODE  DATA_STAT_CD,
CONTRACT_FAMILY_PARTICIPANT.CTR_CORE_DET_ID  CTR_FAM_ID,
CONTRACT_FAMILY_PARTICIPANT.CORE_CUSTOMER_IDENTIFIER  CORE_CUST_ID,
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_PARTICIPATION_START_YEAR  CTR_PTCP_STRT_YR,
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_PARTICIPANT_ERROR_TYPE_IDENTIFIER  CTR_PTCP_ERR_TYPE_ID,
CONTRACT_FAMILY_PARTICIPANT.CONTRACT_PARTICIPANT_ERROR_YEAR  CTR_PTCP_ERR_YR,
NULL CTR_PTCP_ERR_CD,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-ccms-cdc".CONTRACT_FAMILY_PARTICIPANT
WHERE CONTRACT_FAMILY_PARTICIPANT.op = 'D'