MERGE into
EDV.FRS_DMN_RS dv
 using(
 SELECT sub1.*
FROM
(	
	SELECT sub.*,
		   ROW_NUMBER() OVER (PARTITION BY DMN_NM ORDER BY LOAD_DT desc) DMN_NM_RANK
	FROM
	(
		select distinct
		coalesce(DMN.DMN_NM, '[NULL IN SOURCE]') DMN_NM,
		DMN.CDC_DT DATA_EFF_STRT_DT,
		DMN.DATA_SRC_NM DATA_SRC_NM,
		DMN.DMN_DESC DMN_DESC,
		DMN.DMN_ID DMN_ID,
		DMN.LOAD_DT LOAD_DT,
		DMN.CRE_DT SRC_CRE_DT,
		DMN.LAST_CHG_DT SRC_LAST_CHG_DT,
		DMN.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
		MD5(trim(both DMN.DMN_NM)||'~~'||trim(both DMN.DMN_DESC)||'~~'||DMN.DMN_ID||'~~'||to_char(DMN.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(DMN.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both DMN.LAST_CHG_USER_NM)) HASH_DIF
		FROM SQL_FARM_RCD_STG.DMN
		where DMN.cdc_oper_cd IN ('I','UN')
		order by DMN.CDC_DT
	) sub
) sub1
WHERE sub1.DMN_NM_RANK = 1
) stg 
 on ( 
coalesce(stg.DMN_ID,0) = coalesce(dv.DMN_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;