INSERT into
EDV.FRS_DMN_RS(
DMN_NM,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DMN_DESC,
DMN_ID,
LOAD_DT,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM, 
DATA_EFF_END_DT, 
LOAD_END_DT, 
HASH_DIF
)
(
SELECT stg.* from (
SELECT DISTINCT
coalesce(DMN.DMN_NM, '[NULL IN SOURCE]') DMN_NM,
DMN.CDC_DT DATA_EFF_STRT_DT,
DMN.DATA_SRC_NM DATA_SRC_NM,
DMN.DMN_DESC DMN_DESC,
DMN.DMN_ID DMN_ID,
DMN.LOAD_DT LOAD_DT,
DMN.CRE_DT SRC_CRE_DT,
DMN.LAST_CHG_DT SRC_LAST_CHG_DT,
DMN.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM ,
TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(trim(both DMN.DMN_NM)||'~~'||trim(both DMN.DMN_DESC)||'~~'||DMN.DMN_ID||'~~'||to_char(DMN.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(DMN.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both DMN.LAST_CHG_USER_NM)) HASH_DIF
FROM SQL_FARM_RCD_STG.DMN
where DMN.cdc_oper_cd IN ('I','UN')
order by DMN.CDC_DT
) stg 
LEFT JOIN  EDV.FRS_DMN_RS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists ( 
                select 1 from EDV.FRS_DMN_RS rs
				where stg.DMN_NM = rs.DMN_NM
				and stg.LOAD_DT = rs.LOAD_DT
			)
);

