MERGE into
EDV.FRS_DMN_RS dv
 using( select distinct
coalesce(DMN.DMN_NM, '[NULL IN SOURCE]') DMN_NM,
DMN.CDC_DT DATA_EFF_STRT_DT,
DMN.DATA_SRC_NM DATA_SRC_NM,
DMN.DMN_DESC DMN_DESC,
DMN.DMN_ID DMN_ID,
DMN.LOAD_DT LOAD_DT,
DMN.CRE_DT SRC_CRE_DT,
DMN.LAST_CHG_DT SRC_LAST_CHG_DT,
DMN.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
MD5(trim(both DMN.DMN_NM)||'~~'||trim(both DMN.DMN_DESC)||'~~'||DMN.DMN_ID||'~~'||to_char(DMN.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(DMN.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both DMN.LAST_CHG_USER_NM)) HASH_DIF
FROM SQL_FARM_RCD_STG.DMN where DMN.cdc_oper_cd = 'D'
order by DMN.CDC_DT
) stg 
 on ( 
coalesce(stg.DMN_ID,0) = coalesce(dv.DMN_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN INSERT(DMN_NM,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DMN_DESC,
DMN_ID,
LOAD_DT,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM, 
DATA_EFF_END_DT,
LOAD_END_DT,
HASH_DIF
) VALUES (
stg.DMN_NM,
stg.DATA_EFF_STRT_DT,
stg.DATA_SRC_NM,
stg.DMN_DESC,
stg.DMN_ID,
stg.LOAD_DT,
stg.SRC_CRE_DT,
stg.SRC_LAST_CHG_DT,
stg.SRC_LAST_CHG_USER_NM ,
stg.DATA_EFF_STRT_DT,stg.LOAD_DT,stg.HASH_DIF
);