Select
 DV.ACCT_REF_TYPE_DURB_ID
,DV.ACCT_REF_CD
,DV.ACCT_REF_DESC
,DV.CRE_DT
,DV.LAST_CHG_DT
,DV.DATA_STAT_CD
,DV.SRC_CRE_DT
,DV.SRC_CRE_USER_NM
,DV.SRC_LAST_CHG_DT
,DV.SRC_LAST_CHG_USER_NM
,DV.BUS_KEY
,DV.DEF_ERR_IND
,DV.BUS_KEY_ERR
From
(
SELECT  DV_ALL.* FROM
(
SELECT 
 DV_DR.DURB_ID  ACCT_REF_TYPE_DURB_ID
,DV_DR.ACCT_REF_TYPE_CD ACCT_REF_CD
,RCD_REF_ID_TYPE_NM ACCT_REF_DESC
,  TO_TIMESTAMP ('<V_BATCH_LOAD_DT>', 'YYYY-MM-DD HH24:MI:SS.FF') CRE_DT
,  TO_TIMESTAMP ('<V_BATCH_LOAD_DT>', 'YYYY-MM-DD HH24:MI:SS.FF') LAST_CHG_DT
,'A' DATA_STAT_CD
,SRC_CRE_DT
,SRC_CRE_USER_NM
,SRC_LAST_CHG_DT
,SRC_LAST_CHG_USER_NM
,DV_DR.ACCT_REF_TYPE_CD As BUS_KEY
,CASE WHEN DV_DR.DURB_ID >0 THEN 0 ELSE 1  END DEF_ERR_IND
/* USED BY DS JOB TO RANK THE MULTIPLE BUSINESS KEYS */ 
,'ACCT_REF_TYPE_CD: ' || DV_DR.ACCT_REF_TYPE_CD BUS_KEY_ERR
FROM (SELECT * FROM EDV.ACCT_REF_TYPE_RH WHERE DATA_SRC_NM <> 'SYSGEN' 
   AND  (LOAD_DT) <= TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
     ) DV_DR
LEFT JOIN 
(
SELECT 
ACCT_REF_TYPE_CD,
RCD_REF_ID_TYPE_NM,
SRC_CRE_DT,
SRC_CRE_USER_NM,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM
FROM 
(
SELECT 
     ACCT_REF_TYPE_CD,
    RCD_REF_ID_TYPE_NM,
    SRC_CRE_DT     SRC_CRE_DT,
    SRC_CRE_USER_NM    SRC_CRE_USER_NM,
    SRC_LAST_CHG_DT    SRC_LAST_CHG_DT,
    SRC_LAST_CHG_USER_NM
FROM EDV.ACCT_REF_TYPE_RS
WHERE DATA_EFF_END_DT = TO_DATE('12/31/9999','MM/DD/YYYY') 
 AND  (DATA_EFF_STRT_DT) <= TO_TIMESTAMP ('{ETL_START_DATE}','YYYY-MM-DD')
) as t1
)RS
ON (DV_DR.ACCT_REF_TYPE_CD = RS.ACCT_REF_TYPE_CD)
) DV_ALL

)DV
LEFT JOIN pymt_dm_stg.ACCT_REF_TYPE_DIM DM
 ON (
(DV.ACCT_REF_CD,'EDW_DEFAULT') = (DM.ACCT_REF_CD,'EDW_DEFAULT')
AND DM.DATA_STAT_CD = 'A' 
)
WHERE
 (
DM.ACCT_REF_CD IS NULL
)
ORDER BY BUS_KEY
