with cte as (
select 
	MD5('-1') CROP_FARM_L_ID_OHASH
	, MD5(MD5(upper(coalesce(CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.FARM_NBR,'--')))||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_TYPE_CD), '--'))) CROP_FARM_L_ID_HASH
	, CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_ID CROP_FARM_YR_MNG_VAL_ADJ_ID
	, CROP_FARM_YR_MNG_VAL_ADJ.LOAD_DT LOAD_DT
	, CROP_FARM_YR_MNG_VAL_ADJ.CDC_DT DATA_EFF_STRT_DT
	, CROP_FARM_YR_MNG_VAL_ADJ.DATA_SRC_NM DATA_SRC_NM
	, CROP_FARM_YR_MNG_VAL_ADJ.DATA_STAT_CD DATA_STAT_CD
	, CROP_FARM_YR_MNG_VAL_ADJ.CRE_DT SRC_CRE_DT
	, CROP_FARM_YR_MNG_VAL_ADJ.CRE_USER_NM SRC_CRE_USER_NM
	, CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_DT SRC_LAST_CHG_DT
	, CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
	, CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_DCP_ID CROP_FARM_YR_DCP_ID
	, FARM_CROP_ADJ_TYPE_RS.DMN_VAL_NM CROP_FARM_YR_ADJ_TYPE_NAME
	, CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY SRC_CROP_FARM_YR_ADJ_TYPE_CD
	, CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_RS SRC_CROP_FARM_YR_ADJ_RSN_CD
	, CROP_FARM_YR_MNG_VAL_ADJ.AFT_ADJ_VAL AFT_ADJ_VAL
	, CROP_FARM_YR_MNG_VAL_ADJ.BEF_ADJ_VAL BEF_ADJ_VAL
	, CROP_FARM_YR_MNG_VAL_ADJ.PGM_YR PGM_YR 
	, CROP_FARM_YR_MNG_VAL_ADJ.CDC_OPER_CD
	, to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT
	, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT
	, MD5(upper(coalesce(CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.FARM_NBR,'--'))||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.PGM_ABR)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_CD)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_TYPE_CD)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_ID||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.DATA_STAT_CD)||'~~'||to_char(CROP_FARM_YR_MNG_VAL_ADJ.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.CRE_USER_NM)||'~~'||to_char(CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_USER_NM)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_DCP_ID||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY||'~~'||trim(both FARM_CROP_ADJ_TYPE_RS.DMN_VAL_NM)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_RS||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.AFT_ADJ_VAL||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.BEF_ADJ_VAL||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.CROP_FARM_YR_MNG_VAL_ADJ
LEFT JOIN(select * from EDV.FARM_CROP_ADJ_TYPE_RS where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FARM_CROP_ADJ_TYPE_RS 
ON (CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY = FARM_CROP_ADJ_TYPE_RS.DMN_VAL_ID)
)
INSERT into 
	EDV.CROP_FARM_YR_ADJ_DCP_LS (
		CROP_FARM_L_ID
		, CROP_FARM_YR_MNG_VAL_ADJ_ID
		, LOAD_DT
		, DATA_EFF_STRT_DT
		, DATA_SRC_NM
		, DATA_STAT_CD
		, SRC_CRE_DT
		, SRC_CRE_USER_NM
		, SRC_LAST_CHG_DT
		, SRC_LAST_CHG_USER_NM
		, CROP_FARM_YR_DCP_ID
		, SRC_CROP_FARM_YR_ADJ_TYPE_CD
		, CROP_FARM_YR_ADJ_TYPE_NAME
		, SRC_CROP_FARM_YR_ADJ_RSN_CD
		, AFT_ADJ_VAL
		, BEF_ADJ_VAL
		, PGM_YR
		, DATA_EFF_END_DT
		, LOAD_END_DT
		, HASH_DIF
)
SELECT sub.*
from
(
SELECT 
	stg.*
	from (
		SELECT DISTINCT 
			cte.CROP_FARM_L_ID_OHASH AS crop_farm_l_id
			, cte.CROP_FARM_YR_MNG_VAL_ADJ_ID
			, cte.LOAD_DT
			, cte.DATA_EFF_STRT_DT
			, cte.DATA_SRC_NM
			, cte.DATA_STAT_CD
			, cte.SRC_CRE_DT
			, cte.SRC_CRE_USER_NM
			, cte.SRC_LAST_CHG_DT
			, cte.SRC_LAST_CHG_USER_NM
			, cte.CROP_FARM_YR_DCP_ID
			, cte.SRC_CROP_FARM_YR_ADJ_TYPE_CD
			, cte.CROP_FARM_YR_ADJ_TYPE_NAME
			, cte.SRC_CROP_FARM_YR_ADJ_RSN_CD
			, cte.AFT_ADJ_VAL
			, cte.BEF_ADJ_VAL
			, cte.PGM_YR 
			, cte.DATA_EFF_END_DT
			, cte.LOAD_END_DT
			, cte.HASH_DIF
		FROM cte
		WHERE cte.CROP_FARM_YR_DCP_ID IS NOT NULL 
		AND cte.CDC_OPER_CD IN ('I','UN')
		AND cte.CROP_FARM_L_ID_HASH IN (Select CROP_FARM_L_ID From EDV.CROP_FARM_L)

UNION

  SELECT DISTINCT 
		cte.CROP_FARM_L_ID_HASH AS crop_farm_l_id
	    ,  cte.CROP_FARM_YR_MNG_VAL_ADJ_ID
			, cte.LOAD_DT
			, cte.DATA_EFF_STRT_DT
			, cte.DATA_SRC_NM
			, cte.DATA_STAT_CD
			, cte.SRC_CRE_DT
			, cte.SRC_CRE_USER_NM
			, cte.SRC_LAST_CHG_DT
			, cte.SRC_LAST_CHG_USER_NM
			, cte.CROP_FARM_YR_DCP_ID
			, cte.SRC_CROP_FARM_YR_ADJ_TYPE_CD
			, cte.CROP_FARM_YR_ADJ_TYPE_NAME
			, cte.SRC_CROP_FARM_YR_ADJ_RSN_CD
			, cte.AFT_ADJ_VAL
			, cte.BEF_ADJ_VAL
			, cte.PGM_YR 
			, cte.DATA_EFF_END_DT
			, cte.LOAD_END_DT
			, cte.HASH_DIF
	FROM cte
	WHERE cte.CROP_FARM_YR_DCP_ID IS NOT NULL and cte.CDC_OPER_CD IN ('I','UN')
	And cte.CROP_FARM_L_ID_HASH Not IN (Select CROP_FARM_L_ID From EDV.CROP_FARM_L)
	) stg
LEFT JOIN  EDV.CROP_FARM_YR_ADJ_DCP_LS dv
ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
) sub
WHERE not exists (select 1 from EDV.CROP_FARM_YR_ADJ_DCP_LS ls
                  where sub.crop_farm_l_id = ls.crop_farm_l_id  
				  and 	sub.crop_farm_yr_mng_val_adj_id = ls.crop_farm_yr_mng_val_adj_id
				  and sub.load_dt = ls.load_dt
                 )
;