SELECT 
crop_farm_year_managed_values_adjustment.crop_farm_year_managed_values_adjustment_identifier As CROP_FARM_YR_MNG_VAL_ADJ_ID,
crop_farm_year_managed_values_adjustment.year_arc_plc_participation_election_identifier As YR_ARC_PLC_PTCP_ELCT_ID,
crop_farm_year_managed_values_adjustment.farm_year_crop_irrigation_history_identifier As FARM_YR_CROP_IRR_HIST_ID,
crop_farm_year_managed_values_adjustment.crop_farm_year_dcp_identifier As CROP_FARM_YR_DCP_ID,
crop_farm_year_managed_values_adjustment.crop_farm_year_managed_values_adjustment_type_code As CROP_FARM_YR_MNG_VAL_ADJ_TY,
crop_farm_year_managed_values_adjustment.crop_farm_year_managed_values_adjustment_reason_code As CROP_FARM_YR_MNG_VAL_ADJ_RS,
crop_farm_year_managed_values_adjustment.after_adjustment_value As AFT_ADJ_VAL,
crop_farm_year_managed_values_adjustment.before_adjustment_value As BEF_ADJ_VAL,
farm.farm_number As FARM_NBR,
county_office_control.state_fsa_code As ST_FSA_CD,
county_office_control.county_fsa_code As CNTY_FSA_CD,
time_period.time_period_name As PGM_YR,
crop.fsa_crop_type_code As FSA_CROP_TYPE_CD, 
crop.fsa_crop_code As FSA_CROP_CD,
crop.program_abbreviation As PGM_ABR,
crop_farm_year_managed_values_adjustment.data_status_code As DATA_STAT_CD,
crop_farm_year_managed_values_adjustment.creation_date As CRE_DT,
crop_farm_year_managed_values_adjustment.creation_user_name As CRE_USER_NM,
crop_farm_year_managed_values_adjustment.last_change_date As LAST_CHG_DT,
crop_farm_year_managed_values_adjustment.last_change_user_name As LAST_CHG_USER_NM
From farm_records_reporting.crop_farm_year_managed_values_adjustment
LEFT JOIN farm_records_reporting.year_arc_plc_participation_election ON 
(year_arc_plc_participation_election.year_arc_plc_participation_election_identifier=crop_farm_year_managed_values_adjustment.year_arc_plc_participation_election_identifier)
JOIN farm_records_reporting.farm_year ON (year_arc_plc_participation_election.farm_year_identifier= farm_year.farm_year_identifier)
JOIN farm_records_reporting.crop ON (year_arc_plc_participation_election.crop_identifier=crop.crop_identifier)
JOIN farm_records_reporting.farm ON (farm_year.farm_identifier= farm.farm_identifier)
JOIN farm_records_reporting.county_office_control ON (farm.county_office_control_identifier=county_office_control.county_office_control_identifier)
JOIN farm_records_reporting.time_period on (farm_year.time_period_identifier =time_period.time_period_identifier)
Where crop_farm_year_managed_values_adjustment.year_arc_plc_participation_election_identifier IS NOT NULL
UNION 
SELECT 
crop_farm_year_managed_values_adjustment.crop_farm_year_managed_values_adjustment_identifier As CROP_FARM_YR_MNG_VAL_ADJ_ID,
crop_farm_year_managed_values_adjustment.year_arc_plc_participation_election_identifier As YR_ARC_PLC_PTCP_ELCT_ID,
crop_farm_year_managed_values_adjustment.farm_year_crop_irrigation_history_identifier As FARM_YR_CROP_IRR_HIST_ID,
crop_farm_year_managed_values_adjustment.crop_farm_year_dcp_identifier As CROP_FARM_YR_DCP_ID,
crop_farm_year_managed_values_adjustment.crop_farm_year_managed_values_adjustment_type_code As CROP_FARM_YR_MNG_VAL_ADJ_TY,
crop_farm_year_managed_values_adjustment.crop_farm_year_managed_values_adjustment_reason_code As CROP_FARM_YR_MNG_VAL_ADJ_RS,
crop_farm_year_managed_values_adjustment.after_adjustment_value As AFT_ADJ_VAL,
crop_farm_year_managed_values_adjustment.before_adjustment_value As BEF_ADJ_VAL,
farm.farm_number As FARM_NBR,
county_office_control.state_fsa_code As ST_FSA_CD,
county_office_control.county_fsa_code As CNTY_FSA_CD,
time_period.time_period_name As PGM_YR,
crop.fsa_crop_type_code As FSA_CROP_TYPE_CD, 
crop.fsa_crop_code As FSA_CROP_CD,
crop.program_abbreviation As PGM_ABR,
crop_farm_year_managed_values_adjustment.data_status_code As DATA_STAT_CD,
crop_farm_year_managed_values_adjustment.creation_date As CRE_DT,
crop_farm_year_managed_values_adjustment.creation_user_name As CRE_USER_NM,
crop_farm_year_managed_values_adjustment.last_change_date As LAST_CHG_DT,
crop_farm_year_managed_values_adjustment.last_change_user_name As LAST_CHG_USER_NM
From farm_records_reporting.crop_farm_year_managed_values_adjustment
LEFT JOIN farm_records_reporting.farm_year_crop_irrigation_history ON 
(farm_year_crop_irrigation_history.farm_year_crop_irrigation_history_identifier=crop_farm_year_managed_values_adjustment.farm_year_crop_irrigation_history_identifier)
JOIN farm_records_reporting.irrigation_county_crop ON (farm_year_crop_irrigation_history.irrigation_county_crop_identifier=irrigation_county_crop.irrigation_county_crop_identifier)
JOIN farm_records_reporting.crop ON (irrigation_county_crop.crop_identifier=crop.crop_identifier)
JOIN farm_records_reporting.farm_year ON (farm_year_crop_irrigation_history.farm_year_identifier= farm_year.farm_year_identifier)
JOIN farm_records_reporting.farm ON (farm_year.farm_identifier= farm.farm_identifier)
JOIN farm_records_reporting.county_office_control ON (farm.county_office_control_identifier=county_office_control.county_office_control_identifier)
JOIN farm_records_reporting.time_period on (farm_year.time_period_identifier =time_period.time_period_identifier)
Where crop_farm_year_managed_values_adjustment.farm_year_crop_irrigation_history_identifier IS NOT NULL
AND crop_farm_year_managed_values_adjustment.year_arc_plc_participation_election_identifier IS NULL
UNION
SELECT 
crop_farm_year_managed_values_adjustment.crop_farm_year_managed_values_adjustment_identifier As CROP_FARM_YR_MNG_VAL_ADJ_ID,
crop_farm_year_managed_values_adjustment.year_arc_plc_participation_election_identifier As YR_ARC_PLC_PTCP_ELCT_ID,
crop_farm_year_managed_values_adjustment.farm_year_crop_irrigation_history_identifier As FARM_YR_CROP_IRR_HIST_ID,
crop_farm_year_managed_values_adjustment.crop_farm_year_dcp_identifier As CROP_FARM_YR_DCP_ID,
crop_farm_year_managed_values_adjustment.crop_farm_year_managed_values_adjustment_type_code As CROP_FARM_YR_MNG_VAL_ADJ_TY,
crop_farm_year_managed_values_adjustment.crop_farm_year_managed_values_adjustment_reason_code As CROP_FARM_YR_MNG_VAL_ADJ_RS,
crop_farm_year_managed_values_adjustment.after_adjustment_value As AFT_ADJ_VAL,
crop_farm_year_managed_values_adjustment.before_adjustment_value As BEF_ADJ_VAL,
farm.farm_number As FARM_NBR,
county_office_control.state_fsa_code As ST_FSA_CD,
county_office_control.county_fsa_code As CNTY_FSA_CD,
time_period.time_period_name As PGM_YR,
crop.fsa_crop_type_code As FSA_CROP_TYPE_CD, 
crop.fsa_crop_code As FSA_CROP_CD,
crop.program_abbreviation As PGM_ABR,
crop_farm_year_managed_values_adjustment.data_status_code As DATA_STAT_CD,
crop_farm_year_managed_values_adjustment.creation_date As CRE_DT,
crop_farm_year_managed_values_adjustment.creation_user_name As CRE_USER_NM,
crop_farm_year_managed_values_adjustment.last_change_date As LAST_CHG_DT,
crop_farm_year_managed_values_adjustment.last_change_user_name As LAST_CHG_USER_NM
From farm_records_reporting.crop_farm_year_managed_values_adjustment
LEFT JOIN farm_records_reporting.crop_farm_year_dcp ON (crop_farm_year_dcp.crop_farm_year_dcp_identifier=crop_farm_year_managed_values_adjustment.crop_farm_year_dcp_identifier)
JOIN farm_records_reporting.crop ON (crop_farm_year_dcp.crop_identifier = crop.crop_identifier)
JOIN farm_records_reporting.farm_year_dcp ON (crop_farm_year_dcp.farm_year_dcp_identifier=farm_year_dcp.farm_year_dcp_identifier)
JOIN farm_records_reporting.farm_year ON (farm_year_dcp.farm_year_identifier= farm_year.farm_year_identifier)
JOIN farm_records_reporting.farm ON (farm_year.farm_identifier= farm.farm_identifier)
JOIN farm_records_reporting.county_office_control ON (farm.county_office_control_identifier=county_office_control.county_office_control_identifier)
JOIN farm_records_reporting.time_period on (farm_year.time_period_identifier =time_period.time_period_identifier)
Where crop_farm_year_managed_values_adjustment.crop_farm_year_dcp_identifier IS NOT NULL
AND crop_farm_year_managed_values_adjustment.farm_year_crop_irrigation_history_identifier IS  NULL
AND crop_farm_year_managed_values_adjustment.year_arc_plc_participation_election_identifier IS NULL