-- Julia Lu edition - will update this paragraph and query when cnsv-cdc is ready
-- Stage SQL: CNSV_EWT51OCHST (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_EWT51OCHST/incremental/CNSV_EWT51OCHST.sql
-- =============================================================================

SELECT * FROM
(
SELECT PGM_YR,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
TR_NBR,
OFR_SCNR_NM,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
CROP_YR,
FLD_NBR,
CNSV_PRAC_CD,
FSA_MULT_CROP_CD,
FSA_MULT_CROP_NM,
FARM_NBR,
OFR_ACRG,
FSA_578_ACRG,
CRP_CROP_ASGN_IND,
CROP_PROD_QTY,
CROP_HVST_DT,
CNSV_CTR_SEQ_NBR,
CNSV_CTR_SFX_CD,
OFR_SCNR_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
-- op,
TBL_PRIORITY,
ROW_NUMBER() over ( partition by 
CROP_YR,
FLD_NBR,
CNSV_PRAC_CD,
OFR_SCNR_ID
--order by TBL_PRIORITY ASC, LAST_CHG_DT DESC, __CDC_STARTLSN DESC, __CDC_SEQVAL DESC) AS row_num_part
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC) AS row_num_part
FROM
(
SELECT 
NET_CHANGES.PGM_YR,
NET_CHANGES.ADM_ST_FSA_CD,
NET_CHANGES.ADM_CNTY_FSA_CD,
NET_CHANGES.TR_NBR,
NET_CHANGES.OFR_SCNR_NM,
NET_CHANGES.SGNP_TYPE_DESC,
NET_CHANGES.SGNP_STYPE_DESC,
NET_CHANGES.SGNP_NBR,
NET_CHANGES.SGNP_STYPE_AGR_NM,
NET_CHANGES.CROP_YR,
NET_CHANGES.FLD_NBR,
NET_CHANGES.CNSV_PRAC_CD,
NET_CHANGES.FSA_MULT_CROP_CD,
NET_CHANGES.FSA_MULT_CROP_NM,
NET_CHANGES.FARM_NBR,
NET_CHANGES.OFR_ACRG,
NET_CHANGES.FSA_578_ACRG,
NET_CHANGES.CRP_CROP_ASGN_IND,
NET_CHANGES.CROP_PROD_QTY,
NET_CHANGES.CROP_HVST_DT,
NET_CHANGES.CNSV_CTR_SEQ_NBR,
NET_CHANGES.CNSV_CTR_SFX_CD,
NET_CHANGES.OFR_SCNR_ID,
NET_CHANGES.DATA_STAT_CD,
NET_CHANGES.CRE_DT,
NET_CHANGES.LAST_CHG_DT,
NET_CHANGES.LAST_CHG_USER_NM,
--NET_CHANGES.__CDC_OPERATION,
-- op,
NET_CHANGES.TBL_PRIORITY,
--NET_CHANGES.__CDC_STARTLSN,
--NET_CHANGES.__CDC_SEQVAL
0 AS row_num_part
FROM ( 
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt51ochst.CROP_YR CROP_YR,
ewt51ochst.FLD_NBR FLD_NBR,
ewt51ochst.CNSV_PRAC_CD CNSV_PRAC_CD,
ewt51ochst.FSA_MULT_CROP_CD FSA_MULT_CROP_CD,
ewt51ochst.FSA_MULT_CROP_NM FSA_MULT_CROP_NM,
ewt40ofrsc.FARM_NBR FARM_NBR,
ewt51ochst.OFR_ACRG OFR_ACRG,
ewt51ochst.FSA_578_ACRG FSA_578_ACRG,
ewt51ochst.CRP_CROP_ASGN_IND CRP_CROP_ASGN_IND,
ewt51ochst.CROP_PROD_QTY CROP_PROD_QTY,
ewt51ochst.CROP_HVST_DT CROP_HVST_DT,
ewt40ofrsc.CNSV_CTR_SEQ_NBR CNSV_CTR_SEQ_NBR,
ewt40ofrsc.CNSV_CTR_SUFX_CD CNSV_CTR_SFX_CD,
ewt51ochst.OFR_SCNR_ID OFR_SCNR_ID,
ewt51ochst.DATA_STAT_CD DATA_STAT_CD,
ewt51ochst.CRE_DT CRE_DT,
ewt51ochst.LAST_CHG_DT LAST_CHG_DT,
ewt51ochst.LAST_CHG_USER_NM LAST_CHG_USER_NM,
--__CDC_OPERATION,
-- op,
1 AS TBL_PRIORITY,
--__CDC_STARTLSN,
1 AS row_num_part
--ROW_NUMBER() over ( partition by 
--EWT51OCHST.CROP_YR,
--EWT51OCHST.FLD_NBR,
--EWT51OCHST.CNSV_PRAC_CD,
--EWT51OCHST.OFR_SCNR_ID
--order by EWT51OCHST.__CDC_STARTLSN DESC, EWT51OCHST.__CDC_SEQVAL DESC  ) AS row_num_part
FROM  "fsa-prod-cnsv".EWT51OCHST 
LEFT JOIN "fsa-prod-cnsv".EWT40OFRSC 
ON (EWT51OCHST.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN "fsa-prod-cnsv".EWT14SGNP 
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
-- WHERE __CDC_OPERATION <> 'D'
) NET_CHANGES
WHERE NET_CHANGES.row_num_part = 1

UNION
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt51ochst.CROP_YR CROP_YR,
ewt51ochst.FLD_NBR FLD_NBR,
ewt51ochst.CNSV_PRAC_CD CNSV_PRAC_CD,
ewt51ochst.FSA_MULT_CROP_CD FSA_MULT_CROP_CD,
ewt51ochst.FSA_MULT_CROP_NM FSA_MULT_CROP_NM,
ewt40ofrsc.FARM_NBR FARM_NBR,
ewt51ochst.OFR_ACRG OFR_ACRG,
ewt51ochst.FSA_578_ACRG FSA_578_ACRG,
ewt51ochst.CRP_CROP_ASGN_IND CRP_CROP_ASGN_IND,
ewt51ochst.CROP_PROD_QTY CROP_PROD_QTY,
ewt51ochst.CROP_HVST_DT CROP_HVST_DT,
ewt40ofrsc.CNSV_CTR_SEQ_NBR CNSV_CTR_SEQ_NBR,
ewt40ofrsc.CNSV_CTR_SUFX_CD CNSV_CTR_SFX_CD,
ewt51ochst.OFR_SCNR_ID OFR_SCNR_ID,
ewt51ochst.DATA_STAT_CD DATA_STAT_CD,
ewt51ochst.CRE_DT CRE_DT,
ewt51ochst.LAST_CHG_DT LAST_CHG_DT,
ewt51ochst.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
2 AS TBL_PRIORITY,
--1 AS __CDC_STARTLSN,
1 AS __CDC_SEQVAL
FROM "fsa-prod-cnsv".EWT40OFRSC 
JOIN "fsa-prod-cnsv".EWT51OCHST 
ON (EWT51OCHST.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN "fsa-prod-cnsv".EWT14SGNP 
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
-- WHERE __CDC_OPERATION <> 'D'

UNION
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt51ochst.CROP_YR CROP_YR,
ewt51ochst.FLD_NBR FLD_NBR,
ewt51ochst.CNSV_PRAC_CD CNSV_PRAC_CD,
ewt51ochst.FSA_MULT_CROP_CD FSA_MULT_CROP_CD,
ewt51ochst.FSA_MULT_CROP_NM FSA_MULT_CROP_NM,
ewt40ofrsc.FARM_NBR FARM_NBR,
ewt51ochst.OFR_ACRG OFR_ACRG,
ewt51ochst.FSA_578_ACRG FSA_578_ACRG,
ewt51ochst.CRP_CROP_ASGN_IND CRP_CROP_ASGN_IND,
ewt51ochst.CROP_PROD_QTY CROP_PROD_QTY,
ewt51ochst.CROP_HVST_DT CROP_HVST_DT,
ewt40ofrsc.CNSV_CTR_SEQ_NBR CNSV_CTR_SEQ_NBR,
ewt40ofrsc.CNSV_CTR_SUFX_CD CNSV_CTR_SFX_CD,
ewt51ochst.OFR_SCNR_ID OFR_SCNR_ID,
ewt51ochst.DATA_STAT_CD DATA_STAT_CD,
ewt51ochst.CRE_DT CRE_DT,
ewt51ochst.LAST_CHG_DT LAST_CHG_DT,
ewt51ochst.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
3 AS TBL_PRIORITY,
--1 AS __CDC_STARTLSN,
1 AS __CDC_SEQVAL
FROM "fsa-prod-cnsv".EWT14SGNP 
LEFT JOIN "fsa-prod-cnsv".EWT40OFRSC 
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
JOIN "fsa-prod-cnsv".EWT51OCHST 
ON (EWT51OCHST.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID)

UNION
SELECT 
DELETE_NET.PGM_YR,
DELETE_NET.ADM_ST_FSA_CD,
DELETE_NET.ADM_CNTY_FSA_CD,
DELETE_NET.TR_NBR,
DELETE_NET.OFR_SCNR_NM,
DELETE_NET.SGNP_TYPE_DESC,
DELETE_NET.SGNP_STYPE_DESC,
DELETE_NET.SGNP_NBR,
DELETE_NET.SGNP_STYPE_AGR_NM,
DELETE_NET.CROP_YR,
DELETE_NET.FLD_NBR,
DELETE_NET.CNSV_PRAC_CD,
DELETE_NET.FSA_MULT_CROP_CD,
DELETE_NET.FSA_MULT_CROP_NM,
DELETE_NET.FARM_NBR,
DELETE_NET.OFR_ACRG,
DELETE_NET.FSA_578_ACRG,
DELETE_NET.CRP_CROP_ASGN_IND,
DELETE_NET.CROP_PROD_QTY,
DELETE_NET.CROP_HVST_DT,
DELETE_NET.CNSV_CTR_SEQ_NBR,
DELETE_NET.CNSV_CTR_SFX_CD,
DELETE_NET.OFR_SCNR_ID,
DELETE_NET.DATA_STAT_CD,
DELETE_NET.CRE_DT,
DELETE_NET.LAST_CHG_DT,
DELETE_NET.LAST_CHG_USER_NM,
DELETE_NET.TBL_PRIORITY,
-- op,
--DELETE_NET.__CDC_STARTLSN,
--DELETE_NET.__CDC_SEQVAL
1 As CDC_SEQVAL
FROM (
SELECT
NULL PGM_YR,
NULL ADM_ST_FSA_CD,
NULL ADM_CNTY_FSA_CD,
NULL TR_NBR,
NULL OFR_SCNR_NM,
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
EWT51OCHST.CROP_YR CROP_YR,
EWT51OCHST.FLD_NBR FLD_NBR,
EWT51OCHST.CNSV_PRAC_CD CNSV_PRAC_CD,
EWT51OCHST.FSA_MULT_CROP_CD FSA_MULT_CROP_CD,
EWT51OCHST.FSA_MULT_CROP_NM FSA_MULT_CROP_NM,
NULL FARM_NBR,
EWT51OCHST.OFR_ACRG OFR_ACRG,
EWT51OCHST.FSA_578_ACRG FSA_578_ACRG,
EWT51OCHST.CRP_CROP_ASGN_IND CRP_CROP_ASGN_IND,
EWT51OCHST.CROP_PROD_QTY CROP_PROD_QTY,
EWT51OCHST.CROP_HVST_DT CROP_HVST_DT,
NULL CNSV_CTR_SEQ_NBR,
NULL CNSV_CTR_SFX_CD,
EWT51OCHST.OFR_SCNR_ID OFR_SCNR_ID,
EWT51OCHST.DATA_STAT_CD DATA_STAT_CD,
EWT51OCHST.CRE_DT CRE_DT,
EWT51OCHST.LAST_CHG_DT LAST_CHG_DT,
EWT51OCHST.LAST_CHG_USER_NM LAST_CHG_USER_NM,
1 AS TBL_PRIORITY,
--ROW_NUMBER() over ( partition by --EWT51OCHST.CROP_YR,--EWT51OCHST.FLD_NBR,--EWT51OCHST.CNSV_PRAC_CD,--EWT51OCHST.OFR_SCNR_ID--order by EWT51OCHST.__CDC_STARTLSN DESC, EWT51OCHST.__CDC_SEQVAL DESC ) AS row_num_part1 As row_num_part
FROM "fsa-prod-cnsv".EWT51OCHST
--WHERE __CDC_OPERATION = 'D'
)DELETE_NET
WHERE DELETE_NET.row_num_part = 1

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('2025-07-01' AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('2025-07-01' AS DATE))
)
