INSERT INTO EDV.IRS_AGI_ELG_ERR_CAT_RH (IRS_AGI_ELG_ERR_CAT_CD, LOAD_DT, DATA_SRC_NM)
  (SELECT stg.IRS_AGI_ELG_ERR_CAT_CD,
          stg.LOAD_DT,
          stg.DATA_SRC_NM
   FROM
     (SELECT DISTINCT COALESCE (IRS_AGI_ELG_CAT_TYPE.IRS_AGI_ELG_ERR_CAT_CD,
                           '--') IRS_AGI_ELG_ERR_CAT_CD,
                          IRS_AGI_ELG_CAT_TYPE.LOAD_DT LOAD_DT,
                          IRS_AGI_ELG_CAT_TYPE.DATA_SRC_NM DATA_SRC_NM,
                          ROW_NUMBER () OVER (PARTITION BY IRS_AGI_ELG_CAT_TYPE.IRS_AGI_ELG_ERR_CAT_CD
                                              ORDER BY IRS_AGI_ELG_CAT_TYPE.CDC_DT DESC, IRS_AGI_ELG_CAT_TYPE.LOAD_DT DESC) STG_EFF_DT_RANK
      FROM SBSD_STG.IRS_AGI_ELG_CAT_TYPE) stg
   LEFT JOIN EDV.IRS_AGI_ELG_ERR_CAT_RH dv ON (stg.IRS_AGI_ELG_ERR_CAT_CD = dv.IRS_AGI_ELG_ERR_CAT_CD)
   WHERE (dv.IRS_AGI_ELG_ERR_CAT_CD IS NULL)
     AND stg.STG_EFF_DT_RANK = 1 )