INSERT INTO EDV.DIR_ATRB_PRPS_PYMT_LS (DIR_ATRB_PRPS_PYMT_L_ID, PRPS_PYMT_ID, LOAD_DT, DATA_EFF_STRT_DT, DATA_SRC_NM, DATA_STAT_CD, SRC_CRE_DT, SRC_CRE_USER_NM, SRC_LAST_CHG_DT, SRC_LAST_CHG_USER_NM, ST_FSA_CD, CNTY_FSA_CD, ACCT_PGM_CD, PAID_CORE_CUST_ID, SBSD_PRD_STRT_YR, RCD_REF_PRIM_ID_TYPE_CD, RCD_REF_SCND_ID_TYPE_CD, PROC_RQST_REF_NBR, RCD_REF_PRIM_ID, RCD_REF_SCND_ID, CMDY_CD, PYMT_AMT, PYMT_LMT_IND, HRCH_PYMT_LMT_IND, PRST_OPYMT_ATRB_IND, APP_3_OWNSHP_LVL_LMT_IND, DEC_PRCS_NBR, PYMT_ATRB_RQST_RSN_TXT, PYMT_ATRB_RVRS_DT, OVRRD_SBSD_PRD_STRT_YR, PYMT_PGM_ID, PYMT_LMT_YR, OBL_CNFRM_NBR, PRV_PRPS_PYMT_ID, PRV_PRPS_PYMT_SBSD_PRD_STRT_YR, PRV_PRPS_PYMT_ST_FSA_CD, PRV_PRPS_PYMT_CNTY_FSA_CD, PRV_PRPS_PYMT_ACCT_PGM_CD, PRV_PRPS_PYMT_CORE_CUST_ID, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
  (SELECT stg.*
   FROM
     (SELECT DISTINCT MD5 (upper(COALESCE (trim(PRPS_PYMT.ST_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(PRPS_PYMT.CNTY_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(PRPS_PYMT.ACCT_PGM_CD), '--')) ||'~~'||COALESCE (PRPS_PYMT.PAID_CORE_CUST_ID, '-1')) AS DIR_ATRB_PRPS_PYMT_L_ID,
                      coalesce(PRPS_PYMT.PRPS_PYMT_ID, '-1') PRPS_PYMT_ID,
                      PRPS_PYMT.LOAD_DT LOAD_DT,
                      PRPS_PYMT.CDC_DT DATA_EFF_STRT_DT,
                      PRPS_PYMT.DATA_SRC_NM DATA_SRC_NM,
                      PRPS_PYMT.DATA_STAT_CD DATA_STAT_CD,
                      PRPS_PYMT.CRE_DT SRC_CRE_DT,
                      PRPS_PYMT.CRE_USER_NM SRC_CRE_USER_NM,
                      PRPS_PYMT.LAST_CHG_DT SRC_LAST_CHG_DT,
                      PRPS_PYMT.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
                      PRPS_PYMT.ST_FSA_CD ST_FSA_CD,
                      PRPS_PYMT.CNTY_FSA_CD CNTY_FSA_CD,
                      PRPS_PYMT.ACCT_PGM_CD ACCT_PGM_CD,
                      PRPS_PYMT.PAID_CORE_CUST_ID PAID_CORE_CUST_ID,
                      PRPS_PYMT.SBSD_PRD_STRT_YR SBSD_PRD_STRT_YR,
                      PRPS_PYMT.RCD_REF_PRIM_ID_TYPE_CD RCD_REF_PRIM_ID_TYPE_CD,
                      PRPS_PYMT.RCD_REF_SCND_ID_TYPE_CD RCD_REF_SCND_ID_TYPE_CD,
                      PRPS_PYMT.PROC_RQST_REF_NBR PROC_RQST_REF_NBR,
                      PRPS_PYMT.RCD_REF_PRIM_ID RCD_REF_PRIM_ID,
                      PRPS_PYMT.RCD_REF_SCND_ID RCD_REF_SCND_ID,
                      PRPS_PYMT.CMDY_CD CMDY_CD,
                      PRPS_PYMT.PYMT_AMT PYMT_AMT,
                      PRPS_PYMT.PYMT_LMT_IND PYMT_LMT_IND,
                      PRPS_PYMT.HRCH_PYMT_LMT_IND HRCH_PYMT_LMT_IND,
                      PRPS_PYMT.PRST_OPYMT_ATRB_IND PRST_OPYMT_ATRB_IND,
                      PRPS_PYMT.APP_3_OWNSHP_LVL_LMT_IND APP_3_OWNSHP_LVL_LMT_IND,
                      PRPS_PYMT.DEC_PRCS_NBR DEC_PRCS_NBR,
                      PRPS_PYMT.PYMT_ATRB_RQST_RSN_TXT PYMT_ATRB_RQST_RSN_TXT,
                      PRPS_PYMT.PYMT_ATRB_RVRS_DT PYMT_ATRB_RVRS_DT,
                      PRPS_PYMT.OVRRD_SBSD_PRD_STRT_YR OVRRD_SBSD_PRD_STRT_YR,
                      PRPS_PYMT.PYMT_PGM_ID PYMT_PGM_ID,
                      PRPS_PYMT.PYMT_LMT_YR PYMT_LMT_YR,
                      PRPS_PYMT.OBL_CNFRM_NBR OBL_CNFRM_NBR,
                      PRPS_PYMT.PRV_PRPS_PYMT_ID PRV_PRPS_PYMT_ID,
                      PRPS_PYMT.PRV_PRPS_PYMT_SBSD_PRD_STRT_YR PRV_PRPS_PYMT_SBSD_PRD_STRT_YR,
                      PRPS_PYMT.PRV_PRPS_PYMT_ST_FSA_CD PRV_PRPS_PYMT_ST_FSA_CD,
                      PRPS_PYMT.PRV_PRPS_PYMT_CNTY_FSA_CD PRV_PRPS_PYMT_CNTY_FSA_CD,
                      PRPS_PYMT.PRV_PRPS_PYMT_ACCT_PGM_CD PRV_PRPS_PYMT_ACCT_PGM_CD,
                      PRPS_PYMT.PRV_PRPS_PYMT_CORE_CUST_ID PRV_PRPS_PYMT_CORE_CUST_ID,
                      to_date('9999-12-31', 'YYYY-MM-DD') DATA_EFF_END_DT,
                      to_date('9999-12-31', 'YYYY-MM-DD') LOAD_END_DT,
                      MD5 (trim(PRPS_PYMT.ST_FSA_CD)||'~~'||trim(PRPS_PYMT.CNTY_FSA_CD)||'~~'||trim(PRPS_PYMT.ACCT_PGM_CD)||'~~'||PRPS_PYMT.PAID_CORE_CUST_ID||'~~'||PRPS_PYMT.PRPS_PYMT_ID||'~~'||trim(PRPS_PYMT.DATA_STAT_CD)||'~~'||to_char(PRPS_PYMT.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PRPS_PYMT.CRE_USER_NM)||'~~'||to_char(PRPS_PYMT.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PRPS_PYMT.LAST_CHG_USER_NM)||'~~'||trim(PRPS_PYMT.ST_FSA_CD)||'~~'||trim(PRPS_PYMT.CNTY_FSA_CD)||'~~'||trim(PRPS_PYMT.ACCT_PGM_CD)||'~~'||PRPS_PYMT.PAID_CORE_CUST_ID||'~~'||PRPS_PYMT.SBSD_PRD_STRT_YR||'~~'||trim(PRPS_PYMT.RCD_REF_PRIM_ID_TYPE_CD)||'~~'||trim(PRPS_PYMT.RCD_REF_SCND_ID_TYPE_CD)||'~~'||PRPS_PYMT.PROC_RQST_REF_NBR||'~~'||trim(PRPS_PYMT.RCD_REF_PRIM_ID)||'~~'||trim(PRPS_PYMT.RCD_REF_SCND_ID)||'~~'||trim(PRPS_PYMT.CMDY_CD)||'~~'||PRPS_PYMT.PYMT_AMT||'~~'||trim(PRPS_PYMT.PYMT_LMT_IND)||'~~'||trim(PRPS_PYMT.HRCH_PYMT_LMT_IND)||'~~'||trim(PRPS_PYMT.PRST_OPYMT_ATRB_IND)||'~~'||trim(PRPS_PYMT.APP_3_OWNSHP_LVL_LMT_IND)||'~~'||PRPS_PYMT.DEC_PRCS_NBR||'~~'||trim(PRPS_PYMT.PYMT_ATRB_RQST_RSN_TXT)||'~~'||to_char(PRPS_PYMT.PYMT_ATRB_RVRS_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||PRPS_PYMT.OVRRD_SBSD_PRD_STRT_YR||'~~'||PRPS_PYMT.PYMT_PGM_ID||'~~'||PRPS_PYMT.PYMT_LMT_YR||'~~'||PRPS_PYMT.OBL_CNFRM_NBR||'~~'||PRPS_PYMT.PRV_PRPS_PYMT_ID||'~~'||PRPS_PYMT.PRV_PRPS_PYMT_SBSD_PRD_STRT_YR||'~~'||trim(PRPS_PYMT.PRV_PRPS_PYMT_ST_FSA_CD)||'~~'||trim(PRPS_PYMT.PRV_PRPS_PYMT_CNTY_FSA_CD)||'~~'||trim(PRPS_PYMT.PRV_PRPS_PYMT_ACCT_PGM_CD)||'~~'||PRPS_PYMT.PRV_PRPS_PYMT_CORE_CUST_ID) HASH_DIF
      FROM SBSD_STG.PRPS_PYMT PRPS_PYMT
      WHERE PRPS_PYMT.CDC_OPER_CD IN ('I',
                                      'UN')
        AND date(PRPS_PYMT.CDC_DT) = date(TO_TIMESTAMP ('{ETL_START_TIMESTAMP}', 'YYYY-MM-DD HH24:MI:SS.FF'))
      ORDER BY PRPS_PYMT.CDC_DT) stg
   LEFT JOIN EDV.DIR_ATRB_PRPS_PYMT_LS dv ON (stg.HASH_DIF = dv.HASH_DIF
                                              AND dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD'))
   WHERE dv.HASH_DIF IS NULL )