-- Julia Lu edition - will upthis paragraph and query when cnsv-cdc is ready
-- Stage SQL: CNSV_EWT41OCUST (incremental)
-- Location: s3://c108-cert-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_EWT41OCUST/incremental/CNSV_EWT41OCUST.sql
-- =============================================================================
select * from
(
select distinct pgm_yr,
adm_st_fsa_cd,
adm_cnty_fsa_cd,
tr_nbr,
ofr_scnr_nm,
sgnp_type_desc,
sgnp_stype_desc,
sgnp_nbr,
sgnp_stype_agr_nm,
core_cust_id,
ofr_invl_cd,
cmn_cust_nm,
adr_info_line,
dlvr_adr_line,
city_nm,
st_abr,
zip_cd,
phn_nbr,
ownr_pct,
cust_ofr_asgn_ind,
ofr_prim_prdr_ind,
auth_sgn_ind,
crp_cpld_elg_pct,
prdr_elg_ind,
agi_shr_pct,
inhrt_ctr_ind,
cnsv_ctr_seq_nbr,
cnsv_ctr_sfx_cd,
ofr_scnr_id,
data_stat_cd,
cre_dt,
last_chg_dt,
last_chg_user_nm,
beg_farm_dt,
beg_farm_ind,
ltd_rsrc_prdr_ind,
socl_dadvg_ind,
vet_cert_dter_dt,
vet_ind,
cdc_oper_cd,
load_dt,
data_src_nm,
cdc_dt,
row_number() over ( partition by 
core_cust_id,
ofr_scnr_id
order by tbl_priority asc, last_chg_dt desc ) as row_num_part
from
(
select 
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt41ocust.core_cust_id core_cust_id,
ewt41ocust.ofr_invl_cd ofr_invl_cd,
ewt41ocust.cmn_cust_nm cmn_cust_nm,
ewt41ocust.adr_info_line adr_info_line,
ewt41ocust.dlvr_adr_line dlvr_adr_line,
ewt41ocust.city_nm city_nm,
ewt41ocust.st_abr st_abr,
ewt41ocust.zip_cd zip_cd,
ewt41ocust.phn_nbr phn_nbr,
ewt41ocust.ownr_pct ownr_pct,
ewt41ocust.cust_ofr_asgn_ind cust_ofr_asgn_ind,
ewt41ocust.ofr_prim_prdr_ind ofr_prim_prdr_ind,
ewt41ocust.auth_sgn_ind auth_sgn_ind,
ewt41ocust.crp_cpld_elg_pct crp_cpld_elg_pct,
ewt41ocust.prdr_elg_ind prdr_elg_ind,
ewt41ocust.agi_shr_pct agi_shr_pct,
ewt41ocust.inhrt_ctr_ind inhrt_ctr_ind,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt41ocust.ofr_scnr_id ofr_scnr_id,
ewt41ocust.data_stat_cd data_stat_cd,
ewt41ocust.cre_dt cre_dt,
ewt41ocust.last_chg_dt last_chg_dt,
ewt41ocust.last_chg_user_nm last_chg_user_nm,
ewt41ocust.beg_farm_dt beg_farm_dt,
ewt41ocust.beg_farm_ind beg_farm_ind,
ewt41ocust.lmt_rsrc_prdr_ind ltd_rsrc_prdr_ind,
ewt41ocust.socl_dadvg_ind socl_dadvg_ind,
ewt41ocust.vet_cert_dter_dt vet_cert_dter_dt,
ewt41ocust.vet_ind vet_ind,
ewt41ocust.op as cdc_oper_cd,
current_timestamp() as load_dt,
'ewt41ocust' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as tbl_priority
from `fsa-{env}-cnsv-cdc`.`ewt41ocust`
left join `fsa-{env}-cnsv`.`ewt40ofrsc` on (ewt41ocust.ofr_scnr_id = ewt40ofrsc.ofr_scnr_id)
left join `fsa-{env}-cnsv`.`ewt14sgnp` on (ewt40ofrsc.sgnp_id = ewt14sgnp.sgnp_id)
where ewt41ocust.op <> 'D'
  and ewt41ocust.dart_filedate between '{etl_start_date}' and '{etl_end_date}'

union
select 
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt41ocust.core_cust_id core_cust_id,
ewt41ocust.ofr_invl_cd ofr_invl_cd,
ewt41ocust.cmn_cust_nm cmn_cust_nm,
ewt41ocust.adr_info_line adr_info_line,
ewt41ocust.dlvr_adr_line dlvr_adr_line,
ewt41ocust.city_nm city_nm,
ewt41ocust.st_abr st_abr,
ewt41ocust.zip_cd zip_cd,
ewt41ocust.phn_nbr phn_nbr,
ewt41ocust.ownr_pct ownr_pct,
ewt41ocust.cust_ofr_asgn_ind cust_ofr_asgn_ind,
ewt41ocust.ofr_prim_prdr_ind ofr_prim_prdr_ind,
ewt41ocust.auth_sgn_ind auth_sgn_ind,
ewt41ocust.crp_cpld_elg_pct crp_cpld_elg_pct,
ewt41ocust.prdr_elg_ind prdr_elg_ind,
ewt41ocust.agi_shr_pct agi_shr_pct,
ewt41ocust.inhrt_ctr_ind inhrt_ctr_ind,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt41ocust.ofr_scnr_id ofr_scnr_id,
ewt41ocust.data_stat_cd data_stat_cd,
ewt41ocust.cre_dt cre_dt,
ewt41ocust.last_chg_dt last_chg_dt,
ewt41ocust.last_chg_user_nm last_chg_user_nm,
ewt41ocust.beg_farm_dt beg_farm_dt,
ewt41ocust.beg_farm_ind beg_farm_ind,
ewt41ocust.lmt_rsrc_prdr_ind ltd_rsrc_prdr_ind,
ewt41ocust.socl_dadvg_ind socl_dadvg_ind,
ewt41ocust.vet_cert_dter_dt vet_cert_dter_dt,
ewt41ocust.vet_ind vet_ind,
ewt40ofrsc.op as cdc_oper_cd,
current_timestamp() as load_dt,
'ewt41ocust' as data_src_nm,
'{etl_start_date}' as cdc_dt,
2 as tbl_priority
from `fsa-{env}-cnsv`.`ewt40ofrsc`
join `fsa-{env}-cnsv-cdc`.`ewt41ocust` on (ewt40ofrsc.ofr_scnr_id = ewt41ocust.ofr_scnr_id) 
left join `fsa-{env}-cnsv`.`ewt14sgnp` on (ewt40ofrsc.sgnp_id = ewt14sgnp.sgnp_id)
where ewt40ofrsc.op <> 'D'

union
select 
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt41ocust.core_cust_id core_cust_id,
ewt41ocust.ofr_invl_cd ofr_invl_cd,
ewt41ocust.cmn_cust_nm cmn_cust_nm,
ewt41ocust.adr_info_line adr_info_line,
ewt41ocust.dlvr_adr_line dlvr_adr_line,
ewt41ocust.city_nm city_nm,
ewt41ocust.st_abr st_abr,
ewt41ocust.zip_cd zip_cd,
ewt41ocust.phn_nbr phn_nbr,
ewt41ocust.ownr_pct ownr_pct,
ewt41ocust.cust_ofr_asgn_ind cust_ofr_asgn_ind,
ewt41ocust.ofr_prim_prdr_ind ofr_prim_prdr_ind,
ewt41ocust.auth_sgn_ind auth_sgn_ind,
ewt41ocust.crp_cpld_elg_pct crp_cpld_elg_pct,
ewt41ocust.prdr_elg_ind prdr_elg_ind,
ewt41ocust.agi_shr_pct agi_shr_pct,
ewt41ocust.inhrt_ctr_ind inhrt_ctr_ind,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt41ocust.ofr_scnr_id ofr_scnr_id,
ewt41ocust.data_stat_cd data_stat_cd,
ewt41ocust.cre_dt cre_dt,
ewt41ocust.last_chg_dt last_chg_dt,
ewt41ocust.last_chg_user_nm last_chg_user_nm,
ewt41ocust.beg_farm_dt beg_farm_dt,
ewt41ocust.beg_farm_ind beg_farm_ind,
ewt41ocust.lmt_rsrc_prdr_ind ltd_rsrc_prdr_ind,
ewt41ocust.socl_dadvg_ind socl_dadvg_ind,
ewt41ocust.vet_cert_dter_dt vet_cert_dter_dt,
ewt41ocust.vet_ind vet_ind,
ewt14sgnp.op as cdc_oper_cd,
current_timestamp() as load_dt,
'ewt41ocust' as data_src_nm,
'{etl_start_date}' as cdc_dt,
3 as tbl_priority
from `fsa-{env}-cnsv`.`ewt14sgnp`
left join `fsa-{env}-cnsv`.`ewt40ofrsc` on (ewt14sgnp.sgnp_id = ewt40ofrsc.sgnp_id) 
join `fsa-{env}-cnsv-cdc`.`ewt41ocust` on (ewt40ofrsc.ofr_scnr_id = ewt41ocust.ofr_scnr_id)
where ewt14sgnp.op <> 'D'
) stg_all
) stg_unq
where row_num_part = 1

union
select distinct
null pgm_yr,
null adm_st_fsa_cd,
null adm_cnty_fsa_cd,
null tr_nbr,
null ofr_scnr_nm,
null sgnp_type_desc,
null sgnp_stype_desc,
null sgnp_nbr,
null sgnp_stype_agr_nm,
ewt41ocust.core_cust_id core_cust_id,
ewt41ocust.ofr_invl_cd ofr_invl_cd,
ewt41ocust.cmn_cust_nm cmn_cust_nm,
ewt41ocust.adr_info_line adr_info_line,
ewt41ocust.dlvr_adr_line dlvr_adr_line,
ewt41ocust.city_nm city_nm,
ewt41ocust.st_abr st_abr,
ewt41ocust.zip_cd zip_cd,
ewt41ocust.phn_nbr phn_nbr,
ewt41ocust.ownr_pct ownr_pct,
ewt41ocust.cust_ofr_asgn_ind cust_ofr_asgn_ind,
ewt41ocust.ofr_prim_prdr_ind ofr_prim_prdr_ind,
ewt41ocust.auth_sgn_ind auth_sgn_ind,
ewt41ocust.crp_cpld_elg_pct crp_cpld_elg_pct,
ewt41ocust.prdr_elg_ind prdr_elg_ind,
ewt41ocust.agi_shr_pct agi_shr_pct,
ewt41ocust.inhrt_ctr_ind inhrt_ctr_ind,
null cnsv_ctr_seq_nbr,
null cnsv_ctr_sfx_cd,
ewt41ocust.ofr_scnr_id ofr_scnr_id,
ewt41ocust.data_stat_cd data_stat_cd,
ewt41ocust.cre_dt cre_dt,
ewt41ocust.last_chg_dt last_chg_dt,
ewt41ocust.last_chg_user_nm last_chg_user_nm,
ewt41ocust.beg_farm_dt beg_farm_dt,
ewt41ocust.beg_farm_ind beg_farm_ind,
ewt41ocust.lmt_rsrc_prdr_ind ltd_rsrc_prdr_ind,
ewt41ocust.socl_dadvg_ind socl_dadvg_ind,
ewt41ocust.vet_cert_dter_dt vet_cert_dter_dt,
ewt41ocust.vet_ind vet_ind,
ewt41ocust.op as cdc_oper_cd,
current_timestamp() as load_dt,
'ewt41ocust' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as row_num_part
from `fsa-{env}-cnsv-cdc`.`ewt41ocust`
where ewt41ocust.op = 'D'
