SELECT DISTINCT
REDUCTION_TYPE.REDUCTION_CODE RDN_CD,
REDUCTION_TYPE.REDUCTION_DESCRIPTION RDN_DESC,
REDUCTION_TYPE.DATA_STATUS_CODE DATA_STAT_CD,
REDUCTION_TYPE.CREATION_DATE CRE_DT,
REDUCTION_TYPE.CREATION_USER_NAME CRE_USER_NM,
REDUCTION_TYPE.LAST_CHANGE_DATE LAST_CHG_DT,
REDUCTION_TYPE.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
OP AS CDC_OPER_CD,
1 AS row_num_part
FROM REDUCTION_TYPE
WHERE OP <> 'D'
UNION
SELECT DISTINCT
REDUCTION_TYPE.REDUCTION_CODE RDN_CD,
REDUCTION_TYPE.REDUCTION_DESCRIPTION RDN_DESC,
REDUCTION_TYPE.DATA_STATUS_CODE DATA_STAT_CD,
REDUCTION_TYPE.CREATION_DATE CRE_DT,
REDUCTION_TYPE.CREATION_USER_NAME CRE_USER_NM,
REDUCTION_TYPE.LAST_CHANGE_DATE LAST_CHG_DT,
REDUCTION_TYPE.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM REDUCTION_TYPE
WHERE OP = 'D'