SELECT PGM_YR,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
TR_NBR,
OFR_SCNR_NM,
BUS_EVNT_NM,
BUS_EVNT_DT,
CNSV_CTR_SEQ_NBR,
CNSV_CTR_SFX_CD,
OFR_SCNR_ID,
CNSV_EVNT_MST_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT PGM_YR,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
TR_NBR,
OFR_SCNR_NM,
BUS_EVNT_NM,
BUS_EVNT_DT,
CNSV_CTR_SEQ_NBR,
CNSV_CTR_SFX_CD,
OFR_SCNR_ID,
CNSV_EVNT_MST_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
OFR_SCNR_ID,
CNSV_EVNT_MST_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
CONSERVATION_EVENT_MASTER.BUS_EVNT_NM BUS_EVNT_NM,
OFFER_CONSERVATION_EVENT.BUS_EVNT_DT BUS_EVNT_DT,
EWT40OFRSC.CNSV_CTR_SEQ_NBR CNSV_CTR_SEQ_NBR,
EWT40OFRSC.CNSV_CTR_SUFX_CD CNSV_CTR_SFX_CD,
OFFER_CONSERVATION_EVENT.OFR_SCNR_ID OFR_SCNR_ID,
OFFER_CONSERVATION_EVENT.CNSV_EVNT_MST_ID CNSV_EVNT_MST_ID,
OFFER_CONSERVATION_EVENT.DATA_STAT_CD DATA_STAT_CD,
OFFER_CONSERVATION_EVENT.CRE_DT CRE_DT,
OFFER_CONSERVATION_EVENT.LAST_CHG_DT LAST_CHG_DT,
OFFER_CONSERVATION_EVENT.LAST_CHG_USER_NM LAST_CHG_USER_NM,
OFFER_CONSERVATION_EVENT.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."offer_conservation_event" OFFER_CONSERVATION_EVENT 
LEFT JOIN   "fsa-{env}-cnsv".CONSERVATION_EVENT_MASTER  
ON (OFFER_CONSERVATION_EVENT.CNSV_EVNT_MST_ID = CONSERVATION_EVENT_MASTER.CNSV_EVNT_MST_ID) 
LEFT JOIN   "fsa-{env}-cnsv".EWT40OFRSC  
ON (OFFER_CONSERVATION_EVENT.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP  
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
WHERE OFFER_CONSERVATION_EVENT.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and OFFER_CONSERVATION_EVENT.OP <> 'D'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
CONSERVATION_EVENT_MASTER.BUS_EVNT_NM BUS_EVNT_NM,
OFFER_CONSERVATION_EVENT.BUS_EVNT_DT BUS_EVNT_DT,
EWT40OFRSC.CNSV_CTR_SEQ_NBR CNSV_CTR_SEQ_NBR,
EWT40OFRSC.CNSV_CTR_SUFX_CD CNSV_CTR_SFX_CD,
OFFER_CONSERVATION_EVENT.OFR_SCNR_ID OFR_SCNR_ID,
OFFER_CONSERVATION_EVENT.CNSV_EVNT_MST_ID CNSV_EVNT_MST_ID,
OFFER_CONSERVATION_EVENT.DATA_STAT_CD DATA_STAT_CD,
OFFER_CONSERVATION_EVENT.CRE_DT CRE_DT,
OFFER_CONSERVATION_EVENT.LAST_CHG_DT LAST_CHG_DT,
OFFER_CONSERVATION_EVENT.LAST_CHG_USER_NM LAST_CHG_USER_NM,
CONSERVATION_EVENT_MASTER.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."conservation_event_master" CONSERVATION_EVENT_MASTER  
JOIN   "fsa-{env}-cnsv".OFFER_CONSERVATION_EVENT  
ON (OFFER_CONSERVATION_EVENT.CNSV_EVNT_MST_ID = CONSERVATION_EVENT_MASTER.CNSV_EVNT_MST_ID) 
LEFT JOIN   "fsa-{env}-cnsv".EWT40OFRSC  
ON (OFFER_CONSERVATION_EVENT.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP 
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
WHERE CONSERVATION_EVENT_MASTER.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and CONSERVATION_EVENT_MASTER.OP <> 'D'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
CONSERVATION_EVENT_MASTER.BUS_EVNT_NM BUS_EVNT_NM,
OFFER_CONSERVATION_EVENT.BUS_EVNT_DT BUS_EVNT_DT,
EWT40OFRSC.CNSV_CTR_SEQ_NBR CNSV_CTR_SEQ_NBR,
EWT40OFRSC.CNSV_CTR_SUFX_CD CNSV_CTR_SFX_CD,
OFFER_CONSERVATION_EVENT.OFR_SCNR_ID OFR_SCNR_ID,
OFFER_CONSERVATION_EVENT.CNSV_EVNT_MST_ID CNSV_EVNT_MST_ID,
OFFER_CONSERVATION_EVENT.DATA_STAT_CD DATA_STAT_CD,
OFFER_CONSERVATION_EVENT.CRE_DT CRE_DT,
OFFER_CONSERVATION_EVENT.LAST_CHG_DT LAST_CHG_DT,
OFFER_CONSERVATION_EVENT.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT40OFRSC.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."EWT40OFRSC" EWT40OFRSC 
JOIN   "fsa-{env}-cnsv".OFFER_CONSERVATION_EVENT  
ON (OFFER_CONSERVATION_EVENT.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN   "fsa-{env}-cnsv".CONSERVATION_EVENT_MASTER  
ON (OFFER_CONSERVATION_EVENT.CNSV_EVNT_MST_ID = CONSERVATION_EVENT_MASTER.CNSV_EVNT_MST_ID)  
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP  
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
WHERE EWT40OFRSC.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT40OFRSC.OP <> 'D'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
CONSERVATION_EVENT_MASTER.BUS_EVNT_NM BUS_EVNT_NM,
OFFER_CONSERVATION_EVENT.BUS_EVNT_DT BUS_EVNT_DT,
EWT40OFRSC.CNSV_CTR_SEQ_NBR CNSV_CTR_SEQ_NBR,
EWT40OFRSC.CNSV_CTR_SUFX_CD CNSV_CTR_SFX_CD,
OFFER_CONSERVATION_EVENT.OFR_SCNR_ID OFR_SCNR_ID,
OFFER_CONSERVATION_EVENT.CNSV_EVNT_MST_ID CNSV_EVNT_MST_ID,
OFFER_CONSERVATION_EVENT.DATA_STAT_CD DATA_STAT_CD,
OFFER_CONSERVATION_EVENT.CRE_DT CRE_DT,
OFFER_CONSERVATION_EVENT.LAST_CHG_DT LAST_CHG_DT,
OFFER_CONSERVATION_EVENT.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT14SGNP.OP,
4 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."ewt14sgnp" EWT14SGNP 
LEFT JOIN   "fsa-{env}-cnsv".EWT40OFRSC 
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
JOIN   "fsa-{env}-cnsv".OFFER_CONSERVATION_EVENT  
ON (OFFER_CONSERVATION_EVENT.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN   "fsa-{env}-cnsv".CONSERVATION_EVENT_MASTER  
ON (OFFER_CONSERVATION_EVENT.CNSV_EVNT_MST_ID = CONSERVATION_EVENT_MASTER.CNSV_EVNT_MST_ID) 
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT14SGNP.OP <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
NULL PGM_YR,
NULL ADM_ST_FSA_CD,
NULL ADM_CNTY_FSA_CD,
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL TR_NBR,
NULL OFR_SCNR_NM,
NULL BUS_EVNT_NM,
OFFER_CONSERVATION_EVENT.BUS_EVNT_DT BUS_EVNT_DT,
NULL CNSV_CTR_SEQ_NBR,
NULL CNSV_CTR_SFX_CD,
OFFER_CONSERVATION_EVENT.OFR_SCNR_ID OFR_SCNR_ID,
OFFER_CONSERVATION_EVENT.CNSV_EVNT_MST_ID CNSV_EVNT_MST_ID,
OFFER_CONSERVATION_EVENT.DATA_STAT_CD DATA_STAT_CD,
OFFER_CONSERVATION_EVENT.CRE_DT CRE_DT,
OFFER_CONSERVATION_EVENT.LAST_CHG_DT LAST_CHG_DT,
OFFER_CONSERVATION_EVENT.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".OFFER_CONSERVATION_EVENT OFFER_CONSERVATION_EVENT
WHERE OFFER_CONSERVATION_EVENT.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and OFFER_CONSERVATION_EVENT.OP = 'D'
)