SELECT SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
GRSLD_RANK_FCTR_IDN,
GRSLD_RANK_SFCTR_IDN,
ST_FIPS_CD,
CNTY_FIPS_CD,
RANK_PNT_CT,
GRSLD_RANK_SFCTR_CNTY_ID,
GRSLD_RANK_SFCTR_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
CRE_USER_NM,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
GRSLD_RANK_FCTR_IDN,
GRSLD_RANK_SFCTR_IDN,
ST_FIPS_CD,
CNTY_FIPS_CD,
RANK_PNT_CT,
GRSLD_RANK_SFCTR_CNTY_ID,
GRSLD_RANK_SFCTR_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
CRE_USER_NM,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
GRSLD_RANK_SFCTR_CNTY_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.ST_FIPS_CD ST_FIPS_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CNTY_FIPS_CD CNTY_FIPS_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_CNTY_ID GRSLD_RANK_SFCTR_CNTY_ID,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_SUBFACTOR_COUNTY" GRASSLAND_RANKING_SUBFACTOR_COUNTY
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR
ON (GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID)
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR
ON (GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID)
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP
ON (GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE GRASSLAND_RANKING_SUBFACTOR_COUNTY.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR_COUNTY.OP <> 'D'

UNION
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.ST_FIPS_CD ST_FIPS_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CNTY_FIPS_CD CNTY_FIPS_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_CNTY_ID GRSLD_RANK_SFCTR_CNTY_ID,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_SUBFACTOR.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_SUBFACTOR" GRASSLAND_RANKING_SUBFACTOR
JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_COUNTY
ON (GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_ID)
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR
ON (GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID)
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP
ON (GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE GRASSLAND_RANKING_SUBFACTOR.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR.OP <> 'D'

UNION
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.ST_FIPS_CD ST_FIPS_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CNTY_FIPS_CD CNTY_FIPS_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_CNTY_ID GRSLD_RANK_SFCTR_CNTY_ID,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_FACTOR.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_FACTOR" GRASSLAND_RANKING_FACTOR
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR
ON (GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID)
JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_COUNTY
ON (GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_ID)
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP
ON (GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE GRASSLAND_RANKING_FACTOR.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_FACTOR.OP <> 'D'

UNION
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.ST_FIPS_CD ST_FIPS_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CNTY_FIPS_CD CNTY_FIPS_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_CNTY_ID GRSLD_RANK_SFCTR_CNTY_ID,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT14SGNP.OP,
4 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."EWT14SGNP" EWT14SGNP
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR
ON (EWT14SGNP.SGNP_ID = GRASSLAND_RANKING_FACTOR.SGNP_ID)
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR
ON (GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID)
JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_COUNTY
ON (GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_ID)
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT14SGNP.OP <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL GRSLD_RANK_FCTR_IDN,
NULL GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.ST_FIPS_CD ST_FIPS_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CNTY_FIPS_CD CNTY_FIPS_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_CNTY_ID GRSLD_RANK_SFCTR_CNTY_ID,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_COUNTY.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".GRASSLAND_RANKING_SUBFACTOR_COUNTY GRASSLAND_RANKING_SUBFACTOR_COUNTY
WHERE dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR_COUNTY.OP = 'D'
)