with cte as (
	Select FARM_CROP_IRR_HIST_L_ID 
	From EDV.FARM_CROP_IRR_HIST_L
),
cte1 as (
	SELECT DISTINCT
			MD5(upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_TYPE_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD), '--')) ||'~~'||MD5(upper(coalesce(CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.FARM_NBR ,'--')))) FARM_CROP_IRR_HIST_L_ID
			, MD5('-1') FARM_CROP_IRR_HIST_L_ID_2
			, CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_ID CROP_FARM_YR_MNG_VAL_ADJ_ID
			, CROP_FARM_YR_MNG_VAL_ADJ.LOAD_DT LOAD_DT
			, CROP_FARM_YR_MNG_VAL_ADJ.CDC_DT DATA_EFF_STRT_DT
			, CROP_FARM_YR_MNG_VAL_ADJ.DATA_SRC_NM DATA_SRC_NM
			, CROP_FARM_YR_MNG_VAL_ADJ.DATA_STAT_CD DATA_STAT_CD
			, CROP_FARM_YR_MNG_VAL_ADJ.CRE_DT SRC_CRE_DT 
			, CROP_FARM_YR_MNG_VAL_ADJ.CRE_USER_NM SRC_CRE_USER_NM
			, CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_DT SRC_LAST_CHG_DT
			, CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
			, CROP_FARM_YR_MNG_VAL_ADJ.FARM_YR_CROP_IRR_HIST_ID FARM_YR_CROP_IRR_HIST_ID
			, CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY SRC_CROP_FARM_YR_ADJ_TYPE_CD
			, FARM_CROP_ADJ_TYPE_RS.DMN_VAL_NM CROP_FARM_YR_ADJ_TYPE_NM
			, CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_RS SRC_CROP_FARM_YR_ADJ_RSN_CD
			, CROP_FARM_YR_MNG_VAL_ADJ.AFT_ADJ_VAL AFT_ADJ_VAL
			, CROP_FARM_YR_MNG_VAL_ADJ.BEF_ADJ_VAL BEF_ADJ_VAL
			, CROP_FARM_YR_MNG_VAL_ADJ.PGM_YR PGM_YR 
			, to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT
			, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT
			, MD5(trim(both CROP_FARM_YR_MNG_VAL_ADJ.PGM_ABR)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_CD)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_TYPE_CD)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD)||'~~'||upper(coalesce(CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.FARM_NBR,'--'))||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_ID||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.DATA_STAT_CD)||'~~'||to_char(CROP_FARM_YR_MNG_VAL_ADJ.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.CRE_USER_NM)||'~~'||to_char(CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_USER_NM)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.FARM_YR_CROP_IRR_HIST_ID||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY||'~~'||trim(both FARM_CROP_ADJ_TYPE_RS.DMN_VAL_NM)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_RS||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.AFT_ADJ_VAL||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.BEF_ADJ_VAL||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.PGM_YR) HASH_DIF
		FROM SQL_FARM_RCD_STG.CROP_FARM_YR_MNG_VAL_ADJ  CROP_FARM_YR_MNG_VAL_ADJ 
		JOIN EDV.FARM_CROP_ADJ_TYPE_RS FARM_CROP_ADJ_TYPE_RS 
		ON (CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY = FARM_CROP_ADJ_TYPE_RS.DMN_VAL_ID)
		WHERE CROP_FARM_YR_MNG_VAL_ADJ.FARM_YR_CROP_IRR_HIST_ID IS NOT NULL 
		and CROP_FARM_YR_MNG_VAL_ADJ.CDC_OPER_CD IN ('I','UN')
),
cte2 as (
select distinct *
from cte1 
where (
		(cte1.FARM_CROP_IRR_HIST_L_ID IN (select FARM_CROP_IRR_HIST_L_ID from cte))
		or 
		(cte1.FARM_CROP_IRR_HIST_L_ID_2 in (select FARM_CROP_IRR_HIST_L_ID from cte))
	)
)
INSERT into
EDV.CROP_FARM_YR_ADJ_IRR_LS(
FARM_CROP_IRR_HIST_L_ID
, CROP_FARM_YR_MNG_VAL_ADJ_ID
, LOAD_DT
, DATA_EFF_STRT_DT
, DATA_SRC_NM
, DATA_STAT_CD
, SRC_CRE_DT
, SRC_CRE_USER_NM
, SRC_LAST_CHG_DT
, SRC_LAST_CHG_USER_NM
, FARM_YR_CROP_IRR_HIST_ID
, SRC_CROP_FARM_YR_ADJ_TYPE_CD
, CROP_FARM_YR_ADJ_TYPE_NM
, SRC_CROP_FARM_YR_ADJ_RSN_CD
, AFT_ADJ_VAL
, BEF_ADJ_VAL
, PGM_YR
, DATA_EFF_END_DT
, LOAD_END_DT
, HASH_DIF
)
select 
cte2.FARM_CROP_IRR_HIST_L_ID
, cte2.CROP_FARM_YR_MNG_VAL_ADJ_ID
, cte2.LOAD_DT
, cte2.DATA_EFF_STRT_DT
, cte2.DATA_SRC_NM
, cte2.DATA_STAT_CD
, cte2.SRC_CRE_DT
, cte2.SRC_CRE_USER_NM
, cte2.SRC_LAST_CHG_DT
, cte2.SRC_LAST_CHG_USER_NM
, cte2.FARM_YR_CROP_IRR_HIST_ID
, cte2.SRC_CROP_FARM_YR_ADJ_TYPE_CD
, cte2.CROP_FARM_YR_ADJ_TYPE_NM
, cte2.SRC_CROP_FARM_YR_ADJ_RSN_CD
, cte2.AFT_ADJ_VAL
, cte2.BEF_ADJ_VAL
, cte2.PGM_YR
, cte2.DATA_EFF_END_DT
, cte2.LOAD_END_DT
, cte2.HASH_DIF
from cte2
LEFT JOIN EDV.CROP_FARM_YR_ADJ_IRR_LS dv
ON (
cte2.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists ( 
                select 1 from EDV.CROP_FARM_YR_ADJ_IRR_LS ls
                where cte2.farm_crop_irr_hist_l_id = ls.farm_crop_irr_hist_l_id
				and cte2.crop_farm_yr_mng_val_adj_id = ls.crop_farm_yr_mng_val_adj_id
				and cte2.load_dt = ls.load_dt
			   )
;