-- Julia Lu edition - will update this paragraph and query when (cnsv/ccms)-cdc is ready
-- Stage SQL: CCMS_SGNP (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CCMS_SGNP/incremental/CCMS_SGNP.sql
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT SGNP_TYPE_NM,
SGNP_SUB_CAT_NM,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
SGNP_ID,
SGNP_NM,
SGNP_TYPE_CD,
SGNP_SUB_CAT_CD,
DATA_STAT_CD,
CRE_DT,
CRE_USER_NM,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
SGNP_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
SIGNUP.SIGNUP_IDENTIFIER SGNP_ID,
SIGNUP.signup_name SGNP_NM,
SIGNUP.SIGNUP_TYPE_CODE SGNP_TYPE_CD,
SIGNUP.SIGNUP_SUB_CATEGORY_CODE SGNP_SUB_CAT_CD,
SIGNUP.DATA_STATUS_CODE DATA_STAT_CD,
SIGNUP.CREATION_DATE CRE_DT,
SIGNUP.CREATION_USER_NAME CRE_USER_NM,
SIGNUP.LAST_CHANGE_DATE LAST_CHG_DT,
SIGNUP.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP.op,
1 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".SIGNUP 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP.SIGNUP_TYPE_CODE = SIGNUP_TYPE.SIGNUP_TYPE_CODE) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE)
WHERE SIGNUP.op <> 'D'

UNION
SELECT 
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
SIGNUP.SIGNUP_IDENTIFIER SGNP_ID,
SIGNUP.signup_name SGNP_NM,
SIGNUP.SIGNUP_TYPE_CODE SGNP_TYPE_CD,
SIGNUP.SIGNUP_SUB_CATEGORY_CODE SGNP_SUB_CAT_CD,
SIGNUP.DATA_STATUS_CODE DATA_STAT_CD,
SIGNUP.CREATION_DATE CRE_DT,
SIGNUP.CREATION_USER_NAME CRE_USER_NM,
SIGNUP.LAST_CHANGE_DATE LAST_CHG_DT,
SIGNUP.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP_TYPE.op,
2 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
JOIN "fsa-{env}-ccms-cdc".SIGNUP ON (SIGNUP.SIGNUP_TYPE_CODE = SIGNUP_TYPE.SIGNUP_TYPE_CODE) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE)
WHERE SIGNUP_TYPE.op <> 'D'

UNION
SELECT 
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
SIGNUP.SIGNUP_IDENTIFIER SGNP_ID,
SIGNUP.signup_name SGNP_NM,
SIGNUP.SIGNUP_TYPE_CODE SGNP_TYPE_CD,
SIGNUP.SIGNUP_SUB_CATEGORY_CODE SGNP_SUB_CAT_CD,
SIGNUP.DATA_STATUS_CODE DATA_STAT_CD,
SIGNUP.CREATION_DATE CRE_DT,
SIGNUP.CREATION_USER_NAME CRE_USER_NM,
SIGNUP.LAST_CHANGE_DATE LAST_CHG_DT,
SIGNUP.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP_SUB_CATEGORY.op,
3 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY 
JOIN "fsa-{env}-ccms-cdc".SIGNUP 
ON (SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE) 
LEFT JOIN "fsa-{env}-ccms-cdc".SIGNUP_TYPE 
ON (SIGNUP.SIGNUP_TYPE_CODE = SIGNUP_TYPE.SIGNUP_TYPE_CODE)
WHERE SIGNUP_SUB_CATEGORY.op <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND SIGNUP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
NULL SGNP_TYPE_NM,
NULL SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
SIGNUP.SIGNUP_IDENTIFIER SGNP_ID,
SIGNUP.signup_name SGNP_NM,
SIGNUP.SIGNUP_TYPE_CODE SGNP_TYPE_CD,
SIGNUP.SIGNUP_SUB_CATEGORY_CODE SGNP_SUB_CAT_CD,
SIGNUP.DATA_STATUS_CODE DATA_STAT_CD,
SIGNUP.CREATION_DATE CRE_DT,
SIGNUP.CREATION_USER_NAME CRE_USER_NM,
SIGNUP.LAST_CHANGE_DATE LAST_CHG_DT,
SIGNUP.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-ccms-cdc".SIGNUP
WHERE SIGNUP.op = 'D'