MERGE INTO EDV.CORE_CUST_PRD_IRS_LS dv USING
  (SELECT DISTINCT MD5 (coalesce(PGM_YR_IRS_BUS_PTY_2014.CORE_CUST_ID::varchar, '-1')||PGM_YR_IRS_BUS_PTY_2014.PGM_YR) AS CORE_CUST_PRD_IRS_L_ID,
                   PGM_YR_IRS_BUS_PTY_2014.LOAD_DT,
                   PGM_YR_IRS_BUS_PTY_2014.CDC_DT,
                   PGM_YR_IRS_BUS_PTY_2014.DATA_SRC_NM,
                   PGM_YR_IRS_BUS_PTY_2014.DATA_STAT_CD,
                   PGM_YR_IRS_BUS_PTY_2014.CRE_DT,
                   PGM_YR_IRS_BUS_PTY_2014.CRE_USER_NM,
                   PGM_YR_IRS_BUS_PTY_2014.LAST_CHG_DT,
                   PGM_YR_IRS_BUS_PTY_2014.LAST_CHG_USER_NM,
                   PGM_YR_IRS_BUS_PTY_2014.DATA_RCV_DT,
                   PGM_YR_IRS_BUS_PTY_2014.AGI_CNST_FORM_IRS_IPUT_DT,
                   PGM_YR_IRS_BUS_PTY_2014.BAT_PROC_STAT_EFF_DT,
                   PGM_YR_IRS_BUS_PTY_2014.BAT_PROC_STAT_CD,
                   PGM_YR_IRS_BUS_PTY_2014.CUST_DATA_IRS_VLD_CD,
                   PGM_YR_IRS_BUS_PTY_2014.IRS_900K_AGI_ELG_DTER_CD,
                   IRS_AGI_ELG_ERR_TYPE.IRS_AGI_ELG_ERR_TYPE_NBR,
                   IRS_AGI_ELG_ERR_TYPE.IRS_AGI_ELG_ERR_CAT_CD,
                   PGM_YR_IRS_BUS_PTY_2014.IRS_AGI_ELG_ERR_TYPE_ID,
                   PGM_YR_IRS_BUS_PTY_2014.CORE_CUST_ID,
                   PGM_YR_IRS_BUS_PTY_2014.PGM_YR_IRS_BUS_PTY_2014_ID,
                   PGM_YR_IRS_BUS_PTY_2014.CDC_OPER_CD
   FROM SBSD_STG.PGM_YR_IRS_BUS_PTY_2014
   LEFT OUTER JOIN EDV.V_IRS_AGI_ELG_ERR_TYPE IRS_AGI_ELG_ERR_TYPE ON (PGM_YR_IRS_BUS_PTY_2014.IRS_AGI_ELG_ERR_TYPE_ID=IRS_AGI_ELG_ERR_TYPE.IRS_AGI_ELG_ERR_TYPE_ID)
   WHERE PGM_YR_IRS_BUS_PTY_2014.CDC_OPER_CD='D'
     AND DATE_TRUNC('day',PGM_YR_IRS_BUS_PTY_2014.CDC_DT) = DATE_TRUNC('day',TO_TIMESTAMP ('{ETL_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF'))
     AND PGM_YR_IRS_BUS_PTY_2014.LOAD_DT = (SELECT MAX(LOAD_DT) FROM SBSD_STG.PGM_YR_IRS_BUS_PTY_2014)
   ORDER BY PGM_YR_IRS_BUS_PTY_2014.CDC_DT
  ) stg
ON (coalesce(stg.PGM_YR_IRS_BUS_PTY_2014_ID, 0) = coalesce(dv.PGM_YR_IRS_BUS_PTY_2014_ID, 0))
WHEN MATCHED 
  AND dv.LOAD_DT <> stg.LOAD_DT
  AND dv.LOAD_END_DT = to_date('9999-12-31', 'YYYY-MM-DD') 
THEN
UPDATE
SET LOAD_END_DT=stg.LOAD_DT,
    DATA_EFF_END_DT=stg.CDC_DT
WHEN NOT MATCHED THEN
  INSERT (CORE_CUST_PRD_IRS_L_ID,
          LOAD_DT,
          DATA_EFF_STRT_DT,
          DATA_SRC_NM,
          DATA_STAT_CD,
          SRC_CRE_DT,
          SRC_CRE_USER_NM,
          SRC_LAST_CHG_DT,
          SRC_LAST_CHG_USER_NM,
          SRC_DATA_RCV_DT,
          AGI_CNST_FORM_IRS_IPUT_DT,
          BAT_PROC_STAT_EFF_DT,
          BAT_PROC_STAT_CD,
          CUST_DATA_IRS_VLD_CD,
          IRS_900K_AGI_ELG_DTER_CD,
          IRS_AGI_ELG_ERR_TYPE_NBR,
          IRS_AGI_ELG_ERR_CAT_CD,
          IRS_AGI_ELG_ERR_TYPE_ID,
          CORE_CUST_ID,
          PGM_YR_IRS_BUS_PTY_2014_ID,
          DATA_EFF_END_DT,
          LOAD_END_DT)
  VALUES (stg.CORE_CUST_PRD_IRS_L_ID,
          stg.LOAD_DT,
          stg.CDC_DT,
          stg.DATA_SRC_NM,
          stg.DATA_STAT_CD,
          stg.CRE_DT,
          stg.CRE_USER_NM,
          stg.LAST_CHG_DT,
          stg.LAST_CHG_USER_NM,
          stg.DATA_RCV_DT,
          stg.AGI_CNST_FORM_IRS_IPUT_DT,
          stg.BAT_PROC_STAT_EFF_DT,
          stg.BAT_PROC_STAT_CD,
          stg.CUST_DATA_IRS_VLD_CD,
          stg.IRS_900K_AGI_ELG_DTER_CD,
          stg.IRS_AGI_ELG_ERR_TYPE_NBR,
          stg.IRS_AGI_ELG_ERR_CAT_CD,
          stg.IRS_AGI_ELG_ERR_TYPE_ID,
          stg.CORE_CUST_ID,
          stg.PGM_YR_IRS_BUS_PTY_2014_ID,
          stg.CDC_DT,
          stg.LOAD_DT)