MERGE into
EDV.FLD_PRDR_PCW_EXCP_RS dv
 using(
 SELECT sub1.*
FROM
(	
	SELECT sub.*,
		   ROW_NUMBER() OVER (PARTITION BY FLD_PRDR_PCW_EXCP_CD ORDER BY LOAD_DT desc) FLD_PRDR_PCW_EXCP_CD_RANK
	FROM
	(
		select distinct
		coalesce(DMN_VAL.DMN_CHAR_VAL, '[NULL IN SOURCE]') FLD_PRDR_PCW_EXCP_CD,
		DMN_VAL.CDC_DT DATA_EFF_STRT_DT,
		DMN_VAL.DATA_SRC_NM DATA_SRC_NM,
		DMN_VAL.DFLT_VAL_IND DFLT_VAL_IND,
		DMN_VAL.DMN_ID DMN_ID,
		DMN_VAL.DMN_VAL_DESC DMN_VAL_DESC,
		DMN_VAL.DMN_VAL_ID DMN_VAL_ID,
		DMN_VAL.DMN_VAL_NM DMN_VAL_NM,
		DMN_VAL.DPLY_SEQ_NBR DPLY_SEQ_NBR,
		DMN_VAL.LOAD_DT LOAD_DT,
		DMN_VAL.CRE_DT SRC_CRE_DT,
		DMN_VAL.LAST_CHG_DT SRC_LAST_CHG_DT,
		DMN_VAL.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
		MD5(trim(both DMN_VAL.DMN_CHAR_VAL)||'~~'||trim(both DMN_VAL.DFLT_VAL_IND)||'~~'||DMN_VAL.DMN_ID||'~~'||trim(both DMN_VAL.DMN_VAL_DESC)||'~~'||DMN_VAL.DMN_VAL_ID||'~~'||trim(both DMN_VAL.DMN_VAL_NM)||'~~'||DMN_VAL.DPLY_SEQ_NBR||'~~'||to_char(DMN_VAL.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(DMN_VAL.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both DMN_VAL.LAST_CHG_USER_NM)) HASH_DIF
		FROM SQL_FARM_RCD_STG.DMN_VAL
		WHERE DMN_VAL.DMN_ID =39
		and DMN_VAL.cdc_oper_cd IN ('I','UN')
		order by DMN_VAL.CDC_DT
	) sub
) sub1
WHERE sub1.FLD_PRDR_PCW_EXCP_CD_RANK = 1
) stg 
 on ( 
coalesce(stg.DMN_VAL_ID,0) = coalesce(dv.DMN_VAL_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;