MERGE INTO EDV.UCHG_ATRB_PRPS_PYMT_LS dv USING
  (SELECT DISTINCT MD5 (upper(COALESCE (trim(UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_ST_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_CNTY_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_ACCT_PGM_CD), '--')) ||'~~'||COALESCE (UCHG_ATRB_PRPS_PYMT_LOG.PAID_CORE_CUST_ID, '-1')) AS DIR_ATRB_PRPS_PYMT_L_ID,
                   coalesce(UCHG_ATRB_PRPS_PYMT_LOG.UCHG_ATRB_PRPS_PYMT_LOG_ID, '-1') UCHG_ATRB_PRPS_PYMT_LOG_ID,
                   UCHG_ATRB_PRPS_PYMT_LOG.ACCT_PGM_CD ACCT_PGM_CD,
                   UCHG_ATRB_PRPS_PYMT_LOG.APP_3_OWNSHP_LVL_LMT_IND APP_3_OWNSHP_LVL_LMT_IND,
                   UCHG_ATRB_PRPS_PYMT_LOG.CMDY_CD CMDY_CD,
                   UCHG_ATRB_PRPS_PYMT_LOG.CNTY_FSA_CD CNTY_FSA_CD,
                   UCHG_ATRB_PRPS_PYMT_LOG.CRE_DT CRE_DT,
                   UCHG_ATRB_PRPS_PYMT_LOG.CRE_USER_NM CRE_USER_NM,
                   UCHG_ATRB_PRPS_PYMT_LOG.CDC_DT DATA_EFF_STRT_DT,
                   UCHG_ATRB_PRPS_PYMT_LOG.DATA_SRC_NM DATA_SRC_NM,
                   UCHG_ATRB_PRPS_PYMT_LOG.DATA_STAT_CD DATA_STAT_CD,
                   UCHG_ATRB_PRPS_PYMT_LOG.DEC_PRCS_NBR DEC_PRCS_NBR,
                   UCHG_ATRB_PRPS_PYMT_LOG.HRCHL_PYMT_LMT_IND HRCHL_PYMT_LMT_IND,
                   UCHG_ATRB_PRPS_PYMT_LOG.LAST_CHG_DT LAST_CHG_DT,
                   UCHG_ATRB_PRPS_PYMT_LOG.LAST_CHG_USER_NM LAST_CHG_USER_NM,
                   UCHG_ATRB_PRPS_PYMT_LOG.LOAD_DT LOAD_DT,
                   UCHG_ATRB_PRPS_PYMT_LOG.OVRRD_SBSD_PRD_STRT_YR OVRRD_SBSD_PRD_STRT_YR,
                   UCHG_ATRB_PRPS_PYMT_LOG.PAID_CORE_CUST_ID PAID_CORE_CUST_ID,
                   UCHG_ATRB_PRPS_PYMT_LOG.PROC_RQST_REF_NBR PROC_RQST_REF_NBR,
                   UCHG_ATRB_PRPS_PYMT_LOG.PRST_OPYMT_ATRB_IND PRST_OPYMT_ATRB_IND,
                   UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_ACCT_PGM_CD PRV_PRPS_PYMT_ACCT_PGM_CD,
                   UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_CNTY_FSA_CD PRV_PRPS_PYMT_CNTY_FSA_CD,
                   UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_ID PRV_PRPS_PYMT_ID,
                   UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_SBSD_PRD_STRT_YR PRV_PRPS_PYMT_SBSD_PRD_STRT_YR,
                   UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_ST_FSA_CD PRV_PRPS_PYMT_ST_FSA_CD,
                   UCHG_ATRB_PRPS_PYMT_LOG.PYMT_AMT PYMT_AMT,
                   UCHG_ATRB_PRPS_PYMT_LOG.PYMT_ATRB_RQST_RSN_TXT PYMT_ATRB_RQST_RSN_TXT,
                   UCHG_ATRB_PRPS_PYMT_LOG.PYMT_ATRB_RVRS_DT PYMT_ATRB_RVRS_DT,
                   UCHG_ATRB_PRPS_PYMT_LOG.PYMT_LMT_IND PYMT_LMT_IND,
                   UCHG_ATRB_PRPS_PYMT_LOG.PYMT_LMT_YR PYMT_LMT_YR,
                   UCHG_ATRB_PRPS_PYMT_LOG.PYMT_PGM_ID PYMT_PGM_ID,
                   UCHG_ATRB_PRPS_PYMT_LOG.RCD_REF_PRIM_ID RCD_REF_PRIM_ID,
                   UCHG_ATRB_PRPS_PYMT_LOG.RCD_REF_PRIM_ID_TYPE_CD RCD_REF_PRIM_ID_TYPE_CD,
                   UCHG_ATRB_PRPS_PYMT_LOG.RCD_REF_SCND_ID RCD_REF_SCND_ID,
                   UCHG_ATRB_PRPS_PYMT_LOG.RCD_REF_SCND_ID_TYPE_CD RCD_REF_SCND_ID_TYPE_CD,
                   UCHG_ATRB_PRPS_PYMT_LOG.SBSD_PRD_STRT_YR SBSD_PRD_STRT_YR,
                   UCHG_ATRB_PRPS_PYMT_LOG.ST_FSA_CD ST_FSA_CD,
                   UCHG_ATRB_PRPS_PYMT_LOG.CDC_OPER_CD,
                   MD5 (trim(UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_ST_FSA_CD)||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_CNTY_FSA_CD)||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_ACCT_PGM_CD)||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.PAID_CORE_CUST_ID||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.UCHG_ATRB_PRPS_PYMT_LOG_ID||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.ACCT_PGM_CD)||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.APP_3_OWNSHP_LVL_LMT_IND)||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.CMDY_CD)||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.CNTY_FSA_CD)||'~~'||to_char(UCHG_ATRB_PRPS_PYMT_LOG.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.CRE_USER_NM)||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.DATA_STAT_CD)||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.DEC_PRCS_NBR||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.HRCHL_PYMT_LMT_IND)||'~~'||to_char(UCHG_ATRB_PRPS_PYMT_LOG.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.LAST_CHG_USER_NM)||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.OVRRD_SBSD_PRD_STRT_YR||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.PAID_CORE_CUST_ID||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.PROC_RQST_REF_NBR||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.PRST_OPYMT_ATRB_IND)||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_ACCT_PGM_CD)||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_CNTY_FSA_CD)||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_ID||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_SBSD_PRD_STRT_YR||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.PRV_PRPS_PYMT_ST_FSA_CD)||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.PYMT_AMT||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.PYMT_ATRB_RQST_RSN_TXT)||'~~'||to_char(UCHG_ATRB_PRPS_PYMT_LOG.PYMT_ATRB_RVRS_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.PYMT_LMT_IND)||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.PYMT_LMT_YR||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.PYMT_PGM_ID||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.RCD_REF_PRIM_ID)||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.RCD_REF_PRIM_ID_TYPE_CD)||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.RCD_REF_SCND_ID)||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.RCD_REF_SCND_ID_TYPE_CD)||'~~'||UCHG_ATRB_PRPS_PYMT_LOG.SBSD_PRD_STRT_YR||'~~'||trim(UCHG_ATRB_PRPS_PYMT_LOG.ST_FSA_CD)) HASH_DIF
   FROM SBSD_STG.UCHG_ATRB_PRPS_PYMT_LOG UCHG_ATRB_PRPS_PYMT_LOG
   WHERE UCHG_ATRB_PRPS_PYMT_LOG.CDC_OPER_CD='D'
     AND date(UCHG_ATRB_PRPS_PYMT_LOG.CDC_DT) = date(TO_TIMESTAMP ('{ETL_START_TIMESTAMP}', 'YYYY-MM-DD HH24:MI:SS.FF'))
   ORDER BY UCHG_ATRB_PRPS_PYMT_LOG.CDC_DT) stg ON (coalesce(stg.UCHG_ATRB_PRPS_PYMT_LOG_ID, 0) = coalesce(dv.UCHG_ATRB_PRPS_PYMT_LOG_ID, 0)) 
WHEN MATCHED
	AND dv.LOAD_DT <> stg.LOAD_DT
  AND dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD')
THEN
UPDATE
SET LOAD_END_DT = stg.LOAD_DT,
    DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT