WITH stg AS
  (SELECT DISTINCT MD5 (COALESCE (CMPL_DET_HIST.AG_PROD_PLAN_ID::varchar(32), '-1')) AS AG_PROD_PLAN_H_ID,
                   CMPL_DET_HIST.LOAD_DT LOAD_DT,
                   CMPL_DET_HIST.CDC_DT DATA_EFF_STRT_DT,
                   CMPL_DET_HIST.DATA_SRC_NM DATA_SRC_NM,
                   CMPL_DET_HIST.DATA_STAT_CD DATA_STAT_CD,
                   CMPL_DET_HIST.CRE_DT SRC_CRE_DT,
                   CMPL_DET_HIST.LAST_CHG_DT SRC_LAST_CHG_DT,
                   CMPL_DET_HIST.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
                   CMPL_DET_HIST.SFLD_NBR SFLD_NBR,
                   CMPL_DET_HIST.FLD_VST_MEAS_IND FLD_VST_MEAS_IND,
                   CMPL_DET_HIST.WKLD_FST_QTR_IND WKLD_FST_QTR_IND,
                   CMPL_DET_HIST.WKLD_SE_QTR_IND WKLD_SE_QTR_IND,
                   CMPL_DET_HIST.WKLD_THRD_QTR_IND WKLD_THRD_QTR_IND,
                   CMPL_DET_HIST.WKLD_FRTH_QTR_IND WKLD_FRTH_QTR_IND,
                   CMPL_DET_HIST.WKLD_LATE_QTR_IND WKLD_LATE_QTR_IND,
                   CMPL_DET_HIST.LAND_USE_SRC_IND LAND_USE_SRC_IND,
                   CMPL_DET_HIST.LAND_USE_DTER_IND LAND_USE_DTER_IND,
                   CMPL_DET_HIST.CROP_STAT_CD CROP_STAT_CD,
                   CMPL_DET_HIST.CROP_FLD_DTER_DT CROP_FLD_DTER_DT,
                   CMPL_DET_HIST.AG_PROD_PLAN_ID AG_PROD_PLAN_ID,
                   CMPL_DET_HIST.CMPL_DET_HIST_ID CMPL_DET_HIST_ID,
                   CMPL_DET_HIST.CDC_OPER_CD,
                   MD5 (CMPL_DET_HIST.AG_PROD_PLAN_ID || '~~' || TRIM (CMPL_DET_HIST.DATA_STAT_CD) || '~~' || TO_CHAR (CMPL_DET_HIST.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF') || '~~' || TO_CHAR (CMPL_DET_HIST.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF') || '~~' || TRIM (CMPL_DET_HIST.LAST_CHG_USER_NM) || '~~' || TRIM (CMPL_DET_HIST.SFLD_NBR) || '~~' || TRIM (CMPL_DET_HIST.FLD_VST_MEAS_IND) || '~~' || TRIM (CMPL_DET_HIST.WKLD_FST_QTR_IND) || '~~' || TRIM (CMPL_DET_HIST.WKLD_SE_QTR_IND) || '~~' || TRIM (CMPL_DET_HIST.WKLD_THRD_QTR_IND) || '~~' || TRIM (CMPL_DET_HIST.WKLD_FRTH_QTR_IND) || '~~' || TRIM (CMPL_DET_HIST.WKLD_LATE_QTR_IND) || '~~' || TRIM (CMPL_DET_HIST.LAND_USE_SRC_IND) || '~~' || TRIM (CMPL_DET_HIST.LAND_USE_DTER_IND) || '~~' || TRIM (CMPL_DET_HIST.CROP_STAT_CD) || '~~' || TO_CHAR (CMPL_DET_HIST.CROP_FLD_DTER_DT, 'YYYY-MM-DD HH24:MI:SS') || '~~' || CMPL_DET_HIST.AG_PROD_PLAN_ID || '~~' || CMPL_DET_HIST.CMPL_DET_HIST_ID) HASH_DIF
   FROM CARS_STG.CMPL_DET_HIST CMPL_DET_HIST
   WHERE CMPL_DET_HIST.AG_PROD_PLAN_ID IS NOT NULL
     AND CMPL_DET_HIST.CDC_OPER_CD = 'D'
     AND DATE (CMPL_DET_HIST.CDC_DT) = DATE (TO_TIMESTAMP ('{ETL_START_TIMESTAMP}', 'YYYY-MM-DD HH24:MI:SS.FF'))
     AND CMPL_DET_HIST.LOAD_DT = TO_TIMESTAMP (TO_CHAR(CURRENT_DATE, 'YYYY-MM-DD'),
                                               'YYYY-MM-DD HH24:MI:SS.FF')
   ORDER BY CMPL_DET_HIST.CDC_DT),
     remainder AS
  (UPDATE edv.AG_PROD_PLAN_CMPL_DET_HS dv
   SET LOAD_END_DT = stg.LOAD_DT,
       DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
   FROM stg
   WHERE COALESCE (stg.CMPL_DET_HIST_ID,
                   0) = COALESCE (dv.CMPL_DET_HIST_ID,
                                  0)
     AND dv.LOAD_DT <> stg.LOAD_DT
     AND dv.LOAD_END_DT = TO_TIMESTAMP ('9999-12-31',
                                        'YYYY-MM-DD') RETURNING dv.*)
INSERT INTO edv.AG_PROD_PLAN_CMPL_DET_HS (AG_PROD_PLAN_H_ID, LOAD_DT, DATA_EFF_STRT_DT, DATA_SRC_NM, DATA_STAT_CD, SRC_CRE_DT, SRC_LAST_CHG_DT, SRC_LAST_CHG_USER_NM, SFLD_NBR, FLD_VST_MEAS_IND, WKLD_FST_QTR_IND, WKLD_SE_QTR_IND, WKLD_THRD_QTR_IND, WKLD_FRTH_QTR_IND, WKLD_LATE_QTR_IND, LAND_USE_SRC_IND, LAND_USE_DTER_IND, CROP_STAT_CD, CROP_FLD_DTER_DT, AG_PROD_PLAN_ID, CMPL_DET_HIST_ID, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
SELECT stg.AG_PROD_PLAN_H_ID,
       stg.LOAD_DT,
       stg.DATA_EFF_STRT_DT,
       stg.DATA_SRC_NM,
       stg.DATA_STAT_CD,
       stg.SRC_CRE_DT,
       stg.SRC_LAST_CHG_DT,
       stg.SRC_LAST_CHG_USER_NM,
       stg.SFLD_NBR,
       stg.FLD_VST_MEAS_IND,
       stg.WKLD_FST_QTR_IND,
       stg.WKLD_SE_QTR_IND,
       stg.WKLD_THRD_QTR_IND,
       stg.WKLD_FRTH_QTR_IND,
       stg.WKLD_LATE_QTR_IND,
       stg.LAND_USE_SRC_IND,
       stg.LAND_USE_DTER_IND,
       stg.CROP_STAT_CD,
       stg.CROP_FLD_DTER_DT,
       stg.AG_PROD_PLAN_ID,
       stg.CMPL_DET_HIST_ID,
       stg.DATA_EFF_STRT_DT,
       stg.LOAD_DT,
       stg.HASH_DIF
FROM stg
WHERE NOT EXISTS
    (SELECT '1'
     FROM remainder dv
     WHERE COALESCE (stg.CMPL_DET_HIST_ID,
                     0) = COALESCE (dv.CMPL_DET_HIST_ID,
                                    0) )