SELECT      DISTINCT
                PYMT_PGM_RH.DURB_ID AS LTD_PYMT_PGM_DURB_ID,
                PYMT_PGM_RS.DATA_EFF_STRT_DT,
                PYMT_PGM_RS.DATA_EFF_END_DT,
                PYMT_PGM_RS.PYMT_PGM_NM AS LTD_PYMT_PGM_NM,
                PYMT_PGM_RS.PGM_SHRT_NM AS LTD_PYMT_PGM_SHRT_NM,
                PYMT_PGM_RS.DATA_STAT_CD AS SRC_DATA_STAT_CD
        FROM        EDV.PYMT_PGM_RS
                LEFT JOIN EDV.PYMT_PGM_RH ON PYMT_PGM_RS.PYMT_PGM_NM = PYMT_PGM_RH.PYMT_PGM_NM
        WHERE       PYMT_PGM_RS.DATA_EFF_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
            AND     (PYMT_PGM_RS.DATA_EFF_STRT_DT) <= TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
            AND     PYMT_PGM_RH.DURB_ID IS NOT NULL