INSERT INTO EDV.PYMT_ATRB_RDN_LS (DIR_ATRB_PRPS_PYMT_RDN_L_ID, PYMT_ATRB_RDN_ID, LOAD_DT, DATA_EFF_STRT_DT, DATA_SRC_NM, DATA_STAT_CD, SRC_CRE_DT, SRC_CRE_USER_NM, SRC_LAST_CHG_DT, SRC_LAST_CHG_USER_NM, PYMT_ATRB_ID, PRPS_PYMT_ID, ACCT_PGM_CD, MBR_CORE_CUST_ID, PAID_CORE_CUST_ID, ST_FSA_CD, CNTY_FSA_CD, SBSD_PRD_STRT_YR, PYMT_ATRB_RDN_TYPE_CD, PYMT_ATRB_RDN_AMT, TOT_PYMT_ATRB_RDN_AMT, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
  (SELECT stg.*
   FROM
     (SELECT DISTINCT MD5 (upper(COALESCE (trim(PYMT_ATRB_RDN.ST_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(PYMT_ATRB_RDN.CNTY_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(PYMT_ATRB_RDN.ACCT_PGM_CD), '--')) ||'~~'||COALESCE (PYMT_ATRB_RDN.MBR_CORE_CUST_ID, '-1') ||'~~'||COALESCE (PYMT_ATRB_RDN.PAID_CORE_CUST_ID, '-1') ||'~~'||upper(COALESCE (trim(PYMT_ATRB_RDN.PYMT_ATRB_RDN_TYPE_CD), '--'))) AS DIR_ATRB_PRPS_PYMT_RDN_L_ID,
                      coalesce(PYMT_ATRB_RDN.PYMT_ATRB_RDN_ID, '-1') PYMT_ATRB_RDN_ID,
                      PYMT_ATRB_RDN.LOAD_DT LOAD_DT,
                      PYMT_ATRB_RDN.CDC_DT DATA_EFF_STRT_DT,
                      PYMT_ATRB_RDN.DATA_SRC_NM DATA_SRC_NM,
                      PYMT_ATRB_RDN.DATA_STAT_CD DATA_STAT_CD,
                      PYMT_ATRB_RDN.CRE_DT SRC_CRE_DT,
                      PYMT_ATRB_RDN.CRE_USER_NM SRC_CRE_USER_NM,
                      PYMT_ATRB_RDN.LAST_CHG_DT SRC_LAST_CHG_DT,
                      PYMT_ATRB_RDN.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
                      PYMT_ATRB_RDN.PYMT_ATRB_ID PYMT_ATRB_ID,
                      PYMT_ATRB_RDN.PRPS_PYMT_ID PRPS_PYMT_ID,
                      PYMT_ATRB_RDN.ACCT_PGM_CD ACCT_PGM_CD,
                      PYMT_ATRB_RDN.MBR_CORE_CUST_ID MBR_CORE_CUST_ID,
                      PYMT_ATRB_RDN.PAID_CORE_CUST_ID PAID_CORE_CUST_ID,
                      PYMT_ATRB_RDN.ST_FSA_CD ST_FSA_CD,
                      PYMT_ATRB_RDN.CNTY_FSA_CD CNTY_FSA_CD,
                      PYMT_ATRB_RDN.SBSD_PRD_STRT_YR SBSD_PRD_STRT_YR,
                      PYMT_ATRB_RDN.PYMT_ATRB_RDN_TYPE_CD PYMT_ATRB_RDN_TYPE_CD,
                      PYMT_ATRB_RDN.PYMT_ATRB_RDN_AMT PYMT_ATRB_RDN_AMT,
                      PYMT_ATRB_RDN.TOT_PYMT_ATRB_RDN_AMT TOT_PYMT_ATRB_RDN_AMT,
                      to_date('9999-12-31', 'YYYY-MM-DD') DATA_EFF_END_DT,
                      to_date('9999-12-31', 'YYYY-MM-DD') LOAD_END_DT,
                      MD5 (trim(PYMT_ATRB_RDN.ST_FSA_CD)||'~~'||trim(PYMT_ATRB_RDN.CNTY_FSA_CD)||'~~'||trim(PYMT_ATRB_RDN.ACCT_PGM_CD)||'~~'||PYMT_ATRB_RDN.MBR_CORE_CUST_ID||'~~'||PYMT_ATRB_RDN.PAID_CORE_CUST_ID||'~~'||trim(PYMT_ATRB_RDN.PYMT_ATRB_RDN_TYPE_CD)||'~~'||PYMT_ATRB_RDN.PYMT_ATRB_RDN_ID||'~~'||trim(PYMT_ATRB_RDN.DATA_STAT_CD)||'~~'||to_char(PYMT_ATRB_RDN.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PYMT_ATRB_RDN.CRE_USER_NM)||'~~'||to_char(PYMT_ATRB_RDN.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PYMT_ATRB_RDN.LAST_CHG_USER_NM)||'~~'||PYMT_ATRB_RDN.PYMT_ATRB_ID||'~~'||PYMT_ATRB_RDN.PRPS_PYMT_ID||'~~'||trim(PYMT_ATRB_RDN.ACCT_PGM_CD)||'~~'||PYMT_ATRB_RDN.MBR_CORE_CUST_ID||'~~'||PYMT_ATRB_RDN.PAID_CORE_CUST_ID||'~~'||trim(PYMT_ATRB_RDN.ST_FSA_CD)||'~~'||trim(PYMT_ATRB_RDN.CNTY_FSA_CD)||'~~'||PYMT_ATRB_RDN.SBSD_PRD_STRT_YR||'~~'||trim(PYMT_ATRB_RDN.PYMT_ATRB_RDN_TYPE_CD)||'~~'||PYMT_ATRB_RDN.PYMT_ATRB_RDN_AMT||'~~'||PYMT_ATRB_RDN.TOT_PYMT_ATRB_RDN_AMT) HASH_DIF
      FROM SBSD_STG.PYMT_ATRB_RDN PYMT_ATRB_RDN
      WHERE PYMT_ATRB_RDN.CDC_OPER_CD IN ('I',
                                          'UN')
        AND date(PYMT_ATRB_RDN.CDC_DT) = date(TO_TIMESTAMP ('{ETL_START_TIMESTAMP}', 'YYYY-MM-DD HH24:MI:SS.FF'))
      ORDER BY PYMT_ATRB_RDN.CDC_DT) stg
   LEFT JOIN EDV.PYMT_ATRB_RDN_LS dv ON (stg.HASH_DIF = dv.HASH_DIF
                                         AND dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD'))
   WHERE dv.HASH_DIF IS NULL )