with del_data as (
SELECT DISTINCT
DM.ARC_PLC_ELCT_DURB_ID,
DM.DATA_EFF_STRT_DT,
DM.data_eff_end_dt,
DM.ARC_PLC_ELCT_CD,
DM.ARC_PLC_ELCT_NM,
DM.ARC_PLC_ELCT_DESC
FROM (
SELECT
APH.DURB_ID ARC_PLC_ELCT_DURB_ID,
COALESCE(APE.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) DATA_EFF_STRT_DT,
COALESCE(APE.data_eff_end_dt, TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')) data_eff_end_dt,
APE.ARC_PLC_ELCT_CD ARC_PLC_ELCT_CD,
APE.DMN_VAL_NM ARC_PLC_ELCT_NM,
APE.DMN_VAL_DESC ARC_PLC_ELCT_DESC,
ROW_NUMBER() OVER ( PARTITION BY COALESCE(APE.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')), APE.ARC_PLC_ELCT_CD ORDER BY APE.DATA_EFF_STRT_DT DESC) AS ROW_NUM_PART
FROM EDV.ARC_PLC_ELCT_RS APE
LEFT JOIN EDV.ARC_PLC_ELCT_RH  APH ON (COALESCE(APE.ARC_PLC_ELCT_CD,'[NULL IN SOURCE]') = APH.ARC_PLC_ELCT_CD)
WHERE CAST(APE.DATA_EFF_END_DT as DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
AND NOT EXISTS ( SELECT '1' FROM EDV.ARC_PLC_ELCT_RS APE_IN
				 WHERE APE_IN.ARC_PLC_ELCT_CD = APE.ARC_PLC_ELCT_CD
                 AND CAST(APE_IN.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
			 ) 
			  
AND APH.DURB_ID IS NOT NULL            
) DM WHERE DM.ROW_NUM_PART = 1
)
SELECT ud.arc_plc_elct_durb_id, 
	   0 as cur_rcd_ind, 
	   ud.data_eff_strt_dt,
	   ud.data_eff_end_dt, 
	   ud.data_eff_strt_dt as cre_dt, 
	   ud.arc_plc_elct_cd, 
	   ud.arc_plc_elct_nm, 
	   ud.arc_plc_elct_desc
FROM del_data ud
where ud.arc_plc_elct_durb_id > 0
order by ud.arc_plc_elct_durb_id




