SELECT SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
GRSLD_RANK_FCTR_IDN,
GRSLD_RANK_SFCTR_IDN,
CNSV_PRAC_CD,
GRSLD_USE_TYPE_NM,
RANK_PNT_CT,
GRSLD_RANK_SFCTR_PRAC_USE_ID,
GRSLD_RANK_SFCTR_ID,
CNSV_PRAC_USE_TYPE_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
CRE_USER_NM,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
GRSLD_RANK_FCTR_IDN,
GRSLD_RANK_SFCTR_IDN,
CNSV_PRAC_CD,
GRSLD_USE_TYPE_NM,
RANK_PNT_CT,
GRSLD_RANK_SFCTR_PRAC_USE_ID,
GRSLD_RANK_SFCTR_ID,
CNSV_PRAC_USE_TYPE_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
CRE_USER_NM,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
GRSLD_RANK_SFCTR_PRAC_USE_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_CD CNSV_PRAC_CD,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_NM GRSLD_USE_TYPE_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_PRAC_USE_ID GRSLD_RANK_SFCTR_PRAC_USE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID CNSV_PRAC_USE_TYPE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE" GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE
LEFT JOIN    "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR
ON GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".CONSERVATION_PRACTICE_USAGE_TYPE
ON GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID = CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_USE_TYPE_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR 
ON GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_USAGE_TYPE
ON CONSERVATION_PRACTICE_USAGE_TYPE.GRSLD_USE_TYPE_ID = GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP
ON GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID
WHERE GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.OP <> 'D'

UNION
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_CD CNSV_PRAC_CD,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_NM GRSLD_USE_TYPE_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_PRAC_USE_ID GRSLD_RANK_SFCTR_PRAC_USE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID CNSV_PRAC_USE_TYPE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_SUBFACTOR.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_SUBFACTOR" GRASSLAND_RANKING_SUBFACTOR
JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE
ON GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".CONSERVATION_PRACTICE_USAGE_TYPE
ON GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID= CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_USE_TYPE_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR 
ON GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_USAGE_TYPE
ON CONSERVATION_PRACTICE_USAGE_TYPE.GRSLD_USE_TYPE_ID = GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP
ON GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID
WHERE GRASSLAND_RANKING_SUBFACTOR.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR.OP <> 'D'

UNION
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_CD CNSV_PRAC_CD,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_NM GRSLD_USE_TYPE_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_PRAC_USE_ID GRSLD_RANK_SFCTR_PRAC_USE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID CNSV_PRAC_USE_TYPE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
CONSERVATION_PRACTICE_USAGE_TYPE.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."CONSERVATION_PRACTICE_USAGE_TYPE" CONSERVATION_PRACTICE_USAGE_TYPE
JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE 
ON CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_USE_TYPE_ID = GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID  
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR 
ON GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR  
ON GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_USAGE_TYPE 
ON CONSERVATION_PRACTICE_USAGE_TYPE.GRSLD_USE_TYPE_ID = GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP 
ON GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID
WHERE CONSERVATION_PRACTICE_USAGE_TYPE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and CONSERVATION_PRACTICE_USAGE_TYPE.OP <> 'D'

UNION
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_CD CNSV_PRAC_CD,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_NM GRSLD_USE_TYPE_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_PRAC_USE_ID GRSLD_RANK_SFCTR_PRAC_USE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID CNSV_PRAC_USE_TYPE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_FACTOR.OP,
4 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_FACTOR" GRASSLAND_RANKING_FACTOR 
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR
ON GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID 
JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE
ON GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID
LEFT JOIN    "fsa-{env}-cnsv".CONSERVATION_PRACTICE_USAGE_TYPE
ON GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID = CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_USE_TYPE_ID  
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_USAGE_TYPE
ON CONSERVATION_PRACTICE_USAGE_TYPE.GRSLD_USE_TYPE_ID = GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP
ON GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID
WHERE GRASSLAND_RANKING_FACTOR.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_FACTOR.OP <> 'D'

UNION
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_CD CNSV_PRAC_CD,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_NM GRSLD_USE_TYPE_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_PRAC_USE_ID GRSLD_RANK_SFCTR_PRAC_USE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID CNSV_PRAC_USE_TYPE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_USAGE_TYPE.OP,
5 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_USAGE_TYPE" GRASSLAND_USAGE_TYPE
LEFT JOIN   "fsa-{env}-cnsv".CONSERVATION_PRACTICE_USAGE_TYPE 
ON GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_ID = CONSERVATION_PRACTICE_USAGE_TYPE.GRSLD_USE_TYPE_ID
JOIN    "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE 
ON CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_USE_TYPE_ID = GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID
LEFT JOIN    "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR
ON GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR  
ON GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP
ON GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID
WHERE GRASSLAND_USAGE_TYPE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_USAGE_TYPE.OP <> 'D'

UNION
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_CD CNSV_PRAC_CD,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_NM GRSLD_USE_TYPE_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_PRAC_USE_ID GRSLD_RANK_SFCTR_PRAC_USE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID CNSV_PRAC_USE_TYPE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT14SGNP.OP,
6 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."EWT14SGNP" EWT14SGNP
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR  
ON EWT14SGNP.SGNP_ID = GRASSLAND_RANKING_FACTOR.SGNP_ID
LEFT JOIN    "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR 
ON GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID
JOIN    "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE 
ON GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".CONSERVATION_PRACTICE_USAGE_TYPE 
ON GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID = CONSERVATION_PRACTICE_USAGE_TYPE.CNSV_PRAC_USE_TYPE_ID     
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_USAGE_TYPE 
ON CONSERVATION_PRACTICE_USAGE_TYPE.GRSLD_USE_TYPE_ID = GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_ID
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT14SGNP.OP <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL GRSLD_RANK_FCTR_IDN,
NULL GRSLD_RANK_SFCTR_IDN,
NULL CNSV_PRAC_CD,
NULL GRSLD_USE_TYPE_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_PRAC_USE_ID GRSLD_RANK_SFCTR_PRAC_USE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CNSV_PRAC_USE_TYPE_ID CNSV_PRAC_USE_TYPE_ID,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE
WHERE GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR_PRACTICE_USAGE.OP = 'D'
)