INSERT into
EDV.FARM_RCON_LS(FARM_RCON_L_ID,FARM_RCON_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
RCON_ID,
PRNT_FARM_YR_ID,
RSLT_FARM_YR_ID,
PGM_YR, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(SELECT stg.* from (SELECT DISTINCT 
MD5(MD5(upper(coalesce( FARM_RCON.PRNT_ST_FSA_CD,'--') ||'~~'|| coalesce(FARM_RCON.PRNT_CNTY_FSA_CD,'--') ||'~~'|| coalesce(FARM_RCON.PRNT_FARM_NBR,'--')))||'~~'||MD5(upper(coalesce( FARM_RCON.RSLT_ST_FSA_CD,'--') ||'~~'|| coalesce( FARM_RCON.RSLT_CNTY_FSA_CD,'--')||'~~'||coalesce(FARM_RCON.RSLT_FARM_NBR,'--')))) as FARM_RCON_L_ID, FARM_RCON.FARM_RCON_ID FARM_RCON_ID,FARM_RCON.LOAD_DT LOAD_DT,FARM_RCON.CDC_DT DATA_EFF_STRT_DT,FARM_RCON.DATA_SRC_NM DATA_SRC_NM,FARM_RCON.DATA_STAT_CD DATA_STAT_CD,FARM_RCON.CRE_DT SRC_CRE_DT,FARM_RCON.LAST_CHG_DT SRC_LAST_CHG_DT,FARM_RCON.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,FARM_RCON.RCON_ID RCON_ID,FARM_RCON.PRNT_FARM_YR_ID PRNT_FARM_YR_ID,FARM_RCON.RSLT_FARM_YR_ID RSLT_FARM_YR_ID,FARM_RCON.PGM_YR PGM_YR ,
to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(upper(coalesce( FARM_RCON.PRNT_ST_FSA_CD,'--') ||'~~'|| coalesce(FARM_RCON.PRNT_CNTY_FSA_CD,'--') ||'~~'|| coalesce(FARM_RCON.PRNT_FARM_NBR,'--'))||'~~'||upper(coalesce( FARM_RCON.RSLT_ST_FSA_CD,'--') ||'~~'|| coalesce( FARM_RCON.RSLT_CNTY_FSA_CD,'--')||'~~'||coalesce(FARM_RCON.RSLT_FARM_NBR,'--'))||'~~'||FARM_RCON.FARM_RCON_ID||'~~'||trim(both FARM_RCON.DATA_STAT_CD)||'~~'||to_char(FARM_RCON.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(FARM_RCON.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both FARM_RCON.LAST_CHG_USER_NM)||'~~'||FARM_RCON.RCON_ID||'~~'||FARM_RCON.PRNT_FARM_YR_ID||'~~'||FARM_RCON.RSLT_FARM_YR_ID||'~~'||FARM_RCON.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.FARM_RCON  FARM_RCON
 where FARM_RCON.CDC_OPER_CD IN ('I','UN')
order by FARM_RCON.CDC_DT
) stg
 LEFT JOIN  EDV.FARM_RCON_LS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.FARM_RCON_LS ls
                where stg.FARM_RCON_L_ID = ls.FARM_RCON_L_ID
			    and stg.FARM_RCON_ID = ls.FARM_RCON_ID
			    and stg.LOAD_DT = ls.LOAD_DT
			   )
);