MERGE into
EDV.FRS_TM_PRD_RS dv
 using( 
 SELECT sub1.*
FROM
(	
	SELECT sub.*,
		   ROW_NUMBER() OVER (PARTITION BY PGM_YR, TM_PRD_ID ORDER BY LOAD_DT desc) PGM_YR_RANK
	FROM
	(
		select distinct
		coalesce(TM_PRD.TM_PRD_NM, '0000') PGM_YR,
		coalesce(TM_PRD.TM_PRD_NM, '--') TM_PRD_NM,
		TM_PRD.CDC_DT DATA_EFF_STRT_DT,
		TM_PRD.DATA_SRC_NM DATA_SRC_NM,
		TM_PRD.DATA_STAT_CD DATA_STAT_CD,
		TM_PRD.LOAD_DT LOAD_DT,
		TM_PRD.PGM_ABR PGM_ABR,
		TM_PRD.CRE_DT SRC_CRE_DT,
		TM_PRD.LAST_CHG_DT SRC_LAST_CHG_DT,
		TM_PRD.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
		TM_PRD.TM_PRD_END_DT TM_PRD_END_DT,
		TM_PRD.TM_PRD_ID TM_PRD_ID,
		TM_PRD.TM_PRD_STRT_DT TM_PRD_STRT_DT,
		MD5(trim(both TM_PRD.TM_PRD_NM)||'~~'||trim(both TM_PRD.DATA_STAT_CD)||'~~'||trim(both TM_PRD.PGM_ABR)||'~~'||to_char(TM_PRD.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TM_PRD.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TM_PRD.LAST_CHG_USER_NM)||'~~'||to_char(TM_PRD.TM_PRD_END_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TM_PRD.TM_PRD_ID||'~~'||to_char(TM_PRD.TM_PRD_STRT_DT,'YYYY-MM-DD HH24:MI:SS.US')) HASH_DIF
		FROM SQL_FARM_RCD_STG.TM_PRD
		where TM_PRD.cdc_oper_cd IN ('I','UN')
		order by TM_PRD.CDC_DT
	) sub
) sub1
WHERE sub1.PGM_YR_RANK = 1
) stg 
 on ( 
coalesce(stg.TM_PRD_ID,0) = coalesce(dv.TM_PRD_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;