INSERT into
EDV.FRS_TM_PRD_RS( PGM_YR,
TM_PRD_NM,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
LOAD_DT,
PGM_ABR,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
TM_PRD_END_DT,
TM_PRD_ID,
TM_PRD_STRT_DT, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(
SELECT stg.* from (
SELECT DISTINCT
coalesce((TM_PRD.TM_PRD_NM::numeric), 0000) PGM_YR,
coalesce(TM_PRD.TM_PRD_NM, '--') TM_PRD_NM,
TM_PRD.CDC_DT DATA_EFF_STRT_DT,
TM_PRD.DATA_SRC_NM DATA_SRC_NM,
TM_PRD.DATA_STAT_CD DATA_STAT_CD,
TM_PRD.LOAD_DT LOAD_DT,
TM_PRD.PGM_ABR PGM_ABR,
TM_PRD.CRE_DT SRC_CRE_DT,
TM_PRD.LAST_CHG_DT SRC_LAST_CHG_DT,
TM_PRD.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
TM_PRD.TM_PRD_END_DT TM_PRD_END_DT,
TM_PRD.TM_PRD_ID TM_PRD_ID,
TM_PRD.TM_PRD_STRT_DT TM_PRD_STRT_DT ,
TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(trim(both TM_PRD.TM_PRD_NM)||'~~'||trim(both TM_PRD.DATA_STAT_CD)||'~~'||trim(both TM_PRD.PGM_ABR)||'~~'||to_char(TM_PRD.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TM_PRD.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TM_PRD.LAST_CHG_USER_NM)||'~~'||to_char(TM_PRD.TM_PRD_END_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TM_PRD.TM_PRD_ID||'~~'||to_char(TM_PRD.TM_PRD_STRT_DT,'YYYY-MM-DD HH24:MI:SS.US')) HASH_DIF
FROM SQL_FARM_RCD_STG.TM_PRD
where TM_PRD.cdc_oper_cd IN ('I','UN')
order by TM_PRD.CDC_DT
) stg 
LEFT JOIN  EDV.FRS_TM_PRD_RS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and  not exists (select 1 from EDV.FRS_TM_PRD_RS rs
				 where stg.PGM_YR = rs.PGM_YR
				 and stg.TM_PRD_ID = rs.TM_PRD_ID
				 and stg.LOAD_DT = rs.LOAD_DT
                 )
)
;

