MERGE INTO
EDV.FARM_TR_YR_LS dv
USING(SELECT DISTINCT MD5(MD5(UPPER(COALESCE(TR_YR.ST_FSA_CD ,'--')||'~~'||COALESCE(TR_YR.CNTY_FSA_CD,'--')||'~~'||COALESCE(TR_YR.FARM_NBR ,'--')))||'~~'||MD5(UPPER(COALESCE(TR_YR.ST_FSA_CD ,'--')||'~~'||COALESCE(TR_YR.CNTY_FSA_CD,'--')||'~~'||COALESCE((TR_YR.TR_NBR)::numeric  ,-1)))) as FARM_TR_L_ID,COALESCE(TR_YR.TR_YR_ID, '-1') TR_YR_ID,TR_YR.LOAD_DT LOAD_DT,TR_YR.CDC_DT DATA_EFF_STRT_DT,TR_YR.DATA_SRC_NM DATA_SRC_NM,TR_YR.DATA_STAT_CD DATA_STAT_CD,TR_YR.CRE_DT SRC_CRE_DT,TR_YR.LAST_CHG_DT SRC_LAST_CHG_DT,TR_YR.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_YR.TR_ID TR_ID,TR_YR.FARM_YR_ID FARM_YR_ID,TR_YR.FMLD_ACRG FMLD_ACRG,TR_YR.CPLD_ACRG CPLD_ACRG,TR_YR.CRP_ACRG CRP_ACRG,TR_YR.MPL_ACRG MPL_ACRG,TR_YR.WBP_ACRG WBP_ACRG,TR_YR.WRP_TR_ACRG WRP_TR_ACRG,TR_YR.GRP_CPLD_ACRG GRP_CPLD_ACRG,TR_YR.ST_CNSV_ACRG ST_CNSV_ACRG,TR_YR.OT_CNSV_ACRG OT_CNSV_ACRG,TR_YR.SUGARCANE_ACRG SGRCN_ACRG,TR_YR.NAP_CROP_ACRG NAP_CROP_ACRG,TR_YR.NTV_SOD_BRK_OUT_ACRG NTV_SOD_BRK_OUT_ACRG,TR_YR.HEL_TR_CD SRC_HEL_TR_CD,HEL_TR_RS.DMN_VAL_NM HEL_TR_NM,TR_YR.WL_PRES_CD SRC_WL_PRES_CD,WL_PRES_RS.DMN_VAL_NM WL_PRES_NM,
TR_YR.PGM_YR PGM_YR ,TR_YR.EWP_TR_ACRG,TR_YR.CDC_OPER_CD,
MD5(UPPER(COALESCE(TR_YR.ST_FSA_CD ,'--')||'~~'||COALESCE(TR_YR.CNTY_FSA_CD,'--')||'~~'||COALESCE(TR_YR.FARM_NBR ,'--'))||'~~'||UPPER(COALESCE(TR_YR.ST_FSA_CD ,'--')||'~~'||COALESCE(TR_YR.CNTY_FSA_CD,'--')||'~~'||COALESCE((TR_YR.TR_NBR)::numeric  ,-1))||'~~'||TR_YR.TR_YR_ID||'~~'||TRIM(both TR_YR.DATA_STAT_CD)||'~~'||to_char(TR_YR.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TR_YR.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TRIM(both TR_YR.LAST_CHG_USER_NM)||'~~'||TR_YR.TR_ID||'~~'||TR_YR.FARM_YR_ID||'~~'||TR_YR.FMLD_ACRG||'~~'||TR_YR.CPLD_ACRG||'~~'||TR_YR.CRP_ACRG||'~~'||TR_YR.MPL_ACRG||'~~'||TR_YR.WBP_ACRG||'~~'||TR_YR.WRP_TR_ACRG||'~~'||TR_YR.GRP_CPLD_ACRG||'~~'||TR_YR.ST_CNSV_ACRG||'~~'||TR_YR.OT_CNSV_ACRG||'~~'||TR_YR.SUGARCANE_ACRG||'~~'||TR_YR.NAP_CROP_ACRG||'~~'||TR_YR.NTV_SOD_BRK_OUT_ACRG||'~~'||TR_YR.HEL_TR_CD||'~~'||TRIM(both HEL_TR_RS.DMN_VAL_NM)||'~~'||TR_YR.WL_PRES_CD||'~~'||TRIM(both WL_PRES_RS.DMN_VAL_NM)||'~~'||TR_YR.PGM_YR||'~~'||TR_YR.EWP_TR_ACRG) HASH_DIF
FROM SQL_FARM_RCD_STG.TR_YR 
LEFT JOIN(SELECT * from EDV.HEL_TR_RS
WHERE load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) HEL_TR_RS 
ON (TR_YR.HEL_TR_CD = HEL_TR_RS.DMN_VAL_ID) 
LEFT JOIN(SELECT * from EDV.WL_PRES_RS
WHERE load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) WL_PRES_RS 
ON (TR_YR.WL_PRES_CD = WL_PRES_RS.DMN_VAL_ID)
 WHERE TR_YR.CDC_OPER_CD='D'
--AND date_trunc('day', TR_YR.CDC_DT) = date_trunc('day', TO_TIMESTAMP('<DATA_EFF_STRT_DT>', 'YYYY-MM-DD HH24:MI:SS.FF'))
--AND TR_YR.LOAD_DT = TO_TIMESTAMP('<LOAD_DT>', 'YYYY-MM-DD HH24:MI:SS.FF')
order by TR_YR.CDC_DT)
stg
 on ( COALESCE(stg.TR_YR_ID,0) = COALESCE(dv.TR_YR_ID,0) ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
SET LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN
INSERT(
FARM_TR_L_ID,TR_YR_ID,LOAD_DT,
DATA_EFF_STRT_DT,DATA_SRC_NM,DATA_STAT_CD,
SRC_CRE_DT,SRC_LAST_CHG_DT,SRC_LAST_CHG_USER_NM,
TR_ID,FARM_YR_ID,FMLD_ACRG,
CPLD_ACRG,CRP_ACRG,MPL_ACRG,
WBP_ACRG,WRP_TR_ACRG,GRP_CPLD_ACRG,
ST_CNSV_ACRG,OT_CNSV_ACRG,SGRCN_ACRG,
NAP_CROP_ACRG,
NTV_SOD_BRK_OUT_ACRG,
SRC_HEL_TR_CD,
HEL_TR_NM,
SRC_WL_PRES_CD,
WL_PRES_NM,
PGM_YR,  EWP_TR_ACRG ,
DATA_EFF_END_DT,LOAD_END_DT,HASH_DIF)
VALUES (
stg.FARM_TR_L_ID,stg.TR_YR_ID,stg.LOAD_DT,stg.DATA_EFF_STRT_DT,stg.DATA_SRC_NM,stg.DATA_STAT_CD,stg.SRC_CRE_DT,stg.SRC_LAST_CHG_DT,stg.SRC_LAST_CHG_USER_NM,stg.TR_ID,stg.FARM_YR_ID,stg.FMLD_ACRG,stg.CPLD_ACRG,stg.CRP_ACRG,stg.MPL_ACRG,stg.WBP_ACRG,stg.WRP_TR_ACRG,stg.GRP_CPLD_ACRG,stg.ST_CNSV_ACRG,stg.OT_CNSV_ACRG,stg.SGRCN_ACRG,stg.NAP_CROP_ACRG,stg.NTV_SOD_BRK_OUT_ACRG,stg.SRC_HEL_TR_CD,stg.HEL_TR_NM,stg.SRC_WL_PRES_CD,stg.WL_PRES_NM,stg.PGM_YR,stg.EWP_TR_ACRG,stg.DATA_EFF_STRT_DT,stg.LOAD_DT,
stg.HASH_DIF
)
;