MERGE  INTO
EDV.FLD_CLU_YR_HS dv
USING(
SELECT sub1.*
FROM
(	
	SELECT sub.*,
		   ROW_NUMBER() OVER (PARTITION BY FLD_H_ID ORDER BY LOAD_DT desc) FLD_H_ID_RANK
	FROM
	(
		SELECT  DISTINCT MD5(upper(coalesce(trim(both CLU_YR.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both CLU_YR.CNTY_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both Lpad(trim(both CLU_YR.FARM_NBR), 7,'0')), '--'))||'~~'||upper(coalesce(trim(both CLU_YR.TR_NBR), '-1'))||'~~'||upper(coalesce(trim(both ltrim(trim(both CLU_YR.FLD_NBR),'0')),'--'))) as FLD_H_ID,
		coalesce(CLU_YR.CLU_YR_ID, '-1') CLU_YR_ID,
		CLU_YR.LOAD_DT LOAD_DT,
		CLU_YR.CDC_DT DATA_EFF_STRT_DT,
		CLU_YR.DATA_SRC_NM DATA_SRC_NM,
		CLU_YR.DATA_STAT_CD SRC_DATA_STAT_CD,
		CLU_YR.CRE_DT SRC_CRE_DT,
		CLU_YR.LAST_CHG_DT SRC_LAST_CHG_DT,
		CLU_YR.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
		CLU_YR.CLU_ALT_ID CLU_ALT_ID,
		CLU_YR.PGM_YR PGM_YR,
		CLU_YR.LOC_CNTY_FSA_CD LOC_CNTY_FSA_CD,
		CLU_YR.LOC_ST_FSA_CD LOC_ST_FSA_CD,
		CLU_YR.ST_ANSI_CD ST_ANSI_CD,
		CLU_YR.CNTY_ANSI_CD CNTY_ANSI_CD,
		CLU_YR.CONG_DIST_CD CONG_DIST_CD,
		CLU_YR.LAND_CLS_ID LAND_CLS_ID,
		CLU_YR.CLU_ACRG CLU_ACRG,
		CLU_YR.HEL_STAT_ID HEL_STAT_ID,
		CLU_YR.CPLD_IND_3CM CPLD_IND_3CM,
		CLU_YR.CLU_DESC CLU_DESC,
		CLU_YR.CRP_CTR_NBR CRP_CTR_NBR,
		CLU_YR.CRP_CTR_EXPR_DT CRP_CTR_EXPR_DT,
		CLU_YR.CNSV_PRAC_ID CNSV_PRAC_ID,
		CLU_YR.NTV_SOD_CVSN_DT NTV_SOD_CVSN_DT,
		CLU_YR.SOD_CVSN_CROP_YR_1 SOD_CVSN_CROP_YR_1,
		CLU_YR.SOD_CVSN_CROP_YR_2 SOD_CVSN_CROP_YR_2,
		CLU_YR.SOD_CVSN_CROP_YR_3 SOD_CVSN_CROP_YR_3,
		CLU_YR.SOD_CVSN_CROP_YR_4 SOD_CVSN_CROP_YR_4,
		CLU_YR.TR_YR_ID TR_YR_ID ,
		CLU_YR.CDC_OPER_CD,
		MD5(trim(both CLU_YR.ST_FSA_CD)||'~~'||trim(both CLU_YR.CNTY_FSA_CD)||'~~'||upper(coalesce(trim(both Lpad(trim(both CLU_YR.FARM_NBR), 7,'0')), '--'))||'~~'||upper(coalesce(trim(both (CLU_YR.TR_NBR), '-1'))||'~~'||upper(coalesce(trim(both ltrim(trim(both CLU_YR.FLD_NBR),'0')),'--'))||'~~'||CLU_YR.CLU_YR_ID||'~~'||trim(both CLU_YR.DATA_STAT_CD)||'~~'||to_char(CLU_YR.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(CLU_YR.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CLU_YR.LAST_CHG_USER_NM)||'~~'||trim(both CLU_YR.CLU_ALT_ID)||'~~'||CLU_YR.PGM_YR||'~~'||trim(both CLU_YR.LOC_CNTY_FSA_CD)||'~~'||trim(both CLU_YR.LOC_ST_FSA_CD)||'~~'||trim(both CLU_YR.ST_ANSI_CD)||'~~'||trim(both CLU_YR.CNTY_ANSI_CD)||'~~'||trim(both CLU_YR.CONG_DIST_CD)||'~~'||CLU_YR.LAND_CLS_ID||'~~'||CLU_YR.CLU_ACRG||'~~'||CLU_YR.HEL_STAT_ID||'~~'||trim(both CLU_YR.CPLD_IND_3CM)||'~~'||trim(both CLU_YR.CLU_DESC)||'~~'||trim(both CLU_YR.CRP_CTR_NBR)||'~~'||to_char(CLU_YR.CRP_CTR_EXPR_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||CLU_YR.CNSV_PRAC_ID||'~~'||to_char(CLU_YR.NTV_SOD_CVSN_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||CLU_YR.SOD_CVSN_CROP_YR_1||'~~'||CLU_YR.SOD_CVSN_CROP_YR_2||'~~'||CLU_YR.SOD_CVSN_CROP_YR_3||'~~'||CLU_YR.SOD_CVSN_CROP_YR_4||'~~'||CLU_YR.TR_YR_ID)) HASH_DIF
		FROM SQL_FARM_RCD_STG.CLU_YR  CLU_YR
		WHERE CLU_YR.CDC_OPER_CD IN ('I','UN')
		ORDER BY CLU_YR.CDC_DT
	) sub
) sub1
WHERE sub1.FLD_H_ID_RANK = 1
)
stg
 on ( 
coalesce(stg.CLU_YR_ID,0) = coalesce(dv.CLU_YR_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
SET LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;