with APP_DS_RW_INCR_FLD_YR_DIM as
 (
 Select distinct DURB_ID ,FLD_H_ID FROM EDV.FLD_H  where DATA_SRC_NM <> 'SYSGEN'
And FLD_H_ID in
   (
      SELECT FLD_H_ID          FROM EDV.FLD_CLU_YR_HS 
     WHERE CAST(DATA_EFF_STRT_DT as DATE) = TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')           
    UNION
     SELECT FLD_H_ID   from EDV.FLD_CLU_YR_HS where HEL_STAT_ID in (
     Select DMN_VAL_ID FROM EDV.FLD_HEL_STAT_RS  WHERE CAST(DATA_EFF_STRT_DT as DATE) = TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') )
    UNION
     SELECT FLD_H_ID   from EDV.FLD_CLU_YR_HS where LAND_CLS_ID in (
     Select DMN_VAL_ID  FROM EDV.LAND_CLS_RS  WHERE CAST(DATA_EFF_STRT_DT as DATE) = TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') )
    )
 )
Select 
dv.FLD_DURB_ID ,
1 CUR_RCD_IND,
dv.ST_FSA_CD ,
dv.CNTY_FSA_CD ,
dv.FARM_NBR ,
dv.TR_NBR ,
dv.FLD_NBR ,
COALESCE(dv.PGM_YR ,'-1') PGM_YR,
COALESCE(dv.SRC_DATA_SRC_NM ,'SQL_FARM_RCD') SRC_DATA_SRC_NM,
dv.CLU_ACRG,
dv.CLU_ALT_ID,
dv.CLU_DESC,
dv.DATA_EFF_STRT_DT ,
dv.DATA_EFF_END_DT ,
dv.ST_NM ,
dv.CNTY_NM ,
dv.LOC_ST_FSA_CD ,
dv.LOC_ST_NM ,
dv.LOC_CNTY_FSA_CD ,
dv.LOC_CNTY_NM ,
dv.ST_ANSI_CD ,
dv.ANSI_ST_NM ,
dv.CNTY_ANSI_CD ,
dv.ANSI_CNTY_NM ,
dv.CONG_DIST_CD ,
dv.CONG_DIST_NM ,
dv.CPLD_IND_3CM ,
dv.NTV_SOD_CVSN_DT ,
dv.HEL_STAT_CD ,
dv.HEL_STAT_NM ,
dv.HEL_STAT_DESC ,
dv.LAND_CLS_CD ,
dv.LAND_CLS_NM ,
dv.LAND_CLS_DESC ,
dv.CRP_CTR_NBR ,
dv.CRP_CTR_EXPR_DT ,
dv.SRC_DATA_STAT_CD,
dv.DEF_ERR_IND ,
md5(dv.FLD_DURB_ID||'~~'||dv.PGM_YR) BUS_KEY,
('FLD_DURB_ID:'||DV.FLD_DURB_ID ||'PGM_YR:'||dv.PGM_YR ) BUS_KEY_ERR 
 from (
 Select DV_ALL.* From  
  (
 Select  
 DV_DR.FLD_H_ID,
 DV_DR.CLU_YR_ID,
 DV_DR.CLU_ACRG,
 DV_DR.CLU_ALT_ID,
 DV_DR.CLU_DESC,
 DV_DR.CNTY_ANSI_CD,
 DV_DR.CONG_DIST_CD,
 DV_DR.CPLD_IND_3CM,
 DV_DR.CRP_CTR_EXPR_DT,
 DV_DR.SRC_DATA_STAT_CD,
 DV_DR.CRP_CTR_NBR,
 DV_DR.DATA_EFF_END_DT,
 greatest(
    COALESCE(DV_DR.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),
    COALESCE(HS.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) ,
    COALESCE(LNDS.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD'))  
    )       
 DATA_EFF_STRT_DT ,
 DV_DR.DATA_SRC_NM SRC_DATA_SRC_NM,
 DV_DR.LOC_CNTY_FSA_CD,
 DV_DR.LOC_ST_FSA_CD,
 DV_DR.NTV_SOD_CVSN_DT,
 DV_DR.PGM_YR,
 DV_DR.ST_ANSI_CD,
 h.DURB_ID FLD_DURB_ID,
 h.FARM_NBR,
 h.FLD_NBR,
 h.ST_FSA_CD,
 h.CNTY_FSA_CD,
 h.TR_NBR,
 HS.DMN_VAL_DESC HEL_STAT_DESC,
 HS.DMN_VAL_NM HEL_STAT_NM,
 HS.FLD_HEL_STAT_CD HEL_STAT_CD,
 LNDS.DMN_VAL_DESC  LAND_CLS_DESC,
 LNDS.DMN_VAL_NM LAND_CLS_NM,
 LNDS.LAND_CLS_ID LAND_CLS_CD,
 CONG_DIST_DIM.CONG_DIST_NM,
 ANSI_ST_CNTY_DIM.ST_NM ANSI_ST_NM,
 ANSI_ST_CNTY_DIM.CNTY_NM ANSI_CNTY_NM,
 FSA_ST_CNTY_DIM.ST_NM,
 FSA_ST_CNTY_DIM.CNTY_NM,
 LOC_FSA_ST_CNTY_DIM.ST_NM LOC_ST_NM,
 LOC_FSA_ST_CNTY_DIM.CNTY_NM LOC_CNTY_NM,
 CASE
     WHEN   h.DURB_ID IS NOT NULL 
      THEN 0
     ELSE 1 
     END DEF_ERR_IND , 
 ROW_NUMBER() OVER ( PARTITION BY h.DURB_ID, DV_DR.PGM_YR ORDER BY  CASE DV_DR.SRC_DATA_STAT_CD
            WHEN 'A' THEN 1
            WHEN 'I' THEN 2
            WHEN 'D' THEN 3
            ELSE 4
            END ASC,
         DV_DR.SRC_LAST_CHG_DT DESC NULLS LAST          
   ) AS PRECEDENCE
 from  
 (
 Select * from EDV.FLD_CLU_YR_HS   
 where   TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(FLD_CLU_YR_HS.DATA_EFF_STRT_DT AS DATE)
  AND TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') < CAST(FLD_CLU_YR_HS.DATA_EFF_END_DT AS DATE) 
  And SRC_DATA_STAT_CD <> 'D'
  And FLD_H_ID IN ( select FLD_H_ID from  APP_DS_RW_INCR_FLD_YR_DIM )
  -- And FLD_H_ID in ('a92ae8234dcef7647085371bb9a3f2c0','c93c05696aff6b24d4f309166386d696','aacb3c260638f996eded519f006aafbc','0b0c43a6b70d00a0637984677e1df0ac')
 )  DV_DR
 Inner join  EDV.FLD_H h
 ON (  COALESCE(h.FLD_H_ID,'EDW DEFAULT') = COALESCE(DV_DR.FLD_H_ID ,'EDW DEFAULT')
    AND h.DATA_SRC_NM <> 'SYSGEN'
 )
 Left join   EDV.FLD_HEL_STAT_RS HS
 ON (  COALESCE(DV_DR.HEL_STAT_ID,-1) = COALESCE(HS.DMN_VAL_ID ,-1)
  AND TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(HS.DATA_EFF_STRT_DT AS DATE)
  AND TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') < CAST(HS.DATA_EFF_END_DT AS DATE) 
 )
 Left join   EDV.LAND_CLS_RS LNDS
 ON (  COALESCE(DV_DR.LAND_CLS_ID,-1) = COALESCE(LNDS.DMN_VAL_ID ,-1)
  AND TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(LNDS.DATA_EFF_STRT_DT AS DATE)
  AND TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') < CAST(LNDS.DATA_EFF_END_DT AS DATE) 
 )
 Left JOIN  
 (   select CONG_DIST_CD ,ST_FSA_CD , CONG_DIST_NM  ,ROW_NUMBER() OVER ( PARTITION BY CONG_DIST_CD ,ST_FSA_CD ORDER BY CRE_DT DESC
         ) AS PRECEDENCE
         from cmn_dim_dm_stg.CONG_DIST_DIM
         where  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(CONG_DIST_DIM.DATA_EFF_STRT_DT AS DATE)
        AND TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') < CAST(CONG_DIST_DIM.DATA_EFF_END_DT AS DATE)    
 ) CONG_DIST_DIM
   ON ( COALESCE(upper(trim(DV_DR.CONG_DIST_CD)),'--') =   COALESCE(upper(trim(CONG_DIST_DIM.CONG_DIST_CD)),'--')
        AND    COALESCE(upper(trim(DV_DR.LOC_ST_FSA_CD)),'--') =   COALESCE(upper(trim(CONG_DIST_DIM.ST_FSA_CD)),'--')  
         AND CONG_DIST_DIM.PRECEDENCE = 1  )
 Left JOIN cmn_dim_dm_stg.ANSI_ST_CNTY_DIM 
   ON ( COALESCE(upper(trim(DV_DR.ST_ANSI_CD)),'--') =   COALESCE(upper(trim(ANSI_ST_CNTY_DIM.ST_ANSI_CD)),'--')
        AND    COALESCE(upper(trim(DV_DR.CNTY_ANSI_CD)),'--') =   COALESCE(upper(trim(ANSI_ST_CNTY_DIM.CNTY_ANSI_CD)),'--')
        AND TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(ANSI_ST_CNTY_DIM.DATA_EFF_STRT_DT AS DATE)
        AND TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') < CAST(ANSI_ST_CNTY_DIM.DATA_EFF_END_DT AS DATE)         )
 LEFT  JOIN 
    (  SELECT FSA_ST_CNTY_SRGT_ID,FSA_ST_CNTY_DURB_ID ,ST_FSA_CD ,CNTY_FSA_CD,ST_NM,CNTY_NM ,ST_ABR
         ,ROW_NUMBER() OVER ( PARTITION BY ST_FSA_CD  ,CNTY_FSA_CD ORDER BY CRE_DT DESC
         ) AS PRECEDENCE
         FROM cmn_dim_dm_stg.FSA_ST_CNTY_DIM
         WHERE  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(FSA_ST_CNTY_DIM.DATA_EFF_STRT_DT AS DATE)
        AND TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') < CAST(FSA_ST_CNTY_DIM.DATA_EFF_END_DT AS DATE)
    ) FSA_ST_CNTY_DIM 
   ON ( COALESCE(trim(h.ST_FSA_CD),'--') = COALESCE(trim(FSA_ST_CNTY_DIM.ST_FSA_CD),'--')   
   And COALESCE(trim(h.CNTY_FSA_CD),'--') = COALESCE(trim(FSA_ST_CNTY_DIM.CNTY_FSA_CD),'--') AND FSA_ST_CNTY_DIM.PRECEDENCE = 1 ) 
 LEFT  JOIN 
    (  SELECT FSA_ST_CNTY_SRGT_ID,FSA_ST_CNTY_DURB_ID ,ST_FSA_CD ,CNTY_FSA_CD,ST_NM,CNTY_NM ,ST_ABR
         ,ROW_NUMBER() OVER ( PARTITION BY ST_FSA_CD  ,CNTY_FSA_CD ORDER BY CRE_DT DESC
         ) AS PRECEDENCE
         FROM cmn_dim_dm_stg.FSA_ST_CNTY_DIM
         WHERE TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(FSA_ST_CNTY_DIM.DATA_EFF_STRT_DT AS DATE)
        AND TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') < CAST(FSA_ST_CNTY_DIM.DATA_EFF_END_DT AS DATE)
    ) LOC_FSA_ST_CNTY_DIM 
   ON ( COALESCE(trim(DV_DR.LOC_ST_FSA_CD),'--') = COALESCE(trim(LOC_FSA_ST_CNTY_DIM.ST_FSA_CD),'--')   
   And COALESCE(trim(DV_DR.LOC_CNTY_FSA_CD),'--') = COALESCE(trim(LOC_FSA_ST_CNTY_DIM.CNTY_FSA_CD),'--') AND LOC_FSA_ST_CNTY_DIM.PRECEDENCE = 1 )
 ) DV_ALL
 WHERE DV_ALL.PRECEDENCE = 1 
 ) dv
 ORDER BY BUS_KEY asc
