SELECT DISTINCT
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_TYPE.SIGNUP_TYPE_CODE SGNP_TYPE_CD,
SIGNUP_TYPE.DATA_STATUS_CODE DATA_STAT_CD,
SIGNUP_TYPE.CREATION_DATE CRE_DT,
SIGNUP_TYPE.CREATION_USER_NAME CRE_USER_NM,
SIGNUP_TYPE.LAST_CHANGE_DATE LAST_CHG_DT,
SIGNUP_TYPE.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
OP AS CDC_OPER_CD,
1 AS row_num_part
FROM SIGNUP_TYPE
WHERE OP <> 'D'
UNION
SELECT DISTINCT
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_TYPE.SIGNUP_TYPE_CODE SGNP_TYPE_CD,
SIGNUP_TYPE.DATA_STATUS_CODE DATA_STAT_CD,
SIGNUP_TYPE.CREATION_DATE CRE_DT,
SIGNUP_TYPE.CREATION_USER_NAME CRE_USER_NM,
SIGNUP_TYPE.LAST_CHANGE_DATE LAST_CHG_DT,
SIGNUP_TYPE.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM SIGNUP_TYPE
WHERE OP = 'D'