INSERT into
EDV.FARM_CROP_IRR_HIST_L(FARM_CROP_IRR_HIST_L_ID ,
PGM_ABR,
FSA_CROP_CD,
FSA_CROP_TYPE_CD,
ST_FSA_CD,
CNTY_FSA_CD,
FARM_H_ID,
LOAD_DT,
DATA_SRC_NM)
(
select 
stg.FARM_CROP_IRR_HIST_L_ID,
stg.PGM_ABR,
stg.FSA_CROP_CD,
stg.FSA_CROP_TYPE_CD,
stg.ST_FSA_CD,
stg.CNTY_FSA_CD,
stg.FARM_H_ID,
stg.LOAD_DT,
stg.DATA_SRC_NM
from (
SELECT DISTINCT
coalesce(FARM_YR_CROP_IRR_HIST.PGM_ABR, '--') PGM_ABR,
coalesce(FARM_YR_CROP_IRR_HIST.FSA_CROP_CD, '--') FSA_CROP_CD,
coalesce(FARM_YR_CROP_IRR_HIST.FSA_CROP_TYPE_CD, '--') FSA_CROP_TYPE_CD,
coalesce(FARM_YR_CROP_IRR_HIST.ST_FSA_CD, '--') ST_FSA_CD,
coalesce(FARM_YR_CROP_IRR_HIST.CNTY_FSA_CD, '--') CNTY_FSA_CD,
MD5(upper(coalesce(FARM_YR_CROP_IRR_HIST.FARM_ST_FSA_CD ,'--')||'~~'||coalesce(FARM_YR_CROP_IRR_HIST.FARM_CNTY_FSA_CD,'--')||'~~'||coalesce(FARM_YR_CROP_IRR_HIST.FARM_NBR ,'--'))) FARM_H_ID,
FARM_YR_CROP_IRR_HIST.LOAD_DT LOAD_DT,
FARM_YR_CROP_IRR_HIST.DATA_SRC_NM DATA_SRC_NM,
ROW_NUMBER() OVER (PARTITION BY coalesce(FARM_YR_CROP_IRR_HIST.PGM_ABR, '--') ,
coalesce(FARM_YR_CROP_IRR_HIST.FSA_CROP_CD, '--') ,
coalesce(FARM_YR_CROP_IRR_HIST.FSA_CROP_TYPE_CD, '--') ,
coalesce(FARM_YR_CROP_IRR_HIST.ST_FSA_CD, '--') ,
coalesce(FARM_YR_CROP_IRR_HIST.CNTY_FSA_CD, '--') ,
coalesce(FARM_YR_CROP_IRR_HIST.FARM_ST_FSA_CD, '--') ,
coalesce(FARM_YR_CROP_IRR_HIST.FARM_CNTY_FSA_CD, '--') ,
MD5(upper(coalesce(FARM_YR_CROP_IRR_HIST.ST_FSA_CD ,'--')||'~~'||coalesce(FARM_YR_CROP_IRR_HIST.CNTY_FSA_CD,'--')||'~~'||coalesce(FARM_YR_CROP_IRR_HIST.FARM_NBR ,'--'))) ORDER BY FARM_YR_CROP_IRR_HIST.CDC_DT desc, FARM_YR_CROP_IRR_HIST.LOAD_DT desc) STG_EFF_DT_RANK,
MD5(upper(coalesce(trim(both FARM_YR_CROP_IRR_HIST.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_CROP_IRR_HIST.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_CROP_IRR_HIST.FSA_CROP_TYPE_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_CROP_IRR_HIST.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_CROP_IRR_HIST.CNTY_FSA_CD), '--')) ||'~~'||MD5(upper(coalesce(FARM_YR_CROP_IRR_HIST.FARM_ST_FSA_CD ,'--')||'~~'||coalesce(FARM_YR_CROP_IRR_HIST.FARM_CNTY_FSA_CD,'--')||'~~'||coalesce(FARM_YR_CROP_IRR_HIST.FARM_NBR ,'--')))) FARM_CROP_IRR_HIST_L_ID
FROM SQL_FARM_RCD_STG.FARM_YR_CROP_IRR_HIST
where FARM_YR_CROP_IRR_HIST.cdc_oper_cd IN ('I','UN','D')
) stg 
LEFT JOIN  EDV.FARM_CROP_IRR_HIST_L dv
 ON (
stg.FARM_CROP_IRR_HIST_L_ID = dv.FARM_CROP_IRR_HIST_L_ID
)
where (
dv.FARM_CROP_IRR_HIST_L_ID IS NULL
)
and stg.STG_EFF_DT_RANK = 1
)
;