INSERT CAR_DM_STG.ARC_PLC_BM_PRDR_SUMM
(
cd.CORE_CUST_ID
, CROP_FLD_RPT_SHR_QTY
, CROP_FLD_DTER_SHR_QTY
, AG_PROD_PLAN_ID
)
SELECT DISTINCT 
cd.CORE_CUST_ID
, nvl(appd.CROP_FLD_RPT_QTY * (appbpf.CROP_SHR_PCT/100),0) as CROP_FLD_RPT_SHR_QTY
,nvl(appd.CROP_FLD_DTER_QTY * (appbpf.CROP_SHR_PCT/100),0) as CROP_FLD_DTER_SHR_QTY
, appd.SRC_AG_PROD_PLAN_ID as AG_PROD_PLAN_ID
FROM CAR_DM_STG.AG_PROD_PLAN_BUS_PTY_FACT appbpf
INNER JOIN CAR_DM_STG.AG_PROD_PLAN_DIM appd
ON appbpf.AG_PROD_PLAN_DURB_ID = appd.AG_PROD_PLAN_DURB_ID
AND appd.CUR_RCD_IND = 1
AND appbpf.DATA_STAT_CD = 'A'
AND appd.SRC_DATA_STAT_CD = 'A'
AND appbpf.CROP_SHR_PCT > 0
INNER JOIN cmn_dim_dm_stg.CUST_DIM cd
ON appbpf.CUST_DURB_ID = cd.CUST_DURB_ID
AND cd.CUR_RCD_IND = 1'