pipeline {
  agent any
  environment {
    AWS_REGION = 'us-east-1'
  }

  stages {
    stage('Checkout') { steps { checkout scm } }

    stage('Install') {
      steps {
        sh '''
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
        '''
      }
    }

    stage('Deploy') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'aws-access-keys-dev',
          usernameVariable: 'AWS_ACCESS_KEY_ID',
          passwordVariable: 'AWS_SECRET_ACCESS_KEY'
        )]) {
          sh '''
            . .venv/bin/activate
            python deploy.py --config config/dev.json --region $AWS_REGION
          '''
        }
      }
    }
  }
}
