MERGE INTO EDV.PRPS_PYMT_ATRB_RDN_LS dv USING
  (SELECT DISTINCT MD5 (upper(COALESCE (trim(PRPS_PYMT_ATRB_RDN_LOG.ST_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(PRPS_PYMT_ATRB_RDN_LOG.CNTY_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(PRPS_PYMT_ATRB_RDN_LOG.ACCT_PGM_CD), '--')) ||'~~'||COALESCE (PRPS_PYMT_ATRB_RDN_LOG.MBR_CORE_CUST_ID, '-1') ||'~~'||COALESCE (PRPS_PYMT_ATRB_RDN_LOG.PAID_CORE_CUST_ID, '-1') ||'~~'||upper(COALESCE (trim(PRPS_PYMT_ATRB_RDN_LOG.PYMT_ATRB_RDN_TYPE_CD), '--'))) AS DIR_ATRB_PRPS_PYMT_RDN_L_ID,
                   coalesce(PRPS_PYMT_ATRB_RDN_LOG.PRPS_PYMT_ATRB_RDN_LOG_ID, '-1') PRPS_PYMT_ATRB_RDN_LOG_ID,
                   PRPS_PYMT_ATRB_RDN_LOG.LOAD_DT LOAD_DT,
                   PRPS_PYMT_ATRB_RDN_LOG.CDC_DT DATA_EFF_STRT_DT,
                   PRPS_PYMT_ATRB_RDN_LOG.DATA_SRC_NM DATA_SRC_NM,
                   PRPS_PYMT_ATRB_RDN_LOG.DATA_STAT_CD DATA_STAT_CD,
                   PRPS_PYMT_ATRB_RDN_LOG.CRE_DT SRC_CRE_DT,
                   PRPS_PYMT_ATRB_RDN_LOG.CRE_USER_NM SRC_CRE_USER_NM,
                   PRPS_PYMT_ATRB_RDN_LOG.LAST_CHG_DT SRC_LAST_CHG_DT,
                   PRPS_PYMT_ATRB_RDN_LOG.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
                   PRPS_PYMT_ATRB_RDN_LOG.PYMT_ATRB_ID PYMT_ATRB_ID,
                   PRPS_PYMT_ATRB_RDN_LOG.PRPS_PYMT_ID PRPS_PYMT_ID,
                   PRPS_PYMT_ATRB_RDN_LOG.ST_FSA_CD ST_FSA_CD,
                   PRPS_PYMT_ATRB_RDN_LOG.CNTY_FSA_CD CNTY_FSA_CD,
                   PRPS_PYMT_ATRB_RDN_LOG.ACCT_PGM_CD ACCT_PGM_CD,
                   PRPS_PYMT_ATRB_RDN_LOG.SBSD_PRD_STRT_YR SBSD_PRD_STRT_YR,
                   PRPS_PYMT_ATRB_RDN_LOG.MBR_CORE_CUST_ID MBR_CORE_CUST_ID,
                   PRPS_PYMT_ATRB_RDN_LOG.PAID_CORE_CUST_ID PAID_CORE_CUST_ID,
                   PRPS_PYMT_ATRB_RDN_LOG.PYMT_ATRB_RDN_TYPE_CD PYMT_ATRB_RDN_TYPE_CD,
                   PRPS_PYMT_ATRB_RDN_LOG.PYMT_ATRB_RDN_AMT PYMT_ATRB_RDN_AMT,
                   PRPS_PYMT_ATRB_RDN_LOG.PRTY_NBR PRTY_NBR,
                   PRPS_PYMT_ATRB_RDN_LOG.PYMT_ATRB_RDN_PCT PYMT_ATRB_RDN_PCT,
                   PRPS_PYMT_ATRB_RDN_LOG.CDC_OPER_CD,
                   MD5 (trim(PRPS_PYMT_ATRB_RDN_LOG.ST_FSA_CD)||'~~'||trim(PRPS_PYMT_ATRB_RDN_LOG.CNTY_FSA_CD)||'~~'||trim(PRPS_PYMT_ATRB_RDN_LOG.ACCT_PGM_CD)||'~~'||PRPS_PYMT_ATRB_RDN_LOG.MBR_CORE_CUST_ID||'~~'||PRPS_PYMT_ATRB_RDN_LOG.PAID_CORE_CUST_ID||'~~'||trim(PRPS_PYMT_ATRB_RDN_LOG.PYMT_ATRB_RDN_TYPE_CD)||'~~'||PRPS_PYMT_ATRB_RDN_LOG.PRPS_PYMT_ATRB_RDN_LOG_ID||'~~'||trim(PRPS_PYMT_ATRB_RDN_LOG.DATA_STAT_CD)||'~~'||to_char(PRPS_PYMT_ATRB_RDN_LOG.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PRPS_PYMT_ATRB_RDN_LOG.CRE_USER_NM)||'~~'||to_char(PRPS_PYMT_ATRB_RDN_LOG.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PRPS_PYMT_ATRB_RDN_LOG.LAST_CHG_USER_NM)||'~~'||PRPS_PYMT_ATRB_RDN_LOG.PYMT_ATRB_ID||'~~'||PRPS_PYMT_ATRB_RDN_LOG.PRPS_PYMT_ID||'~~'||trim(PRPS_PYMT_ATRB_RDN_LOG.ST_FSA_CD)||'~~'||trim(PRPS_PYMT_ATRB_RDN_LOG.CNTY_FSA_CD)||'~~'||trim(PRPS_PYMT_ATRB_RDN_LOG.ACCT_PGM_CD)||'~~'||PRPS_PYMT_ATRB_RDN_LOG.SBSD_PRD_STRT_YR||'~~'||PRPS_PYMT_ATRB_RDN_LOG.MBR_CORE_CUST_ID||'~~'||PRPS_PYMT_ATRB_RDN_LOG.PAID_CORE_CUST_ID||'~~'||trim(PRPS_PYMT_ATRB_RDN_LOG.PYMT_ATRB_RDN_TYPE_CD)||'~~'||PRPS_PYMT_ATRB_RDN_LOG.PYMT_ATRB_RDN_AMT||'~~'||PRPS_PYMT_ATRB_RDN_LOG.PRTY_NBR||'~~'||PRPS_PYMT_ATRB_RDN_LOG.PYMT_ATRB_RDN_PCT) HASH_DIF
   FROM SBSD_STG.PRPS_PYMT_ATRB_RDN_LOG PRPS_PYMT_ATRB_RDN_LOG
   WHERE PRPS_PYMT_ATRB_RDN_LOG.CDC_OPER_CD='D'
     AND date(PRPS_PYMT_ATRB_RDN_LOG.CDC_DT) = date(TO_TIMESTAMP ('{ETL_START_TIMESTAMP}', 'YYYY-MM-DD HH24:MI:SS.FF'))
   ORDER BY PRPS_PYMT_ATRB_RDN_LOG.CDC_DT) stg ON (coalesce(stg.PRPS_PYMT_ATRB_RDN_LOG_ID, 0) = coalesce(dv.PRPS_PYMT_ATRB_RDN_LOG_ID, 0)) 
WHEN MATCHED
	AND dv.LOAD_DT <> stg.LOAD_DT
  AND dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD')
THEN
UPDATE
SET LOAD_END_DT = stg.LOAD_DT,
    DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT