SELECT UOM_NM,
UOM_ID,
UOM_ABR,
UOM_DESC,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM(


SELECT * FROM (SELECT DISTINCT
UNIT_OF_MEASURE.UOM_NM UOM_NM,
UNIT_OF_MEASURE.UOM_ID UOM_ID,
UNIT_OF_MEASURE.UOM_ABR UOM_ABR,
UNIT_OF_MEASURE.UOM_DESC UOM_DESC,
UNIT_OF_MEASURE.DATA_STAT_CD DATA_STAT_CD,
UNIT_OF_MEASURE.CRE_DT CRE_DT,
UNIT_OF_MEASURE.LAST_CHG_DT LAST_CHG_DT,
UNIT_OF_MEASURE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
OP AS CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".UNIT_OF_MEASURE UNIT_OF_MEASURE
WHERE OP <> 'D'
AND UNIT_OF_MEASURE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'


UNION
SELECT DISTINCT
UNIT_OF_MEASURE.UOM_NM UOM_NM,
UNIT_OF_MEASURE.UOM_ID UOM_ID,
UNIT_OF_MEASURE.UOM_ABR UOM_ABR,
UNIT_OF_MEASURE.UOM_DESC UOM_DESC,
UNIT_OF_MEASURE.DATA_STAT_CD DATA_STAT_CD,
UNIT_OF_MEASURE.CRE_DT CRE_DT,
UNIT_OF_MEASURE.LAST_CHG_DT LAST_CHG_DT,
UNIT_OF_MEASURE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".UNIT_OF_MEASURE UNIT_OF_MEASURE
WHERE OP = 'D'
AND dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}' 

)

)