SELECT HRCH_LVL_NM,
ST_FSA_CD,
CNTY_FSA_CD,
SGNP_SUB_CAT_NM,
CNSV_CTR_NBR,
CORE_CUST_ID,
CTR_PRDR_ID,
CTR_NBR,
PGM_HRCH_LVL_ID,
CNSV_CTR_SFX_CD,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM(
SELECT * FROM
(
SELECT DISTINCT HRCH_LVL_NM,
ST_FSA_CD,
CNTY_FSA_CD,
SGNP_SUB_CAT_NM,
CNSV_CTR_NBR,
CORE_CUST_ID,
CTR_PRDR_ID,
CTR_NBR,
PGM_HRCH_LVL_ID,
CNSV_CTR_SFX_CD,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CTR_PRDR_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
contract_producer.st_fsa_cd ST_FSA_CD,
contract_producer.cnty_fsa_cd CNTY_FSA_CD,
(CASE WHEN  PAYMENT_TYPE.APP_CD = 'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME 
WHEN PAYMENT_TYPE.APP_CD IN ('FCRP', 'BCAP' ) THEN ewt14sgnp.SGNP_STYPE_DESC 
END ) SGNP_SUB_CAT_NM,
left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1) CNSV_CTR_NBR,
contract_producer.core_cust_id CORE_CUST_ID,
contract_producer.ctr_prdr_id CTR_PRDR_ID,
contract_producer.ctr_nbr CTR_NBR,
contract_producer.pgm_hrch_lvl_id PGM_HRCH_LVL_ID,
(CASE 
WHEN patindex('%[a-z]%',contract_producer.ctr_nbr) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( contract_producer.ctr_nbr,patindex('%[^0-9]%', contract_producer.ctr_nbr+'.')-1),'')))) > 2
THEN NULL 
ELSE
/* rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),'')))  RA:original code */
rtrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),'')) /* RA:Updated code */
END)  CNSV_CTR_SFX_CD,
contract_producer.data_stat_cd DATA_STAT_CD,
contract_producer.cre_dt CRE_DT,
contract_producer.last_chg_dt LAST_CHG_DT,
contract_producer.last_chg_user_nm LAST_CHG_USER_NM,
CONTRACT_PRODUCER.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."CONTRACT_PRODUCER" CONTRACT_PRODUCER
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (CONTRACT_PRODUCER.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN  
(SELECT /* CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),LTRIM(RTRIM(CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT,  RA:Original code */  
LTRIM(RTRIM(CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT, /* RA:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER, 
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE, 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE  
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER) 
) AS TEMP 
ON ( TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = CONTRACT_PRODUCER.CNTY_FSA_CD 
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = CONTRACT_PRODUCER.ST_FSA_CD 
/* AND TEMP.CAT = REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','') RA:Original code */
AND TEMP.CAT = LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)) /* RA:Updated code */
) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP  
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP_SUB_CATEGORY" SIGNUP_SUB_CATEGORY 
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE) 
LEFT JOIN ( SELECT * FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC WHERE CNSV_CTR_SEQ_NBR > 0 ) EWT40OFRSC
ON ( CONTRACT_PRODUCER.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND CONTRACT_PRODUCER.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD 
/* AND REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','') = CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),LTRIM(RTRIM(EWT40OFRSC.CNSV_CTR_SUFX_CD))) RA:Original code */
AND LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)) = LTRIM(RTRIM(CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),EWT40OFRSC.CNSV_CTR_SUFX_CD))) /* RA:Updated code */
) 
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP 
ON ( EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE 
ON ( PAYMENT_TYPE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND EWT14SGNP.OP <> 'D'
UNION
SELECT 
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
contract_producer.st_fsa_cd ST_FSA_CD,
contract_producer.cnty_fsa_cd CNTY_FSA_CD,
(CASE WHEN  PAYMENT_TYPE.APP_CD = 'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME 
WHEN PAYMENT_TYPE.APP_CD IN ('FCRP', 'BCAP' ) THEN ewt14sgnp.SGNP_STYPE_DESC 
END ) SGNP_SUB_CAT_NM,
left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1)  CNSV_CTR_NBR,
contract_producer.core_cust_id CORE_CUST_ID,
contract_producer.ctr_prdr_id CTR_PRDR_ID,
contract_producer.ctr_nbr CTR_NBR,
contract_producer.pgm_hrch_lvl_id PGM_HRCH_LVL_ID,
(CASE 
WHEN patindex('%[a-z]%',contract_producer.ctr_nbr) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( contract_producer.ctr_nbr,patindex('%[^0-9]%', contract_producer.ctr_nbr+'.')-1),'')))) > 2
THEN NULL 
ELSE
/* rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))) RA:Original code */
rtrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),'')) /* RA:Updated code */
END)  CNSV_CTR_SFX_CD,
contract_producer.data_stat_cd DATA_STAT_CD,
contract_producer.cre_dt CRE_DT,
contract_producer.last_chg_dt LAST_CHG_DT,
contract_producer.last_chg_user_nm LAST_CHG_USER_NM,
PROGRAM_HIERARCHY_LEVEL.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL
JOIN "fsa-{env}-cnsv"."CONTRACT_PRODUCER" CONTRACT_PRODUCER  
ON (CONTRACT_PRODUCER.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN  
(SELECT /* CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),LTRIM(RTRIM(CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT, RA:Original code */
LTRIM(RTRIM(CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT, /* RA:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER, 
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE, 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE  
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL 
ON (CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER) 
) AS TEMP 
ON ( TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = CONTRACT_PRODUCER.CNTY_FSA_CD 
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = CONTRACT_PRODUCER.ST_FSA_CD 
/* AND TEMP.CAT = REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ',''))  RA:Original code */
AND TEMP.CAT = LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR))) /* RA:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP  
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP_SUB_CATEGORY" SIGNUP_SUB_CATEGORY 
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE) 
LEFT JOIN ( SELECT * FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC WHERE CNSV_CTR_SEQ_NBR > 0 ) EWT40OFRSC
ON ( CONTRACT_PRODUCER.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND CONTRACT_PRODUCER.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD 
/* AND REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','') = CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),LTRIM(RTRIM(EWT40OFRSC.CNSV_CTR_SUFX_CD))) RA:Original code */ 
AND LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)) = LTRIM(RTRIM(CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),EWT40OFRSC.CNSV_CTR_SUFX_CD))) /* RA:Updated code */
) 
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP 
ON ( EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE 
ON ( PAYMENT_TYPE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)
WHERE PAYMENT_TYPE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND PAYMENT_TYPE.OP <> 'D'
UNION
SELECT 
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
contract_producer.st_fsa_cd ST_FSA_CD,
contract_producer.cnty_fsa_cd CNTY_FSA_CD,
(CASE WHEN  PAYMENT_TYPE.APP_CD = 'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME 
WHEN PAYMENT_TYPE.APP_CD IN ('FCRP', 'BCAP' ) THEN ewt14sgnp.SGNP_STYPE_DESC 
END ) SGNP_SUB_CAT_NM,
left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1)  CNSV_CTR_NBR,
contract_producer.core_cust_id CORE_CUST_ID,
contract_producer.ctr_prdr_id CTR_PRDR_ID,
contract_producer.ctr_nbr CTR_NBR,
contract_producer.pgm_hrch_lvl_id PGM_HRCH_LVL_ID,
(CASE 
WHEN patindex('%[a-z]%',contract_producer.ctr_nbr) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( contract_producer.ctr_nbr,patindex('%[^0-9]%', contract_producer.ctr_nbr+'.')-1),'')))) > 2
THEN NULL 
ELSE
/* rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))) RA:Original code */
rtrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))  /* RA:Updated code */
END)  CNSV_CTR_SFX_CD,
contract_producer.data_stat_cd DATA_STAT_CD,
contract_producer.cre_dt CRE_DT,
contract_producer.last_chg_dt LAST_CHG_DT,
contract_producer.last_chg_user_nm LAST_CHG_USER_NM,
MASTER_CONTRACT.OP,
3 AS TBL_PRIORITY
FROM 
(SELECT /* CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),LTRIM(RTRIM(CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT,  RA:Original code */
LTRIM(RTRIM(CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT,  /* RA:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER, 
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE, 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ,
supplemental_contract_type_abbreviation.OP  
FROM (Select * from "fsa-{env}-cnsv-cdc"."supplemental_contract_type_abbreviation" supplemental_contract_type_abbreviation where supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER) 
) AS TEMP 
JOIN  
"fsa-{env}-cnsv"."CONTRACT_PRODUCER" CONTRACT_PRODUCER 
ON ( TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = CONTRACT_PRODUCER.CNTY_FSA_CD 
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = CONTRACT_PRODUCER.ST_FSA_CD 
/* AND TEMP.CAT = REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ',''))  RA:Original code */
AND TEMP.CAT = LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)))  /* RA:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (CONTRACT_PRODUCER.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP  
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP_SUB_CATEGORY" SIGNUP_SUB_CATEGORY 
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE) 
LEFT JOIN ( SELECT * FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC WHERE CNSV_CTR_SEQ_NBR > 0 ) EWT40OFRSC
ON ( CONTRACT_PRODUCER.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND CONTRACT_PRODUCER.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD 
/* AND REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','') = CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),LTRIM(RTRIM(EWT40OFRSC.CNSV_CTR_SUFX_CD)))  RA:Original code */ 
AND LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)) = LTRIM(RTRIM(CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),EWT40OFRSC.CNSV_CTR_SUFX_CD)))  /* RA:Updated code */
) 
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP 
ON ( EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE 
ON ( PAYMENT_TYPE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)
WHERE PAYMENT_TYPE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND PAYMENT_TYPE.OP <> 'D'
UNION
SELECT 
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
contract_producer.st_fsa_cd ST_FSA_CD,
contract_producer.cnty_fsa_cd CNTY_FSA_CD,
(CASE WHEN  PAYMENT_TYPE.APP_CD = 'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME 
WHEN PAYMENT_TYPE.APP_CD IN ('FCRP', 'BCAP' ) THEN ewt14sgnp.SGNP_STYPE_DESC 
END ) SGNP_SUB_CAT_NM,
left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1)  CNSV_CTR_NBR,
contract_producer.core_cust_id CORE_CUST_ID,
contract_producer.ctr_prdr_id CTR_PRDR_ID,
contract_producer.ctr_nbr CTR_NBR,
contract_producer.pgm_hrch_lvl_id PGM_HRCH_LVL_ID,
(CASE 
WHEN patindex('%[a-z]%',contract_producer.ctr_nbr) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( contract_producer.ctr_nbr,patindex('%[^0-9]%', contract_producer.ctr_nbr+'.')-1),'')))) > 2
THEN NULL 
ELSE
/* rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))) RA:Original code */
rtrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))  /* RA:Updated code */
END)  CNSV_CTR_SFX_CD,
contract_producer.data_stat_cd DATA_STAT_CD,
contract_producer.cre_dt CRE_DT,
contract_producer.last_chg_dt LAST_CHG_DT,
contract_producer.last_chg_user_nm LAST_CHG_USER_NM,
MASTER_CONTRACT.OP,
4 AS TBL_PRIORITY
FROM 
(SELECT /* CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),LTRIM(RTRIM(CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT, RA:Original code */
LTRIM(RTRIM(CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT, /* RA:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER, 
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE, 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE  ,
CONTRACT_DETAIL.OP 
FROM "fsa-{env}-cnsv-cdc"."CONTRACT_DETAIL" CONTRACT_DETAIL
LEFT JOIN ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
ON (CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER) 
) AS TEMP 
JOIN  
"fsa-{env}-cnsv"."CONTRACT_PRODUCER" CONTRACT_PRODUCER 
ON ( TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = CONTRACT_PRODUCER.CNTY_FSA_CD 
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = CONTRACT_PRODUCER.ST_FSA_CD 
/* AND TEMP.CAT = REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','')) RA:Original code */
AND TEMP.CAT = LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)))  /* RA:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (CONTRACT_PRODUCER.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP  
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP_SUB_CATEGORY" SIGNUP_SUB_CATEGORY 
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE) 
LEFT JOIN ( SELECT * FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC WHERE CNSV_CTR_SEQ_NBR > 0 ) EWT40OFRSC
ON ( CONTRACT_PRODUCER.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND CONTRACT_PRODUCER.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD 
/* AND REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','') = CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),LTRIM(RTRIM(EWT40OFRSC.CNSV_CTR_SUFX_CD))) RA:Original code */ 
AND LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)) = LTRIM(RTRIM(CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),EWT40OFRSC.CNSV_CTR_SUFX_CD)))  /* RA:Updated code */
) 
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP 
ON ( EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE 
ON ( PAYMENT_TYPE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)
WHERE PROGRAM_HIERARCHY_LEVEL.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND PROGRAM_HIERARCHY_LEVEL.OP <> 'D'
UNION
SELECT 
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
contract_producer.st_fsa_cd ST_FSA_CD,
contract_producer.cnty_fsa_cd CNTY_FSA_CD,
(CASE WHEN  PAYMENT_TYPE.APP_CD = 'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME 
WHEN PAYMENT_TYPE.APP_CD IN ('FCRP', 'BCAP' ) THEN ewt14sgnp.SGNP_STYPE_DESC 
END ) SGNP_SUB_CAT_NM,
left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1)  CNSV_CTR_NBR,
contract_producer.core_cust_id CORE_CUST_ID,
contract_producer.ctr_prdr_id CTR_PRDR_ID,
contract_producer.ctr_nbr CTR_NBR,
contract_producer.pgm_hrch_lvl_id PGM_HRCH_LVL_ID,
(CASE 
WHEN patindex('%[a-z]%',contract_producer.ctr_nbr) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( contract_producer.ctr_nbr,patindex('%[^0-9]%', contract_producer.ctr_nbr+'.')-1),'')))) > 2
THEN NULL 
ELSE
/* rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))) RA:Original code */
rtrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))  /* RA:Updated code */
END)  CNSV_CTR_SFX_CD,
contract_producer.data_stat_cd DATA_STAT_CD,
contract_producer.cre_dt CRE_DT,
contract_producer.last_chg_dt LAST_CHG_DT,
contract_producer.last_chg_user_nm LAST_CHG_USER_NM,
SIGNUP.OP,
5 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."SIGNUP" SIGNUP
 LEFT JOIN (SELECT /* CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),LTRIM(RTRIM(CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT, RA:Original code */ 
 LTRIM(RTRIM(CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT, /* RA:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER, 
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE, 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE  
FROM ( Select * from  "fsa-{env}-cnsv-cdc"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER) 
) AS TEMP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER) 
JOIN "fsa-{env}-cnsv"."CONTRACT_PRODUCER" CONTRACT_PRODUCER 
ON ( TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = CONTRACT_PRODUCER.CNTY_FSA_CD 
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = CONTRACT_PRODUCER.ST_FSA_CD 
/* AND TEMP.CAT = REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','')) RA:Original code  */
AND TEMP.CAT = LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR))) /* RA:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (CONTRACT_PRODUCER.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
 LEFT JOIN "fsa-{env}-cnsv"."SIGNUP_SUB_CATEGORY" SIGNUP_SUB_CATEGORY 
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE) 
LEFT JOIN ( SELECT * FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC WHERE CNSV_CTR_SEQ_NBR > 0 ) EWT40OFRSC
ON ( CONTRACT_PRODUCER.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND CONTRACT_PRODUCER.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD 
/* AND REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','') = CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),LTRIM(RTRIM(EWT40OFRSC.CNSV_CTR_SUFX_CD))) RA:Original code */ 
AND LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)) = LTRIM(RTRIM(CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),EWT40OFRSC.CNSV_CTR_SUFX_CD)))  /* RA:Updated code */
) 
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP 
ON ( EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE 
ON ( PAYMENT_TYPE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)
WHERE PAYMENT_TYPE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND PAYMENT_TYPE.OP <> 'D'
UNION
SELECT 
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
contract_producer.st_fsa_cd ST_FSA_CD,
contract_producer.cnty_fsa_cd CNTY_FSA_CD,
(CASE WHEN  PAYMENT_TYPE.APP_CD = 'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME 
WHEN PAYMENT_TYPE.APP_CD IN ('FCRP', 'BCAP' ) THEN ewt14sgnp.SGNP_STYPE_DESC 
END ) SGNP_SUB_CAT_NM,
left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1)  CNSV_CTR_NBR,
contract_producer.core_cust_id CORE_CUST_ID,
contract_producer.ctr_prdr_id CTR_PRDR_ID,
contract_producer.ctr_nbr CTR_NBR,
contract_producer.pgm_hrch_lvl_id PGM_HRCH_LVL_ID,
(CASE 
WHEN patindex('%[a-z]%',contract_producer.ctr_nbr) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( contract_producer.ctr_nbr,patindex('%[^0-9]%', contract_producer.ctr_nbr+'.')-1),'')))) > 2
THEN NULL 
ELSE
/* rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),'')))  RA:Original code */
rtrim( REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))  /* RA:Updated code */
END)  CNSV_CTR_SFX_CD,
contract_producer.data_stat_cd DATA_STAT_CD,
contract_producer.cre_dt CRE_DT,
contract_producer.last_chg_dt LAST_CHG_DT,
contract_producer.last_chg_user_nm LAST_CHG_USER_NM,
SIGNUP_SUB_CATEGORY.OP,
6 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."SIGNUP_SUB_CATEGORY" SIGNUP_SUB_CATEGORY
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP  
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)  
LEFT JOIN  
(SELECT /* CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),LTRIM(RTRIM(CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT, RA:Original code */ 
LTRIM(RTRIM(CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT,  /* RA:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER, 
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE, 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE  
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER) 
) AS TEMP  
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
JOIN "fsa-{env}-cnsv"."CONTRACT_PRODUCER" CONTRACT_PRODUCER 
ON ( TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = CONTRACT_PRODUCER.CNTY_FSA_CD 
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = CONTRACT_PRODUCER.ST_FSA_CD 
/* AND TEMP.CAT = REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','')) RA:Original code */
AND TEMP.CAT = LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR))) /* RA:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (CONTRACT_PRODUCER.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN ( SELECT * FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC WHERE CNSV_CTR_SEQ_NBR > 0 ) EWT40OFRSC 
ON ( CONTRACT_PRODUCER.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND CONTRACT_PRODUCER.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD 
/* AND REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','') = CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),LTRIM(RTRIM(EWT40OFRSC.CNSV_CTR_SUFX_CD)))  RA:Original code */ 
AND LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)) = LTRIM(RTRIM(CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),EWT40OFRSC.CNSV_CTR_SUFX_CD)))  /* RA:Updated code */
) 
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP 
ON ( EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE 
ON ( PAYMENT_TYPE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)
WHERE PROGRAM_HIERARCHY_LEVEL.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND PROGRAM_HIERARCHY_LEVEL.OP <> 'D'
UNION
SELECT 
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
contract_producer.st_fsa_cd ST_FSA_CD,
contract_producer.cnty_fsa_cd CNTY_FSA_CD,
(CASE WHEN  PAYMENT_TYPE.APP_CD = 'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME 
WHEN PAYMENT_TYPE.APP_CD IN ('FCRP', 'BCAP' ) THEN ewt14sgnp.SGNP_STYPE_DESC 
END ) SGNP_SUB_CAT_NM,
left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1)  CNSV_CTR_NBR,
contract_producer.core_cust_id CORE_CUST_ID,
contract_producer.ctr_prdr_id CTR_PRDR_ID,
contract_producer.ctr_nbr CTR_NBR,
contract_producer.pgm_hrch_lvl_id PGM_HRCH_LVL_ID,
(CASE 
WHEN patindex('%[a-z]%',contract_producer.ctr_nbr) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( contract_producer.ctr_nbr,patindex('%[^0-9]%', contract_producer.ctr_nbr+'.')-1),'')))) > 2
THEN NULL 
ELSE
/* rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))) RA:Original code */
rtrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))  /* RA:Updated code  */
END)  CNSV_CTR_SFX_CD,
contract_producer.data_stat_cd DATA_STAT_CD,
contract_producer.cre_dt CRE_DT,
contract_producer.last_chg_dt LAST_CHG_DT,
contract_producer.last_chg_user_nm LAST_CHG_USER_NM,
CNSV_CTR_SEQ_NBR.OP,
7 AS TBL_PRIORITY
FROM  ( SELECT * FROM "fsa-{env}-cnsv-cdc"."CNSV_CTR_SEQ_NBR" CNSV_CTR_SEQ_NBR WHERE CNSV_CTR_SEQ_NBR > 0 ) EWT40OFRSC    
JOIN "fsa-{env}-cnsv"."CONTRACT_PRODUCER" CONTRACT_PRODUCER 
ON ( CONTRACT_PRODUCER.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND CONTRACT_PRODUCER.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD 
/* AND REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','') = CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),LTRIM(RTRIM(EWT40OFRSC.CNSV_CTR_SUFX_CD)))  RA:Original code */ 
AND LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)) = LTRIM(RTRIM(CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),EWT40OFRSC.CNSV_CTR_SUFX_CD)))  /* RA:Updated code */
) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (CONTRACT_PRODUCER.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN  
(SELECT /* CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),LTRIM(RTRIM(CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT,  RA:Original code */
LTRIM(RTRIM(CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT, /* RA:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER, 
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE, 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE  
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT 
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER) 
) AS TEMP 
ON ( TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = CONTRACT_PRODUCER.CNTY_FSA_CD 
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = CONTRACT_PRODUCER.ST_FSA_CD 
/* AND TEMP.CAT = REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ',''))  RA:Original code */
AND TEMP.CAT = LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)))  /* RA:Updated code  */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP  
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP_SUB_CATEGORY" SIGNUP_SUB_CATEGORY 
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE) 
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP 
ON ( EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE 
ON ( PAYMENT_TYPE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)
WHERE PAYMENT_TYPE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND PAYMENT_TYPE.OP <> 'D'
UNION
SELECT 
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
contract_producer.st_fsa_cd ST_FSA_CD,
contract_producer.cnty_fsa_cd CNTY_FSA_CD,
(CASE WHEN  PAYMENT_TYPE.APP_CD = 'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME 
WHEN PAYMENT_TYPE.APP_CD IN ('FCRP', 'BCAP' ) THEN ewt14sgnp.SGNP_STYPE_DESC 
END ) SGNP_SUB_CAT_NM,
left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1)  CNSV_CTR_NBR,
contract_producer.core_cust_id CORE_CUST_ID,
contract_producer.ctr_prdr_id CTR_PRDR_ID,
contract_producer.ctr_nbr CTR_NBR,
contract_producer.pgm_hrch_lvl_id PGM_HRCH_LVL_ID,
(CASE 
WHEN patindex('%[a-z]%',contract_producer.ctr_nbr) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( contract_producer.ctr_nbr,patindex('%[^0-9]%', contract_producer.ctr_nbr+'.')-1),'')))) > 2
THEN NULL 
ELSE
/* rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),'')))  RA:Original code */
rtrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))   /* RA:Updated code  */
END)  CNSV_CTR_SFX_CD,
contract_producer.data_stat_cd DATA_STAT_CD,
contract_producer.cre_dt CRE_DT,
contract_producer.last_chg_dt LAST_CHG_DT,
contract_producer.last_chg_user_nm LAST_CHG_USER_NM,
EWT14SGNP.OP,
8 AS TBL_PRIORITY
FROM  "fsa-{env}-cnsv-cdc"."EWT14SGNP" EWT14SGNP
LEFT JOIN ( SELECT * FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC WHERE CNSV_CTR_SEQ_NBR > 0 ) EWT40OFRSC 
ON ( EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
JOIN "fsa-{env}-cnsv"."CONTRACT_PRODUCER" CONTRACT_PRODUCER 
ON ( CONTRACT_PRODUCER.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND CONTRACT_PRODUCER.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD 
/* AND REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','') = CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),LTRIM(RTRIM(EWT40OFRSC.CNSV_CTR_SUFX_CD)))  RA:Original code */
AND LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)) = LTRIM(RTRIM(CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),EWT40OFRSC.CNSV_CTR_SUFX_CD)))  /* RA:Updated code  */
) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (CONTRACT_PRODUCER.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN  
(SELECT /* CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),LTRIM(RTRIM(CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT,  RA:Original code */
LTRIM(RTRIM(CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT, /* RA:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER, 
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE, 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE  
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER) 
) AS TEMP 
ON ( TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = CONTRACT_PRODUCER.CNTY_FSA_CD 
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = CONTRACT_PRODUCER.ST_FSA_CD 
/* AND TEMP.CAT = REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ',''))   RA:Original code */
AND TEMP.CAT = LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)))  /* RA:Updated code  */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP  
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP_SUB_CATEGORY" SIGNUP_SUB_CATEGORY 
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE 
ON ( PAYMENT_TYPE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)
WHERE PROGRAM_HIERARCHY_LEVEL.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND PROGRAM_HIERARCHY_LEVEL.OP <> 'D'
UNION
SELECT 
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
contract_producer.st_fsa_cd ST_FSA_CD,
contract_producer.cnty_fsa_cd CNTY_FSA_CD,
(CASE WHEN  PAYMENT_TYPE.APP_CD = 'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME 
WHEN PAYMENT_TYPE.APP_CD IN ('FCRP', 'BCAP' ) THEN ewt14sgnp.SGNP_STYPE_DESC 
END ) SGNP_SUB_CAT_NM,
left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1)  CNSV_CTR_NBR,
contract_producer.core_cust_id CORE_CUST_ID,
contract_producer.ctr_prdr_id CTR_PRDR_ID,
contract_producer.ctr_nbr CTR_NBR,
contract_producer.pgm_hrch_lvl_id PGM_HRCH_LVL_ID,
(CASE 
WHEN patindex('%[a-z]%',contract_producer.ctr_nbr) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( contract_producer.ctr_nbr,patindex('%[^0-9]%', contract_producer.ctr_nbr+'.')-1),'')))) > 2
THEN NULL 
ELSE
/* rtrim(ltrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),'')))  RA:Original code */
rtrim(REPLACE ( contract_producer.ctr_nbr,left( CONTRACT_PRODUCER.ctr_nbr,patindex('%[^0-9]%', CONTRACT_PRODUCER.ctr_nbr+'.')-1),''))   /* RA:Updated code */
END)  CNSV_CTR_SFX_CD,
contract_producer.data_stat_cd DATA_STAT_CD,
contract_producer.cre_dt CRE_DT,
contract_producer.last_chg_dt LAST_CHG_DT,
contract_producer.last_chg_user_nm LAST_CHG_USER_NM,
PAYMENT_TYPE.OP,
9 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PAYMENT_TYPE"
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL 
ON ( PAYMENT_TYPE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)
JOIN "fsa-{env}-cnsv"."CONTRACT_PRODUCER" CONTRACT_PRODUCER 
ON (CONTRACT_PRODUCER.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN  
(SELECT /* CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),LTRIM(RTRIM(CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT,  RA:Original code */ 
LTRIM(RTRIM(CONCAT(CAST(MASTER_CONTRACT.CONTRACT_NUMBER AS VARCHAR),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) AS CAT,  /* RA:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER, 
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE, 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE  
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT 
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER) 
) AS TEMP 
ON ( TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = CONTRACT_PRODUCER.CNTY_FSA_CD 
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = CONTRACT_PRODUCER.ST_FSA_CD 
/* AND TEMP.CAT = REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ',''))  RA:Original code  */
AND TEMP.CAT = LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)))  /* RA:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP  
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP_SUB_CATEGORY" SIGNUP_SUB_CATEGORY 
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE) 
LEFT JOIN ( SELECT * FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC WHERE CNSV_CTR_SEQ_NBR > 0 ) EWT40OFRSC 
ON ( CONTRACT_PRODUCER.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND CONTRACT_PRODUCER.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD 
/* AND REPLACE(CONTRACT_PRODUCER.CTR_NBR,' ','') = CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),LTRIM(RTRIM(EWT40OFRSC.CNSV_CTR_SUFX_CD)))  RA:Original code */ 
AND LTRIM(RTRIM(CONTRACT_PRODUCER.CTR_NBR)) = LTRIM(RTRIM(CONCAT(CAST(EWT40OFRSC.CNSV_CTR_SEQ_NBR AS VARCHAR),EWT40OFRSC.CNSV_CTR_SUFX_CD)))  /* RA:Updated code */
) 
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP 
ON ( EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
WHERE EWT40OFRSC.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND EWT40OFRSC.OP <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
NULL HRCH_LVL_NM,
contract_producer.st_fsa_cd ST_FSA_CD,
contract_producer.cnty_fsa_cd CNTY_FSA_CD,
NULL SGNP_SUB_CAT_NM,
NULL CNSV_CTR_NBR,
contract_producer.core_cust_id CORE_CUST_ID,
contract_producer.ctr_prdr_id CTR_PRDR_ID,
contract_producer.ctr_nbr CTR_NBR,
contract_producer.pgm_hrch_lvl_id PGM_HRCH_LVL_ID,
NULL CNSV_CTR_SFX_CD,
contract_producer.data_stat_cd DATA_STAT_CD,
contract_producer.cre_dt CRE_DT,
contract_producer.last_chg_dt LAST_CHG_DT,
contract_producer.last_chg_user_nm LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc"."CONTRACT_PRODUCER" CONTRACT_PRODUCER
WHERE contract_producer.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND contract_producer.OP = 'D')