select
	cre_dt,
	last_chg_dt,
	data_stat_cd,
	pgm_yr,
	adm_fsa_st_cnty_srgt_id,
	adm_fsa_st_cnty_durb_id,
	prnt_tr_srgt_id,
	prnt_tr_durb_id,
	rslt_tr_srgt_id,
	rslt_tr_durb_id,
	rcon_type_srgt_id,
	rcon_type_durb_id,
	rcon_apvl_dt,
	rcon_eff_dt,
	rcon_init_dt,
	tr_rcon_cre_dt,
	tr_rcon_cre_user_nm,
	tr_rcon_last_chg_dt,
	tr_rcon_last_chg_user_nm,
	src_data_stat_cd,
	rcon_seq_nbr
from
	farm_dm_stg.tr_rcon_fact;