INSERT   into
EDV.TR_YR_DCP_LS(FARM_TR_L_ID,TR_YR_DCP_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
TR_YR_ID,
DCP_DBL_CROP_ACRG,
DCP_CPLD_ACRG,
DCP_AFT_RDN_ACRG,
FAV_WR_HIST_IND,
PGM_YR, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(SELECT stg.* from (SELECT /*+ parallel (TR_YR_DCP, 8) */ DISTINCT 
MD5(MD5(upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.FARM_NBR ,'--')))||'~~'||MD5(upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.TR_NBR, '-1')))) FARM_TR_L_ID,
TR_YR_DCP.TR_YR_DCP_ID TR_YR_DCP_ID,TR_YR_DCP.LOAD_DT LOAD_DT,TR_YR_DCP.CDC_DT DATA_EFF_STRT_DT,TR_YR_DCP.DATA_SRC_NM DATA_SRC_NM,TR_YR_DCP.DATA_STAT_CD DATA_STAT_CD,TR_YR_DCP.CRE_DT SRC_CRE_DT,TR_YR_DCP.LAST_CHG_DT SRC_LAST_CHG_DT,TR_YR_DCP.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_YR_DCP.TR_YR_ID TR_YR_ID,TR_YR_DCP.DCP_DBL_CROP_ACRG DCP_DBL_CROP_ACRG,TR_YR_DCP.DCP_CPLD_ACRG DCP_CPLD_ACRG,TR_YR_DCP.DCP_AFT_RDN_ACRG DCP_AFT_RDN_ACRG,TR_YR_DCP.FAV_WR_HIST_IND FAV_WR_HIST_IND,TR_YR_DCP.PGM_YR PGM_YR ,
to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.FARM_NBR ,'--'))||'~~'||upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.TR_NBR, '-1'))||'~~'||TR_YR_DCP.TR_YR_DCP_ID||'~~'||trim(both TR_YR_DCP.DATA_STAT_CD)||'~~'||to_char(TR_YR_DCP.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TR_YR_DCP.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_YR_DCP.LAST_CHG_USER_NM)||'~~'||TR_YR_DCP.TR_YR_ID||'~~'||TR_YR_DCP.DCP_DBL_CROP_ACRG||'~~'||TR_YR_DCP.DCP_CPLD_ACRG||'~~'||TR_YR_DCP.DCP_AFT_RDN_ACRG||'~~'||trim(both TR_YR_DCP.FAV_WR_HIST_IND)||'~~'||TR_YR_DCP.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.TR_YR_DCP  TR_YR_DCP
 where TR_YR_DCP.CDC_OPER_CD IN ('I','UN')
AND MD5(MD5(upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.FARM_NBR ,'--')))||'~~'||MD5(upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.TR_NBR, '-1'))))
IN (SELECT FARM_TR_L_ID from EDV.FARM_TR_L )

UNION

 
SELECT /*+ parallel (TR_YR_DCP, 8) */ DISTINCT 
MD5('-1') FARM_TR_L_ID,
TR_YR_DCP.TR_YR_DCP_ID TR_YR_DCP_ID,TR_YR_DCP.LOAD_DT LOAD_DT,TR_YR_DCP.CDC_DT DATA_EFF_STRT_DT,TR_YR_DCP.DATA_SRC_NM DATA_SRC_NM,TR_YR_DCP.DATA_STAT_CD DATA_STAT_CD,TR_YR_DCP.CRE_DT SRC_CRE_DT,TR_YR_DCP.LAST_CHG_DT SRC_LAST_CHG_DT,TR_YR_DCP.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_YR_DCP.TR_YR_ID TR_YR_ID,TR_YR_DCP.DCP_DBL_CROP_ACRG DCP_DBL_CROP_ACRG,TR_YR_DCP.DCP_CPLD_ACRG DCP_CPLD_ACRG,TR_YR_DCP.DCP_AFT_RDN_ACRG DCP_AFT_RDN_ACRG,TR_YR_DCP.FAV_WR_HIST_IND FAV_WR_HIST_IND,TR_YR_DCP.PGM_YR PGM_YR ,
to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.FARM_NBR ,'--'))||'~~'||upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.TR_NBR, '-1'))||'~~'||TR_YR_DCP.TR_YR_DCP_ID||'~~'||trim(both TR_YR_DCP.DATA_STAT_CD)||'~~'||to_char(TR_YR_DCP.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TR_YR_DCP.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_YR_DCP.LAST_CHG_USER_NM)||'~~'||TR_YR_DCP.TR_YR_ID||'~~'||TR_YR_DCP.DCP_DBL_CROP_ACRG||'~~'||TR_YR_DCP.DCP_CPLD_ACRG||'~~'||TR_YR_DCP.DCP_AFT_RDN_ACRG||'~~'||trim(both TR_YR_DCP.FAV_WR_HIST_IND)||'~~'||TR_YR_DCP.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.TR_YR_DCP  TR_YR_DCP
 where TR_YR_DCP.CDC_OPER_CD IN ('I','UN')
AND MD5(MD5(upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.FARM_NBR ,'--')))||'~~'||MD5(upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.TR_NBR, '-1'))))
NOT IN (SELECT FARM_TR_L_ID from EDV.FARM_TR_L )
) stg
 LEFT JOIN  EDV.TR_YR_DCP_LS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.TR_YR_DCP_LS ls
				where stg.FARM_TR_L_ID = ls.FARM_TR_L_ID
				and stg.TR_YR_DCP_ID = ls.TR_YR_DCP_ID
				and stg.LOAD_DT = ls.LOAD_DT
               )
)
;


