Merge into
EDV.TR_YR_DCP_LS dv
using(select DISTINCT 
MD5(MD5(upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.FARM_NBR ,'--')))||'~~'||MD5(upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce((TR_YR_DCP.TR_NBR)::numeric  ,-1)))) FARM_TR_L_ID,
TR_YR_DCP.TR_YR_DCP_ID TR_YR_DCP_ID,TR_YR_DCP.LOAD_DT LOAD_DT,TR_YR_DCP.CDC_DT DATA_EFF_STRT_DT,TR_YR_DCP.DATA_SRC_NM DATA_SRC_NM,TR_YR_DCP.DATA_STAT_CD DATA_STAT_CD,TR_YR_DCP.CRE_DT SRC_CRE_DT,TR_YR_DCP.LAST_CHG_DT SRC_LAST_CHG_DT,TR_YR_DCP.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_YR_DCP.TR_YR_ID TR_YR_ID,TR_YR_DCP.DCP_DBL_CROP_ACRG DCP_DBL_CROP_ACRG,TR_YR_DCP.DCP_CPLD_ACRG DCP_CPLD_ACRG,TR_YR_DCP.DCP_AFT_RDN_ACRG DCP_AFT_RDN_ACRG,TR_YR_DCP.FAV_WR_HIST_IND FAV_WR_HIST_IND,TR_YR_DCP.PGM_YR PGM_YR ,
TR_YR_DCP.CDC_OPER_CD,
MD5(upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_DCP.FARM_NBR ,'--'))||'~~'||upper(coalesce(TR_YR_DCP.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce((TR_YR_DCP.TR_NBR)::numeric  ,-1))||'~~'||TR_YR_DCP.TR_YR_DCP_ID||'~~'||trim(both TR_YR_DCP.DATA_STAT_CD)||'~~'||to_char(TR_YR_DCP.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TR_YR_DCP.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_YR_DCP.LAST_CHG_USER_NM)||'~~'||TR_YR_DCP.TR_YR_ID||'~~'||TR_YR_DCP.DCP_DBL_CROP_ACRG||'~~'||TR_YR_DCP.DCP_CPLD_ACRG||'~~'||TR_YR_DCP.DCP_AFT_RDN_ACRG||'~~'||trim(both TR_YR_DCP.FAV_WR_HIST_IND)||'~~'||TR_YR_DCP.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.TR_YR_DCP  TR_YR_DCP
 where TR_YR_DCP.CDC_OPER_CD='D'
--and date_trunc('day', TR_YR_DCP.CDC_DT) = date_trunc('day', TO_TIMESTAMP('<DATA_EFF_STRT_DT>', 'YYYY-MM-DD HH24:MI:SS.FF'))
--and TR_YR_DCP.LOAD_DT = TO_TIMESTAMP('<LOAD_DT>', 'YYYY-MM-DD HH24:MI:SS.FF')
order by TR_YR_DCP.CDC_DT)
stg
 on ( 
coalesce(stg.TR_YR_DCP_ID,0) = coalesce(dv.TR_YR_DCP_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN
INSERT(
FARM_TR_L_ID,TR_YR_DCP_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
TR_YR_ID,
DCP_DBL_CROP_ACRG,
DCP_CPLD_ACRG,
DCP_AFT_RDN_ACRG,
FAV_WR_HIST_IND,
PGM_YR, 
DATA_EFF_END_DT,LOAD_END_DT,HASH_DIF)
VALUES (
stg.FARM_TR_L_ID,stg.TR_YR_DCP_ID,stg.LOAD_DT,stg.DATA_EFF_STRT_DT,stg.DATA_SRC_NM,stg.DATA_STAT_CD,stg.SRC_CRE_DT,stg.SRC_LAST_CHG_DT,stg.SRC_LAST_CHG_USER_NM,stg.TR_YR_ID,stg.DCP_DBL_CROP_ACRG,stg.DCP_CPLD_ACRG,stg.DCP_AFT_RDN_ACRG,stg.FAV_WR_HIST_IND,stg.PGM_YR,stg.DATA_EFF_STRT_DT,stg.LOAD_DT,
stg.HASH_DIF
)
;