MERGE into
EDV.RCON_RS dv
 using( select distinct
coalesce(RCON.ST_FSA_CD, '--') ST_FSA_CD,
coalesce(RCON.CNTY_FSA_CD, '--') CNTY_FSA_CD,
coalesce(RCON.RCON_ID, '-1') RCON_ID,
RCON.LOAD_DT LOAD_DT,
RCON.CDC_DT DATA_EFF_STRT_DT,
RCON.DATA_SRC_NM DATA_SRC_NM,
RCON.DATA_STAT_CD DATA_STAT_CD,
RCON.CRE_DT SRC_CRE_DT,
RCON.LAST_CHG_DT SRC_LAST_CHG_DT,
RCON.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
RCON.CNTY_OFC_CTL_ID CNTY_OFC_CTL_ID,
RCON.TM_PRD_ID TM_PRD_ID,
RCON.PGM_YR PGM_YR,
RCON.RCON_PFX_CD RCON_PFX_CD,
RCON.RCON_SEQ_NBR RCON_SEQ_NBR,
RCON.RCON_TYPE_CD SRC_RCON_TYPE_CD,
FARM_CHG_TYPE_RS.DMN_VAL_NM RCON_TYPE_NM,
RCON.RCON_APVL_DT RCON_APVL_DT,
RCON.RCON_EFF_DT RCON_EFF_DT,
RCON.RCON_INIT_DT RCON_INIT_DT,
MD5(trim(both RCON.ST_FSA_CD)||'~~'||trim(both RCON.CNTY_FSA_CD)||'~~'||RCON.RCON_ID||'~~'||trim(both RCON.DATA_STAT_CD)||'~~'||to_char(RCON.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(RCON.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both RCON.LAST_CHG_USER_NM)||'~~'||RCON.CNTY_OFC_CTL_ID||'~~'||RCON.TM_PRD_ID||'~~'||RCON.PGM_YR||'~~'||trim(both RCON.RCON_PFX_CD)||'~~'||trim(both RCON.RCON_SEQ_NBR)||'~~'||trim(both RCON.RCON_TYPE_CD)||'~~'||trim(both FARM_CHG_TYPE_RS.DMN_VAL_NM)||'~~'||to_char(RCON.RCON_APVL_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(RCON.RCON_EFF_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(RCON.RCON_INIT_DT,'YYYY-MM-DD HH24:MI:SS.US')) HASH_DIF
FROM SQL_FARM_RCD_STG.RCON 
LEFT JOIN(select * from EDV.FARM_CHG_TYPE_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FARM_CHG_TYPE_RS 
ON ( RCON.RCON_TYPE_CD = FARM_CHG_TYPE_RS.FARM_CHG_TYPE_CD )
where RCON.cdc_oper_cd IN ('I','UN')
order by RCON.CDC_DT
) stg 
 on ( 
coalesce(stg.RCON_ID,0) = coalesce(dv.RCON_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;