INSERT into
EDV.RCON_RS(ST_FSA_CD,
CNTY_FSA_CD,
RCON_ID,
LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
CNTY_OFC_CTL_ID,
TM_PRD_ID,
PGM_YR,
RCON_PFX_CD,
RCON_SEQ_NBR,
SRC_RCON_TYPE_CD,
RCON_TYPE_NM,
RCON_APVL_DT,
RCON_EFF_DT,
RCON_INIT_DT, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(
SELECT stg.* from (
SELECT DISTINCT
coalesce(RCON.ST_FSA_CD, '--') ST_FSA_CD,
coalesce(RCON.CNTY_FSA_CD, '--') CNTY_FSA_CD,
RCON.RCON_ID RCON_ID,
RCON.LOAD_DT LOAD_DT,
RCON.CDC_DT DATA_EFF_STRT_DT,
RCON.DATA_SRC_NM DATA_SRC_NM,
RCON.DATA_STAT_CD DATA_STAT_CD,
RCON.CRE_DT SRC_CRE_DT,
RCON.LAST_CHG_DT SRC_LAST_CHG_DT,
RCON.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
RCON.CNTY_OFC_CTL_ID CNTY_OFC_CTL_ID,
RCON.TM_PRD_ID TM_PRD_ID,
RCON.PGM_YR PGM_YR,
RCON.RCON_PFX_CD RCON_PFX_CD,
RCON.RCON_SEQ_NBR RCON_SEQ_NBR,
RCON.RCON_TYPE_CD SRC_RCON_TYPE_CD,
FARM_CHG_TYPE_RS.DMN_VAL_NM RCON_TYPE_NM,
RCON.RCON_APVL_DT RCON_APVL_DT,
RCON.RCON_EFF_DT RCON_EFF_DT,
RCON.RCON_INIT_DT RCON_INIT_DT ,
TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(trim(both RCON.ST_FSA_CD)||'~~'||trim(both RCON.CNTY_FSA_CD)||'~~'||RCON.RCON_ID||'~~'||trim(both RCON.DATA_STAT_CD)||'~~'||to_char(RCON.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(RCON.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both RCON.LAST_CHG_USER_NM)||'~~'||RCON.CNTY_OFC_CTL_ID||'~~'||RCON.TM_PRD_ID||'~~'||RCON.PGM_YR||'~~'||trim(both RCON.RCON_PFX_CD)||'~~'||trim(both RCON.RCON_SEQ_NBR)||'~~'||trim(both RCON.RCON_TYPE_CD)||'~~'||trim(both FARM_CHG_TYPE_RS.DMN_VAL_NM)||'~~'||to_char(RCON.RCON_APVL_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(RCON.RCON_EFF_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(RCON.RCON_INIT_DT,'YYYY-MM-DD HH24:MI:SS.US')) HASH_DIF
FROM SQL_FARM_RCD_STG.RCON 
LEFT JOIN(select * from EDV.FARM_CHG_TYPE_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FARM_CHG_TYPE_RS 
ON ( RCON.RCON_TYPE_CD = FARM_CHG_TYPE_RS.FARM_CHG_TYPE_CD )
where RCON.cdc_oper_cd IN ('I','UN')
order by RCON.CDC_DT
) stg 
LEFT JOIN  EDV.RCON_RS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.RCON_RS rs 
				where stg.ST_FSA_CD = rs.ST_FSA_CD
				and stg.CNTY_FSA_CD = rs.CNTY_FSA_CD 
				and stg.RCON_ID = rs.RCON_ID
				and stg.LOAD_DT = rs.LOAD_DT
		  )
);

