SELECT TECH_PRAC_CPNT_CAT,
CPNT_CAT_ID,
TECH_PRAC_ID,
TECH_PRAC_CD,
CPNT_CAT_NM,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT TECH_PRAC_CPNT_CAT,
CPNT_CAT_ID,
TECH_PRAC_ID,
TECH_PRAC_CD,
CPNT_CAT_NM,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
TECH_PRAC_CPNT_CAT
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
technical_practice_component_category.TECH_PRAC_CPNT_CAT TECH_PRAC_CPNT_CAT,
technical_practice_component_category.CPNT_CAT_ID CPNT_CAT_ID,
technical_practice_component_category.TECH_PRAC_ID TECH_PRAC_ID,
technical_practice.TECH_PRAC_CD TECH_PRAC_CD,
component_category.CPNT_CAT_NM CPNT_CAT_NM,
technical_practice_component_category.DATA_STAT_CD DATA_STAT_CD,
technical_practice_component_category.CRE_DT CRE_DT,
technical_practice_component_category.LAST_CHG_DT LAST_CHG_DT,
technical_practice_component_category.LAST_CHG_USER_NM LAST_CHG_USER_NM,
TECHNICAL_PRACTICE_COMPONENT_CATEGORY.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."TECHNICAL_PRACTICE_COMPONENT_CATEGORY" TECHNICAL_PRACTICE_COMPONENT_CATEGORY 
LEFT JOIN "fsa-{env}-cnsv".TECHNICAL_PRACTICE TECHNICAL_PRACTICE ON (TECHNICAL_PRACTICE_COMPONENT_CATEGORY.TECH_PRAC_ID = TECHNICAL_PRACTICE.TECH_PRAC_ID) 
LEFT JOIN "fsa-{env}-cnsv".COMPONENT_CATEGORY COMPONENT_CATEGORY ON (TECHNICAL_PRACTICE_COMPONENT_CATEGORY.CPNT_CAT_ID = COMPONENT_CATEGORY.CPNT_CAT_ID) 
WHERE TECHNICAL_PRACTICE_COMPONENT_CATEGORY.OP <> 'D' AND
TECHNICAL_PRACTICE_COMPONENT_CATEGORY.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
technical_practice_component_category.TECH_PRAC_CPNT_CAT TECH_PRAC_CPNT_CAT,
technical_practice_component_category.CPNT_CAT_ID CPNT_CAT_ID,
technical_practice_component_category.TECH_PRAC_ID TECH_PRAC_ID,
technical_practice.TECH_PRAC_CD TECH_PRAC_CD,
component_category.CPNT_CAT_NM CPNT_CAT_NM,
technical_practice_component_category.DATA_STAT_CD DATA_STAT_CD,
technical_practice_component_category.CRE_DT CRE_DT,
technical_practice_component_category.LAST_CHG_DT LAST_CHG_DT,
technical_practice_component_category.LAST_CHG_USER_NM LAST_CHG_USER_NM,
TECHNICAL_PRACTICE.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."TECHNICAL_PRACTICE" TECHNICAL_PRACTICE 
JOIN "fsa-{env}-cnsv".TECHNICAL_PRACTICE_COMPONENT_CATEGORY TECHNICAL_PRACTICE_COMPONENT_CATEGORY ON (TECHNICAL_PRACTICE_COMPONENT_CATEGORY.TECH_PRAC_ID = TECHNICAL_PRACTICE.TECH_PRAC_ID) 
LEFT JOIN "fsa-{env}-cnsv".COMPONENT_CATEGORY COMPONENT_CATEGORY ON (TECHNICAL_PRACTICE_COMPONENT_CATEGORY.CPNT_CAT_ID = COMPONENT_CATEGORY.CPNT_CAT_ID) 
WHERE TECHNICAL_PRACTICE.OP <> 'D' AND
TECHNICAL_PRACTICE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
technical_practice_component_category.TECH_PRAC_CPNT_CAT TECH_PRAC_CPNT_CAT,
technical_practice_component_category.CPNT_CAT_ID CPNT_CAT_ID,
technical_practice_component_category.TECH_PRAC_ID TECH_PRAC_ID,
technical_practice.TECH_PRAC_CD TECH_PRAC_CD,
component_category.CPNT_CAT_NM CPNT_CAT_NM,
technical_practice_component_category.DATA_STAT_CD DATA_STAT_CD,
technical_practice_component_category.CRE_DT CRE_DT,
technical_practice_component_category.LAST_CHG_DT LAST_CHG_DT,
technical_practice_component_category.LAST_CHG_USER_NM LAST_CHG_USER_NM,
COMPONENT_CATEGORY.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."COMPONENT_CATEGORY" COMPONENT_CATEGORY 
JOIN "fsa-{env}-cnsv".TECHNICAL_PRACTICE_COMPONENT_CATEGORY TECHNICAL_PRACTICE_COMPONENT_CATEGORY ON (TECHNICAL_PRACTICE_COMPONENT_CATEGORY.CPNT_CAT_ID = COMPONENT_CATEGORY.CPNT_CAT_ID) 
LEFT JOIN "fsa-{env}-cnsv".TECHNICAL_PRACTICE TECHNICAL_PRACTICE ON (TECHNICAL_PRACTICE_COMPONENT_CATEGORY.TECH_PRAC_ID = TECHNICAL_PRACTICE.TECH_PRAC_ID) 
WHERE COMPONENT_CATEGORY.OP <> 'D' AND
COMPONENT_CATEGORY.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
technical_practice_component_category.TECH_PRAC_CPNT_CAT TECH_PRAC_CPNT_CAT,
technical_practice_component_category.CPNT_CAT_ID CPNT_CAT_ID,
technical_practice_component_category.TECH_PRAC_ID TECH_PRAC_ID,
NULL TECH_PRAC_CD,
NULL CPNT_CAT_NM,
technical_practice_component_category.DATA_STAT_CD DATA_STAT_CD,
technical_practice_component_category.CRE_DT CRE_DT,
technical_practice_component_category.LAST_CHG_DT LAST_CHG_DT,
technical_practice_component_category.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".technical_practice_component_category technical_practice_component_category
WHERE OP = 'D'
AND dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}' 
)