MERGE INTO EDV.DIR_ATRB_PRPS_PYMT_SIM_LS dv USING
  (SELECT DISTINCT MD5 (upper(COALESCE (trim(PRPS_PYMT_SIM.ST_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(PRPS_PYMT_SIM.CNTY_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(PRPS_PYMT_SIM.ACCT_PGM_CD), '--')) ||'~~'||COALESCE (PRPS_PYMT_SIM.PAID_CORE_CUST_ID, '-1')) AS DIR_ATRB_PRPS_PYMT_L_ID,
                   coalesce(PRPS_PYMT_SIM.PRPS_PYMT_SIM_ID, '-1') PRPS_PYMT_SIM_ID,
                   PRPS_PYMT_SIM.LOAD_DT LOAD_DT,
                   PRPS_PYMT_SIM.CDC_DT DATA_EFF_STRT_DT,
                   PRPS_PYMT_SIM.DATA_SRC_NM DATA_SRC_NM,
                   PRPS_PYMT_SIM.DATA_STAT_CD DATA_STAT_CD,
                   PRPS_PYMT_SIM.CRE_DT SRC_CRE_DT,
                   PRPS_PYMT_SIM.CRE_USER_NM SRC_CRE_USER_NM,
                   PRPS_PYMT_SIM.LAST_CHG_DT SRC_LAST_CHG_DT,
                   PRPS_PYMT_SIM.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
                   PRPS_PYMT_SIM.PRV_PRPS_PYMT_SIM_ID PRV_PRPS_PYMT_SIM_ID,
                   PRPS_PYMT_SIM.RCD_REF_PRIM_ID_TYPE_CD RCD_REF_PRIM_ID_TYPE_CD,
                   PRPS_PYMT_SIM.RCD_REF_SCND_ID_TYPE_CD RCD_REF_SCND_ID_TYPE_CD,
                   PRPS_PYMT_SIM.ST_FSA_CD ST_FSA_CD,
                   PRPS_PYMT_SIM.CNTY_FSA_CD CNTY_FSA_CD,
                   PRPS_PYMT_SIM.ACCT_PGM_CD ACCT_PGM_CD,
                   PRPS_PYMT_SIM.PAID_CORE_CUST_ID PAID_CORE_CUST_ID,
                   PRPS_PYMT_SIM.SBSD_PRD_STRT_YR SBSD_PRD_STRT_YR,
                   PRPS_PYMT_SIM.PROC_RQST_REF_NBR PROC_RQST_REF_NBR,
                   PRPS_PYMT_SIM.RCD_REF_PRIM_ID RCD_REF_PRIM_ID,
                   PRPS_PYMT_SIM.RCD_REF_SCND_ID RCD_REF_SCND_ID,
                   PRPS_PYMT_SIM.CMDY_CD CMDY_CD,
                   PRPS_PYMT_SIM.PYMT_AMT PYMT_AMT,
                   PRPS_PYMT_SIM.PYMT_LMT_IND PYMT_LMT_IND,
                   PRPS_PYMT_SIM.HRCH_PYMT_LMT_IND HRCH_PYMT_LMT_IND,
                   PRPS_PYMT_SIM.PRST_OPYMT_ATRB_IND PRST_OPYMT_ATRB_IND,
                   PRPS_PYMT_SIM.APP_3_OWNSHP_LVL_LMT_IND APP_3_OWNSHP_LVL_LMT_IND,
                   PRPS_PYMT_SIM.DEC_PRCS_NBR DEC_PRCS_NBR,
                   PRPS_PYMT_SIM.PYMT_ATRB_RQST_RSN_TXT PYMT_ATRB_RQST_RSN_TXT,
                   PRPS_PYMT_SIM.PYMT_ATRB_RVRS_DT PYMT_ATRB_RVRS_DT,
                   PRPS_PYMT_SIM.OVRRD_SBSD_PRD_STRT_YR OVRRD_SBSD_PRD_STRT_YR,
                   PRPS_PYMT_SIM.PYMT_PGM_ID PYMT_PGM_ID,
                   PRPS_PYMT_SIM.PYMT_LMT_YR PYMT_LMT_YR,
                   PRPS_PYMT_SIM.SIM_SCHD_END_DT SIM_SCHD_END_DT,
                   PRPS_PYMT_SIM.ATRB_SIM_PYMT_TYPE_CD ATRB_SIM_PYMT_TYPE_CD,
                   PRPS_PYMT_SIM.PGM_ENRL_APP_ID PGM_ENRL_APP_ID,
                   PRPS_PYMT_SIM.OBL_CNFRM_NBR OBL_CNFRM_NBR,
                   PRPS_PYMT_SIM.CDC_OPER_CD,
                   MD5 (trim(PRPS_PYMT_SIM.ST_FSA_CD)||'~~'||trim(PRPS_PYMT_SIM.CNTY_FSA_CD)||'~~'||trim(PRPS_PYMT_SIM.ACCT_PGM_CD)||'~~'||PRPS_PYMT_SIM.PAID_CORE_CUST_ID||'~~'||PRPS_PYMT_SIM.PRPS_PYMT_SIM_ID||'~~'||trim(PRPS_PYMT_SIM.DATA_STAT_CD)||'~~'||to_char(PRPS_PYMT_SIM.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PRPS_PYMT_SIM.CRE_USER_NM)||'~~'||to_char(PRPS_PYMT_SIM.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PRPS_PYMT_SIM.LAST_CHG_USER_NM)||'~~'||PRPS_PYMT_SIM.PRV_PRPS_PYMT_SIM_ID||'~~'||trim(PRPS_PYMT_SIM.RCD_REF_PRIM_ID_TYPE_CD)||'~~'||trim(PRPS_PYMT_SIM.RCD_REF_SCND_ID_TYPE_CD)||'~~'||trim(PRPS_PYMT_SIM.ST_FSA_CD)||'~~'||trim(PRPS_PYMT_SIM.CNTY_FSA_CD)||'~~'||trim(PRPS_PYMT_SIM.ACCT_PGM_CD)||'~~'||PRPS_PYMT_SIM.PAID_CORE_CUST_ID||'~~'||PRPS_PYMT_SIM.SBSD_PRD_STRT_YR||'~~'||PRPS_PYMT_SIM.PROC_RQST_REF_NBR||'~~'||trim(PRPS_PYMT_SIM.RCD_REF_PRIM_ID)||'~~'||trim(PRPS_PYMT_SIM.RCD_REF_SCND_ID)||'~~'||trim(PRPS_PYMT_SIM.CMDY_CD)||'~~'||PRPS_PYMT_SIM.PYMT_AMT||'~~'||trim(PRPS_PYMT_SIM.PYMT_LMT_IND)||'~~'||trim(PRPS_PYMT_SIM.HRCH_PYMT_LMT_IND)||'~~'||trim(PRPS_PYMT_SIM.PRST_OPYMT_ATRB_IND)||'~~'||trim(PRPS_PYMT_SIM.APP_3_OWNSHP_LVL_LMT_IND)||'~~'||PRPS_PYMT_SIM.DEC_PRCS_NBR||'~~'||trim(PRPS_PYMT_SIM.PYMT_ATRB_RQST_RSN_TXT)||'~~'||to_char(PRPS_PYMT_SIM.PYMT_ATRB_RVRS_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||PRPS_PYMT_SIM.OVRRD_SBSD_PRD_STRT_YR||'~~'||PRPS_PYMT_SIM.PYMT_PGM_ID||'~~'||PRPS_PYMT_SIM.PYMT_LMT_YR||'~~'||to_char(PRPS_PYMT_SIM.SIM_SCHD_END_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PRPS_PYMT_SIM.ATRB_SIM_PYMT_TYPE_CD)||'~~'||trim(PRPS_PYMT_SIM.PGM_ENRL_APP_ID)||'~~'||PRPS_PYMT_SIM.OBL_CNFRM_NBR) HASH_DIF
   FROM SBSD_STG.PRPS_PYMT_SIM PRPS_PYMT_SIM
   WHERE PRPS_PYMT_SIM.CDC_OPER_CD='D'
     AND date(PRPS_PYMT_SIM.CDC_DT) = date(TO_TIMESTAMP ('{ETL_START_TIMESTAMP}', 'YYYY-MM-DD HH24:MI:SS.FF'))
   ORDER BY PRPS_PYMT_SIM.CDC_DT) stg ON (coalesce(stg.PRPS_PYMT_SIM_ID, 0) = coalesce(dv.PRPS_PYMT_SIM_ID, 0)) 
WHEN MATCHED
  AND dv.LOAD_DT <> stg.LOAD_DT
  AND dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD')
THEN
UPDATE
SET LOAD_END_DT = stg.LOAD_DT,
    DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT