INSERT INTO EDV.PRDR_PGM_PYMT_LMT_ADJ_TYPE_RS (PRDR_PYMT_LMT_ADJ_TYPE_CD, LOAD_DT, DATA_EFF_STRT_DT, DATA_SRC_NM, DATA_STAT_CD, SRC_CRE_DT, SRC_CRE_USER_NM, SRC_LAST_CHG_DT, SRC_LAST_CHG_USER_NM, PRDR_PYMT_LMT_ADJ_TYPE_NM, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
  (SELECT stg.*
   FROM
     (SELECT DISTINCT COALESCE (PRDR_PYMT_LMT_ADJ_TYPE.PRDR_PYMT_LMT_ADJ_TYPE_CD,
                           '--') PRDR_PYMT_LMT_ADJ_TYPE_CD,
                          PRDR_PYMT_LMT_ADJ_TYPE.LOAD_DT LOAD_DT,
                          PRDR_PYMT_LMT_ADJ_TYPE.CDC_DT DATA_EFF_STRT_DT,
                          PRDR_PYMT_LMT_ADJ_TYPE.DATA_SRC_NM DATA_SRC_NM,
                          PRDR_PYMT_LMT_ADJ_TYPE.DATA_STAT_CD DATA_STAT_CD,
                          PRDR_PYMT_LMT_ADJ_TYPE.CRE_DT SRC_CRE_DT,
                          PRDR_PYMT_LMT_ADJ_TYPE.CRE_USER_NM SRC_CRE_USER_NM,
                          PRDR_PYMT_LMT_ADJ_TYPE.LAST_CHG_DT SRC_LAST_CHG_DT,
                          PRDR_PYMT_LMT_ADJ_TYPE.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
                          PRDR_PYMT_LMT_ADJ_TYPE.PRDR_PYMT_LMT_ADJ_TYPE_NM PRDR_PYMT_LMT_ADJ_TYPE_NM,
                          TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD') DATA_EFF_END_DT,
                          TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD') LOAD_END_DT,
                          MD5 (trim(PRDR_PYMT_LMT_ADJ_TYPE.PRDR_PYMT_LMT_ADJ_TYPE_CD)||'~~'||trim(PRDR_PYMT_LMT_ADJ_TYPE.DATA_STAT_CD)||'~~'||to_char(PRDR_PYMT_LMT_ADJ_TYPE.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PRDR_PYMT_LMT_ADJ_TYPE.CRE_USER_NM)||'~~'||to_char(PRDR_PYMT_LMT_ADJ_TYPE.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PRDR_PYMT_LMT_ADJ_TYPE.LAST_CHG_USER_NM)||'~~'||trim(PRDR_PYMT_LMT_ADJ_TYPE.PRDR_PYMT_LMT_ADJ_TYPE_NM)) HASH_DIF
      FROM SBSD_STG.PRDR_PYMT_LMT_ADJ_TYPE
      WHERE PRDR_PYMT_LMT_ADJ_TYPE.cdc_oper_cd IN ('I',
                                                   'UN')
        AND date(PRDR_PYMT_LMT_ADJ_TYPE.CDC_DT) = date(TO_TIMESTAMP ('{ETL_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF'))
        AND PRDR_PYMT_LMT_ADJ_TYPE.LOAD_DT = (SELECT MAX(LOAD_DT) FROM SBSD_STG.PRDR_PYMT_LMT_ADJ_TYPE)
      ORDER BY PRDR_PYMT_LMT_ADJ_TYPE.CDC_DT) stg
   LEFT JOIN EDV.PRDR_PGM_PYMT_LMT_ADJ_TYPE_RS dv ON (stg.HASH_DIF = dv.HASH_DIF
                                                      AND dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD'))
   WHERE dv.HASH_DIF IS NULL )