-- Julia Lu edition - will update this paragraph and query when (cnsv/ccms)-cdc is ready
-- Stage SQL: CCMS_CTR_PRDR (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CCMS_CTR_PRDR/incremental/CCMS_CTR_PRDR.sql
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT CTR_PRDR_ID,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_NM,
SGNP_SUB_CAT_NM,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
CTR_NBR,
CTR_SFX_NBR,
CORE_CUST_ID,
CTR_DET_ID,
PRDR_SHR_PCT,
PRIM_PRDR_IND,
--PRDR_INVL_CD,
DATA_STAT_CD,
CRE_DT,
CRE_USER_NM,
LAST_CHG_DT,
LAST_CHG_USER_NM,
TIP_ELG_PTCP_IND,
LTD_RSRC_PRDR_IND,
SOCL_DADVG_IND,
BEG_FARM_IND,
VET_IND,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CTR_PRDR_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
CONTRACT_PRODUCER.CONTRACT_PRODUCER_IDENTIFIER CTR_PRDR_ID,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_PRODUCER.CORE_CUSTOMER_IDENTIFIER CORE_CUST_ID,
CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_PRODUCER.PRODUCER_SHARE_PERCENTAGE PRDR_SHR_PCT,
CONTRACT_PRODUCER.PRIMARY_PRODUCER_INDICATOR PRIM_PRDR_IND,
--CONTRACT_PRODUCER.PRODUCER_INVOLVEMENT_CODE PRDR_INVL_CD,
CONTRACT_PRODUCER.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_PRODUCER.CREATION_DATE CRE_DT,
CONTRACT_PRODUCER.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_PRODUCER.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_PRODUCER.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_PRODUCER.tip_eligible_participant_indicator  TIP_ELG_PTCP_IND,
CONTRACT_PRODUCER.limited_resource_producer_indicator LTD_RSRC_PRDR_IND,
CONTRACT_PRODUCER.socially_disadvantaged_indicator SOCL_DADVG_IND,
CONTRACT_PRODUCER.beginning_farmer_indicator BEG_FARM_IND,
CONTRACT_PRODUCER.veteran_indicator VET_IND,
CONTRACT_PRODUCER.op,
1 AS TBL_PRIORITY
From "fsa-{env}-ccms-cdc".CONTRACT_PRODUCER
Left Join "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
on CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left join "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left join "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
WHERE CONTRACT_PRODUCER.op <> 'D'

UNION
SELECT 
CONTRACT_PRODUCER.CONTRACT_PRODUCER_IDENTIFIER CTR_PRDR_ID,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_PRODUCER.CORE_CUSTOMER_IDENTIFIER CORE_CUST_ID,
CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_PRODUCER.PRODUCER_SHARE_PERCENTAGE PRDR_SHR_PCT,
CONTRACT_PRODUCER.PRIMARY_PRODUCER_INDICATOR PRIM_PRDR_IND,
CONTRACT_PRODUCER.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_PRODUCER.CREATION_DATE CRE_DT,
CONTRACT_PRODUCER.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_PRODUCER.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_PRODUCER.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_PRODUCER.tip_eligible_participant_indicator  TIP_ELG_PTCP_IND,
CONTRACT_PRODUCER.limited_resource_producer_indicator LTD_RSRC_PRDR_IND,
CONTRACT_PRODUCER.socially_disadvantaged_indicator SOCL_DADVG_IND,
CONTRACT_PRODUCER.beginning_farmer_indicator BEG_FARM_IND,
CONTRACT_PRODUCER.veteran_indicator VET_IND,
CONTRACT_DETAIL.op,
2 AS TBL_PRIORITY
From  "fsa-{env}-ccms-cdc".CONTRACT_DETAIL
Join "fsa-{env}-ccms-cdc".CONTRACT_PRODUCER
on CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left join "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left join "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
WHERE CONTRACT_DETAIL.op <> 'D'

UNION
SELECT 
CONTRACT_PRODUCER.CONTRACT_PRODUCER_IDENTIFIER CTR_PRDR_ID,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_PRODUCER.CORE_CUSTOMER_IDENTIFIER CORE_CUST_ID,
CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_PRODUCER.PRODUCER_SHARE_PERCENTAGE PRDR_SHR_PCT,
CONTRACT_PRODUCER.PRIMARY_PRODUCER_INDICATOR PRIM_PRDR_IND,
CONTRACT_PRODUCER.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_PRODUCER.CREATION_DATE CRE_DT,
CONTRACT_PRODUCER.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_PRODUCER.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_PRODUCER.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_PRODUCER.tip_eligible_participant_indicator  TIP_ELG_PTCP_IND,
CONTRACT_PRODUCER.limited_resource_producer_indicator LTD_RSRC_PRDR_IND,
CONTRACT_PRODUCER.socially_disadvantaged_indicator SOCL_DADVG_IND,
CONTRACT_PRODUCER.beginning_farmer_indicator BEG_FARM_IND,
CONTRACT_PRODUCER.veteran_indicator VET_IND,
MASTER_CONTRACT.op,
4 AS TBL_PRIORITY
From "fsa-{env}-ccms-cdc".MASTER_CONTRACT
Left Join  "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_PRODUCER
on CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left join "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
WHERE MASTER_CONTRACT.op <> 'D'

UNION
SELECT 
CONTRACT_PRODUCER.CONTRACT_PRODUCER_IDENTIFIER CTR_PRDR_ID,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_PRODUCER.CORE_CUSTOMER_IDENTIFIER CORE_CUST_ID,
CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_PRODUCER.PRODUCER_SHARE_PERCENTAGE PRDR_SHR_PCT,
CONTRACT_PRODUCER.PRIMARY_PRODUCER_INDICATOR PRIM_PRDR_IND,
CONTRACT_PRODUCER.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_PRODUCER.CREATION_DATE CRE_DT,
CONTRACT_PRODUCER.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_PRODUCER.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_PRODUCER.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_PRODUCER.tip_eligible_participant_indicator  TIP_ELG_PTCP_IND,
CONTRACT_PRODUCER.limited_resource_producer_indicator LTD_RSRC_PRDR_IND,
CONTRACT_PRODUCER.socially_disadvantaged_indicator SOCL_DADVG_IND,
CONTRACT_PRODUCER.beginning_farmer_indicator BEG_FARM_IND,
CONTRACT_PRODUCER.veteran_indicator VET_IND,
SIGNUP.op,
5 AS TBL_PRIORITY
From "fsa-{env}-ccms-cdc".SIGNUP
Left Join "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join  "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_PRODUCER
on CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left join "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
WHERE SIGNUP.op <> 'D'

UNION
SELECT 
CONTRACT_PRODUCER.CONTRACT_PRODUCER_IDENTIFIER CTR_PRDR_ID,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_PRODUCER.CORE_CUSTOMER_IDENTIFIER CORE_CUST_ID,
CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_PRODUCER.PRODUCER_SHARE_PERCENTAGE PRDR_SHR_PCT,
CONTRACT_PRODUCER.PRIMARY_PRODUCER_INDICATOR PRIM_PRDR_IND,
CONTRACT_PRODUCER.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_PRODUCER.CREATION_DATE CRE_DT,
CONTRACT_PRODUCER.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_PRODUCER.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_PRODUCER.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_PRODUCER.tip_eligible_participant_indicator  TIP_ELG_PTCP_IND,
CONTRACT_PRODUCER.limited_resource_producer_indicator LTD_RSRC_PRDR_IND,
CONTRACT_PRODUCER.socially_disadvantaged_indicator SOCL_DADVG_IND,
CONTRACT_PRODUCER.beginning_farmer_indicator BEG_FARM_IND,
CONTRACT_PRODUCER.veteran_indicator VET_IND,
SIGNUP_TYPE.op,
6 AS TBL_PRIORITY
From "fsa-{env}-ccms-cdc".SIGNUP_TYPE
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left Join "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join  "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_PRODUCER
on CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left join "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
WHERE SIGNUP_TYPE.op <> 'D'

UNION
SELECT 
CONTRACT_PRODUCER.CONTRACT_PRODUCER_IDENTIFIER CTR_PRDR_ID,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_PRODUCER.CORE_CUSTOMER_IDENTIFIER CORE_CUST_ID,
CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_PRODUCER.PRODUCER_SHARE_PERCENTAGE PRDR_SHR_PCT,
CONTRACT_PRODUCER.PRIMARY_PRODUCER_INDICATOR PRIM_PRDR_IND,
CONTRACT_PRODUCER.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_PRODUCER.CREATION_DATE CRE_DT,
CONTRACT_PRODUCER.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_PRODUCER.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_PRODUCER.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_PRODUCER.tip_eligible_participant_indicator  TIP_ELG_PTCP_IND,
CONTRACT_PRODUCER.limited_resource_producer_indicator LTD_RSRC_PRDR_IND,
CONTRACT_PRODUCER.socially_disadvantaged_indicator SOCL_DADVG_IND,
CONTRACT_PRODUCER.beginning_farmer_indicator BEG_FARM_IND,
CONTRACT_PRODUCER.veteran_indicator VET_IND,
SIGNUP_SUB_CATEGORY.op,
7 AS TBL_PRIORITY
From "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
 Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
 On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left Join "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join  "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_PRODUCER
on CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
WHERE SIGNUP_SUB_CATEGORY.op <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND CONTRACT_PRODUCER.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
CONTRACT_PRODUCER.CONTRACT_PRODUCER_IDENTIFIER CTR_PRDR_ID,
NULL ADM_ST_FSA_CD,
NULL ADM_CNTY_FSA_CD,
NULL SGNP_TYPE_NM,
NULL SGNP_SUB_CAT_NM,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL CTR_NBR,
NULL CTR_SFX_NBR,
CONTRACT_PRODUCER.CORE_CUSTOMER_IDENTIFIER CORE_CUST_ID,
CONTRACT_PRODUCER.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_PRODUCER.PRODUCER_SHARE_PERCENTAGE PRDR_SHR_PCT,
CONTRACT_PRODUCER.PRIMARY_PRODUCER_INDICATOR PRIM_PRDR_IND,
CONTRACT_PRODUCER.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_PRODUCER.CREATION_DATE CRE_DT,
CONTRACT_PRODUCER.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_PRODUCER.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_PRODUCER.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_PRODUCER.tip_eligible_participant_indicator  TIP_ELG_PTCP_IND,
CONTRACT_PRODUCER.limited_resource_producer_indicator LTD_RSRC_PRDR_IND,
CONTRACT_PRODUCER.socially_disadvantaged_indicator SOCL_DADVG_IND,
CONTRACT_PRODUCER.beginning_farmer_indicator BEG_FARM_IND,
CONTRACT_PRODUCER.veteran_indicator VET_IND,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-ccms-cdc".CONTRACT_PRODUCER
WHERE CONTRACT_PRODUCER.op = 'D'