Merge into
EDV.CROP_TR_CTR_LS dv
using(select DISTINCT
MD5(MD5(upper(coalesce(CROP_TR_CTR.ST_FSA_CD,'--')||'~~'||coalesce(CROP_TR_CTR.CNTY_FSA_CD,'--')||'~~'||coalesce((CROP_TR_CTR.TR_NBR)::numeric ,-1)))||'~~'||upper(coalesce(trim(both CROP_TR_CTR.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both CROP_TR_CTR.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_TR_CTR.FSA_CROP_TYPE_CD), '--')) ) CROP_TR_CTR_L_ID,
CROP_TR_CTR.CROP_TR_CTR_ID CROP_TR_CTR_ID,CROP_TR_CTR.LOAD_DT LOAD_DT,CROP_TR_CTR.CDC_DT DATA_EFF_STRT_DT,CROP_TR_CTR.DATA_SRC_NM DATA_SRC_NM,CROP_TR_CTR.DATA_STAT_CD DATA_STAT_CD,CROP_TR_CTR.CRE_DT SRC_CRE_DT,CROP_TR_CTR.LAST_CHG_DT SRC_LAST_CHG_DT,CROP_TR_CTR.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,CROP_TR_CTR.TR_ID TR_ID,CROP_TR_CTR.CROP_ID CROP_ID,CROP_TR_CTR.CTR_NBR CTR_NBR,CROP_TR_CTR.RDN_ACRG_STRT_YR RDN_ACRG_STRT_YR,CROP_TR_CTR.RDN_ACRG RDN_ACRG,CROP_TR_CTR.CROP_PGM_PYMT_YLD CROP_PGM_PYMT_YLD,CROP_TR_CTR.CROP_PGM_ALT_PYMT_YLD CROP_PGM_ALT_PYMT_YLD ,
CROP_TR_CTR.TR_YR_ID, CROP_TR_CTR.PGM_YR,
CROP_TR_CTR.CDC_OPER_CD,
MD5(upper(coalesce(CROP_TR_CTR.ST_FSA_CD,'--')||'~~'||coalesce(CROP_TR_CTR.CNTY_FSA_CD,'--')||'~~'||coalesce((CROP_TR_CTR.TR_NBR)::numeric ,-1))||'~~'||trim(both CROP_TR_CTR.PGM_ABR)||'~~'||trim(both CROP_TR_CTR.FSA_CROP_CD)||'~~'||trim(both CROP_TR_CTR.FSA_CROP_TYPE_CD)||'~~'||CROP_TR_CTR.CROP_TR_CTR_ID||'~~'||trim(both CROP_TR_CTR.DATA_STAT_CD)||'~~'||to_char(CROP_TR_CTR.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(CROP_TR_CTR.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_TR_CTR.LAST_CHG_USER_NM)||'~~'||CROP_TR_CTR.TR_ID||'~~'||CROP_TR_CTR.CROP_ID||'~~'||trim(both CROP_TR_CTR.CTR_NBR)||'~~'||CROP_TR_CTR.RDN_ACRG_STRT_YR||'~~'||CROP_TR_CTR.RDN_ACRG||'~~'||CROP_TR_CTR.CROP_PGM_PYMT_YLD||'~~'||CROP_TR_CTR.CROP_PGM_ALT_PYMT_YLD||'~~'||coalesce(CROP_TR_CTR.TR_YR_ID,-1)||'~~'||coalesce(CROP_TR_CTR.PGM_YR,-1) ) HASH_DIF
FROM SQL_FARM_RCD_STG.CROP_TR_CTR  CROP_TR_CTR
 where CROP_TR_CTR.CDC_OPER_CD='D'
order by CROP_TR_CTR.CDC_DT)
stg
 on ( 
coalesce(stg.CROP_TR_CTR_ID,0) = coalesce(dv.CROP_TR_CTR_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN
INSERT(
CROP_TR_CTR_L_ID,CROP_TR_CTR_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
TR_ID,
CROP_ID,
CTR_NBR,
RDN_ACRG_STRT_YR,
RDN_ACRG,
CROP_PGM_PYMT_YLD,
CROP_PGM_ALT_PYMT_YLD,
 TR_YR_ID, PGM_YR	,
DATA_EFF_END_DT,LOAD_END_DT,HASH_DIF)
VALUES (
stg.CROP_TR_CTR_L_ID,stg.CROP_TR_CTR_ID,stg.LOAD_DT,stg.DATA_EFF_STRT_DT,stg.DATA_SRC_NM,stg.DATA_STAT_CD,stg.SRC_CRE_DT,stg.SRC_LAST_CHG_DT,stg.SRC_LAST_CHG_USER_NM,stg.TR_ID,stg.CROP_ID,stg.CTR_NBR,stg.RDN_ACRG_STRT_YR,stg.RDN_ACRG,stg.CROP_PGM_PYMT_YLD,stg.CROP_PGM_ALT_PYMT_YLD, stg.TR_YR_ID,stg.PGM_YR	,stg.DATA_EFF_STRT_DT,stg.LOAD_DT,
stg.HASH_DIF
)
;