-- Julia Lu edition - will update this paragraph and query when cnsv-cdc is ready
-- Stage SQL: CNSV_EWT84SPRAC (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_EWT84SPRAC/incremental/CNSV_EWT84SPRAC.sql
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
CNSV_PRAC_CD,
N5_PNT_NBR,
LONG_LEAF_PINE_IND,
TREE_PLNT_PDMNT,
WLHD_ACRG_IND,
MPL_ACRG_IND,
IFSBL_TO_FARM_AUTH,
PRAC_INCTV_RT,
WLHD_INCTV_RT,
MPL_INCTV_RT,
IFSBL_INCTV_RT,
CRP_SIP_AUTH_IND,
CRP_SIP_RT,
PIP_AUTH_IND,
PIP_RT,
CPLD_PRAC_IND,
WL_RSTR_INCTV_RT,
PRAC_WL_RSTR_INCTV,
MAX_CNSR_ACRG,
MAX_BDGT_AMT,
PRAC_MIN_LFSP_CT,
PRAC_MAX_LFSP_CT,
PVT_IRR_CRNR_IND,
NONCROPLAND_PRAC_IND,
SGNP_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OPYMT_ALOW_IND,
-- op,
ROW_NUMBER() over ( partition by 
CNSV_PRAC_CD,
SGNP_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt84sprac.CNSV_PRAC_CD CNSV_PRAC_CD,
ewt84sprac.N5_PNT_NBR N5_PNT_NBR,
ewt84sprac.LONG_LEAF_PINE_IND LONG_LEAF_PINE_IND,
ewt84sprac.TREE_PLNT_PDMNT TREE_PLNT_PDMNT,
ewt84sprac.WLHD_ACRG_IND WLHD_ACRG_IND,
ewt84sprac.MPL_ACRG_IND MPL_ACRG_IND,
ewt84sprac.IFSBL_TO_FARM_AUTH IFSBL_TO_FARM_AUTH,
ewt84sprac.PRAC_INCTV_RT PRAC_INCTV_RT,
ewt84sprac.WLHD_INCTV_RT WLHD_INCTV_RT,
ewt84sprac.MPL_INCTV_RT MPL_INCTV_RT,
ewt84sprac.IFSBL_INCTV_RT IFSBL_INCTV_RT,
ewt84sprac.CRP_SIP_AUTH_IND CRP_SIP_AUTH_IND,
ewt84sprac.CRP_SIP_RT CRP_SIP_RT,
ewt84sprac.PIP_AUTH_IND PIP_AUTH_IND,
ewt84sprac.PIP_RT PIP_RT,
ewt84sprac.CPLD_PRAC_IND CPLD_PRAC_IND,
ewt84sprac.WL_RSTR_INCTV_RT WL_RSTR_INCTV_RT,
ewt84sprac.PRAC_WL_RSTR_INCTV PRAC_WL_RSTR_INCTV,
ewt84sprac.MAX_CNSR_ACRG MAX_CNSR_ACRG,
ewt84sprac.MAX_BDGT_AMT MAX_BDGT_AMT,
ewt84sprac.prac_min_lfsp_ct PRAC_MIN_LFSP_CT,
ewt84sprac.prac_max_lfsp_ct PRAC_MAX_LFSP_CT,
ewt84sprac.pvt_irr_crnr_ind PVT_IRR_CRNR_IND,
ewt84sprac.ncpld_prac_ind NONCROPLAND_PRAC_IND,
ewt84sprac.SGNP_ID SGNP_ID,
ewt84sprac.DATA_STAT_CD DATA_STAT_CD,
ewt84sprac.CRE_DT CRE_DT,
ewt84sprac.LAST_CHG_DT LAST_CHG_DT,
ewt84sprac.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ewt84sprac.OPYMT_ALOW_IND OPYMT_ALOW_IND,
-- op,
1 AS TBL_PRIORITY
FROM "fsa-prod-cnsv".EWT84SPRAC 
LEFT JOIN "fsa-prod-cnsv".EWT14SGNP ON (EWT84SPRAC.SGNP_ID = EWT14SGNP.SGNP_ID)
--WHERE __CDC_OPERATION <> 'D'

UNION
SELECT 
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt84sprac.CNSV_PRAC_CD CNSV_PRAC_CD,
ewt84sprac.N5_PNT_NBR N5_PNT_NBR,
ewt84sprac.LONG_LEAF_PINE_IND LONG_LEAF_PINE_IND,
ewt84sprac.TREE_PLNT_PDMNT TREE_PLNT_PDMNT,
ewt84sprac.WLHD_ACRG_IND WLHD_ACRG_IND,
ewt84sprac.MPL_ACRG_IND MPL_ACRG_IND,
ewt84sprac.IFSBL_TO_FARM_AUTH IFSBL_TO_FARM_AUTH,
ewt84sprac.PRAC_INCTV_RT PRAC_INCTV_RT,
ewt84sprac.WLHD_INCTV_RT WLHD_INCTV_RT,
ewt84sprac.MPL_INCTV_RT MPL_INCTV_RT,
ewt84sprac.IFSBL_INCTV_RT IFSBL_INCTV_RT,
ewt84sprac.CRP_SIP_AUTH_IND CRP_SIP_AUTH_IND,
ewt84sprac.CRP_SIP_RT CRP_SIP_RT,
ewt84sprac.PIP_AUTH_IND PIP_AUTH_IND,
ewt84sprac.PIP_RT PIP_RT,
ewt84sprac.CPLD_PRAC_IND CPLD_PRAC_IND,
ewt84sprac.WL_RSTR_INCTV_RT WL_RSTR_INCTV_RT,
ewt84sprac.PRAC_WL_RSTR_INCTV PRAC_WL_RSTR_INCTV,
ewt84sprac.MAX_CNSR_ACRG MAX_CNSR_ACRG,
ewt84sprac.MAX_BDGT_AMT MAX_BDGT_AMT,
ewt84sprac.prac_min_lfsp_ct PRAC_MIN_LFSP_CT,
ewt84sprac.prac_max_lfsp_ct PRAC_MAX_LFSP_CT,
ewt84sprac.pvt_irr_crnr_ind PVT_IRR_CRNR_IND,
ewt84sprac.ncpld_prac_ind NONCROPLAND_PRAC_IND,
ewt84sprac.SGNP_ID SGNP_ID,
ewt84sprac.DATA_STAT_CD DATA_STAT_CD,
ewt84sprac.CRE_DT CRE_DT,
ewt84sprac.LAST_CHG_DT LAST_CHG_DT,
ewt84sprac.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ewt84sprac.OPYMT_ALOW_IND OPYMT_ALOW_IND,
-- op,
2 AS TBL_PRIORITY
FROM "fsa-prod-cnsv".EWT14SGNP 
JOIN "fsa-prod-cnsv".EWT84SPRAC ON (EWT14SGNP.SGNP_ID = EWT84SPRAC.SGNP_ID)
--WHERE __CDC_OPERATION <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('2025-07-01' AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('2025-07-01' AS DATE))
)

UNION
SELECT DISTINCT
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
ewt84sprac.CNSV_PRAC_CD CNSV_PRAC_CD,
ewt84sprac.N5_PNT_NBR N5_PNT_NBR,
ewt84sprac.LONG_LEAF_PINE_IND LONG_LEAF_PINE_IND,
ewt84sprac.TREE_PLNT_PDMNT TREE_PLNT_PDMNT,
ewt84sprac.WLHD_ACRG_IND WLHD_ACRG_IND,
ewt84sprac.MPL_ACRG_IND MPL_ACRG_IND,
ewt84sprac.IFSBL_TO_FARM_AUTH IFSBL_TO_FARM_AUTH,
ewt84sprac.PRAC_INCTV_RT PRAC_INCTV_RT,
ewt84sprac.WLHD_INCTV_RT WLHD_INCTV_RT,
ewt84sprac.MPL_INCTV_RT MPL_INCTV_RT,
ewt84sprac.IFSBL_INCTV_RT IFSBL_INCTV_RT,
ewt84sprac.CRP_SIP_AUTH_IND CRP_SIP_AUTH_IND,
ewt84sprac.CRP_SIP_RT CRP_SIP_RT,
ewt84sprac.PIP_AUTH_IND PIP_AUTH_IND,
ewt84sprac.PIP_RT PIP_RT,
ewt84sprac.CPLD_PRAC_IND CPLD_PRAC_IND,
ewt84sprac.WL_RSTR_INCTV_RT WL_RSTR_INCTV_RT,
ewt84sprac.PRAC_WL_RSTR_INCTV PRAC_WL_RSTR_INCTV,
ewt84sprac.MAX_CNSR_ACRG MAX_CNSR_ACRG,
ewt84sprac.MAX_BDGT_AMT MAX_BDGT_AMT,
ewt84sprac.prac_min_lfsp_ct PRAC_MIN_LFSP_CT,
ewt84sprac.prac_max_lfsp_ct PRAC_MAX_LFSP_CT,
ewt84sprac.pvt_irr_crnr_ind PVT_IRR_CRNR_IND,
ewt84sprac.ncpld_prac_ind NONCROPLAND_PRAC_IND,
ewt84sprac.SGNP_ID SGNP_ID,
ewt84sprac.DATA_STAT_CD DATA_STAT_CD,
ewt84sprac.CRE_DT CRE_DT,
ewt84sprac.LAST_CHG_DT LAST_CHG_DT,
ewt84sprac.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ewt84sprac.OPYMT_ALOW_IND OPYMT_ALOW_IND,
-- op,
1 AS row_num_part
FROM "fsa-prod-cnsv".ewt84sprac
-- WHERE __CDC_OPERATION = 'D'