-- Julia Lu edition - will update this paragraph and query when (cnsv/ccms)-cdc is ready
-- Stage SQL: CNSV_CAT_CNFG (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_CAT_CNFG/incremental/CNSV_CAT_CNFG.sql
-- =============================================================================
SELECT * FROM
(
SELECT DISTINCT CAT_CNFG_ID,
CPNT_CAT_ID,
CPNT_SUB_CAT_ID,
CPNT_CAT_NM,
CPNT_SUB_CAT_CD,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CAT_CNFG_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
CATEGORY_CONFIGURATION.CAT_CNFG_ID CAT_CNFG_ID,
CATEGORY_CONFIGURATION.CPNT_CAT_ID CPNT_CAT_ID,
CATEGORY_CONFIGURATION.CPNT_SUB_CAT_ID CPNT_SUB_CAT_ID,
COMPONENT_CATEGORY.CPNT_CAT_NM CPNT_CAT_NM,
COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_CD CPNT_SUB_CAT_CD,
CATEGORY_CONFIGURATION.DATA_STAT_CD DATA_STAT_CD,
CATEGORY_CONFIGURATION.CRE_DT CRE_DT,
CATEGORY_CONFIGURATION.LAST_CHG_DT LAST_CHG_DT,
CATEGORY_CONFIGURATION.LAST_CHG_USER_NM LAST_CHG_USER_NM,
CATEGORY_CONFIGURATION.op,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".CATEGORY_CONFIGURATION LEFT JOIN "fsa-{env}-cnsv-cdc".COMPONENT_SUB_CATEGORY ON ( CATEGORY_CONFIGURATION.CPNT_SUB_CAT_ID = COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_ID) LEFT JOIN "fsa-{env}-cnsv-cdc".COMPONENT_CATEGORY ON ( CATEGORY_CONFIGURATION.CPNT_CAT_ID = COMPONENT_CATEGORY.CPNT_CAT_ID) 
WHERE CATEGORY_CONFIGURATION.op <> 'D'

UNION
SELECT 
CATEGORY_CONFIGURATION.CAT_CNFG_ID CAT_CNFG_ID,
CATEGORY_CONFIGURATION.CPNT_CAT_ID CPNT_CAT_ID,
CATEGORY_CONFIGURATION.CPNT_SUB_CAT_ID CPNT_SUB_CAT_ID,
COMPONENT_CATEGORY.CPNT_CAT_NM CPNT_CAT_NM,
COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_CD CPNT_SUB_CAT_CD,
CATEGORY_CONFIGURATION.DATA_STAT_CD DATA_STAT_CD,
CATEGORY_CONFIGURATION.CRE_DT CRE_DT,
CATEGORY_CONFIGURATION.LAST_CHG_DT LAST_CHG_DT,
CATEGORY_CONFIGURATION.LAST_CHG_USER_NM LAST_CHG_USER_NM,
COMPONENT_SUB_CATEGORY.op,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".COMPONENT_SUB_CATEGORY JOIN "fsa-{env}-cnsv-cdc".CATEGORY_CONFIGURATION ON ( CATEGORY_CONFIGURATION.CPNT_SUB_CAT_ID = COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_ID) LEFT JOIN "fsa-{env}-cnsv-cdc".COMPONENT_CATEGORY ON ( CATEGORY_CONFIGURATION.CPNT_CAT_ID = COMPONENT_CATEGORY.CPNT_CAT_ID) WHERE COMPONENT_SUB_CATEGORY.op <> 'D'

UNION
SELECT 
CATEGORY_CONFIGURATION.CAT_CNFG_ID CAT_CNFG_ID,
CATEGORY_CONFIGURATION.CPNT_CAT_ID CPNT_CAT_ID,
CATEGORY_CONFIGURATION.CPNT_SUB_CAT_ID CPNT_SUB_CAT_ID,
COMPONENT_CATEGORY.CPNT_CAT_NM CPNT_CAT_NM,
COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_CD CPNT_SUB_CAT_CD,
CATEGORY_CONFIGURATION.DATA_STAT_CD DATA_STAT_CD,
CATEGORY_CONFIGURATION.CRE_DT CRE_DT,
CATEGORY_CONFIGURATION.LAST_CHG_DT LAST_CHG_DT,
CATEGORY_CONFIGURATION.LAST_CHG_USER_NM LAST_CHG_USER_NM,
COMPONENT_CATEGORY.op,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".COMPONENT_CATEGORY JOIN "fsa-{env}-cnsv-cdc".CATEGORY_CONFIGURATION ON ( CATEGORY_CONFIGURATION.CPNT_CAT_ID = COMPONENT_CATEGORY.CPNT_CAT_ID) LEFT JOIN "fsa-{env}-cnsv-cdc".COMPONENT_SUB_CATEGORY ON ( CATEGORY_CONFIGURATION.CPNT_SUB_CAT_ID = COMPONENT_SUB_CATEGORY.CPNT_SUB_CAT_ID) 
WHERE COMPONENT_CATEGORY.op <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND CATEGORY_CONFIGURATION.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
CATEGORY_CONFIGURATION.CAT_CNFG_ID CAT_CNFG_ID,
CATEGORY_CONFIGURATION.CPNT_CAT_ID CPNT_CAT_ID,
CATEGORY_CONFIGURATION.CPNT_SUB_CAT_ID CPNT_SUB_CAT_ID,
NULL CPNT_CAT_NM,
NULL CPNT_SUB_CAT_CD,
CATEGORY_CONFIGURATION.DATA_STAT_CD DATA_STAT_CD,
CATEGORY_CONFIGURATION.CRE_DT CRE_DT,
CATEGORY_CONFIGURATION.LAST_CHG_DT LAST_CHG_DT,
CATEGORY_CONFIGURATION.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".CATEGORY_CONFIGURATION
WHERE CATEGORY_CONFIGURATION.op = 'D'