Select /*+ parallel (12) */
 DV.PYMT_ATRB_ID,
 DV.PRPS_PYMT_ID,
 DV.PRV_PRPS_PYMT_ID,
 DV.PRNT_PYMT_ATRB_ID,
 DV.AGI_ERR_REF_CD,
 DV.BUS_TYPE_CD,
 DV.CASH_RENT_CPLD_FCTR,
 DV.CMB_PTY_PYMT_SHR_PCT,
 DV.MBR_CTRB_SHR_PCT,
 DV.MBR_SHR_PCT,
 DV.NET_PYMT_AMT,
 DV.OWNSHP_HRCH_LVL_SHR_PCT,
 DV.PAID_PTY_SHR_PCT,
 DV.PGM_INELG_RSN_TYPE_CD,
 DV.PYMT_ATRB_AMT,
 DV.PYMT_ATRB_BUS_CAT_CD,
 DV.PYMT_ATRB_DATA_STAT_CD,
 DV.PYMT_ATRB_SHR_PCT,
 DV.PYMT_PTY_RLT_CD,
 DV.SRC_CRE_DT,
 DV.SRC_CRE_USER_NM,
 DV.SRC_LAST_CHG_DT,
 DV.SRC_LAST_CHG_USER_NM,
 DV.TAX_ID_TYPE_CD,
 DV.TOT_NET_PYMT_AMT,
 DV.TOT_PYMT_ATRB_AMT,
 DV.DATA_ACTN_DT,
 DV.LATEST_PYMT_ATRB_TXN_IND,
 DV.SBSD_PRD_STRT_YR,
 DV.PRPS_PYMT_AMT,
 DV.CMDY_CD,
 DV.PRPS_PYMT_DATA_STAT_CD,
 DV.OBL_CNFRM_NBR,
 DV.OVRRD_SBSD_PRD_STRT_YR,
 DV.PROC_RQST_REF_NBR,
 DV.PYMT_ATRB_RVRS_DT,
 DV.AGI_ELG_IND,
 DV.FGN_PRSN_ELG_IND,
 DV.MBR_CTRB_ELG_IND,
 DV.PMIT_ENTY_ELG_IND,
 DV.SBST_CHG_ELG_IND,
 DV.APP_3_OWNSHP_LVL_LMT_IND,
 DV.HRCH_PYMT_LMT_IND,
 DV.PRST_OPYMT_ATRB_IND,
 DV.PYMT_LMT_IND,
 DV.PYMT_LMT_YR,
 DV.RCD_REF_PRIM_ID,
 DV.RCD_REF_SCND_ID,
 DV.LTD_PYMT_PGM_DURB_ID,
 DV.LTD_PYMT_PGM_SRGT_ID,
 DV.ACCT_REF_PRIM_ID_TYPE_DURB_ID,
 DV.ACCT_REF_SCND_ID_TYPE_DURB_ID,
 DV.ACCT_PGM_DURB_ID,
 DV.FSA_ST_CNTY_DURB_ID,
 DV.FSA_ST_CNTY_SRGT_ID,
 DV.CUST_DURB_ID,
 DV.CUST_SRGT_ID,
 DV.RPT_FSA_ST_CNTY_SRGT_ID,
 DV.RPT_FSA_ST_CNTY_DURB_ID,
TO_TIMESTAMP ('{ETL_START_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF') CRE_DT, 
TO_TIMESTAMP ('{ETL_START_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF') LAST_CHG_DT,
'A' DATA_STAT_CD,
CASE
   WHEN 
       DV.PYMT_ATRB_ID IS NOT NULL
       AND DV.PRPS_PYMT_ID IS NOT NULL
   THEN 0
   ELSE 1 
   END DEF_ERR_IND ,
MD5(DV.PYMT_ATRB_ID||'~~'||DV.PRPS_PYMT_ID||'~~'|| (DV.DATA_ACTN_DT,TO_TIMESTAMP ('1900-01-01 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF'))) BUS_KEY,
 /*used by DS job to detect multiple BK records (for single AK field, no hashing required) */
 ('PYMT_ATRB_ID:'||DV.PYMT_ATRB_ID||'~~'||'PRPS_PYMT_ID:'||DV.PRPS_PYMT_ID||'~~'||'DATA_ACTN_DT:'||DV.DATA_ACTN_DT ) BUS_KEY_ERR
From (

SELECT DV_ALL.* FROM 
 (

Select 
 DV_DR.PYMT_ATRB_ID,
 DV_DR.PRPS_PYMT_ID,
 DIR_ATRB_PRPS_PYMT_LS.PRV_PRPS_PYMT_ID,
 DV_DR.PRNT_PYMT_ATRB_ID,
 DV_DR.AGI_ERR_REF_CD,
 DV_DR.BUS_TYPE_CD,
 DV_DR.CASH_RENT_CPLD_FCTR,
 DV_DR.CMB_PTY_PYMT_SHR_PCT,
 DV_DR.MBR_CTRB_SHR_PCT,
 DV_DR.MBR_SHR_PCT,
 DV_DR.NET_PYMT_AMT,
 DV_DR.OWNSHP_HRCH_LVL_SHR_PCT,
 DV_DR.PAID_PTY_SHR_PCT,
 DV_DR.PGM_INELG_RSN_TYPE_CD,
 DV_DR.PYMT_ATRB_AMT,
 DV_DR.PYMT_ATRB_BUS_CAT_CD,
 DV_DR.DATA_STAT_CD PYMT_ATRB_DATA_STAT_CD,
 DV_DR.PYMT_ATRB_SHR_PCT,
 DV_DR.PYMT_PTY_RLT_CD,
 DV_DR.SRC_CRE_DT,
 DV_DR.SRC_CRE_USER_NM,
 DV_DR.SRC_LAST_CHG_DT,
 DV_DR.SRC_LAST_CHG_USER_NM,
 DV_DR.TAX_ID_TYPE_CD,
 DV_DR.TOT_NET_PYMT_AMT,
 DV_DR.TOT_PYMT_ATRB_AMT,
 DV_DR.DATA_ACTN_DT,
 case (TO_CHAR(DV_DR.DATA_ACTN_DT),0) when  '0' Then 1 when NULL then 1  else  0 End As LATEST_PYMT_ATRB_TXN_IND,
 (PGM_YR_DIM.PGM_YR,-1) SBSD_PRD_STRT_YR,
 DIR_ATRB_PRPS_PYMT_LS.PYMT_AMT PRPS_PYMT_AMT,
 DIR_ATRB_PRPS_PYMT_LS.CMDY_CD,
 DIR_ATRB_PRPS_PYMT_LS.DATA_STAT_CD PRPS_PYMT_DATA_STAT_CD,
 DIR_ATRB_PRPS_PYMT_LS.OBL_CNFRM_NBR,
 DIR_ATRB_PRPS_PYMT_LS.OVRRD_SBSD_PRD_STRT_YR,
 DIR_ATRB_PRPS_PYMT_LS.PROC_RQST_REF_NBR,
 DIR_ATRB_PRPS_PYMT_LS.PYMT_ATRB_RVRS_DT,
 Case UPPER(DV_DR.AGI_ELG_IND)  when 'Y' Then 1  when 'N' Then 0 else -1 END AS AGI_ELG_IND,
 Case UPPER(DV_DR.FGN_PRSN_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS FGN_PRSN_ELG_IND,
 Case UPPER(DV_DR.MBR_CTRB_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS MBR_CTRB_ELG_IND,
 Case UPPER(DV_DR.PMIT_ENTY_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS PMIT_ENTY_ELG_IND,
 Case UPPER(DV_DR.SBST_CHG_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS SBST_CHG_ELG_IND,
 Case UPPER(DIR_ATRB_PRPS_PYMT_LS.APP_3_OWNSHP_LVL_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS APP_3_OWNSHP_LVL_LMT_IND,
 Case UPPER(DIR_ATRB_PRPS_PYMT_LS.HRCH_PYMT_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS HRCH_PYMT_LMT_IND,
 Case  UPPER(DIR_ATRB_PRPS_PYMT_LS.PRST_OPYMT_ATRB_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS PRST_OPYMT_ATRB_IND,
 Case UPPER(DIR_ATRB_PRPS_PYMT_LS.PYMT_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS PYMT_LMT_IND,
 DIR_ATRB_PRPS_PYMT_LS.PYMT_LMT_YR,
 DIR_ATRB_PRPS_PYMT_LS.RCD_REF_PRIM_ID,
 DIR_ATRB_PRPS_PYMT_LS.RCD_REF_SCND_ID,
 (LTD_PYMT_PGM_DIM.LTD_PYMT_PGM_DURB_ID,-3) LTD_PYMT_PGM_DURB_ID,
 (LTD_PYMT_PGM_DIM.LTD_PYMT_PGM_SRGT_ID,-3) LTD_PYMT_PGM_SRGT_ID,
 (ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_TYPE_DURB_ID,-3) ACCT_REF_PRIM_ID_TYPE_DURB_ID,
 (ACCT_REF_TYPE_SCND_DIM.ACCT_REF_TYPE_DURB_ID,-3) ACCT_REF_SCND_ID_TYPE_DURB_ID,
 (ACCT_PGM_DIM.ACCT_PGM_DURB_ID,-3) ACCT_PGM_DURB_ID,
 (FSA_ST_CNTY_DIM.FSA_ST_CNTY_DURB_ID,-3) FSA_ST_CNTY_DURB_ID,
 (FSA_ST_CNTY_DIM.FSA_ST_CNTY_SRGT_ID,-3) FSA_ST_CNTY_SRGT_ID,
 (CUST_DIM.CUST_DURB_ID,-3) CUST_DURB_ID,
 (CUST_DIM.CUST_SRGT_ID,-3) CUST_SRGT_ID,
 (RPT_FSA_ST_CNTY_DIM.RPT_FSA_ST_CNTY_SRGT_ID,-3) RPT_FSA_ST_CNTY_SRGT_ID,
 (RPT_FSA_ST_CNTY_DIM.RPT_FSA_ST_CNTY_DURB_ID,-3) RPT_FSA_ST_CNTY_DURB_ID,

 RANK() over ( partition by  DV_DR.PYMT_ATRB_ID,    DV_DR.PRPS_PYMT_ID   , (DV_DR.DATA_ACTN_DT,TO_TIMESTAMP ('1900-01-01 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF') ) Order by DATA_ACTN_DT asc,
         CASE DV_DR.DATA_STAT_CD
         WHEN 'A' THEN 1
         WHEN 'I' THEN 2
         WHEN 'D' THEN 3
         ELSE 4
         END ASC,
      DV_DR.SRC_CRE_DT DESC NULLS LAST
       )  as Rank_Part

FROM
(
SELECT   PYMT_ATRB_ID,
         PRPS_PYMT_ID,
         PRNT_PYMT_ATRB_ID,
         AGI_ELG_IND,
         AGI_ERR_REF_CD,
         BUS_TYPE_CD,
         CASH_RENT_CPLD_FCTR,
         CMB_PTY_PYMT_SHR_PCT,
         FGN_PRSN_ELG_IND,
         MBR_CTRB_ELG_IND,
         MBR_CTRB_SHR_PCT,
         MBR_SHR_PCT,
         NET_PYMT_AMT,
         OWNSHP_HRCH_LVL_SHR_PCT,
         PAID_PTY_SHR_PCT,
         PGM_INELG_RSN_TYPE_CD,
         PMIT_ENTY_ELG_IND,
         PYMT_ATRB_AMT,
         PYMT_ATRB_BUS_CAT_CD,
         PYMT_ATRB_SHR_PCT,
         PYMT_PTY_RLT_CD,
         SBST_CHG_ELG_IND,
         SRC_CRE_DT,
         SRC_CRE_USER_NM,
         SRC_LAST_CHG_DT,
         SRC_LAST_CHG_USER_NM,
         TAX_ID_TYPE_CD,
         TOT_NET_PYMT_AMT,
         TOT_PYMT_ATRB_AMT,
         DATA_STAT_CD,
         TO_TIMESTAMP ('', 'YYYY:MM:DD HH:MM;SS.FF') DATA_ACTN_DT
  FROM   EDV.PYMT_ATRB_LS
 WHERE    (DATA_EFF_END_DT) = TO_TIMESTAMP ('9999-12-31', 'YYYY-MM-DD') 
         AND (DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
         --AND PRPS_PYMT_ID IN (260300, 985150, 8981182, 836100)
UNION
SELECT   PYMT_ATRB_ID,
         PRPS_PYMT_ID,
         PRNT_PYMT_ATRB_ID,
         AGI_ELG_IND,
         AGI_ERR_REF_CD,
         BUS_TYPE_CD,
         CASH_RENT_CPLD_FCTR,
         CMB_PTY_PYMT_SHR_PCT,
         FGN_PRSN_ELG_IND,
         MBR_CTRB_ELG_IND,
         MBR_CTRB_SHR_PCT,
         MBR_SHR_PCT,
         NET_PYMT_AMT,
         OWNSHP_HRCH_LVL_SHR_PCT,
         PAID_PTY_SHR_PCT,
         PGM_INELG_RSN_TYPE_CD,
         PMIT_ENTY_ELG_IND,
         PYMT_ATRB_AMT,
         PYMT_ATRB_BUS_CAT_CD,
         PYMT_ATRB_SHR_PCT,
         PYMT_PTY_RLT_CD,
         SBST_CHG_ELG_IND,
         SRC_CRE_DT,
         SRC_CRE_USER_NM,
         SRC_LAST_CHG_DT,
         SRC_LAST_CHG_USER_NM,
         TAX_ID_TYPE_CD,
         TOT_NET_PYMT_AMT,
         TOT_PYMT_ATRB_AMT,
         DATA_STAT_CD,
         PR_PYMT_ATRB_LS.DATA_ACTN_DT
  FROM   EDV.PR_PYMT_ATRB_LS
 WHERE    (DATA_EFF_END_DT) = TO_TIMESTAMP ('9999-12-31', 'YYYY-MM-DD') 
          AND (DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
         --AND PRPS_PYMT_ID IN (260300, 985150, 8981182, 836100)
) DV_DR

 Left JOIN
 (
    
     Select * From EDV.DIR_ATRB_PRPS_PYMT_LS  
     where (DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
           AND (DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')          
          --And PRPS_PYMT_ID IN (260300,985150,8981182,836100)
 ) DIR_ATRB_PRPS_PYMT_LS
ON (DV_DR.PRPS_PYMT_ID =DIR_ATRB_PRPS_PYMT_LS.PRPS_PYMT_ID)

Left Join EDV.PYMT_PGM_RS
  ON ( DIR_ATRB_PRPS_PYMT_LS.PYMT_PGM_ID = PYMT_PGM_RS.PYMT_PGM_ID And  (PYMT_PGM_RS.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )
   
  Left Join PYMT_DM.LTD_PYMT_PGM_DIM
  ON ( PYMT_PGM_RS.PYMT_PGM_NM = LTD_PYMT_PGM_NM And  (LTD_PYMT_PGM_DIM.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )
  
Left Join PYMT_DM.ACCT_REF_TYPE_DIM  ACCT_REF_TYPE_PRIM_DIM
  ON (DIR_ATRB_PRPS_PYMT_LS.RCD_REF_PRIM_ID_TYPE_CD =ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_CD And ACCT_REF_TYPE_PRIM_DIM.DATA_STAT_CD ='A' And ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_TYPE_DURB_ID > 0 )
  
  
  Left Join PYMT_DM.ACCT_REF_TYPE_DIM  ACCT_REF_TYPE_SCND_DIM
  ON( DIR_ATRB_PRPS_PYMT_LS.RCD_REF_SCND_ID_TYPE_CD =ACCT_REF_TYPE_SCND_DIM.ACCT_REF_CD And ACCT_REF_TYPE_SCND_DIM.DATA_STAT_CD ='A' And ACCT_REF_TYPE_SCND_DIM.ACCT_REF_TYPE_DURB_ID > 0)
  
  Left Join CMN_DIM_DM.ACCT_PGM_DIM
  ON  ( DIR_ATRB_PRPS_PYMT_LS.ACCT_PGM_CD = ACCT_PGM_DIM.ACCT_PGM_CD And ACCT_PGM_DIM.DATA_STAT_CD ='A')
    
  LEFT  JOIN 
   (
        SELECT FSA_ST_CNTY_SRGT_ID,FSA_ST_CNTY_DURB_ID ,ST_FSA_CD ,CNTY_FSA_CD,ST_NM,CNTY_NM
        ,ROW_NUMBER() OVER ( PARTITION BY ST_FSA_CD  ,CNTY_FSA_CD ORDER BY CRE_DT DESC
        ) AS PRECEDENCE
        FROM CMN_DIM_DM.FSA_ST_CNTY_DIM
        WHERE CUR_RCD_IND = 1
   ) FSA_ST_CNTY_DIM 
  ON ( DIR_ATRB_PRPS_PYMT_LS.ST_FSA_CD=FSA_ST_CNTY_DIM.ST_FSA_CD   And DIR_ATRB_PRPS_PYMT_LS.CNTY_FSA_CD = FSA_ST_CNTY_DIM.CNTY_FSA_CD AND FSA_ST_CNTY_DIM.PRECEDENCE = 1 )  

  Left join CMN_DIM_DM.CUST_DIM 
  On ( DIR_ATRB_PRPS_PYMT_LS.PAID_CORE_CUST_ID = CUST_DIM.CORE_CUST_ID  And CUST_DIM.CUR_RCD_IND =1 And (CUST_DIM.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') ) 
        
  Left Join 
   (
           Select * from (
        SELECT FSA_ST_CNTY_SRGT_ID RPT_FSA_ST_CNTY_SRGT_ID ,FSA_ST_CNTY_DURB_ID RPT_FSA_ST_CNTY_DURB_ID ,ST_FSA_CD ,CNTY_FSA_CD,ST_NM,CNTY_NM
        ,ROW_NUMBER() OVER ( PARTITION BY ST_FSA_CD  ,CNTY_FSA_CD ORDER BY CRE_DT DESC) AS PRECEDENCE
        FROM CMN_DIM_DM.FSA_ST_CNTY_DIM
        WHERE CUR_RCD_IND = 1   ) FSA_ST_CNTY_DIM JOIN CMN_DIM_DM.CUST_DIM  
                ON (FSA_ST_CNTY_DIM.ST_FSA_CD = CUST_DIM.RPT_ST_FSA_CD And FSA_ST_CNTY_DIM.CNTY_FSA_CD = CUST_DIM.RPT_CNTY_FSA_CD
                And   (CUST_DIM.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')                 And  FSA_ST_CNTY_DIM.PRECEDENCE=1 
                    )
   ) RPT_FSA_ST_CNTY_DIM
  ON (DIR_ATRB_PRPS_PYMT_LS.PAID_CORE_CUST_ID= RPT_FSA_ST_CNTY_DIM.CORE_CUST_ID)


  Left Join CMN_DIM_DM.PGM_YR_DIM
  on (  DIR_ATRB_PRPS_PYMT_LS.SBSD_PRD_STRT_YR = PGM_YR_DIM.PGM_YR And PGM_YR_DIM.DATA_STAT_CD ='A')
  
  Order by  DV_DR.PYMT_ATRB_ID,  DV_DR.PRPS_PYMT_ID asc
    ) DV_ALL
   WHERE DV_ALL.Rank_Part = 1 
 ) dv 
 /*
 LEFT JOIN  PYMT_DM.DA_PRIM_CUST_ATRB_TXN_FACT dm
  on (
  (dv.PYMT_ATRB_ID,0) = (dm.PYMT_ATRB_ID,0)
  And (dv.PRPS_PYMT_ID,0) = (dm.PRPS_PYMT_ID,0)
  And (DV.DATA_ACTN_DT,TO_TIMESTAMP ('1900-01-01 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF') ) = (dm.DATA_ACTN_DT,TO_TIMESTAMP ('1900-01-01 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF') )
  And dm.DATA_STAT_CD = 'A' 
 ) 
 where
  (
   dm.PYMT_ATRB_ID IS NULL 
   And dm.PRPS_PYMT_ID is Null
   And dm.DATA_ACTN_DT is NUll
  ) */
 ORDER BY BUS_KEY  asc 