Merge into
EDV.IRR_CNTY_CROP_LS dv
using(select DISTINCT MD5(upper(coalesce(trim(both IRR_CNTY_CROP.PGM_ABR), '--') ||'~~'||coalesce(trim(both IRR_CNTY_CROP.FSA_CROP_CD), '--') ||'~~'||coalesce(trim(both IRR_CNTY_CROP.FSA_CROP_TYPE_CD), '--') ||'~~'||coalesce(trim(both IRR_CNTY_CROP.ST_FSA_CD), '--') ||'~~'||coalesce(trim(both IRR_CNTY_CROP.CNTY_FSA_CD), '--') )) as IRR_CNTY_CROP_L_ID,IRR_CNTY_CROP.IRR_CNTY_CROP_ID IRR_CNTY_CROP_ID,IRR_CNTY_CROP.LOAD_DT LOAD_DT,IRR_CNTY_CROP.CDC_DT DATA_EFF_STRT_DT,IRR_CNTY_CROP.DATA_SRC_NM DATA_SRC_NM,IRR_CNTY_CROP.DATA_STAT_CD DATA_STAT_CD,IRR_CNTY_CROP.CRE_DT SRC_CRE_DT,IRR_CNTY_CROP.CRE_USER_NM SRC_CRE_USER_NM,IRR_CNTY_CROP.LAST_CHG_DT SRC_LAST_CHG_DT,IRR_CNTY_CROP.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,IRR_CNTY_CROP.CNTY_OFC_CTL_ID CNTY_OFC_CTL_ID,IRR_CNTY_CROP.CROP_ID CROP_ID ,
IRR_CNTY_CROP.CDC_OPER_CD,
MD5(trim(both IRR_CNTY_CROP.PGM_ABR)||'~~'||trim(both IRR_CNTY_CROP.FSA_CROP_CD)||'~~'||trim(both IRR_CNTY_CROP.FSA_CROP_TYPE_CD)||'~~'||trim(both IRR_CNTY_CROP.ST_FSA_CD)||'~~'||trim(both IRR_CNTY_CROP.CNTY_FSA_CD)||'~~'||IRR_CNTY_CROP.IRR_CNTY_CROP_ID||'~~'||trim(both IRR_CNTY_CROP.DATA_STAT_CD)||'~~'||to_char(IRR_CNTY_CROP.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both IRR_CNTY_CROP.CRE_USER_NM)||'~~'||to_char(IRR_CNTY_CROP.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both IRR_CNTY_CROP.LAST_CHG_USER_NM)||'~~'||IRR_CNTY_CROP.CNTY_OFC_CTL_ID||'~~'||IRR_CNTY_CROP.CROP_ID) HASH_DIF
FROM SQL_FARM_RCD_STG.IRR_CNTY_CROP  IRR_CNTY_CROP
 where IRR_CNTY_CROP.CDC_OPER_CD='D'
--and date_trunc('day', IRR_CNTY_CROP.CDC_DT) = date_trunc('day', TO_TIMESTAMP('<DATA_EFF_STRT_DT>', 'YYYY-MM-DD HH24:MI:SS.FF'))
--and IRR_CNTY_CROP.LOAD_DT = TO_TIMESTAMP('<LOAD_DT>', 'YYYY-MM-DD HH24:MI:SS.FF')
order by IRR_CNTY_CROP.CDC_DT)
stg
 on ( 
coalesce(stg.IRR_CNTY_CROP_ID,0) = coalesce(dv.IRR_CNTY_CROP_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN
INSERT(
IRR_CNTY_CROP_L_ID,IRR_CNTY_CROP_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_CRE_USER_NM,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
CNTY_OFC_CTL_ID,
CROP_ID, 
DATA_EFF_END_DT,LOAD_END_DT,HASH_DIF)
VALUES (
stg.IRR_CNTY_CROP_L_ID,stg.IRR_CNTY_CROP_ID,stg.LOAD_DT,stg.DATA_EFF_STRT_DT,stg.DATA_SRC_NM,stg.DATA_STAT_CD,stg.SRC_CRE_DT,stg.SRC_CRE_USER_NM,stg.SRC_LAST_CHG_DT,stg.SRC_LAST_CHG_USER_NM,stg.CNTY_OFC_CTL_ID,stg.CROP_ID,stg.DATA_EFF_STRT_DT,stg.LOAD_DT,
stg.HASH_DIF
);