INSERT into
EDV.TR_H(TR_H_ID ,
ST_FSA_CD,
CNTY_FSA_CD,
TR_NBR,
LOAD_DT,
DATA_SRC_NM)
(
select distinct sub.TR_H_ID,
sub.ST_FSA_CD,
sub.CNTY_FSA_CD,
sub.TR_NBR,
MAX(sub.LOAD_DT) as LOAD_DT,
sub.DATA_SRC_NM
from
(
SELECT distinct stg.TR_H_ID,
stg.ST_FSA_CD,
stg.CNTY_FSA_CD,
(stg.TR_NBR):: numeric,
stg.LOAD_DT,
stg.DATA_SRC_NM
from (
(
SELECT DISTINCT
MD5(upper(coalesce(trim(both TR.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both TR.CNTY_FSA_CD), '--')) ||'~~'||coalesce((trim(both TR.TR_NBR))::numeric , -1) ) TR_H_ID,
coalesce(TR.ST_FSA_CD,'--') ST_FSA_CD,
coalesce(TR.CNTY_FSA_CD , '--') CNTY_FSA_CD,
coalesce(TR.TR_NBR,'-1') TR_NBR,
TR.LOAD_DT LOAD_DT,
TR.DATA_SRC_NM DATA_SRC_NM,
TR.ST_FSA_CD SK_COL1,
TR.CNTY_FSA_CD SK_COL2,
TR.TR_NBR SK_COL3,
ROW_NUMBER() OVER (PARTITION BY TR.ST_FSA_CD,TR.CNTY_FSA_CD,(TR.TR_NBR)::numeric  ORDER BY TR.CDC_DT desc, TR.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.TR
WHERE TR.cdc_oper_cd IN ('I','UN','D')


UNION


SELECT DISTINCT
MD5(upper(coalesce(trim(both MIDAS_FARM_TR_CHG.PRNT_ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both MIDAS_FARM_TR_CHG.PRNT_CNTY_FSA_CD), '--')) ||'~~'||coalesce((trim(both MIDAS_FARM_TR_CHG.PRNT_TR_NBR))::numeric , -1) ) TR_H_ID,
coalesce(MIDAS_FARM_TR_CHG.PRNT_ST_FSA_CD,'--') ST_FSA_CD,
coalesce(MIDAS_FARM_TR_CHG.PRNT_CNTY_FSA_CD , '--') CNTY_FSA_CD,
coalesce(MIDAS_FARM_TR_CHG.PRNT_TR_NBR,'-1') TR_NBR,
MIDAS_FARM_TR_CHG.LOAD_DT LOAD_DT,
MIDAS_FARM_TR_CHG.DATA_SRC_NM DATA_SRC_NM,
MIDAS_FARM_TR_CHG.PRNT_ST_FSA_CD SK_COL1,
MIDAS_FARM_TR_CHG.PRNT_CNTY_FSA_CD SK_COL2,
MIDAS_FARM_TR_CHG.PRNT_TR_NBR SK_COL3,
ROW_NUMBER() OVER (PARTITION BY MIDAS_FARM_TR_CHG.PRNT_ST_FSA_CD,MIDAS_FARM_TR_CHG.PRNT_CNTY_FSA_CD,(MIDAS_FARM_TR_CHG.PRNT_TR_NBR)::numeric  ORDER BY MIDAS_FARM_TR_CHG.CDC_DT desc, MIDAS_FARM_TR_CHG.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.MIDAS_FARM_TR_CHG
WHERE MIDAS_FARM_TR_CHG.cdc_oper_cd IN ('I','UN','D')

)

UNION


SELECT DISTINCT
MD5(upper(coalesce(trim(both MIDAS_FARM_TR_CHG.RSLT_ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both MIDAS_FARM_TR_CHG.RSLT_CNTY_FSA_CD), '--')) ||'~~'||coalesce((trim(both MIDAS_FARM_TR_CHG.RSLT_TR_NBR))::numeric , -1) ) TR_H_ID,
coalesce(MIDAS_FARM_TR_CHG.RSLT_ST_FSA_CD,'--') ST_FSA_CD,
coalesce(MIDAS_FARM_TR_CHG.RSLT_CNTY_FSA_CD , '--') CNTY_FSA_CD,
coalesce(MIDAS_FARM_TR_CHG.RSLT_TR_NBR,'-1') TR_NBR,
MIDAS_FARM_TR_CHG.LOAD_DT LOAD_DT,
MIDAS_FARM_TR_CHG.DATA_SRC_NM DATA_SRC_NM,
MIDAS_FARM_TR_CHG.RSLT_ST_FSA_CD SK_COL1,
MIDAS_FARM_TR_CHG.RSLT_CNTY_FSA_CD SK_COL2,
MIDAS_FARM_TR_CHG.RSLT_TR_NBR SK_COL3,
ROW_NUMBER() OVER (PARTITION BY MIDAS_FARM_TR_CHG.RSLT_ST_FSA_CD,MIDAS_FARM_TR_CHG.RSLT_CNTY_FSA_CD,(MIDAS_FARM_TR_CHG.RSLT_TR_NBR)::numeric  ORDER BY MIDAS_FARM_TR_CHG.CDC_DT desc, MIDAS_FARM_TR_CHG.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.MIDAS_FARM_TR_CHG
WHERE MIDAS_FARM_TR_CHG.cdc_oper_cd IN ('I','UN','D')
) stg 
LEFT JOIN  EDV.TR_H dv
 ON (
stg.TR_H_ID = dv.TR_H_ID
)
where dv.TR_H_ID IS NULL
and stg.STG_EFF_DT_RANK = 1
) sub
where not exists (select 1 from EDV.TR_H h
                  where sub.TR_H_ID = h.TR_H_ID
				  AND sub.ST_FSA_CD = h.ST_FSA_CD
				  AND sub.CNTY_FSA_CD = h.CNTY_FSA_CD
				  AND sub.TR_NBR = h.TR_NBR
				  AND sub.LOAD_DT = h.LOAD_DT
				  AND sub.DATA_SRC_NM = h.DATA_SRC_NM
				  )
group by 
sub.TR_H_ID,
sub.ST_FSA_CD,
sub.CNTY_FSA_CD,
sub.TR_NBR,
sub.DATA_SRC_NM
);