MERGE INTO EDV.PR_PYMT_ATRB_MBR_HLS dv USING
  (SELECT DISTINCT MD5 (upper(COALESCE (trim(PYMT_ATRB_AUD.ST_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(PYMT_ATRB_AUD.CNTY_FSA_CD), '--')) ||'~~'||upper(COALESCE (trim(PYMT_ATRB_AUD.PRPS_PYMT_ACCT_PGM_CD), '--')) ||'~~'||COALESCE (PYMT_ATRB_AUD.MBR_CORE_CUST_ID, '-1') ||'~~'||COALESCE (PYMT_ATRB_AUD.PRNT_PYMT_ATRB_CORE_CUST_ID, '-1') ||'~~'||COALESCE (PYMT_ATRB_AUD.PAID_CORE_CUST_ID, '-1')) AS PYMT_ATRB_MBR_HL_ID,
                   coalesce(PYMT_ATRB_AUD.PYMT_ATRB_ID, '-1') PYMT_ATRB_ID,
                   PYMT_ATRB_AUD.DATA_ACTN_DT DATA_ACTN_DT,
                   coalesce(PYMT_ATRB_AUD.PRPS_PYMT_ID, '-1') PRPS_PYMT_ID,
                   PYMT_ATRB_AUD.ACCT_PGM_CD ACCT_PGM_CD,
                   PYMT_ATRB_AUD.AGI_ELG_IND AGI_ELG_IND,
                   PYMT_ATRB_AUD.AGI_ERR_REF_CD AGI_ERR_REF_CD,
                   PYMT_ATRB_AUD.BUS_TYPE_CD BUS_TYPE_CD,
                   PYMT_ATRB_AUD.CASH_RENT_CPLD_FCTR CASH_RENT_CPLD_FCTR,
                   PYMT_ATRB_AUD.CMB_PTY_PYMT_SHR_PCT CMB_PTY_PYMT_SHR_PCT,
                   PYMT_ATRB_AUD.CNTY_FSA_CD CNTY_FSA_CD,
                   PYMT_ATRB_AUD.DATA_ACTN_CD DATA_ACTN_CD,
                   PYMT_ATRB_AUD.DATA_STAT_CD DATA_STAT_CD,
                   PYMT_ATRB_AUD.FGN_PRSN_ELG_IND FGN_PRSN_ELG_IND,
                   PYMT_ATRB_AUD.MBR_CORE_CUST_ID MBR_CORE_CUST_ID,
                   PYMT_ATRB_AUD.MBR_CTRB_ELG_IND MBR_CTRB_ELG_IND,
                   PYMT_ATRB_AUD.MBR_CTRB_SHR_PCT MBR_CTRB_SHR_PCT,
                   PYMT_ATRB_AUD.MBR_SHR_PCT MBR_SHR_PCT,
                   PYMT_ATRB_AUD.NET_PYMT_AMT NET_PYMT_AMT,
                   PYMT_ATRB_AUD.OWNSHP_HRCH_LVL_SHR_PCT OWNSHP_HRCH_LVL_SHR_PCT,
                   PYMT_ATRB_AUD.PAID_CORE_CUST_ID PAID_CORE_CUST_ID,
                   PYMT_ATRB_AUD.PAID_PTY_SHR_PCT PAID_PTY_SHR_PCT,
                   PYMT_ATRB_AUD.PAID_SBSD_CUST_ID PAID_SBSD_CUST_ID,
                   PYMT_ATRB_AUD.PGM_INELG_RSN_TYPE_CD PGM_INELG_RSN_TYPE_CD,
                   PYMT_ATRB_AUD.PMIT_ENTY_ELG_IND PMIT_ENTY_ELG_IND,
                   PYMT_ATRB_AUD.PRNT_PYMT_ATRB_ACCT_PGM_CD PRNT_PYMT_ATRB_ACCT_PGM_CD,
                   PYMT_ATRB_AUD.PRNT_PYMT_ATRB_CNTY_FSA_CD PRNT_PYMT_ATRB_CNTY_FSA_CD,
                   PYMT_ATRB_AUD.PRNT_PYMT_ATRB_CORE_CUST_ID PRNT_PYMT_ATRB_CORE_CUST_ID,
                   PYMT_ATRB_AUD.PRNT_PYMT_ATRB_ID PRNT_PYMT_ATRB_ID,
                   PYMT_ATRB_AUD.PRNT_SBSD_PRD_STRT_YR PRNT_PYMT_ATRB_SBSD_PRD_YR,
                   PYMT_ATRB_AUD.PRNT_PYMT_ATRB_ST_FSA_CD PRNT_PYMT_ATRB_ST_FSA_CD,
                   PYMT_ATRB_AUD.PRPS_PYMT_ACCT_PGM_CD PRPS_PYMT_ACCT_PGM_CD,
                   PYMT_ATRB_AUD.PRPS_PYMT_SBSD_PRD_STRT_YR PRPS_PYMT_SBSD_PRD_STRT_YR,
                   PYMT_ATRB_AUD.PYMT_ATRB_AMT PYMT_ATRB_AMT,
                   PYMT_ATRB_AUD.PYMT_ATRB_BUS_CAT_CD PYMT_ATRB_BUS_CAT_CD,
                   PYMT_ATRB_AUD.PYMT_ATRB_SHR_PCT PYMT_ATRB_SHR_PCT,
                   PYMT_ATRB_AUD.PYMT_LMT_YR PYMT_LMT_YR,
                   PYMT_ATRB_AUD.PYMT_PGM_ID PYMT_PGM_ID,
                   PYMT_ATRB_AUD.PYMT_PTY_RLT_CD PYMT_PTY_RLT_CD,
                   PYMT_ATRB_AUD.RCD_REF_PRIM_ID RCD_REF_PRIM_ID,
                   PYMT_ATRB_AUD.RCD_REF_PRIM_ID_TYPE_CD RCD_REF_PRIM_ID_TYPE_CD,
                   PYMT_ATRB_AUD.RCD_REF_SCND_ID RCD_REF_SCND_ID,
                   PYMT_ATRB_AUD.RCD_REF_SCND_ID_TYPE_CD RCD_REF_SCND_ID_TYPE_CD,
                   PYMT_ATRB_AUD.SBSD_CUST_ID SBSD_CUST_ID,
                   PYMT_ATRB_AUD.SBSD_PRD_STRT_YR SBSD_PRD_STRT_YR,
                   PYMT_ATRB_AUD.SBST_CHG_ELG_IND SBST_CHG_ELG_IND,
                   PYMT_ATRB_AUD.CRE_DT SRC_CRE_DT,
                   PYMT_ATRB_AUD.CRE_USER_NM SRC_CRE_USER_NM,
                   PYMT_ATRB_AUD.LAST_CHG_DT SRC_LAST_CHG_DT,
                   PYMT_ATRB_AUD.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
                   PYMT_ATRB_AUD.ST_FSA_CD ST_FSA_CD,
                   PYMT_ATRB_AUD.TAX_ID_TYPE_CD TAX_ID_TYPE_CD,
                   PYMT_ATRB_AUD.TOT_NET_PYMT_AMT TOT_NET_PYMT_AMT,
                   PYMT_ATRB_AUD.TOT_PYMT_ATRB_AMT TOT_PYMT_ATRB_AMT,
                   PYMT_ATRB_AUD.LOAD_DT LOAD_DT,
                   PYMT_ATRB_AUD.CDC_DT DATA_EFF_STRT_DT,
                   PYMT_ATRB_AUD.DATA_SRC_NM DATA_SRC_NM,
                   PYMT_ATRB_AUD.CDC_OPER_CD,
                   MD5 (trim(PYMT_ATRB_AUD.ST_FSA_CD)||'~~'||trim(PYMT_ATRB_AUD.CNTY_FSA_CD)||'~~'||trim(PYMT_ATRB_AUD.PRPS_PYMT_ACCT_PGM_CD)||'~~'||PYMT_ATRB_AUD.MBR_CORE_CUST_ID||'~~'||PYMT_ATRB_AUD.PRNT_PYMT_ATRB_CORE_CUST_ID||'~~'||PYMT_ATRB_AUD.PAID_CORE_CUST_ID||'~~'||PYMT_ATRB_AUD.PYMT_ATRB_ID||'~~'||trim(PYMT_ATRB_AUD.ACCT_PGM_CD)||'~~'||trim(PYMT_ATRB_AUD.AGI_ELG_IND)||'~~'||trim(PYMT_ATRB_AUD.AGI_ERR_REF_CD)||'~~'||trim(PYMT_ATRB_AUD.BUS_TYPE_CD)||'~~'||PYMT_ATRB_AUD.CASH_RENT_CPLD_FCTR||'~~'||PYMT_ATRB_AUD.CMB_PTY_PYMT_SHR_PCT||'~~'||trim(PYMT_ATRB_AUD.CNTY_FSA_CD)||'~~'||trim(PYMT_ATRB_AUD.DATA_ACTN_CD)||'~~'||to_char(PYMT_ATRB_AUD.DATA_ACTN_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PYMT_ATRB_AUD.DATA_STAT_CD)||'~~'||trim(PYMT_ATRB_AUD.FGN_PRSN_ELG_IND)||'~~'||PYMT_ATRB_AUD.MBR_CORE_CUST_ID||'~~'||trim(PYMT_ATRB_AUD.MBR_CTRB_ELG_IND)||'~~'||PYMT_ATRB_AUD.MBR_CTRB_SHR_PCT||'~~'||PYMT_ATRB_AUD.MBR_SHR_PCT||'~~'||PYMT_ATRB_AUD.NET_PYMT_AMT||'~~'||PYMT_ATRB_AUD.OWNSHP_HRCH_LVL_SHR_PCT||'~~'||PYMT_ATRB_AUD.PAID_CORE_CUST_ID||'~~'||PYMT_ATRB_AUD.PAID_PTY_SHR_PCT||'~~'||PYMT_ATRB_AUD.PAID_SBSD_CUST_ID||'~~'||trim(PYMT_ATRB_AUD.PGM_INELG_RSN_TYPE_CD)||'~~'||trim(PYMT_ATRB_AUD.PMIT_ENTY_ELG_IND)||'~~'||trim(PYMT_ATRB_AUD.PRNT_PYMT_ATRB_ACCT_PGM_CD)||'~~'||trim(PYMT_ATRB_AUD.PRNT_PYMT_ATRB_CNTY_FSA_CD)||'~~'||PYMT_ATRB_AUD.PRNT_PYMT_ATRB_CORE_CUST_ID||'~~'||PYMT_ATRB_AUD.PRNT_PYMT_ATRB_ID||'~~'||PYMT_ATRB_AUD.PRNT_SBSD_PRD_STRT_YR||'~~'||trim(PYMT_ATRB_AUD.PRNT_PYMT_ATRB_ST_FSA_CD)||'~~'||trim(PYMT_ATRB_AUD.PRPS_PYMT_ACCT_PGM_CD)||'~~'||PYMT_ATRB_AUD.PRPS_PYMT_ID||'~~'||PYMT_ATRB_AUD.PRPS_PYMT_SBSD_PRD_STRT_YR||'~~'||PYMT_ATRB_AUD.PYMT_ATRB_AMT||'~~'||trim(PYMT_ATRB_AUD.PYMT_ATRB_BUS_CAT_CD)||'~~'||PYMT_ATRB_AUD.PYMT_ATRB_SHR_PCT||'~~'||PYMT_ATRB_AUD.PYMT_LMT_YR||'~~'||PYMT_ATRB_AUD.PYMT_PGM_ID||'~~'||trim(PYMT_ATRB_AUD.PYMT_PTY_RLT_CD)||'~~'||trim(PYMT_ATRB_AUD.RCD_REF_PRIM_ID)||'~~'||trim(PYMT_ATRB_AUD.RCD_REF_PRIM_ID_TYPE_CD)||'~~'||trim(PYMT_ATRB_AUD.RCD_REF_SCND_ID)||'~~'||trim(PYMT_ATRB_AUD.RCD_REF_SCND_ID_TYPE_CD)||'~~'||PYMT_ATRB_AUD.SBSD_CUST_ID||'~~'||PYMT_ATRB_AUD.SBSD_PRD_STRT_YR||'~~'||trim(PYMT_ATRB_AUD.SBST_CHG_ELG_IND)||'~~'||to_char(PYMT_ATRB_AUD.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PYMT_ATRB_AUD.CRE_USER_NM)||'~~'||to_char(PYMT_ATRB_AUD.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PYMT_ATRB_AUD.LAST_CHG_USER_NM)||'~~'||trim(PYMT_ATRB_AUD.ST_FSA_CD)||'~~'||trim(PYMT_ATRB_AUD.TAX_ID_TYPE_CD)||'~~'||PYMT_ATRB_AUD.TOT_NET_PYMT_AMT||'~~'||PYMT_ATRB_AUD.TOT_PYMT_ATRB_AMT) HASH_DIF
   FROM SBSD_STG.PYMT_ATRB_AUD PYMT_ATRB_AUD
   WHERE PYMT_ATRB_AUD.PRNT_PYMT_ATRB_ID IS NOT NULL
     AND PYMT_ATRB_AUD.CDC_OPER_CD IN ('I',
                                       'UN')
     AND date(PYMT_ATRB_AUD.CDC_DT) = date(TO_TIMESTAMP ('{ETL_START_TIMESTAMP}', 'YYYY-MM-DD HH24:MI:SS.FF'))
   ORDER BY PYMT_ATRB_AUD.CDC_DT) stg ON (coalesce(stg.PYMT_ATRB_ID, 0) = coalesce(dv.PYMT_ATRB_ID, 0)
                                          AND coalesce(stg.DATA_ACTN_DT, current_timestamp) = coalesce(dv.DATA_ACTN_DT, current_timestamp)
                                          AND coalesce(stg.PRPS_PYMT_ID, 0) = coalesce(dv.PRPS_PYMT_ID, 0)) 
WHEN MATCHED
	AND dv.LOAD_DT <> stg.LOAD_DT
  AND dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD')
  AND stg.HASH_DIF <> dv.HASH_DIF
THEN
UPDATE
SET LOAD_END_DT = stg.LOAD_DT,
    DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT