INSERT INTO pymt_dm_stg.da_rdn_txn_fact  (
                             CRE_DT,
                             LAST_CHG_DT,
                             DATA_STAT_CD,
                             SBSD_PRD_STRT_YR,
                             ACCT_PGM_DURB_ID,
                             MBR_CUST_SRGT_ID,
                             MBR_CUST_DURB_ID,
                             PRNT_MBR_CUST_SRGT_ID,
                             PRNT_MBR_CUST_DURB_ID,
                             PRIM_CUST_SRGT_ID,
                             PRIM_CUST_DURB_ID,
                             MBR_RPT_FSA_ST_CNTY_SRGT_ID,
                             MBR_RPT_FSA_ST_CNTY_DURB_ID,
                             PYMT_ATRB_RDN_TYPE_DURB_ID,
                             FSA_ST_CNTY_SRGT_ID,
                             FSA_ST_CNTY_DURB_ID,
                             ACCT_REF_PRIM_ID_TYPE_DURB_ID,
                             ACCT_REF_SCND_ID_TYPE_DURB_ID,
                             LTD_PYMT_PGM_SRGT_ID,
                             LTD_PYMT_PGM_DURB_ID,
                             PYMT_LMT_YR,
                             CMDY_CD,
                             PRPS_PYMT_AMT,
                             PYMT_ATRB_RDN_AMT,
                             TOT_PYMT_ATRB_RDN_AMT,
                             RCD_REF_PRIM_ID,
                             RCD_REF_SCND_ID,
                             PYMT_LMT_IND,
                             HRCH_PYMT_LMT_IND,
                             PRST_OPYMT_ATRB_IND,
                             APP_3_OWNSHP_LVL_LMT_IND,
                             PYMT_ATRB_RVRS_DT,
                             OVRRD_SBSD_PRD_STRT_YR,
                             PYMT_PGM_ID,
                             OBL_CNFRM_NBR,
                             PRPS_PYMT_DATA_STAT_CD,
                             PYMT_ATRB_RDN_DATA_STAT_CD,
                             PROC_RQST_REF_NBR,
                             DATA_ACTN_DT,
                             LATEST_PYMT_ATRB_RDN_TXN_IND,
                             PRPS_PYMT_ID,
                             PYMT_ATRB_ID,
                             PYMT_ATRB_RDN_ID,
                             SRC_CRE_DT,
                             SRC_CRE_USER_NM,
                             SRC_LAST_CHG_DT,
                             SRC_LAST_CHG_USER_NM)    



Select /*+ parallel (24) */
CURRENT_TIMESTAMP CRE_DT, /*V_BATCH_LOAD_DT in datastage*/
CURRENT_TIMESTAMP LAST_CHG_DT, /*V_BATCH_LOAD_DT in datastage*/
'A' DATA_STAT_CD,
DV.SBSD_PRD_STRT_YR,
DV.ACCT_PGM_DURB_ID,
DV.MBR_CUST_SRGT_ID,
DV.MBR_CUST_DURB_ID,
DV.PRNT_MBR_CUST_SRGT_ID,
DV.PRNT_MBR_CUST_DURB_ID,
DV.PRIM_CUST_SRGT_ID,
DV.PRIM_CUST_DURB_ID,
DV.MBR_RPT_FSA_ST_CNTY_SRGT_ID,
DV.MBR_RPT_FSA_ST_CNTY_DURB_ID,
DV.PYMT_ATRB_RDN_TYPE_DURB_ID,
DV.FSA_ST_CNTY_SRGT_ID,
DV.FSA_ST_CNTY_DURB_ID,
DV.ACCT_REF_PRIM_ID_TYPE_DURB_ID,
DV.ACCT_REF_SCND_ID_TYPE_DURB_ID,
DV.LTD_PYMT_PGM_SRGT_ID,
DV.LTD_PYMT_PGM_DURB_ID,
DV.PYMT_LMT_YR,
DV.CMDY_CD,
DV.PRPS_PYMT_AMT,
DV.PYMT_ATRB_RDN_AMT,
DV.TOT_PYMT_ATRB_RDN_AMT,
DV.RCD_REF_PRIM_ID,
DV.RCD_REF_SCND_ID,
DV.PYMT_LMT_IND,
DV.HRCH_PYMT_LMT_IND,
DV.PRST_OPYMT_ATRB_IND,
DV.APP_3_OWNSHP_LVL_LMT_IND,
DV.PYMT_ATRB_RVRS_DT,
DV.OVRRD_SBSD_PRD_STRT_YR,
DV.PYMT_PGM_ID,
DV.OBL_CNFRM_NBR,
DV.PRPS_PYMT_DATA_STAT_CD,
DV.PYMT_ATRB_RDN_DATA_STAT_CD,
DV.PROC_RQST_REF_NBR,
DV.DATA_ACTN_DT,
DV.LATEST_PYMT_ATRB_RDN_TXN_IND,
DV.PRPS_PYMT_ID,
DV.PYMT_ATRB_ID,
DV.PYMT_ATRB_RDN_ID,
DV.SRC_CRE_DT,
DV.SRC_CRE_USER_NM,
DV.SRC_LAST_CHG_DT,
DV.SRC_LAST_CHG_USER_NM

 /*,
CASE
   WHEN 
       DV.PYMT_ATRB_RDN_ID IS NOT NULL
       AND DV.PYMT_ATRB_ID IS NOT NULL
       AND DV.PRPS_PYMT_ID IS NOT NULL
   THEN 0
   ELSE 1 
   END DEF_ERR_IND ,
sys.md5hash(DV.PYMT_ATRB_RDN_ID||'~~'||DV.PYMT_ATRB_ID||'~~'||DV.PRPS_PYMT_ID||'~~'|| NVL(TO_CHAR(DV.DATA_ACTN_DT),'--')) BUS_KEY,
 --used by DS job to detect multiple BK records (for single AK field, no hashing required) 
 ('PYMT_ATRB_RDN_ID:'||DV.PYMT_ATRB_RDN_ID||'~~'||'PYMT_ATRB_ID:'||DV.PYMT_ATRB_ID||'~~'||'PRPS_PYMT_ID:'||DV.PRPS_PYMT_ID||'~~'||'DATA_ACTN_DT:'||DV.DATA_ACTN_DT ) BUS_KEY_ERR*/

From (

SELECT /*+ parallel (24) */ DV_ALL.* FROM 
 (
  Select 
 DV_DR.PYMT_ATRB_RDN_ID,
 DV_DR.PYMT_ATRB_ID,
 DV_DR.PRPS_PYMT_ID,
 DV_DR.DATA_ACTN_DT,
 DIR_ATRB_PRPS_PYMT_LS.CMDY_CD,
 case coalesce (cast (DV_DR.DATA_ACTN_DT as CHAR ),'0') when  '0' Then 1 when NULL then 1  else  0 End As LATEST_PYMT_ATRB_RDN_TXN_IND,
 Case UPPER(DIR_ATRB_PRPS_PYMT_LS.APP_3_OWNSHP_LVL_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS APP_3_OWNSHP_LVL_LMT_IND,
 Case UPPER(DIR_ATRB_PRPS_PYMT_LS.HRCH_PYMT_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS HRCH_PYMT_LMT_IND,
 Case  UPPER(DIR_ATRB_PRPS_PYMT_LS.PRST_OPYMT_ATRB_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS PRST_OPYMT_ATRB_IND,
 Case UPPER(DIR_ATRB_PRPS_PYMT_LS.PYMT_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS PYMT_LMT_IND,
 DIR_ATRB_PRPS_PYMT_LS.OBL_CNFRM_NBR,
 DIR_ATRB_PRPS_PYMT_LS.OVRRD_SBSD_PRD_STRT_YR,
 COALESCE(PGM_YR_DIM.PGM_YR,-1) SBSD_PRD_STRT_YR,
 DIR_ATRB_PRPS_PYMT_LS.PROC_RQST_REF_NBR,
 DIR_ATRB_PRPS_PYMT_LS.PYMT_AMT PRPS_PYMT_AMT,
 DV_DR.PYMT_ATRB_RDN_AMT,
 DV_DR.TOT_PYMT_ATRB_RDN_AMT,
 DIR_ATRB_PRPS_PYMT_LS.DATA_STAT_CD PRPS_PYMT_DATA_STAT_CD,
 DV_DR.DATA_STAT_CD PYMT_ATRB_RDN_DATA_STAT_CD,
 DIR_ATRB_PRPS_PYMT_LS.PYMT_ATRB_RVRS_DT,
 DIR_ATRB_PRPS_PYMT_LS.PYMT_LMT_YR,
 DIR_ATRB_PRPS_PYMT_LS.PYMT_PGM_ID,
 DIR_ATRB_PRPS_PYMT_LS.RCD_REF_PRIM_ID,
 DIR_ATRB_PRPS_PYMT_LS.RCD_REF_SCND_ID,
 DV_DR.SRC_CRE_DT,
 DV_DR.SRC_CRE_USER_NM,
 DV_DR.SRC_LAST_CHG_DT,
 DV_DR.SRC_LAST_CHG_USER_NM,
COALESCE(ACCT_PGM_DIM.ACCT_PGM_DURB_ID,-3) ACCT_PGM_DURB_ID,
COALESCE(ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_TYPE_DURB_ID,-3) ACCT_REF_PRIM_ID_TYPE_DURB_ID,
COALESCE(ACCT_REF_TYPE_SCND_DIM.ACCT_REF_TYPE_DURB_ID,-3) ACCT_REF_SCND_ID_TYPE_DURB_ID,
COALESCE(FSA_ST_CNTY_DIM.FSA_ST_CNTY_DURB_ID,-3) FSA_ST_CNTY_DURB_ID,
COALESCE(FSA_ST_CNTY_DIM.FSA_ST_CNTY_SRGT_ID,-3) FSA_ST_CNTY_SRGT_ID,
COALESCE(MBR_CUST_DM.CUST_DURB_ID,-3) MBR_CUST_DURB_ID,
COALESCE(MBR_CUST_DM.CUST_SRGT_ID,-3) MBR_CUST_SRGT_ID,
COALESCE(MBR_RPT_FSA_ST_CNTY_DIM.RPT_FSA_ST_CNTY_DURB_ID,-3) MBR_RPT_FSA_ST_CNTY_DURB_ID,
COALESCE(MBR_RPT_FSA_ST_CNTY_DIM.RPT_FSA_ST_CNTY_SRGT_ID,-3) MBR_RPT_FSA_ST_CNTY_SRGT_ID,
COALESCE(LTD_PYMT_PGM_DIM.LTD_PYMT_PGM_DURB_ID,-3) LTD_PYMT_PGM_DURB_ID,
COALESCE(LTD_PYMT_PGM_DIM.LTD_PYMT_PGM_SRGT_ID,-3) LTD_PYMT_PGM_SRGT_ID,
COALESCE(CUST_DIM.CUST_DURB_ID,-3) PRIM_CUST_DURB_ID,
COALESCE(CUST_DIM.CUST_SRGT_ID,-3) PRIM_CUST_SRGT_ID,
COALESCE(PRNT_MBR_CUST_DM.CUST_DURB_ID,-3) PRNT_MBR_CUST_DURB_ID,
COALESCE(PRNT_MBR_CUST_DM.CUST_SRGT_ID,-3) PRNT_MBR_CUST_SRGT_ID,
COALESCE(PYMT_ATRB_RDN_TYPE_DIM.PYMT_ATRB_RDN_TYPE_DURB_ID,-3) PYMT_ATRB_RDN_TYPE_DURB_ID,
 RANK() over ( partition by DV_DR.PYMT_ATRB_RDN_ID, DV_DR.PYMT_ATRB_ID,    DV_DR.PRPS_PYMT_ID   ,COALESCE(DV_DR.DATA_ACTN_DT,TO_TIMESTAMP ('1900-01-01 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.FF') ) Order by DATA_ACTN_DT asc,
         CASE DV_DR.DATA_STAT_CD
         WHEN 'A' THEN 1
         WHEN 'I' THEN 2
         WHEN 'D' THEN 3
         ELSE 4
         END ASC,
      DV_DR.SRC_CRE_DT DESC NULLS LAST
       )  as Rank_Part 
From 
( 
     select 
     PYMT_ATRB_RDN_LS.PYMT_ATRB_RDN_ID,  PYMT_ATRB_RDN_LS.PYMT_ATRB_ID, PYMT_ATRB_RDN_LS.PRPS_PYMT_ID,   PYMT_ATRB_RDN_LS.DATA_STAT_CD,
     PYMT_ATRB_RDN_LS.PYMT_ATRB_RDN_AMT, PYMT_ATRB_RDN_LS.TOT_PYMT_ATRB_RDN_AMT, Trim(PYMT_ATRB_RDN_LS.PYMT_ATRB_RDN_TYPE_CD) PYMT_ATRB_RDN_TYPE_CD,
     PYMT_ATRB_RDN_LS.SRC_CRE_DT,     PYMT_ATRB_RDN_LS.SRC_CRE_USER_NM, PYMT_ATRB_RDN_LS.SRC_LAST_CHG_DT, PYMT_ATRB_RDN_LS.SRC_LAST_CHG_USER_NM,TO_TIMESTAMP('','YYYY-MM-DD HH24:MI:SS.FF') DATA_ACTN_DT
     from EDV.PYMT_ATRB_RDN_LS
     where 
      CAST(DATA_EFF_END_DT AS date) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
           AND CAST(DATA_EFF_STRT_DT  AS date) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')         
        
      UNION
        
      select 
      PR_PYMT_ATRB_RDN_LS.PYMT_ATRB_RDN_ID,  PR_PYMT_ATRB_RDN_LS.PYMT_ATRB_ID, PR_PYMT_ATRB_RDN_LS.PRPS_PYMT_ID,  PR_PYMT_ATRB_RDN_LS.DATA_STAT_CD,
      PR_PYMT_ATRB_RDN_LS.PYMT_ATRB_RDN_AMT, PR_PYMT_ATRB_RDN_LS.TOT_PYMT_ATRB_RDN_AMT, Trim(PR_PYMT_ATRB_RDN_LS.PYMT_ATRB_RDN_TYPE_CD) PYMT_ATRB_RDN_TYPE_CD ,
      PR_PYMT_ATRB_RDN_LS.SRC_CRE_DT,      PR_PYMT_ATRB_RDN_LS.SRC_CRE_USER_NM, PR_PYMT_ATRB_RDN_LS.SRC_LAST_CHG_DT, PR_PYMT_ATRB_RDN_LS.SRC_LAST_CHG_USER_NM, PR_PYMT_ATRB_RDN_LS.DATA_ACTN_DT
      From EDV.PR_PYMT_ATRB_RDN_LS
      where CAST(DATA_EFF_END_DT AS date) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
            AND CAST(DATA_EFF_STRT_DT AS date) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')         
) DV_DR
  
Left Join 
 (  
 Select * From (
 SELECT   PYMT_ATRB_UNION.*, ROW_NUMBER () OVER (PARTITION BY PYMT_ATRB_ID ORDER BY SRC_LAST_CHG_DT DESC) AS PRECEDENCE
  FROM   (SELECT   PYMT_ATRB_ID,
                   PRPS_PYMT_ID,
                   MBR_CORE_CUST_ID,PRNT_PYMT_ATRB_CORE_CUST_ID,
                   SRC_LAST_CHG_DT
            FROM   EDV.PYMT_ATRB_MBR_HLS
           WHERE  CAST (DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP ('9999-12-31', 'YYYY-MM-DD')
                   AND CAST(DATA_EFF_STRT_DT AS DATE) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
                   
          UNION
          SELECT   PYMT_ATRB_ID,
                   PRPS_PYMT_ID,
                   MBR_CORE_CUST_ID,PRNT_PYMT_ATRB_CORE_CUST_ID,
                   SRC_LAST_CHG_DT
            FROM   EDV.PR_PYMT_ATRB_MBR_HLS
           WHERE   CAST (DATA_EFF_END_DT as DATE) = TO_TIMESTAMP ('9999-12-31', 'YYYY-MM-DD')
                   AND cast (DATA_EFF_STRT_DT as DATE) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
                   
            UNION        
                   SELECT   PYMT_ATRB_ID,
                   PRPS_PYMT_ID,
                   MBR_CORE_CUST_ID,PRNT_PYMT_ATRB_CORE_CUST_ID,
                   SRC_LAST_CHG_DT
            FROM   EDV.PYMT_ATRB_LS
           WHERE   CAST (DATA_EFF_END_DT as DATE) = TO_TIMESTAMP ('9999-12-31', 'YYYY-MM-DD')
                   AND CAST(DATA_EFF_STRT_DT as DATE) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
                  
          UNION
          SELECT   PYMT_ATRB_ID,
                   PRPS_PYMT_ID,
                   MBR_CORE_CUST_ID,PRNT_PYMT_ATRB_CORE_CUST_ID,
                   SRC_LAST_CHG_DT
            FROM   EDV.PR_PYMT_ATRB_LS
           WHERE   CAST (DATA_EFF_END_DT as DATE) = TO_TIMESTAMP ('9999-12-31', 'YYYY-MM-DD')
                   AND CAST(DATA_EFF_STRT_DT as DATE) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
                  
       
          )  PYMT_ATRB_UNION
    ) as subquery_a where PRECEDENCE =1
 ) PYMT_ATRB_LS
ON ( DV_DR.PYMT_ATRB_ID =PYMT_ATRB_LS.PYMT_ATRB_ID ) 
 
Inner JOIN
 (
    
     Select * From EDV.DIR_ATRB_PRPS_PYMT_LS  
     where CAST(DATA_EFF_END_DT as DATE) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
          AND CAST(DATA_EFF_STRT_DT as DATE) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')          
          
 ) DIR_ATRB_PRPS_PYMT_LS
ON (DV_DR.PRPS_PYMT_ID =DIR_ATRB_PRPS_PYMT_LS.PRPS_PYMT_ID)

  Left Join EDV.PYMT_PGM_RS
  ON ( DIR_ATRB_PRPS_PYMT_LS.PYMT_PGM_ID = PYMT_PGM_RS.PYMT_PGM_ID And  CAST(PYMT_PGM_RS.DATA_EFF_END_DT as DATE) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )
   
  Left Join PYMT_DM_STG.LTD_PYMT_PGM_DIM
  ON ( PYMT_PGM_RS.PYMT_PGM_NM = LTD_PYMT_PGM_NM And  CAST(LTD_PYMT_PGM_DIM.DATA_EFF_END_DT as DATE) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )
   
  LEFT JOIN PYMT_DM_STG.PYMT_ATRB_RDN_TYPE_DIM
  ON ( DV_DR.PYMT_ATRB_RDN_TYPE_CD =  PYMT_ATRB_RDN_TYPE_DIM.PYMT_ATRB_RDN_TYPE_CD And PYMT_ATRB_RDN_TYPE_DIM.DATA_STAT_CD ='A')
     
  Left Join PYMT_DM_STG.ACCT_REF_TYPE_DIM  ACCT_REF_TYPE_PRIM_DIM
  ON (DIR_ATRB_PRPS_PYMT_LS.RCD_REF_PRIM_ID_TYPE_CD =ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_CD And ACCT_REF_TYPE_PRIM_DIM.DATA_STAT_CD ='A' And ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_TYPE_DURB_ID > 0 )
  
  
  Left Join PYMT_DM_STG.ACCT_REF_TYPE_DIM  ACCT_REF_TYPE_SCND_DIM
  ON( DIR_ATRB_PRPS_PYMT_LS.RCD_REF_SCND_ID_TYPE_CD =ACCT_REF_TYPE_SCND_DIM.ACCT_REF_CD And ACCT_REF_TYPE_SCND_DIM.DATA_STAT_CD ='A' And ACCT_REF_TYPE_SCND_DIM.ACCT_REF_TYPE_DURB_ID > 0)
  
  Left Join CMN_DIM_DM_STG.ACCT_PGM_DIM
  ON  ( DIR_ATRB_PRPS_PYMT_LS.ACCT_PGM_CD = ACCT_PGM_DIM.ACCT_PGM_CD And ACCT_PGM_DIM.DATA_STAT_CD ='A')
    
  LEFT  JOIN 
   (
        SELECT FSA_ST_CNTY_SRGT_ID,FSA_ST_CNTY_DURB_ID ,ST_FSA_CD ,CNTY_FSA_CD,ST_NM,CNTY_NM
        ,ROW_NUMBER() OVER ( PARTITION BY ST_FSA_CD  ,CNTY_FSA_CD ORDER BY CRE_DT DESC
        ) AS PRECEDENCE
        FROM CMN_DIM_DM_STG.FSA_ST_CNTY_DIM
        WHERE CUR_RCD_IND = 1
   ) FSA_ST_CNTY_DIM 
  ON ( DIR_ATRB_PRPS_PYMT_LS.ST_FSA_CD=FSA_ST_CNTY_DIM.ST_FSA_CD   And DIR_ATRB_PRPS_PYMT_LS.CNTY_FSA_CD = FSA_ST_CNTY_DIM.CNTY_FSA_CD AND FSA_ST_CNTY_DIM.PRECEDENCE = 1 )  

  Left join CMN_DIM_DM_STG.CUST_DIM 
  On ( DIR_ATRB_PRPS_PYMT_LS.PAID_CORE_CUST_ID = CUST_DIM.CORE_CUST_ID  And CUST_DIM.CUR_RCD_IND =1 And cast (CUST_DIM.DATA_EFF_END_DT as DATE) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') ) 
        
  Left Join 
   (
           Select * from (
        SELECT FSA_ST_CNTY_SRGT_ID RPT_FSA_ST_CNTY_SRGT_ID ,FSA_ST_CNTY_DURB_ID RPT_FSA_ST_CNTY_DURB_ID ,ST_FSA_CD ,CNTY_FSA_CD,ST_NM,CNTY_NM
        ,ROW_NUMBER() OVER ( PARTITION BY ST_FSA_CD  ,CNTY_FSA_CD ORDER BY CRE_DT DESC) AS PRECEDENCE
        FROM CMN_DIM_DM_STG.FSA_ST_CNTY_DIM
        WHERE CUR_RCD_IND = 1   ) FSA_ST_CNTY_DIM JOIN CMN_DIM_DM_STG.CUST_DIM  
                ON (FSA_ST_CNTY_DIM.ST_FSA_CD = CUST_DIM.RPT_ST_FSA_CD And FSA_ST_CNTY_DIM.CNTY_FSA_CD = CUST_DIM.RPT_CNTY_FSA_CD
                And   CAST(CUST_DIM.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')                 And  FSA_ST_CNTY_DIM.PRECEDENCE=1 
                    )
   ) MBR_RPT_FSA_ST_CNTY_DIM 
  ON (  PYMT_ATRB_LS.MBR_CORE_CUST_ID= MBR_RPT_FSA_ST_CNTY_DIM.CORE_CUST_ID)

  Left join CMN_DIM_DM_STG.CUST_DIM MBR_CUST_DM
  On ( PYMT_ATRB_LS.MBR_CORE_CUST_ID = MBR_CUST_DM.CORE_CUST_ID  And MBR_CUST_DM.CUR_RCD_IND =1 And CAST(MBR_CUST_DM.DATA_EFF_END_DT as DATE) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )
  
  Left join CMN_DIM_DM_STG.CUST_DIM PRNT_MBR_CUST_DM
   On ( PYMT_ATRB_LS.PRNT_PYMT_ATRB_CORE_CUST_ID = PRNT_MBR_CUST_DM.CORE_CUST_ID  And PRNT_MBR_CUST_DM.CUR_RCD_IND =1 And CAST(PRNT_MBR_CUST_DM.DATA_EFF_END_DT as DATE) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )

  Left Join CMN_DIM_DM_STG.PGM_YR_DIM
  on (  DIR_ATRB_PRPS_PYMT_LS.SBSD_PRD_STRT_YR = PGM_YR_DIM.PGM_YR And PGM_YR_DIM.DATA_STAT_CD ='A')

    Order by  DV_DR.PYMT_ATRB_ID,  DV_DR.PRPS_PYMT_ID asc
    ) DV_ALL
   WHERE DV_ALL.Rank_Part = 1 
 ) dv 
 

 --ORDER BY BUS_KEY  asc 