INSERT into
EDV.RMA_PCW_EXCP_RS(RMA_PCW_EXCP_CD,
DMN_VAL_ID,
LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
RMA_PCW_NM,
RMA_PCW_DESC,
DPLY_SEQ_NBR,
DFLT_VAL_IND,
DMN_ID, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(
SELECT stg.* from (
SELECT DISTINCT
coalesce(DMN_VAL.DMN_CHAR_VAL, '[NULL IN SOURCE]') RMA_PCW_EXCP_CD,
coalesce(DMN_VAL.DMN_VAL_ID, '-1') DMN_VAL_ID,
DMN_VAL.LOAD_DT LOAD_DT,
DMN_VAL.CDC_DT DATA_EFF_STRT_DT,
DMN_VAL.DATA_SRC_NM DATA_SRC_NM,
DMN_VAL.CRE_DT SRC_CRE_DT,
DMN_VAL.LAST_CHG_DT SRC_LAST_CHG_DT,
DMN_VAL.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
DMN_VAL.DMN_VAL_NM RMA_PCW_NM,
DMN_VAL.DMN_VAL_DESC RMA_PCW_DESC,
DMN_VAL.DPLY_SEQ_NBR DPLY_SEQ_NBR,
DMN_VAL.DFLT_VAL_IND DFLT_VAL_IND,
DMN_VAL.DMN_ID DMN_ID ,
TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(trim(both DMN_VAL.DMN_CHAR_VAL)||'~~'||DMN_VAL.DMN_VAL_ID||'~~'||to_char(DMN_VAL.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(DMN_VAL.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both DMN_VAL.LAST_CHG_USER_NM)||'~~'||trim(both DMN_VAL.DMN_VAL_NM)||'~~'||trim(both DMN_VAL.DMN_VAL_DESC)||'~~'||DMN_VAL.DPLY_SEQ_NBR||'~~'||trim(both DMN_VAL.DFLT_VAL_IND)||'~~'||DMN_VAL.DMN_ID) HASH_DIF
FROM SQL_FARM_RCD_STG.DMN_VAL
WHERE DMN_VAL.DMN_ID in (51,54,57)
and DMN_VAL.cdc_oper_cd IN ('I','UN')
order by DMN_VAL.CDC_DT
) stg 
LEFT JOIN  EDV.RMA_PCW_EXCP_RS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
);