
SELECT 
agricultural_production_plan.agricultural_production_plan_identifier AS AG_PROD_PLAN_ID
,agricultural_production_plan.tract_identifier AS CLU_TR_ID
,agricultural_production_plan.crop_intended_use_code AS CROP_INTN_USE_CD
,agricultural_production_plan.planting_primary_status_code AS PLNT_PRIM_STAT_CD
,agricultural_production_plan.planting_secondary_status_code AS PLNT_SCND_STAT_CD
,agricultural_production_plan.planting_multiple_crop_code AS PLNT_MULT_CROP_CD
,agricultural_production_plan.fsa_crop_code AS FSA_CROP_CD
,agricultural_production_plan.fsa_crop_type_code AS FSA_CROP_TYPE_CD
,agricultural_production_plan.planting_period_code AS PLNT_PRD_CD
,agricultural_production_plan.irrigation_practice_code AS IRR_PRAC_CD
,agricultural_production_plan.field_number AS FLD_NBR
,cast(agricultural_production_plan.crop_planted_date AS timestamp) AS CROP_PLNT_DT
,agricultural_production_plan.cropland_indicator AS CPLD_IND
,agricultural_production_plan.skip_row_width AS SKIP_ROW_WDTH
,agricultural_production_plan.crop_row_width AS CROP_ROW_WDTH
,agricultural_production_plan.crop_row_count AS CROP_ROW_CT
,agricultural_production_plan.skip_row_count AS SKIP_ROW_CT
,agricultural_production_plan.tree_separation_length AS TREE_SEP_LGTH
,agricultural_production_plan.tree_age AS TREE_AGE
,agricultural_production_plan.tree_unit_count AS TREE_UNIT_CT
,agricultural_production_plan.acreage_official_measurement_code AS ACRG_OFCL_MEAS_CD
,agricultural_production_plan.determined_acreage_indicator AS DTER_ACRG_IND
,agricultural_production_plan.crop_reporting_unit_code AS CROP_RPT_UNIT_CD
,agricultural_production_plan.crop_field_determined_quantity AS CROP_FLD_DTER_QTY
,agricultural_production_plan.crop_field_reported_quantity AS CROP_FLD_RPT_QTY
,cast(agricultural_production_plan.certification_date AS timestamp) AS CERT_DT
,agricultural_production_plan.nap_unit_number AS NAP_UNIT_NBR
,agricultural_production_plan.perennial_crop_expiration_year AS PRNL_CROP_EXPR_YR
,agricultural_production_plan.land_use_code AS LAND_USE_CD
,agricultural_production_plan.planting_pattern_type_code AS PLNT_PTRN_TYPE_CD
,agricultural_production_plan.crop_planted_percent AS CROP_PLNT_PCT
,agricultural_production_plan.concurrent_planting_code AS CNCUR_PLNT_CD
,agricultural_production_plan.crop_use_code AS CROP_USE_CD
,cast(agricultural_production_plan.creation_date AS timestamp) AS CRE_DT
,cast(agricultural_production_plan.last_change_date AS timestamp) AS LAST_CHG_DT
,agricultural_production_plan.last_change_user_name AS LAST_CHG_USER_NM
,agricultural_production_plan.data_status_code AS DATA_STAT_CD
,agricultural_production_plan.coc_disapproved_acreage_indicator AS COC_DAPRV_ACRG_IND
,cast(agricultural_production_plan.data_inactive_date AS timestamp) AS DATA_IACTV_DT
,agricultural_production_plan.field_identification AS FLD_ID
,agricultural_production_plan.nap_unit_override_ind AS NAP_UNIT_OVRRD_IND
,agricultural_production_plan.organic_practice_type_code AS OGNC_PRAC_TYPE_CD
,agricultural_production_plan.native_pasture_conversion_indicator AS NTV_PSTR_CVSN_IND
,agricultural_production_plan.cropping_practice_code AS CROP_PRAC_CD
,agricultural_production_plan.geospatial_agriculture_production_plan_identifier AS GSPTL_AG_PROD_PLAN_ID
,agricultural_production_plan.core_product_code AS CORE_PROD_CD
,agricultural_production_plan.core_product_type_code AS CORE_PROD_TYPE_CD
,agricultural_production_plan.product_intended_use_code AS PROD_INTN_USE_CD
,agricultural_production_plan.clu_identifier AS CLU_ID
,agricultural_production_plan.original_reported_acreage AS ORGN_RPT_ACRG
,agricultural_production_plan.reported_acreage_modified_indicator AS RPT_ACRG_MOD_IND
,agricultural_production_plan.reported_acreage_modified_reason_code AS RPT_ACRG_MOD_RSN_CD
,agricultural_production_plan.reported_acreage_modified_other_reason_text AS RPT_ACRG_MOD_OT_RSN_TXT
,agricultural_production_plan.acreage_calculation_projection_code AS ACRG_CALC_PRJ_CD
,cast(agricultural_production_plan.original_planted_date AS timestamp) AS ORGN_PLNT_DT
,agricultural_production_plan.planted_date_modified_indicator AS PLNT_DT_MOD_IND
,agricultural_production_plan.planted_date_modified_reason_code AS PLNT_DT_MOD_RSN_CD
,agricultural_production_plan.planted_date_modified_other_reason_text AS PLNT_DT_MOD_OT_RSN_TXT
,agricultural_production_plan.clu_producer_review_request_indicator AS CLU_PRDR_RVW_RQST_IND
,agricultural_production_plan.subfield_number AS SFLD_NBR
,crop_acreage_report.program_year AS PGM_YR
,crop_acreage_report.farm_number AS FARM_NBR
,crop_acreage_report.state_fsa_code AS ST_FSA_CD
,crop_acreage_report.county_fsa_code AS CNTY_FSA_CD
,tract.tract_number AS TR_NBR
,'' AS HASH_DIFF
,agricultural_production_plan.op AS CDC_OPER_CD
,current_timestamp AS LOAD_DT
,'CARS_STG' AS DATA_SRC_NM
,agricultural_production_plan.dart_filedate AS CDC_DT
,agricultural_production_plan.animal_unit_public_land_usage_percentage AS ANML_UNIT_PUB_LAND_USE_PCT
,cast(agricultural_production_plan.animal_unit_public_grazing_beginning_date AS timestamp) AS ANML_UNIT_GRZ_BEG_DT
,cast(agricultural_production_plan.animal_unit_public_grazing_ending_date AS timestamp) AS ANML_UNIT_GRZ_END_DT
,agricultural_production_plan.skip_row_pattern_code AS SKIP_ROW_PTRN_CD
,agricultural_production_plan.multiple_crop_intended_use_status_code AS MULT_CROP_INTN_USE_STAT_CD
,agricultural_production_plan.actual_land_use_code AS ACTL_LAND_USE_CD
,agricultural_production_plan.crop_late_filing_indicator AS CROP_LATE_FILE_IND
,agricultural_production_plan.native_pasture_conversion_override_indicator AS NTV_PSTR_CVSN_OVRRD_IND
,agricultural_production_plan.animal_unit_federal_managed_land_usage_percentage AS ANML_UNIT_FED_MNG_LAND_USE_PCT
,agricultural_production_plan.plant_count AS PLNT_CNT

FROM `fsa-{env}-cars-cdc`.`agricultural_production_plan`
 LEFT JOIN  `fsa-{env}-cars-cdc`.`tract` ON (agricultural_production_plan.tract_identifier=tract.tract_identifier)
 JOIN `fsa-{env}-cars-cdc`.`crop_acreage_report` ON (tract.crop_acreage_report_identifier=crop_acreage_report.crop_acreage_report_identifier)

WHERE `agricultural_production_plan`.`dart_filedate` BETWEEN DATE '{ETL_START_TIMESTAMP}' AND DATE '{ETL_END_TIMESTAMP}'
