Merge  into
EDV.YR_ARC_PLC_PTCP_ELCT_LS dv
using(
SELECT sub1.*
FROM
(	
	SELECT sub.*,
		   ROW_NUMBER() OVER (PARTITION BY CROP_FARM_L_ID, FARM_H_ID, YR_ARC_PLC_PTCP_ELCT_ID ORDER BY LOAD_DT desc) YR_ARC_PLC_PTCP_ELCT_ID_RANK
	FROM
	(
		select DISTINCT MD5(MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--')))||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_TYPE_CD), '--')) ) as CROP_FARM_L_ID,
		MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--'))) FARM_H_ID,
		coalesce(YR_ARC_PLC_PTCP_ELCT.YR_ARC_PLC_PTCP_ELCT_ID, '-1') YR_ARC_PLC_PTCP_ELCT_ID,
		YR_ARC_PLC_PTCP_ELCT.LOAD_DT LOAD_DT,
		YR_ARC_PLC_PTCP_ELCT.CDC_DT DATA_EFF_STRT_DT,
		YR_ARC_PLC_PTCP_ELCT.DATA_SRC_NM DATA_SRC_NM,
		YR_ARC_PLC_PTCP_ELCT.DATA_STAT_CD DATA_STAT_CD,
		YR_ARC_PLC_PTCP_ELCT.CRE_DT SRC_CRE_DT,
		YR_ARC_PLC_PTCP_ELCT.CRE_USER_NM SRC_CRE_USER_NM,
		YR_ARC_PLC_PTCP_ELCT.LAST_CHG_DT SRC_LAST_CHG_DT,
		YR_ARC_PLC_PTCP_ELCT.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
		YR_ARC_PLC_PTCP_ELCT.FARM_YR_ID FARM_YR_ID,
		YR_ARC_PLC_PTCP_ELCT.PGM_YR PGM_YR,
		YR_ARC_PLC_PTCP_ELCT.CROP_ID CROP_ID,
		YR_ARC_PLC_PTCP_ELCT.ARC_PLC_ELCT_CHC_ID SRC_ARC_PLC_ELCT_CHC_ID,
		ARC_PLC_ELCT_RS.DMN_VAL_NM ARC_PLC_ELCT_CHC_NM ,
		YR_ARC_PLC_PTCP_ELCT.CDC_OPER_CD,
		MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--'))||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.PGM_ABR)||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_CD)||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_TYPE_CD)||'~~'||MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--')))||'~~'||YR_ARC_PLC_PTCP_ELCT.YR_ARC_PLC_PTCP_ELCT_ID||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.DATA_STAT_CD)||'~~'||to_char(YR_ARC_PLC_PTCP_ELCT.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.CRE_USER_NM)||'~~'||to_char(YR_ARC_PLC_PTCP_ELCT.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.LAST_CHG_USER_NM)||'~~'||YR_ARC_PLC_PTCP_ELCT.FARM_YR_ID||'~~'||YR_ARC_PLC_PTCP_ELCT.PGM_YR||'~~'||YR_ARC_PLC_PTCP_ELCT.CROP_ID||'~~'||YR_ARC_PLC_PTCP_ELCT.ARC_PLC_ELCT_CHC_ID||'~~'||trim(both ARC_PLC_ELCT_RS.DMN_VAL_NM)) HASH_DIF
		from SQL_FARM_RCD_STG.YR_ARC_PLC_PTCP_ELCT 
		left join(select * from EDV.ARC_PLC_ELCT_RS
		where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) ARC_PLC_ELCT_RS 
		ON (YR_ARC_PLC_PTCP_ELCT.ARC_PLC_ELCT_CHC_ID=ARC_PLC_ELCT_RS.DMN_VAL_ID)
		 where YR_ARC_PLC_PTCP_ELCT.CDC_OPER_CD IN ('I','UN')
		order by YR_ARC_PLC_PTCP_ELCT.CDC_DT
	) sub
) sub1
WHERE sub1.YR_ARC_PLC_PTCP_ELCT_ID_RANK = 1
)
stg
 on ( 
coalesce(stg.YR_ARC_PLC_PTCP_ELCT_ID,0) = coalesce(dv.YR_ARC_PLC_PTCP_ELCT_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;