 INSERT  into
EDV.YR_ARC_PLC_PTCP_ELCT_LS(
CROP_FARM_L_ID,FARM_H_ID,YR_ARC_PLC_PTCP_ELCT_ID,
LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_CRE_USER_NM,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
FARM_YR_ID,
PGM_YR,
CROP_ID,
SRC_ARC_PLC_ELCT_CHC_ID,
ARC_PLC_ELCT_CHC_NM, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(
SELECT stg.* from (SELECT DISTINCT 
MD5(MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--')))||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_TYPE_CD),'--')) ) as CROP_FARM_L_ID,
MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--'))) FARM_H_ID, YR_ARC_PLC_PTCP_ELCT.YR_ARC_PLC_PTCP_ELCT_ID YR_ARC_PLC_PTCP_ELCT_ID,YR_ARC_PLC_PTCP_ELCT.LOAD_DT LOAD_DT,YR_ARC_PLC_PTCP_ELCT.CDC_DT DATA_EFF_STRT_DT,YR_ARC_PLC_PTCP_ELCT.DATA_SRC_NM DATA_SRC_NM,YR_ARC_PLC_PTCP_ELCT.DATA_STAT_CD DATA_STAT_CD,YR_ARC_PLC_PTCP_ELCT.CRE_DT SRC_CRE_DT,YR_ARC_PLC_PTCP_ELCT.CRE_USER_NM SRC_CRE_USER_NM,YR_ARC_PLC_PTCP_ELCT.LAST_CHG_DT SRC_LAST_CHG_DT,YR_ARC_PLC_PTCP_ELCT.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,YR_ARC_PLC_PTCP_ELCT.FARM_YR_ID FARM_YR_ID,YR_ARC_PLC_PTCP_ELCT.PGM_YR PGM_YR,YR_ARC_PLC_PTCP_ELCT.CROP_ID CROP_ID,YR_ARC_PLC_PTCP_ELCT.ARC_PLC_ELCT_CHC_ID SRC_ARC_PLC_ELCT_CHC_ID,ARC_PLC_ELCT_RS.DMN_VAL_NM ARC_PLC_ELCT_CHC_NM ,
to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--'))||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.PGM_ABR)||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_CD)||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_TYPE_CD)||'~~'||MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--')))||'~~'||YR_ARC_PLC_PTCP_ELCT.YR_ARC_PLC_PTCP_ELCT_ID||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.DATA_STAT_CD)||'~~'||to_char(YR_ARC_PLC_PTCP_ELCT.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.CRE_USER_NM)||'~~'||to_char(YR_ARC_PLC_PTCP_ELCT.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.LAST_CHG_USER_NM)||'~~'||YR_ARC_PLC_PTCP_ELCT.FARM_YR_ID||'~~'||YR_ARC_PLC_PTCP_ELCT.PGM_YR||'~~'||YR_ARC_PLC_PTCP_ELCT.CROP_ID||'~~'||YR_ARC_PLC_PTCP_ELCT.ARC_PLC_ELCT_CHC_ID||'~~'||trim(both ARC_PLC_ELCT_RS.DMN_VAL_NM)) HASH_DIF
from SQL_FARM_RCD_STG.YR_ARC_PLC_PTCP_ELCT 
left join(select * from EDV.ARC_PLC_ELCT_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) ARC_PLC_ELCT_RS 
ON (YR_ARC_PLC_PTCP_ELCT.ARC_PLC_ELCT_CHC_ID=ARC_PLC_ELCT_RS.DMN_VAL_ID)
 where YR_ARC_PLC_PTCP_ELCT.CDC_OPER_CD IN ('I','UN')
And MD5(MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--')))||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_TYPE_CD),'--')) )
IN (Select CROP_FARM_L_ID FROM EDV.CROP_FARM_L )

Union

 
 
SELECT DISTINCT 
MD5('-1') as CROP_FARM_L_ID,
MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--'))) FARM_H_ID, YR_ARC_PLC_PTCP_ELCT.YR_ARC_PLC_PTCP_ELCT_ID YR_ARC_PLC_PTCP_ELCT_ID,YR_ARC_PLC_PTCP_ELCT.LOAD_DT LOAD_DT,YR_ARC_PLC_PTCP_ELCT.CDC_DT DATA_EFF_STRT_DT,YR_ARC_PLC_PTCP_ELCT.DATA_SRC_NM DATA_SRC_NM,YR_ARC_PLC_PTCP_ELCT.DATA_STAT_CD DATA_STAT_CD,YR_ARC_PLC_PTCP_ELCT.CRE_DT SRC_CRE_DT,YR_ARC_PLC_PTCP_ELCT.CRE_USER_NM SRC_CRE_USER_NM,YR_ARC_PLC_PTCP_ELCT.LAST_CHG_DT SRC_LAST_CHG_DT,YR_ARC_PLC_PTCP_ELCT.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,YR_ARC_PLC_PTCP_ELCT.FARM_YR_ID FARM_YR_ID,YR_ARC_PLC_PTCP_ELCT.PGM_YR PGM_YR,YR_ARC_PLC_PTCP_ELCT.CROP_ID CROP_ID,YR_ARC_PLC_PTCP_ELCT.ARC_PLC_ELCT_CHC_ID SRC_ARC_PLC_ELCT_CHC_ID,ARC_PLC_ELCT_RS.DMN_VAL_NM ARC_PLC_ELCT_CHC_NM ,
to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--'))||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.PGM_ABR)||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_CD)||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_TYPE_CD)||'~~'||MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--')))||'~~'||YR_ARC_PLC_PTCP_ELCT.YR_ARC_PLC_PTCP_ELCT_ID||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.DATA_STAT_CD)||'~~'||to_char(YR_ARC_PLC_PTCP_ELCT.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.CRE_USER_NM)||'~~'||to_char(YR_ARC_PLC_PTCP_ELCT.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both YR_ARC_PLC_PTCP_ELCT.LAST_CHG_USER_NM)||'~~'||YR_ARC_PLC_PTCP_ELCT.FARM_YR_ID||'~~'||YR_ARC_PLC_PTCP_ELCT.PGM_YR||'~~'||YR_ARC_PLC_PTCP_ELCT.CROP_ID||'~~'||YR_ARC_PLC_PTCP_ELCT.ARC_PLC_ELCT_CHC_ID||'~~'||trim(both ARC_PLC_ELCT_RS.DMN_VAL_NM)) HASH_DIF
from SQL_FARM_RCD_STG.YR_ARC_PLC_PTCP_ELCT 
left join(select * from EDV.ARC_PLC_ELCT_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) ARC_PLC_ELCT_RS 
ON (YR_ARC_PLC_PTCP_ELCT.ARC_PLC_ELCT_CHC_ID=ARC_PLC_ELCT_RS.DMN_VAL_ID)
where YR_ARC_PLC_PTCP_ELCT.CDC_OPER_CD IN ('I','UN')
And MD5(MD5(upper(coalesce(YR_ARC_PLC_PTCP_ELCT.ST_FSA_CD ,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.CNTY_FSA_CD,'--')||'~~'||coalesce(YR_ARC_PLC_PTCP_ELCT.FARM_NBR ,'--')))||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both YR_ARC_PLC_PTCP_ELCT.FSA_CROP_TYPE_CD), '--')) )
Not IN (Select CROP_FARM_L_ID FROM EDV.CROP_FARM_L )
) stg
LEFT JOIN  EDV.YR_ARC_PLC_PTCP_ELCT_LS dv
ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.YR_ARC_PLC_PTCP_ELCT_LS ls 
				where stg.CROP_FARM_L_ID = ls.CROP_FARM_L_ID 
				and stg.FARM_H_ID = ls.FARM_H_ID 
				and stg.YR_ARC_PLC_PTCP_ELCT_ID = ls.YR_ARC_PLC_PTCP_ELCT_ID 
				and stg.LOAD_DT = ls.LOAD_DT
             )
)
;


