-- Julia Lu edition - will update this paragraph and query when cnsv-cdc is ready
-- Stage SQL: CNSV_EWT84SPRAC (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_EWT84SPRAC/incremental/CNSV_EWT84SPRAC.sql
-- =============================================================================

select * from
(
select distinct sgnp_type_desc,
sgnp_stype_desc,
sgnp_nbr,
sgnp_stype_agr_nm,
cnsv_prac_cd,
n5_pnt_nbr,
long_leaf_pine_ind,
tree_plnt_pdmnt,
wlhd_acrg_ind,
mpl_acrg_ind,
ifsbl_to_farm_auth,
prac_inctv_rt,
wlhd_inctv_rt,
mpl_inctv_rt,
ifsbl_inctv_rt,
crp_sip_auth_ind,
crp_sip_rt,
pip_auth_ind,
pip_rt,
cpld_prac_ind,
wl_rstr_inctv_rt,
prac_wl_rstr_inctv,
max_cnsr_acrg,
max_bdgt_amt,
prac_min_lfsp_ct,
prac_max_lfsp_ct,
pvt_irr_crnr_ind,
noncropland_prac_ind,
sgnp_id,
data_stat_cd,
cre_dt,
last_chg_dt,
last_chg_user_nm,
opymt_alow_ind,
cdc_oper_cd,
load_dt,
data_src_nm,
cdc_dt,
row_number() over ( partition by 
cnsv_prac_cd,
sgnp_id
order by tbl_priority asc, last_chg_dt desc ) as row_num_part
from
(
select 
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt84sprac.cnsv_prac_cd cnsv_prac_cd,
ewt84sprac.n5_pnt_nbr n5_pnt_nbr,
ewt84sprac.long_leaf_pine_ind long_leaf_pine_ind,
ewt84sprac.tree_plnt_pdmnt tree_plnt_pdmnt,
ewt84sprac.wlhd_acrg_ind wlhd_acrg_ind,
ewt84sprac.mpl_acrg_ind mpl_acrg_ind,
ewt84sprac.ifsbl_to_farm_auth ifsbl_to_farm_auth,
ewt84sprac.prac_inctv_rt prac_inctv_rt,
ewt84sprac.wlhd_inctv_rt wlhd_inctv_rt,
ewt84sprac.mpl_inctv_rt mpl_inctv_rt,
ewt84sprac.ifsbl_inctv_rt ifsbl_inctv_rt,
ewt84sprac.crp_sip_auth_ind crp_sip_auth_ind,
ewt84sprac.crp_sip_rt crp_sip_rt,
ewt84sprac.pip_auth_ind pip_auth_ind,
ewt84sprac.pip_rt pip_rt,
ewt84sprac.cpld_prac_ind cpld_prac_ind,
ewt84sprac.wl_rstr_inctv_rt wl_rstr_inctv_rt,
ewt84sprac.prac_wl_rstr_inctv prac_wl_rstr_inctv,
ewt84sprac.max_cnsr_acrg max_cnsr_acrg,
ewt84sprac.max_bdgt_amt max_bdgt_amt,
ewt84sprac.prac_min_lfsp_ct prac_min_lfsp_ct,
ewt84sprac.prac_max_lfsp_ct prac_max_lfsp_ct,
ewt84sprac.pvt_irr_crnr_ind pvt_irr_crnr_ind,
ewt84sprac.ncpld_prac_ind noncropland_prac_ind,
ewt84sprac.sgnp_id sgnp_id,
ewt84sprac.data_stat_cd data_stat_cd,
ewt84sprac.cre_dt cre_dt,
ewt84sprac.last_chg_dt last_chg_dt,
ewt84sprac.last_chg_user_nm last_chg_user_nm,
ewt84sprac.opymt_alow_ind opymt_alow_ind,
ewt84sprac.op as cdc_oper_cd,
current_timestamp() as load_dt,
'cnsv_ewt84sprac' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as tbl_priority
from `fsa-{env}-cnsv-cdc`.`ewt84sprac`
left join `fsa-{env}-cnsv`.`ewt14sgnp` on (ewt84sprac.sgnp_id = ewt14sgnp.sgnp_id)
where ewt84sprac.op <> 'D'
  and ewt84sprac.dart_filedate between '{etl_start_date}' and '{etl_end_date}'

union
select 
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt84sprac.cnsv_prac_cd cnsv_prac_cd,
ewt84sprac.n5_pnt_nbr n5_pnt_nbr,
ewt84sprac.long_leaf_pine_ind long_leaf_pine_ind,
ewt84sprac.tree_plnt_pdmnt tree_plnt_pdmnt,
ewt84sprac.wlhd_acrg_ind wlhd_acrg_ind,
ewt84sprac.mpl_acrg_ind mpl_acrg_ind,
ewt84sprac.ifsbl_to_farm_auth ifsbl_to_farm_auth,
ewt84sprac.prac_inctv_rt prac_inctv_rt,
ewt84sprac.wlhd_inctv_rt wlhd_inctv_rt,
ewt84sprac.mpl_inctv_rt mpl_inctv_rt,
ewt84sprac.ifsbl_inctv_rt ifsbl_inctv_rt,
ewt84sprac.crp_sip_auth_ind crp_sip_auth_ind,
ewt84sprac.crp_sip_rt crp_sip_rt,
ewt84sprac.pip_auth_ind pip_auth_ind,
ewt84sprac.pip_rt pip_rt,
ewt84sprac.cpld_prac_ind cpld_prac_ind,
ewt84sprac.wl_rstr_inctv_rt wl_rstr_inctv_rt,
ewt84sprac.prac_wl_rstr_inctv prac_wl_rstr_inctv,
ewt84sprac.max_cnsr_acrg max_cnsr_acrg,
ewt84sprac.max_bdgt_amt max_bdgt_amt,
ewt84sprac.prac_min_lfsp_ct prac_min_lfsp_ct,
ewt84sprac.prac_max_lfsp_ct prac_max_lfsp_ct,
ewt84sprac.pvt_irr_crnr_ind pvt_irr_crnr_ind,
ewt84sprac.ncpld_prac_ind noncropland_prac_ind,
ewt84sprac.sgnp_id sgnp_id,
ewt84sprac.data_stat_cd data_stat_cd,
ewt84sprac.cre_dt cre_dt,
ewt84sprac.last_chg_dt last_chg_dt,
ewt84sprac.last_chg_user_nm last_chg_user_nm,
ewt84sprac.opymt_alow_ind opymt_alow_ind,
ewt84sprac.op as cdc_oper_cd,
current_timestamp() as load_dt,
'cnsv_ewt84sprac' as data_src_nm,
'{etl_start_date}' as cdc_dt,
2 as tbl_priority
from `fsa-{env}-cnsv`.`ewt14sgnp` 
join `fsa-{env}-cnsv-cdc`.`ewt84sprac` on (ewt14sgnp.sgnp_id = ewt84sprac.sgnp_id)
where ewt84sprac.op <> 'D'
) stg_all
) stg_unq
where row_num_part = 1

union
select distinct
null sgnp_type_desc,
null sgnp_stype_desc,
null sgnp_nbr,
null sgnp_stype_agr_nm,
ewt84sprac.cnsv_prac_cd cnsv_prac_cd,
ewt84sprac.n5_pnt_nbr n5_pnt_nbr,
ewt84sprac.long_leaf_pine_ind long_leaf_pine_ind,
ewt84sprac.tree_plnt_pdmnt tree_plnt_pdmnt,
ewt84sprac.wlhd_acrg_ind wlhd_acrg_ind,
ewt84sprac.mpl_acrg_ind mpl_acrg_ind,
ewt84sprac.ifsbl_to_farm_auth ifsbl_to_farm_auth,
ewt84sprac.prac_inctv_rt prac_inctv_rt,
ewt84sprac.wlhd_inctv_rt wlhd_inctv_rt,
ewt84sprac.mpl_inctv_rt mpl_inctv_rt,
ewt84sprac.ifsbl_inctv_rt ifsbl_inctv_rt,
ewt84sprac.crp_sip_auth_ind crp_sip_auth_ind,
ewt84sprac.crp_sip_rt crp_sip_rt,
ewt84sprac.pip_auth_ind pip_auth_ind,
ewt84sprac.pip_rt pip_rt,
ewt84sprac.cpld_prac_ind cpld_prac_ind,
ewt84sprac.wl_rstr_inctv_rt wl_rstr_inctv_rt,
ewt84sprac.prac_wl_rstr_inctv prac_wl_rstr_inctv,
ewt84sprac.max_cnsr_acrg max_cnsr_acrg,
ewt84sprac.max_bdgt_amt max_bdgt_amt,
ewt84sprac.prac_min_lfsp_ct prac_min_lfsp_ct,
ewt84sprac.prac_max_lfsp_ct prac_max_lfsp_ct,
ewt84sprac.pvt_irr_crnr_ind pvt_irr_crnr_ind,
ewt84sprac.ncpld_prac_ind noncropland_prac_ind,
ewt84sprac.sgnp_id sgnp_id,
ewt84sprac.data_stat_cd data_stat_cd,
ewt84sprac.cre_dt cre_dt,
ewt84sprac.last_chg_dt last_chg_dt,
ewt84sprac.last_chg_user_nm last_chg_user_nm,
ewt84sprac.opymt_alow_ind opymt_alow_ind,
ewt84sprac.op as cdc_oper_cd,
current_timestamp() as load_dt,
'cnsv_ewt84sprac' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as row_num_part
from `fsa-{env}-cnsv-cdc`.`ewt84sprac`
where ewt84sprac.op = 'D'