Merge into
EDV.FARM_YR_HS dv
using(
select DISTINCT 
MD5(upper(coalesce(trim(both FARM_YR.ST_FSA_CD), '--') ||'~~'||coalesce(trim(both FARM_YR.CNTY_FSA_CD), '--') ||'~~'||coalesce(trim(both FARM_YR.FARM_NBR), '--') )) as FARM_H_ID,
FARM_YR.FARM_YR_ID FARM_YR_ID,
FARM_YR.LOAD_DT LOAD_DT,
FARM_YR.CDC_DT DATA_EFF_STRT_DT,
FARM_YR.DATA_SRC_NM DATA_SRC_NM,
FARM_YR.CRE_DT SRC_CRE_DT,
FARM_YR.LAST_CHG_DT SRC_LAST_CHG_DT,
FARM_YR.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
FARM_YR.FARM_ID FARM_ID,
FARM_YR.TM_PRD_ID TM_PRD_ID,
FARM_YR.PGM_YR PGM_YR,
FARM_YR.CRP_ACRG CRP_ACRG,
FARM_YR.MPL_ACRG MPL_ACRG,
FARM_YR.DATA_STAT_CD DATA_STAT_CD,
FARM_YR.VER_NBR VER_NBR,
FARM_YR.ARC_PLC_ELG_DTER_CD ARC_PLC_ELG_DTER_CD,
FARM_YR.ARC_PLC_ELG_DTER_ID ARC_PLC_ELG_DTER_ID,
FARM_YR.CDC_OPER_CD,
MD5(trim(both FARM_YR.ST_FSA_CD)||'~~'||trim(both FARM_YR.CNTY_FSA_CD)||'~~'||trim(both FARM_YR.FARM_NBR)||'~~'||FARM_YR.FARM_YR_ID||'~~'||to_char(FARM_YR.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(FARM_YR.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both FARM_YR.LAST_CHG_USER_NM)||'~~'||FARM_YR.FARM_ID||'~~'||FARM_YR.TM_PRD_ID||'~~'||FARM_YR.PGM_YR||'~~'||FARM_YR.CRP_ACRG||'~~'||FARM_YR.MPL_ACRG||'~~'||trim(both FARM_YR.DATA_STAT_CD)||'~~'||FARM_YR.VER_NBR||'~~'||trim(both FARM_YR.ARC_PLC_ELG_DTER_CD)||'~~'||FARM_YR.ARC_PLC_ELG_DTER_ID) HASH_DIF
FROM SQL_FARM_RCD_STG.FARM_YR FARM_YR
where FARM_YR.CDC_OPER_CD = 'D'
order by FARM_YR.CDC_DT)
stg
 on ( 
coalesce(stg.FARM_YR_ID,0) = coalesce(dv.FARM_YR_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN
INSERT(
FARM_H_ID,
FARM_YR_ID,
LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
FARM_ID,
TM_PRD_ID,
PGM_YR,
CRP_ACRG,
MPL_ACRG,
DATA_STAT_CD,
VER_NBR,
ARC_PLC_ELG_DTER_CD,
ARC_PLC_ELG_DTER_ID, 
DATA_EFF_END_DT,
LOAD_END_DT,
HASH_DIF)
VALUES (
stg.FARM_H_ID,
stg.FARM_YR_ID,
stg.LOAD_DT,
stg.DATA_EFF_STRT_DT,
stg.DATA_SRC_NM,
stg.SRC_CRE_DT,
stg.SRC_LAST_CHG_DT,
stg.SRC_LAST_CHG_USER_NM,
stg.FARM_ID,
stg.TM_PRD_ID,
stg.PGM_YR,
stg.CRP_ACRG,
stg.MPL_ACRG,
stg.DATA_STAT_CD,
stg.VER_NBR,
stg.ARC_PLC_ELG_DTER_CD,
stg.ARC_PLC_ELG_DTER_ID,
stg.DATA_EFF_STRT_DT,
stg.LOAD_DT,
stg.HASH_DIF
);