INSERT into
EDV.CROP_FARM_YR_DCP_LS(
CROP_FARM_L_ID
, CROP_FARM_YR_DCP_ID
, LOAD_DT
, DATA_EFF_STRT_DT
, DATA_SRC_NM
, DATA_STAT_CD
, SRC_CRE_DT
, SRC_LAST_CHG_DT
, SRC_LAST_CHG_USER_NM
, FARM_YR_DCP_ID
, CROP_ID
, CRP_RDN_ACRG
, CRP_REL_ACRG
, CCP_PYMT_YLD
, DIR_PYMT_YLD
, PGM_YR
, DATA_EFF_END_DT
, LOAD_END_DT
, HASH_DIF)
(
SELECT stg.* 
from (
SELECT DISTINCT 
MD5(MD5(upper(coalesce(CROP_FARM_YR_DCP.ST_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_DCP.FARM_NBR,'--')))||'~~'||upper(coalesce(trim(both CROP_FARM_YR_DCP.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_DCP.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_DCP.FSA_CROP_TYPE_CD), '--')) ) as CROP_FARM_L_ID
, CROP_FARM_YR_DCP.CROP_FARM_YR_DCP_ID CROP_FARM_YR_DCP_ID
, CROP_FARM_YR_DCP.LOAD_DT LOAD_DT
, CROP_FARM_YR_DCP.CDC_DT DATA_EFF_STRT_DT
, CROP_FARM_YR_DCP.DATA_SRC_NM DATA_SRC_NM
, CROP_FARM_YR_DCP.DATA_STAT_CD DATA_STAT_CD
, CROP_FARM_YR_DCP.CRE_DT SRC_CRE_DT
, CROP_FARM_YR_DCP.LAST_CHG_DT SRC_LAST_CHG_DT
, CROP_FARM_YR_DCP.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
, CROP_FARM_YR_DCP.FARM_YR_DCP_ID FARM_YR_DCP_ID
, CROP_FARM_YR_DCP.CROP_ID CROP_ID
, CROP_FARM_YR_DCP.CRP_RDN_ACRG CRP_RDN_ACRG
, CROP_FARM_YR_DCP.CRP_REL_ACRG CRP_REL_ACRG
, CROP_FARM_YR_DCP.CCP_PYMT_YLD CCP_PYMT_YLD
, CROP_FARM_YR_DCP.DIR_PYMT_YLD DIR_PYMT_YLD
, CROP_FARM_YR_DCP.PGM_YR PGM_YR 
, to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT
, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT
, MD5(upper(coalesce(CROP_FARM_YR_DCP.ST_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_DCP.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_DCP.FARM_NBR,'--'))||'~~'||trim(both CROP_FARM_YR_DCP.PGM_ABR)||'~~'||trim(both CROP_FARM_YR_DCP.FSA_CROP_CD)||'~~'||trim(both CROP_FARM_YR_DCP.FSA_CROP_TYPE_CD)||'~~'||CROP_FARM_YR_DCP.CROP_FARM_YR_DCP_ID||'~~'||trim(both CROP_FARM_YR_DCP.DATA_STAT_CD)||'~~'||to_char(CROP_FARM_YR_DCP.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(CROP_FARM_YR_DCP.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_FARM_YR_DCP.LAST_CHG_USER_NM)||'~~'||CROP_FARM_YR_DCP.FARM_YR_DCP_ID||'~~'||CROP_FARM_YR_DCP.CROP_ID||'~~'||CROP_FARM_YR_DCP.CRP_RDN_ACRG||'~~'||CROP_FARM_YR_DCP.CRP_REL_ACRG||'~~'||CROP_FARM_YR_DCP.CCP_PYMT_YLD||'~~'||CROP_FARM_YR_DCP.DIR_PYMT_YLD||'~~'||CROP_FARM_YR_DCP.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.CROP_FARM_YR_DCP  CROP_FARM_YR_DCP
where CROP_FARM_YR_DCP.CDC_OPER_CD IN ('I','UN')
order by CROP_FARM_YR_DCP.CDC_DT
) stg
 LEFT JOIN  EDV.CROP_FARM_YR_DCP_LS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.CROP_FARM_YR_DCP_LS ls
			where stg.crop_farm_l_id = ls.crop_farm_l_id
			and stg.crop_farm_yr_dcp_id = ls.crop_farm_yr_dcp_id
			and stg.load_dt = ls.load_dt
		   )
);