Merge into
EDV.TR_RCON_LS dv
using(select DISTINCT 
MD5(MD5(upper(coalesce(TR_RCON.PRNT_ST_FSA_CD ,'--')||'~~'||coalesce(TR_RCON.PRNT_CNTY_FSA_CD,'--')||'~~'||coalesce(TR_RCON.PRNT_TR_NBR, '-1')))||'~~'||MD5(upper(coalesce(TR_RCON.RSLT_ST_FSA_CD ,'--')||'~~'||coalesce(TR_RCON.RSLT_CNTY_FSA_CD,'--')||'~~'||coalesce(TR_RCON.RSLT_TR_NBR, '-1')))) TR_RCON_L_ID,
TR_RCON.TR_RCON_ID TR_RCON_ID,TR_RCON.LOAD_DT LOAD_DT,TR_RCON.CDC_DT DATA_EFF_STRT_DT,TR_RCON.DATA_SRC_NM DATA_SRC_NM,TR_RCON.DATA_STAT_CD DATA_STAT_CD,TR_RCON.CRE_DT SRC_CRE_DT,TR_RCON.LAST_CHG_DT SRC_LAST_CHG_DT,TR_RCON.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_RCON.RCON_ID RCON_ID,TR_RCON.PRNT_TR_YR_ID PRNT_TR_YR_ID,TR_RCON.RSLT_TR_YR_ID RSLT_TR_YR_ID,TR_RCON.PGM_YR PGM_YR ,
TR_RCON.CDC_OPER_CD,
MD5(upper(coalesce(TR_RCON.PRNT_ST_FSA_CD ,'--')||'~~'||coalesce(TR_RCON.PRNT_CNTY_FSA_CD,'--')||'~~'||coalesce(TR_RCON.PRNT_TR_NBR, '-1'))||'~~'||upper(coalesce(TR_RCON.RSLT_ST_FSA_CD ,'--')||'~~'||coalesce(TR_RCON.RSLT_CNTY_FSA_CD,'--')||'~~'||coalesce(TR_RCON.RSLT_TR_NBR, '-1'))||'~~'||TR_RCON.TR_RCON_ID||'~~'||trim(both TR_RCON.DATA_STAT_CD)||'~~'||to_char(TR_RCON.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TR_RCON.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_RCON.LAST_CHG_USER_NM)||'~~'||TR_RCON.RCON_ID||'~~'||TR_RCON.PRNT_TR_YR_ID||'~~'||TR_RCON.RSLT_TR_YR_ID||'~~'||TR_RCON.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.TR_RCON  TR_RCON
where TR_RCON.CDC_OPER_CD IN ('I','UN')
order by TR_RCON.CDC_DT)
stg
 on ( 
coalesce(stg.TR_RCON_ID,0) = coalesce(dv.TR_RCON_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;