INSERT into
EDV.TR_RCON_LS(TR_RCON_L_ID,TR_RCON_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
RCON_ID,
PRNT_TR_YR_ID,
RSLT_TR_YR_ID,
PGM_YR, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(SELECT stg.* from (SELECT DISTINCT 
MD5(MD5(upper(coalesce(TR_RCON.PRNT_ST_FSA_CD ,'--')||'~~'||coalesce(TR_RCON.PRNT_CNTY_FSA_CD,'--')||'~~'||coalesce(TR_RCON.PRNT_TR_NBR, '-1')))||'~~'||MD5(upper(coalesce(TR_RCON.RSLT_ST_FSA_CD ,'--')||'~~'||coalesce(TR_RCON.RSLT_CNTY_FSA_CD,'--')||'~~'||coalesce(TR_RCON.RSLT_TR_NBR, '-1')))) TR_RCON_L_ID,
TR_RCON.TR_RCON_ID TR_RCON_ID,TR_RCON.LOAD_DT LOAD_DT,TR_RCON.CDC_DT DATA_EFF_STRT_DT,TR_RCON.DATA_SRC_NM DATA_SRC_NM,TR_RCON.DATA_STAT_CD DATA_STAT_CD,TR_RCON.CRE_DT SRC_CRE_DT,TR_RCON.LAST_CHG_DT SRC_LAST_CHG_DT,TR_RCON.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_RCON.RCON_ID RCON_ID,TR_RCON.PRNT_TR_YR_ID PRNT_TR_YR_ID,TR_RCON.RSLT_TR_YR_ID RSLT_TR_YR_ID,TR_RCON.PGM_YR PGM_YR ,
to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(upper(coalesce(TR_RCON.PRNT_ST_FSA_CD ,'--')||'~~'||coalesce(TR_RCON.PRNT_CNTY_FSA_CD,'--')||'~~'||coalesce(TR_RCON.PRNT_TR_NBR, '-1'))||'~~'||upper(coalesce(TR_RCON.RSLT_ST_FSA_CD ,'--')||'~~'||coalesce(TR_RCON.RSLT_CNTY_FSA_CD,'--')||'~~'||coalesce(TR_RCON.RSLT_TR_NBR, '-1'))||'~~'||TR_RCON.TR_RCON_ID||'~~'||trim(both TR_RCON.DATA_STAT_CD)||'~~'||to_char(TR_RCON.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TR_RCON.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_RCON.LAST_CHG_USER_NM)||'~~'||TR_RCON.RCON_ID||'~~'||TR_RCON.PRNT_TR_YR_ID||'~~'||TR_RCON.RSLT_TR_YR_ID||'~~'||TR_RCON.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.TR_RCON  TR_RCON
 where TR_RCON.CDC_OPER_CD IN ('I','UN')
order by TR_RCON.CDC_DT
) stg
 LEFT JOIN  EDV.TR_RCON_LS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.TR_RCON_LS ls
				where stg.TR_RCON_L_ID = ls.TR_RCON_L_ID
				and stg.TR_RCON_ID = ls.TR_RCON_ID
				and stg.LOAD_DT = ls.LOAD_DT
			)
)
;

