INSERT INTO EDV.CLU_PRDR_YR_LS(
	CLU_PRDR_L_ID
	, CLU_PRDR_YR_ID
	, LOAD_DT
	, DATA_EFF_STRT_DT
	, DATA_SRC_NM
	, DATA_STAT_CD
	, SRC_CRE_DT
	, SRC_LAST_CHG_DT
	, SRC_LAST_CHG_USER_NM
	, CLU_YR_ID
	, CORE_CUST_ID
	, SRC_PRDR_INVL_CD
	, PRDR_INVL_NM
	, SRC_CLU_PRDR_HEL_EXCP_CD
	, CLU_PRDR_HEL_EXCP_NM
	, SRC_CLU_PRDR_CW_EXCP_CD
	, CLU_PRDR_CW_EXCP_NM
	, SRC_CLU_PRDR_PCW_EXCP_CD
	, CLU_PRDR_PCW_EXCP_NM
	, PGM_YR
	, DATA_EFF_END_DT
	, LOAD_END_DT
	, HASH_DIF
	, HEL_APLS_EXHST_DT
	, CW_APLS_EXHST_DT
	, PCW_APLS_EXHST_DT
	, CLU_PRDR_RMA_HEL_EXCP_CD
	, CLU_PRDR_RMA_CW_EXCP_CD
	, CLU_PRDR_RMA_PCW_EXCP_CD
	)
(
SELECT  STG.*
FROM (
SELECT DISTINCT 
	MD5( coalesce(CPY.CORE_CUST_ID, '-1') ||'~~'|| MD5(UPPER(coalesce(CPY.ST_FSA_CD,'--')||'~~'||coalesce(CPY.CNTY_FSA_CD,'--')||'~~'||coalesce(CPY.FARM_NBR,'--')))||'~~'|| MD5(UPPER(coalesce(CPY.ST_FSA_CD,'--')||'~~'||coalesce(CPY.CNTY_FSA_CD,'--')||'~~'||coalesce((CPY.TR_NBR)::numeric ,-1))) ) CLU_PRDR_L_ID
    , CPY.CLU_PRDR_YR_ID CLU_PRDR_YR_ID
	, CPY.LOAD_DT LOAD_DT
    , CPY.CDC_DT DATA_EFF_STRT_DT
    , CPY.DATA_SRC_NM DATA_SRC_NM
    , CPY.DATA_STAT_CD DATA_STAT_CD
    , CPY.CRE_DT SRC_CRE_DT
    , CPY.LAST_CHG_DT SRC_LAST_CHG_DT
    , CPY.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
    , CPY.CLU_YR_ID CLU_YR_ID
    , CPY.CORE_CUST_ID CORE_CUST_ID
    , CPY.PRDR_INVL_CD SRC_PRDR_INVL_CD
    , PIRS.DMN_VAL_NM PRDR_INVL_NM
    , CPY.CLU_PRDR_HEL_EXCP_CD SRC_CLU_PRDR_HEL_EXCP_CD
    , FPHERS.DMN_VAL_NM CLU_PRDR_HEL_EXCP_NM
    , CPY.CLU_PRDR_CW_EXCP_CD SRC_CLU_PRDR_CW_EXCP_CD
    , FPCERS.DMN_VAL_NM CLU_PRDR_CW_EXCP_NM
    , CPY.CLU_PRDR_PCW_EXCP_CD SRC_CLU_PRDR_PCW_EXCP_CD
    , FPPERS.DMN_VAL_NM CLU_PRDR_PCW_EXCP_NM
    , CPY.PGM_YR PGM_YR
    , TO_DATE('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT
    , TO_DATE('9999-12-31','YYYY-MM-DD') LOAD_END_DT
    , MD5(CPY.CORE_CUST_ID||'~~'||UPPER(coalesce(CPY.ST_FSA_CD,'--')||'~~'||coalesce(CPY.CNTY_FSA_CD,'--')||'~~'||coalesce(CPY.FARM_NBR,'--'))||'~~'||UPPER(coalesce(CPY.ST_FSA_CD,'--')||'~~'||coalesce(CPY.CNTY_FSA_CD,'--')||'~~'||coalesce((CPY.TR_NBR)::numeric ,-1))||'~~'||CPY.CLU_PRDR_YR_ID||'~~'||trim(both CPY.DATA_STAT_CD)||'~~'||TO_CHAR(CPY.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(CPY.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CPY.LAST_CHG_USER_NM)||'~~'||CPY.CLU_YR_ID||'~~'||CPY.PRDR_INVL_CD||'~~'||PIRS.DMN_VAL_NM||'~~'||CPY.CLU_PRDR_HEL_EXCP_CD||'~~'||FPHERS.DMN_VAL_NM||'~~'||CPY.CLU_PRDR_CW_EXCP_CD||'~~'||FPCERS.DMN_VAL_NM||'~~'||CPY.CLU_PRDR_PCW_EXCP_CD||'~~'||FPPERS.DMN_VAL_NM||'~~'||CPY.PGM_YR||'~~'||TO_CHAR(CPY.HEL_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(CPY.CW_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(CPY.PCW_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US')||'~~'||CPY.CLU_PRDR_RMA_HEL_EXCP_CD||'~~'||CPY.CLU_PRDR_RMA_CW_EXCP_CD||'~~'||CPY.CLU_PRDR_RMA_PCW_EXCP_CD) HASH_DIF
    , CPY.HEL_APLS_EXHST_DT
    , CPY.CW_APLS_EXHST_DT
    , CPY.PCW_APLS_EXHST_DT
    , CPY.CLU_PRDR_RMA_HEL_EXCP_CD
    , CPY.CLU_PRDR_RMA_CW_EXCP_CD
    , CPY.CLU_PRDR_RMA_PCW_EXCP_CD
FROM SQL_FARM_RCD_STG.CLU_PRDR_YR CPY
LEFT JOIN(
    SELECT * FROM EDV.FLD_PRDR_CW_EXCP_RS WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FPCERS 
ON (CPY.CLU_PRDR_CW_EXCP_CD = FPCERS.DMN_VAL_ID)
LEFT JOIN(
    SELECT * FROM EDV.FLD_PRDR_HEL_EXCP_RS WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FPHERS 
ON (CPY.CLU_PRDR_HEL_EXCP_CD = FPHERS.DMN_VAL_ID) 
LEFT JOIN(
    SELECT * FROM EDV.FLD_PRDR_PCW_EXCP_RS WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FPPERS 
ON (CPY.CLU_PRDR_PCW_EXCP_CD = FPPERS.DMN_VAL_ID) 
LEFT JOIN(
    SELECT * FROM EDV.PRDR_INVL_RS WHERE LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) PIRS 
ON (CPY.PRDR_INVL_CD= PIRS.DMN_VAL_ID)
WHERE CPY.CDC_OPER_CD IN ('I','UN')
ORDER BY  CPY.CDC_DT
) STG
LEFT JOIN  EDV.CLU_PRDR_YR_LS DV 
ON (STG.HASH_DIF = DV.HASH_DIF AND DV.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD'))
WHERE DV.HASH_DIF IS NULL
and not exists ( select distinct clu_prdr_l_id from EDV.CLU_PRDR_YR_LS ls
				 where STG.clu_prdr_l_id = ls.clu_prdr_l_id
				 and STG.clu_prdr_yr_id = ls.clu_prdr_yr_id
				 and STG.load_dt = ls.load_dt
	           )
);