MERGE INTO EDV.CLU_PRDR_YR_LS DV
USING(
    SELECT      DISTINCT
                MD5(coalesce(CLU_PRDR_YR.CORE_CUST_ID, '-1') ||'~~'||MD5(UPPER(coalesce(CLU_PRDR_YR.ST_FSA_CD,'--')||'~~'||coalesce(CLU_PRDR_YR.CNTY_FSA_CD,'--')||'~~'||coalesce(CLU_PRDR_YR.FARM_NBR,'--')))||'~~'||MD5(UPPER(coalesce(CLU_PRDR_YR.ST_FSA_CD,'--')||'~~'||coalesce(CLU_PRDR_YR.CNTY_FSA_CD,'--')||'~~'||coalesce((CLU_PRDR_YR.TR_NBR)::numeric ,-1)))) CLU_PRDR_L_ID
                ,CLU_PRDR_YR.CLU_PRDR_YR_ID CLU_PRDR_YR_ID
                ,CLU_PRDR_YR.LOAD_DT LOAD_DT
                ,CLU_PRDR_YR.CDC_DT DATA_EFF_STRT_DT
                ,CLU_PRDR_YR.DATA_SRC_NM DATA_SRC_NM
                ,CLU_PRDR_YR.DATA_STAT_CD DATA_STAT_CD
                ,CLU_PRDR_YR.CRE_DT SRC_CRE_DT
                ,CLU_PRDR_YR.LAST_CHG_DT SRC_LAST_CHG_DT
                ,CLU_PRDR_YR.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
                ,CLU_PRDR_YR.CLU_YR_ID CLU_YR_ID
                ,CLU_PRDR_YR.CORE_CUST_ID CORE_CUST_ID
                ,CLU_PRDR_YR.PRDR_INVL_CD SRC_PRDR_INVL_CD
                ,PRDR_INVL_RS.DMN_VAL_NM PRDR_INVL_NM
                ,CLU_PRDR_YR.CLU_PRDR_HEL_EXCP_CD SRC_CLU_PRDR_HEL_EXCP_CD
                ,FLD_PRDR_HEL_EXCP_RS.DMN_VAL_NM CLU_PRDR_HEL_EXCP_NM
                ,CLU_PRDR_YR.CLU_PRDR_CW_EXCP_CD SRC_CLU_PRDR_CW_EXCP_CD
                ,FLD_PRDR_CW_EXCP_RS.DMN_VAL_NM CLU_PRDR_CW_EXCP_NM
                ,CLU_PRDR_YR.CLU_PRDR_PCW_EXCP_CD SRC_CLU_PRDR_PCW_EXCP_CD
                ,FLD_PRDR_PCW_EXCP_RS.DMN_VAL_NM CLU_PRDR_PCW_EXCP_NM
                ,CLU_PRDR_YR.PGM_YR PGM_YR
                ,CLU_PRDR_YR.CDC_OPER_CD
                ,MD5(CLU_PRDR_YR.CORE_CUST_ID||'~~'||UPPER(coalesce(CLU_PRDR_YR.ST_FSA_CD,'--')||'~~'||coalesce(CLU_PRDR_YR.CNTY_FSA_CD,'--')||'~~'||coalesce(CLU_PRDR_YR.FARM_NBR,'--'))||'~~'||UPPER(coalesce(CLU_PRDR_YR.ST_FSA_CD,'--')||'~~'||coalesce(CLU_PRDR_YR.CNTY_FSA_CD,'--')||'~~'||coalesce((CLU_PRDR_YR.TR_NBR)::numeric ,-1))||'~~'||CLU_PRDR_YR.CLU_PRDR_YR_ID||'~~'||trim(both CLU_PRDR_YR.DATA_STAT_CD)||'~~'||TO_CHAR(CLU_PRDR_YR.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(CLU_PRDR_YR.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CLU_PRDR_YR.LAST_CHG_USER_NM)||'~~'||CLU_PRDR_YR.CLU_YR_ID||'~~'||CLU_PRDR_YR.PRDR_INVL_CD||'~~'||PRDR_INVL_RS.DMN_VAL_NM||'~~'||CLU_PRDR_YR.CLU_PRDR_HEL_EXCP_CD||'~~'||FLD_PRDR_HEL_EXCP_RS.DMN_VAL_NM||'~~'||CLU_PRDR_YR.CLU_PRDR_CW_EXCP_CD||'~~'||FLD_PRDR_CW_EXCP_RS.DMN_VAL_NM||'~~'||CLU_PRDR_YR.CLU_PRDR_PCW_EXCP_CD||'~~'||FLD_PRDR_PCW_EXCP_RS.DMN_VAL_NM||'~~'||CLU_PRDR_YR.PGM_YR||'~~'||TO_CHAR(CLU_PRDR_YR.HEL_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(CLU_PRDR_YR.CW_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US')||'~~'||TO_CHAR(CLU_PRDR_YR.PCW_APLS_EXHST_DT, 'YYYY-MM-DD HH24:MI:SS.US')||'~~'||CLU_PRDR_YR.CLU_PRDR_RMA_HEL_EXCP_CD||'~~'||CLU_PRDR_YR.CLU_PRDR_RMA_CW_EXCP_CD||'~~'||CLU_PRDR_YR.CLU_PRDR_RMA_PCW_EXCP_CD) HASH_DIF
                ,CLU_PRDR_YR.HEL_APLS_EXHST_DT
                ,CLU_PRDR_YR.CW_APLS_EXHST_DT
                ,CLU_PRDR_YR.PCW_APLS_EXHST_DT
                ,CLU_PRDR_YR.CLU_PRDR_RMA_HEL_EXCP_CD
                ,CLU_PRDR_YR.CLU_PRDR_RMA_CW_EXCP_CD
                ,CLU_PRDR_YR.CLU_PRDR_RMA_PCW_EXCP_CD
    FROM        SQL_FARM_RCD_STG.CLU_PRDR_YR
                LEFT JOIN(
                    SELECT      *
                    FROM        EDV.FLD_PRDR_CW_EXCP_RS
                    WHERE       LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
                ) FLD_PRDR_CW_EXCP_RS 
                ON (CLU_PRDR_YR.CLU_PRDR_CW_EXCP_CD = FLD_PRDR_CW_EXCP_RS.DMN_VAL_ID)  
                LEFT JOIN(
                    SELECT      *
                    FROM        EDV.FLD_PRDR_HEL_EXCP_RS
                    WHERE       LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
                ) FLD_PRDR_HEL_EXCP_RS 
               ON (CLU_PRDR_YR.CLU_PRDR_HEL_EXCP_CD = FLD_PRDR_HEL_EXCP_RS.DMN_VAL_ID)  
               LEFT JOIN(
                    SELECT      *
                    FROM        EDV.FLD_PRDR_PCW_EXCP_RS
                    WHERE       LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
               ) FLD_PRDR_PCW_EXCP_RS 
               ON (CLU_PRDR_YR.CLU_PRDR_PCW_EXCP_CD = FLD_PRDR_PCW_EXCP_RS.DMN_VAL_ID) 
               LEFT JOIN(
                    SELECT      * 
                    FROM        EDV.PRDR_INVL_RS
                    WHERE       LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
               ) PRDR_INVL_RS 
               ON (CLU_PRDR_YR.PRDR_INVL_CD= PRDR_INVL_RS.DMN_VAL_ID)
    WHERE      CLU_PRDR_YR.CDC_OPER_CD='D'
    ORDER BY CLU_PRDR_YR.CDC_DT
) STG ON ( coalesce(STG.CLU_PRDR_YR_ID,0) = coalesce(DV.CLU_PRDR_YR_ID,0) ) 
WHEN MATCHED AND DV.LOAD_DT <> STG.LOAD_DT AND DV.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') THEN 
UPDATE SET LOAD_END_DT = STG.LOAD_DT, DATA_EFF_END_DT = STG.DATA_EFF_STRT_DT
WHEN NOT MATCHED THEN
    INSERT(
        CLU_PRDR_L_ID,CLU_PRDR_YR_ID,LOAD_DT,
        DATA_EFF_STRT_DT,
        DATA_SRC_NM,
        DATA_STAT_CD,
        SRC_CRE_DT,
        SRC_LAST_CHG_DT,
        SRC_LAST_CHG_USER_NM,
        CLU_YR_ID,
        CORE_CUST_ID,
        SRC_PRDR_INVL_CD,
        PRDR_INVL_NM,
        SRC_CLU_PRDR_HEL_EXCP_CD,
        CLU_PRDR_HEL_EXCP_NM,
        SRC_CLU_PRDR_CW_EXCP_CD,
        CLU_PRDR_CW_EXCP_NM,
        SRC_CLU_PRDR_PCW_EXCP_CD,
        CLU_PRDR_PCW_EXCP_NM,
        PGM_YR, 
        DATA_EFF_END_DT,LOAD_END_DT,
        HASH_DIF,
        HEL_APLS_EXHST_DT,
        CW_APLS_EXHST_DT,
        PCW_APLS_EXHST_DT,
        CLU_PRDR_RMA_HEL_EXCP_CD,
        CLU_PRDR_RMA_CW_EXCP_CD,
        CLU_PRDR_RMA_PCW_EXCP_CD
    )
    VALUES (
        STG.CLU_PRDR_L_ID,STG.CLU_PRDR_YR_ID,STG.LOAD_DT,STG.DATA_EFF_STRT_DT,STG.DATA_SRC_NM,STG.DATA_STAT_CD,STG.SRC_CRE_DT,STG.SRC_LAST_CHG_DT,STG.SRC_LAST_CHG_USER_NM,STG.CLU_YR_ID,STG.CORE_CUST_ID,STG.SRC_PRDR_INVL_CD,STG.PRDR_INVL_NM,STG.SRC_CLU_PRDR_HEL_EXCP_CD,STG.CLU_PRDR_HEL_EXCP_NM,STG.SRC_CLU_PRDR_CW_EXCP_CD,STG.CLU_PRDR_CW_EXCP_NM,STG.SRC_CLU_PRDR_PCW_EXCP_CD,STG.CLU_PRDR_PCW_EXCP_NM,STG.PGM_YR,
        STG.DATA_EFF_STRT_DT,STG.LOAD_DT,STG.HASH_DIF,STG.HEL_APLS_EXHST_DT,STG.CW_APLS_EXHST_DT,STG.PCW_APLS_EXHST_DT,STG.CLU_PRDR_RMA_HEL_EXCP_CD,STG.CLU_PRDR_RMA_CW_EXCP_CD,STG.CLU_PRDR_RMA_PCW_EXCP_CD
    );