Merge into 
EDV.CROP_FARM_YR_ADJ_IRR_LS dv
using(select DISTINCT 
MD5(upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_TYPE_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD), '--')) ||'~~'||MD5(upper(coalesce(CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.FARM_NBR ,'--')))) FARM_CROP_IRR_HIST_L_ID,
coalesce(CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_ID, 0) CROP_FARM_YR_MNG_VAL_ADJ_ID,CROP_FARM_YR_MNG_VAL_ADJ.LOAD_DT LOAD_DT,CROP_FARM_YR_MNG_VAL_ADJ.CDC_DT DATA_EFF_STRT_DT,CROP_FARM_YR_MNG_VAL_ADJ.DATA_SRC_NM DATA_SRC_NM,CROP_FARM_YR_MNG_VAL_ADJ.DATA_STAT_CD DATA_STAT_CD,CROP_FARM_YR_MNG_VAL_ADJ.CRE_DT SRC_CRE_DT,CROP_FARM_YR_MNG_VAL_ADJ.CRE_USER_NM SRC_CRE_USER_NM,CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_DT SRC_LAST_CHG_DT,CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,CROP_FARM_YR_MNG_VAL_ADJ.FARM_YR_CROP_IRR_HIST_ID FARM_YR_CROP_IRR_HIST_ID,CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY SRC_CROP_FARM_YR_ADJ_TYPE_CD,FARM_CROP_ADJ_TYPE_RS.DMN_VAL_NM CROP_FARM_YR_ADJ_TYPE_NM,CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_RS SRC_CROP_FARM_YR_ADJ_RSN_CD,CROP_FARM_YR_MNG_VAL_ADJ.AFT_ADJ_VAL AFT_ADJ_VAL,CROP_FARM_YR_MNG_VAL_ADJ.BEF_ADJ_VAL BEF_ADJ_VAL,CROP_FARM_YR_MNG_VAL_ADJ.PGM_YR PGM_YR ,
CROP_FARM_YR_MNG_VAL_ADJ.CDC_OPER_CD,
MD5(trim(both CROP_FARM_YR_MNG_VAL_ADJ.PGM_ABR)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_CD)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_TYPE_CD)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD)||'~~'||upper(coalesce(CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.FARM_NBR,'--'))||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_ID||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.DATA_STAT_CD)||'~~'||to_char(CROP_FARM_YR_MNG_VAL_ADJ.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.CRE_USER_NM)||'~~'||to_char(CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_USER_NM)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.FARM_YR_CROP_IRR_HIST_ID||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY||'~~'||trim(both FARM_CROP_ADJ_TYPE_RS.DMN_VAL_NM)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_RS||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.AFT_ADJ_VAL||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.BEF_ADJ_VAL||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.CROP_FARM_YR_MNG_VAL_ADJ  CROP_FARM_YR_MNG_VAL_ADJ JOIN 
     EDV.FARM_CROP_ADJ_TYPE_RS  FARM_CROP_ADJ_TYPE_RS ON ( CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY = FARM_CROP_ADJ_TYPE_RS.DMN_VAL_ID  )
WHERE CROP_FARM_YR_MNG_VAL_ADJ.FARM_YR_CROP_IRR_HIST_ID IS NOT NULL and CROP_FARM_YR_MNG_VAL_ADJ.CDC_OPER_CD IN ('I','UN')
order by CROP_FARM_YR_MNG_VAL_ADJ.CDC_DT)
stg
 on ( 
coalesce(stg.CROP_FARM_YR_MNG_VAL_ADJ_ID,0) = coalesce(dv.CROP_FARM_YR_MNG_VAL_ADJ_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;