INSERT INTO CAR_DM_STG.CNTY_CROP_ACRG_RPT_PRMPT
(CRE_DT,
PGM_YR,
ADM_ST_NM,
ADM_CNTY_NM,
FSA_CROP_NM,
FSA_CROP_TYPE_NM
)
SELECT DISTINCT current_date as cur_dt
           ,T185.PGM_YR  AS PGM_YR                       
           ,T1195.ST_NM AS ST_NM
           ,T1195.CNTY_NM AS CNTY_NM                   
           ,T1182.FSA_CROP_NM AS FSA_CROP_NM
           ,T1182.FSA_CROP_TYPE_NM AS FSA_CROP_TYPE_NM
     FROM  
(   cmn_dim_dm_stg.FSA_CROP_TYPE_DIM T1182 /* ALS_FSA_CROP_TYPE_DIM */
   INNER JOIN
(   cmn_dim_dm_stg.FSA_ST_CNTY_DIM T1195 /* ALS_ADMIN_FSA_ST_CNTY_DIM */
INNER JOIN
CAR_DM_STG.AG_PROD_PLAN_FACT T185 /* ALS_ AG_PROD_PLAN_FACT */
ON T185.ADM_FSA_ST_CNTY_DURB_ID =T1195.FSA_ST_CNTY_DURB_ID)
ON T185.FSA_CROP_DURB_ID =T1182.FSA_CROP_DURB_ID) 
WHERE  
    T185.SRC_DATA_STAT_CD = 'A'
    AND T1182.CUR_RCD_IND = 1
    AND T1195.CUR_RCD_IND = 1