SELECT CNSV_PYMT_TYPE,
ACCT_PGM_CD,
PYMT_TYPE_ID,
PGM_HRCH_LVL_ID,
ACCT_PGM_ID,
CNSV_PYMT_TYPE_NM,
HRCH_LVL_NM,
OO_CLS_FULL_NM,
APP_CD,
APP_SYS_CD,
ACCT_TXN_CD,
ACCT_REF_1_CD,
ACCT_REF_2_CD,
ACCT_PGM_CD_DESC,
APP_ACCT_ID,
PYMT_IMPL_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT CNSV_PYMT_TYPE,
ACCT_PGM_CD,
PYMT_TYPE_ID,
PGM_HRCH_LVL_ID,
ACCT_PGM_ID,
CNSV_PYMT_TYPE_NM,
HRCH_LVL_NM,
OO_CLS_FULL_NM,
APP_CD,
APP_SYS_CD,
ACCT_TXN_CD,
ACCT_REF_1_CD,
ACCT_REF_2_CD,
ACCT_PGM_CD_DESC,
APP_ACCT_ID,
PYMT_IMPL_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
PYMT_TYPE_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
payment_type.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
payment_type.ACCT_PGM_CD ACCT_PGM_CD,
payment_type.PYMT_TYPE_ID PYMT_TYPE_ID,
payment_type.PGM_HRCH_LVL_ID PGM_HRCH_LVL_ID,
payment_type.ACCT_PGM_ID ACCT_PGM_ID,
payment_type.CNSV_PYMT_TYPE_NM CNSV_PYMT_TYPE_NM,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
payment_type.OO_CLS_FULL_NM OO_CLS_FULL_NM,
payment_type.APP_CD APP_CD,
payment_type.APP_SYS_CD APP_SYS_CD,
payment_type.ACCT_TXN_CD ACCT_TXN_CD,
payment_type.ACCT_REF_1_CD ACCT_REF_1_CD,
payment_type.ACCT_REF_2_CD ACCT_REF_2_CD,
payment_type.ACCT_PGM_CD_DESC ACCT_PGM_CD_DESC,
payment_type.APP_ACCT_ID APP_ACCT_ID,
payment_type.PYMT_IMPL_ID PYMT_IMPL_ID,
payment_type.DATA_STAT_CD DATA_STAT_CD,
payment_type.CRE_DT CRE_DT,
payment_type.LAST_CHG_DT LAST_CHG_DT,
payment_type.LAST_CHG_USER_NM LAST_CHG_USER_NM,
PAYMENT_TYPE.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PAYMENT_TYPE" PAYMENT_TYPE 
LEFT JOIN "fsa-{env}-cnsv".PYMT_IMPL 
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv".PROGRAM_HIERARCHY_LEVEL 
ON (PYMT_IMPL.pgm_hrch_lvl_id = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)
WHERE PAYMENT_TYPE.OP <> 'D' AND
PAYMENT_TYPE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
payment_type.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
payment_type.ACCT_PGM_CD ACCT_PGM_CD,
payment_type.PYMT_TYPE_ID PYMT_TYPE_ID,
payment_type.PGM_HRCH_LVL_ID PGM_HRCH_LVL_ID,
payment_type.ACCT_PGM_ID ACCT_PGM_ID,
payment_type.CNSV_PYMT_TYPE_NM CNSV_PYMT_TYPE_NM,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
payment_type.OO_CLS_FULL_NM OO_CLS_FULL_NM,
payment_type.APP_CD APP_CD,
payment_type.APP_SYS_CD APP_SYS_CD,
payment_type.ACCT_TXN_CD ACCT_TXN_CD,
payment_type.ACCT_REF_1_CD ACCT_REF_1_CD,
payment_type.ACCT_REF_2_CD ACCT_REF_2_CD,
payment_type.ACCT_PGM_CD_DESC ACCT_PGM_CD_DESC,
payment_type.APP_ACCT_ID APP_ACCT_ID,
payment_type.PYMT_IMPL_ID PYMT_IMPL_ID,
payment_type.DATA_STAT_CD DATA_STAT_CD,
payment_type.CRE_DT CRE_DT,
payment_type.LAST_CHG_DT LAST_CHG_DT,
payment_type.LAST_CHG_USER_NM LAST_CHG_USER_NM,
PYMT_IMPL.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PYMT_IMPL" PYMT_IMPL
 JOIN "fsa-{env}-cnsv".PAYMENT_TYPE 
ON (PYMT_IMPL.PYMT_IMPL_ID = PAYMENT_TYPE.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv".PROGRAM_HIERARCHY_LEVEL 
ON (PYMT_IMPL.pgm_hrch_lvl_id = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)
WHERE PYMT_IMPL.OP <> 'D' AND
PYMT_IMPL.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
payment_type.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
payment_type.ACCT_PGM_CD ACCT_PGM_CD,
payment_type.PYMT_TYPE_ID PYMT_TYPE_ID,
payment_type.PGM_HRCH_LVL_ID PGM_HRCH_LVL_ID,
payment_type.ACCT_PGM_ID ACCT_PGM_ID,
payment_type.CNSV_PYMT_TYPE_NM CNSV_PYMT_TYPE_NM,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
payment_type.OO_CLS_FULL_NM OO_CLS_FULL_NM,
payment_type.APP_CD APP_CD,
payment_type.APP_SYS_CD APP_SYS_CD,
payment_type.ACCT_TXN_CD ACCT_TXN_CD,
payment_type.ACCT_REF_1_CD ACCT_REF_1_CD,
payment_type.ACCT_REF_2_CD ACCT_REF_2_CD,
payment_type.ACCT_PGM_CD_DESC ACCT_PGM_CD_DESC,
payment_type.APP_ACCT_ID APP_ACCT_ID,
payment_type.PYMT_IMPL_ID PYMT_IMPL_ID,
payment_type.DATA_STAT_CD DATA_STAT_CD,
payment_type.CRE_DT CRE_DT,
payment_type.LAST_CHG_DT LAST_CHG_DT,
payment_type.LAST_CHG_USER_NM LAST_CHG_USER_NM,
PROGRAM_HIERARCHY_LEVEL.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL 
LEFT JOIN "fsa-{env}-cnsv".PYMT_IMPL 
ON (PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID = PYMT_IMPL.pgm_hrch_lvl_id)
 JOIN "fsa-{env}-cnsv".PAYMENT_TYPE 
ON (PYMT_IMPL.PYMT_IMPL_ID = PAYMENT_TYPE.PYMT_IMPL_ID)
WHERE PROGRAM_HIERARCHY_LEVEL.OP <> 'D' AND
PROGRAM_HIERARCHY_LEVEL.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
payment_type.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
payment_type.ACCT_PGM_CD ACCT_PGM_CD,
payment_type.PYMT_TYPE_ID PYMT_TYPE_ID,
payment_type.PGM_HRCH_LVL_ID PGM_HRCH_LVL_ID,
payment_type.ACCT_PGM_ID ACCT_PGM_ID,
payment_type.CNSV_PYMT_TYPE_NM CNSV_PYMT_TYPE_NM,
NULL HRCH_LVL_NM,
payment_type.OO_CLS_FULL_NM OO_CLS_FULL_NM,
payment_type.APP_CD APP_CD,
payment_type.APP_SYS_CD APP_SYS_CD,
payment_type.ACCT_TXN_CD ACCT_TXN_CD,
payment_type.ACCT_REF_1_CD ACCT_REF_1_CD,
payment_type.ACCT_REF_2_CD ACCT_REF_2_CD,
payment_type.ACCT_PGM_CD_DESC ACCT_PGM_CD_DESC,
payment_type.APP_ACCT_ID APP_ACCT_ID,
payment_type.PYMT_IMPL_ID PYMT_IMPL_ID,
payment_type.DATA_STAT_CD DATA_STAT_CD,
payment_type.CRE_DT CRE_DT,
payment_type.LAST_CHG_DT LAST_CHG_DT,
payment_type.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".payment_type payment_type
WHERE OP = 'D'
AND dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}' 
)