WITH TAB_INCR_DR_ID AS 
(         

SELECT DISTINCT FARM_YR_HS.FARM_H_ID INCR_DR_ID,  
                                   FARM_YR_HS.PGM_YR 
FROM EDV.FARM_YR_HS, EDV.FARM_H 
WHERE  COALESCE(FARM_YR_HS.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = FARM_H.FARM_H_ID 
AND CAST(DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')  

UNION 

SELECT DISTINCT FARM_H.FARM_H_ID INCR_DR_ID,  
                                   FARM_YR_HS.PGM_YR 
FROM EDV.LOC_AREA_MRT_SRC_RS, EDV.FARM_H, EDV.FARM_YR_HS  
WHERE (CAST(LOC_AREA_MRT_SRC_RS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')  
      ) 
AND LOC_AREA_MRT_SRC_RS.CTRY_DIV_MRT_CD = FARM_H.ST_FSA_CD 
AND LOC_AREA_MRT_SRC_RS.LOC_AREA_MRT_CD = FARM_H.CNTY_FSA_CD 
AND LOC_AREA_MRT_SRC_RS.LOC_AREA_MRT_CD_SRC_ACRO = 'FSA' 
AND COALESCE(FARM_YR_HS.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = FARM_H.FARM_H_ID 

UNION 

SELECT DISTINCT  FARM_YR_DCP_HS.FARM_H_ID INCR_DR_ID,  
                                    FARM_YR_HS.PGM_YR 
FROM EDV.FARM_YR_DCP_HS, EDV.FARM_YR_HS 
WHERE (CAST(FARM_YR_DCP_HS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')  
      )   
      AND FARM_YR_HS.FARM_H_ID = COALESCE(FARM_YR_DCP_HS.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') 
      AND FARM_YR_HS.PGM_YR = FARM_YR_DCP_HS.PGM_YR
	  
UNION 

SELECT DISTINCT  FARM_YR_HS.FARM_H_ID INCR_DR_ID,  
                                    FARM_YR_HS.PGM_YR 
FROM EDV.ARC_PLC_ELG_DTER_RS, EDV.FARM_YR_HS 
WHERE (CAST(ARC_PLC_ELG_DTER_RS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')  
      )   
      AND COALESCE(FARM_YR_HS.ARC_PLC_ELG_DTER_CD, '[NULL IN SOURCE]') = ARC_PLC_ELG_DTER_RS.ARC_PLC_ELG_DTER_CD 
)
SELECT 
(CURRENT_DATE) AS CRE_DT,
(CURRENT_DATE) AS LAST_CHG_DT, 
'I' as DATA_STAT_CD,
 DM.PGM_YR 
,DM.ADM_FSA_ST_CNTY_SRGT_ID 
,DM.ADM_FSA_ST_CNTY_DURB_ID 
,DM.FARM_SRGT_ID 
,DM.FARM_DURB_ID 
,DM.FARM_YR_CRE_DT 
,DM.FARM_YR_LAST_CHG_DT 
,DM.FARM_YR_LAST_CHG_USER_NM 
,DM.FARM_YR_DCP_CRE_DT 
,DM.FARM_YR_DCP_LAST_CHG_DT 
,DM.FARM_YR_DCP_LAST_CHG_USER_NM 
,DM.SRC_DATA_STAT_CD 
,DM.CRP_ACRG 
,DM.MPL_ACRG 
,DM.DCP_DBL_CROP_ACRG 
,DM.ARC_PLC_ELG_DTER_DURB_ID 
,DM.DATA_EFF_STRT_DT 
FROM  
(SELECT  
     DM_1.PGM_YR 
    ,DM_1.ADM_FSA_ST_CNTY_SRGT_ID 
    ,DM_1.ADM_FSA_ST_CNTY_DURB_ID 
    ,DM_1.FARM_SRGT_ID 
    ,DM_1.FARM_DURB_ID 
    ,DM_1.FARM_YR_CRE_DT 
    ,DM_1.FARM_YR_LAST_CHG_DT 
    ,DM_1.FARM_YR_LAST_CHG_USER_NM 
    ,DM_1.FARM_YR_DCP_CRE_DT 
    ,DM_1.FARM_YR_DCP_LAST_CHG_DT 
    ,DM_1.FARM_YR_DCP_LAST_CHG_USER_NM 
    ,DM_1.SRC_DATA_STAT_CD 
    ,DM_1.CRP_ACRG 
    ,DM_1.MPL_ACRG 
    ,DM_1.DCP_DBL_CROP_ACRG 
    ,DM_1.ARC_PLC_ELG_DTER_DURB_ID 
    ,DM_1.DATA_EFF_STRT_DT 
    ,DM_1.FS_DATA_EFF_STRT_DT 
    ,DM_1.LAS_ADM_DATA_EFF_STRT_DT 
    ,DM_1.FDS_DATA_EFF_STRT_DT 
    ,DM_1.APEDRS_DATA_EFF_STRT_DT  
    ,ROW_NUMBER() OVER ( PARTITION BY  
    DM_1.FARM_DURB_ID, 
    DM_1.PGM_YR 
    ORDER BY  
      FS_DATA_EFF_STRT_DT DESC, 
      LAS_ADM_DATA_EFF_STRT_DT DESC,  
      FDS_DATA_EFF_STRT_DT DESC, 
      APEDRS_DATA_EFF_STRT_DT DESC 
        )  AS ROW_NUM_PART 
FROM ( 
SELECT * FROM ( 
SELECT DISTINCT  
     FS.PGM_YR PGM_YR 
    ,COALESCE(FSD_ADM.FSA_ST_CNTY_SRGT_ID, -3) ADM_FSA_ST_CNTY_SRGT_ID 
    ,COALESCE(FSD_ADM.FSA_ST_CNTY_DURB_ID, -3) ADM_FSA_ST_CNTY_DURB_ID 
    ,COALESCE(FD.FARM_SRGT_ID, -3) FARM_SRGT_ID 
    ,FD.FARM_DURB_ID FARM_DURB_ID 
    ,FS.SRC_CRE_DT FARM_YR_CRE_DT 
    ,FS.SRC_LAST_CHG_DT FARM_YR_LAST_CHG_DT 
    ,FS.SRC_LAST_CHG_USER_NM FARM_YR_LAST_CHG_USER_NM 
    ,FDS.SRC_CRE_DT FARM_YR_DCP_CRE_DT 
    ,FDS.SRC_LAST_CHG_DT FARM_YR_DCP_LAST_CHG_DT 
    ,FDS.SRC_LAST_CHG_USER_NM FARM_YR_DCP_LAST_CHG_USER_NM 
    ,FS.DATA_STAT_CD SRC_DATA_STAT_CD 
    ,FS.CRP_ACRG CRP_ACRG 
    ,FS.MPL_ACRG MPL_ACRG 
    ,FDS.DCP_DBL_CROP_ACRG DCP_DBL_CROP_ACRG     
    ,COALESCE(APED_DIM.ARC_PLC_ELG_DTER_DURB_ID, -3) ARC_PLC_ELG_DTER_DURB_ID 
    ,GREATEST(COALESCE(FS.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),  
              COALESCE(LAS_ADM.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')), 
              COALESCE(FDS.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),  
              
              COALESCE(APEDRS.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD'))  
             ) DATA_EFF_STRT_DT, 
    FS.DATA_EFF_STRT_DT FS_DATA_EFF_STRT_DT, 
    LAS_ADM.DATA_EFF_STRT_DT LAS_ADM_DATA_EFF_STRT_DT, 
    FDS.DATA_EFF_STRT_DT FDS_DATA_EFF_STRT_DT, 
    APEDRS.DATA_EFF_STRT_DT APEDRS_DATA_EFF_STRT_DT 
FROM EDV.FARM_YR_HS FS 
LEFT JOIN EDV.FARM_H FH  
ON (COALESCE(FS.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = FH.FARM_H_ID) 
LEFT JOIN CMN_DIM_DM_STG.FARM_DIM FD  
ON (FH.DURB_ID = COALESCE(FD.FARM_DURB_ID,-1) 
        AND FD.CUR_RCD_IND = 1) 
LEFT JOIN EDV.LOC_AREA_MRT_SRC_RS LAS_ADM  
ON (COALESCE(LAS_ADM.CTRY_DIV_MRT_CD,'--') = FH.ST_FSA_CD 
    AND COALESCE(LAS_ADM.LOC_AREA_MRT_CD,'--') =  FH.CNTY_FSA_CD  
    AND LAS_ADM.LOC_AREA_MRT_CD_SRC_ACRO = 'FSA') 
LEFT JOIN EDV.LOC_AREA_RH LAH_ADM  
ON (COALESCE(LAS_ADM.LOC_AREA_CAT_NM,'NULL IN SOURCE') = LAH_ADM.LOC_AREA_CAT_NM 
    AND COALESCE(LAS_ADM.LOC_AREA_NM,'NULL IN SOURCE') = LAH_ADM.LOC_AREA_NM 
    AND COALESCE(LAS_ADM.CTRY_DIV_NM,'NULL IN SOURCE') = LAH_ADM.CTRY_DIV_NM 
    AND LAS_ADM.LOC_AREA_MRT_CD_SRC_ACRO = 'FSA') 
LEFT JOIN CMN_DIM_DM_STG.FSA_ST_CNTY_DIM FSD_ADM  
ON (LAH_ADM.DURB_ID = FSD_ADM.FSA_ST_CNTY_DURB_ID 
    AND FSD_ADM.CUR_RCD_IND = 1) 
LEFT JOIN EDV.FARM_YR_DCP_HS FDS  
ON (FS.FARM_H_ID = COALESCE(FDS.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') 
    AND FS.PGM_YR = FDS.PGM_YR) 

LEFT JOIN EDV.ARC_PLC_ELG_DTER_RH APEDRH 
ON (COALESCE(FS.ARC_PLC_ELG_DTER_CD,'[NULL IN SOURCE]') = APEDRH.ARC_PLC_ELG_DTER_CD) 
LEFT JOIN EDV.ARC_PLC_ELG_DTER_RS APEDRS 
ON (APEDRH.ARC_PLC_ELG_DTER_CD = COALESCE(APEDRS.ARC_PLC_ELG_DTER_CD,'[NULL IN SOURCE]') 
    AND CAST(APEDRS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{ETL_DATE}', 'YYYY-MM-DD') 
    AND CAST(APEDRS.DATA_EFF_STRT_DT AS DATE) <= TO_TIMESTAMP('{ETL_DATE}', 'YYYY-MM-DD')) 
LEFT JOIN FARM_DM_STG.ARC_PLC_ELG_DTER_DIM APED_DIM 
ON (APEDRH.DURB_ID = APED_DIM.ARC_PLC_ELG_DTER_DURB_ID 
    AND APED_DIM.DATA_STAT_CD = 'A') 
WHERE (FS.FARM_H_ID, FS.PGM_YR) IN (SELECT INCR_DR_ID, PGM_YR FROM TAB_INCR_DR_ID) 
AND FS.PGM_YR IS NOT NULL 
AND FD.FARM_DURB_ID IS NOT NULL 
) sub ) DM_1 
WHERE COALESCE(CAST(FS_DATA_EFF_STRT_DT as DATE ),TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) <=  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD') 
AND CAST(COALESCE(LAS_ADM_DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) AS DATE) <=  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD') 
AND CAST(COALESCE(FDS_DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) AS DATE) <=  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD') 
 
AND CAST(COALESCE(APEDRS_DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) AS DATE) <=  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD') 
) DM 
WHERE DM.ROW_NUM_PART = 1





