SELECT PGM_YR,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
TR_NBR,
OFR_SCNR_NM,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
FARM_NBR,
CLU_NBR,
OFFERED_ACRG,
ELG_ACRG,
CNSV_CTR_SEQ_NBR,
CNSV_CTR_SFX_CD,
OFR_CLU_ID,
OFR_FARM_TR_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT PGM_YR,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
TR_NBR,
OFR_SCNR_NM,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
FARM_NBR,
CLU_NBR,
OFFERED_ACRG,
ELG_ACRG,
CNSV_CTR_SEQ_NBR,
CNSV_CTR_SFX_CD,
OFR_CLU_ID,
OFR_FARM_TR_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
OFR_CLU_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt40ofrsc.FARM_NBR FARM_NBR,
offer_clu.CLU_NBR CLU_NBR,
offer_clu.OFFERED_ACRG OFFERED_ACRG,
offer_clu.ELG_ACRG ELG_ACRG,
ewt40ofrsc.CNSV_CTR_SEQ_NBR CNSV_CTR_SEQ_NBR,
ewt40ofrsc.CNSV_CTR_SUFX_CD CNSV_CTR_SFX_CD,
offer_clu.OFR_CLU_ID OFR_CLU_ID,
offer_clu.OFR_FARM_TR_ID OFR_FARM_TR_ID,
offer_clu.DATA_STAT_CD DATA_STAT_CD,
offer_clu.CRE_DT CRE_DT,
offer_clu.LAST_CHG_DT LAST_CHG_DT,
offer_clu.LAST_CHG_USER_NM LAST_CHG_USER_NM,
OFFER_CLU.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."OFFER_CLU" OFFER_CLU 
LEFT JOIN   "fsa-{env}-cnsv".OFFER_FARM_TRACT 
ON (OFFER_FARM_TRACT.OFR_FARM_TR_ID = OFFER_CLU.OFR_FARM_TR_ID)  
LEFT JOIN   "fsa-{env}-cnsv".EWT40OFRSC  
ON (EWT40OFRSC.OFR_SCNR_ID = OFFER_FARM_TRACT.OFR_SCNR_ID) 
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP 
ON (EWT14SGNP.SGNP_ID = EWT40OFRSC.SGNP_ID) 
WHERE OFFER_CLU.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and OFFER_CLU.OP <> 'D'

UNION
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt40ofrsc.FARM_NBR FARM_NBR,
offer_clu.CLU_NBR CLU_NBR,
offer_clu.OFFERED_ACRG OFFERED_ACRG,
offer_clu.ELG_ACRG ELG_ACRG,
ewt40ofrsc.CNSV_CTR_SEQ_NBR CNSV_CTR_SEQ_NBR,
ewt40ofrsc.CNSV_CTR_SUFX_CD CNSV_CTR_SFX_CD,
offer_clu.OFR_CLU_ID OFR_CLU_ID,
offer_clu.OFR_FARM_TR_ID OFR_FARM_TR_ID,
offer_clu.DATA_STAT_CD DATA_STAT_CD,
offer_clu.CRE_DT CRE_DT,
offer_clu.LAST_CHG_DT LAST_CHG_DT,
offer_clu.LAST_CHG_USER_NM LAST_CHG_USER_NM,
OFFER_FARM_TRACT.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."OFFER_FARM_TRACT" OFFER_FARM_TRACT 
JOIN   "fsa-{env}-cnsv".OFFER_CLU 
ON (OFFER_FARM_TRACT.OFR_FARM_TR_ID = OFFER_CLU.OFR_FARM_TR_ID)  
LEFT JOIN   "fsa-{env}-cnsv".EWT40OFRSC  
ON (EWT40OFRSC.OFR_SCNR_ID = OFFER_FARM_TRACT.OFR_SCNR_ID) 
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP 
ON (EWT14SGNP.SGNP_ID = EWT40OFRSC.SGNP_ID) 
WHERE OFFER_FARM_TRACT.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and OFFER_FARM_TRACT.OP <> 'D'

UNION
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt40ofrsc.FARM_NBR FARM_NBR,
offer_clu.CLU_NBR CLU_NBR,
offer_clu.OFFERED_ACRG OFFERED_ACRG,
offer_clu.ELG_ACRG ELG_ACRG,
ewt40ofrsc.CNSV_CTR_SEQ_NBR CNSV_CTR_SEQ_NBR,
ewt40ofrsc.CNSV_CTR_SUFX_CD CNSV_CTR_SFX_CD,
offer_clu.OFR_CLU_ID OFR_CLU_ID,
offer_clu.OFR_FARM_TR_ID OFR_FARM_TR_ID,
offer_clu.DATA_STAT_CD DATA_STAT_CD,
offer_clu.CRE_DT CRE_DT,
offer_clu.LAST_CHG_DT LAST_CHG_DT,
offer_clu.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT40OFRSC.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."EWT40OFRSC"  EWT40OFRSC    
LEFT JOIN   "fsa-{env}-cnsv".OFFER_FARM_TRACT 
ON (EWT40OFRSC.OFR_SCNR_ID = OFFER_FARM_TRACT.OFR_SCNR_ID) 
JOIN   "fsa-{env}-cnsv".OFFER_CLU 
ON (OFFER_FARM_TRACT.OFR_FARM_TR_ID = OFFER_CLU.OFR_FARM_TR_ID)  
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP 
ON (EWT14SGNP.SGNP_ID = EWT40OFRSC.SGNP_ID)
WHERE EWT40OFRSC.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT40OFRSC.OP <> 'D'

UNION
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt40ofrsc.FARM_NBR FARM_NBR,
offer_clu.CLU_NBR CLU_NBR,
offer_clu.OFFERED_ACRG OFFERED_ACRG,
offer_clu.ELG_ACRG ELG_ACRG,
ewt40ofrsc.CNSV_CTR_SEQ_NBR CNSV_CTR_SEQ_NBR,
ewt40ofrsc.CNSV_CTR_SUFX_CD CNSV_CTR_SFX_CD,
offer_clu.OFR_CLU_ID OFR_CLU_ID,
offer_clu.OFR_FARM_TR_ID OFR_FARM_TR_ID,
offer_clu.DATA_STAT_CD DATA_STAT_CD,
offer_clu.CRE_DT CRE_DT,
offer_clu.LAST_CHG_DT LAST_CHG_DT,
offer_clu.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT14SGNP.OP,
4 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."EWT14SGNP" EWT14SGNP      
LEFT JOIN   "fsa-{env}-cnsv".EWT40OFRSC 
ON (EWT14SGNP.SGNP_ID = EWT40OFRSC.SGNP_ID) 
LEFT JOIN   "fsa-{env}-cnsv".OFFER_FARM_TRACT 
ON (EWT40OFRSC.OFR_SCNR_ID = OFFER_FARM_TRACT.OFR_SCNR_ID) 
JOIN   "fsa-{env}-cnsv".OFFER_CLU
ON (OFFER_FARM_TRACT.OFR_FARM_TR_ID = OFFER_CLU.OFR_FARM_TR_ID) 
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT14SGNP.OP <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
NULL PGM_YR,
NULL ADM_ST_FSA_CD,
NULL ADM_CNTY_FSA_CD,
NULL TR_NBR,
NULL OFR_SCNR_NM,
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL FARM_NBR,
offer_clu.CLU_NBR CLU_NBR,
offer_clu.OFFERED_ACRG OFFERED_ACRG,
offer_clu.ELG_ACRG ELG_ACRG,
NULL CNSV_CTR_SEQ_NBR,
NULL CNSV_CTR_SFX_CD,
offer_clu.OFR_CLU_ID OFR_CLU_ID,
offer_clu.OFR_FARM_TR_ID OFR_FARM_TR_ID,
offer_clu.DATA_STAT_CD DATA_STAT_CD,
offer_clu.CRE_DT CRE_DT,
offer_clu.LAST_CHG_DT LAST_CHG_DT,
offer_clu.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".offer_clu offer_clu
WHERE offer_clu.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and offer_clu.OP = 'D'
)