-- Julia Lu edition - will update this paragraph and query when (cnsv/ccms)-cdc is ready
-- Stage SQL: CCMS_MST_CTR (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CCMS_MST_CTR/incremental/CCMS_MST_CTR.sql
-- =============================================================================

select * from
(
select distinct adm_st_fsa_cd,
adm_cnty_fsa_cd,
sgnp_type_nm,
sgnp_sub_cat_nm,
sgnp_nbr,
sgnp_stype_agr_nm,
ctr_nbr,
ctr_id,
cnsv_pgm_cd,
sgnp_id,
pgm_yr,
orgn_strt_dt,
orgn_end_dt,
ofr_id,
hydro_unit_cd,
orgn_aprv_dt,
loc_st_fsa_cd,
loc_cnty_fsa_cd,
huc_gis_cpa_zone,
sgnp_inctv_pymt_amt,
orgn_anl_rnt_amt_per_acre,
ctr_lgth_years,
pymt_lmt_type_id,
ctr_core_det_id,
pymt_lmt_pvsn_cd,
pymt_lmt_pvsn_cd_yr,
ofr_adm_st_fsa_cd,
ofr_adm_cnty_fsa_cd,
ofr_tr_nbr,
ofr_scnr_nm,
data_stat_cd,
cre_dt,
cre_user_nm,
last_chg_dt,
last_chg_user_nm,
supl_ctr_type_abr,
cdc_oper_cd,
load_dt,
data_src_nm,
cdc_dt,
row_number() over ( partition by 
ctr_id
order by tbl_priority asc, last_chg_dt desc ) as row_num_part
from
(
select 
master_contract.administrative_state_fsa_code adm_st_fsa_cd,
master_contract.administrative_county_fsa_code adm_cnty_fsa_cd,
ewt14sgnp.sgnp_type_desc sgnp_type_nm,
ewt14sgnp.sgnp_stype_desc sgnp_sub_cat_nm,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
master_contract.contract_number ctr_nbr,
master_contract.contract_identifier ctr_id,
master_contract.conservation_program_code cnsv_pgm_cd,
master_contract.signup_identifier sgnp_id,
master_contract.program_year pgm_yr,
master_contract.original_start_date orgn_strt_dt,
master_contract.original_end_date orgn_end_dt,
master_contract.offer_identification ofr_id,
master_contract.hydrologic_unit_code hydro_unit_cd,
master_contract.original_approved_date orgn_aprv_dt,
master_contract.location_state_fsa_code loc_st_fsa_cd,
master_contract.location_county_fsa_code loc_cnty_fsa_cd,
master_contract.huc_gis_cpa_zone huc_gis_cpa_zone,
master_contract.signup_incentive_payment_amount sgnp_inctv_pymt_amt,
master_contract.original_annual_rental_amount_per_acre orgn_anl_rnt_amt_per_acre,
master_contract.contract_length_years ctr_lgth_years,
master_contract.pymt_lmt_type_id pymt_lmt_type_id,
master_contract.ctr_core_det_id ctr_core_det_id,
pymt_lmt_type.pymt_lmt_pvsn_cd pymt_lmt_pvsn_cd,
pymt_lmt_type.pymt_lmt_pvsn_cd_yr pymt_lmt_pvsn_cd_yr,
ewt40ofrsc.adm_st_fsa_cd ofr_adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd ofr_adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr ofr_tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
master_contract.data_status_code data_stat_cd,
master_contract.creation_date cre_dt,
master_contract.creation_user_name cre_user_nm,
master_contract.last_change_date last_chg_dt,
master_contract.last_change_user_name last_chg_user_nm,
master_contract.supplemental_contract_type_abbreviation supl_ctr_type_abr,
master_contract.op as cdc_oper_cd,
current_timestamp() as load_dt,
'CCMS_MST_CTR' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as tbl_priority
from `fsa-{env}-ccms-cdc`.`master_contract`
left join `fsa-{env}-cnsv`.`ewt14sgnp` on (master_contract.signup_identifier = ewt14sgnp.sgnp_id)   
left join `fsa-{env}-ccms`.`pymt_lmt_type` on (master_contract.pymt_lmt_type_id = pymt_lmt_type.pymt_lmt_type_id )  
left join `fsa-{env}-cnsv`.`ewt40ofrsc` on (ewt40ofrsc.ofr_scnr_id = master_contract.offer_identification ) 
where master_contract.op <> 'D'
and master_contract.dart_filedate between '{etl_start_date}' and '{etl_end_date}'

union
select 
master_contract.administrative_state_fsa_code adm_st_fsa_cd,
master_contract.administrative_county_fsa_code adm_cnty_fsa_cd,
ewt14sgnp.sgnp_type_desc sgnp_type_nm,
ewt14sgnp.sgnp_stype_desc sgnp_sub_cat_nm,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
master_contract.contract_number ctr_nbr,
master_contract.contract_identifier ctr_id,
master_contract.conservation_program_code cnsv_pgm_cd,
master_contract.signup_identifier sgnp_id,
master_contract.program_year pgm_yr,
master_contract.original_start_date orgn_strt_dt,
master_contract.original_end_date orgn_end_dt,
master_contract.offer_identification ofr_id,
master_contract.hydrologic_unit_code hydro_unit_cd,
master_contract.original_approved_date orgn_aprv_dt,
master_contract.location_state_fsa_code loc_st_fsa_cd,
master_contract.location_county_fsa_code loc_cnty_fsa_cd,
master_contract.huc_gis_cpa_zone huc_gis_cpa_zone,
master_contract.signup_incentive_payment_amount sgnp_inctv_pymt_amt,
master_contract.original_annual_rental_amount_per_acre orgn_anl_rnt_amt_per_acre,
master_contract.contract_length_years ctr_lgth_years,
master_contract.pymt_lmt_type_id pymt_lmt_type_id,
master_contract.ctr_core_det_id ctr_core_det_id,
pymt_lmt_type.pymt_lmt_pvsn_cd pymt_lmt_pvsn_cd,
pymt_lmt_type.pymt_lmt_pvsn_cd_yr pymt_lmt_pvsn_cd_yr,
ewt40ofrsc.adm_st_fsa_cd ofr_adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd ofr_adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr ofr_tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
master_contract.data_status_code data_stat_cd,
master_contract.creation_date cre_dt,
master_contract.creation_user_name cre_user_nm,
master_contract.last_change_date last_chg_dt,
master_contract.last_change_user_name last_chg_user_nm,
master_contract.supplemental_contract_type_abbreviation supl_ctr_type_abr,
master_contract.op as cdc_oper_cd,
current_timestamp() as load_dt,
'CCMS_MST_CTR' as data_src_nm,
'{etl_start_date}' as cdc_dt,
2 as tbl_priority
from `fsa-{env}-cnsv`.`ewt14sgnp` 
join `fsa-{env}-ccms-cdc`.`master_contract` on  (master_contract.signup_identifier = ewt14sgnp.sgnp_id)   
left join `fsa-{env}-ccms`.`pymt_lmt_type` on (master_contract.pymt_lmt_type_id = pymt_lmt_type.pymt_lmt_type_id )  
left join `fsa-{env}-cnsv`.`ewt40ofrsc` on (ewt40ofrsc.ofr_scnr_id = master_contract.offer_identification ) 
where master_contract.op <> 'D'

union
select 
master_contract.administrative_state_fsa_code adm_st_fsa_cd,
master_contract.administrative_county_fsa_code adm_cnty_fsa_cd,
ewt14sgnp.sgnp_type_desc sgnp_type_nm,
ewt14sgnp.sgnp_stype_desc sgnp_sub_cat_nm,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
master_contract.contract_number ctr_nbr,
master_contract.contract_identifier ctr_id,
master_contract.conservation_program_code cnsv_pgm_cd,
master_contract.signup_identifier sgnp_id,
master_contract.program_year pgm_yr,
master_contract.original_start_date orgn_strt_dt,
master_contract.original_end_date orgn_end_dt,
master_contract.offer_identification ofr_id,
master_contract.hydrologic_unit_code hydro_unit_cd,
master_contract.original_approved_date orgn_aprv_dt,
master_contract.location_state_fsa_code loc_st_fsa_cd,
master_contract.location_county_fsa_code loc_cnty_fsa_cd,
master_contract.huc_gis_cpa_zone huc_gis_cpa_zone,
master_contract.signup_incentive_payment_amount sgnp_inctv_pymt_amt,
master_contract.original_annual_rental_amount_per_acre orgn_anl_rnt_amt_per_acre,
master_contract.contract_length_years ctr_lgth_years,
master_contract.pymt_lmt_type_id pymt_lmt_type_id,
master_contract.ctr_core_det_id ctr_core_det_id,
pymt_lmt_type.pymt_lmt_pvsn_cd pymt_lmt_pvsn_cd,
pymt_lmt_type.pymt_lmt_pvsn_cd_yr pymt_lmt_pvsn_cd_yr,
ewt40ofrsc.adm_st_fsa_cd ofr_adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd ofr_adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr ofr_tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
master_contract.data_status_code data_stat_cd,
master_contract.creation_date cre_dt,
master_contract.creation_user_name cre_user_nm,
master_contract.last_change_date last_chg_dt,
master_contract.last_change_user_name last_chg_user_nm,
master_contract.supplemental_contract_type_abbreviation supl_ctr_type_abr,
master_contract.op as cdc_oper_cd,
current_timestamp() as load_dt,
'CCMS_MST_CTR' as data_src_nm,
'{etl_start_date}' as cdc_dt,
3 as tbl_priority
from `fsa-{env}-cnsv`.`ewt40ofrsc` 
join `fsa-{env}-ccms-cdc`.`master_contract` on  (ewt40ofrsc.ofr_scnr_id = master_contract.offer_identification ) 
left join `fsa-{env}-cnsv`.`ewt14sgnp` on (master_contract.signup_identifier = ewt14sgnp.sgnp_id)   
left join `fsa-{env}-ccms`.`pymt_lmt_type` on (master_contract.pymt_lmt_type_id = pymt_lmt_type.pymt_lmt_type_id )  
where master_contract.op <> 'D'

union
select 
master_contract.administrative_state_fsa_code adm_st_fsa_cd,
master_contract.administrative_county_fsa_code adm_cnty_fsa_cd,
ewt14sgnp.sgnp_type_desc sgnp_type_nm,
ewt14sgnp.sgnp_stype_desc sgnp_sub_cat_nm,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
master_contract.contract_number ctr_nbr,
master_contract.contract_identifier ctr_id,
master_contract.conservation_program_code cnsv_pgm_cd,
master_contract.signup_identifier sgnp_id,
master_contract.program_year pgm_yr,
master_contract.original_start_date orgn_strt_dt,
master_contract.original_end_date orgn_end_dt,
master_contract.offer_identification ofr_id,
master_contract.hydrologic_unit_code hydro_unit_cd,
master_contract.original_approved_date orgn_aprv_dt,
master_contract.location_state_fsa_code loc_st_fsa_cd,
master_contract.location_county_fsa_code loc_cnty_fsa_cd,
master_contract.huc_gis_cpa_zone huc_gis_cpa_zone,
master_contract.signup_incentive_payment_amount sgnp_inctv_pymt_amt,
master_contract.original_annual_rental_amount_per_acre orgn_anl_rnt_amt_per_acre,
master_contract.contract_length_years ctr_lgth_years,
master_contract.pymt_lmt_type_id pymt_lmt_type_id,
master_contract.ctr_core_det_id ctr_core_det_id,
pymt_lmt_type.pymt_lmt_pvsn_cd pymt_lmt_pvsn_cd,
pymt_lmt_type.pymt_lmt_pvsn_cd_yr pymt_lmt_pvsn_cd_yr,
ewt40ofrsc.adm_st_fsa_cd ofr_adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd ofr_adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr ofr_tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
master_contract.data_status_code data_stat_cd,
master_contract.creation_date cre_dt,
master_contract.creation_user_name cre_user_nm,
master_contract.last_change_date last_chg_dt,
master_contract.last_change_user_name last_chg_user_nm,
master_contract.supplemental_contract_type_abbreviation supl_ctr_type_abr,
master_contract.op as cdc_oper_cd,
current_timestamp() as load_dt,
'CCMS_MST_CTR' as data_src_nm,
'{etl_start_date}' as cdc_dt,
4 as tbl_priority
from `fsa-{env}-ccms`.`pymt_lmt_type` 
join `fsa-{env}-ccms-cdc`.`master_contract` on  (master_contract.pymt_lmt_type_id = pymt_lmt_type.pymt_lmt_type_id )  
left join `fsa-{env}-cnsv`.`ewt14sgnp` on (master_contract.signup_identifier = ewt14sgnp.sgnp_id)   
left join `fsa-{env}-cnsv`.`ewt40ofrsc` on (ewt40ofrsc.ofr_scnr_id = master_contract.offer_identification ) 
where master_contract.op <> 'D'
) stg_all
) stg_unq
where row_num_part = 1

union
select distinct
master_contract.administrative_state_fsa_code adm_st_fsa_cd,
master_contract.administrative_county_fsa_code adm_cnty_fsa_cd,
null sgnp_type_nm,
null sgnp_sub_cat_nm,
null sgnp_nbr,
null sgnp_stype_agr_nm,
master_contract.contract_number ctr_nbr,
master_contract.contract_identifier ctr_id,
master_contract.conservation_program_code cnsv_pgm_cd,
master_contract.signup_identifier sgnp_id,
master_contract.program_year pgm_yr,
master_contract.original_start_date orgn_strt_dt,
master_contract.original_end_date orgn_end_dt,
master_contract.offer_identification ofr_id,
master_contract.hydrologic_unit_code hydro_unit_cd,
master_contract.original_approved_date orgn_aprv_dt,
master_contract.location_state_fsa_code loc_st_fsa_cd,
master_contract.location_county_fsa_code loc_cnty_fsa_cd,
master_contract.huc_gis_cpa_zone huc_gis_cpa_zone,
master_contract.signup_incentive_payment_amount sgnp_inctv_pymt_amt,
master_contract.original_annual_rental_amount_per_acre orgn_anl_rnt_amt_per_acre,
master_contract.contract_length_years ctr_lgth_years,
master_contract.pymt_lmt_type_id pymt_lmt_type_id,
master_contract.ctr_core_det_id ctr_core_det_id,
null pymt_lmt_pvsn_cd,
null pymt_lmt_pvsn_cd_yr,
null ofr_adm_st_fsa_cd,
null ofr_adm_cnty_fsa_cd,
null ofr_tr_nbr,
null ofr_scnr_nm,
master_contract.data_status_code data_stat_cd,
master_contract.creation_date cre_dt,
master_contract.creation_user_name cre_user_nm,
master_contract.last_change_date last_chg_dt,
master_contract.last_change_user_name last_chg_user_nm,
master_contract.supplemental_contract_type_abbreviation supl_ctr_type_abr,
'D' cdc_oper_cd,
current_timestamp() as load_dt,
'CCMS_MST_CTR' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as row_num_part
from `fsa-{env}-ccms-cdc`.`master_contract`
where master_contract.op = 'D'