-- Julia Lu edition - will update this paragraph and query when (cnsv/ccms)-cdc is ready
-- Stage SQL: CNSV_CNSV_PRAC (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_CNSV_PRAC/incremental/CNSV_CNSV_PRAC.sql
-- =============================================================================
SELECT * FROM
(
SELECT DISTINCT CNSV_PRAC_CD,
CNSV_PRAC_ID,
PGM_HRCH_LVL_ID,
UOM_ID,
CNSV_PRAC_DESC,
PRAC_MAX_LFSP_CT,
PRAC_MIN_LFSP_CT,
REG_COST_SHR_PCT,
LTD_COST_SHR_PCT,
UOM_NM,
HRCH_LVL_NM,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CNSV_PRAC_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
CONSERVATION_PRACTICE.CNSV_PRAC_CD CNSV_PRAC_CD,
CONSERVATION_PRACTICE.CNSV_PRAC_ID CNSV_PRAC_ID,
CONSERVATION_PRACTICE.PGM_HRCH_LVL_ID PGM_HRCH_LVL_ID,
CONSERVATION_PRACTICE.UOM_ID UOM_ID,
CONSERVATION_PRACTICE.CNSV_PRAC_DESC CNSV_PRAC_DESC,
CONSERVATION_PRACTICE.PRAC_MAX_LFSP_CT PRAC_MAX_LFSP_CT,
CONSERVATION_PRACTICE.PRAC_MIN_LFSP_CT PRAC_MIN_LFSP_CT,
CONSERVATION_PRACTICE.REG_COST_SHR_PCT REG_COST_SHR_PCT,
CONSERVATION_PRACTICE.LTD_COST_SHR_PCT LTD_COST_SHR_PCT,
UNIT_OF_MEASURE.UOM_NM UOM_NM,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
CONSERVATION_PRACTICE.DATA_STAT_CD DATA_STAT_CD,
CONSERVATION_PRACTICE.CRE_DT CRE_DT,
CONSERVATION_PRACTICE.LAST_CHG_DT LAST_CHG_DT,
CONSERVATION_PRACTICE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
CONSERVATION_PRACTICE.op,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".CONSERVATION_PRACTICELEFT JOIN "fsa-{env}-cnsv-cdc".PROGRAM_HIERARCHY_LEVELON(CONSERVATION_PRACTICE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)LEFT JOIN "fsa-{env}-cnsv-cdc".UNIT_OF_MEASUREON (CONSERVATION_PRACTICE.UOM_ID = UNIT_OF_MEASURE.UOM_ID)WHERE CONSERVATION_PRACTICE.op <> 'D'

UNION
SELECT 
CONSERVATION_PRACTICE.CNSV_PRAC_CD CNSV_PRAC_CD,
CONSERVATION_PRACTICE.CNSV_PRAC_ID CNSV_PRAC_ID,
CONSERVATION_PRACTICE.PGM_HRCH_LVL_ID PGM_HRCH_LVL_ID,
CONSERVATION_PRACTICE.UOM_ID UOM_ID,
CONSERVATION_PRACTICE.CNSV_PRAC_DESC CNSV_PRAC_DESC,
CONSERVATION_PRACTICE.PRAC_MAX_LFSP_CT PRAC_MAX_LFSP_CT,
CONSERVATION_PRACTICE.PRAC_MIN_LFSP_CT PRAC_MIN_LFSP_CT,
CONSERVATION_PRACTICE.REG_COST_SHR_PCT REG_COST_SHR_PCT,
CONSERVATION_PRACTICE.LTD_COST_SHR_PCT LTD_COST_SHR_PCT,
UNIT_OF_MEASURE.UOM_NM UOM_NM,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
CONSERVATION_PRACTICE.DATA_STAT_CD DATA_STAT_CD,
CONSERVATION_PRACTICE.CRE_DT CRE_DT,
CONSERVATION_PRACTICE.LAST_CHG_DT LAST_CHG_DT,
CONSERVATION_PRACTICE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
PROGRAM_HIERARCHY_LEVEL.op,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".PROGRAM_HIERARCHY_LEVEL JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_PRACTICE ON(CONSERVATION_PRACTICE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) LEFT JOIN "fsa-{env}-cnsv-cdc".UNIT_OF_MEASURE ON (CONSERVATION_PRACTICE.UOM_ID = UNIT_OF_MEASURE.UOM_ID)WHERE PROGRAM_HIERARCHY_LEVEL.op <> 'D'

UNION
SELECT 
CONSERVATION_PRACTICE.CNSV_PRAC_CD CNSV_PRAC_CD,
CONSERVATION_PRACTICE.CNSV_PRAC_ID CNSV_PRAC_ID,
CONSERVATION_PRACTICE.PGM_HRCH_LVL_ID PGM_HRCH_LVL_ID,
CONSERVATION_PRACTICE.UOM_ID UOM_ID,
CONSERVATION_PRACTICE.CNSV_PRAC_DESC CNSV_PRAC_DESC,
CONSERVATION_PRACTICE.PRAC_MAX_LFSP_CT PRAC_MAX_LFSP_CT,
CONSERVATION_PRACTICE.PRAC_MIN_LFSP_CT PRAC_MIN_LFSP_CT,
CONSERVATION_PRACTICE.REG_COST_SHR_PCT REG_COST_SHR_PCT,
CONSERVATION_PRACTICE.LTD_COST_SHR_PCT LTD_COST_SHR_PCT,
UNIT_OF_MEASURE.UOM_NM UOM_NM,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
CONSERVATION_PRACTICE.DATA_STAT_CD DATA_STAT_CD,
CONSERVATION_PRACTICE.CRE_DT CRE_DT,
CONSERVATION_PRACTICE.LAST_CHG_DT LAST_CHG_DT,
CONSERVATION_PRACTICE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
UNIT_OF_MEASURE.op,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".UNIT_OF_MEASURE JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_PRACTICE ON (CONSERVATION_PRACTICE.UOM_ID = UNIT_OF_MEASURE.UOM_ID) LEFT JOIN "fsa-{env}-cnsv-cdc".PROGRAM_HIERARCHY_LEVEL ON(CONSERVATION_PRACTICE.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID)WHERE UNIT_OF_MEASURE.op <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND CONSERVATION_PRACTICE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
CONSERVATION_PRACTICE.CNSV_PRAC_CD CNSV_PRAC_CD,
CONSERVATION_PRACTICE.CNSV_PRAC_ID CNSV_PRAC_ID,
CONSERVATION_PRACTICE.PGM_HRCH_LVL_ID PGM_HRCH_LVL_ID,
CONSERVATION_PRACTICE.UOM_ID UOM_ID,
CONSERVATION_PRACTICE.CNSV_PRAC_DESC CNSV_PRAC_DESC,
CONSERVATION_PRACTICE.PRAC_MAX_LFSP_CT PRAC_MAX_LFSP_CT,
CONSERVATION_PRACTICE.PRAC_MIN_LFSP_CT PRAC_MIN_LFSP_CT,
CONSERVATION_PRACTICE.REG_COST_SHR_PCT REG_COST_SHR_PCT,
CONSERVATION_PRACTICE.LTD_COST_SHR_PCT LTD_COST_SHR_PCT,
NULL UOM_NM,
NULL HRCH_LVL_NM,
CONSERVATION_PRACTICE.DATA_STAT_CD DATA_STAT_CD,
CONSERVATION_PRACTICE.CRE_DT CRE_DT,
CONSERVATION_PRACTICE.LAST_CHG_DT LAST_CHG_DT,
CONSERVATION_PRACTICE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".CONSERVATION_PRACTICE
WHERE CONSERVATION_PRACTICE.op = 'D'