-- julia lu edition - will update this paragraph and query when cnsv-cdc is ready
-- stage sql: CNSV_EWT43OSOIL (incremental)
-- location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/cnsv_ewt43osoil/incremental/cnsv_ewt43osoil.sql
-- =============================================================================

select * from
(
select distinct pgm_yr,
adm_st_fsa_cd,
adm_cnty_fsa_cd,
tr_nbr,
ofr_scnr_nm,
sgnp_nbr,
sgnp_type_desc,
sgnp_stype_desc,
sgnp_stype_agr_nm,
soil_grp_nm,
soil_ar_id,
soil_map_unit_acrg,
soil_rnt_rt,
calc_wtr_envr_idx,
calc_tot_wtr_envr_idx,
calc_wind_envr_idx,
calc_tot_wind_envr_idx,
calc_clmt_wt_idx,
calc_tot_clmt_idx,
calc_rkls_nbr,
calc_tot_rkls_nbr,
calc_tot_soil_lch_idx,
wesl_acrg,
st_fips_cd,
cnty_fips_cd,
soil_srvy_ar_cd,
soil_map_unit_sym_cd,
soil_lch_idx,
wtr_erod_fctr,
soil_loss_tolr_fctr,
wind_erod_idx,
long_leaf_suit_ind,
soil_slp_lgth_fctr,
wesl_ind,
nipf_prd_adj_factor_pct,
cnsv_ctr_seq_nbr,
cnsv_ctr_sfx_cd,
ofr_scnr_id,
data_stat_cd,
cre_dt,
last_chg_dt,
last_chg_user_nm,
cdc_oper_cd,
load_dt,
data_src_nm,
cdc_dt,
row_number() over ( partition by 
soil_grp_nm,
soil_ar_id,
ofr_scnr_id
order by tbl_priority asc, last_chg_dt desc ) as row_num_part
from
(
select 
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt43osoil.soil_grp_nm soil_grp_nm,
ewt43osoil.soil_ar_id soil_ar_id,
ewt43osoil.soil_map_unit_acrg soil_map_unit_acrg,
ewt43osoil.soil_rnt_rt soil_rnt_rt,
ewt43osoil.calc_wtr_envr_idx calc_wtr_envr_idx,
ewt43osoil.calc_tot_wtr_nbr calc_tot_wtr_envr_idx,
ewt43osoil.calc_wind_envr_idx calc_wind_envr_idx,
ewt43osoil.calc_tot_wind_idx calc_tot_wind_envr_idx,
ewt43osoil.calc_clmt_idx calc_clmt_wt_idx,
ewt43osoil.calc_tot_clmt_idx calc_tot_clmt_idx,
ewt43osoil.calc_rkls_nbr calc_rkls_nbr,
ewt43osoil.calc_tot_rkls_nbr calc_tot_rkls_nbr,
ewt43osoil.calc_tot_lch_idx calc_tot_soil_lch_idx,
ewt43osoil.wesl_acrg wesl_acrg,
ewt43osoil.st_fips_cd st_fips_cd,
ewt43osoil.cnty_fips_cd cnty_fips_cd,
ewt43osoil.soil_srvy_ar_cd soil_srvy_ar_cd,
ewt43osoil.soil_map_unit_cd soil_map_unit_sym_cd,
ewt43osoil.soil_lch_idx soil_lch_idx,
ewt43osoil.wtr_erod_fctr wtr_erod_fctr,
ewt43osoil.soil_loss_tolr soil_loss_tolr_fctr,
ewt43osoil.wind_erod_idx wind_erod_idx,
ewt43osoil.long_leaf_suit_ind long_leaf_suit_ind,
ewt43osoil.soil_slp_lgth_fctr soil_slp_lgth_fctr,
ewt43osoil.wesl_ind wesl_ind,
ewt43osoil.nipf_prd_adj_factor_pct nipf_prd_adj_factor_pct,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt43osoil.ofr_scnr_id ofr_scnr_id,
ewt43osoil.data_stat_cd data_stat_cd,
ewt43osoil.cre_dt cre_dt,
ewt43osoil.last_chg_dt last_chg_dt,
ewt43osoil.last_chg_user_nm last_chg_user_nm,
ewt43osoil.op as cdc_oper_cd,
current_timestamp() as load_dt,
'cnsv_ewt43osoil' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as tbl_priority
from `fsa-{env}-cnsv-cdc`.`ewt43osoil` 
left join `fsa-{env}-cnsv`.`ewt40ofrsc` on (ewt43osoil.ofr_scnr_id = ewt40ofrsc.ofr_scnr_id) 
left join `fsa-{env}-cnsv`.`ewt14sgnp` on (ewt40ofrsc.sgnp_id = ewt14sgnp.sgnp_id)
where ewt43osoil.op <> 'D'
  and ewt43osoil.dart_filedate between '{etl_start_date}' and '{etl_end_date}'

union
select 
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt43osoil.soil_grp_nm soil_grp_nm,
ewt43osoil.soil_ar_id soil_ar_id,
ewt43osoil.soil_map_unit_acrg soil_map_unit_acrg,
ewt43osoil.soil_rnt_rt soil_rnt_rt,
ewt43osoil.calc_wtr_envr_idx calc_wtr_envr_idx,
ewt43osoil.calc_tot_wtr_nbr calc_tot_wtr_envr_idx,
ewt43osoil.calc_wind_envr_idx calc_wind_envr_idx,
ewt43osoil.calc_tot_wind_idx calc_tot_wind_envr_idx,
ewt43osoil.calc_clmt_idx calc_clmt_wt_idx,
ewt43osoil.calc_tot_clmt_idx calc_tot_clmt_idx,
ewt43osoil.calc_rkls_nbr calc_rkls_nbr,
ewt43osoil.calc_tot_rkls_nbr calc_tot_rkls_nbr,
ewt43osoil.calc_tot_lch_idx calc_tot_soil_lch_idx,
ewt43osoil.wesl_acrg wesl_acrg,
ewt43osoil.st_fips_cd st_fips_cd,
ewt43osoil.cnty_fips_cd cnty_fips_cd,
ewt43osoil.soil_srvy_ar_cd soil_srvy_ar_cd,
ewt43osoil.soil_map_unit_cd soil_map_unit_sym_cd,
ewt43osoil.soil_lch_idx soil_lch_idx,
ewt43osoil.wtr_erod_fctr wtr_erod_fctr,
ewt43osoil.soil_loss_tolr soil_loss_tolr_fctr,
ewt43osoil.wind_erod_idx wind_erod_idx,
ewt43osoil.long_leaf_suit_ind long_leaf_suit_ind,
ewt43osoil.soil_slp_lgth_fctr soil_slp_lgth_fctr,
ewt43osoil.wesl_ind wesl_ind,
ewt43osoil.nipf_prd_adj_factor_pct nipf_prd_adj_factor_pct,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt43osoil.ofr_scnr_id ofr_scnr_id,
ewt43osoil.data_stat_cd data_stat_cd,
ewt43osoil.cre_dt cre_dt,
ewt43osoil.last_chg_dt last_chg_dt,
ewt43osoil.last_chg_user_nm last_chg_user_nm,
ewt43osoil.op as cdc_oper_cd,
current_timestamp() as load_dt,
'cnsv_ewt43osoil' as data_src_nm,
'{etl_start_date}' as cdc_dt,
2 as tbl_priority
from `fsa-{env}-cnsv`.`ewt40ofrsc` 
join `fsa-{env}-cnsv-cdc`.`ewt43osoil` on (ewt40ofrsc.ofr_scnr_id = ewt43osoil.ofr_scnr_id) 
left join `fsa-{env}-cnsv`.`ewt14sgnp` on (ewt40ofrsc.sgnp_id = ewt14sgnp.sgnp_id)
where ewt43osoil.op <> 'D'

union
select 
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt43osoil.soil_grp_nm soil_grp_nm,
ewt43osoil.soil_ar_id soil_ar_id,
ewt43osoil.soil_map_unit_acrg soil_map_unit_acrg,
ewt43osoil.soil_rnt_rt soil_rnt_rt,
ewt43osoil.calc_wtr_envr_idx calc_wtr_envr_idx,
ewt43osoil.calc_tot_wtr_nbr calc_tot_wtr_envr_idx,
ewt43osoil.calc_wind_envr_idx calc_wind_envr_idx,
ewt43osoil.calc_tot_wind_idx calc_tot_wind_envr_idx,
ewt43osoil.calc_clmt_idx calc_clmt_wt_idx,
ewt43osoil.calc_tot_clmt_idx calc_tot_clmt_idx,
ewt43osoil.calc_rkls_nbr calc_rkls_nbr,
ewt43osoil.calc_tot_rkls_nbr calc_tot_rkls_nbr,
ewt43osoil.calc_tot_lch_idx calc_tot_soil_lch_idx,
ewt43osoil.wesl_acrg wesl_acrg,
ewt43osoil.st_fips_cd st_fips_cd,
ewt43osoil.cnty_fips_cd cnty_fips_cd,
ewt43osoil.soil_srvy_ar_cd soil_srvy_ar_cd,
ewt43osoil.soil_map_unit_cd soil_map_unit_sym_cd,
ewt43osoil.soil_lch_idx soil_lch_idx,
ewt43osoil.wtr_erod_fctr wtr_erod_fctr,
ewt43osoil.soil_loss_tolr soil_loss_tolr_fctr,
ewt43osoil.wind_erod_idx wind_erod_idx,
ewt43osoil.long_leaf_suit_ind long_leaf_suit_ind,
ewt43osoil.soil_slp_lgth_fctr soil_slp_lgth_fctr,
ewt43osoil.wesl_ind wesl_ind,
ewt43osoil.nipf_prd_adj_factor_pct nipf_prd_adj_factor_pct,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt43osoil.ofr_scnr_id ofr_scnr_id,
ewt43osoil.data_stat_cd data_stat_cd,
ewt43osoil.cre_dt cre_dt,
ewt43osoil.last_chg_dt last_chg_dt,
ewt43osoil.last_chg_user_nm last_chg_user_nm,
ewt43osoil.op as cdc_oper_cd,
current_timestamp() as load_dt,
'cnsv_ewt43osoil' as data_src_nm,
'{etl_start_date}' as cdc_dt,
3 as tbl_priority
from `fsa-{env}-cnsv`.`ewt14sgnp`
left join `fsa-{env}-cnsv`.`ewt40ofrsc` on (ewt14sgnp.sgnp_id = ewt40ofrsc.sgnp_id) 
join `fsa-{env}-cnsv-cdc`.`ewt43osoil` on (ewt40ofrsc.ofr_scnr_id = ewt43osoil.ofr_scnr_id)
where ewt43osoil.op <> 'D'
) stg_all
) stg_unq
where row_num_part = 1

union
select distinct
null pgm_yr,
null adm_st_fsa_cd,
null adm_cnty_fsa_cd,
null tr_nbr,
null ofr_scnr_nm,
null sgnp_nbr,
null sgnp_type_desc,
null sgnp_stype_desc,
null sgnp_stype_agr_nm,
ewt43osoil.soil_grp_nm soil_grp_nm,
ewt43osoil.soil_ar_id soil_ar_id,
ewt43osoil.soil_map_unit_acrg soil_map_unit_acrg,
ewt43osoil.soil_rnt_rt soil_rnt_rt,
ewt43osoil.calc_wtr_envr_idx calc_wtr_envr_idx,
ewt43osoil.calc_tot_wtr_nbr calc_tot_wtr_envr_idx,
ewt43osoil.calc_wind_envr_idx calc_wind_envr_idx,
ewt43osoil.calc_tot_wind_idx calc_tot_wind_envr_idx,
ewt43osoil.calc_clmt_idx calc_clmt_wt_idx,
ewt43osoil.calc_tot_clmt_idx calc_tot_clmt_idx,
ewt43osoil.calc_rkls_nbr calc_rkls_nbr,
ewt43osoil.calc_tot_rkls_nbr calc_tot_rkls_nbr,
ewt43osoil.calc_tot_lch_idx calc_tot_soil_lch_idx,
ewt43osoil.wesl_acrg wesl_acrg,
ewt43osoil.st_fips_cd st_fips_cd,
ewt43osoil.cnty_fips_cd cnty_fips_cd,
ewt43osoil.soil_srvy_ar_cd soil_srvy_ar_cd,
ewt43osoil.soil_map_unit_cd soil_map_unit_sym_cd,
ewt43osoil.soil_lch_idx soil_lch_idx,
ewt43osoil.wtr_erod_fctr wtr_erod_fctr,
ewt43osoil.soil_loss_tolr soil_loss_tolr_fctr,
ewt43osoil.wind_erod_idx wind_erod_idx,
ewt43osoil.long_leaf_suit_ind long_leaf_suit_ind,
ewt43osoil.soil_slp_lgth_fctr soil_slp_lgth_fctr,
ewt43osoil.wesl_ind wesl_ind,
ewt43osoil.nipf_prd_adj_factor_pct nipf_prd_adj_factor_pct,
null cnsv_ctr_seq_nbr,
null cnsv_ctr_sfx_cd,
ewt43osoil.ofr_scnr_id ofr_scnr_id,
ewt43osoil.data_stat_cd data_stat_cd,
ewt43osoil.cre_dt cre_dt,
ewt43osoil.last_chg_dt last_chg_dt,
ewt43osoil.last_chg_user_nm last_chg_user_nm,
ewt43osoil.op as cdc_oper_cd,
current_timestamp() as load_dt,
'cnsv_ewt43osoil' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as row_num_part
from `fsa-{env}-cnsv-cdc`.`ewt43osoil`
 where ewt43osoil.op = 'D'