-- Julia Lu edition - will upthis paragraph and query when cnsv-cdc is ready
-- Stage SQL: CNSV_EWT42OFPRAC (incremental)
-- Location: s3://c108-cert-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_EWT42OFPRAC/incremental/CNSV_EWT42OFPRAC.sql
-- =============================================================================
select * from
(
select distinct pgm_yr,
adm_st_fsa_cd,
adm_cnty_fsa_cd,
tr_nbr,
ofr_scnr_nm,
sgnp_type_desc,
sgnp_stype_desc,
sgnp_nbr,
sgnp_stype_agr_nm,
fld_nbr,
cnsv_prac_cd,
farm_nbr,
prac_seq_nbr,
st_fsa_cd,
cnty_fsa_cd,
prac_acrg,
cost_shr_est_amt,
crp_prac_yr_ct,
hdwd_tree_plnt_ind,
long_leaf_pine_ind,
cp12_acrg,
prac_mnt_rt,
crp_sip_amt,
crp_pip_amt,
prac_rt_cat_desc,
prac_ar_nbr,
crp_1_actv_acrg,
prac_land_stat_cd,
ofr_clu_id,
prac_land_type_cd,
mpl_acrg,
pvt_irr_crnr_ind,
cpld_acrg,
cnsv_ctr_seq_nbr,
cnsv_ctr_sfx_cd,
ofr_scnr_id,
ncpld_acrg,
wlhd_acrg,
ifsbl_to_farm_acrg,
crp_expr_cpld_acrg,
crp_expr_ncpld_acrg,
crp_expr_mpl_acrg,
grp_expr_cpld_acrg,
grp_expr_ncpld_acrg,
prac_inctv_rt,
crp_expr_wlhd_acrg,
crp_expr_ifsbl_to_farm_acrg,
data_stat_cd,
cre_dt,
last_chg_dt,
last_chg_user_nm,
cnsv_elg_area_cd,
clu_hist_nbr,
crp_acre_rent_rdn_cd,
ifsbl_to_farm_prac_inctv_rt,
cdc_oper_cd,
load_dt,
data_src_nm,
cdc_dt,
row_number() over ( partition by 
prac_seq_nbr,
ofr_scnr_id
order by tbl_priority asc, last_chg_dt desc ) as row_num_part
from
(
select 
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt42ofprac.fld_nbr fld_nbr,
ewt42ofprac.cnsv_prac_cd cnsv_prac_cd,
ewt40ofrsc.farm_nbr farm_nbr,
ewt42ofprac.prac_seq_nbr prac_seq_nbr,
ewt42ofprac.st_fsa_cd st_fsa_cd,
ewt42ofprac.cnty_fsa_cd cnty_fsa_cd,
ewt42ofprac.prac_acrg prac_acrg,
ewt42ofprac.cost_shr_est_amt cost_shr_est_amt,
ewt42ofprac.crp_prac_yr_ct crp_prac_yr_ct,
ewt42ofprac.hard_tree_plnt_ind hdwd_tree_plnt_ind,
ewt42ofprac.long_leaf_pine_ind long_leaf_pine_ind,
ewt42ofprac.cp12_acrg cp12_acrg,
ewt42ofprac.prac_mnt_rt prac_mnt_rt,
ewt42ofprac.crp_sip_amt crp_sip_amt,
ewt42ofprac.crp_pip_amt crp_pip_amt,
ewt42ofprac.prac_rt_cat_desc prac_rt_cat_desc,
ewt42ofprac.prac_ar_nbr prac_ar_nbr,
ewt42ofprac.crp_1_actv_acrg crp_1_actv_acrg,
ewt42ofprac.prac_land_stat_cd prac_land_stat_cd,
ewt42ofprac.ofr_clu_id ofr_clu_id,
ewt42ofprac.prac_land_type_cd prac_land_type_cd,
ewt42ofprac.mpl_acrg mpl_acrg,
ewt42ofprac.pvt_irr_crnr_ind pvt_irr_crnr_ind,
ewt42ofprac.cpld_acrg cpld_acrg,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt42ofprac.ofr_scnr_id ofr_scnr_id,
ewt42ofprac.ncpld_acrg ncpld_acrg,
ewt42ofprac.wlhd_acrg wlhd_acrg,
ewt42ofprac.ifbl_to_farm_acrg ifsbl_to_farm_acrg,
ewt42ofprac.crp_expr_cpld_acrg crp_expr_cpld_acrg,
ewt42ofprac.crp_expr_ncpld_acrg crp_expr_ncpld_acrg,
ewt42ofprac.crp_expr_mpl_acrg crp_expr_mpl_acrg,
ewt42ofprac.grp_expr_cpld_acrg grp_expr_cpld_acrg,
ewt42ofprac.grp_expr_ncpld_acrg grp_expr_ncpld_acrg,
ewt42ofprac.prac_inctv_rt prac_inctv_rt,
ewt42ofprac.crp_expr_wlhd_acrg crp_expr_wlhd_acrg,
ewt42ofprac.crp_expr_ifbl_to_farm_acrg crp_expr_ifsbl_to_farm_acrg,
ewt42ofprac.data_stat_cd data_stat_cd,
ewt42ofprac.cre_dt cre_dt,
ewt42ofprac.last_chg_dt last_chg_dt,
ewt42ofprac.last_chg_user_nm last_chg_user_nm,
ewt42ofprac.cnsv_elg_area_cd cnsv_elg_area_cd,
ewt42ofprac.clu_hist_nbr clu_hist_nbr,
ewt42ofprac.crp_acre_rent_rdn_cd crp_acre_rent_rdn_cd,
ewt42ofprac.ifsbl_to_farm_prac_inctv_rt ifsbl_to_farm_prac_inctv_rt,
ewt42ofprac.op as cdc_oper_cd,
current_timestamp() as load_dt,
'ewt42ofprac' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as tbl_priority
from `fsa-{env}-cnsv-cdc`.`ewt42ofprac` 
left join `fsa-{env}-cnsv`.`ewt40ofrsc` on (ewt42ofprac.ofr_scnr_id = ewt40ofrsc.ofr_scnr_id) 
left join `fsa-{env}-cnsv`.`ewt14sgnp` on (ewt40ofrsc.sgnp_id = ewt14sgnp.sgnp_id)
where ewt42ofprac.op <> 'D'
  and ewt42ofprac.dart_filedate between '{etl_start_date}' and '{etl_end_date}'
union
select 
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt42ofprac.fld_nbr fld_nbr,
ewt42ofprac.cnsv_prac_cd cnsv_prac_cd,
ewt40ofrsc.farm_nbr farm_nbr,
ewt42ofprac.prac_seq_nbr prac_seq_nbr,
ewt42ofprac.st_fsa_cd st_fsa_cd,
ewt42ofprac.cnty_fsa_cd cnty_fsa_cd,
ewt42ofprac.prac_acrg prac_acrg,
ewt42ofprac.cost_shr_est_amt cost_shr_est_amt,
ewt42ofprac.crp_prac_yr_ct crp_prac_yr_ct,
ewt42ofprac.hard_tree_plnt_ind hdwd_tree_plnt_ind,
ewt42ofprac.long_leaf_pine_ind long_leaf_pine_ind,
ewt42ofprac.cp12_acrg cp12_acrg,
ewt42ofprac.prac_mnt_rt prac_mnt_rt,
ewt42ofprac.crp_sip_amt crp_sip_amt,
ewt42ofprac.crp_pip_amt crp_pip_amt,
ewt42ofprac.prac_rt_cat_desc prac_rt_cat_desc,
ewt42ofprac.prac_ar_nbr prac_ar_nbr,
ewt42ofprac.crp_1_actv_acrg crp_1_actv_acrg,
ewt42ofprac.prac_land_stat_cd prac_land_stat_cd,
ewt42ofprac.ofr_clu_id ofr_clu_id,
ewt42ofprac.prac_land_type_cd prac_land_type_cd,
ewt42ofprac.mpl_acrg mpl_acrg,
ewt42ofprac.pvt_irr_crnr_ind pvt_irr_crnr_ind,
ewt42ofprac.cpld_acrg cpld_acrg,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt42ofprac.ofr_scnr_id ofr_scnr_id,
ewt42ofprac.ncpld_acrg ncpld_acrg,
ewt42ofprac.wlhd_acrg wlhd_acrg,
ewt42ofprac.ifbl_to_farm_acrg ifsbl_to_farm_acrg,
ewt42ofprac.crp_expr_cpld_acrg crp_expr_cpld_acrg,
ewt42ofprac.crp_expr_ncpld_acrg crp_expr_ncpld_acrg,
ewt42ofprac.crp_expr_mpl_acrg crp_expr_mpl_acrg,
ewt42ofprac.grp_expr_cpld_acrg grp_expr_cpld_acrg,
ewt42ofprac.grp_expr_ncpld_acrg grp_expr_ncpld_acrg,
ewt42ofprac.prac_inctv_rt prac_inctv_rt,
ewt42ofprac.crp_expr_wlhd_acrg crp_expr_wlhd_acrg,
ewt42ofprac.crp_expr_ifbl_to_farm_acrg crp_expr_ifsbl_to_farm_acrg,
ewt42ofprac.data_stat_cd data_stat_cd,
ewt42ofprac.cre_dt cre_dt,
ewt42ofprac.last_chg_dt last_chg_dt,
ewt42ofprac.last_chg_user_nm last_chg_user_nm,
ewt42ofprac.cnsv_elg_area_cd cnsv_elg_area_cd,
ewt42ofprac.clu_hist_nbr clu_hist_nbr,
ewt42ofprac.crp_acre_rent_rdn_cd crp_acre_rent_rdn_cd,
ewt42ofprac.ifsbl_to_farm_prac_inctv_rt ifsbl_to_farm_prac_inctv_rt,
ewt40ofrsc.op as cdc_oper_cd,
current_timestamp() as load_dt,
'ewt42ofprac' as data_src_nm,
'{etl_start_date}' as cdc_dt,
2 as tbl_priority
from `fsa-{env}-cnsv`.`ewt40ofrsc`
join `fsa-{env}-cnsv-cdc`.`ewt42ofprac` on (ewt40ofrsc.ofr_scnr_id = ewt42ofprac.ofr_scnr_id) 
left join `fsa-{env}-cnsv`.`ewt14sgnp` on (ewt40ofrsc.sgnp_id = ewt14sgnp.sgnp_id)
where ewt40ofrsc.op <> 'D'

union
select 
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt42ofprac.fld_nbr fld_nbr,
ewt42ofprac.cnsv_prac_cd cnsv_prac_cd,
ewt40ofrsc.farm_nbr farm_nbr,
ewt42ofprac.prac_seq_nbr prac_seq_nbr,
ewt42ofprac.st_fsa_cd st_fsa_cd,
ewt42ofprac.cnty_fsa_cd cnty_fsa_cd,
ewt42ofprac.prac_acrg prac_acrg,
ewt42ofprac.cost_shr_est_amt cost_shr_est_amt,
ewt42ofprac.crp_prac_yr_ct crp_prac_yr_ct,
ewt42ofprac.hard_tree_plnt_ind hdwd_tree_plnt_ind,
ewt42ofprac.long_leaf_pine_ind long_leaf_pine_ind,
ewt42ofprac.cp12_acrg cp12_acrg,
ewt42ofprac.prac_mnt_rt prac_mnt_rt,
ewt42ofprac.crp_sip_amt crp_sip_amt,
ewt42ofprac.crp_pip_amt crp_pip_amt,
ewt42ofprac.prac_rt_cat_desc prac_rt_cat_desc,
ewt42ofprac.prac_ar_nbr prac_ar_nbr,
ewt42ofprac.crp_1_actv_acrg crp_1_actv_acrg,
ewt42ofprac.prac_land_stat_cd prac_land_stat_cd,
ewt42ofprac.ofr_clu_id ofr_clu_id,
ewt42ofprac.prac_land_type_cd prac_land_type_cd,
ewt42ofprac.mpl_acrg mpl_acrg,
ewt42ofprac.pvt_irr_crnr_ind pvt_irr_crnr_ind,
ewt42ofprac.cpld_acrg cpld_acrg,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt42ofprac.ofr_scnr_id ofr_scnr_id,
ewt42ofprac.ncpld_acrg ncpld_acrg,
ewt42ofprac.wlhd_acrg wlhd_acrg,
ewt42ofprac.ifbl_to_farm_acrg ifsbl_to_farm_acrg,
ewt42ofprac.crp_expr_cpld_acrg crp_expr_cpld_acrg,
ewt42ofprac.crp_expr_ncpld_acrg crp_expr_ncpld_acrg,
ewt42ofprac.crp_expr_mpl_acrg crp_expr_mpl_acrg,
ewt42ofprac.grp_expr_cpld_acrg grp_expr_cpld_acrg,
ewt42ofprac.grp_expr_ncpld_acrg grp_expr_ncpld_acrg,
ewt42ofprac.prac_inctv_rt prac_inctv_rt,
ewt42ofprac.crp_expr_wlhd_acrg crp_expr_wlhd_acrg,
ewt42ofprac.crp_expr_ifbl_to_farm_acrg crp_expr_ifsbl_to_farm_acrg,
ewt42ofprac.data_stat_cd data_stat_cd,
ewt42ofprac.cre_dt cre_dt,
ewt42ofprac.last_chg_dt last_chg_dt,
ewt42ofprac.last_chg_user_nm last_chg_user_nm,
ewt42ofprac.cnsv_elg_area_cd cnsv_elg_area_cd,
ewt42ofprac.clu_hist_nbr clu_hist_nbr,
ewt42ofprac.crp_acre_rent_rdn_cd crp_acre_rent_rdn_cd,
ewt42ofprac.ifsbl_to_farm_prac_inctv_rt ifsbl_to_farm_prac_inctv_rt,
ewt14sgnp.op as cdc_oper_cd,
current_timestamp() as load_dt,
'ewt42ofprac' as data_src_nm,
'{etl_start_date}' as cdc_dt,
3 as tbl_priority
from `fsa-{env}-cnsv`.`ewt14sgnp`
left join `fsa-{env}-cnsv`.`ewt40ofrsc` on (ewt14sgnp.sgnp_id = ewt40ofrsc.sgnp_id) 
join `fsa-{env}-cnsv-cdc`.`ewt42ofprac` on (ewt40ofrsc.ofr_scnr_id = ewt42ofprac.ofr_scnr_id)
where ewt14sgnp.op <> 'D'
) stg_all
) stg_unq
where row_num_part = 1

union
select distinct
null pgm_yr,
null adm_st_fsa_cd,
null adm_cnty_fsa_cd,
null tr_nbr,
null ofr_scnr_nm,
null sgnp_type_desc,
null sgnp_stype_desc,
null sgnp_nbr,
null sgnp_stype_agr_nm,
ewt42ofprac.fld_nbr fld_nbr,
ewt42ofprac.cnsv_prac_cd cnsv_prac_cd,
null farm_nbr,
ewt42ofprac.prac_seq_nbr prac_seq_nbr,
ewt42ofprac.st_fsa_cd st_fsa_cd,
ewt42ofprac.cnty_fsa_cd cnty_fsa_cd,
ewt42ofprac.prac_acrg prac_acrg,
ewt42ofprac.cost_shr_est_amt cost_shr_est_amt,
ewt42ofprac.crp_prac_yr_ct crp_prac_yr_ct,
ewt42ofprac.hard_tree_plnt_ind hdwd_tree_plnt_ind,
ewt42ofprac.long_leaf_pine_ind long_leaf_pine_ind,
ewt42ofprac.cp12_acrg cp12_acrg,
ewt42ofprac.prac_mnt_rt prac_mnt_rt,
ewt42ofprac.crp_sip_amt crp_sip_amt,
ewt42ofprac.crp_pip_amt crp_pip_amt,
ewt42ofprac.prac_rt_cat_desc prac_rt_cat_desc,
ewt42ofprac.prac_ar_nbr prac_ar_nbr,
ewt42ofprac.crp_1_actv_acrg crp_1_actv_acrg,
ewt42ofprac.prac_land_stat_cd prac_land_stat_cd,
ewt42ofprac.ofr_clu_id ofr_clu_id,
ewt42ofprac.prac_land_type_cd prac_land_type_cd,
ewt42ofprac.mpl_acrg mpl_acrg,
ewt42ofprac.pvt_irr_crnr_ind pvt_irr_crnr_ind,
ewt42ofprac.cpld_acrg cpld_acrg,
null cnsv_ctr_seq_nbr,
null cnsv_ctr_sfx_cd,
ewt42ofprac.ofr_scnr_id ofr_scnr_id,
null ncpld_acrg,
null wlhd_acrg,
null ifsbl_to_farm_acrg,
null crp_expr_cpld_acrg,
null crp_expr_ncpld_acrg,
null crp_expr_mpl_acrg,
null grp_expr_cpld_acrg,
null grp_expr_ncpld_acrg,
null prac_inctv_rt,
null crp_expr_wlhd_acrg,
null crp_expr_ifsbl_to_farm_acrg,
ewt42ofprac.data_stat_cd data_stat_cd,
ewt42ofprac.cre_dt cre_dt,
ewt42ofprac.last_chg_dt last_chg_dt,
ewt42ofprac.last_chg_user_nm last_chg_user_nm,
ewt42ofprac.cnsv_elg_area_cd cnsv_elg_area_cd,
ewt42ofprac.clu_hist_nbr clu_hist_nbr,
ewt42ofprac.crp_acre_rent_rdn_cd crp_acre_rent_rdn_cd,
ewt42ofprac.ifsbl_to_farm_prac_inctv_rt ifsbl_to_farm_prac_inctv_rt,
ewt42ofprac.op as cdc_oper_cd,
current_timestamp() as load_dt,
'ewt42ofprac' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as row_num_part
from `fsa-{env}-cnsv-cdc`.`ewt42ofprac`
where ewt42ofprac.op = 'D'
