SELECT DISTINCT
CTR_CORE_DET.CTR_CORE_DET_ID CTR_CORE_DET_ID,
CTR_CORE_DET.DATA_LOCKED_DATE DATA_LOCK_DT,
CTR_CORE_DET.DATA_STATUS_CODE DATA_STAT_CD,
CTR_CORE_DET.CREATION_DATE CRE_DT,
CTR_CORE_DET.CREATION_USER_NAME CRE_USER_NM,
CTR_CORE_DET.LAST_CHANGE_DATE LAST_CHG_DT,
CTR_CORE_DET.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CTR_CORE_DET.PARTICIPATION_START_YEAR_LAST_UPDATE_DATE PTCP_STRT_YR_LAST_UPD_DT,
CTR_CORE_DET.COST_SHARE_EXEMPTION_INDICATOR COST_SHR_EXMP_IND,
OP AS CDC_OPER_CD,
1 AS row_num_part
FROM CTR_CORE_DET
WHERE OP <> 'D'
UNION
SELECT DISTINCT
CTR_CORE_DET.CTR_CORE_DET_ID CTR_CORE_DET_ID,
CTR_CORE_DET.DATA_LOCKED_DATE DATA_LOCK_DT,
CTR_CORE_DET.DATA_STATUS_CODE DATA_STAT_CD,
CTR_CORE_DET.CREATION_DATE CRE_DT,
CTR_CORE_DET.CREATION_USER_NAME CRE_USER_NM,
CTR_CORE_DET.LAST_CHANGE_DATE LAST_CHG_DT,
CTR_CORE_DET.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CTR_CORE_DET.PARTICIPATION_START_YEAR_LAST_UPDATE_DATE PTCP_STRT_YR_LAST_UPD_DT,
CTR_CORE_DET.COST_SHARE_EXEMPTION_INDICATOR COST_SHR_EXMP_IND,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM CTR_CORE_DET
WHERE OP = 'D'