INSERT into
EDV.FRS_CNTY_OFC_CTL_RS(ST_FSA_CD,
CNTY_FSA_CD,
CNTY_OFC_CTL_ID,
LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
TM_PRD_ID,
LAST_ASGN_FARM_NBR,
LAST_ASGN_TR_NBR,
LAST_ASGN_RCON_SEQ_NBR, 
SRC_ST_FSA_CD,
SRC_CNTY_FSA_CD,
DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(
SELECT stg.* from (
SELECT DISTINCT
coalesce(FSA_CNTY_RH.ST_FSA_CD, '--') ST_FSA_CD,
coalesce(FSA_CNTY_RH.CNTY_FSA_CD, '--') CNTY_FSA_CD,
CNTY_OFC_CTL.CNTY_OFC_CTL_ID CNTY_OFC_CTL_ID,
CNTY_OFC_CTL.LOAD_DT LOAD_DT,
CNTY_OFC_CTL.CDC_DT DATA_EFF_STRT_DT,
CNTY_OFC_CTL.DATA_SRC_NM DATA_SRC_NM,
CNTY_OFC_CTL.DATA_STAT_CD DATA_STAT_CD,
CNTY_OFC_CTL.CRE_DT SRC_CRE_DT,
CNTY_OFC_CTL.LAST_CHG_DT SRC_LAST_CHG_DT,
CNTY_OFC_CTL.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
CNTY_OFC_CTL.TM_PRD_ID TM_PRD_ID,
CNTY_OFC_CTL.LAST_ASGN_FARM_NBR LAST_ASGN_FARM_NBR,
CNTY_OFC_CTL.LAST_ASGN_TR_NBR LAST_ASGN_TR_NBR,
CNTY_OFC_CTL.LAST_ASGN_RCON_SEQ_NBR LAST_ASGN_RCON_SEQ_NBR ,
CNTY_OFC_CTL.ST_FSA_CD SRC_ST_FSA_CD, 
CNTY_OFC_CTL.CNTY_FSA_CD SRC_CNTY_FSA_CD,
TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(trim(both FSA_CNTY_RH.ST_FSA_CD)||'~~'||trim(both FSA_CNTY_RH.CNTY_FSA_CD)||'~~'||CNTY_OFC_CTL.CNTY_OFC_CTL_ID||'~~'||trim(both CNTY_OFC_CTL.DATA_STAT_CD)||'~~'||to_char(CNTY_OFC_CTL.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(CNTY_OFC_CTL.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CNTY_OFC_CTL.LAST_CHG_USER_NM)||'~~'||CNTY_OFC_CTL.TM_PRD_ID||'~~'||CNTY_OFC_CTL.LAST_ASGN_FARM_NBR||'~~'||CNTY_OFC_CTL.LAST_ASGN_TR_NBR||'~~'||CNTY_OFC_CTL.LAST_ASGN_RCON_SEQ_NBR||'~~'||trim(both CNTY_OFC_CTL.ST_FSA_CD)||'~~'||trim(both CNTY_OFC_CTL.CNTY_FSA_CD)) HASH_DIF
FROM SQL_FARM_RCD_STG.CNTY_OFC_CTL  
JOIN EDV.FSA_CNTY_RH ON (CNTY_OFC_CTL.ST_FSA_CD = FSA_CNTY_RH.ST_FSA_CD AND CNTY_OFC_CTL.CNTY_FSA_CD = FSA_CNTY_RH.CNTY_FSA_CD)
where CNTY_OFC_CTL.cdc_oper_cd IN ('I','UN')
order by CNTY_OFC_CTL.CDC_DT
) stg 
LEFT JOIN  EDV.FRS_CNTY_OFC_CTL_RS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.FRS_CNTY_OFC_CTL_RS rs
				where stg.ST_FSA_CD = rs.ST_FSA_CD
				and stg.CNTY_FSA_CD = rs.CNTY_FSA_CD
				and stg.LOAD_DT = rs.LOAD_DT
               )
)
;

