Merge into
EDV.FARM_YR_CROP_IRR_HIST_LS dv
using(select DISTINCT MD5(upper(coalesce(trim(both FARM_YR_CROP_IRR_HIST.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_CROP_IRR_HIST.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_CROP_IRR_HIST.FSA_CROP_TYPE_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_CROP_IRR_HIST.ST_FSA_CD), '--')) ||'~~'||upper(coalesce(trim(both FARM_YR_CROP_IRR_HIST.CNTY_FSA_CD), '--')) ||'~~'||MD5(upper(coalesce(FARM_YR_CROP_IRR_HIST.FARM_ST_FSA_CD ,'--')||'~~'||coalesce(FARM_YR_CROP_IRR_HIST.FARM_CNTY_FSA_CD,'--')||'~~'||coalesce(FARM_YR_CROP_IRR_HIST.FARM_NBR ,'--')))) FARM_CROP_IRR_HIST_L_ID,FARM_YR_CROP_IRR_HIST.FARM_YR_CROP_IRR_HIST_ID FARM_YR_CROP_IRR_HIST_ID,FARM_YR_CROP_IRR_HIST.LOAD_DT LOAD_DT,FARM_YR_CROP_IRR_HIST.CDC_DT DATA_EFF_STRT_DT,FARM_YR_CROP_IRR_HIST.DATA_SRC_NM DATA_SRC_NM,FARM_YR_CROP_IRR_HIST.DATA_STAT_CD DATA_STAT_CD,FARM_YR_CROP_IRR_HIST.CRE_DT SRC_CRE_DT,FARM_YR_CROP_IRR_HIST.CRE_USER_NM SRC_CRE_USER_NM,FARM_YR_CROP_IRR_HIST.LAST_CHG_DT SRC_LAST_CHG_DT,FARM_YR_CROP_IRR_HIST.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,FARM_YR_CROP_IRR_HIST.FARM_YR_ID FARM_YR_ID,FARM_YR_CROP_IRR_HIST.IRR_CNTY_CROP_ID IRR_CNTY_CROP_ID,FARM_YR_CROP_IRR_HIST.HIST_IRR_PCT HIST_IRR_PCT,FARM_YR_CROP_IRR_HIST.PGM_YR PGM_YR ,
FARM_YR_CROP_IRR_HIST.CDC_OPER_CD,
MD5(trim(both FARM_YR_CROP_IRR_HIST.PGM_ABR)||'~~'||trim(both FARM_YR_CROP_IRR_HIST.FSA_CROP_CD)||'~~'||trim(both FARM_YR_CROP_IRR_HIST.FSA_CROP_TYPE_CD)||'~~'||trim(both FARM_YR_CROP_IRR_HIST.ST_FSA_CD)||'~~'||trim(both FARM_YR_CROP_IRR_HIST.CNTY_FSA_CD)||'~~'||upper(coalesce(FARM_YR_CROP_IRR_HIST.FARM_ST_FSA_CD ,'--')||'~~'||coalesce(FARM_YR_CROP_IRR_HIST.FARM_CNTY_FSA_CD,'--')||'~~'||coalesce(FARM_YR_CROP_IRR_HIST.FARM_NBR ,'--'))||'~~'||FARM_YR_CROP_IRR_HIST.FARM_YR_CROP_IRR_HIST_ID||'~~'||trim(both FARM_YR_CROP_IRR_HIST.DATA_STAT_CD)||'~~'||to_char(FARM_YR_CROP_IRR_HIST.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both FARM_YR_CROP_IRR_HIST.CRE_USER_NM)||'~~'||to_char(FARM_YR_CROP_IRR_HIST.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both FARM_YR_CROP_IRR_HIST.LAST_CHG_USER_NM)||'~~'||FARM_YR_CROP_IRR_HIST.FARM_YR_ID||'~~'||FARM_YR_CROP_IRR_HIST.IRR_CNTY_CROP_ID||'~~'||FARM_YR_CROP_IRR_HIST.HIST_IRR_PCT||'~~'||FARM_YR_CROP_IRR_HIST.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.FARM_YR_CROP_IRR_HIST  FARM_YR_CROP_IRR_HIST
 where FARM_YR_CROP_IRR_HIST.CDC_OPER_CD='D'
order by FARM_YR_CROP_IRR_HIST.CDC_DT)
stg
 on ( 
coalesce(stg.FARM_YR_CROP_IRR_HIST_ID,0) = coalesce(dv.FARM_YR_CROP_IRR_HIST_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN
INSERT(
FARM_CROP_IRR_HIST_L_ID,FARM_YR_CROP_IRR_HIST_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_CRE_USER_NM,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
FARM_YR_ID,
IRR_CNTY_CROP_ID,
HIST_IRR_PCT,
PGM_YR, 
DATA_EFF_END_DT,LOAD_END_DT,HASH_DIF)
VALUES (
stg.FARM_CROP_IRR_HIST_L_ID,stg.FARM_YR_CROP_IRR_HIST_ID,stg.LOAD_DT,stg.DATA_EFF_STRT_DT,stg.DATA_SRC_NM,stg.DATA_STAT_CD,stg.SRC_CRE_DT,stg.SRC_CRE_USER_NM,stg.SRC_LAST_CHG_DT,stg.SRC_LAST_CHG_USER_NM,stg.FARM_YR_ID,stg.IRR_CNTY_CROP_ID,stg.HIST_IRR_PCT,stg.PGM_YR,stg.DATA_EFF_STRT_DT,stg.LOAD_DT,
stg.HASH_DIF
)
;