-- Julia Lu edition - will update this paragraph and query when (cnsv/ccms)-cdc is ready
-- Stage SQL: CNSV_CNSV_OFR_ELG_AR (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_CNSV_OFR_ELG_AR/incremental/CNSV_CNSV_OFR_ELG_AR.sql
-- =============================================================================
SELECT * FROM
(
SELECT DISTINCT PGM_YR,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
TR_NBR,
OFR_SCNR_NM,
SGNP_NBR,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_STYPE_AGR_NM,
CNSV_ELG_AR_NM,
CNSV_OFR_ELG_AR_PCT,
GIS_OFR_CRE_IND,
CNSV_OFR_ELG_AR_ID,
SGNP_ID,
CNSV_ELG_AR_ID,
OFR_SCNR_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CNSV_OFR_ELG_AR_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
conservation_eligibility_area.CNSV_ELG_AREA_NM CNSV_ELG_AR_NM,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_PCT CNSV_OFR_ELG_AR_PCT,
conservation_offer_eligibility_area.GIS_OFR_CRE_IND GIS_OFR_CRE_IND,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_ID CNSV_OFR_ELG_AR_ID,
conservation_offer_eligibility_area.SGNP_ID SGNP_ID,
conservation_offer_eligibility_area.CNSV_ELG_AREA_ID CNSV_ELG_AR_ID,
conservation_offer_eligibility_area.OFR_SCNR_ID OFR_SCNR_ID,
conservation_offer_eligibility_area.DATA_STAT_CD DATA_STAT_CD,
conservation_offer_eligibility_area.CRE_DT CRE_DT,
conservation_offer_eligibility_area.LAST_CHG_DT LAST_CHG_DT,
conservation_offer_eligibility_area.LAST_CHG_USER_NM LAST_CHG_USER_NM,
CONSERVATION_OFFER_ELIGIBILITY_AREA.op,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".CONSERVATION_OFFER_ELIGIBILITY_AREA   
LEFT JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION 
ON(CONSERVATION_OFFER_ELIGIBILITY_AREA.SGNP_ID = CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.SGNP_ID 
AND CONSERVATION_OFFER_ELIGIBILITY_AREA.CNSV_ELG_AREA_ID = CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.CNSV_ELG_AREA_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_ELIGIBILITY_AREA 
ON(CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.CNSV_ELG_AREA_ID = CONSERVATION_ELIGIBILITY_AREA.CNSV_ELG_AREA_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".EWT40OFRSC 
ON(CONSERVATION_OFFER_ELIGIBILITY_AREA.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".EWT14SGNP 
ON(EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
WHERE CONSERVATION_OFFER_ELIGIBILITY_AREA.op <> 'D'

UNION
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
conservation_eligibility_area.CNSV_ELG_AREA_NM CNSV_ELG_AR_NM,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_PCT CNSV_OFR_ELG_AR_PCT,
conservation_offer_eligibility_area.GIS_OFR_CRE_IND GIS_OFR_CRE_IND,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_ID CNSV_OFR_ELG_AR_ID,
conservation_offer_eligibility_area.SGNP_ID SGNP_ID,
conservation_offer_eligibility_area.CNSV_ELG_AREA_ID CNSV_ELG_AR_ID,
conservation_offer_eligibility_area.OFR_SCNR_ID OFR_SCNR_ID,
conservation_offer_eligibility_area.DATA_STAT_CD DATA_STAT_CD,
conservation_offer_eligibility_area.CRE_DT CRE_DT,
conservation_offer_eligibility_area.LAST_CHG_DT LAST_CHG_DT,
conservation_offer_eligibility_area.LAST_CHG_USER_NM LAST_CHG_USER_NM,
CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.op,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION   
JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_OFFER_ELIGIBILITY_AREA 
ON(CONSERVATION_OFFER_ELIGIBILITY_AREA.SGNP_ID = CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.SGNP_ID 
AND CONSERVATION_OFFER_ELIGIBILITY_AREA.CNSV_ELG_AREA_ID = CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.CNSV_ELG_AREA_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_ELIGIBILITY_AREA 
ON(CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.CNSV_ELG_AREA_ID = CONSERVATION_ELIGIBILITY_AREA.CNSV_ELG_AREA_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".EWT40OFRSC 
ON(CONSERVATION_OFFER_ELIGIBILITY_AREA.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".EWT14SGNP 
ON(EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
WHERE CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.op <> 'D'

UNION
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
conservation_eligibility_area.CNSV_ELG_AREA_NM CNSV_ELG_AR_NM,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_PCT CNSV_OFR_ELG_AR_PCT,
conservation_offer_eligibility_area.GIS_OFR_CRE_IND GIS_OFR_CRE_IND,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_ID CNSV_OFR_ELG_AR_ID,
conservation_offer_eligibility_area.SGNP_ID SGNP_ID,
conservation_offer_eligibility_area.CNSV_ELG_AREA_ID CNSV_ELG_AR_ID,
conservation_offer_eligibility_area.OFR_SCNR_ID OFR_SCNR_ID,
conservation_offer_eligibility_area.DATA_STAT_CD DATA_STAT_CD,
conservation_offer_eligibility_area.CRE_DT CRE_DT,
conservation_offer_eligibility_area.LAST_CHG_DT LAST_CHG_DT,
conservation_offer_eligibility_area.LAST_CHG_USER_NM LAST_CHG_USER_NM,
CONSERVATION_ELIGIBILITY_AREA.op,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".CONSERVATION_ELIGIBILITY_AREA   
LEFT JOIN  "fsa-{env}-cnsv-cdc".CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION 
ON(CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.CNSV_ELG_AREA_ID = CONSERVATION_ELIGIBILITY_AREA.CNSV_ELG_AREA_ID) 
JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_OFFER_ELIGIBILITY_AREA 
ON(CONSERVATION_OFFER_ELIGIBILITY_AREA.SGNP_ID = CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.SGNP_ID 
AND CONSERVATION_OFFER_ELIGIBILITY_AREA.CNSV_ELG_AREA_ID = CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.CNSV_ELG_AREA_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".EWT40OFRSC 
ON(CONSERVATION_OFFER_ELIGIBILITY_AREA.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".EWT14SGNP 
ON(EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
WHERE CONSERVATION_ELIGIBILITY_AREA.op <> 'D'

UNION
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
conservation_eligibility_area.CNSV_ELG_AREA_NM CNSV_ELG_AR_NM,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_PCT CNSV_OFR_ELG_AR_PCT,
conservation_offer_eligibility_area.GIS_OFR_CRE_IND GIS_OFR_CRE_IND,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_ID CNSV_OFR_ELG_AR_ID,
conservation_offer_eligibility_area.SGNP_ID SGNP_ID,
conservation_offer_eligibility_area.CNSV_ELG_AREA_ID CNSV_ELG_AR_ID,
conservation_offer_eligibility_area.OFR_SCNR_ID OFR_SCNR_ID,
conservation_offer_eligibility_area.DATA_STAT_CD DATA_STAT_CD,
conservation_offer_eligibility_area.CRE_DT CRE_DT,
conservation_offer_eligibility_area.LAST_CHG_DT LAST_CHG_DT,
conservation_offer_eligibility_area.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT40OFRSC.op,
4 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".EWT40OFRSC   
JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_OFFER_ELIGIBILITY_AREA 
ON(CONSERVATION_OFFER_ELIGIBILITY_AREA.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".EWT14SGNP 
ON(EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION 
ON(CONSERVATION_OFFER_ELIGIBILITY_AREA.SGNP_ID = CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.SGNP_ID 
AND CONSERVATION_OFFER_ELIGIBILITY_AREA.CNSV_ELG_AREA_ID = CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.CNSV_ELG_AREA_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_ELIGIBILITY_AREA 
ON(CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.CNSV_ELG_AREA_ID = CONSERVATION_ELIGIBILITY_AREA.CNSV_ELG_AREA_ID) 
WHERE EWT40OFRSC.op <> 'D'

UNION
SELECT 
ewt40ofrsc.PGM_YR PGM_YR,
ewt40ofrsc.ADM_ST_FSA_CD ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
conservation_eligibility_area.CNSV_ELG_AREA_NM CNSV_ELG_AR_NM,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_PCT CNSV_OFR_ELG_AR_PCT,
conservation_offer_eligibility_area.GIS_OFR_CRE_IND GIS_OFR_CRE_IND,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_ID CNSV_OFR_ELG_AR_ID,
conservation_offer_eligibility_area.SGNP_ID SGNP_ID,
conservation_offer_eligibility_area.CNSV_ELG_AREA_ID CNSV_ELG_AR_ID,
conservation_offer_eligibility_area.OFR_SCNR_ID OFR_SCNR_ID,
conservation_offer_eligibility_area.DATA_STAT_CD DATA_STAT_CD,
conservation_offer_eligibility_area.CRE_DT CRE_DT,
conservation_offer_eligibility_area.LAST_CHG_DT LAST_CHG_DT,
conservation_offer_eligibility_area.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT14SGNP.op,
5 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".EWT14SGNP 
LEFT JOIN "fsa-{env}-cnsv-cdc".EWT40OFRSC 
ON(EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID) 
JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_OFFER_ELIGIBILITY_AREA 
ON(CONSERVATION_OFFER_ELIGIBILITY_AREA.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION 
ON(CONSERVATION_OFFER_ELIGIBILITY_AREA.SGNP_ID = CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.SGNP_ID 
AND CONSERVATION_OFFER_ELIGIBILITY_AREA.CNSV_ELG_AREA_ID = CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.CNSV_ELG_AREA_ID) 
LEFT JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_ELIGIBILITY_AREA 
ON(CONSERVATION_ELIGIBILITY_AREA_ASSOCIATION.CNSV_ELG_AREA_ID = CONSERVATION_ELIGIBILITY_AREA.CNSV_ELG_AREA_ID) 
WHERE EWT14SGNP.op <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND CONSERVATION_OFFER_ELIGIBILITY_AREA.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
NULL PGM_YR,
NULL ADM_ST_FSA_CD,
NULL ADM_CNTY_FSA_CD,
NULL TR_NBR,
NULL OFR_SCNR_NM,
NULL SGNP_NBR,
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_STYPE_AGR_NM,
NULL CNSV_ELG_AR_NM,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_PCT CNSV_OFR_ELG_AR_PCT,
conservation_offer_eligibility_area.GIS_OFR_CRE_IND GIS_OFR_CRE_IND,
conservation_offer_eligibility_area.CNSV_OFR_ELG_AREA_ID CNSV_OFR_ELG_AR_ID,
conservation_offer_eligibility_area.SGNP_ID SGNP_ID,
conservation_offer_eligibility_area.CNSV_ELG_AREA_ID CNSV_ELG_AR_ID,
conservation_offer_eligibility_area.OFR_SCNR_ID OFR_SCNR_ID,
conservation_offer_eligibility_area.DATA_STAT_CD DATA_STAT_CD,
conservation_offer_eligibility_area.CRE_DT CRE_DT,
conservation_offer_eligibility_area.LAST_CHG_DT LAST_CHG_DT,
conservation_offer_eligibility_area.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".conservation_offer_eligibility_area
WHERE conservation_offer_eligibility_area.op = 'D'