SELECT DISTINCT
BUSINESS_RULE_GROUP.BUS_RULE_GRP_NM BUS_RULE_GRP_NM,
BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID BUS_RULE_GRP_ID,
BUSINESS_RULE_GROUP.LAST_CHG_DT LAST_CHG_DT,
BUSINESS_RULE_GROUP.CRE_DT CRE_DT,
BUSINESS_RULE_GROUP.LAST_CHG_USER_NM LAST_CHG_USER_NM,
BUSINESS_RULE_GROUP.CRE_USER_NM CRE_USER_NM,
BUSINESS_RULE_GROUP.DATA_STAT_CD DATA_STAT_CD,
BUSINESS_RULE_GROUP.BUS_RULE_GRP_DESC BUS_RULE_GRP_DESC,
--OP AS CDC_OPER_CD,
1 AS row_num_part
FROM BUSINESS_RULE_GROUP
--WHERE OP <> 'D'
UNION
SELECT DISTINCT
BUSINESS_RULE_GROUP.BUS_RULE_GRP_NM BUS_RULE_GRP_NM,
BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID BUS_RULE_GRP_ID,
BUSINESS_RULE_GROUP.LAST_CHG_DT LAST_CHG_DT,
BUSINESS_RULE_GROUP.CRE_DT CRE_DT,
BUSINESS_RULE_GROUP.LAST_CHG_USER_NM LAST_CHG_USER_NM,
BUSINESS_RULE_GROUP.CRE_USER_NM CRE_USER_NM,
BUSINESS_RULE_GROUP.DATA_STAT_CD DATA_STAT_CD,
BUSINESS_RULE_GROUP.BUS_RULE_GRP_DESC BUS_RULE_GRP_DESC,
--'D' CDC_OPER_CD,
1 AS row_num_part
FROM BUSINESS_RULE_GROUP
--WHERE OP = 'D'