INSERT into
EDV.CNSV_PRAC_RH(CNSV_PRAC_ID,
DATA_SRC_NM,
LOAD_DT)
(
SELECT 
stg.CNSV_PRAC_ID,
stg.DATA_SRC_NM,
stg.LOAD_DT
from (
SELECT DISTINCT
coalesce(DMN_VAL.DMN_CHAR_VAL, '[NULL IN SOURCE]') CNSV_PRAC_ID,
DMN_VAL.DATA_SRC_NM DATA_SRC_NM,
DMN_VAL.LOAD_DT LOAD_DT,
ROW_NUMBER() OVER (PARTITION BY DMN_VAL.DMN_CHAR_VAL ORDER BY DMN_VAL.CDC_DT desc, DMN_VAL.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.DMN_VAL
WHERE DMN_VAL.DMN_ID = 42
and DMN_VAL.cdc_oper_cd IN ('I','UN','D')
) stg 
LEFT JOIN  EDV.CNSV_PRAC_RH dv
 ON (
stg.CNSV_PRAC_ID = dv.CNSV_PRAC_ID
)
where (
dv.CNSV_PRAC_ID IS NULL
)
and stg.STG_EFF_DT_RANK = 1
);