INSERT  into
EDV.CORE_CUST_H(CORE_CUST_ID,
DATA_SRC_NM,
LOAD_DT)
select insert_data.CORE_CUST_ID, insert_data.DATA_SRC_NM, insert_data.LOAD_DT
FROM (
SELECT 
stg.CORE_CUST_ID,
stg.DATA_SRC_NM,
stg.LOAD_DT
from (
select distinct CORE_CUST_ID,DATA_SRC_NM, LOAD_DT,
ROW_NUMBER() OVER (PARTITION BY CORE_CUST_ID ORDER BY CDC_DT desc, LOAD_DT desc) STG_EFF_DT_RANK
from (
SELECT distinct 
coalesce(CLU_PRDR_YR.CORE_CUST_ID, '-1') CORE_CUST_ID,
CLU_PRDR_YR.DATA_SRC_NM DATA_SRC_NM,
CLU_PRDR_YR.LOAD_DT LOAD_DT,
CLU_PRDR_YR.CDC_DT CDC_DT
FROM SQL_FARM_RCD_STG.CLU_PRDR_YR
where CLU_PRDR_YR.cdc_oper_cd IN ('I','UN','D')

UNION

SELECT distinct
coalesce(FARM_PRDR_YR.CORE_CUST_ID, '-1') CORE_CUST_ID,
FARM_PRDR_YR.DATA_SRC_NM DATA_SRC_NM,
FARM_PRDR_YR.LOAD_DT LOAD_DT,
FARM_PRDR_YR.CDC_DT CDC_DT
FROM SQL_FARM_RCD_STG.FARM_PRDR_YR
where FARM_PRDR_YR.cdc_oper_cd IN ('I','UN','D')

UNION

SELECT distinct
coalesce(TR_PRDR_YR.CORE_CUST_ID, '-1') CORE_CUST_ID,
TR_PRDR_YR.DATA_SRC_NM DATA_SRC_NM,
TR_PRDR_YR.LOAD_DT LOAD_DT,
TR_PRDR_YR.CDC_DT CDC_DT
FROM SQL_FARM_RCD_STG.TR_PRDR_YR
where TR_PRDR_YR.cdc_oper_cd IN ('I','UN','D')
) alias9
) stg 
LEFT JOIN  EDV.CORE_CUST_H dv
ON (
stg.CORE_CUST_ID = dv.CORE_CUST_ID
)
where
dv.CORE_CUST_ID IS NULL
and stg.STG_EFF_DT_RANK = 1
) insert_data
where not exists (select 1 from EDV.CORE_CUST_H h 
                  where h.CORE_CUST_ID = insert_data.CORE_CUST_ID
				  )