Merge into
EDV.CROP_TR_YR_DCP_ADJ_LS dv
using(select DISTINCT 
MD5(upper(coalesce(trim(both CROP_TR_YR_DCP_ADJ.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both CROP_TR_YR_DCP_ADJ.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_TR_YR_DCP_ADJ.FSA_CROP_TYPE_CD), '--')) ||'~~'||MD5(upper(coalesce(CROP_TR_YR_DCP_ADJ.ST_FSA_CD,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.FARM_NBR,'--')))||'~~'||MD5(upper(coalesce(CROP_TR_YR_DCP_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce((CROP_TR_YR_DCP_ADJ.TR_NBR)::numeric  ,-1)))) CROP_TR_DCP_L_ID,
coalesce(CROP_TR_YR_DCP_ADJ.CROP_TR_YR_DCP_ADJ_ID, 0) CROP_TR_YR_DCP_ADJ_ID,CROP_TR_YR_DCP_ADJ.LOAD_DT LOAD_DT,CROP_TR_YR_DCP_ADJ.CDC_DT DATA_EFF_STRT_DT,CROP_TR_YR_DCP_ADJ.DATA_SRC_NM DATA_SRC_NM,CROP_TR_YR_DCP_ADJ.DATA_STAT_CD DATA_STAT_CD,CROP_TR_YR_DCP_ADJ.CRE_DT SRC_CRE_DT,CROP_TR_YR_DCP_ADJ.LAST_CHG_DT SRC_LAST_CHG_DT,CROP_TR_YR_DCP_ADJ.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,CROP_TR_YR_DCP_ADJ.CROP_TR_YR_DCP_ID CROP_TR_YR_DCP_ID,CROP_TR_YR_DCP_ADJ.DCP_ADJ_TYPE_CD SRC_DCP_ADJ_TYPE_CD,DCP_ADJ_TYPE_RS.DMN_VAL_NM DCP_ADJ_TYPE_NM,CROP_TR_YR_DCP_ADJ.DCP_ADJ_RSN_CD SRC_DCP_ADJ_RSN_CD,DCP_ADJ_RSN_RS.DMN_VAL_NM DCP_ADJ_RSN_NM,CROP_TR_YR_DCP_ADJ.AFT_ADJ_VAL AFT_ADJ_VAL,CROP_TR_YR_DCP_ADJ.BEF_ADJ_VAL BEF_ADJ_VAL ,
CROP_TR_YR_DCP_ADJ.CDC_OPER_CD,
MD5(trim(both CROP_TR_YR_DCP_ADJ.PGM_ABR)||'~~'||trim(both CROP_TR_YR_DCP_ADJ.FSA_CROP_CD)||'~~'||trim(both CROP_TR_YR_DCP_ADJ.FSA_CROP_TYPE_CD)||'~~'||upper(coalesce(CROP_TR_YR_DCP_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.FARM_NBR ,'--'))||'~~'||upper(coalesce(CROP_TR_YR_DCP_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce((CROP_TR_YR_DCP_ADJ.TR_NBR)::numeric  ,-1))||'~~'||CROP_TR_YR_DCP_ADJ.CROP_TR_YR_DCP_ADJ_ID||'~~'||trim(both CROP_TR_YR_DCP_ADJ.DATA_STAT_CD)||'~~'||to_char(CROP_TR_YR_DCP_ADJ.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(CROP_TR_YR_DCP_ADJ.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_TR_YR_DCP_ADJ.LAST_CHG_USER_NM)||'~~'||CROP_TR_YR_DCP_ADJ.CROP_TR_YR_DCP_ID||'~~'||CROP_TR_YR_DCP_ADJ.DCP_ADJ_TYPE_CD||'~~'||trim(both DCP_ADJ_TYPE_RS.DMN_VAL_NM)||'~~'||CROP_TR_YR_DCP_ADJ.DCP_ADJ_RSN_CD||'~~'||trim(both DCP_ADJ_RSN_RS.DMN_VAL_NM)||'~~'||CROP_TR_YR_DCP_ADJ.AFT_ADJ_VAL||'~~'||CROP_TR_YR_DCP_ADJ.BEF_ADJ_VAL) HASH_DIF
FROM SQL_FARM_RCD_STG.CROP_TR_YR_DCP_ADJ 
LEFT JOIN(select * from EDV.DCP_ADJ_RSN_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) DCP_ADJ_RSN_RS 
ON (CROP_TR_YR_DCP_ADJ.DCP_ADJ_RSN_CD = DCP_ADJ_RSN_RS.DMN_VAL_ID) 
LEFT JOIN(select * from EDV.DCP_ADJ_TYPE_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) DCP_ADJ_TYPE_RS 
ON (CROP_TR_YR_DCP_ADJ.DCP_ADJ_TYPE_CD = DCP_ADJ_TYPE_RS.DMN_VAL_ID)
where CROP_TR_YR_DCP_ADJ.CDC_OPER_CD IN ('I','UN')
order by CROP_TR_YR_DCP_ADJ.CDC_DT)
stg
 on ( 
coalesce(stg.CROP_TR_YR_DCP_ADJ_ID,0) = coalesce(dv.CROP_TR_YR_DCP_ADJ_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;