with cte0 as (
	SELECT 
		MD5(upper(coalesce(trim(both CROP_TR_YR_DCP_ADJ.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both CROP_TR_YR_DCP_ADJ.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_TR_YR_DCP_ADJ.FSA_CROP_TYPE_CD), '--')) ||'~~'||MD5(upper(coalesce(CROP_TR_YR_DCP_ADJ.ST_FSA_CD,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.FARM_NBR,'--')))||'~~'||MD5(upper(coalesce(CROP_TR_YR_DCP_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce((CROP_TR_YR_DCP_ADJ.TR_NBR)::numeric  ,-1)))) as CROP_TR_DCP_L_ID,
		MD5('-1') as CROP_TR_DCP_L_ID_S,
		CROP_TR_YR_DCP_ADJ.CROP_TR_YR_DCP_ADJ_ID CROP_TR_YR_DCP_ADJ_ID,
		CROP_TR_YR_DCP_ADJ.LOAD_DT LOAD_DT,
		CROP_TR_YR_DCP_ADJ.CDC_OPER_CD, 
		CROP_TR_YR_DCP_ADJ.CDC_DT DATA_EFF_STRT_DT,
		CROP_TR_YR_DCP_ADJ.DATA_SRC_NM DATA_SRC_NM,
		CROP_TR_YR_DCP_ADJ.DATA_STAT_CD DATA_STAT_CD,
		CROP_TR_YR_DCP_ADJ.CRE_DT SRC_CRE_DT,
		CROP_TR_YR_DCP_ADJ.LAST_CHG_DT SRC_LAST_CHG_DT,
		CROP_TR_YR_DCP_ADJ.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
		CROP_TR_YR_DCP_ADJ.CROP_TR_YR_DCP_ID CROP_TR_YR_DCP_ID,
		CROP_TR_YR_DCP_ADJ.DCP_ADJ_TYPE_CD SRC_DCP_ADJ_TYPE_CD,
		DCP_ADJ_TYPE_RS.DMN_VAL_NM DCP_ADJ_TYPE_NM,
		CROP_TR_YR_DCP_ADJ.DCP_ADJ_RSN_CD SRC_DCP_ADJ_RSN_CD,
		DCP_ADJ_RSN_RS.DMN_VAL_NM DCP_ADJ_RSN_NM,
		CROP_TR_YR_DCP_ADJ.AFT_ADJ_VAL AFT_ADJ_VAL,
		CROP_TR_YR_DCP_ADJ.BEF_ADJ_VAL BEF_ADJ_VAL,
		to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, 
		to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
		MD5(trim(both CROP_TR_YR_DCP_ADJ.PGM_ABR)||'~~'||trim(both CROP_TR_YR_DCP_ADJ.FSA_CROP_CD)||'~~'||trim(both CROP_TR_YR_DCP_ADJ.FSA_CROP_TYPE_CD)||'~~'||upper(coalesce(CROP_TR_YR_DCP_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.FARM_NBR ,'--'))||'~~'||upper(coalesce(CROP_TR_YR_DCP_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(CROP_TR_YR_DCP_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce((CROP_TR_YR_DCP_ADJ.TR_NBR)::numeric  ,-1))||'~~'||CROP_TR_YR_DCP_ADJ.CROP_TR_YR_DCP_ADJ_ID||'~~'||trim(both CROP_TR_YR_DCP_ADJ.DATA_STAT_CD)||'~~'||to_char(CROP_TR_YR_DCP_ADJ.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(CROP_TR_YR_DCP_ADJ.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_TR_YR_DCP_ADJ.LAST_CHG_USER_NM)||'~~'||CROP_TR_YR_DCP_ADJ.CROP_TR_YR_DCP_ID||'~~'||CROP_TR_YR_DCP_ADJ.DCP_ADJ_TYPE_CD||'~~'||trim(both DCP_ADJ_TYPE_RS.DMN_VAL_NM)||'~~'||CROP_TR_YR_DCP_ADJ.DCP_ADJ_RSN_CD||'~~'||trim(both DCP_ADJ_RSN_RS.DMN_VAL_NM)||'~~'||CROP_TR_YR_DCP_ADJ.AFT_ADJ_VAL||'~~'||CROP_TR_YR_DCP_ADJ.BEF_ADJ_VAL) HASH_DIF
	FROM SQL_FARM_RCD_STG.CROP_TR_YR_DCP_ADJ 
	LEFT JOIN(select * from EDV.DCP_ADJ_RSN_RS
	where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) DCP_ADJ_RSN_RS 
	ON (CROP_TR_YR_DCP_ADJ.DCP_ADJ_RSN_CD = DCP_ADJ_RSN_RS.DMN_VAL_ID) 
	LEFT JOIN(select * from EDV.DCP_ADJ_TYPE_RS
	where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) DCP_ADJ_TYPE_RS 
	ON (CROP_TR_YR_DCP_ADJ.DCP_ADJ_TYPE_CD = DCP_ADJ_TYPE_RS.DMN_VAL_ID)
 	),
cte1 as (
select distinct *
from cte0
where cte0.CDC_OPER_CD IN ('I','UN')
AND (
(cte0.CROP_TR_DCP_L_ID IN (Select CROP_TR_DCP_L_ID From EDV.CROP_TR_DCP_L))
or
(cte0.CROP_TR_DCP_L_ID_S not in (Select CROP_TR_DCP_L_ID From EDV.CROP_TR_DCP_L)))
)

INSERT into 
EDV.CROP_TR_YR_DCP_ADJ_LS(
CROP_TR_DCP_L_ID
, CROP_TR_YR_DCP_ADJ_ID
, LOAD_DT
, DATA_EFF_STRT_DT
, DATA_SRC_NM
, DATA_STAT_CD
, SRC_CRE_DT
, SRC_LAST_CHG_DT
, SRC_LAST_CHG_USER_NM
, CROP_TR_YR_DCP_ID
, SRC_DCP_ADJ_TYPE_CD
, DCP_ADJ_TYPE_NM
, SRC_DCP_ADJ_RSN_CD
, DCP_ADJ_RSN_NM
, AFT_ADJ_VAL
, BEF_ADJ_VAL
, DATA_EFF_END_DT
, LOAD_END_DT
, HASH_DIF
)
(SELECT 
	cte1.CROP_TR_DCP_L_ID
	, cte1.CROP_TR_YR_DCP_ADJ_ID
	, cte1.LOAD_DT
	, cte1.DATA_EFF_STRT_DT
	, cte1.DATA_SRC_NM
	, cte1.DATA_STAT_CD
	, cte1.SRC_CRE_DT
	, cte1.SRC_LAST_CHG_DT
	, cte1.SRC_LAST_CHG_USER_NM
	, cte1.CROP_TR_YR_DCP_ID
	, cte1.SRC_DCP_ADJ_TYPE_CD
	, cte1.DCP_ADJ_TYPE_NM
	, cte1.SRC_DCP_ADJ_RSN_CD
	, cte1.DCP_ADJ_RSN_NM
	, cte1.AFT_ADJ_VAL
	, cte1.BEF_ADJ_VAL
	, cte1.DATA_EFF_END_DT
	, cte1.LOAD_END_DT
	, cte1.HASH_DIF
from cte1 cte1
LEFT JOIN EDV.CROP_TR_YR_DCP_ADJ_LS dv
ON
cte1.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
where dv.HASH_DIF is null
and Not exists (select 1 from EDV.CROP_TR_YR_DCP_ADJ_LS ls
                Where cte1.crop_tr_dcp_l_id = ls.crop_tr_dcp_l_id
				and cte1.crop_tr_yr_dcp_adj_id = ls.crop_tr_yr_dcp_adj_id
				and cte1.load_dt = ls.load_dt
			)
)
;