-- =============================================================================
-- Julia Lu - 2026-01-22
-- Stage SQL: CCMS_CTR_FARM_TR (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/STG/CCMS_CTR_FARM_TR/incremental/CCMS_CTR_FARM_TR.sql
-- Date Logic:
--   ETL_START_DATE = User provided start_date
--   ETL_END_DATE   = Today (automatically set by Glue job)
--
-- Examples:
--   start_date=2025-01-12 (today is 2025-01-12) → Single day
--   start_date=2025-01-10 (today is 2025-01-12) → 3 days catch-up
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_NM,
SGNP_SUB_CAT_NM,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
CTR_NBR,
CTR_SFX_NBR,
FARM_NBR,
TR_NBR,
CTR_FARM_TR_ID,
CTR_DET_ID,
CPLD_ACRG,
MPL_ACRG,
WLHD_ACRG,
NON_CPLD_ACRG,
DATA_STAT_CD,
CRE_DT,
CRE_USER_NM,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CTR_FARM_TR_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_FARM_TRACT.FARM_NUMBER FARM_NBR,
CONTRACT_FARM_TRACT.TRACT_NUMBER TR_NBR,
CONTRACT_FARM_TRACT.CONTRACT_FARM_TRACT_IDENTIFIER CTR_FARM_TR_ID,
CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_FARM_TRACT.CROPLAND_ACREAGE CPLD_ACRG,
CONTRACT_FARM_TRACT.MPL_ACREAGE MPL_ACRG,
CONTRACT_FARM_TRACT.WELLHEAD_ACREAGE WLHD_ACRG,
CONTRACT_FARM_TRACT.NON_CROPLAND_ACREAGE NON_CPLD_ACRG,
CONTRACT_FARM_TRACT.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_FARM_TRACT.CREATION_DATE CRE_DT,
CONTRACT_FARM_TRACT.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_FARM_TRACT.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_FARM_TRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_FARM_TRACT.op,
1 AS TBL_PRIORITY
from "fsa-{env}-ccms-cdc".CONTRACT_FARM_TRACT
Left join "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left join "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left join "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
WHERE CONTRACT_FARM_TRACT.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_FARM_TRACT.FARM_NUMBER FARM_NBR,
CONTRACT_FARM_TRACT.TRACT_NUMBER TR_NBR,
CONTRACT_FARM_TRACT.CONTRACT_FARM_TRACT_IDENTIFIER CTR_FARM_TR_ID,
CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_FARM_TRACT.CROPLAND_ACREAGE CPLD_ACRG,
CONTRACT_FARM_TRACT.MPL_ACREAGE MPL_ACRG,
CONTRACT_FARM_TRACT.WELLHEAD_ACREAGE WLHD_ACRG,
CONTRACT_FARM_TRACT.NON_CROPLAND_ACREAGE NON_CPLD_ACRG,
CONTRACT_FARM_TRACT.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_FARM_TRACT.CREATION_DATE CRE_DT,
CONTRACT_FARM_TRACT.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_FARM_TRACT.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_FARM_TRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_DETAIL.op,
2 AS TBL_PRIORITY
from  "fsa-{env}-ccms-cdc".CONTRACT_DETAIL
Join "fsa-{env}-ccms-cdc".CONTRACT_FARM_TRACT
On CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left join "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left join "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
WHERE CONTRACT_DETAIL.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_FARM_TRACT.FARM_NUMBER FARM_NBR,
CONTRACT_FARM_TRACT.TRACT_NUMBER TR_NBR,
CONTRACT_FARM_TRACT.CONTRACT_FARM_TRACT_IDENTIFIER CTR_FARM_TR_ID,
CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_FARM_TRACT.CROPLAND_ACREAGE CPLD_ACRG,
CONTRACT_FARM_TRACT.MPL_ACREAGE MPL_ACRG,
CONTRACT_FARM_TRACT.WELLHEAD_ACREAGE WLHD_ACRG,
CONTRACT_FARM_TRACT.NON_CROPLAND_ACREAGE NON_CPLD_ACRG,
CONTRACT_FARM_TRACT.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_FARM_TRACT.CREATION_DATE CRE_DT,
CONTRACT_FARM_TRACT.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_FARM_TRACT.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_FARM_TRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
MASTER_CONTRACT.op,
3 AS TBL_PRIORITY
from  "fsa-{env}-ccms-cdc".MASTER_CONTRACT
Left Join "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_FARM_TRACT
On CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left join "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
WHERE MASTER_CONTRACT.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_FARM_TRACT.FARM_NUMBER FARM_NBR,
CONTRACT_FARM_TRACT.TRACT_NUMBER TR_NBR,
CONTRACT_FARM_TRACT.CONTRACT_FARM_TRACT_IDENTIFIER CTR_FARM_TR_ID,
CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_FARM_TRACT.CROPLAND_ACREAGE CPLD_ACRG,
CONTRACT_FARM_TRACT.MPL_ACREAGE MPL_ACRG,
CONTRACT_FARM_TRACT.WELLHEAD_ACREAGE WLHD_ACRG,
CONTRACT_FARM_TRACT.NON_CROPLAND_ACREAGE NON_CPLD_ACRG,
CONTRACT_FARM_TRACT.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_FARM_TRACT.CREATION_DATE CRE_DT,
CONTRACT_FARM_TRACT.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_FARM_TRACT.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_FARM_TRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP.op,
4 AS TBL_PRIORITY
from  "fsa-{env}-ccms-cdc".SIGNUP
Left Join "fsa-{env}-ccms-cdc".MASTER_CONTRACT
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_FARM_TRACT
On CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left join "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
WHERE SIGNUP.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_FARM_TRACT.FARM_NUMBER FARM_NBR,
CONTRACT_FARM_TRACT.TRACT_NUMBER TR_NBR,
CONTRACT_FARM_TRACT.CONTRACT_FARM_TRACT_IDENTIFIER CTR_FARM_TR_ID,
CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_FARM_TRACT.CROPLAND_ACREAGE CPLD_ACRG,
CONTRACT_FARM_TRACT.MPL_ACREAGE MPL_ACRG,
CONTRACT_FARM_TRACT.WELLHEAD_ACREAGE WLHD_ACRG,
CONTRACT_FARM_TRACT.NON_CROPLAND_ACREAGE NON_CPLD_ACRG,
CONTRACT_FARM_TRACT.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_FARM_TRACT.CREATION_DATE CRE_DT,
CONTRACT_FARM_TRACT.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_FARM_TRACT.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_FARM_TRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP_TYPE.op,
5 AS TBL_PRIORITY
from  "fsa-{env}-ccms-cdc".SIGNUP_TYPE
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left Join "fsa-{env}-ccms-cdc".MASTER_CONTRACT
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_FARM_TRACT
On CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left join "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
WHERE SIGNUP_TYPE.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_FARM_TRACT.FARM_NUMBER FARM_NBR,
CONTRACT_FARM_TRACT.TRACT_NUMBER TR_NBR,
CONTRACT_FARM_TRACT.CONTRACT_FARM_TRACT_IDENTIFIER CTR_FARM_TR_ID,
CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_FARM_TRACT.CROPLAND_ACREAGE CPLD_ACRG,
CONTRACT_FARM_TRACT.MPL_ACREAGE MPL_ACRG,
CONTRACT_FARM_TRACT.WELLHEAD_ACREAGE WLHD_ACRG,
CONTRACT_FARM_TRACT.NON_CROPLAND_ACREAGE NON_CPLD_ACRG,
CONTRACT_FARM_TRACT.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_FARM_TRACT.CREATION_DATE CRE_DT,
CONTRACT_FARM_TRACT.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_FARM_TRACT.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_FARM_TRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP_SUB_CATEGORY.op,
6 AS TBL_PRIORITY
from  "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
Left join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left Join "fsa-{env}-ccms-cdc".MASTER_CONTRACT
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_FARM_TRACT
On CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
WHERE SIGNUP_SUB_CATEGORY.op <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND CONTRACT_FARM_TRACT.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
NULL ADM_ST_FSA_CD,
NULL ADM_CNTY_FSA_CD,
NULL SGNP_TYPE_NM,
NULL SGNP_SUB_CAT_NM,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL CTR_NBR,
NULL CTR_SFX_NBR,
CONTRACT_FARM_TRACT.FARM_NUMBER FARM_NBR,
CONTRACT_FARM_TRACT.TRACT_NUMBER TR_NBR,
CONTRACT_FARM_TRACT.CONTRACT_FARM_TRACT_IDENTIFIER CTR_FARM_TR_ID,
CONTRACT_FARM_TRACT.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_FARM_TRACT.CROPLAND_ACREAGE CPLD_ACRG,
CONTRACT_FARM_TRACT.MPL_ACREAGE MPL_ACRG,
CONTRACT_FARM_TRACT.WELLHEAD_ACREAGE WLHD_ACRG,
CONTRACT_FARM_TRACT.NON_CROPLAND_ACREAGE NON_CPLD_ACRG,
CONTRACT_FARM_TRACT.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_FARM_TRACT.CREATION_DATE CRE_DT,
CONTRACT_FARM_TRACT.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_FARM_TRACT.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_FARM_TRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-ccms-cdc".CONTRACT_FARM_TRACT
WHERE CONTRACT_FARM_TRACT.op = 'D'