INSERT into
EDV.DCP_ADJ_TYPE_RH(DCP_ADJ_TYPE_CD,
LOAD_DT,
DATA_SRC_NM)
(
SELECT 
stg.DCP_ADJ_TYPE_CD,
stg.LOAD_DT,
stg.DATA_SRC_NM
from (
SELECT DISTINCT
coalesce(DMN_VAL.DMN_CHAR_VAL, '[NULL IN SOURCE]') DCP_ADJ_TYPE_CD,
DMN_VAL.LOAD_DT LOAD_DT,
DMN_VAL.DATA_SRC_NM DATA_SRC_NM,
ROW_NUMBER() OVER (PARTITION BY DMN_VAL.DMN_CHAR_VAL ORDER BY DMN_VAL.CDC_DT desc, DMN_VAL.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.DMN_VAL
WHERE DMN_VAL.DMN_ID = 7
and DMN_VAL.cdc_oper_cd IN ('I','UN','D')
) stg 
LEFT JOIN  EDV.DCP_ADJ_TYPE_RH dv
 ON (
stg.DCP_ADJ_TYPE_CD = dv.DCP_ADJ_TYPE_CD
)
where (
dv.DCP_ADJ_TYPE_CD IS NULL
)
and stg.STG_EFF_DT_RANK = 1
);