SELECT distinct t.tract_producer_year_identifier As TR_PRDR_YR_ID,
t.core_customer_identifier As CORE_CUST_ID,
t.tract_year_identifier As TR_YR_ID,
t.producer_involvement_code As PRDR_INVL_CD,
t.producer_involvement_start_date As PRDR_INVL_STRT_DT,
t.producer_involvement_end_date As PRDR_INVL_END_DT,
LTrim(RTrim(t.producer_involvement_interrupted_indicator)) As PRDR_INVL_INTRPT_IND,
t.tract_producer_hel_exception_code As TR_PRDR_HEL_EXCP_CD,
t.tract_producer_cw_exception_code As TR_PRDR_CW_EXCP_CD,
t.tract_producer_pcw_exception_code As TR_PRDR_PCW_EXCP_CD,
LTrim(RTrim(t.data_status_code) ) As DATA_STAT_CD,
t.creation_date As CRE_DT,
t.last_change_date As LAST_CHG_DT,
LTrim(RTrim(t.last_change_user_name) ) As LAST_CHG_USER_NM,
t.time_period_identifier As TM_PRD_ID,
LTrim(RTrim(t.state_fsa_code) ) As ST_FSA_CD,
LTrim(RTrim(t.county_fsa_code) ) As CNTY_FSA_CD,
t.farm_identifier As FARM_ID,
LTrim(RTrim(t.farm_number) ) As FARM_NBR,
LTrim(RTrim(t.tract_number) ) As TR_NBR,
CAST(tp.time_period_name AS numeric(4)) as PGM_YR,
''  as HASH_DIF,
t.cdc_oper_cd AS CDC_OPER_CD,
CAST(current_date as date) as LOAD_DT,
'SAP/CRM' as DATA_SCR_NM,
t.cdc_dt as CDC_DT,
t.hel_appeals_exhausted_date As HEL_APLS_EXHST_DT, 
t.cw_appeals_exhausted_date As CW_APLS_EXHST_DT, 
t.pcw_appeals_exhausted_date As PCW_APLS_EXHST_DT,
t.tract_producer_rma_hel_exception_code As TR_PRDR_RMA_HEL_EXCP_CD,
t.tract_producer_rma_cw_exception_code As TR_PRDR_RMA_CW_EXCP_CD, 
t.tract_producer_rma_pcw_exception_code As TR_PRDR_RMA_PCW_EXCP_CD
from farm_records_reporting.tract_producer_year t 
left join farm_records_reporting.time_period tp on t.time_period_identifier = tp.time_period_identifier
where t.cdc_dt between date '{ETL_START_DATE}' and date '{ETL_END_DATE}'