-- Julia Lu edition - will update this paragraph and query when (cnsv/ccms)-cdc is ready
-- Stage SQL: CCMS_CTR_STAT (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CCMS_CTR_STAT/incremental/CCMS_CTR_STAT.sql
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_NM,
SGNP_SUB_CAT_NM,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
CTR_NBR,
CTR_SFX_NBR,
CTR_STAT_TYPE_CD,
CTR_STAT_ID,
CTR_STAT_EFF_DT,
CTR_DET_ID,
CTR_STAT_EXPR_DT,
TERM_PROC_CD,
DATA_STAT_CD,
CRE_DT,
CRE_USER_NM,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CTR_STAT_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_STATUS.CONTRACT_STATUS_TYPE_CODE CTR_STAT_TYPE_CD,
CONTRACT_STATUS.CONTRACT_STATUS_IDENTIFIER CTR_STAT_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EFFECTIVE_DATE CTR_STAT_EFF_DT,
CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EXPIRATION_DATE CTR_STAT_EXPR_DT,
CONTRACT_STATUS.TERMINATION_PROCESSING_CODE TERM_PROC_CD,
CONTRACT_STATUS.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_STATUS.CREATION_DATE CRE_DT,
CONTRACT_STATUS.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_STATUS.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_STATUS.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_STATUS.op,
1 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".CONTRACT_STATUS
Left Join "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
On CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join  "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
WHERE CONTRACT_STATUS.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_STATUS.CONTRACT_STATUS_TYPE_CODE CTR_STAT_TYPE_CD,
CONTRACT_STATUS.CONTRACT_STATUS_IDENTIFIER CTR_STAT_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EFFECTIVE_DATE CTR_STAT_EFF_DT,
CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EXPIRATION_DATE CTR_STAT_EXPR_DT,
CONTRACT_STATUS.TERMINATION_PROCESSING_CODE TERM_PROC_CD,
CONTRACT_STATUS.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_STATUS.CREATION_DATE CRE_DT,
CONTRACT_STATUS.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_STATUS.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_STATUS.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CONTRACT_DETAIL.op,
2 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".CONTRACT_DETAIL
Join "fsa-{env}-ccms-cdc".CONTRACT_STATUS 
On CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".MASTER_CONTRACT 
On CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join  "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
WHERE CONTRACT_DETAIL.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_STATUS.CONTRACT_STATUS_TYPE_CODE CTR_STAT_TYPE_CD,
CONTRACT_STATUS.CONTRACT_STATUS_IDENTIFIER CTR_STAT_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EFFECTIVE_DATE CTR_STAT_EFF_DT,
CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EXPIRATION_DATE CTR_STAT_EXPR_DT,
CONTRACT_STATUS.TERMINATION_PROCESSING_CODE TERM_PROC_CD,
CONTRACT_STATUS.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_STATUS.CREATION_DATE CRE_DT,
CONTRACT_STATUS.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_STATUS.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_STATUS.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
MASTER_CONTRACT.op,
3 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".MASTER_CONTRACT
Left Join "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_STATUS 
On CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join  "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
WHERE MASTER_CONTRACT.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_STATUS.CONTRACT_STATUS_TYPE_CODE CTR_STAT_TYPE_CD,
CONTRACT_STATUS.CONTRACT_STATUS_IDENTIFIER CTR_STAT_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EFFECTIVE_DATE CTR_STAT_EFF_DT,
CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EXPIRATION_DATE CTR_STAT_EXPR_DT,
CONTRACT_STATUS.TERMINATION_PROCESSING_CODE TERM_PROC_CD,
CONTRACT_STATUS.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_STATUS.CREATION_DATE CRE_DT,
CONTRACT_STATUS.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_STATUS.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_STATUS.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP.op,
4 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".SIGNUP
Left Join "fsa-{env}-ccms-cdc".MASTER_CONTRACT
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_STATUS 
On CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left Join  "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
WHERE SIGNUP.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_STATUS.CONTRACT_STATUS_TYPE_CODE CTR_STAT_TYPE_CD,
CONTRACT_STATUS.CONTRACT_STATUS_IDENTIFIER CTR_STAT_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EFFECTIVE_DATE CTR_STAT_EFF_DT,
CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EXPIRATION_DATE CTR_STAT_EXPR_DT,
CONTRACT_STATUS.TERMINATION_PROCESSING_CODE TERM_PROC_CD,
CONTRACT_STATUS.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_STATUS.CREATION_DATE CRE_DT,
CONTRACT_STATUS.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_STATUS.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_STATUS.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP_TYPE.op,
5 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".SIGNUP_TYPE
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left Join "fsa-{env}-ccms-cdc".MASTER_CONTRACT
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_STATUS 
On CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
Left Join  "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
WHERE SIGNUP_TYPE.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
SIGNUP_TYPE.SIGNUP_TYPE_NAME SGNP_TYPE_NM,
SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME SGNP_SUB_CAT_NM,
SIGNUP.signup_number SGNP_NBR,
SIGNUP.SIGNUP_SUBTYPE_AGREEMENT_NAME SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER CTR_SFX_NBR,
CONTRACT_STATUS.CONTRACT_STATUS_TYPE_CODE CTR_STAT_TYPE_CD,
CONTRACT_STATUS.CONTRACT_STATUS_IDENTIFIER CTR_STAT_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EFFECTIVE_DATE CTR_STAT_EFF_DT,
CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EXPIRATION_DATE CTR_STAT_EXPR_DT,
CONTRACT_STATUS.TERMINATION_PROCESSING_CODE TERM_PROC_CD,
CONTRACT_STATUS.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_STATUS.CREATION_DATE CRE_DT,
CONTRACT_STATUS.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_STATUS.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_STATUS.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
SIGNUP_SUB_CATEGORY.op,
6 AS TBL_PRIORITY
FROM  "fsa-{env}-ccms-cdc".SIGNUP_SUB_CATEGORY
Left Join "fsa-{env}-ccms-cdc".SIGNUP
On SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE = SIGNUP.SIGNUP_SUB_CATEGORY_CODE
Left Join "fsa-{env}-ccms-cdc".SIGNUP_TYPE
On SIGNUP_TYPE.SIGNUP_TYPE_CODE = SIGNUP.SIGNUP_TYPE_CODE
Left Join "fsa-{env}-ccms-cdc".MASTER_CONTRACT
On SIGNUP.SIGNUP_IDENTIFIER = MASTER_CONTRACT.SIGNUP_IDENTIFIER
Left Join "fsa-{env}-ccms-cdc".CONTRACT_DETAIL 
On CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER
Join "fsa-{env}-ccms-cdc".CONTRACT_STATUS 
On CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_DETAIL_IDENTIFIER
WHERE SIGNUP_SUB_CATEGORY.op <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND CONTRACT_STATUS.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
NULL ADM_ST_FSA_CD,
NULL ADM_CNTY_FSA_CD,
NULL SGNP_TYPE_NM,
NULL SGNP_SUB_CAT_NM,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL CTR_NBR,
NULL CTR_SFX_NBR,
CONTRACT_STATUS.CONTRACT_STATUS_TYPE_CODE CTR_STAT_TYPE_CD,
CONTRACT_STATUS.CONTRACT_STATUS_IDENTIFIER CTR_STAT_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EFFECTIVE_DATE CTR_STAT_EFF_DT,
CONTRACT_STATUS.CONTRACT_DETAIL_IDENTIFIER CTR_DET_ID,
CONTRACT_STATUS.CONTRACT_STATUS_EXPIRATION_DATE CTR_STAT_EXPR_DT,
CONTRACT_STATUS.TERMINATION_PROCESSING_CODE TERM_PROC_CD,
CONTRACT_STATUS.DATA_STATUS_CODE DATA_STAT_CD,
CONTRACT_STATUS.CREATION_DATE CRE_DT,
CONTRACT_STATUS.CREATION_USER_NAME CRE_USER_NM,
CONTRACT_STATUS.LAST_CHANGE_DATE LAST_CHG_DT,
CONTRACT_STATUS.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-ccms-cdc".CONTRACT_STATUS
WHERE CONTRACT_STATUS.op = 'D'