SELECT PRAC_CPNT_CAT_ID,
CNSV_PRAC_ID,
CPNT_CAT_ID,
CNSV_PRAC_CD,
CPNT_CAT_NM,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT PRAC_CPNT_CAT_ID,
CNSV_PRAC_ID,
CPNT_CAT_ID,
CNSV_PRAC_CD,
CPNT_CAT_NM,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
PRAC_CPNT_CAT_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
PRACTICE_COMPONENT_CATEGORY.PRAC_CPNT_CAT_ID PRAC_CPNT_CAT_ID,
PRACTICE_COMPONENT_CATEGORY.CNSV_PRAC_ID CNSV_PRAC_ID,
PRACTICE_COMPONENT_CATEGORY.CPNT_CAT_ID CPNT_CAT_ID,
CONSERVATION_PRACTICE.CNSV_PRAC_CD CNSV_PRAC_CD,
COMPONENT_CATEGORY.CPNT_CAT_NM CPNT_CAT_NM,
PRACTICE_COMPONENT_CATEGORY.DATA_STAT_CD DATA_STAT_CD,
PRACTICE_COMPONENT_CATEGORY.CRE_DT CRE_DT,
PRACTICE_COMPONENT_CATEGORY.LAST_CHG_DT LAST_CHG_DT,
PRACTICE_COMPONENT_CATEGORY.LAST_CHG_USER_NM LAST_CHG_USER_NM,
PRACTICE_COMPONENT_CATEGORY.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PRACTICE_COMPONENT_CATEGORY" PRACTICE_COMPONENT_CATEGORY
LEFT JOIN "fsa-{env}-cnsv".CONSERVATION_PRACTICE
ON (PRACTICE_COMPONENT_CATEGORY.CNSV_PRAC_ID = CONSERVATION_PRACTICE.CNSV_PRAC_ID)
LEFT JOIN "fsa-{env}-cnsv".COMPONENT_CATEGORY
ON (PRACTICE_COMPONENT_CATEGORY.CPNT_CAT_ID = COMPONENT_CATEGORY.CPNT_CAT_ID)  
WHERE PRACTICE_COMPONENT_CATEGORY.OP <> 'D' AND
PRACTICE_COMPONENT_CATEGORY.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
PRACTICE_COMPONENT_CATEGORY.PRAC_CPNT_CAT_ID PRAC_CPNT_CAT_ID,
PRACTICE_COMPONENT_CATEGORY.CNSV_PRAC_ID CNSV_PRAC_ID,
PRACTICE_COMPONENT_CATEGORY.CPNT_CAT_ID CPNT_CAT_ID,
CONSERVATION_PRACTICE.CNSV_PRAC_CD CNSV_PRAC_CD,
COMPONENT_CATEGORY.CPNT_CAT_NM CPNT_CAT_NM,
PRACTICE_COMPONENT_CATEGORY.DATA_STAT_CD DATA_STAT_CD,
PRACTICE_COMPONENT_CATEGORY.CRE_DT CRE_DT,
PRACTICE_COMPONENT_CATEGORY.LAST_CHG_DT LAST_CHG_DT,
PRACTICE_COMPONENT_CATEGORY.LAST_CHG_USER_NM LAST_CHG_USER_NM,
CONSERVATION_PRACTICE.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."CONSERVATION_PRACTICE" CONSERVATION_PRACTICE
JOIN "fsa-{env}-cnsv".PRACTICE_COMPONENT_CATEGORY
ON (PRACTICE_COMPONENT_CATEGORY.CNSV_PRAC_ID = CONSERVATION_PRACTICE.CNSV_PRAC_ID)
LEFT JOIN "fsa-{env}-cnsv".COMPONENT_CATEGORY
ON (PRACTICE_COMPONENT_CATEGORY.CPNT_CAT_ID = COMPONENT_CATEGORY.CPNT_CAT_ID)  
WHERE CONSERVATION_PRACTICE.OP <> 'D' AND
CONSERVATION_PRACTICE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
PRACTICE_COMPONENT_CATEGORY.PRAC_CPNT_CAT_ID PRAC_CPNT_CAT_ID,
PRACTICE_COMPONENT_CATEGORY.CNSV_PRAC_ID CNSV_PRAC_ID,
PRACTICE_COMPONENT_CATEGORY.CPNT_CAT_ID CPNT_CAT_ID,
CONSERVATION_PRACTICE.CNSV_PRAC_CD CNSV_PRAC_CD,
COMPONENT_CATEGORY.CPNT_CAT_NM CPNT_CAT_NM,
PRACTICE_COMPONENT_CATEGORY.DATA_STAT_CD DATA_STAT_CD,
PRACTICE_COMPONENT_CATEGORY.CRE_DT CRE_DT,
PRACTICE_COMPONENT_CATEGORY.LAST_CHG_DT LAST_CHG_DT,
PRACTICE_COMPONENT_CATEGORY.LAST_CHG_USER_NM LAST_CHG_USER_NM,
COMPONENT_CATEGORY.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."COMPONENT_CATEGORY" COMPONENT_CATEGORY
JOIN "fsa-{env}-cnsv".PRACTICE_COMPONENT_CATEGORY
ON (PRACTICE_COMPONENT_CATEGORY.CPNT_CAT_ID = COMPONENT_CATEGORY.CPNT_CAT_ID)
LEFT JOIN "fsa-{env}-cnsv".CONSERVATION_PRACTICE
ON (PRACTICE_COMPONENT_CATEGORY.CNSV_PRAC_ID = CONSERVATION_PRACTICE.CNSV_PRAC_ID)  
WHERE COMPONENT_CATEGORY.OP <> 'D' AND
COMPONENT_CATEGORY.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
PRACTICE_COMPONENT_CATEGORY.PRAC_CPNT_CAT_ID PRAC_CPNT_CAT_ID,
PRACTICE_COMPONENT_CATEGORY.CNSV_PRAC_ID CNSV_PRAC_ID,
PRACTICE_COMPONENT_CATEGORY.CPNT_CAT_ID CPNT_CAT_ID,
NULL CNSV_PRAC_CD,
NULL CPNT_CAT_NM,
PRACTICE_COMPONENT_CATEGORY.DATA_STAT_CD DATA_STAT_CD,
PRACTICE_COMPONENT_CATEGORY.CRE_DT CRE_DT,
PRACTICE_COMPONENT_CATEGORY.LAST_CHG_DT LAST_CHG_DT,
PRACTICE_COMPONENT_CATEGORY.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".PRACTICE_COMPONENT_CATEGORY PRACTICE_COMPONENT_CATEGORY
WHERE OP = 'D'
AND dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}' 
)