INSERT INTO EDV.CMB_PRDR_ACCT_H (CMB_PRDR_ACCT_H_ID, CMB_PRDR_ACCT_ID, DATA_SRC_NM, LOAD_DT)
  (SELECT stg.CMB_PRDR_ACCT_H_ID,
          stg.CMB_PRDR_ACCT_ID,
          stg.DATA_SRC_NM,
          stg.LOAD_DT
   FROM
     (SELECT DISTINCT MD5(CMB_PRDR_ACCT_ID::varchar) CMB_PRDR_ACCT_H_ID,
                      CMB_PRDR_ACCT.CMB_PRDR_ACCT_ID CMB_PRDR_ACCT_ID,
                      CMB_PRDR_ACCT.DATA_SRC_NM DATA_SRC_NM,
                      CMB_PRDR_ACCT.LOAD_DT LOAD_DT,
                      ROW_NUMBER () OVER (PARTITION BY CMB_PRDR_ACCT.CMB_PRDR_ACCT_ID
                                          ORDER BY CMB_PRDR_ACCT.CDC_DT DESC, CMB_PRDR_ACCT.LOAD_DT DESC) STG_EFF_DT_RANK
      FROM SBSD_STG.CMB_PRDR_ACCT) stg
   LEFT OUTER JOIN EDV.CMB_PRDR_ACCT_H dv ON (stg.CMB_PRDR_ACCT_H_ID = dv.CMB_PRDR_ACCT_H_ID)
   WHERE (dv.CMB_PRDR_ACCT_H_ID IS NULL)
     AND stg.STG_EFF_DT_RANK = 1 )