INSERT into 
EDV.FSA_CNTY_RH(ST_FSA_CD,
CNTY_FSA_CD,
DATA_SRC_NM,
LOAD_DT)
(
SELECT 
stg.ST_FSA_CD,
stg.CNTY_FSA_CD,
stg.DATA_SRC_NM,
stg.LOAD_DT
from (
SELECT DISTINCT
coalesce(CNTY_OFC_CTL.ST_FSA_CD, '--') ST_FSA_CD,
coalesce(CNTY_OFC_CTL.CNTY_FSA_CD, '--') CNTY_FSA_CD,
CNTY_OFC_CTL.DATA_SRC_NM DATA_SRC_NM,
CNTY_OFC_CTL.LOAD_DT LOAD_DT,
ROW_NUMBER() OVER (PARTITION BY CNTY_OFC_CTL.ST_FSA_CD,CNTY_OFC_CTL.CNTY_FSA_CD ORDER BY CNTY_OFC_CTL.CDC_DT desc, CNTY_OFC_CTL.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.CNTY_OFC_CTL
) stg 
LEFT JOIN  EDV.FSA_CNTY_RH dv
 ON (
stg.ST_FSA_CD = dv.ST_FSA_CD
and stg.CNTY_FSA_CD = dv.CNTY_FSA_CD
)
where (
dv.ST_FSA_CD IS NULL
OR dv.CNTY_FSA_CD IS NULL
)
and stg.STG_EFF_DT_RANK = 1
);