-- Julia Lu edition - will update this paragraph and query when (cnsv/ccms)-cdc is ready
-- Stage SQL: CNSV_CNSV_PRAC_BUS_RULE_GRP (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_CNSV_PRAC_BUS_RULE_GRP/incremental/CNSV_CNSV_PRAC_BUS_RULE_GRP.sql
-- =============================================================================
SELECT * FROM
(
SELECT DISTINCT CNSV_PRAC_CD,
BUS_RULE_CD,
BUS_RULE_GRP_NM,
CNSV_PRAC_BUS_RULE_GRP_ID,
LAST_CHG_DT,
CRE_DT,
LAST_CHG_USER_NM,
CRE_USER_NM,
DATA_STAT_CD,
BUS_RULE_GRP_ID,
BUS_RULE_ID,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CNSV_PRAC_BUS_RULE_GRP_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_CD CNSV_PRAC_CD,
BUSINESS_RULE.BUS_RULE_CD BUS_RULE_CD,
BUSINESS_RULE_GROUP.BUS_RULE_GRP_NM BUS_RULE_GRP_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_BUS_RULE_GRP_ID CNSV_PRAC_BUS_RULE_GRP_ID,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.LAST_CHG_DT LAST_CHG_DT,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CRE_DT CRE_DT,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CRE_USER_NM LAST_CHG_USER_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.LAST_CHG_USER_NM CRE_USER_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.DATA_STAT_CD DATA_STAT_CD,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID BUS_RULE_GRP_ID,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_ID BUS_RULE_ID,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.op,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP
LEFT JOIN "fsa-{env}-cnsv-cdc".EWT12PRACT EWT12PRACT
ON (CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_CD = EWT12PRACT.CNSV_PRAC_CD)
LEFT JOIN "fsa-{env}-cnsv-cdc".BUSINESS_RULE_GROUP BUSINESS_RULE_GROUP
ON (CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID = BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID)
LEFT JOIN "fsa-{env}-cnsv-cdc".BUSINESS_RULE BUSINESS_RULE 
ON (CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_ID = BUSINESS_RULE.BUS_RULE_ID)
WHERE CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.op <> 'D'

UNION
SELECT 
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_CD CNSV_PRAC_CD,
BUSINESS_RULE.BUS_RULE_CD BUS_RULE_CD,
BUSINESS_RULE_GROUP.BUS_RULE_GRP_NM BUS_RULE_GRP_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_BUS_RULE_GRP_ID CNSV_PRAC_BUS_RULE_GRP_ID,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.LAST_CHG_DT LAST_CHG_DT,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CRE_DT CRE_DT,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CRE_USER_NM LAST_CHG_USER_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.LAST_CHG_USER_NM CRE_USER_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.DATA_STAT_CD DATA_STAT_CD,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID BUS_RULE_GRP_ID,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_ID BUS_RULE_ID,
EWT12PRACT.op,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".EWT12PRACT
JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP
ON (EWT12PRACT.CNSV_PRAC_CD = CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_CD)
LEFT JOIN "fsa-{env}-cnsv-cdc".BUSINESS_RULE_GROUP BUSINESS_RULE_GROUP
ON (CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID = BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID)
LEFT JOIN "fsa-{env}-cnsv-cdc".BUSINESS_RULE BUSINESS_RULE 
ON (CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_ID = BUSINESS_RULE.BUS_RULE_ID)
WHERE EWT12PRACT.op <> 'D'

UNION
SELECT 
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_CD CNSV_PRAC_CD,
BUSINESS_RULE.BUS_RULE_CD BUS_RULE_CD,
BUSINESS_RULE_GROUP.BUS_RULE_GRP_NM BUS_RULE_GRP_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_BUS_RULE_GRP_ID CNSV_PRAC_BUS_RULE_GRP_ID,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.LAST_CHG_DT LAST_CHG_DT,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CRE_DT CRE_DT,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CRE_USER_NM LAST_CHG_USER_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.LAST_CHG_USER_NM CRE_USER_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.DATA_STAT_CD DATA_STAT_CD,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID BUS_RULE_GRP_ID,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_ID BUS_RULE_ID,
BUSINESS_RULE_GROUP.op,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".BUSINESS_RULE_GROUP
JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP
ON (BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID = CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID)
LEFT JOIN "fsa-{env}-cnsv-cdc".EWT12PRACT EWT12PRACT
ON (CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_CD = EWT12PRACT.CNSV_PRAC_CD)
LEFT JOIN "fsa-{env}-cnsv-cdc".BUSINESS_RULE BUSINESS_RULE 
ON (CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_ID = BUSINESS_RULE.BUS_RULE_ID)
WHERE BUSINESS_RULE_GROUP.op <> 'D'

UNION
SELECT 
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_CD CNSV_PRAC_CD,
BUSINESS_RULE.BUS_RULE_CD BUS_RULE_CD,
BUSINESS_RULE_GROUP.BUS_RULE_GRP_NM BUS_RULE_GRP_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_BUS_RULE_GRP_ID CNSV_PRAC_BUS_RULE_GRP_ID,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.LAST_CHG_DT LAST_CHG_DT,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CRE_DT CRE_DT,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CRE_USER_NM LAST_CHG_USER_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.LAST_CHG_USER_NM CRE_USER_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.DATA_STAT_CD DATA_STAT_CD,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID BUS_RULE_GRP_ID,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_ID BUS_RULE_ID,
BUSINESS_RULE.op,
4 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".BUSINESS_RULE
JOIN "fsa-{env}-cnsv-cdc".CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP
ON (BUSINESS_RULE.BUS_RULE_ID = CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_ID)
LEFT JOIN "fsa-{env}-cnsv-cdc".BUSINESS_RULE_GROUP BUSINESS_RULE_GROUP
ON (CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID = BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID)
LEFT JOIN "fsa-{env}-cnsv-cdc".EWT12PRACT EWT12PRACT
ON (CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_CD = EWT12PRACT.CNSV_PRAC_CD)
WHERE BUSINESS_RULE.op <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_CD CNSV_PRAC_CD,
NULL BUS_RULE_CD,
NULL BUS_RULE_GRP_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CNSV_PRAC_BUS_RULE_GRP_ID CNSV_PRAC_BUS_RULE_GRP_ID,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.LAST_CHG_DT LAST_CHG_DT,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CRE_DT CRE_DT,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.CRE_USER_NM LAST_CHG_USER_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.LAST_CHG_USER_NM CRE_USER_NM,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.DATA_STAT_CD DATA_STAT_CD,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_GRP_ID BUS_RULE_GRP_ID,
CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.BUS_RULE_ID BUS_RULE_ID,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP
WHERE CONSERVATION_PRACTICE_BUSINESS_RULE_GROUP.op = 'D'