SELECT SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
GRSLD_RANK_FCTR_IDN,
GRSLD_RANK_SFCTR_IDN,
GRSLD_RANK_SFCTR_TYPE_CD,
GRSLD_RANK_SFCTR_DTER_MTHD_CD,
AWRD_EACH_QLFY_RESP_IND,
QSTN_CT,
RANK_PNT_CT,
GRSLD_RANK_FCTR_ID,
GRSLD_RANK_SFCTR_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
CRE_USER_NM,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
GRSLD_RANK_FCTR_IDN,
GRSLD_RANK_SFCTR_IDN,
GRSLD_RANK_SFCTR_TYPE_CD,
GRSLD_RANK_SFCTR_DTER_MTHD_CD,
AWRD_EACH_QLFY_RESP_IND,
QSTN_CT,
RANK_PNT_CT,
GRSLD_RANK_FCTR_ID,
GRSLD_RANK_SFCTR_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
CRE_USER_NM,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
GRSLD_RANK_SFCTR_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_TYPE_CD GRSLD_RANK_SFCTR_TYPE_CD,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_DTER_MTHD_CD GRSLD_RANK_SFCTR_DTER_MTHD_CD,
GRASSLAND_RANKING_SUBFACTOR.AWRD_EACH_QLFY_RESP_IND AWRD_EACH_QLFY_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR.QSTN_CT QSTN_CT,
GRASSLAND_RANKING_SUBFACTOR.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID GRSLD_RANK_FCTR_ID,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_SUBFACTOR.OP,
1 AS TBL_PRIORITY
From   "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_SUBFACTOR" GRASSLAND_RANKING_SUBFACTOR
Left JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR
On (GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID)
Left Join   "fsa-{env}-cnsv".EWT14SGNP
On (GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE GRASSLAND_RANKING_SUBFACTOR.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR.OP <> 'D'

UNION
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_TYPE_CD GRSLD_RANK_SFCTR_TYPE_CD,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_DTER_MTHD_CD GRSLD_RANK_SFCTR_DTER_MTHD_CD,
GRASSLAND_RANKING_SUBFACTOR.AWRD_EACH_QLFY_RESP_IND AWRD_EACH_QLFY_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR.QSTN_CT QSTN_CT,
GRASSLAND_RANKING_SUBFACTOR.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID GRSLD_RANK_FCTR_ID,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_FACTOR.OP,
2 AS TBL_PRIORITY
From    "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_FACTOR" GRASSLAND_RANKING_FACTOR
JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR 
ON (GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID)
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP
ON (GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE GRASSLAND_RANKING_FACTOR.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_FACTOR.OP <> 'D'

UNION
SELECT 
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_TYPE_CD GRSLD_RANK_SFCTR_TYPE_CD,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_DTER_MTHD_CD GRSLD_RANK_SFCTR_DTER_MTHD_CD,
GRASSLAND_RANKING_SUBFACTOR.AWRD_EACH_QLFY_RESP_IND AWRD_EACH_QLFY_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR.QSTN_CT QSTN_CT,
GRASSLAND_RANKING_SUBFACTOR.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID GRSLD_RANK_FCTR_ID,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT14SGNP.OP,
3 AS TBL_PRIORITY
From    "fsa-{env}-cnsv-cdc"."EWT14SGNP" EWT14SGNP
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR
On (EWT14SGNP.SGNP_ID = GRASSLAND_RANKING_FACTOR.SGNP_ID)
JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR
On (GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID)
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT14SGNP.OP <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_TYPE_CD GRSLD_RANK_SFCTR_TYPE_CD,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_DTER_MTHD_CD GRSLD_RANK_SFCTR_DTER_MTHD_CD,
GRASSLAND_RANKING_SUBFACTOR.AWRD_EACH_QLFY_RESP_IND AWRD_EACH_QLFY_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR.QSTN_CT QSTN_CT,
GRASSLAND_RANKING_SUBFACTOR.RANK_PNT_CT RANK_PNT_CT,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID GRSLD_RANK_FCTR_ID,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID GRSLD_RANK_SFCTR_ID,
GRASSLAND_RANKING_SUBFACTOR.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".GRASSLAND_RANKING_SUBFACTOR GRASSLAND_RANKING_SUBFACTOR
WHERE dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR.OP = 'D'
)