Merge into
EDV.CROP_FARM_YR_ADJ_DCP_LS dv
using(select DISTINCT MD5(MD5(upper(coalesce(CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.FARM_NBR,'--')))||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_TYPE_CD),'--')) ) CROP_FARM_L_ID,
coalesce(CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_ID, '-1') CROP_FARM_YR_MNG_VAL_ADJ_ID,CROP_FARM_YR_MNG_VAL_ADJ.LOAD_DT LOAD_DT,CROP_FARM_YR_MNG_VAL_ADJ.CDC_DT DATA_EFF_STRT_DT,CROP_FARM_YR_MNG_VAL_ADJ.DATA_SRC_NM DATA_SRC_NM,CROP_FARM_YR_MNG_VAL_ADJ.DATA_STAT_CD DATA_STAT_CD,CROP_FARM_YR_MNG_VAL_ADJ.CRE_DT SRC_CRE_DT,CROP_FARM_YR_MNG_VAL_ADJ.CRE_USER_NM SRC_CRE_USER_NM,CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_DT SRC_LAST_CHG_DT,CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_DCP_ID CROP_FARM_YR_DCP_ID,CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY SRC_CROP_FARM_YR_ADJ_TYPE_CD,FARM_CROP_ADJ_TYPE_RS.DMN_VAL_NM CROP_FARM_YR_ADJ_TYPE_NAME,CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_RS SRC_CROP_FARM_YR_ADJ_RSN_CD,CROP_FARM_YR_MNG_VAL_ADJ.AFT_ADJ_VAL AFT_ADJ_VAL,CROP_FARM_YR_MNG_VAL_ADJ.BEF_ADJ_VAL BEF_ADJ_VAL,CROP_FARM_YR_MNG_VAL_ADJ.PGM_YR PGM_YR ,
CROP_FARM_YR_MNG_VAL_ADJ.CDC_OPER_CD,
MD5(upper(coalesce(CROP_FARM_YR_MNG_VAL_ADJ.ST_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(CROP_FARM_YR_MNG_VAL_ADJ.FARM_NBR,'--'))||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.PGM_ABR)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_CD)||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.FSA_CROP_TYPE_CD)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_ID||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.DATA_STAT_CD)||'~~'||to_char(CROP_FARM_YR_MNG_VAL_ADJ.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.CRE_USER_NM)||'~~'||to_char(CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP_FARM_YR_MNG_VAL_ADJ.LAST_CHG_USER_NM)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_DCP_ID||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY||'~~'||trim(both FARM_CROP_ADJ_TYPE_RS.DMN_VAL_NM)||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_RS||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.AFT_ADJ_VAL||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.BEF_ADJ_VAL||'~~'||CROP_FARM_YR_MNG_VAL_ADJ.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.CROP_FARM_YR_MNG_VAL_ADJ 
LEFT JOIN(select * from EDV.FARM_CROP_ADJ_TYPE_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FARM_CROP_ADJ_TYPE_RS 
ON (CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_MNG_VAL_ADJ_TY = FARM_CROP_ADJ_TYPE_RS.DMN_VAL_ID)
WHERE CROP_FARM_YR_MNG_VAL_ADJ.CROP_FARM_YR_DCP_ID IS NOT NULL and CROP_FARM_YR_MNG_VAL_ADJ.CDC_OPER_CD='D'
order by CROP_FARM_YR_MNG_VAL_ADJ.CDC_DT)
stg
 on ( 
coalesce(stg.CROP_FARM_YR_MNG_VAL_ADJ_ID,0) = coalesce(dv.CROP_FARM_YR_MNG_VAL_ADJ_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN
INSERT(
CROP_FARM_L_ID,CROP_FARM_YR_MNG_VAL_ADJ_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_CRE_USER_NM,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
CROP_FARM_YR_DCP_ID,
SRC_CROP_FARM_YR_ADJ_TYPE_CD,
CROP_FARM_YR_ADJ_TYPE_NAME,
SRC_CROP_FARM_YR_ADJ_RSN_CD,
AFT_ADJ_VAL,
BEF_ADJ_VAL,
PGM_YR, 
DATA_EFF_END_DT,LOAD_END_DT,HASH_DIF)
   VALUES (
stg.CROP_FARM_L_ID,stg.CROP_FARM_YR_MNG_VAL_ADJ_ID,stg.LOAD_DT,stg.DATA_EFF_STRT_DT,stg.DATA_SRC_NM,stg.DATA_STAT_CD,stg.SRC_CRE_DT,stg.SRC_CRE_USER_NM,stg.SRC_LAST_CHG_DT,
stg.SRC_LAST_CHG_USER_NM,stg.CROP_FARM_YR_DCP_ID,
stg.SRC_CROP_FARM_YR_ADJ_TYPE_CD,stg.CROP_FARM_YR_ADJ_TYPE_NAME,stg.SRC_CROP_FARM_YR_ADJ_RSN_CD,stg.AFT_ADJ_VAL,stg.BEF_ADJ_VAL,stg.PGM_YR,stg.DATA_EFF_STRT_DT,stg.LOAD_DT,
stg.HASH_DIF
)
;