SELECT cre_dt, 
		last_chg_dt, 
		data_stat_cd, 
		farm_srgt_id, 
		farm_durb_id, 
		adm_fsa_st_cnty_srgt_id, 
		adm_fsa_st_cnty_durb_id, 
		pgm_yr, 
		tr_srgt_id, tr_durb_id, 
		fsa_crop_srgt_id, 
		fsa_crop_durb_id, 
		loc_fsa_st_cnty_srgt_id, 
		loc_fsa_st_cnty_durb_id, 
		cong_dist_srgt_id, 
		cong_dist_durb_id, 
		crop_tr_yr_dcp_cre_dt, 
		crop_tr_yr_dcp_last_chg_dt, 
		crop_tr_yr_last_chg_user_nm, 
		src_data_stat_cd, 
		crp_rdn_acrg, 
		crp_rel_acrg, 
		dcp_crop_base_acrg, 
		fav_rdn_acrg, 
		ccp_pymt_yld, 
		crp_pymt_yld, 
		dir_pymt_yld, 
		fav_dir_pymt_yld, 
		fav_ccp_pymt_yld, 
		ctr_rdn_acrg
FROM farm_dm_stg.crop_tr_fact
where farm_srgt_id > 0
ORDER BY farm_srgt_id ASC;