WITH stg AS
  (SELECT DISTINCT MD5 (COALESCE (CONT_PLAN_CERT_ELCT.PGM_YR::varchar(32), '-1') || '~~' || UPPER (COALESCE (TRIM (CONT_PLAN_CERT_ELCT.ST_FSA_CD) , '--')) || '~~' || UPPER (COALESCE (TRIM (CONT_PLAN_CERT_ELCT.CNTY_FSA_CD) , '--')) || '~~' || UPPER (COALESCE (TRIM (CONT_PLAN_CERT_ELCT.FARM_NBR) , '--')) || '~~' || COALESCE (CONT_PLAN_CERT_ELCT.CORE_CUST_ID::varchar(32), '-1') || '~~' || UPPER (COALESCE (TRIM (CONT_PLAN_CERT_ELCT.FSA_CROP_CD) , '--')) || '~~' || UPPER (COALESCE (TRIM (CONT_PLAN_CERT_ELCT.FSA_CROP_TYPE_CD) , '--')) || '~~' || UPPER (COALESCE (TRIM (CONT_PLAN_CERT_ELCT.CROP_INTN_USE_CD) , '--'))) AS CONT_PLAN_CERT_ELCT_L_ID,
                   COALESCE (CONT_PLAN_CERT_ELCT.CONT_PLAN_CERT_ELCT_ID,
                             0) CONT_PLAN_CERT_ELCT_ID,
                            CONT_PLAN_CERT_ELCT.LOAD_DT LOAD_DT,
                            CONT_PLAN_CERT_ELCT.CDC_DT DATA_EFF_STRT_DT,
                            CONT_PLAN_CERT_ELCT.DATA_SRC_NM DATA_SRC_NM,
                            CONT_PLAN_CERT_ELCT.DATA_STAT_CD DATA_STAT_CD,
                            CONT_PLAN_CERT_ELCT.CRE_DT SRC_CRE_DT,
                            CONT_PLAN_CERT_ELCT.CRE_USER_NM SRC_CRE_USER_NM,
                            CONT_PLAN_CERT_ELCT.LAST_CHG_DT SRC_LAST_CHG_DT,
                            CONT_PLAN_CERT_ELCT.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
                            CONT_PLAN_CERT_ELCT.DATA_IACTV_DT DATA_IACTV_DT,
                            CONT_PLAN_CERT_ELCT.CROP_TYPE_ID CROP_TYPE_ID,
                            CONT_PLAN_CERT_ELCT.BUS_PTY_ID BUS_PTY_ID,
                            CONT_PLAN_CERT_ELCT.ELCT_TERM_DT ELCT_TERM_DT,
                            CONT_PLAN_CERT_ELCT.ELCT_TERM_RSN_DESC ELCT_TERM_RSN_DESC,
                            CONT_PLAN_CERT_ELCT.TERM_LTR_GNRT_IND TERM_LTR_GNRT_IND,
                            CONT_PLAN_CERT_ELCT.ELCT_DT ELCT_DT,
                            CONT_PLAN_CERT_ELCT.CDC_OPER_CD,
                            MD5 (CONT_PLAN_CERT_ELCT.PGM_YR || '~~' || TRIM (CONT_PLAN_CERT_ELCT.ST_FSA_CD) || '~~' || TRIM (CONT_PLAN_CERT_ELCT.CNTY_FSA_CD) || '~~' || TRIM (CONT_PLAN_CERT_ELCT.FARM_NBR) || '~~' || CONT_PLAN_CERT_ELCT.CORE_CUST_ID || '~~' || TRIM (CONT_PLAN_CERT_ELCT.FSA_CROP_CD) || '~~' || TRIM (CONT_PLAN_CERT_ELCT.FSA_CROP_TYPE_CD) || '~~' || TRIM (CONT_PLAN_CERT_ELCT.CROP_INTN_USE_CD) || '~~' || CONT_PLAN_CERT_ELCT.CONT_PLAN_CERT_ELCT_ID || '~~' || TRIM (CONT_PLAN_CERT_ELCT.DATA_STAT_CD) || '~~' || TO_CHAR (CONT_PLAN_CERT_ELCT.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF') || '~~' || TRIM (CONT_PLAN_CERT_ELCT.CRE_USER_NM) || '~~' || TO_CHAR (CONT_PLAN_CERT_ELCT.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF') || '~~' || TRIM (CONT_PLAN_CERT_ELCT.LAST_CHG_USER_NM) || '~~' || TO_CHAR (CONT_PLAN_CERT_ELCT.DATA_IACTV_DT, 'YYYY-MM-DD HH24:MI:SS.FF') || '~~' || CONT_PLAN_CERT_ELCT.CROP_TYPE_ID || '~~' || CONT_PLAN_CERT_ELCT.BUS_PTY_ID || '~~' || TO_CHAR (CONT_PLAN_CERT_ELCT.ELCT_TERM_DT, 'YYYY-MM-DD HH24:MI:SS.FF') || '~~' || TRIM (CONT_PLAN_CERT_ELCT.ELCT_TERM_RSN_DESC) || '~~' || TRIM (CONT_PLAN_CERT_ELCT.TERM_LTR_GNRT_IND) || '~~' || TO_CHAR (CONT_PLAN_CERT_ELCT.ELCT_DT, 'YYYY-MM-DD HH24:MI:SS.FF')) HASH_DIF
   FROM CARS_STG.CONT_PLAN_CERT_ELCT CONT_PLAN_CERT_ELCT
   WHERE CONT_PLAN_CERT_ELCT.CDC_OPER_CD = 'D'
     AND DATE (CONT_PLAN_CERT_ELCT.CDC_DT) = DATE (TO_TIMESTAMP ('{ETL_START_TIMESTAMP}', 'YYYY-MM-DD HH24:MI:SS.FF'))
     AND CONT_PLAN_CERT_ELCT.LOAD_DT = TO_TIMESTAMP (TO_CHAR(CURRENT_DATE, 'YYYY-MM-DD'),
                                                     'YYYY-MM-DD HH24:MI:SS.FF')
   ORDER BY CONT_PLAN_CERT_ELCT.CDC_DT),
     remainder AS
  (UPDATE edv.CONT_PLAN_CERT_ELCT_LS dv
   SET LOAD_END_DT = stg.LOAD_DT,
       DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
   FROM stg
   WHERE COALESCE (stg.CONT_PLAN_CERT_ELCT_ID,
                   0) = COALESCE (dv.CONT_PLAN_CERT_ELCT_ID,
                                  0)
     AND dv.LOAD_DT <> stg.LOAD_DT
     AND dv.LOAD_END_DT = TO_TIMESTAMP ('9999-12-31',
                                        'YYYY-MM-DD') RETURNING dv.*)
INSERT INTO edv.CONT_PLAN_CERT_ELCT_LS (CONT_PLAN_CERT_ELCT_L_ID, CONT_PLAN_CERT_ELCT_ID, LOAD_DT, DATA_EFF_STRT_DT, DATA_SRC_NM, DATA_STAT_CD, SRC_CRE_DT, SRC_CRE_USER_NM, SRC_LAST_CHG_DT, SRC_LAST_CHG_USER_NM, DATA_IACTV_DT, CROP_TYPE_ID, BUS_PTY_ID, ELCT_TERM_DT, ELCT_TERM_RSN_DESC, TERM_LTR_GNRT_IND, ELCT_DT, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
SELECT stg.CONT_PLAN_CERT_ELCT_L_ID,
       stg.CONT_PLAN_CERT_ELCT_ID,
       stg.LOAD_DT,
       stg.DATA_EFF_STRT_DT,
       stg.DATA_SRC_NM,
       stg.DATA_STAT_CD,
       stg.SRC_CRE_DT,
       stg.SRC_CRE_USER_NM,
       stg.SRC_LAST_CHG_DT,
       stg.SRC_LAST_CHG_USER_NM,
       stg.DATA_IACTV_DT,
       stg.CROP_TYPE_ID,
       stg.BUS_PTY_ID,
       stg.ELCT_TERM_DT,
       stg.ELCT_TERM_RSN_DESC,
       stg.TERM_LTR_GNRT_IND,
       stg.ELCT_DT,
       stg.DATA_EFF_STRT_DT,
       stg.LOAD_DT,
       stg.HASH_DIF
FROM stg
WHERE NOT EXISTS
    (SELECT '1'
     FROM remainder dv
     WHERE COALESCE (stg.CONT_PLAN_CERT_ELCT_ID,
                     0) = COALESCE (dv.CONT_PLAN_CERT_ELCT_ID,
                                    0) )