INSERT INTO EDV.PYMT_ATRB_RDN_TYPE_RS (PYMT_ATRB_RDN_TYPE_CD, LOAD_DT, DATA_EFF_STRT_DT, DATA_SRC_NM, SRC_CRE_DT, SRC_CRE_USER_NM, SRC_LAST_CHG_DT, SRC_LAST_CHG_USER_NM, PYMT_ATRB_RDN_CAT_CD, PYMT_ATRB_RDN_TYPE_NM, PCT_BASE_RDN_IND, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
  (SELECT stg.*
   FROM
     (SELECT DISTINCT COALESCE (trim(PYMT_ATRB_RDN_TYPE.PYMT_ATRB_RDN_TYPE_CD),
                           '--') PYMT_ATRB_RDN_TYPE_CD,
                          PYMT_ATRB_RDN_TYPE.LOAD_DT LOAD_DT,
                          PYMT_ATRB_RDN_TYPE.CDC_DT DATA_EFF_STRT_DT,
                          PYMT_ATRB_RDN_TYPE.DATA_SRC_NM DATA_SRC_NM,
                          PYMT_ATRB_RDN_TYPE.CRE_DT SRC_CRE_DT,
                          PYMT_ATRB_RDN_TYPE.CRE_USER_NM SRC_CRE_USER_NM,
                          PYMT_ATRB_RDN_TYPE.LAST_CHG_DT SRC_LAST_CHG_DT,
                          PYMT_ATRB_RDN_TYPE.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
                          PYMT_ATRB_RDN_TYPE.PYMT_ATRB_RDN_CAT_CD PYMT_ATRB_RDN_CAT_CD,
                          PYMT_ATRB_RDN_TYPE.PYMT_ATRB_RDN_TYPE_NM PYMT_ATRB_RDN_TYPE_NM,
                          PYMT_ATRB_RDN_TYPE.PCT_BASE_RDN_IND PCT_BASE_RDN_IND,
                          TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD') DATA_EFF_END_DT,
                          TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD') LOAD_END_DT, /** DATA_EFF_END_DT, LOAD_END_DT */ MD5 (trim(PYMT_ATRB_RDN_TYPE.PYMT_ATRB_RDN_TYPE_CD)||'~~'||to_char(PYMT_ATRB_RDN_TYPE.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PYMT_ATRB_RDN_TYPE.CRE_USER_NM)||'~~'||to_char(PYMT_ATRB_RDN_TYPE.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF')||'~~'||trim(PYMT_ATRB_RDN_TYPE.LAST_CHG_USER_NM)||'~~'||trim(PYMT_ATRB_RDN_TYPE.PYMT_ATRB_RDN_CAT_CD)||'~~'||trim(PYMT_ATRB_RDN_TYPE.PYMT_ATRB_RDN_TYPE_NM)||'~~'||trim(PYMT_ATRB_RDN_TYPE.PCT_BASE_RDN_IND)) HASH_DIF
      FROM SBSD_STG.PYMT_ATRB_RDN_TYPE
      WHERE PYMT_ATRB_RDN_TYPE.cdc_oper_cd IN ('I',
                                               'UN')
        AND date(PYMT_ATRB_RDN_TYPE.CDC_DT) = date(TO_TIMESTAMP ('{ETL_START_TIMESTAMP}', 'YYYY-MM-DD HH24:MI:SS.FF'))
      ORDER BY PYMT_ATRB_RDN_TYPE.CDC_DT) stg
   LEFT JOIN EDV.PYMT_ATRB_RDN_TYPE_RS dv ON (stg.HASH_DIF = dv.HASH_DIF
                                              AND dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD'))
   WHERE dv.HASH_DIF IS NULL )