SELECT 
PYMT_ATRB_RDN_TYPE_CD,
PYMT_ATRB_RDN_TYPE_NM,
PYMT_ATRB_RDN_CAT_CD,
PCT_BASE_RDN_IND,
CRE_DT,
CRE_USER_NM,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT
FROM (
SELECT * FROM
(
SELECT PYMT_ATRB_RDN_TYPE_CD,
PYMT_ATRB_RDN_TYPE_NM,
PYMT_ATRB_RDN_CAT_CD,
PCT_BASE_RDN_IND,
CRE_DT,
CRE_USER_NM,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
PYMT_ATRB_RDN_TYPE_CD
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
PAYMENT_ATTRIBUTION_REDUCTION_TYPE.payment_attribution_reduction_type_code PYMT_ATRB_RDN_TYPE_CD,
PAYMENT_ATTRIBUTION_REDUCTION_TYPE.payment_attribution_reduction_type_name PYMT_ATRB_RDN_TYPE_NM,
PAYMENT_ATTRIBUTION_REDUCTION_TYPE.payment_attribution_reduction_category_code PYMT_ATRB_RDN_CAT_CD,
PAYMENT_ATTRIBUTION_REDUCTION_TYPE.percentage_based_reduction_indicator PCT_BASE_RDN_IND,
PAYMENT_ATTRIBUTION_REDUCTION_TYPE.creation_date CRE_DT,
PAYMENT_ATTRIBUTION_REDUCTION_TYPE.creation_user_name CRE_USER_NM,
PAYMENT_ATTRIBUTION_REDUCTION_TYPE.last_change_date LAST_CHG_DT,
PAYMENT_ATTRIBUTION_REDUCTION_TYPE.last_change_user_name LAST_CHG_USER_NM,
'I' OP,
1 AS TBL_PRIORITY
FROM `fsa-{env}-sbsd-cdc`.`PAYMENT_ATTRIBUTION_REDUCTION_TYPE`
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
)