SELECT DISTINCT
CRP_ACREAGE.COUNTY_FSA_CODE CNTY_FSA_CD,
CRP_ACREAGE.CROPLAND_ACREAGE CPLD_ACRG,
CRP_ACREAGE.CREATION_DATE CRE_DT,
CRP_ACREAGE.CREATION_USER_NAME CRE_USER_NM,
CRP_ACREAGE.CROP_YEAR CROP_YR,
CRP_ACREAGE.CRP_ACREAGE_IDENTIFIER CRP_ACRG_ID,
CRP_ACREAGE.DATA_STATUS_CODE DATA_STAT_CD,
CRP_ACREAGE.FARM_NUMBER FARM_NBR,
CRP_ACREAGE.LAST_CHANGE_DATE LAST_CHG_DT,
CRP_ACREAGE.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CRP_ACREAGE.MPL_ACREAGE MPL_ACRG,
CRP_ACREAGE.NON_CROPLAND_ACREAGE NON_CPLD_ACRG,
CRP_ACREAGE.STATE_FSA_CODE ST_FSA_CD,
OP AS CDC_OPER_CD,
1 AS row_num_part
FROM CRP_ACREAGE
WHERE OP <> 'D'
UNION
SELECT DISTINCT
CRP_ACREAGE.COUNTY_FSA_CODE CNTY_FSA_CD,
CRP_ACREAGE.CROPLAND_ACREAGE CPLD_ACRG,
CRP_ACREAGE.CREATION_DATE CRE_DT,
CRP_ACREAGE.CREATION_USER_NAME CRE_USER_NM,
CRP_ACREAGE.CROP_YEAR CROP_YR,
CRP_ACREAGE.CRP_ACREAGE_IDENTIFIER CRP_ACRG_ID,
CRP_ACREAGE.DATA_STATUS_CODE DATA_STAT_CD,
CRP_ACREAGE.FARM_NUMBER FARM_NBR,
CRP_ACREAGE.LAST_CHANGE_DATE LAST_CHG_DT,
CRP_ACREAGE.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
CRP_ACREAGE.MPL_ACREAGE MPL_ACRG,
CRP_ACREAGE.NON_CROPLAND_ACREAGE NON_CPLD_ACRG,
CRP_ACREAGE.STATE_FSA_CODE ST_FSA_CD,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM CRP_ACREAGE
WHERE OP = 'D'