SELECT SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
GRSLD_RANK_FCTR_IDN,
GRSLD_RANK_FCTR_NM,
GRSLD_RANK_FCTR_DESC,
MAX_RANK_PNT_CT,
GRSLD_RANK_FCTR_ID,
SGNP_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
CRE_USER_NM,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT SGNP_NBR,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_STYPE_AGR_NM,
GRSLD_RANK_FCTR_IDN,
GRSLD_RANK_FCTR_NM,
GRSLD_RANK_FCTR_DESC,
MAX_RANK_PNT_CT,
GRSLD_RANK_FCTR_ID,
SGNP_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
CRE_USER_NM,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
GRSLD_RANK_FCTR_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
grassland_ranking_factor.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
grassland_ranking_factor.GRSLD_RANK_FCTR_NM GRSLD_RANK_FCTR_NM,
grassland_ranking_factor.GRSLD_RANK_FCTR_DESC GRSLD_RANK_FCTR_DESC,
grassland_ranking_factor.MAX_RANK_PNT_CT MAX_RANK_PNT_CT,
grassland_ranking_factor.GRSLD_RANK_FCTR_ID GRSLD_RANK_FCTR_ID,
grassland_ranking_factor.SGNP_ID SGNP_ID,
grassland_ranking_factor.DATA_STAT_CD DATA_STAT_CD,
grassland_ranking_factor.CRE_DT CRE_DT,
grassland_ranking_factor.LAST_CHG_DT LAST_CHG_DT,
grassland_ranking_factor.CRE_USER_NM CRE_USER_NM,
grassland_ranking_factor.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_FACTOR.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_FACTOR" GRASSLAND_RANKING_FACTOR 

  Left join "fsa-{env}-cnsv".EWT14SGNP EWT14SGNP 
 ON ( GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID)
 WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_FACTOR.OP <> 'D'

UNION
SELECT 
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
grassland_ranking_factor.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
grassland_ranking_factor.GRSLD_RANK_FCTR_NM GRSLD_RANK_FCTR_NM,
grassland_ranking_factor.GRSLD_RANK_FCTR_DESC GRSLD_RANK_FCTR_DESC,
grassland_ranking_factor.MAX_RANK_PNT_CT MAX_RANK_PNT_CT,
grassland_ranking_factor.GRSLD_RANK_FCTR_ID GRSLD_RANK_FCTR_ID,
grassland_ranking_factor.SGNP_ID SGNP_ID,
grassland_ranking_factor.DATA_STAT_CD DATA_STAT_CD,
grassland_ranking_factor.CRE_DT CRE_DT,
grassland_ranking_factor.LAST_CHG_DT LAST_CHG_DT,
grassland_ranking_factor.CRE_USER_NM CRE_USER_NM,
grassland_ranking_factor.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT14SGNP.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."EWT14SGNP" EWT14SGNP

       JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR GRASSLAND_RANKING_FACTOR
      ON ( GRASSLAND_RANKING_FACTOR.SGNP_ID = EWT14SGNP.SGNP_ID)
 WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT14SGNP.OP <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
NULL SGNP_NBR,
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_STYPE_AGR_NM,
grassland_ranking_factor.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
grassland_ranking_factor.GRSLD_RANK_FCTR_NM GRSLD_RANK_FCTR_NM,
grassland_ranking_factor.GRSLD_RANK_FCTR_DESC GRSLD_RANK_FCTR_DESC,
grassland_ranking_factor.MAX_RANK_PNT_CT MAX_RANK_PNT_CT,
grassland_ranking_factor.GRSLD_RANK_FCTR_ID GRSLD_RANK_FCTR_ID,
grassland_ranking_factor.SGNP_ID SGNP_ID,
grassland_ranking_factor.DATA_STAT_CD DATA_STAT_CD,
grassland_ranking_factor.CRE_DT CRE_DT,
grassland_ranking_factor.LAST_CHG_DT LAST_CHG_DT,
grassland_ranking_factor.CRE_USER_NM CRE_USER_NM,
grassland_ranking_factor.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".grassland_ranking_factor grassland_ranking_factor
 WHERE grassland_ranking_factor.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and grassland_ranking_factor.OP = 'D'
)