INSERT into
EDV.ARC_PLC_ELG_DTER_RH(ARC_PLC_ELG_DTER_CD,
LOAD_DT,
DATA_SRC_NM)
(
SELECT 
stg.ARC_PLC_ELG_DTER_CD,
stg.LOAD_DT,
stg.DATA_SRC_NM
from (
SELECT DISTINCT
coalesce(DMN_VAL.DMN_CHAR_VAL, '[NULL IN SOURCE]') ARC_PLC_ELG_DTER_CD,
DMN_VAL.LOAD_DT LOAD_DT,
DMN_VAL.DATA_SRC_NM DATA_SRC_NM,
ROW_NUMBER() OVER (PARTITION BY DMN_VAL.DMN_CHAR_VAL ORDER BY DMN_VAL.CDC_DT desc, DMN_VAL.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.DMN_VAL
WHERE DMN_VAL.DMN_ID in (59)
and DMN_VAL.cdc_oper_cd IN ('I','UN','D')
) stg 
LEFT JOIN  EDV.ARC_PLC_ELG_DTER_RH dv
 ON (
stg.ARC_PLC_ELG_DTER_CD = dv.ARC_PLC_ELG_DTER_CD
)
where (
dv.ARC_PLC_ELG_DTER_CD IS NULL
)
and stg.STG_EFF_DT_RANK = 1
);