INSERT into
EDV.FRS_PGM_RS(PGM_ABR,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
LOAD_DT,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(
SELECT stg.PGM_ABR,
stg.DATA_EFF_STRT_DT,
stg.DATA_SRC_NM,
stg.DATA_STAT_CD,
stg.LOAD_DT,
stg.SRC_CRE_DT,
stg.SRC_LAST_CHG_DT,
stg.SRC_LAST_CHG_USER_NM, stg.DATA_EFF_END_DT, stg.LOAD_END_DT, stg.HASH_DIF from (
SELECT DISTINCT
coalesce(CROP.PGM_ABR, '--') PGM_ABR,
CROP.CDC_DT DATA_EFF_STRT_DT,
CROP.DATA_SRC_NM DATA_SRC_NM,
CROP.DATA_STAT_CD DATA_STAT_CD,
CROP.LOAD_DT LOAD_DT,
CROP.CRE_DT SRC_CRE_DT,
CROP.LAST_CHG_DT SRC_LAST_CHG_DT,
CROP.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM ,
TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(trim(both CROP.PGM_ABR)||'~~'||trim(both CROP.DATA_STAT_CD)||'~~'||CROP.DPLY_SEQ_NBR||'~~'||to_char(CROP.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(CROP.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP.LAST_CHG_USER_NM)) HASH_DIF,
ROW_NUMBER() OVER (PARTITION BY CROP.PGM_ABR ORDER BY CROP.CDC_DT desc, CROP.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.CROP
where CROP.cdc_oper_cd IN ('I','UN')
order by CROP.CDC_DT
) stg 
LEFT JOIN  EDV.FRS_PGM_RS dv
ON (
stg.PGM_ABR = dv.PGM_ABR
)
where (
dv.PGM_ABR IS NULL
and  not exists (select 1 from EDV.FRS_PGM_RS rs
                 where stg.PGM_ABR = rs.PGM_ABR
				 and stg.PGM_ABR = rs.PGM_ABR
				)
)
and stg.STG_EFF_DT_RANK = 1
)
;


