INSERT into
EDV.FLD_HEL_STAT_RS(
FLD_HEL_STAT_CD,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DFLT_VAL_IND,
DMN_ID,
DMN_VAL_DESC,
DMN_VAL_ID,
DMN_VAL_NM,
DPLY_SEQ_NBR,
LOAD_DT,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM, 
DATA_EFF_END_DT, 
LOAD_END_DT, 
HASH_DIF
)
(
SELECT stg.* 
from (
	SELECT DISTINCT
		coalesce(DMN_VAL.DMN_CHAR_VAL, '[NULL IN SOURCE]') FLD_HEL_STAT_CD,
		DMN_VAL.CDC_DT DATA_EFF_STRT_DT,
		DMN_VAL.DATA_SRC_NM DATA_SRC_NM,
		DMN_VAL.DFLT_VAL_IND DFLT_VAL_IND,
		DMN_VAL.DMN_ID DMN_ID,
		DMN_VAL.DMN_VAL_DESC DMN_VAL_DESC,
		DMN_VAL.DMN_VAL_ID DMN_VAL_ID,
		DMN_VAL.DMN_VAL_NM DMN_VAL_NM,
		DMN_VAL.DPLY_SEQ_NBR DPLY_SEQ_NBR,
		DMN_VAL.LOAD_DT LOAD_DT,
		DMN_VAL.CRE_DT SRC_CRE_DT,
		DMN_VAL.LAST_CHG_DT SRC_LAST_CHG_DT,
		DMN_VAL.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM ,
		TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
		MD5(trim(both DMN_VAL.DMN_CHAR_VAL)||'~~'||trim(both DMN_VAL.DFLT_VAL_IND)||'~~'||DMN_VAL.DMN_ID||'~~'||trim(both DMN_VAL.DMN_VAL_DESC)||'~~'||DMN_VAL.DMN_VAL_ID||'~~'||trim(both DMN_VAL.DMN_VAL_NM)||'~~'||DMN_VAL.DPLY_SEQ_NBR||'~~'||to_char(DMN_VAL.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(DMN_VAL.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both DMN_VAL.LAST_CHG_USER_NM)) HASH_DIF
		FROM SQL_FARM_RCD_STG.DMN_VAL
		WHERE DMN_ID = 43
		and DMN_VAL.cdc_oper_cd IN ('I','UN')
		order by DMN_VAL.CDC_DT
	) stg 
LEFT JOIN  EDV.FLD_HEL_STAT_RS dv
ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.FLD_HEL_STAT_RS rs
				 where stg.FLD_HEL_STAT_CD = rs.FLD_HEL_STAT_CD
				 and stg.LOAD_DT = rs.LOAD_DT
			)
);

