INSERT into
EDV.PGM_CROP_LS(PGM_CROP_L_ID,
CROP_ID,
LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
PGM_ABR,
FSA_CROP_CD,
FSA_CROP_ABR,
FSA_CROP_NM,
FSA_CROP_TYPE_NM,
FSA_CROP_TYPE_CD,
DPLY_SEQ_NBR,
DATA_EFF_END_DT,
LOAD_END_DT,
HASH_DIF)
(SELECT stg.* 
from (
	SELECT DISTINCT 
		MD5(upper(coalesce(trim(both CROP.PGM_ABR), '--')) ||'~~'||upper(coalesce(trim(both CROP.FSA_CROP_CD), '--')) ||'~~'||upper(coalesce(trim(both CROP.FSA_CROP_TYPE_CD), '--')) ) as PGM_CROP_L_ID,
		CROP.CROP_ID CROP_ID,
		CROP.LOAD_DT LOAD_DT,
		CROP.CDC_DT DATA_EFF_STRT_DT,
		CROP.DATA_SRC_NM DATA_SRC_NM,
		CROP.DATA_STAT_CD DATA_STAT_CD,
		CROP.CRE_DT SRC_CRE_DT,
		CROP.LAST_CHG_DT SRC_LAST_CHG_DT,
		CROP.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
		coalesce(CROP.PGM_ABR, '--') PGM_ABR,
		coalesce(CROP.FSA_CROP_CD, '--') FSA_CROP_CD,
		CROP.FSA_CROP_ABR FSA_CROP_ABR,CROP.FSA_CROP_NM FSA_CROP_NM,
		CROP.FSA_CROP_TYPE_NM FSA_CROP_TYPE_NM,
		coalesce(CROP.FSA_CROP_TYPE_CD, '--') FSA_CROP_TYPE_CD,
		CROP.DPLY_SEQ_NBR DPLY_SEQ_NBR,
		to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, 
		to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
		MD5(trim(both CROP.PGM_ABR)||'~~'||trim(both CROP.FSA_CROP_CD)||'~~'||trim(both CROP.FSA_CROP_TYPE_CD)||'~~'||CROP.CROP_ID||'~~'||trim(both CROP.DATA_STAT_CD)||'~~'||to_char(CROP.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(CROP.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CROP.LAST_CHG_USER_NM)||'~~'||trim(both CROP.PGM_ABR)||'~~'||trim(both CROP.FSA_CROP_CD)||'~~'||trim(both CROP.FSA_CROP_ABR)||'~~'||trim(both CROP.FSA_CROP_NM)||'~~'||trim(both CROP.FSA_CROP_TYPE_NM)||'~~'||trim(both CROP.FSA_CROP_TYPE_CD)||'~~'||CROP.DPLY_SEQ_NBR) HASH_DIF
	FROM SQL_FARM_RCD_STG.CROP CROP
	where CROP.CDC_OPER_CD IN ('I','UN')
	order by CROP.CDC_DT
	) stg
 LEFT JOIN  EDV.PGM_CROP_LS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.PGM_CROP_LS ls
				where stg.PGM_CROP_L_ID = ls.PGM_CROP_L_ID 
				and stg.CROP_ID = ls.CROP_ID 
				and stg.LOAD_DT = ls.LOAD_DT 
              )
)
;

