SELECT GRSLD_USE_TYPE_NM,
GRSLD_USE_TYPE_CD,
GRSLD_USE_TYPE_DESC,
GRSLD_USE_TYPE_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
CRE_USER_NM,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM(

SELECT * FROM (
SELECT DISTINCT
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_NM GRSLD_USE_TYPE_NM,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_CD GRSLD_USE_TYPE_CD,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_DESC GRSLD_USE_TYPE_DESC,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_ID GRSLD_USE_TYPE_ID,
GRASSLAND_USAGE_TYPE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_USAGE_TYPE.CRE_DT CRE_DT,
GRASSLAND_USAGE_TYPE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_USAGE_TYPE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_USAGE_TYPE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
OP AS CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".GRASSLAND_USAGE_TYPE GRASSLAND_USAGE_TYPE
WHERE dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and OP <> 'D'
UNION
SELECT DISTINCT
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_NM GRSLD_USE_TYPE_NM,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_CD GRSLD_USE_TYPE_CD,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_DESC GRSLD_USE_TYPE_DESC,
GRASSLAND_USAGE_TYPE.GRSLD_USE_TYPE_ID GRSLD_USE_TYPE_ID,
GRASSLAND_USAGE_TYPE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_USAGE_TYPE.CRE_DT CRE_DT,
GRASSLAND_USAGE_TYPE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_USAGE_TYPE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_USAGE_TYPE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".GRASSLAND_USAGE_TYPE GRASSLAND_USAGE_TYPE
WHERE dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and OP = 'D'
))