SELECT DISTINCT
ewt13ajcncnty.ST_FIPS_CD ST_FIPS_CD,
ewt13ajcncnty.CNTY_FIPS_CD CNTY_FIPS_CD,
ewt13ajcncnty.AJCN_ST_FIPS_CD AJCN_ST_FIPS_CD,
ewt13ajcncnty.AJCN_CNTY_FIPS_CD AJCN_CNTY_FIPS_CD,
ewt13ajcncnty.DATA_STAT_CD DATA_STAT_CD,
ewt13ajcncnty.CRE_DT CRE_DT,
ewt13ajcncnty.LAST_CHG_DT LAST_CHG_DT,
ewt13ajcncnty.LAST_CHG_USER_NM LAST_CHG_USER_NM,
--OP AS CDC_OPER_CD,
1 AS row_num_part
FROM ewt13ajcncnty
--WHERE OP <> 'D'
UNION
SELECT DISTINCT
ewt13ajcncnty.ST_FIPS_CD ST_FIPS_CD,
ewt13ajcncnty.CNTY_FIPS_CD CNTY_FIPS_CD,
ewt13ajcncnty.AJCN_ST_FIPS_CD AJCN_ST_FIPS_CD,
ewt13ajcncnty.AJCN_CNTY_FIPS_CD AJCN_CNTY_FIPS_CD,
ewt13ajcncnty.DATA_STAT_CD DATA_STAT_CD,
ewt13ajcncnty.CRE_DT CRE_DT,
ewt13ajcncnty.LAST_CHG_DT LAST_CHG_DT,
ewt13ajcncnty.LAST_CHG_USER_NM LAST_CHG_USER_NM,
--'D' CDC_OPER_CD,
1 AS row_num_part
FROM ewt13ajcncnty
--WHERE OP = 'D'