-- Julia Lu edition - will update this paragraph and query when (cnsv/ccms)-cdc is ready
-- Stage SQL: CCMS_MST_CTR (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CCMS_MST_CTR/incremental/CCMS_MST_CTR.sql
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_NM,
SGNP_SUB_CAT_NM,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
CTR_NBR,
CTR_ID,
CNSV_PGM_CD,
SGNP_ID,
PGM_YR,
ORGN_STRT_DT,
ORGN_END_DT,
OFR_ID,
HYDRO_UNIT_CD,
ORGN_APRV_DT,
LOC_ST_FSA_CD,
LOC_CNTY_FSA_CD,
HUC_GIS_CPA_ZONE,
SGNP_INCTV_PYMT_AMT,
ORGN_ANL_RNT_AMT_PER_ACRE,
CTR_LGTH_YEARS,
PYMT_LMT_TYPE_ID,
CTR_CORE_DET_ID,
PYMT_LMT_PVSN_CD,
PYMT_LMT_PVSN_CD_YR,
OFR_ADM_ST_FSA_CD,
OFR_ADM_CNTY_FSA_CD,
OFR_TR_NBR,
OFR_SCNR_NM,
DATA_STAT_CD,
CRE_DT,
CRE_USER_NM,
LAST_CHG_DT,
LAST_CHG_USER_NM,
SUPL_CTR_TYPE_ABR,
CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
CTR_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_NM,
ewt14sgnp.SGNP_STYPE_DESC SGNP_SUB_CAT_NM,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
MASTER_CONTRACT.CONTRACT_IDENTIFIER CTR_ID,
MASTER_CONTRACT.CONSERVATION_PROGRAM_CODE CNSV_PGM_CD,
MASTER_CONTRACT.SIGNUP_IDENTIFIER SGNP_ID,
MASTER_CONTRACT.PROGRAM_YEAR PGM_YR,
MASTER_CONTRACT.ORIGINAL_START_DATE ORGN_STRT_DT,
MASTER_CONTRACT.ORIGINAL_END_DATE ORGN_END_DT,
MASTER_CONTRACT.OFFER_IDENTIFICATION OFR_ID,
MASTER_CONTRACT.HYDROLOGIC_UNIT_CODE HYDRO_UNIT_CD,
MASTER_CONTRACT.ORIGINAL_APPROVED_DATE ORGN_APRV_DT,
MASTER_CONTRACT.LOCATION_STATE_FSA_CODE LOC_ST_FSA_CD,
MASTER_CONTRACT.LOCATION_COUNTY_FSA_CODE LOC_CNTY_FSA_CD,
MASTER_CONTRACT.HUC_GIS_CPA_ZONE HUC_GIS_CPA_ZONE,
MASTER_CONTRACT.SIGNUP_INCENTIVE_PAYMENT_AMOUNT SGNP_INCTV_PYMT_AMT,
MASTER_CONTRACT.ORIGINAL_ANNUAL_RENTAL_AMOUNT_PER_ACRE ORGN_ANL_RNT_AMT_PER_ACRE,
MASTER_CONTRACT.CONTRACT_LENGTH_YEARS CTR_LGTH_YEARS,
MASTER_CONTRACT.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
MASTER_CONTRACT.CTR_CORE_DET_ID CTR_CORE_DET_ID,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
ewt40ofrsc.ADM_ST_FSA_CD OFR_ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD OFR_ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR OFR_TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
MASTER_CONTRACT.DATA_STATUS_CODE DATA_STAT_CD,
MASTER_CONTRACT.CREATION_DATE CRE_DT,
MASTER_CONTRACT.CREATION_USER_NAME CRE_USER_NM,
MASTER_CONTRACT.LAST_CHANGE_DATE LAST_CHG_DT,
MASTER_CONTRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
MASTER_CONTRACT.supplemental_contract_type_abbreviation SUPL_CTR_TYPE_ABR,
MASTER_CONTRACT.op,
1 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".MASTER_CONTRACT  
LEFT JOIN "fsa-{env}-cnsv-cdc".ewt14sgnp ON (MASTER_CONTRACT.SIGNUP_IDENTIFIER = ewt14sgnp.SGNP_ID)   
LEFT JOIN "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE ON (MASTER_CONTRACT.PYMT_LMT_TYPE_ID = PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID )  
LEFT JOIN "fsa-{env}-cnsv-cdc".ewt40ofrsc ON (ewt40ofrsc.OFR_SCNR_ID = MASTER_CONTRACT.OFFER_IDENTIFICATION ) 
WHERE MASTER_CONTRACT.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_NM,
ewt14sgnp.SGNP_STYPE_DESC SGNP_SUB_CAT_NM,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
MASTER_CONTRACT.CONTRACT_IDENTIFIER CTR_ID,
MASTER_CONTRACT.CONSERVATION_PROGRAM_CODE CNSV_PGM_CD,
MASTER_CONTRACT.SIGNUP_IDENTIFIER SGNP_ID,
MASTER_CONTRACT.PROGRAM_YEAR PGM_YR,
MASTER_CONTRACT.ORIGINAL_START_DATE ORGN_STRT_DT,
MASTER_CONTRACT.ORIGINAL_END_DATE ORGN_END_DT,
MASTER_CONTRACT.OFFER_IDENTIFICATION OFR_ID,
MASTER_CONTRACT.HYDROLOGIC_UNIT_CODE HYDRO_UNIT_CD,
MASTER_CONTRACT.ORIGINAL_APPROVED_DATE ORGN_APRV_DT,
MASTER_CONTRACT.LOCATION_STATE_FSA_CODE LOC_ST_FSA_CD,
MASTER_CONTRACT.LOCATION_COUNTY_FSA_CODE LOC_CNTY_FSA_CD,
MASTER_CONTRACT.HUC_GIS_CPA_ZONE HUC_GIS_CPA_ZONE,
MASTER_CONTRACT.SIGNUP_INCENTIVE_PAYMENT_AMOUNT SGNP_INCTV_PYMT_AMT,
MASTER_CONTRACT.ORIGINAL_ANNUAL_RENTAL_AMOUNT_PER_ACRE ORGN_ANL_RNT_AMT_PER_ACRE,
MASTER_CONTRACT.CONTRACT_LENGTH_YEARS CTR_LGTH_YEARS,
MASTER_CONTRACT.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
MASTER_CONTRACT.CTR_CORE_DET_ID CTR_CORE_DET_ID,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
ewt40ofrsc.ADM_ST_FSA_CD OFR_ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD OFR_ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR OFR_TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
MASTER_CONTRACT.DATA_STATUS_CODE DATA_STAT_CD,
MASTER_CONTRACT.CREATION_DATE CRE_DT,
MASTER_CONTRACT.CREATION_USER_NAME CRE_USER_NM,
MASTER_CONTRACT.LAST_CHANGE_DATE LAST_CHG_DT,
MASTER_CONTRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
MASTER_CONTRACT.supplemental_contract_type_abbreviation SUPL_CTR_TYPE_ABR,
ewt14sgnp.op,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".ewt14sgnp 
JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT ON (MASTER_CONTRACT.SIGNUP_IDENTIFIER = ewt14sgnp.SGNP_ID)   
LEFT JOIN "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE ON (MASTER_CONTRACT.PYMT_LMT_TYPE_ID = PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID )  
LEFT JOIN "fsa-{env}-cnsv-cdc".ewt40ofrsc ON (ewt40ofrsc.OFR_SCNR_ID = MASTER_CONTRACT.OFFER_IDENTIFICATION ) 
WHERE ewt14sgnp.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_NM,
ewt14sgnp.SGNP_STYPE_DESC SGNP_SUB_CAT_NM,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
MASTER_CONTRACT.CONTRACT_IDENTIFIER CTR_ID,
MASTER_CONTRACT.CONSERVATION_PROGRAM_CODE CNSV_PGM_CD,
MASTER_CONTRACT.SIGNUP_IDENTIFIER SGNP_ID,
MASTER_CONTRACT.PROGRAM_YEAR PGM_YR,
MASTER_CONTRACT.ORIGINAL_START_DATE ORGN_STRT_DT,
MASTER_CONTRACT.ORIGINAL_END_DATE ORGN_END_DT,
MASTER_CONTRACT.OFFER_IDENTIFICATION OFR_ID,
MASTER_CONTRACT.HYDROLOGIC_UNIT_CODE HYDRO_UNIT_CD,
MASTER_CONTRACT.ORIGINAL_APPROVED_DATE ORGN_APRV_DT,
MASTER_CONTRACT.LOCATION_STATE_FSA_CODE LOC_ST_FSA_CD,
MASTER_CONTRACT.LOCATION_COUNTY_FSA_CODE LOC_CNTY_FSA_CD,
MASTER_CONTRACT.HUC_GIS_CPA_ZONE HUC_GIS_CPA_ZONE,
MASTER_CONTRACT.SIGNUP_INCENTIVE_PAYMENT_AMOUNT SGNP_INCTV_PYMT_AMT,
MASTER_CONTRACT.ORIGINAL_ANNUAL_RENTAL_AMOUNT_PER_ACRE ORGN_ANL_RNT_AMT_PER_ACRE,
MASTER_CONTRACT.CONTRACT_LENGTH_YEARS CTR_LGTH_YEARS,
MASTER_CONTRACT.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
MASTER_CONTRACT.CTR_CORE_DET_ID CTR_CORE_DET_ID,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
ewt40ofrsc.ADM_ST_FSA_CD OFR_ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD OFR_ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR OFR_TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
MASTER_CONTRACT.DATA_STATUS_CODE DATA_STAT_CD,
MASTER_CONTRACT.CREATION_DATE CRE_DT,
MASTER_CONTRACT.CREATION_USER_NAME CRE_USER_NM,
MASTER_CONTRACT.LAST_CHANGE_DATE LAST_CHG_DT,
MASTER_CONTRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
MASTER_CONTRACT.supplemental_contract_type_abbreviation SUPL_CTR_TYPE_ABR,
ewt40ofrsc.op,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc".ewt40ofrsc 
JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT ON (ewt40ofrsc.OFR_SCNR_ID = MASTER_CONTRACT.OFFER_IDENTIFICATION ) 
LEFT JOIN "fsa-{env}-cnsv-cdc".ewt14sgnp ON (MASTER_CONTRACT.SIGNUP_IDENTIFIER = ewt14sgnp.SGNP_ID)   
LEFT JOIN "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE ON (MASTER_CONTRACT.PYMT_LMT_TYPE_ID = PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID )  
WHERE ewt40ofrsc.op <> 'D'

UNION
SELECT 
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_NM,
ewt14sgnp.SGNP_STYPE_DESC SGNP_SUB_CAT_NM,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
MASTER_CONTRACT.CONTRACT_IDENTIFIER CTR_ID,
MASTER_CONTRACT.CONSERVATION_PROGRAM_CODE CNSV_PGM_CD,
MASTER_CONTRACT.SIGNUP_IDENTIFIER SGNP_ID,
MASTER_CONTRACT.PROGRAM_YEAR PGM_YR,
MASTER_CONTRACT.ORIGINAL_START_DATE ORGN_STRT_DT,
MASTER_CONTRACT.ORIGINAL_END_DATE ORGN_END_DT,
MASTER_CONTRACT.OFFER_IDENTIFICATION OFR_ID,
MASTER_CONTRACT.HYDROLOGIC_UNIT_CODE HYDRO_UNIT_CD,
MASTER_CONTRACT.ORIGINAL_APPROVED_DATE ORGN_APRV_DT,
MASTER_CONTRACT.LOCATION_STATE_FSA_CODE LOC_ST_FSA_CD,
MASTER_CONTRACT.LOCATION_COUNTY_FSA_CODE LOC_CNTY_FSA_CD,
MASTER_CONTRACT.HUC_GIS_CPA_ZONE HUC_GIS_CPA_ZONE,
MASTER_CONTRACT.SIGNUP_INCENTIVE_PAYMENT_AMOUNT SGNP_INCTV_PYMT_AMT,
MASTER_CONTRACT.ORIGINAL_ANNUAL_RENTAL_AMOUNT_PER_ACRE ORGN_ANL_RNT_AMT_PER_ACRE,
MASTER_CONTRACT.CONTRACT_LENGTH_YEARS CTR_LGTH_YEARS,
MASTER_CONTRACT.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
MASTER_CONTRACT.CTR_CORE_DET_ID CTR_CORE_DET_ID,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD PYMT_LMT_PVSN_CD,
PYMT_LMT_TYPE.PYMT_LMT_PVSN_CD_YR PYMT_LMT_PVSN_CD_YR,
ewt40ofrsc.ADM_ST_FSA_CD OFR_ADM_ST_FSA_CD,
ewt40ofrsc.ADM_CNTY_FSA_CD OFR_ADM_CNTY_FSA_CD,
ewt40ofrsc.TR_NBR OFR_TR_NBR,
ewt40ofrsc.OFR_SCNR_NM OFR_SCNR_NM,
MASTER_CONTRACT.DATA_STATUS_CODE DATA_STAT_CD,
MASTER_CONTRACT.CREATION_DATE CRE_DT,
MASTER_CONTRACT.CREATION_USER_NAME CRE_USER_NM,
MASTER_CONTRACT.LAST_CHANGE_DATE LAST_CHG_DT,
MASTER_CONTRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
MASTER_CONTRACT.supplemental_contract_type_abbreviation SUPL_CTR_TYPE_ABR,
PYMT_LMT_TYPE.op,
4 AS TBL_PRIORITY
FROM "fsa-{env}-ccms-cdc".PYMT_LMT_TYPE  
JOIN "fsa-{env}-ccms-cdc".MASTER_CONTRACT ON (MASTER_CONTRACT.PYMT_LMT_TYPE_ID = PYMT_LMT_TYPE.PYMT_LMT_TYPE_ID )  
LEFT JOIN "fsa-{env}-cnsv-cdc".ewt14sgnp ON (MASTER_CONTRACT.SIGNUP_IDENTIFIER = ewt14sgnp.SGNP_ID)   
LEFT JOIN "fsa-{env}-cnsv-cdc".ewt40ofrsc ON (ewt40ofrsc.OFR_SCNR_ID = MASTER_CONTRACT.OFFER_IDENTIFICATION ) 
WHERE PYMT_LMT_TYPE.op <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND MASTER_CONTRACT.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT DISTINCT
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE ADM_ST_FSA_CD,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE ADM_CNTY_FSA_CD,
NULL SGNP_TYPE_NM,
NULL SGNP_SUB_CAT_NM,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
MASTER_CONTRACT.CONTRACT_NUMBER CTR_NBR,
MASTER_CONTRACT.CONTRACT_IDENTIFIER CTR_ID,
MASTER_CONTRACT.CONSERVATION_PROGRAM_CODE CNSV_PGM_CD,
MASTER_CONTRACT.SIGNUP_IDENTIFIER SGNP_ID,
MASTER_CONTRACT.PROGRAM_YEAR PGM_YR,
MASTER_CONTRACT.ORIGINAL_START_DATE ORGN_STRT_DT,
MASTER_CONTRACT.ORIGINAL_END_DATE ORGN_END_DT,
MASTER_CONTRACT.OFFER_IDENTIFICATION OFR_ID,
MASTER_CONTRACT.HYDROLOGIC_UNIT_CODE HYDRO_UNIT_CD,
MASTER_CONTRACT.ORIGINAL_APPROVED_DATE ORGN_APRV_DT,
MASTER_CONTRACT.LOCATION_STATE_FSA_CODE LOC_ST_FSA_CD,
MASTER_CONTRACT.LOCATION_COUNTY_FSA_CODE LOC_CNTY_FSA_CD,
MASTER_CONTRACT.HUC_GIS_CPA_ZONE HUC_GIS_CPA_ZONE,
MASTER_CONTRACT.SIGNUP_INCENTIVE_PAYMENT_AMOUNT SGNP_INCTV_PYMT_AMT,
MASTER_CONTRACT.ORIGINAL_ANNUAL_RENTAL_AMOUNT_PER_ACRE ORGN_ANL_RNT_AMT_PER_ACRE,
MASTER_CONTRACT.CONTRACT_LENGTH_YEARS CTR_LGTH_YEARS,
MASTER_CONTRACT.PYMT_LMT_TYPE_ID PYMT_LMT_TYPE_ID,
MASTER_CONTRACT.CTR_CORE_DET_ID CTR_CORE_DET_ID,
NULL PYMT_LMT_PVSN_CD,
NULL PYMT_LMT_PVSN_CD_YR,
NULL OFR_ADM_ST_FSA_CD,
NULL OFR_ADM_CNTY_FSA_CD,
NULL OFR_TR_NBR,
NULL OFR_SCNR_NM,
MASTER_CONTRACT.DATA_STATUS_CODE DATA_STAT_CD,
MASTER_CONTRACT.CREATION_DATE CRE_DT,
MASTER_CONTRACT.CREATION_USER_NAME CRE_USER_NM,
MASTER_CONTRACT.LAST_CHANGE_DATE LAST_CHG_DT,
MASTER_CONTRACT.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,
MASTER_CONTRACT.supplemental_contract_type_abbreviation SUPL_CTR_TYPE_ABR,
'D' CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-{env}-ccms-cdc".MASTER_CONTRACT
WHERE MASTER_CONTRACT.op = 'D'