with upsert_data as(
SELECT DISTINCT
DM.LAND_CLS_DURB_ID,
DM.DATA_EFF_STRT_DT,
DM.LAND_CLS_CD,
DM.LAND_CLS_NM,
DM.LAND_CLS_DESC
FROM (
SELECT 
LH.DURB_ID AS  LAND_CLS_DURB_ID,
coalesce(LS.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) DATA_EFF_STRT_DT,
LS.LAND_CLS_ID AS LAND_CLS_CD,
LS.DMN_VAL_NM AS LAND_CLS_NM,
LS.DMN_VAL_DESC AS LAND_CLS_DESC,
ROW_NUMBER() OVER ( PARTITION BY coalesce(LS.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')), LS.LAND_CLS_ID ORDER BY LS.DATA_EFF_STRT_DT DESC) AS ROW_NUM_PART
FROM EDV.LAND_CLS_RS LS
LEFT JOIN  EDV.LAND_CLS_RH  LH  ON (coalesce(LS.LAND_CLS_ID,'[NULL IN SOURCE]') = LH.LAND_CLS_ID)
WHERE cast(LS.DATA_EFF_STRT_DT as date) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 
AND EXISTS ( SELECT '1' FROM EDV.LAND_CLS_RS LS_IN
             WHERE LS_IN.LAND_CLS_ID = LS.LAND_CLS_ID
              AND cast(LS_IN.DATA_EFF_END_DT as date) > TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')) 
AND LH.DURB_ID IS NOT NULL              
) DM
WHERE DM.ROW_NUM_PART = 1
)
select ud.land_cls_durb_id,
	'1' as cur_rcd_ind,
	(current_date) as data_eff_strt_dt,
	cast('9999-12-31' as DATE) as data_eff_end_dt, 
	(current_date) as cre_dt, 
	ud.land_cls_cd,
	ud.land_cls_nm,
	ud.land_cls_desc
from upsert_data ud









