INSERT INTO EDV.CMB_PRDR_ACCT_PRNT_L (CMB_PRDR_ACCT_PRNT_L_ID, PRIM_CMB_PRDR_ACCT_H_ID, SUB_ACCT_CMB_PRDR_ACCT_H_ID, LOAD_DT, DATA_SRC_NM)
  (SELECT stg.CMB_PRDR_ACCT_PRNT_L_ID,
          stg.PRIM_CMB_PRDR_ACCT_H_ID,
          stg.SUB_ACCT_CMB_PRDR_ACCT_H_ID,
          stg.LOAD_DT,
          stg.DATA_SRC_NM
   FROM
     (SELECT DISTINCT MD5  (MD5  (coalesce(CMB_PRDR_ACCT_H.CMB_PRDR_ACCT_ID::varchar, '-1')) || MD5  (coalesce(CMB_PRDR_ACCT.CMB_PRDR_ACCT_ID::varchar, '-1'))) CMB_PRDR_ACCT_PRNT_L_ID,
                      MD5  (coalesce(CMB_PRDR_ACCT_H.CMB_PRDR_ACCT_ID::varchar, '-1')) PRIM_CMB_PRDR_ACCT_H_ID,
                      MD5  (coalesce(CMB_PRDR_ACCT.CMB_PRDR_ACCT_ID::varchar, '-1')) SUB_ACCT_CMB_PRDR_ACCT_H_ID,
                      CMB_PRDR_ACCT.LOAD_DT LOAD_DT,
                      CMB_PRDR_ACCT.DATA_SRC_NM DATA_SRC_NM,
                      ROW_NUMBER () OVER (PARTITION BY MD5  (coalesce(CMB_PRDR_ACCT_H.CMB_PRDR_ACCT_ID::varchar, '-1')),
                                                       MD5  (coalesce(CMB_PRDR_ACCT.CMB_PRDR_ACCT_ID::varchar, '-1'))
                                          ORDER BY CMB_PRDR_ACCT.CDC_DT DESC, CMB_PRDR_ACCT.LOAD_DT DESC) STG_EFF_DT_RANK
      FROM SBSD_STG.CMB_PRDR_ACCT
      LEFT OUTER JOIN EDV.CMB_PRDR_ACCT_H ON (CMB_PRDR_ACCT_H.CMB_PRDR_ACCT_ID=CMB_PRDR_ACCT.PRNT_CMB_PRDR_ACCT_ID)
      WHERE CMB_PRDR_ACCT.PRNT_CMB_PRDR_ACCT_ID <>0
        AND CMB_PRDR_ACCT.PRNT_CMB_PRDR_ACCT_ID IS NOT NULL ) stg
   LEFT JOIN EDV.CMB_PRDR_ACCT_PRNT_L dv ON (stg.CMB_PRDR_ACCT_PRNT_L_ID = dv.CMB_PRDR_ACCT_PRNT_L_ID)
   WHERE (dv.CMB_PRDR_ACCT_PRNT_L_ID IS NULL)
     AND stg.STG_EFF_DT_RANK = 1 )