merge into EDV.PRDR_PGM_PYMT_LMT_ADJ_LS dv
using (
	select
		distinct md5(coalesce (PRDR_PGM_PYMT_LMT_ADJ.CORE_CUST_ID, '-1') || '~~' || upper(coalesce (trim(PRDR_PGM_PYMT_LMT_ADJ.PGM_NM), '[NULL IN SOURCE]')) || '~~' || coalesce (PRDR_PGM_PYMT_LMT_ADJ.SBSD_PRD_STRT_YR, '-1') || '~~' || upper(coalesce (trim(PRDR_PGM_PYMT_LMT_ADJ.PRDR_PYMT_LMT_ADJ_TYPE_CD), '--')) ) as PRDR_PGM_PYMT_LMT_ADJ_L_ID,
		coalesce(PRDR_PGM_PYMT_LMT_ADJ.PRDR_PGM_PYMT_LMT_ADJ_ID, '-1') PRDR_PGM_PYMT_LMT_ADJ_ID,
		PRDR_PGM_PYMT_LMT_ADJ.LOAD_DT LOAD_DT,
		PRDR_PGM_PYMT_LMT_ADJ.CDC_DT DATA_EFF_STRT_DT,
		PRDR_PGM_PYMT_LMT_ADJ.DATA_SRC_NM DATA_SRC_NM,
		PRDR_PGM_PYMT_LMT_ADJ.DATA_STAT_CD DATA_STAT_CD,
		PRDR_PGM_PYMT_LMT_ADJ.CRE_DT SRC_CRE_DT,
		PRDR_PGM_PYMT_LMT_ADJ.CRE_USER_NM SRC_CRE_USER_NM,
		PRDR_PGM_PYMT_LMT_ADJ.LAST_CHG_DT SRC_LAST_CHG_DT,
		PRDR_PGM_PYMT_LMT_ADJ.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
		PRDR_PGM_PYMT_LMT_ADJ.TRNSM_STAT_CD TRNSM_STAT_CD,
		PRDR_PGM_PYMT_LMT_ADJ.SBSD_CUST_ID SBSD_CUST_ID,
		PRDR_PGM_PYMT_LMT_ADJ.PYMT_PGM_PRD_ID PYMT_PGM_PRD_ID,
		PRDR_PGM_PYMT_LMT_ADJ.PRDR_PYMT_LMT_ADJ_TYPE_CD PRDR_PYMT_LMT_ADJ_TYPE_CD,
		PRDR_PGM_PYMT_LMT_ADJ.PYMT_LMT_ADJ_AMT PYMT_LMT_ADJ_AMT,
		PRDR_PGM_PYMT_LMT_ADJ.NOTE_TXT NOTE_TXT ,
		PRDR_PGM_PYMT_LMT_ADJ.CDC_OPER_CD,
		md5(PRDR_PGM_PYMT_LMT_ADJ.CORE_CUST_ID || '~~' || trim(PRDR_PGM_PYMT_LMT_ADJ.PGM_NM)|| '~~' || PRDR_PGM_PYMT_LMT_ADJ.SBSD_PRD_STRT_YR || '~~' || trim(PRDR_PGM_PYMT_LMT_ADJ.PRDR_PYMT_LMT_ADJ_TYPE_CD)|| '~~' || PRDR_PGM_PYMT_LMT_ADJ.PRDR_PGM_PYMT_LMT_ADJ_ID || '~~' || trim(PRDR_PGM_PYMT_LMT_ADJ.DATA_STAT_CD)|| '~~' || to_char(PRDR_PGM_PYMT_LMT_ADJ.CRE_DT, 'YYYY-MM-DD HH24:MI:SS.FF')|| '~~' || trim(PRDR_PGM_PYMT_LMT_ADJ.CRE_USER_NM)|| '~~' || to_char(PRDR_PGM_PYMT_LMT_ADJ.LAST_CHG_DT, 'YYYY-MM-DD HH24:MI:SS.FF')|| '~~' || trim(PRDR_PGM_PYMT_LMT_ADJ.LAST_CHG_USER_NM)|| '~~' || trim(PRDR_PGM_PYMT_LMT_ADJ.TRNSM_STAT_CD)|| '~~' || PRDR_PGM_PYMT_LMT_ADJ.SBSD_CUST_ID || '~~' || PRDR_PGM_PYMT_LMT_ADJ.PYMT_PGM_PRD_ID || '~~' || trim(PRDR_PGM_PYMT_LMT_ADJ.PRDR_PYMT_LMT_ADJ_TYPE_CD)|| '~~' || PRDR_PGM_PYMT_LMT_ADJ.PYMT_LMT_ADJ_AMT || '~~' || trim(PRDR_PGM_PYMT_LMT_ADJ.NOTE_TXT)) HASH_DIF
	from
		SBSD_STG.PRDR_PGM_PYMT_LMT_ADJ PRDR_PGM_PYMT_LMT_ADJ
	where PRDR_PGM_PYMT_LMT_ADJ.CDC_OPER_CD = 'D'
		and date(PRDR_PGM_PYMT_LMT_ADJ.CDC_DT) = date(TO_TIMESTAMP ('{ETL_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF'))
		and PRDR_PGM_PYMT_LMT_ADJ.LOAD_DT = (SELECT MAX(LOAD_DT) FROM SBSD_STG.PRDR_PGM_PYMT_LMT_ADJ)
	order by
		PRDR_PGM_PYMT_LMT_ADJ.CDC_DT)
stg
 on coalesce(stg.PRDR_PGM_PYMT_LMT_ADJ_ID, 0) = coalesce(dv.PRDR_PGM_PYMT_LMT_ADJ_ID, 0)
when matched 
  and dv.LOAD_DT <> stg.LOAD_DT
	and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31', 'YYYY-MM-DD')
then
update
set
	LOAD_END_DT = stg.LOAD_DT,
	DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
when not matched then
insert
	(
  PRDR_PGM_PYMT_LMT_ADJ_L_ID,
	PRDR_PGM_PYMT_LMT_ADJ_ID,
	LOAD_DT,
	DATA_EFF_STRT_DT,
	DATA_SRC_NM,
	DATA_STAT_CD,
	SRC_CRE_DT,
	SRC_CRE_USER_NM,
	SRC_LAST_CHG_DT,
	SRC_LAST_CHG_USER_NM,
	TRNSM_STAT_CD,
	SBSD_CUST_ID,
	PYMT_PGM_PRD_ID,
	PRDR_PYMT_LMT_ADJ_TYPE_CD,
	PYMT_LMT_ADJ_AMT,
	NOTE_TXT,
	DATA_EFF_END_DT,
	LOAD_END_DT,
	HASH_DIF)
values (
stg.PRDR_PGM_PYMT_LMT_ADJ_L_ID,
stg.PRDR_PGM_PYMT_LMT_ADJ_ID,
stg.LOAD_DT,
stg.DATA_EFF_STRT_DT,
stg.DATA_SRC_NM,
stg.DATA_STAT_CD,
stg.SRC_CRE_DT,
stg.SRC_CRE_USER_NM,
stg.SRC_LAST_CHG_DT,
stg.SRC_LAST_CHG_USER_NM,
stg.TRNSM_STAT_CD,
stg.SBSD_CUST_ID,
stg.PYMT_PGM_PRD_ID,
stg.PRDR_PYMT_LMT_ADJ_TYPE_CD,
stg.PYMT_LMT_ADJ_AMT,
stg.NOTE_TXT,
stg.DATA_EFF_STRT_DT,
stg.LOAD_DT,
stg.HASH_DIF
)