SELECT 
PYMT_ISU_YR,
HRCH_LVL_NM,
ST_FSA_CD,
CNTY_FSA_CD,
SGNP_SUB_CAT_NM,
CNSV_PYMT_TYPE,
ACCT_PGM_CD,
ACCT_REF_1_NBR,
CORE_CUST_ID,
CNSV_CTR_NBR,
CNSV_CTR_SFX_CD,
BUS_TYPE_CD,
ADR_ID,
BUS_NM,
PYMT_RCPT_ID,
ADR_TYPE_CD,
DLVR_ADR_LINE,
ADR_INFO_LINE,
CITY_NM,
ST_ABR,
ZIP_CD,
FGN_ADR_LINE,
ACCT_REF_4_NBR,
BUS_TYPE_DESC,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT
FROM (
SELECT * FROM
(
SELECT DISTINCT PYMT_ISU_YR,
HRCH_LVL_NM,
ST_FSA_CD,
CNTY_FSA_CD,
SGNP_SUB_CAT_NM,
CNSV_PYMT_TYPE,
ACCT_PGM_CD,
ACCT_REF_1_NBR,
CORE_CUST_ID,
CNSV_CTR_NBR,
CNSV_CTR_SFX_CD,
BUS_TYPE_CD,
ADR_ID,
BUS_NM,
PYMT_RCPT_ID,
ADR_TYPE_CD,
DLVR_ADR_LINE,
ADR_INFO_LINE,
CITY_NM,
ST_ABR,
ZIP_CD,
FGN_ADR_LINE,
ACCT_REF_4_NBR,
BUS_TYPE_DESC,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
ADR_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."ADDRESS" ADDRESS
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (ADDRESS.PYMT_RCPT_ID = PAYMENT_RECIPIENT.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT  
ON (PAYMENT_RECIPIENT.PRPS_PYMT_ID = PROPOSED_PAYMENT.PRPS_PYMT_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PROPOSED_PAYMENT.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT14SGNP.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT  
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS 
ON (ADDRESS.PYMT_RCPT_ID = PAYMENT_RECIPIENT.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT  
ON (PAYMENT_RECIPIENT.PRPS_PYMT_ID = PROPOSED_PAYMENT.PRPS_PYMT_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PROPOSED_PAYMENT.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT14SGNP.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."BUSINESS_TYPE" BUSINESS_TYPE  
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (BUSINESS_TYPE.BUS_TYPE_ID = PAYMENT_RECIPIENT.BUS_TYPE_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (PAYMENT_RECIPIENT.PYMT_RCPT_ID = ADDRESS.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT  
ON (PAYMENT_RECIPIENT.PRPS_PYMT_ID = PROPOSED_PAYMENT.PRPS_PYMT_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PROPOSED_PAYMENT.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT 
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT14SGNP.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
4 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PROPOSED_PAYMENT" PROPOSED_PAYMENT  
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = PAYMENT_RECIPIENT.PRPS_PYMT_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (PAYMENT_RECIPIENT.PYMT_RCPT_ID = ADDRESS.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PROPOSED_PAYMENT.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT40OFRSC.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT40OFRSC <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
5 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PAYMENT_TYPE" PAYMENT_TYPE   
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT  
ON (PAYMENT_TYPE.PYMT_TYPE_ID = PROPOSED_PAYMENT.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = PAYMENT_RECIPIENT.PRPS_PYMT_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (PAYMENT_RECIPIENT.PYMT_RCPT_ID = ADDRESS.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT 
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND EWT14SGNP.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
6 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PYMT_IMPL" PYMT_IMPL
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PYMT_IMPL.PYMT_IMPL_ID = PAYMENT_TYPE.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT  
ON (PAYMENT_TYPE.PYMT_TYPE_ID = PROPOSED_PAYMENT.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = PAYMENT_RECIPIENT.PRPS_PYMT_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (PAYMENT_RECIPIENT.PYMT_RCPT_ID = ADDRESS.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT40OFRSC.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND EWT40OFRSC.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
7 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID = PYMT_IMPL.PGM_HRCH_LVL_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PYMT_IMPL.PYMT_IMPL_ID = PAYMENT_TYPE.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT  
ON (PAYMENT_TYPE.PYMT_TYPE_ID = PROPOSED_PAYMENT.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = PAYMENT_RECIPIENT.PRPS_PYMT_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (PAYMENT_RECIPIENT.PYMT_RCPT_ID = ADDRESS.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
AND EWT14SGNP.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
8 AS TBL_PRIORITY
FROM (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID, ENTITY.OP
           FROM "fsa-{env}-cnsv-cdc"."ENTITY" ENTITY   
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT 
ON (ENTITY.PRPS_PYMT_ID = PROPOSED_PAYMENT.PRPS_PYMT_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = PAYMENT_RECIPIENT.PRPS_PYMT_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (PAYMENT_RECIPIENT.PYMT_RCPT_ID = ADDRESS.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PROPOSED_PAYMENT.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT 
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT14SGNP.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
MASTER_CONTRACT.OP,
9 AS TBL_PRIORITY
FROM (SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat,
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE,
MASTER_CONTRACT.OP  
FROM (Select * from"fsa-{env}-cnsv-cdc"."MASTER_CONTRACT" MASTER_CONTRACT where supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) as TEMP
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = PAYMENT_RECIPIENT.PRPS_PYMT_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (PAYMENT_RECIPIENT.PYMT_RCPT_ID = ADDRESS.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PROPOSED_PAYMENT.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT14SGNP.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
10 AS TBL_PRIORITY
FROM (SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat,
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE,
MASTER_CONTRACT.OP  
FROM "fsa-{env}-cnsv-cdc"."CONTRACT_DETAIL" CONTRACT_DETAIL  
LEFT JOIN ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
ON (CONTRACT_DETAIL.CONTRACT_IDENTIFIER = MASTER_CONTRACT.CONTRACT_IDENTIFIER)
) as TEMP
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = PAYMENT_RECIPIENT.PRPS_PYMT_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (PAYMENT_RECIPIENT.PYMT_RCPT_ID = ADDRESS.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PROPOSED_PAYMENT.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT14SGNP.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
11 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."SIGNUP" SIGNUP
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (SIGNUP.SIGNUP_IDENTIFIER = TEMP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT  
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = PAYMENT_RECIPIENT.PRPS_PYMT_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (PAYMENT_RECIPIENT.PYMT_RCPT_ID = ADDRESS.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PROPOSED_PAYMENT.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT40OFRSC.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT40OFRSC.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
12 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."SIGNUP_SUB_CATEGORY" SIGNUP_SUB_CATEGORY
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT  
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (PAYMENT_RECIPIENT.PRPS_PYMT_ID = PROPOSED_PAYMENT.PRPS_PYMT_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (ADDRESS.PYMT_RCPT_ID = PAYMENT_RECIPIENT.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PROPOSED_PAYMENT.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
                           ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
           FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC 
           WHERE CNSV_CTR_SEQ_NBR > 0
          ) EWT40OFRSC
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
and ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) /* RA 09/22/2017:Updated code */
)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT40OFRSC.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
13 AS TBL_PRIORITY
FROM (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, EWT40OFRSC.OP, 
             ltrim(rtrim(concat(cast(CNSV_CTR_SEQ_NBR as varchar),CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
             FROM <V_SRC_SCHM_CNSV_NM>.fn_net_changes_EWT40OFRSC('<V_CDC_ST_DT>','<V_CDC_END_DT>','ALL')   
             WHERE CNSV_CTR_SEQ_NBR > 0
     ) EWT40OFRSC
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT  
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
AND ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) )/* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (PAYMENT_RECIPIENT.PRPS_PYMT_ID = PROPOSED_PAYMENT.PRPS_PYMT_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (ADDRESS.PYMT_RCPT_ID = PAYMENT_RECIPIENT.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PROPOSED_PAYMENT.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
LEFT JOIN "fsa-{env}-cnsv"."EWT14SGNP" EWT14SGNP
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
WHERE EWT40OFRSC.OP <> 'D'
UNION
SELECT 
PROPOSED_PAYMENT.PYMT_ISU_YR PYMT_ISU_YR,
PROGRAM_HIERARCHY_LEVEL.HRCH_LVL_NM HRCH_LVL_NM,
PROPOSED_PAYMENT.ST_FSA_CD ST_FSA_CD,
PROPOSED_PAYMENT.CNTY_FSA_CD CNTY_FSA_CD,
CASE
WHEN  PAYMENT_TYPE.APP_CD IN ( 'FCRP', 'BCAP') THEN  EWT14SGNP.SGNP_STYPE_DESC
WHEN PAYMENT_TYPE.APP_CD =  'CRP' THEN SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_NAME
END SGNP_SUB_CAT_NM,
PAYMENT_TYPE.CNSV_PYMT_TYPE CNSV_PYMT_TYPE,
PAYMENT_TYPE.ACCT_PGM_CD ACCT_PGM_CD,
PROPOSED_PAYMENT.ACCT_REF_1_NBR ACCT_REF_1_NBR,
ENTITY.CORE_CUST_ID CORE_CUST_ID,
left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1) CNSV_CTR_NBR,
CASE 
WHEN patindex('%[a-z]%',PROPOSED_PAYMENT.ACCT_REF_1_NBR) =  1 
THEN NULL 
WHEN len(rtrim(ltrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')))) > 2
THEN NULL 
ELSE
rtrim(REPLACE ( PROPOSED_PAYMENT.ACCT_REF_1_NBR,left( PROPOSED_PAYMENT.ACCT_REF_1_NBR,patindex('%[^0-9]%', PROPOSED_PAYMENT.ACCT_REF_1_NBR+'.')-1),'')) /* RA 09/22/2017:Updated code */
END CNSV_CTR_SFX_CD,
BUSINESS_TYPE.BUS_TYPE_CD BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
PAYMENT_RECIPIENT.BUS_NM BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
PROPOSED_PAYMENT.ACCT_REF_4_NBR ACCT_REF_4_NBR,
BUSINESS_TYPE.BUS_TYPE_DESC BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
ADDRESS.OP,
14 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."EWT14SGNP" EWT14SGNP
LEFT JOIN (SELECT DISTINCT SGNP_ID,ADM_CNTY_FSA_CD, ADM_ST_FSA_CD, 
             ltrim(rtrim(concat(cast(EWT40OFRSC.CNSV_CTR_SEQ_NBR as varchar),EWT40OFRSC.CNSV_CTR_SUFX_CD))) as ACCT_REF_1_NBR  /* RA 09/22/2017:Updated code */
             FROM "fsa-{env}-cnsv"."EWT40OFRSC" EWT40OFRSC
             WHERE CNSV_CTR_SEQ_NBR > 0
     ) EWT40OFRSC
ON (EWT40OFRSC.SGNP_ID = EWT14SGNP.SGNP_ID)
LEFT JOIN "fsa-{env}-cnsv"."PROPOSED_PAYMENT" PROPOSED_PAYMENT  
ON (PROPOSED_PAYMENT.CNTY_FSA_CD = EWT40OFRSC.ADM_CNTY_FSA_CD 
AND PROPOSED_PAYMENT.ST_FSA_CD = EWT40OFRSC.ADM_ST_FSA_CD
AND ltrim(rtrim(PROPOSED_PAYMENT.ACCT_REF_1_NBR)) = ltrim(rtrim(EWT40OFRSC.ACCT_REF_1_NBR)) )/* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_RECIPIENT" PAYMENT_RECIPIENT
ON (PAYMENT_RECIPIENT.PRPS_PYMT_ID = PROPOSED_PAYMENT.PRPS_PYMT_ID)
JOIN "fsa-{env}-cnsv"."ADDRESS" ADDRESS
ON (ADDRESS.PYMT_RCPT_ID = PAYMENT_RECIPIENT.PYMT_RCPT_ID)
LEFT JOIN "fsa-{env}-cnsv"."BUSINESS_TYPE" BUSINESS_TYPE
ON (PAYMENT_RECIPIENT.BUS_TYPE_ID = BUSINESS_TYPE.BUS_TYPE_ID)
LEFT JOIN "fsa-{env}-cnsv"."PAYMENT_TYPE" PAYMENT_TYPE  
ON (PROPOSED_PAYMENT.PYMT_TYPE_ID = PAYMENT_TYPE.PYMT_TYPE_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PYMT_IMPL" PYMT_IMPL  
ON (PAYMENT_TYPE.PYMT_IMPL_ID = PYMT_IMPL.PYMT_IMPL_ID) 
LEFT JOIN "fsa-{env}-cnsv"."PROGRAM_HIERARCHY_LEVEL" PROGRAM_HIERARCHY_LEVEL  
ON (PYMT_IMPL.PGM_HRCH_LVL_ID = PROGRAM_HIERARCHY_LEVEL.PGM_HRCH_LVL_ID) 
LEFT JOIN (SELECT DISTINCT PRPS_PYMT_ID, CORE_CUST_ID 
           FROM "fsa-{env}-cnsv"."ENTITY" ENTITY 
           WHERE PRNT_ENTY_ID IS NULL) ENTITY 
ON (PROPOSED_PAYMENT.PRPS_PYMT_ID = ENTITY.PRPS_PYMT_ID) 
LEFT JOIN 
(SELECT DISTINCT ltrim(rtrim(CONCAT(cast(MASTER_CONTRACT.CONTRACT_NUMBER as varchar),CONTRACT_DETAIL.CONTRACT_SUFFIX_NUMBER))) as cat, /* RA 09/22/2017:Updated code */
MASTER_CONTRACT.SIGNUP_IDENTIFIER,
MASTER_CONTRACT.ADMINISTRATIVE_COUNTY_FSA_CODE,
MASTER_CONTRACT.ADMINISTRATIVE_STATE_FSA_CODE 
FROM ( Select * from  "fsa-{env}-cnsv"."MASTER_CONTRACT" MASTER_CONTRACT where MASTER_CONTRACT.supplemental_contract_type_abbreviation is null ) MASTER_CONTRACT
LEFT JOIN "fsa-{env}-cnsv"."CONTRACT_DETAIL" CONTRACT_DETAIL
ON (MASTER_CONTRACT.CONTRACT_IDENTIFIER = CONTRACT_DETAIL.CONTRACT_IDENTIFIER)
) AS TEMP
ON (TEMP.ADMINISTRATIVE_COUNTY_FSA_CODE = PROPOSED_PAYMENT.CNTY_FSA_CD
AND TEMP.ADMINISTRATIVE_STATE_FSA_CODE = PROPOSED_PAYMENT.ST_FSA_CD
AND TEMP.CAT = LTRIM(RTRIM(PROPOSED_PAYMENT.ACCT_REF_1_NBR))) /* RA 09/22/2017:Updated code */
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP 
ON (TEMP.SIGNUP_IDENTIFIER = SIGNUP.SIGNUP_IDENTIFIER)
LEFT JOIN "fsa-{env}-cnsv"."SIGNUP" SIGNUP_SUB_CATEGORY
ON (SIGNUP.SIGNUP_SUB_CATEGORY_CODE = SIGNUP_SUB_CATEGORY.SIGNUP_SUB_CATEGORY_CODE)
WHERE SIGNUP.OP <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
NULL PYMT_ISU_YR,
NULL HRCH_LVL_NM,
NULL ST_FSA_CD,
NULL CNTY_FSA_CD,
NULL SGNP_SUB_CAT_NM,
NULL CNSV_PYMT_TYPE,
NULL ACCT_PGM_CD,
NULL ACCT_REF_1_NBR,
NULL CORE_CUST_ID,
NULL CNSV_CTR_NBR,
NULL CNSV_CTR_SFX_CD,
NULL BUS_TYPE_CD,
ADDRESS.ADR_ID ADR_ID,
NULL BUS_NM,
ADDRESS.PYMT_RCPT_ID PYMT_RCPT_ID,
ADDRESS.ADR_TYPE_CD ADR_TYPE_CD,
ADDRESS.DLVR_ADR_LINE DLVR_ADR_LINE,
ADDRESS.ADR_INFO_LINE ADR_INFO_LINE,
ADDRESS.CITY_NM CITY_NM,
ADDRESS.ST_ABR ST_ABR,
ADDRESS.ZIP_CD ZIP_CD,
ADDRESS.FGN_ADR_LINE FGN_ADR_LINE,
NULL ACCT_REF_4_NBR,
NULL BUS_TYPE_DESC,
ADDRESS.DATA_STAT_CD DATA_STAT_CD,
ADDRESS.CRE_DT CRE_DT,
ADDRESS.LAST_CHG_DT LAST_CHG_DT,
ADDRESS.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc"."ADDRESS" ADDRESS
WHERE ADDRESS.OP = 'D')