SELECT          DISTINCT
				PRDR_PGM_PYMT_LMT_ADJ_TYPE_RH.DURB_ID PYMT_LMT_ADJ_TYPE_DURB_ID,
				PRDR_PGM_PYMT_LMT_ADJ_TYPE_RS.DATA_EFF_STRT_DT,
				PRDR_PGM_PYMT_LMT_ADJ_TYPE_RS.DATA_EFF_END_DT,
				PRDR_PGM_PYMT_LMT_ADJ_TYPE_RS.DATA_STAT_CD SRC_DATA_STAT_CD,
				PRDR_PGM_PYMT_LMT_ADJ_TYPE_RS.PRDR_PYMT_LMT_ADJ_TYPE_CD PYMT_LMT_ADJ_TYPE_CD,
				PRDR_PGM_PYMT_LMT_ADJ_TYPE_RS.PRDR_PYMT_LMT_ADJ_TYPE_NM PYMT_LMT_ADJ_TYPE_NM
		FROM            EDV.PRDR_PGM_PYMT_LMT_ADJ_TYPE_RS
				LEFT JOIN EDV.PRDR_PGM_PYMT_LMT_ADJ_TYPE_RH ON PRDR_PGM_PYMT_LMT_ADJ_TYPE_RH.PRDR_PYMT_LMT_ADJ_TYPE_CD = PRDR_PGM_PYMT_LMT_ADJ_TYPE_RS.PRDR_PYMT_LMT_ADJ_TYPE_CD
		WHERE           PRDR_PGM_PYMT_LMT_ADJ_TYPE_RS.DATA_EFF_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
			AND     (PRDR_PGM_PYMT_LMT_ADJ_TYPE_RS.DATA_EFF_STRT_DT) <= TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
			AND     PRDR_PGM_PYMT_LMT_ADJ_TYPE_RH.DURB_ID IS NOT NULL