SELECT 
dv.PYMT_ATRB_RDN_TYPE_DURB_ID,
dv.CRE_DT,
dv.LAST_CHG_DT,
dv.DATA_STAT_CD,
dv.PYMT_ATRB_RDN_TYPE_CD,
dv.PYMT_ATRB_RDN_TYPE_DESC,
dv.PYMT_ATRB_RDN_CAT_CD,
dv.PCT_BASE_RDN_IND,
dv.SRC_CRE_DT,
dv.SRC_LAST_CHG_DT,
dv.SRC_CRE_USER_NM,
dv.SRC_LAST_CHG_USER_NM,
CASE 
    WHEN dv.PYMT_ATRB_RDN_TYPE_DURB_ID > 0 THEN 0
    ELSE 1 
END DEF_ERR_IND,
dv.PYMT_ATRB_RDN_TYPE_CD BUS_KEY, 
('PYMT_ATRB_RDN_TYPE_CD:'||dv.PYMT_ATRB_RDN_TYPE_CD) BUS_KEY_ERR 
FROM (
SELECT dv_all.* FROM (
SELECT 
h.DURB_ID PYMT_ATRB_RDN_TYPE_DURB_ID,
TO_TIMESTAMP ('{ETL_START_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF') CRE_DT, 
TO_TIMESTAMP ('{ETL_START_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF') LAST_CHG_DT, 
'A' DATA_STAT_CD,
h.PYMT_ATRB_RDN_TYPE_CD PYMT_ATRB_RDN_TYPE_CD,
s.PYMT_ATRB_RDN_TYPE_NM PYMT_ATRB_RDN_TYPE_DESC,
s.PYMT_ATRB_RDN_CAT_CD PYMT_ATRB_RDN_CAT_CD,
s.PCT_BASE_RDN_IND PCT_BASE_RDN_IND,
s.SRC_CRE_DT SRC_CRE_DT,
s.SRC_LAST_CHG_DT SRC_LAST_CHG_DT,
s.SRC_CRE_USER_NM SRC_CRE_USER_NM,
s.SRC_LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
FROM (SELECT * FROM EDV.PYMT_ATRB_RDN_TYPE_RH WHERE (LOAD_DT) <= TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD') AND DATA_SRC_NM <> 'SYSGEN') h
LEFT JOIN EDV.PYMT_ATRB_RDN_TYPE_RS s                               
ON (h.PYMT_ATRB_RDN_TYPE_CD = s.PYMT_ATRB_RDN_TYPE_CD 
    AND (s.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
    AND (s.DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
   )
) dv_all
) dv
 
LEFT JOIN pymt_dm_stg.PYMT_ATRB_RDN_TYPE_DIM dm
ON (
/*dimension AK fields*/ 
(dv.PYMT_ATRB_RDN_TYPE_CD,'EDW DEFAULT') = (dm.PYMT_ATRB_RDN_TYPE_CD,'EDW DEFAULT')
AND dm.DATA_STAT_CD = 'A' 
)
WHERE
 (
/*separated by OR for other AK fields of dimension table*/ 
dm.PYMT_ATRB_RDN_TYPE_CD IS NULL
)
ORDER BY BUS_KEY,dv.SRC_LAST_CHG_DT desc