MERGE into
EDV.ARC_PLC_ELG_DTER_RS dv
using(select distinct
coalesce(DMN_VAL.DMN_CHAR_VAL, '[NULL IN SOURCE]') ARC_PLC_ELG_DTER_CD,
coalesce(DMN_VAL.DMN_VAL_ID, '-1') DMN_VAL_ID,
DMN_VAL.LOAD_DT LOAD_DT,
DMN_VAL.CDC_DT DATA_EFF_STRT_DT,
DMN_VAL.DATA_SRC_NM DATA_SRC_NM,
DMN_VAL.CRE_DT SRC_CRE_DT,
DMN_VAL.LAST_CHG_DT SRC_LAST_CHG_DT,
DMN_VAL.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
DMN_VAL.DMN_VAL_NM ARC_PLC_ELG_DTER_NM,
DMN_VAL.DMN_VAL_DESC ARC_PLC_ELG_DTER_DESC,
DMN_VAL.DMN_ID DMN_ID,
DMN_VAL.DPLY_SEQ_NBR DPLY_SEQ_NBR,
DMN_VAL.DFLT_VAL_IND DFLT_VAL_IND,
MD5(trim(both DMN_VAL.DMN_CHAR_VAL)||'~~'||DMN_VAL.DMN_VAL_ID||'~~'||to_char(DMN_VAL.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(DMN_VAL.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both DMN_VAL.LAST_CHG_USER_NM)||'~~'||trim(both DMN_VAL.DMN_VAL_NM)||'~~'||trim(both DMN_VAL.DMN_VAL_DESC)||'~~'||DMN_VAL.DMN_ID||'~~'||DMN_VAL.DPLY_SEQ_NBR||'~~'||trim(both DMN_VAL.DFLT_VAL_IND)) HASH_DIF
FROM SQL_FARM_RCD_STG.DMN_VAL
WHERE DMN_VAL.DMN_ID in (59)
and DMN_VAL.cdc_oper_cd IN ('I','UN')
order by DMN_VAL.CDC_DT
) stg 
 on ( 
coalesce(stg.DMN_VAL_ID,0) = coalesce(dv.DMN_VAL_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;