SELECT 
record_reference_component_type.record_reference_component_type_identifier RCD_REF_CPNT_TYPE_ID,
record_reference_component_type.creation_date CRE_DT,
record_reference_component_type.creation_user_name CRE_USER_NM,
record_reference_component_type.last_change_date LAST_CHG_DT,
record_reference_component_type.last_change_user_name LAST_CHG_USER_NM,
record_reference_component_type.data_status_code DATA_STAT_CD,
record_reference_component_type.record_reference_identification_type_code RCD_REF_ID_TYPE_CD,
record_reference_component_type.embedded_data_starting_byte_count EMBEDDED_DATA_STRT_BYTE_CT,
record_reference_component_type.data_element_byte_count DATA_ELE_BYTE_CT,
record_reference_component_type.display_indicator DPLY_IND,
record_reference_component_type.record_reference_component_type_name RCD_REF_CPNT_TYPE_NM,
'I' CDC_OPER_CD,
1 AS row_num_part
FROM `fsa-{env}-sbsd-cdc`.`record_reference_component_type`
