SELECT PRAC_TECH_PRAC_ID,
TECH_PRAC_ID,
CNSV_PRAC_ID,
CNSV_PRAC_CD,
TECH_PRAC_CD,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT PRAC_TECH_PRAC_ID,
TECH_PRAC_ID,
CNSV_PRAC_ID,
CNSV_PRAC_CD,
TECH_PRAC_CD,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
PRAC_TECH_PRAC_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
practice_technical_practice.PRAC_TECH_PRAC_ID PRAC_TECH_PRAC_ID,
practice_technical_practice.TECH_PRAC_ID TECH_PRAC_ID,
practice_technical_practice.CNSV_PRAC_ID CNSV_PRAC_ID,
CONSERVATION_PRACTICE.CNSV_PRAC_CD CNSV_PRAC_CD,
technical_practice.TECH_PRAC_CD TECH_PRAC_CD,
practice_technical_practice.DATA_STAT_CD DATA_STAT_CD,
practice_technical_practice.CRE_DT CRE_DT,
practice_technical_practice.LAST_CHG_DT LAST_CHG_DT,
practice_technical_practice.LAST_CHG_USER_NM LAST_CHG_USER_NM,
PRACTICE_TECHNICAL_PRACTICE.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."PRACTICE_TECHNICAL_PRACTICE" PRACTICE_TECHNICAL_PRACTICE 
LEFT JOIN "fsa-{env}-cnsv".TECHNICAL_PRACTICE TECHNICAL_PRACTICE ON (PRACTICE_TECHNICAL_PRACTICE.TECH_PRAC_ID = TECHNICAL_PRACTICE.TECH_PRAC_ID) 
LEFT JOIN "fsa-{env}-cnsv".CONSERVATION_PRACTICE CONSERVATION_PRACTICE ON (PRACTICE_TECHNICAL_PRACTICE.CNSV_PRAC_ID = CONSERVATION_PRACTICE.CNSV_PRAC_ID) 
WHERE PRACTICE_TECHNICAL_PRACTICE.OP <> 'D' AND
PRACTICE_TECHNICAL_PRACTICE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
practice_technical_practice.PRAC_TECH_PRAC_ID PRAC_TECH_PRAC_ID,
practice_technical_practice.TECH_PRAC_ID TECH_PRAC_ID,
practice_technical_practice.CNSV_PRAC_ID CNSV_PRAC_ID,
CONSERVATION_PRACTICE.CNSV_PRAC_CD CNSV_PRAC_CD,
technical_practice.TECH_PRAC_CD TECH_PRAC_CD,
practice_technical_practice.DATA_STAT_CD DATA_STAT_CD,
practice_technical_practice.CRE_DT CRE_DT,
practice_technical_practice.LAST_CHG_DT LAST_CHG_DT,
practice_technical_practice.LAST_CHG_USER_NM LAST_CHG_USER_NM,
TECHNICAL_PRACTICE.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."TECHNICAL_PRACTICE" TECHNICAL_PRACTICE 
JOIN "fsa-{env}-cnsv".PRACTICE_TECHNICAL_PRACTICE PRACTICE_TECHNICAL_PRACTICE ON (PRACTICE_TECHNICAL_PRACTICE.TECH_PRAC_ID = TECHNICAL_PRACTICE.TECH_PRAC_ID) 
LEFT JOIN "fsa-{env}-cnsv".CONSERVATION_PRACTICE CONSERVATION_PRACTICE ON (PRACTICE_TECHNICAL_PRACTICE.CNSV_PRAC_ID = CONSERVATION_PRACTICE.CNSV_PRAC_ID) 
WHERE TECHNICAL_PRACTICE.OP <> 'D' AND
TECHNICAL_PRACTICE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
practice_technical_practice.PRAC_TECH_PRAC_ID PRAC_TECH_PRAC_ID,
practice_technical_practice.TECH_PRAC_ID TECH_PRAC_ID,
practice_technical_practice.CNSV_PRAC_ID CNSV_PRAC_ID,
CONSERVATION_PRACTICE.CNSV_PRAC_CD CNSV_PRAC_CD,
technical_practice.TECH_PRAC_CD TECH_PRAC_CD,
practice_technical_practice.DATA_STAT_CD DATA_STAT_CD,
practice_technical_practice.CRE_DT CRE_DT,
practice_technical_practice.LAST_CHG_DT LAST_CHG_DT,
practice_technical_practice.LAST_CHG_USER_NM LAST_CHG_USER_NM,
CONSERVATION_PRACTICE.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."CONSERVATION_PRACTICE" CONSERVATION_PRACTICE 
JOIN "fsa-{env}-cnsv".PRACTICE_TECHNICAL_PRACTICE PRACTICE_TECHNICAL_PRACTICE ON (PRACTICE_TECHNICAL_PRACTICE.CNSV_PRAC_ID = CONSERVATION_PRACTICE.CNSV_PRAC_ID) 
LEFT JOIN "fsa-{env}-cnsv".TECHNICAL_PRACTICE TECHNICAL_PRACTICE ON (PRACTICE_TECHNICAL_PRACTICE.TECH_PRAC_ID = TECHNICAL_PRACTICE.TECH_PRAC_ID) 
WHERE CONSERVATION_PRACTICE.OP <> 'D' AND
CONSERVATION_PRACTICE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
practice_technical_practice.PRAC_TECH_PRAC_ID PRAC_TECH_PRAC_ID,
practice_technical_practice.TECH_PRAC_ID TECH_PRAC_ID,
practice_technical_practice.CNSV_PRAC_ID CNSV_PRAC_ID,
NULL CNSV_PRAC_CD,
NULL TECH_PRAC_CD,
practice_technical_practice.DATA_STAT_CD DATA_STAT_CD,
practice_technical_practice.CRE_DT CRE_DT,
practice_technical_practice.LAST_CHG_DT LAST_CHG_DT,
practice_technical_practice.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".practice_technical_practice practice_technical_practice
WHERE OP = 'D'
AND dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}' 
)