SELECT TECH_PRAC_CD,
TECH_PRAC_ID,
UOM_ID,
TECH_PRAC_DESC,
UOM_NM,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
GENERIC_IND,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT TECH_PRAC_CD,
TECH_PRAC_ID,
UOM_ID,
TECH_PRAC_DESC,
UOM_NM,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
GENERIC_IND,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
TECH_PRAC_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
technical_practice.TECH_PRAC_CD TECH_PRAC_CD,
technical_practice.TECH_PRAC_ID TECH_PRAC_ID,
technical_practice.UOM_ID UOM_ID,
technical_practice.TECH_PRAC_DESC TECH_PRAC_DESC,
UNIT_OF_MEASURE.UOM_NM UOM_NM,
technical_practice.DATA_STAT_CD DATA_STAT_CD,
technical_practice.CRE_DT CRE_DT,
technical_practice.LAST_CHG_DT LAST_CHG_DT,
technical_practice.LAST_CHG_USER_NM LAST_CHG_USER_NM,
technical_practice.GENERIC_IND GENERIC_IND,
TECHNICAL_PRACTICE.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."TECHNICAL_PRACTICE" TECHNICAL_PRACTICE 
LEFT JOIN "fsa-{env}-cnsv".UNIT_OF_MEASURE UNIT_OF_MEASURE ON (TECHNICAL_PRACTICE.UOM_ID = UNIT_OF_MEASURE.UOM_ID) 
WHERE TECHNICAL_PRACTICE.OP <> 'D' AND
TECHNICAL_PRACTICE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
technical_practice.TECH_PRAC_CD TECH_PRAC_CD,
technical_practice.TECH_PRAC_ID TECH_PRAC_ID,
technical_practice.UOM_ID UOM_ID,
technical_practice.TECH_PRAC_DESC TECH_PRAC_DESC,
UNIT_OF_MEASURE.UOM_NM UOM_NM,
technical_practice.DATA_STAT_CD DATA_STAT_CD,
technical_practice.CRE_DT CRE_DT,
technical_practice.LAST_CHG_DT LAST_CHG_DT,
technical_practice.LAST_CHG_USER_NM LAST_CHG_USER_NM,
technical_practice.GENERIC_IND GENERIC_IND,
UNIT_OF_MEASURE.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."UNIT_OF_MEASURE" UNIT_OF_MEASURE 
JOIN "fsa-{env}-cnsv".TECHNICAL_PRACTICE TECHNICAL_PRACTICE ON (TECHNICAL_PRACTICE.UOM_ID = UNIT_OF_MEASURE.UOM_ID) 
WHERE UNIT_OF_MEASURE.OP <> 'D' AND
UNIT_OF_MEASURE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
technical_practice.TECH_PRAC_CD TECH_PRAC_CD,
technical_practice.TECH_PRAC_ID TECH_PRAC_ID,
technical_practice.UOM_ID UOM_ID,
technical_practice.TECH_PRAC_DESC TECH_PRAC_DESC,
NULL UOM_NM,
technical_practice.DATA_STAT_CD DATA_STAT_CD,
technical_practice.CRE_DT CRE_DT,
technical_practice.LAST_CHG_DT LAST_CHG_DT,
technical_practice.LAST_CHG_USER_NM LAST_CHG_USER_NM,
technical_practice.GENERIC_IND GENERIC_IND,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".technical_practice technical_practice
WHERE OP = 'D'
AND dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}' 
)