SELECT PGM_YR,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
TR_NBR,
OFR_SCNR_NM,
GRSLD_RANK_FCTR_IDN,
GRSLD_RANK_SFCTR_IDN,
GRSLD_RANK_SFCTR_QSTN_IDN,
USER_RESP_IND,
GRSLD_RANK_SFCTR_USER_RESP_ID,
GRSLD_RANK_SFCTR_QSTN_ID,
GRSLD_RANK_SFCTR_RSLT_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
CRE_USER_NM,
LAST_CHG_USER_NM,
CDC_OPER_CD,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT PGM_YR,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
TR_NBR,
OFR_SCNR_NM,
GRSLD_RANK_FCTR_IDN,
GRSLD_RANK_SFCTR_IDN,
GRSLD_RANK_SFCTR_QSTN_IDN,
USER_RESP_IND,
GRSLD_RANK_SFCTR_USER_RESP_ID,
GRSLD_RANK_SFCTR_QSTN_ID,
GRSLD_RANK_SFCTR_RSLT_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
CRE_USER_NM,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
GRSLD_RANK_SFCTR_USER_RESP_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_IDN GRSLD_RANK_SFCTR_QSTN_IDN,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.USER_RESP_IND USER_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_USER_RESP_ID GRSLD_RANK_SFCTR_USER_RESP_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID GRSLD_RANK_SFCTR_QSTN_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID GRSLD_RANK_SFCTR_RSLT_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE" GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_QUESTION
ON GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR 
ON GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR 
ON GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP
ON EWT14SGNP.SGNP_ID = GRASSLAND_RANKING_FACTOR.SGNP_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_RESULT 
ON GRASSLAND_RANKING_SUBFACTOR_RESULT.GRSLD_RANK_SFCTR_RSLT_ID = GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID
LEFT JOIN   "fsa-{env}-cnsv".CRP_GRASSLAND_OFFER_SCENARIO 
ON GRASSLAND_RANKING_SUBFACTOR_RESULT.OFR_SCNR_ID = CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT40OFRSC 
ON CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID
WHERE GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.OP <> 'D'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_IDN GRSLD_RANK_SFCTR_QSTN_IDN,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.USER_RESP_IND USER_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_USER_RESP_ID GRSLD_RANK_SFCTR_USER_RESP_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID GRSLD_RANK_SFCTR_QSTN_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID GRSLD_RANK_SFCTR_RSLT_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_QUESTION.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_SUBFACTOR_QUESTION" GRASSLAND_RANKING_SUBFACTOR_QUESTION
JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE
ON GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR 
ON GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR 
ON GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID= GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP 
ON EWT14SGNP.SGNP_ID = GRASSLAND_RANKING_FACTOR.SGNP_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_RESULT 
ON GRASSLAND_RANKING_SUBFACTOR_RESULT.GRSLD_RANK_SFCTR_RSLT_ID = GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID
LEFT JOIN   "fsa-{env}-cnsv".CRP_GRASSLAND_OFFER_SCENARIO 
ON GRASSLAND_RANKING_SUBFACTOR_RESULT.OFR_SCNR_ID = CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT40OFRSC 
ON CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID
WHERE GRASSLAND_RANKING_SUBFACTOR_QUESTION.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR_QUESTION.OP <> 'D'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_IDN GRSLD_RANK_SFCTR_QSTN_IDN,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.USER_RESP_IND USER_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_USER_RESP_ID GRSLD_RANK_SFCTR_USER_RESP_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID GRSLD_RANK_SFCTR_QSTN_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID GRSLD_RANK_SFCTR_RSLT_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_SUBFACTOR.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_SUBFACTOR" GRASSLAND_RANKING_SUBFACTOR
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_QUESTION 
ON GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_ID
JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE
ON GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR 
ON GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP 
ON EWT14SGNP.SGNP_ID = GRASSLAND_RANKING_FACTOR.SGNP_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_RESULT 
ON GRASSLAND_RANKING_SUBFACTOR_RESULT.GRSLD_RANK_SFCTR_RSLT_ID = GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID
LEFT JOIN   "fsa-{env}-cnsv".CRP_GRASSLAND_OFFER_SCENARIO 
ON GRASSLAND_RANKING_SUBFACTOR_RESULT.OFR_SCNR_ID = CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT40OFRSC 
ON CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID
WHERE GRASSLAND_RANKING_SUBFACTOR.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR.OP <> 'D'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_IDN GRSLD_RANK_SFCTR_QSTN_IDN,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.USER_RESP_IND USER_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_USER_RESP_ID GRSLD_RANK_SFCTR_USER_RESP_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID GRSLD_RANK_SFCTR_QSTN_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID GRSLD_RANK_SFCTR_RSLT_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_FACTOR.OP,
4 AS TBL_PRIORITY
FROM   "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_FACTOR" GRASSLAND_RANKING_FACTOR
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR 
ON GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_QUESTION 
ON GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_ID
JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE 
ON GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT14SGNP 
ON EWT14SGNP.SGNP_ID = GRASSLAND_RANKING_FACTOR.SGNP_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_RESULT 
ON GRASSLAND_RANKING_SUBFACTOR_RESULT.GRSLD_RANK_SFCTR_RSLT_ID = GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID
LEFT JOIN   "fsa-{env}-cnsv".CRP_GRASSLAND_OFFER_SCENARIO 
ON GRASSLAND_RANKING_SUBFACTOR_RESULT.OFR_SCNR_ID = CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID
LEFT JOIN   "fsa-{env}-cnsv".EWT40OFRSC 
ON CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID
WHERE GRASSLAND_RANKING_FACTOR.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_FACTOR.OP <> 'D'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_IDN GRSLD_RANK_SFCTR_QSTN_IDN,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.USER_RESP_IND USER_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_USER_RESP_ID GRSLD_RANK_SFCTR_USER_RESP_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID GRSLD_RANK_SFCTR_QSTN_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID GRSLD_RANK_SFCTR_RSLT_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT14SGNP.OP,
5 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."EWT14SGNP" EWT14SGNP
Left Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR 
ON EWT14SGNP.SGNP_ID = GRASSLAND_RANKING_FACTOR.SGNP_ID
Left Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR 
On GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID = GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_QUESTION 
On GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_ID
Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE 
On GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_ID
Left Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_RESULT 
On GRASSLAND_RANKING_SUBFACTOR_RESULT.GRSLD_RANK_SFCTR_RSLT_ID = GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID
Left Join   "fsa-{env}-cnsv".CRP_GRASSLAND_OFFER_SCENARIO 
On GRASSLAND_RANKING_SUBFACTOR_RESULT.OFR_SCNR_ID = CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID
Left Join   "fsa-{env}-cnsv".EWT40OFRSC 
On CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID
WHERE EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT14SGNP.OP <> 'D'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_IDN GRSLD_RANK_SFCTR_QSTN_IDN,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.USER_RESP_IND USER_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_USER_RESP_ID GRSLD_RANK_SFCTR_USER_RESP_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID GRSLD_RANK_SFCTR_QSTN_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID GRSLD_RANK_SFCTR_RSLT_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_RESULT.OP,
6 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."GRASSLAND_RANKING_SUBFACTOR_RESULT" GRASSLAND_RANKING_SUBFACTOR_RESULT
Left Join   "fsa-{env}-cnsv".CRP_GRASSLAND_OFFER_SCENARIO 
On GRASSLAND_RANKING_SUBFACTOR_RESULT.OFR_SCNR_ID = CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID
Left Join   "fsa-{env}-cnsv".EWT40OFRSC 
On CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID
Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE 
On GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID = GRASSLAND_RANKING_SUBFACTOR_RESULT.GRSLD_RANK_SFCTR_RSLT_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_QUESTION 
On GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_ID = GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID
Left Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR 
On GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_ID
Left Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR 
On GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID= GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID
LEFT Join   "fsa-{env}-cnsv".EWT14SGNP 
ON EWT14SGNP.SGNP_ID = GRASSLAND_RANKING_FACTOR.SGNP_ID
WHERE GRASSLAND_RANKING_SUBFACTOR_RESULT.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR_RESULT.OP <> 'D'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_IDN GRSLD_RANK_SFCTR_QSTN_IDN,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.USER_RESP_IND USER_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_USER_RESP_ID GRSLD_RANK_SFCTR_USER_RESP_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID GRSLD_RANK_SFCTR_QSTN_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID GRSLD_RANK_SFCTR_RSLT_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
CRP_GRASSLAND_OFFER_SCENARIO.OP,
7 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."CRP_GRASSLAND_OFFER_SCENARIO" CRP_GRASSLAND_OFFER_SCENARIO
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_RESULT 
On GRASSLAND_RANKING_SUBFACTOR_RESULT.OFR_SCNR_ID = CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID
Left Join   "fsa-{env}-cnsv".EWT40OFRSC 
On CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID
Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE 
On GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID = GRASSLAND_RANKING_SUBFACTOR_RESULT.GRSLD_RANK_SFCTR_RSLT_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_QUESTION 
On GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_ID = GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID
Left Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR
On GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_ID
Left Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR 
On GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID= GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID
LEFT Join   "fsa-{env}-cnsv".EWT14SGNP 
ON EWT14SGNP.SGNP_ID = GRASSLAND_RANKING_FACTOR.SGNP_ID
WHERE CRP_GRASSLAND_OFFER_SCENARIO.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and CRP_GRASSLAND_OFFER_SCENARIO.OP <> 'D'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_IDN GRSLD_RANK_FCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_IDN GRSLD_RANK_SFCTR_IDN,
GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_IDN GRSLD_RANK_SFCTR_QSTN_IDN,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.USER_RESP_IND USER_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_USER_RESP_ID GRSLD_RANK_SFCTR_USER_RESP_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID GRSLD_RANK_SFCTR_QSTN_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID GRSLD_RANK_SFCTR_RSLT_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT40OFRSC.OP,
8 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."EWT40OFRSC" EWT40OFRSC
Left Join   "fsa-{env}-cnsv".CRP_GRASSLAND_OFFER_SCENARIO 
On CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID= EWT40OFRSC.OFR_SCNR_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_RESULT 
On GRASSLAND_RANKING_SUBFACTOR_RESULT.OFR_SCNR_ID = CRP_GRASSLAND_OFFER_SCENARIO.OFR_SCNR_ID
Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE 
On GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID = GRASSLAND_RANKING_SUBFACTOR_RESULT.GRSLD_RANK_SFCTR_RSLT_ID
LEFT JOIN   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR_QUESTION 
On GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_QSTN_ID = GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID
Left Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_SUBFACTOR 
On GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_SFCTR_ID = GRASSLAND_RANKING_SUBFACTOR_QUESTION.GRSLD_RANK_SFCTR_ID
Left Join   "fsa-{env}-cnsv".GRASSLAND_RANKING_FACTOR 
On GRASSLAND_RANKING_FACTOR.GRSLD_RANK_FCTR_ID= GRASSLAND_RANKING_SUBFACTOR.GRSLD_RANK_FCTR_ID
LEFT Join   "fsa-{env}-cnsv".EWT14SGNP 
ON EWT14SGNP.SGNP_ID = GRASSLAND_RANKING_FACTOR.SGNP_ID
WHERE EWT40OFRSC.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and EWT40OFRSC.OP <> 'D'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
NULL PGM_YR,
NULL ADM_ST_FSA_CD,
NULL ADM_CNTY_FSA_CD,
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL TR_NBR,
NULL OFR_SCNR_NM,
NULL GRSLD_RANK_FCTR_IDN,
NULL GRSLD_RANK_SFCTR_IDN,
NULL GRSLD_RANK_SFCTR_QSTN_IDN,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.USER_RESP_IND USER_RESP_IND,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_USER_RESP_ID GRSLD_RANK_SFCTR_USER_RESP_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_QSTN_ID GRSLD_RANK_SFCTR_QSTN_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.GRSLD_RANK_SFCTR_RSLT_ID GRSLD_RANK_SFCTR_RSLT_ID,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.DATA_STAT_CD DATA_STAT_CD,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_DT CRE_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_DT LAST_CHG_DT,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.CRE_USER_NM CRE_USER_NM,
GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE
WHERE GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'
and GRASSLAND_RANKING_SUBFACTOR_USER_RESPONSE.OP = 'D'
)