Merge into
EDV.MIDAS_FARM_XFR_LS dv
using(select DISTINCT MD5(MD5(upper(coalesce(MIDAS_FARM_TR_CHG.PRNT_ST_FSA_CD,'--') ||'~~'|| coalesce(MIDAS_FARM_TR_CHG.PRNT_CNTY_FSA_CD,'--') ||'~~'|| coalesce(MIDAS_FARM_TR_CHG.PRNT_FARM_NBR,'--')))||'~~'||MD5(upper(coalesce(MIDAS_FARM_TR_CHG.RSLT_ST_FSA_CD,'--') ||'~~'|| coalesce(MIDAS_FARM_TR_CHG.RSLT_CNTY_FSA_CD,'--') ||'~~'|| coalesce(MIDAS_FARM_TR_CHG.RSLT_FARM_NBR,'--')))) FARM_RCON_L_ID,
MIDAS_FARM_TR_CHG.MIDAS_FARM_TR_CHG_ID MIDAS_FARM_TR_CHG_ID,
MIDAS_FARM_TR_CHG.LOAD_DT LOAD_DT,
MIDAS_FARM_TR_CHG.CDC_DT DATA_EFF_STRT_DT,
MIDAS_FARM_TR_CHG.DATA_SRC_NM DATA_SRC_NM,
MIDAS_FARM_TR_CHG.DATA_STAT_CD DATA_STAT_CD,
MIDAS_FARM_TR_CHG.CRE_DT SRC_CRE_DT,
MIDAS_FARM_TR_CHG.CRE_USER_NM SRC_CRE_USER_NM,
MIDAS_FARM_TR_CHG.LAST_CHG_DT SRC_LAST_CHG_DT,
MIDAS_FARM_TR_CHG.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,
MIDAS_FARM_TR_CHG.FARM_CHG_TYPE_ID SRC_FARM_CHG_TYPE_ID,
FARM_CHG_TYPE_RS.DMN_VAL_NM FARM_CHG_TYPE_NM,
MIDAS_FARM_TR_CHG.PRNT_ST_FSA_CD PRNT_ST_FSA_CD,
MIDAS_FARM_TR_CHG.PRNT_CNTY_FSA_CD PRNT_CNTY_FSA_CD,
MIDAS_FARM_TR_CHG.PRNT_FARM_NBR PRNT_FARM_NBR,
MIDAS_FARM_TR_CHG.RSLT_ST_FSA_CD RSLT_ST_FSA_CD,
MIDAS_FARM_TR_CHG.RSLT_CNTY_FSA_CD RSLT_CNTY_FSA_CD,
MIDAS_FARM_TR_CHG.RSLT_FARM_NBR RSLT_FARM_NBR,
MIDAS_FARM_TR_CHG.TM_PRD_ID TM_PRD_ID,
MIDAS_FARM_TR_CHG.RCON_SEQ_NBR RCON_SEQ_NBR,
MIDAS_FARM_TR_CHG.RCON_INIT_DT RCON_INIT_DT,
MIDAS_FARM_TR_CHG.RCON_APVL_DT RCON_APVL_DT,
MIDAS_FARM_TR_CHG.TM_PRD_NM TM_PRD_NM,
MIDAS_FARM_TR_CHG.CDC_OPER_CD,
MD5(upper(coalesce(MIDAS_FARM_TR_CHG.PRNT_FARM_NBR,'--')||'~~'||coalesce(MIDAS_FARM_TR_CHG.PRNT_ST_FSA_CD,'--')||'~~'||coalesce(MIDAS_FARM_TR_CHG.PRNT_CNTY_FSA_CD,'--'))||'~~'||upper(coalesce(MIDAS_FARM_TR_CHG.RSLT_FARM_NBR,'--')||'~~'||coalesce(MIDAS_FARM_TR_CHG.RSLT_ST_FSA_CD,'--')||'~~'||coalesce(MIDAS_FARM_TR_CHG.RSLT_CNTY_FSA_CD,'--'))||'~~'||MIDAS_FARM_TR_CHG.MIDAS_FARM_TR_CHG_ID||'~~'||trim(both MIDAS_FARM_TR_CHG.DATA_STAT_CD)||'~~'||to_char(MIDAS_FARM_TR_CHG.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both MIDAS_FARM_TR_CHG.CRE_USER_NM)||'~~'||to_char(MIDAS_FARM_TR_CHG.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both MIDAS_FARM_TR_CHG.LAST_CHG_USER_NM)||'~~'||MIDAS_FARM_TR_CHG.FARM_CHG_TYPE_ID||'~~'||FARM_CHG_TYPE_RS.DMN_VAL_NM||'~~'||trim(both MIDAS_FARM_TR_CHG.PRNT_ST_FSA_CD)||'~~'||trim(both MIDAS_FARM_TR_CHG.PRNT_CNTY_FSA_CD)||'~~'||trim(both MIDAS_FARM_TR_CHG.PRNT_FARM_NBR)||'~~'||trim(both MIDAS_FARM_TR_CHG.RSLT_ST_FSA_CD)||'~~'||trim(both MIDAS_FARM_TR_CHG.RSLT_CNTY_FSA_CD)||'~~'||trim(both MIDAS_FARM_TR_CHG.RSLT_FARM_NBR)||MIDAS_FARM_TR_CHG.TM_PRD_ID||trim(both MIDAS_FARM_TR_CHG.RCON_SEQ_NBR)||to_char(MIDAS_FARM_TR_CHG.RCON_INIT_DT,'YYYY-MM-DD HH24:MI:SS.US')||to_char(MIDAS_FARM_TR_CHG.RCON_APVL_DT,'YYYY-MM-DD HH24:MI:SS.US')||trim(both MIDAS_FARM_TR_CHG.TM_PRD_NM)) HASH_DIF
FROM SQL_FARM_RCD_STG.MIDAS_FARM_TR_CHG 
LEFT JOIN(select * from EDV.FARM_CHG_TYPE_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FARM_CHG_TYPE_RS 
ON (MIDAS_FARM_TR_CHG.FARM_CHG_TYPE_ID = FARM_CHG_TYPE_RS.DMN_VAL_ID)
where MIDAS_FARM_TR_CHG.FARM_CHG_TYPE_ID = 1141 and MIDAS_FARM_TR_CHG.CDC_OPER_CD='D'
--and date_trunc('day', MIDAS_FARM_TR_CHG.CDC_DT) = date_trunc('day', TO_TIMESTAMP('<DATA_EFF_STRT_DT>', 'YYYY-MM-DD HH24:MI:SS.FF'))
--and MIDAS_FARM_TR_CHG.LOAD_DT = TO_TIMESTAMP('<LOAD_DT>', 'YYYY-MM-DD HH24:MI:SS.FF')
order by MIDAS_FARM_TR_CHG.CDC_DT)
stg
 on ( 
coalesce(stg.MIDAS_FARM_TR_CHG_ID,0) = coalesce(dv.MIDAS_FARM_TR_CHG_ID,0)
 )  WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN
INSERT(
FARM_RCON_L_ID,
MIDAS_FARM_TR_CHG_ID,
LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_CRE_USER_NM,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
SRC_FARM_CHG_TYPE_ID,
FARM_CHG_TYPE_NM,
PRNT_ST_FSA_CD,
PRNT_CNTY_FSA_CD,
PRNT_FARM_NBR,
RSLT_ST_FSA_CD,
RSLT_CNTY_FSA_CD,
RSLT_FARM_NBR,
TM_PRD_ID,
RCON_SEQ_NBR,
RCON_INIT_DT,
RCON_APVL_DT,
TM_PRD_NM,
DATA_EFF_END_DT,
LOAD_END_DT,
HASH_DIF)
VALUES (
stg.FARM_RCON_L_ID,
stg.MIDAS_FARM_TR_CHG_ID,stg.LOAD_DT,stg.DATA_EFF_STRT_DT,
stg.DATA_SRC_NM,stg.DATA_STAT_CD,stg.SRC_CRE_DT,stg.SRC_CRE_USER_NM,
stg.SRC_LAST_CHG_DT,stg.SRC_LAST_CHG_USER_NM,stg.SRC_FARM_CHG_TYPE_ID,
stg.FARM_CHG_TYPE_NM,stg.PRNT_ST_FSA_CD,stg.PRNT_CNTY_FSA_CD,stg.PRNT_FARM_NBR,
stg.RSLT_ST_FSA_CD,stg.RSLT_CNTY_FSA_CD,stg.RSLT_FARM_NBR,
stg.TM_PRD_ID,stg.RCON_SEQ_NBR,stg.RCON_INIT_DT,stg.RCON_APVL_DT,stg.TM_PRD_NM,
stg.DATA_EFF_STRT_DT,stg.LOAD_DT,
stg.HASH_DIF
);