INSERT  into
EDV.CLU_YR_LS(
FARM_TR_L_ID,
CLU_YR_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
SRC_CRE_DT,
TR_YR_ID,
CLU_ALT_ID,
FLD_NBR,
LOC_CNTY_FSA_CD,
LOC_ST_FSA_CD,
ST_ANSI_CD,
CNTY_ANSI_CD,
CONG_DIST_CD,
SRC_LAND_CLS_ID,
LAND_CLS_NM,
CLU_ACRG,
SRC_HEL_STAT_ID,
HEL_STAT_NM,
CPLD_IND_3CM,
CLU_DESC,
CRP_CTR_NBR,
CRP_CTR_EXPR_DT,
SRC_CNSV_PRAC_ID,
CNSV_PRAC_NM,
NTV_SOD_CVSN_DT,
SOD_CVSN_CROP_YR_1,
SOD_CVSN_CROP_YR_2,
SOD_CVSN_CROP_YR_3,
SOD_CVSN_CROP_YR_4,
PGM_YR, 
DATA_EFF_END_DT, 
LOAD_END_DT, 
HASH_DIF
)
(SELECT 
	stg.* 
from (
SELECT DISTINCT 
		MD5(MD5(upper(coalesce(CLU_YR.ST_FSA_CD,'--')||'~~'||coalesce(CLU_YR.CNTY_FSA_CD,'--')||'~~'||coalesce(CLU_YR.FARM_NBR,'--')))||'~~'||MD5(upper(coalesce(CLU_YR.ST_FSA_CD,'--')||'~~'||coalesce(CLU_YR.CNTY_FSA_CD,'--')||'~~'||coalesce((CLU_YR.TR_NBR)::numeric ,-1)))) as FARM_TR_L_ID
		, CLU_YR.CLU_YR_ID CLU_YR_ID
		, CLU_YR.LOAD_DT LOAD_DT
		, CLU_YR.CDC_DT DATA_EFF_STRT_DT
		, CLU_YR.DATA_SRC_NM DATA_SRC_NM
		, CLU_YR.DATA_STAT_CD DATA_STAT_CD
		, CLU_YR.LAST_CHG_DT SRC_LAST_CHG_DT
		, CLU_YR.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
		, CLU_YR.CRE_DT SRC_CRE_DT
		, CLU_YR.TR_YR_ID TR_YR_ID
		, CLU_YR.CLU_ALT_ID CLU_ALT_ID
		, CLU_YR.FLD_NBR FLD_NBR
		, CLU_YR.LOC_CNTY_FSA_CD LOC_CNTY_FSA_CD
		, CLU_YR.LOC_ST_FSA_CD LOC_ST_FSA_CD
		, CLU_YR.ST_ANSI_CD ST_ANSI_CD
		, CLU_YR.CNTY_ANSI_CD CNTY_ANSI_CD
		, CLU_YR.CONG_DIST_CD CONG_DIST_CD
		, CLU_YR.LAND_CLS_ID SRC_LAND_CLS_ID
		, LAND_CLS_RS.DMN_VAL_NM LAND_CLS_NM
		, CLU_YR.CLU_ACRG CLU_ACRG
		, CLU_YR.HEL_STAT_ID SRC_HEL_STAT_ID
		, FLD_HEL_STAT_RS.DMN_VAL_NM HEL_STAT_NM
		, CLU_YR.CPLD_IND_3CM CPLD_IND_3CM
		, CLU_YR.CLU_DESC CLU_DESC
		, CLU_YR.CRP_CTR_NBR CRP_CTR_NBR
		, CLU_YR.CRP_CTR_EXPR_DT CRP_CTR_EXPR_DT
		, CLU_YR.CNSV_PRAC_ID SRC_CNSV_PRAC_ID
		, CNSV_PRAC_RS.DMN_VAL_NM CNSV_PRAC_NM
		, CLU_YR.NTV_SOD_CVSN_DT NTV_SOD_CVSN_DT
		, CLU_YR.SOD_CVSN_CROP_YR_1 SOD_CVSN_CROP_YR_1
		, CLU_YR.SOD_CVSN_CROP_YR_2 SOD_CVSN_CROP_YR_2
		, CLU_YR.SOD_CVSN_CROP_YR_3 SOD_CVSN_CROP_YR_3
		, CLU_YR.SOD_CVSN_CROP_YR_4 SOD_CVSN_CROP_YR_4
		, CLU_YR.PGM_YR PGM_YR 
		, to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT
		, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT
		, MD5(upper(coalesce(CLU_YR.ST_FSA_CD,'--')||'~~'||coalesce(CLU_YR.CNTY_FSA_CD,'--')||'~~'||coalesce(CLU_YR.FARM_NBR,'--'))||'~~'||upper(coalesce(CLU_YR.ST_FSA_CD,'--')||'~~'||coalesce(CLU_YR.CNTY_FSA_CD,'--')||'~~'||coalesce((CLU_YR.TR_NBR)::numeric ,-1))||'~~'||CLU_YR.CLU_YR_ID||'~~'||trim(both CLU_YR.DATA_STAT_CD)||'~~'||to_char(CLU_YR.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both CLU_YR.LAST_CHG_USER_NM)||'~~'||to_char(CLU_YR.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||CLU_YR.TR_YR_ID||'~~'||trim(both CLU_YR.CLU_ALT_ID)||'~~'||trim(both CLU_YR.FLD_NBR)||'~~'||trim(both CLU_YR.LOC_CNTY_FSA_CD)||'~~'||trim(both CLU_YR.LOC_ST_FSA_CD)||'~~'||trim(both CLU_YR.ST_ANSI_CD)||'~~'||trim(both CLU_YR.CNTY_ANSI_CD)||'~~'||trim(both CLU_YR.CONG_DIST_CD)||'~~'||CLU_YR.LAND_CLS_ID||'~~'||trim(both LAND_CLS_RS.DMN_VAL_NM)||'~~'||CLU_YR.CLU_ACRG||'~~'||CLU_YR.HEL_STAT_ID||'~~'||trim(both FLD_HEL_STAT_RS.DMN_VAL_NM)||'~~'||trim(both CLU_YR.CPLD_IND_3CM)||'~~'||trim(both CLU_YR.CLU_DESC)||'~~'||trim(both CLU_YR.CRP_CTR_NBR)||'~~'||to_char(CLU_YR.CRP_CTR_EXPR_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||CLU_YR.CNSV_PRAC_ID||'~~'||trim(both CNSV_PRAC_RS.DMN_VAL_NM)||'~~'||to_char(CLU_YR.NTV_SOD_CVSN_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||CLU_YR.SOD_CVSN_CROP_YR_1||'~~'||CLU_YR.SOD_CVSN_CROP_YR_2||'~~'||CLU_YR.SOD_CVSN_CROP_YR_3||'~~'||CLU_YR.SOD_CVSN_CROP_YR_4||'~~'||CLU_YR.PGM_YR) HASH_DIF
FROM SQL_FARM_RCD_STG.CLU_YR 
LEFT JOIN(select * from EDV.CNSV_PRAC_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) CNSV_PRAC_RS 
ON (CLU_YR.CNSV_PRAC_ID = CNSV_PRAC_RS.DMN_VAL_ID) 
LEFT JOIN(select * from EDV.FLD_HEL_STAT_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) FLD_HEL_STAT_RS 
ON (CLU_YR.HEL_STAT_ID = FLD_HEL_STAT_RS.DMN_VAL_ID) 
LEFT JOIN(select * from EDV.LAND_CLS_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) LAND_CLS_RS 
ON (CLU_YR.LAND_CLS_ID = LAND_CLS_RS.DMN_VAL_ID)
where CLU_YR.CDC_OPER_CD IN ('I','UN')
order by CLU_YR.CDC_DT ASC) stg
 LEFT JOIN  EDV.CLU_YR_LS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists ( select 1 from EDV.CLU_YR_LS ls 
                 where STG.farm_tr_l_id = ls.farm_tr_l_id
                 and STG.clu_yr_id = ls.clu_yr_id
                 and STG.load_dt = ls.load_dt
                )
)
;