INSERT into
EDV.TR_YR_ADJ_LS(FARM_TR_L_ID,TR_YR_ADJ_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
TR_YR_ID,
PGM_YR,
SRC_TR_YR_ADJ_TYPE_CD,
TR_YR_ADJ_TYPE_NM,
SRC_TR_YR_ADJ_RSN_CD,
TR_YR_ADJ_RSN_NM,
AFT_ADJ_VAL,
BEF_ADJ_VAL,
PRNT_TBL_PHY_NM, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(SELECT stg.* from (SELECT DISTINCT 
MD5(MD5(upper(coalesce(TR_YR_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_ADJ.FARM_NBR ,'--')))||'~~'||MD5(upper(coalesce(TR_YR_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_ADJ.TR_NBR,'-1')))) FARM_TR_L_ID,
TR_YR_ADJ.TR_YR_ADJ_ID TR_YR_ADJ_ID,TR_YR_ADJ.LOAD_DT LOAD_DT,TR_YR_ADJ.CDC_DT DATA_EFF_STRT_DT,TR_YR_ADJ.DATA_SRC_NM DATA_SRC_NM,TR_YR_ADJ.DATA_STAT_CD DATA_STAT_CD,TR_YR_ADJ.CRE_DT SRC_CRE_DT,TR_YR_ADJ.LAST_CHG_DT SRC_LAST_CHG_DT,TR_YR_ADJ.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_YR_ADJ.TR_YR_ID TR_YR_ID,TR_YR_ADJ.PGM_YR PGM_YR,TR_YR_ADJ.TR_YR_ADJ_TYPE_CD SRC_TR_YR_ADJ_TYPE_CD,TR_YR_ADJ_TYPE_RS.DMN_VAL_NM TR_YR_ADJ_TYPE_NM,TR_YR_ADJ.TR_YR_ADJ_RSN_CD SRC_TR_YR_ADJ_RSN_CD,TR_YR_ADJ_RSN_RS.DMN_VAL_NM TR_YR_ADJ_RSN_NM,TR_YR_ADJ.AFT_ADJ_VAL AFT_ADJ_VAL,TR_YR_ADJ.BEF_ADJ_VAL BEF_ADJ_VAL , TR_YR_ADJ.PRNT_TBL_PHY_NM PRNT_TBL_PHY_NM, to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(upper(coalesce(TR_YR_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_ADJ.FARM_NBR ,'--'))||'~~'||upper(coalesce(TR_YR_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_ADJ.TR_NBR, '-1'))||'~~'||TR_YR_ADJ.TR_YR_ADJ_ID||'~~'||trim(both TR_YR_ADJ.DATA_STAT_CD)||'~~'||to_char(TR_YR_ADJ.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TR_YR_ADJ.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_YR_ADJ.LAST_CHG_USER_NM)||'~~'||TR_YR_ADJ.TR_YR_ID||'~~'||TR_YR_ADJ.PGM_YR||'~~'||TR_YR_ADJ.TR_YR_ADJ_TYPE_CD||'~~'||TR_YR_ADJ_TYPE_RS.DMN_VAL_NM||'~~'||TR_YR_ADJ.TR_YR_ADJ_RSN_CD||'~~'||TR_YR_ADJ_RSN_RS.DMN_VAL_NM||'~~'||TR_YR_ADJ.AFT_ADJ_VAL||'~~'||TR_YR_ADJ.BEF_ADJ_VAL||'~~'||TR_YR_ADJ.PRNT_TBL_PHY_NM) HASH_DIF
from SQL_FARM_RCD_STG.TR_YR_ADJ 
left join(select * from EDV.TR_YR_ADJ_RSN_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) TR_YR_ADJ_RSN_RS 
on (TR_YR_ADJ.TR_YR_ADJ_RSN_CD=TR_YR_ADJ_RSN_RS.DMN_VAL_ID) 
left join(select * from EDV.TR_YR_ADJ_TYPE_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) TR_YR_ADJ_TYPE_RS 
ON (TR_YR_ADJ.TR_YR_ADJ_TYPE_CD=TR_YR_ADJ_TYPE_RS.DMN_VAL_ID)
 where TR_YR_ADJ.CDC_OPER_CD IN ('I','UN')
order by TR_YR_ADJ.CDC_DT
) stg
 LEFT JOIN  EDV.TR_YR_ADJ_LS dv
 ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (
                select 1 from EDV.TR_YR_ADJ_LS ls
				where stg.FARM_TR_L_ID = ls.FARM_TR_L_ID
				and stg.TR_YR_ADJ_ID = ls.TR_YR_ADJ_ID
				and stg.LOAD_DT = ls.LOAD_DT
			)
);

 