Merge into
EDV.TR_YR_ADJ_LS dv
using(select DISTINCT MD5(MD5(upper(coalesce(TR_YR_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_ADJ.FARM_NBR ,'--')))||'~~'||MD5(upper(coalesce(TR_YR_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce((TR_YR_ADJ.TR_NBR)::numeric  ,-1)))) FARM_TR_L_ID, 
TR_YR_ADJ.TR_YR_ADJ_ID TR_YR_ADJ_ID,TR_YR_ADJ.LOAD_DT LOAD_DT,TR_YR_ADJ.CDC_DT DATA_EFF_STRT_DT,TR_YR_ADJ.DATA_SRC_NM DATA_SRC_NM,TR_YR_ADJ.DATA_STAT_CD DATA_STAT_CD,TR_YR_ADJ.CRE_DT SRC_CRE_DT,TR_YR_ADJ.LAST_CHG_DT SRC_LAST_CHG_DT,TR_YR_ADJ.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_YR_ADJ.TR_YR_ID TR_YR_ID,TR_YR_ADJ.PGM_YR PGM_YR,TR_YR_ADJ.TR_YR_ADJ_TYPE_CD SRC_TR_YR_ADJ_TYPE_CD,TR_YR_ADJ_TYPE_RS.DMN_VAL_NM TR_YR_ADJ_TYPE_NM,TR_YR_ADJ.TR_YR_ADJ_RSN_CD SRC_TR_YR_ADJ_RSN_CD,TR_YR_ADJ_RSN_RS.DMN_VAL_NM TR_YR_ADJ_RSN_NM,TR_YR_ADJ.AFT_ADJ_VAL AFT_ADJ_VAL,TR_YR_ADJ.BEF_ADJ_VAL BEF_ADJ_VAL, TR_YR_ADJ.PRNT_TBL_PHY_NM PRNT_TBL_PHY_NM, TR_YR_ADJ.CDC_OPER_CD,
MD5(upper(coalesce(TR_YR_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_ADJ.FARM_NBR ,'--'))||'~~'||upper(coalesce(TR_YR_ADJ.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_ADJ.CNTY_FSA_CD,'--')||'~~'||coalesce((TR_YR_ADJ.TR_NBR)::numeric  ,-1))||'~~'||TR_YR_ADJ.TR_YR_ADJ_ID||'~~'||trim(both TR_YR_ADJ.DATA_STAT_CD)||'~~'||to_char(TR_YR_ADJ.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TR_YR_ADJ.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_YR_ADJ.LAST_CHG_USER_NM)||'~~'||TR_YR_ADJ.TR_YR_ID||'~~'||TR_YR_ADJ.PGM_YR||'~~'||TR_YR_ADJ.TR_YR_ADJ_TYPE_CD||'~~'||TR_YR_ADJ_TYPE_RS.DMN_VAL_NM||'~~'||TR_YR_ADJ.TR_YR_ADJ_RSN_CD||'~~'||TR_YR_ADJ_RSN_RS.DMN_VAL_NM||'~~'||TR_YR_ADJ.AFT_ADJ_VAL||'~~'||TR_YR_ADJ.BEF_ADJ_VAL||'~~'||TR_YR_ADJ.PRNT_TBL_PHY_NM) HASH_DIF
from SQL_FARM_RCD_STG.TR_YR_ADJ 
left join(select * from EDV.TR_YR_ADJ_RSN_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) TR_YR_ADJ_RSN_RS 
on (TR_YR_ADJ.TR_YR_ADJ_RSN_CD=TR_YR_ADJ_RSN_RS.DMN_VAL_ID) 
left join(select * from EDV.TR_YR_ADJ_TYPE_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) TR_YR_ADJ_TYPE_RS 
ON (TR_YR_ADJ.TR_YR_ADJ_TYPE_CD=TR_YR_ADJ_TYPE_RS.DMN_VAL_ID)
 where TR_YR_ADJ.CDC_OPER_CD='D'
--and date_trunc('day', TR_YR_ADJ.CDC_DT) = date_trunc('day', TO_TIMESTAMP('<DATA_EFF_STRT_DT>', 'YYYY-MM-DD HH24:MI:SS.FF'))
--and TR_YR_ADJ.LOAD_DT = TO_TIMESTAMP('<LOAD_DT>', 'YYYY-MM-DD HH24:MI:SS.FF')
order by TR_YR_ADJ.CDC_DT)
stg
 on ( 
coalesce(stg.TR_YR_ADJ_ID,0) = coalesce(dv.TR_YR_ADJ_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT

WHEN NOT MATCHED THEN
INSERT(
FARM_TR_L_ID,TR_YR_ADJ_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
TR_YR_ID,
PGM_YR,
SRC_TR_YR_ADJ_TYPE_CD,
TR_YR_ADJ_TYPE_NM,
SRC_TR_YR_ADJ_RSN_CD,
TR_YR_ADJ_RSN_NM,
AFT_ADJ_VAL,
BEF_ADJ_VAL,
PRNT_TBL_PHY_NM, 
DATA_EFF_END_DT,LOAD_END_DT,HASH_DIF)
VALUES (
stg.FARM_TR_L_ID,stg.TR_YR_ADJ_ID,stg.LOAD_DT,stg.DATA_EFF_STRT_DT,stg.DATA_SRC_NM,stg.DATA_STAT_CD,stg.SRC_CRE_DT,stg.SRC_LAST_CHG_DT,stg.SRC_LAST_CHG_USER_NM,stg.TR_YR_ID,stg.PGM_YR,stg.SRC_TR_YR_ADJ_TYPE_CD,stg.TR_YR_ADJ_TYPE_NM,stg.SRC_TR_YR_ADJ_RSN_CD,stg.TR_YR_ADJ_RSN_NM,stg.AFT_ADJ_VAL,stg.BEF_ADJ_VAL,stg.PRNT_TBL_PHY_NM,stg.DATA_EFF_STRT_DT,stg.LOAD_DT,
stg.HASH_DIF
);