MERGE INTO EDV.CMB_PRDR_ACCT_PRD_LS dv USING
  (SELECT DISTINCT MD5 (MD5 (coalesce(CMB_PRDR_ACCT.CMB_PRDR_ACCT_ID::varchar, '-1'))|| SBSD_PRD.SBSD_PRD_NM) AS CMB_PRDR_ACCT_PRD_L_ID,
                   CMB_PRDR_ACCT.LOAD_DT,
                   CMB_PRDR_ACCT.CDC_DT,
                   CMB_PRDR_ACCT.DATA_SRC_NM,
                   CMB_PRDR_ACCT.SBSD_PRD_ID,
                   CMB_PRDR_ACCT.CMB_PRDR_ACCT_ID,
                   CMB_PRDR_ACCT.CDC_OPER_CD
   FROM SBSD_STG.CMB_PRDR_ACCT
   JOIN EDV.V_SBSD_PRD SBSD_PRD ON (CMB_PRDR_ACCT.SBSD_PRD_ID=SBSD_PRD.SBSD_PRD_ID)
   WHERE CMB_PRDR_ACCT.CDC_OPER_CD<>'D'
     AND DATE_TRUNC('day',CMB_PRDR_ACCT.CDC_DT) = DATE_TRUNC('day',TO_TIMESTAMP ('{ETL_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF'))
     AND CMB_PRDR_ACCT.LOAD_DT = (SELECT MAX(LOAD_DT) FROM SBSD_STG.CMB_PRDR_ACCT)
   ORDER BY CMB_PRDR_ACCT.CDC_DT) stg 
ON (coalesce(stg.SBSD_PRD_ID, 0) = coalesce(dv.SBSD_PRD_ID, 0)
  AND coalesce(stg.CMB_PRDR_ACCT_ID, 0) = coalesce(dv.CMB_PRDR_ACCT_ID, 0)) 
WHEN MATCHED 
  AND dv.LOAD_DT <> stg.LOAD_DT
  AND dv.LOAD_END_DT = to_date('9999-12-31', 'YYYY-MM-DD')
  AND (coalesce(stg.CMB_PRDR_ACCT_PRD_L_ID, 'X') <> coalesce(dv.CMB_PRDR_ACCT_PRD_L_ID, 'X'))
THEN
UPDATE
SET LOAD_END_DT=stg.LOAD_DT,
    DATA_EFF_END_DT=stg.CDC_DT
