SELECT DISTINCT CONTRACT_PARTICIPANT_ERROR_TYPE.CONTRACT_PARTICIPANT_ERROR_TYPE_IDENTIFIER  CTR_PTCP_ERR_TYPE_ID,

CONTRACT_PARTICIPANT_ERROR_TYPE.CREATION_DATE  CRE_DT,

CONTRACT_PARTICIPANT_ERROR_TYPE.CREATION_USER_NAME  CRE_USER_NM,

CONTRACT_PARTICIPANT_ERROR_TYPE.LAST_CHANGE_DATE  LAST_CHG_DT,

CONTRACT_PARTICIPANT_ERROR_TYPE.LAST_CHANGE_USER_NAME  LAST_CHG_USER_NM,

CONTRACT_PARTICIPANT_ERROR_TYPE.DATA_STATUS_CODE  DATA_STAT_CD,

CONTRACT_PARTICIPANT_ERROR_TYPE.APPLICATION_ABBREVIATION  APP_ABR,

CONTRACT_PARTICIPANT_ERROR_TYPE.CONTRACT_PARTICIPANT_ERROR_CODE  CTR_PTCP_ERR_CD,

CONTRACT_PARTICIPANT_ERROR_TYPE.CONTRACT_PARTICIPANT_ERROR_DESCRIPTION  CTR_PTCP_ERR_TXT,

OP AS CDC_OPER_CD,

1 AS row_num_part

FROM CONTRACT_PARTICIPANT_ERROR_TYPE

WHERE OP <> 'D'

UNION

SELECT DISTINCT CONTRACT_PARTICIPANT_ERROR_TYPE.CONTRACT_PARTICIPANT_ERROR_TYPE_IDENTIFIER  CTR_PTCP_ERR_TYPE_ID,

CONTRACT_PARTICIPANT_ERROR_TYPE.CREATION_DATE  CRE_DT,

CONTRACT_PARTICIPANT_ERROR_TYPE.CREATION_USER_NAME  CRE_USER_NM,

CONTRACT_PARTICIPANT_ERROR_TYPE.LAST_CHANGE_DATE  LAST_CHG_DT,

CONTRACT_PARTICIPANT_ERROR_TYPE.LAST_CHANGE_USER_NAME  LAST_CHG_USER_NM,

CONTRACT_PARTICIPANT_ERROR_TYPE.DATA_STATUS_CODE  DATA_STAT_CD,

CONTRACT_PARTICIPANT_ERROR_TYPE.APPLICATION_ABBREVIATION  APP_ABR,

CONTRACT_PARTICIPANT_ERROR_TYPE.CONTRACT_PARTICIPANT_ERROR_CODE  CTR_PTCP_ERR_CD,

CONTRACT_PARTICIPANT_ERROR_TYPE.CONTRACT_PARTICIPANT_ERROR_DESCRIPTION  CTR_PTCP_ERR_TXT,

'D' AS CDC_OPER_CD,

1 AS row_num_part

FROM CONTRACT_PARTICIPANT_ERROR_TYPE

WHERE OP = 'D' 