INSERT INTO sql_farm_rcd_stg.tr_yr_dcp_adj
(tr_yr_adj_id, tr_yr_dcp_id, tr_yr_adj_type_cd, tr_yr_adj_rsn_cd, aft_adj_val, bef_adj_val, prnt_tbl_phy_nm,
 farm_nbr, tr_nbr, st_fsa_cd, cnty_fsa_cd, pgm_yr, data_stat_cd, cre_dt, last_chg_dt, last_chg_user_nm, hash_dif,
 cdc_oper_cd, load_dt, data_src_nm, cdc_dt)
SELECT distinct TRACT_YEAR_ADJUSTMENT.TRACT_YEAR_ADJUSTMENT_IDENTIFIER AS TR_YR_ADJ_ID,
TRACT_YEAR_ADJUSTMENT.TRACT_YEAR_DCP_IDENTIFIER AS TR_YR_DCP_ID,
TRACT_YEAR_ADJUSTMENT.TRACT_YEAR_ADJUSTMENT_TYPE_CODE AS TR_YR_ADJ_TYPE_CD,
TRACT_YEAR_ADJUSTMENT.TRACT_YEAR_ADJUSTMENT_REASON_CODE AS TR_YR_ADJ_RSN_CD,
TRACT_YEAR_ADJUSTMENT.AFTER_ADJUSTMENT_VALUE AS AFT_ADJ_VAL,
TRACT_YEAR_ADJUSTMENT.BEFORE_ADJUSTMENT_VALUE AS BEF_ADJ_VAL,
TRACT_YEAR_ADJUSTMENT.PARENT_TABLE_PHYSICAL_NAME AS PRNT_TBL_PHY_NM,
LTRIM(RTRIM(FARM.FARM_NUMBER)) AS FARM_NBR,
LTRIM(RTRIM(TRACT.TRACT_NUMBER)) AS TR_NBR,
LTRIM(RTRIM(COUNTY_OFFICE_CONTROL.STATE_FSA_CODE)) AS ST_FSA_CD,
LTRIM(RTRIM(COUNTY_OFFICE_CONTROL.COUNTY_FSA_CODE)) AS CNTY_FSA_CD,
CAST(TIME_PERIOD.time_period_name AS numeric(4)) as PGM_YR,
LTRIM(RTRIM(TRACT_YEAR_ADJUSTMENT.DATA_STATUS_CODE)) AS DATA_STAT_CD,
TRACT_YEAR_ADJUSTMENT.CREATION_DATE AS CRE_DT,
TRACT_YEAR_ADJUSTMENT.LAST_CHANGE_DATE AS LAST_CHG_DT,
LTRIM(RTRIM(TRACT_YEAR_ADJUSTMENT.LAST_CHANGE_USER_NAME)) AS LAST_CHG_USER_NM,
''  as HASH_DIF,
tract_year_adjustment.cdc_oper_cd AS CDC_OPER_CD,
CAST(current_date as date) as LOAD_DT,
'SAP/CRM' as DATA_SRC_NM,
tract_year_adjustment.cdc_dt as CDC_DT
from farm_records_reporting.tract_year_adjustment 
LEFT JOIN farm_records_reporting.TRACT_YEAR_DCP ON (TRACT_YEAR_ADJUSTMENT.TRACT_YEAR_DCP_IDENTIFIER = TRACT_YEAR_DCP.TRACT_YEAR_DCP_IDENTIFIER)
LEFT JOIN farm_records_reporting.TRACT_YEAR ON (TRACT_YEAR.TRACT_YEAR_IDENTIFIER = TRACT_YEAR_DCP.TRACT_YEAR_IDENTIFIER)
LEFT JOIN farm_records_reporting.TRACT ON (TRACT.TRACT_IDENTIFIER = TRACT_YEAR.TRACT_IDENTIFIER)
LEFT JOIN farm_records_reporting.COUNTY_OFFICE_CONTROL ON (COUNTY_OFFICE_CONTROL.COUNTY_OFFICE_CONTROL_IDENTIFIER = TRACT.COUNTY_OFFICE_CONTROL_IDENTIFIER)
LEFT JOIN farm_records_reporting.FARM_YEAR ON (FARM_YEAR.FARM_YEAR_IDENTIFIER = TRACT_YEAR.FARM_YEAR_IDENTIFIER)
LEFT JOIN farm_records_reporting.FARM ON (FARM.FARM_IDENTIFIER = FARM_YEAR.FARM_IDENTIFIER)
LEFT JOIN farm_records_reporting.TIME_PERIOD ON (TIME_PERIOD.TIME_PERIOD_IDENTIFIER = FARM_YEAR.TIME_PERIOD_IDENTIFIER)
WHERE TRACT_YEAR_DCP.TRACT_YEAR_DCP_IDENTIFIER IS NOT null
and tract_year_adjustment.cdc_dt between date '{ETL_START_DATE}' and date '{ETL_END_DATE}'