-- Julia Lu edition - will update this paragraph and query when cnsv-cdc is ready
-- Stage SQL: CNSV_EWT82SPGYR (Incremental)
-- Location: s3://c108-dev-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_EWT82SPGYR/incremental/CNSV_EWT82SPGYR.sql
-- =============================================================================

SELECT * FROM
(
SELECT DISTINCT SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
PGM_YR,
PGM_EFF_DT,
OFR_RANK_RQR_IND,
SGNP_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
-- op,
ROW_NUMBER() over ( partition by 
PGM_YR,
SGNP_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt82spgyr.PGM_YR PGM_YR,
ewt82spgyr.PGM_EFF_DT PGM_EFF_DT,
ewt82spgyr.ofr_rank_rqr_ind OFR_RANK_RQR_IND,
ewt82spgyr.SGNP_ID SGNP_ID,
ewt82spgyr.DATA_STAT_CD DATA_STAT_CD,
ewt82spgyr.CRE_DT CRE_DT,
ewt82spgyr.LAST_CHG_DT LAST_CHG_DT,
ewt82spgyr.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
1 AS TBL_PRIORITY
FROM "fsa-prod-cnsv".EWT82SPGYR 
LEFT JOIN "fsa-prod-cnsv".EWT14SGNP ON (EWT82SPGYR.SGNP_ID = EWT14SGNP.SGNP_ID)
-- WHERE __CDC_OPERATION <> 'D'

UNION
SELECT 
ewt14sgnp.SGNP_TYPE_DESC SGNP_TYPE_DESC,
ewt14sgnp.SGNP_STYPE_DESC SGNP_STYPE_DESC,
ewt14sgnp.SGNP_NBR SGNP_NBR,
ewt14sgnp.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
ewt82spgyr.PGM_YR PGM_YR,
ewt82spgyr.PGM_EFF_DT PGM_EFF_DT,
ewt82spgyr.ofr_rank_rqr_ind OFR_RANK_RQR_IND,
ewt82spgyr.SGNP_ID SGNP_ID,
ewt82spgyr.DATA_STAT_CD DATA_STAT_CD,
ewt82spgyr.CRE_DT CRE_DT,
ewt82spgyr.LAST_CHG_DT LAST_CHG_DT,
ewt82spgyr.LAST_CHG_USER_NM LAST_CHG_USER_NM,
-- op,
2 AS TBL_PRIORITY
FROM "fsa-prod-cnsv".EWT14SGNP 
JOIN "fsa-prod-cnsv".EWT82SPGYR ON (EWT82SPGYR.SGNP_ID = EWT14SGNP.SGNP_ID)
--WHERE __CDC_OPERATION <> 'D'
) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('2025-07-01' AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('2025-07-01' AS DATE))
)

UNION
SELECT DISTINCT
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
ewt82spgyr.PGM_YR PGM_YR,
ewt82spgyr.PGM_EFF_DT PGM_EFF_DT,
ewt82spgyr.ofr_rank_rqr_ind OFR_RANK_RQR_IND,
ewt82spgyr.SGNP_ID SGNP_ID,
ewt82spgyr.DATA_STAT_CD DATA_STAT_CD,
ewt82spgyr.CRE_DT CRE_DT,
ewt82spgyr.LAST_CHG_DT LAST_CHG_DT,
ewt82spgyr.LAST_CHG_USER_NM LAST_CHG_USER_NM,
--'D' AS CDC_OPER_CD,
1 AS row_num_part
FROM "fsa-prod-cnsv".ewt82spgyr
--WHERE __CDC_OPERATION = 'D'
