UPDATE CAR_DM_STG.AG_PROD_PLAN_BUS_PTY_FACT mart
SET DATA_STAT_CD = 'I',
    LAST_CHG_DT = TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD HH24:MI:SS.FF')
FROM
  (SELECT DISTINCT AG_PROD_PLAN_DIM.AG_PROD_PLAN_DURB_ID,
                   CUST_DIM.CUST_DURB_ID
   FROM edv.CROP_ACRG_RPT_BUS_PTY_SHR_LS DV_DR
   LEFT JOIN edv.CROP_ACRG_RPT_BUS_PTY_SHR_L ON (DV_DR.CROP_ACRG_RPT_BUS_PTY_SHR_L_ID = CROP_ACRG_RPT_BUS_PTY_SHR_L.CROP_ACRG_RPT_BUS_PTY_SHR_L_ID)
   LEFT JOIN edv.AG_PROD_PLAN_H ON (COALESCE (CROP_ACRG_RPT_BUS_PTY_SHR_L.AG_PROD_PLAN_H_ID,
                                              '6bb61e3b7bce0931da574d19d1d82c88') = AG_PROD_PLAN_H.AG_PROD_PLAN_H_ID)
   LEFT JOIN edv.CORE_CUST_H ON (COALESCE (CROP_ACRG_RPT_BUS_PTY_SHR_L.CORE_CUST_ID,
                                           '-1') = CORE_CUST_H.CORE_CUST_ID)
   LEFT JOIN CAR_DM_STG.AG_PROD_PLAN_DIM ON (AG_PROD_PLAN_H.DURB_ID = AG_PROD_PLAN_DIM.AG_PROD_PLAN_DURB_ID
                                         AND AG_PROD_PLAN_DIM.CUR_RCD_IND = 1)
   LEFT JOIN cmn_dim_dm_stg.CUST_DIM ON (CORE_CUST_H.DURB_ID = CUST_DIM.CUST_DURB_ID
                                         AND CUST_DIM.CUR_RCD_IND = 1)
   WHERE (DATE (DV_DR.DATA_EFF_END_DT) = TO_TIMESTAMP ('{ETL_DATE}',
                                                        'YYYY-MM-DD')
          AND NOT EXISTS
            (SELECT '1'
             FROM edv.CROP_ACRG_RPT_BUS_PTY_SHR_LS sub
             WHERE sub.BUS_PTY_SHR_ID = dv_dr.BUS_PTY_SHR_ID
               AND sub. DATA_EFF_END_DT = TO_TIMESTAMP ('9999-12-31',
                                                        'YYYY-MM-DD') ))
     AND AG_PROD_PLAN_DIM.AG_PROD_PLAN_DURB_ID IS NOT NULL
     AND CUST_DIM.CUST_DURB_ID IS NOT NULL) AS vault
WHERE vault.AG_PROD_PLAN_DURB_ID = mart.AG_PROD_PLAN_DURB_ID
  AND vault.CUST_DURB_ID = mart.CUST_DURB_ID
  AND mart.DATA_STAT_CD = 'A'