INSERT into
EDV.FRS_PGM_RH(PGM_ABR,
DATA_SRC_NM,
LOAD_DT)
(
SELECT 
stg.PGM_ABR,
stg.DATA_SRC_NM,
stg.LOAD_DT
from (
SELECT DISTINCT
coalesce(CROP.PGM_ABR, '--') PGM_ABR,
CROP.DATA_SRC_NM DATA_SRC_NM,
CROP.LOAD_DT LOAD_DT,
ROW_NUMBER() OVER (PARTITION BY CROP.PGM_ABR ORDER BY CROP.CDC_DT desc, CROP.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.CROP

where CROP.cdc_oper_cd IN ('I','UN','D')
) stg 
LEFT JOIN  EDV.FRS_PGM_RH dv
 ON (
stg.PGM_ABR = dv.PGM_ABR
)
where (
dv.PGM_ABR IS NULL
)
and stg.STG_EFF_DT_RANK = 1
);