-- Julia Lu edition - will upthis paragraph and query when cnsv-cdc is ready
-- Stage SQL: CNSV_EWT40OFRSC (Incremental)
-- Location: s3://c108-cert-fpacfsa-final-zone/cnsv/_configs/stg/CNSV_EWT40OFRSC/incremental/CNSV_EWT40OFRS.sql
-- =============================================================================

select * from
(
select distinct pgm_yr,
adm_st_fsa_cd,
adm_cnty_fsa_cd,
tr_nbr,
ofr_scnr_nm,
sgnp_type_desc,
sgnp_stype_desc,
sgnp_nbr,
sgnp_stype_agr_nm,
farm_nbr,
prdr_ofr_acpt_ind,
prdr_ofr_sbmt_ind,
sgnp_type_cd,
clmt_fctr,
rnfl_fctr,
crp_ctr_yr_end,
land_type_cd,
crp_orgn_strt_dt,
ofr_sgn_ntfy_dt,
loc_st_fsa_cd,
loc_cnty_fsa_cd,
crp_anl_pymt_amt,
crp_ctr_acrg,
crp_anl_rent_acrg,
ntl_huc_cd,
wt_avg_soil_rnt_rt,
soil_tot_acrg,
soil_rnt_tot_amt,
prdr_tot_ofr_acrg,
ofr_tot_elg_acrg,
cost_shr_exmp_ind,
cost_shr_rqst_ind,
hel_crp_elg_acrg,
elg_cpa_ntl_acrg,
st_cpa_elg_acrg,
wbp_expr_cpld_elg,
crp_1_actv_acrg,
ofr_stat_cd,
tr_loc_dif_ind,
opr_assc_ind,
ownr_assc_ind,
oper_actv_ind,
ownr_actv_ind,
farm_ivld_nbr_ind,
tr_ivld_nbr_ind,
tr_vld_rqr_ind,
trnsm_ind,
last_trnsm_dt,
ofr_last_chg_dt_tm,
n1b_wldlf_enhc,
wbp_cpld_acrg,
wbp_ncpld_acrg,
wbp_ncpld_long,
long_expr_acrg,
new_cpld_acrg,
long_prac_acrg,
wlhd_acrg,
mpl_acrg,
mpl_wlhd_acrg,
ifsbl_to_farm_acrg,
cost_shr_tot_amt,
cntr_latd,
cntr_lgtd,
ofr_scnr_mnt_rt,
ebi_rank_nbr,
ofr_dcsn_desc,
crp_sip_amt,
crp_pip_amt,
tr_acrg,
ofr_pymt_mthd_cd,
enrl_intn_sgn_dt,
site_rvw_rqst_dt,
crp_pln_rqst_dt,
crp_pln_apvl_dt,
tech_asst_rqst_dt,
prnt_ofr_scnr_id,
cnsv_ctr_seq_nbr,
cnsv_ctr_sfx_cd,
cncl_rsn_desc,
anstr_ofr_scnr_id,
gis_scnr_id,
gis_ofr_cre_ind,
ctr_strt_dt,
ctr_apvl_dt,
ctr_pymt_amt,
cs_est_amt,
ctr_end_dt,
crop_rotation_history_ind,
ofr_rank_stat_cd,
dafp_aprv_dt,
long_leaf_pine_plnt_ind,
ofr_elg_ind,
ofr_scnr_id,
ofr_scnr_seq_nbr,
sgnp_id,
prnt_pgm_yr,
prnt_adm_st_fsa_cd,
prnt_adm_cnty_fsa_cd,
prnt_tr_nbr,
prnt_ofr_scnr_nm,
prnt_sgnp_type_desc,
prnt_sgnp_stype_desc,
prnt_sgnp_nbr,
prnt_sgnp_stype_agr_nm,
prnt_cnsv_ctr_seq_nbr,
prnt_cnsv_ctr_sfx_cd,
anstr_pgm_yr,
anstr_adm_st_fsa_cd,
anstr_adm_cnty_fsa_cd,
anstr_tr_nbr,
anstr_ofr_scnr_nm,
anstr_sgnp_type_desc,
anstr_sgnp_stype_desc,
anstr_sgnp_nbr,
anstr_sgnp_stype_agr_nm,
anstr_cnsv_ctr_seq_nbr,
anstr_cnsv_ctr_sfx_cd,
prac_mnt_resp_cd,
ncpld_acrg,
data_stat_cd,
last_chg_dt,
last_chg_user_nm,
cre_dt,
cdc_oper_cd,
load_dt,
data_src_nm,
cdc_dt,
row_number() over ( partition by 
ofr_scnr_id
order by tbl_priority asc, last_chg_dt desc ) as row_num_part
from
(
select 
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt40ofrsc.farm_nbr farm_nbr,
ewt40ofrsc.prdr_ofr_acpt_ind prdr_ofr_acpt_ind,
ewt40ofrsc.prdr_ofr_sbmt_ind prdr_ofr_sbmt_ind,
ewt40ofrsc.sgnp_type_cd sgnp_type_cd,
ewt40ofrsc.clmt_fctr clmt_fctr,
ewt40ofrsc.rnfl_fctr rnfl_fctr,
ewt40ofrsc.crp_ctr_yr_end crp_ctr_yr_end,
ewt40ofrsc.land_type_cd land_type_cd,
ewt40ofrsc.crp_orgn_strt_dt crp_orgn_strt_dt,
ewt40ofrsc.ofr_sgn_ntfy_dt ofr_sgn_ntfy_dt,
ewt40ofrsc.loc_st_fsa_cd loc_st_fsa_cd,
ewt40ofrsc.loc_cnty_fsa_cd loc_cnty_fsa_cd,
ewt40ofrsc.crp_anl_pymt_amt crp_anl_pymt_amt,
ewt40ofrsc.crp_ctr_acrg crp_ctr_acrg,
ewt40ofrsc.crp_anl_rent_acrg crp_anl_rent_acrg,
ewt40ofrsc.ntl_huc_cd ntl_huc_cd,
ewt40ofrsc.wt_avg_soil_rnt_rt wt_avg_soil_rnt_rt,
ewt40ofrsc.soil_tot_acrg soil_tot_acrg,
ewt40ofrsc.soil_rnt_tot_amt soil_rnt_tot_amt,
ewt40ofrsc.prdr_tot_ofr_acrg prdr_tot_ofr_acrg,
ewt40ofrsc.ofr_tot_elg_acrg ofr_tot_elg_acrg,
ewt40ofrsc.cost_shr_exmp_ind cost_shr_exmp_ind,
ewt40ofrsc.cost_shr_rqst_ind cost_shr_rqst_ind,
ewt40ofrsc.hel_crp_elg_acrg hel_crp_elg_acrg,
ewt40ofrsc.elg_cpa_ntl_acrg elg_cpa_ntl_acrg,
ewt40ofrsc.st_cpa_elg_acrg st_cpa_elg_acrg,
ewt40ofrsc.wbp_expr_cpld_elg wbp_expr_cpld_elg,
ewt40ofrsc.crp_1_actv_acrg crp_1_actv_acrg,
ewt40ofrsc.ofr_stat_cd ofr_stat_cd,
ewt40ofrsc.tr_loc_dif_ind tr_loc_dif_ind,
ewt40ofrsc.opr_assc_ind opr_assc_ind,
ewt40ofrsc.ownr_assc_ind ownr_assc_ind,
ewt40ofrsc.oper_actv_ind oper_actv_ind,
ewt40ofrsc.ownr_actv_ind ownr_actv_ind,
ewt40ofrsc.farm_ivld_nbr_ind farm_ivld_nbr_ind,
ewt40ofrsc.tr_ivld_nbr_ind tr_ivld_nbr_ind,
ewt40ofrsc.tr_vld_rqr_ind tr_vld_rqr_ind,
ewt40ofrsc.trnsm_ind trnsm_ind,
ewt40ofrsc.last_trnsm_dt last_trnsm_dt,
ewt40ofrsc.ofr_last_chg_dt_tm ofr_last_chg_dt_tm,
ewt40ofrsc.n1b_wldlf_enhc n1b_wldlf_enhc,
ewt40ofrsc.wbp_cpld_acrg wbp_cpld_acrg,
ewt40ofrsc.wbp_ncpld_acrg wbp_ncpld_acrg,
ewt40ofrsc.wbp_ncpld_long wbp_ncpld_long,
ewt40ofrsc.long_expr_acrg long_expr_acrg,
ewt40ofrsc.new_cpld_acrg new_cpld_acrg,
ewt40ofrsc.long_prac_acrg long_prac_acrg,
ewt40ofrsc.wlhd_acrg wlhd_acrg,
ewt40ofrsc.mpl_acrg mpl_acrg,
ewt40ofrsc.mpl_wlhd_acrg mpl_wlhd_acrg,
ewt40ofrsc.ifsbl_to_farm_acrg ifsbl_to_farm_acrg,
ewt40ofrsc.cost_shr_tot_amt cost_shr_tot_amt,
ewt40ofrsc.cntr_latd cntr_latd,
ewt40ofrsc.cntr_lgtd cntr_lgtd,
ewt40ofrsc.ofr_scnr_mnt_rt ofr_scnr_mnt_rt,
ewt40ofrsc.ebi_rank_nbr ebi_rank_nbr,
ewt40ofrsc.ofr_dcsn_desc ofr_dcsn_desc,
ewt40ofrsc.crp_sip_amt crp_sip_amt,
ewt40ofrsc.crp_pip_amt crp_pip_amt,
ewt40ofrsc.tr_acrg tr_acrg,
ewt40ofrsc.ofr_pymt_mthd_cd ofr_pymt_mthd_cd,
ewt40ofrsc.enrl_intn_sgn_dt enrl_intn_sgn_dt,
ewt40ofrsc.site_rvw_rqst_dt site_rvw_rqst_dt,
ewt40ofrsc.crp_pln_rqst_dt crp_pln_rqst_dt,
ewt40ofrsc.crp_pln_apvl_dt crp_pln_apvl_dt,
ewt40ofrsc.tech_asst_rqst_dt tech_asst_rqst_dt,
ewt40ofrsc.prnt_ofr_scnr_id prnt_ofr_scnr_id,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt40ofrsc.cncl_rsn_desc cncl_rsn_desc,
ewt40ofrsc.anstr_ofr_scnr_id anstr_ofr_scnr_id,
ewt40ofrsc.gis_scnr_id gis_scnr_id,
ewt40ofrsc.gis_ofr_cre_ind gis_ofr_cre_ind,
ewt40ofrsc.ctr_strt_dt ctr_strt_dt,
ewt40ofrsc.ctr_apvl_dt ctr_apvl_dt,
ewt40ofrsc.ctr_pymt_amt ctr_pymt_amt,
ewt40ofrsc.cs_est_amt cs_est_amt,
ewt40ofrsc.ctr_end_dt ctr_end_dt,
ewt40ofrsc.crop_rotation_history_ind crop_rotation_history_ind,
ewt40ofrsc.ofr_rank_stat_cd ofr_rank_stat_cd,
ewt40ofrsc.dafp_approved_dafp_aprv_dt,
ewt40ofrsc.long_leaf_pine_plnt_ind long_leaf_pine_plnt_ind,
ewt40ofrsc.ofr_elg_ind ofr_elg_ind,
ewt40ofrsc.ofr_scnr_id ofr_scnr_id,
ewt40ofrsc.ofr_scnr_seq_nbr ofr_scnr_seq_nbr,
ewt40ofrsc.sgnp_id sgnp_id,
ewt40ofrsc_prnt.pgm_yr prnt_pgm_yr,
ewt40ofrsc_prnt.adm_st_fsa_cd prnt_adm_st_fsa_cd,
ewt40ofrsc_prnt.adm_cnty_fsa_cd prnt_adm_cnty_fsa_cd,
ewt40ofrsc_prnt.tr_nbr prnt_tr_nbr,
ewt40ofrsc_prnt.ofr_scnr_nm prnt_ofr_scnr_nm,
ewt14sgnp_prnt.sgnp_type_desc prnt_sgnp_type_desc,
ewt14sgnp_prnt.sgnp_stype_desc prnt_sgnp_stype_desc,
ewt14sgnp_prnt.sgnp_nbr prnt_sgnp_nbr,
ewt14sgnp_prnt.sgnp_stype_agr_nm prnt_sgnp_stype_agr_nm,
ewt40ofrsc_prnt.cnsv_ctr_seq_nbr prnt_cnsv_ctr_seq_nbr,
ewt40ofrsc_prnt.cnsv_ctr_sufx_cd prnt_cnsv_ctr_sfx_cd,
ewt40ofrsc_anstr.pgm_yr anstr_pgm_yr,
ewt40ofrsc_anstr.adm_st_fsa_cd anstr_adm_st_fsa_cd,
ewt40ofrsc_anstr.adm_cnty_fsa_cd anstr_adm_cnty_fsa_cd,
ewt40ofrsc_anstr.tr_nbr anstr_tr_nbr,
ewt40ofrsc_anstr.ofr_scnr_nm anstr_ofr_scnr_nm,
ewt14sgnp_anstr.sgnp_type_desc anstr_sgnp_type_desc,
ewt14sgnp_anstr.sgnp_stype_desc anstr_sgnp_stype_desc,
ewt14sgnp_anstr.sgnp_nbr anstr_sgnp_nbr,
ewt14sgnp_anstr.sgnp_stype_agr_nm anstr_sgnp_stype_agr_nm,
ewt40ofrsc_anstr.cnsv_ctr_seq_nbr anstr_cnsv_ctr_seq_nbr,
ewt40ofrsc_anstr.cnsv_ctr_sufx_cd anstr_cnsv_ctr_sfx_cd,
ewt40ofrsc.prac_mnt_resp_cd prac_mnt_resp_cd,
ewt40ofrsc.ncpld_acrg ncpld_acrg,
ewt40ofrsc.data_stat_cd data_stat_cd,
ewt40ofrsc.last_chg_dt last_chg_dt,
ewt40ofrsc.last_chg_user_nm last_chg_user_nm,
ewt40ofrsc.cre_dt cre_dt,
ewt40ofrsc.op as cdc_oper_cd,
current_timestamp() as load_dt,
'ewt40ofrsc' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as tbl_priority
from `fsa-{env}-cnsv-cdc`.`ewt40ofrsc`
left join `fsa-{env}-cnsv`.`ewt14sgnp`
on (ewt40ofrsc.sgnp_id = ewt14sgnp.sgnp_id) 
left join `fsa-{env}-cnsv-cdc`.`ewt40ofrsc` ewt40ofrsc_prnt 
on (ewt40ofrsc.prnt_ofr_scnr_id = ewt40ofrsc_prnt.ofr_scnr_id) 
left join `fsa-{env}-cnsv`.`ewt14sgnp` ewt14sgnp_prnt 
on (ewt40ofrsc_prnt.sgnp_id = ewt14sgnp_prnt.sgnp_id) 
left join `fsa-{env}-cnsv-cdc`.`ewt40ofrsc` ewt40ofrsc_anstr 
on (ewt40ofrsc.anstr_ofr_scnr_id = ewt40ofrsc_anstr.ofr_scnr_id) 
left join `fsa-{env}-cnsv`.`ewt14sgnp` ewt14sgnp_anstr 
on (ewt40ofrsc_anstr.sgnp_id = ewt14sgnp_anstr.sgnp_id)
where ewt40ofrsc.op <> 'D'
  and ewt40ofrsc.dart_file between '{etl_start_date}' and '{etl_end_date}'

union
select 
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
ewt14sgnp.sgnp_type_desc sgnp_type_desc,
ewt14sgnp.sgnp_stype_desc sgnp_stype_desc,
ewt14sgnp.sgnp_nbr sgnp_nbr,
ewt14sgnp.sgnp_stype_agr_nm sgnp_stype_agr_nm,
ewt40ofrsc.farm_nbr farm_nbr,
ewt40ofrsc.prdr_ofr_acpt_ind prdr_ofr_acpt_ind,
ewt40ofrsc.prdr_ofr_sbmt_ind prdr_ofr_sbmt_ind,
ewt40ofrsc.sgnp_type_cd sgnp_type_cd,
ewt40ofrsc.clmt_fctr clmt_fctr,
ewt40ofrsc.rnfl_fctr rnfl_fctr,
ewt40ofrsc.crp_ctr_yr_end crp_ctr_yr_end,
ewt40ofrsc.land_type_cd land_type_cd,
ewt40ofrsc.crp_orgn_strt_dt crp_orgn_strt_dt,
ewt40ofrsc.ofr_sgn_ntfy_dt ofr_sgn_ntfy_dt,
ewt40ofrsc.loc_st_fsa_cd loc_st_fsa_cd,
ewt40ofrsc.loc_cnty_fsa_cd loc_cnty_fsa_cd,
ewt40ofrsc.crp_anl_pymt_amt crp_anl_pymt_amt,
ewt40ofrsc.crp_ctr_acrg crp_ctr_acrg,
ewt40ofrsc.crp_anl_rent_acrg crp_anl_rent_acrg,
ewt40ofrsc.ntl_huc_cd ntl_huc_cd,
ewt40ofrsc.wt_avg_soil_rnt_rt wt_avg_soil_rnt_rt,
ewt40ofrsc.soil_tot_acrg soil_tot_acrg,
ewt40ofrsc.soil_rnt_tot_amt soil_rnt_tot_amt,
ewt40ofrsc.prdr_tot_ofr_acrg prdr_tot_ofr_acrg,
ewt40ofrsc.ofr_tot_elg_acrg ofr_tot_elg_acrg,
ewt40ofrsc.cost_shr_exmp_ind cost_shr_exmp_ind,
ewt40ofrsc.cost_shr_rqst_ind cost_shr_rqst_ind,
ewt40ofrsc.hel_crp_elg_acrg hel_crp_elg_acrg,
ewt40ofrsc.elg_cpa_ntl_acrg elg_cpa_ntl_acrg,
ewt40ofrsc.st_cpa_elg_acrg st_cpa_elg_acrg,
ewt40ofrsc.wbp_expr_cpld_elg wbp_expr_cpld_elg,
ewt40ofrsc.crp_1_actv_acrg crp_1_actv_acrg,
ewt40ofrsc.ofr_stat_cd ofr_stat_cd,
ewt40ofrsc.tr_loc_dif_ind tr_loc_dif_ind,
ewt40ofrsc.opr_assc_ind opr_assc_ind,
ewt40ofrsc.ownr_assc_ind ownr_assc_ind,
ewt40ofrsc.oper_actv_ind oper_actv_ind,
ewt40ofrsc.ownr_actv_ind ownr_actv_ind,
ewt40ofrsc.farm_ivld_nbr_ind farm_ivld_nbr_ind,
ewt40ofrsc.tr_ivld_nbr_ind tr_ivld_nbr_ind,
ewt40ofrsc.tr_vld_rqr_ind tr_vld_rqr_ind,
ewt40ofrsc.trnsm_ind trnsm_ind,
ewt40ofrsc.last_trnsm_dt last_trnsm_dt,
ewt40ofrsc.ofr_last_chg_dt_tm ofr_last_chg_dt_tm,
ewt40ofrsc.n1b_wldlf_enhc n1b_wldlf_enhc,
ewt40ofrsc.wbp_cpld_acrg wbp_cpld_acrg,
ewt40ofrsc.wbp_ncpld_acrg wbp_ncpld_acrg,
ewt40ofrsc.wbp_ncpld_long wbp_ncpld_long,
ewt40ofrsc.long_expr_acrg long_expr_acrg,
ewt40ofrsc.new_cpld_acrg new_cpld_acrg,
ewt40ofrsc.long_prac_acrg long_prac_acrg,
ewt40ofrsc.wlhd_acrg wlhd_acrg,
ewt40ofrsc.mpl_acrg mpl_acrg,
ewt40ofrsc.mpl_wlhd_acrg mpl_wlhd_acrg,
ewt40ofrsc.ifsbl_to_farm_acrg ifsbl_to_farm_acrg,
ewt40ofrsc.cost_shr_tot_amt cost_shr_tot_amt,
ewt40ofrsc.cntr_latd cntr_latd,
ewt40ofrsc.cntr_lgtd cntr_lgtd,
ewt40ofrsc.ofr_scnr_mnt_rt ofr_scnr_mnt_rt,
ewt40ofrsc.ebi_rank_nbr ebi_rank_nbr,
ewt40ofrsc.ofr_dcsn_desc ofr_dcsn_desc,
ewt40ofrsc.crp_sip_amt crp_sip_amt,
ewt40ofrsc.crp_pip_amt crp_pip_amt,
ewt40ofrsc.tr_acrg tr_acrg,
ewt40ofrsc.ofr_pymt_mthd_cd ofr_pymt_mthd_cd,
ewt40ofrsc.enrl_intn_sgn_dt enrl_intn_sgn_dt,
ewt40ofrsc.site_rvw_rqst_dt site_rvw_rqst_dt,
ewt40ofrsc.crp_pln_rqst_dt crp_pln_rqst_dt,
ewt40ofrsc.crp_pln_apvl_dt crp_pln_apvl_dt,
ewt40ofrsc.tech_asst_rqst_dt tech_asst_rqst_dt,
ewt40ofrsc.prnt_ofr_scnr_id prnt_ofr_scnr_id,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt40ofrsc.cncl_rsn_desc cncl_rsn_desc,
ewt40ofrsc.anstr_ofr_scnr_id anstr_ofr_scnr_id,
ewt40ofrsc.gis_scnr_id gis_scnr_id,
ewt40ofrsc.gis_ofr_cre_ind gis_ofr_cre_ind,
ewt40ofrsc.ctr_strt_dt ctr_strt_dt,
ewt40ofrsc.ctr_apvl_dt ctr_apvl_dt,
ewt40ofrsc.ctr_pymt_amt ctr_pymt_amt,
ewt40ofrsc.cs_est_amt cs_est_amt,
ewt40ofrsc.ctr_end_dt ctr_end_dt,
ewt40ofrsc.crop_rotation_history_ind crop_rotation_history_ind,
ewt40ofrsc.ofr_rank_stat_cd ofr_rank_stat_cd,
ewt40ofrsc.dafp_approved_dafp_aprv_dt,
ewt40ofrsc.long_leaf_pine_plnt_ind long_leaf_pine_plnt_ind,
ewt40ofrsc.ofr_elg_ind ofr_elg_ind,
ewt40ofrsc.ofr_scnr_id ofr_scnr_id,
ewt40ofrsc.ofr_scnr_seq_nbr ofr_scnr_seq_nbr,
ewt40ofrsc.sgnp_id sgnp_id,
ewt40ofrsc_prnt.pgm_yr prnt_pgm_yr,
ewt40ofrsc_prnt.adm_st_fsa_cd prnt_adm_st_fsa_cd,
ewt40ofrsc_prnt.adm_cnty_fsa_cd prnt_adm_cnty_fsa_cd,
ewt40ofrsc_prnt.tr_nbr prnt_tr_nbr,
ewt40ofrsc_prnt.ofr_scnr_nm prnt_ofr_scnr_nm,
ewt14sgnp_prnt.sgnp_type_desc prnt_sgnp_type_desc,
ewt14sgnp_prnt.sgnp_stype_desc prnt_sgnp_stype_desc,
ewt14sgnp_prnt.sgnp_nbr prnt_sgnp_nbr,
ewt14sgnp_prnt.sgnp_stype_agr_nm prnt_sgnp_stype_agr_nm,
ewt40ofrsc_prnt.cnsv_ctr_seq_nbr prnt_cnsv_ctr_seq_nbr,
ewt40ofrsc_prnt.cnsv_ctr_sufx_cd prnt_cnsv_ctr_sfx_cd,
ewt40ofrsc_anstr.pgm_yr anstr_pgm_yr,
ewt40ofrsc_anstr.adm_st_fsa_cd anstr_adm_st_fsa_cd,
ewt40ofrsc_anstr.adm_cnty_fsa_cd anstr_adm_cnty_fsa_cd,
ewt40ofrsc_anstr.tr_nbr anstr_tr_nbr,
ewt40ofrsc_anstr.ofr_scnr_nm anstr_ofr_scnr_nm,
ewt14sgnp_anstr.sgnp_type_desc anstr_sgnp_type_desc,
ewt14sgnp_anstr.sgnp_stype_desc anstr_sgnp_stype_desc,
ewt14sgnp_anstr.sgnp_nbr anstr_sgnp_nbr,
ewt14sgnp_anstr.sgnp_stype_agr_nm anstr_sgnp_stype_agr_nm,
ewt40ofrsc_anstr.cnsv_ctr_seq_nbr anstr_cnsv_ctr_seq_nbr,
ewt40ofrsc_anstr.cnsv_ctr_sufx_cd anstr_cnsv_ctr_sfx_cd,
ewt40ofrsc.prac_mnt_resp_cd prac_mnt_resp_cd,
ewt40ofrsc.ncpld_acrg ncpld_acrg,
ewt40ofrsc.data_stat_cd data_stat_cd,
ewt40ofrsc.last_chg_dt last_chg_dt,
ewt40ofrsc.last_chg_user_nm last_chg_user_nm,
ewt40ofrsc.cre_dt cre_dt,
ewt14sgnp.op as cdc_oper_cd,
current_timestamp() as load_dt,
'ewt40ofrsc' as data_src_nm,
'{etl_start_date}' as cdc_dt,
2 as tbl_priority
from `fsa-{env}-cnsv`.`ewt14sgnp`
join `fsa-{env}-cnsv-cdc`.`ewt40ofrsc` 
on (ewt14sgnp.sgnp_id = ewt40ofrsc.sgnp_id) 
left join `fsa-{env}-cnsv-cdc`.`ewt40ofrsc` ewt40ofrsc_prnt 
on (ewt40ofrsc.prnt_ofr_scnr_id = ewt40ofrsc_prnt.ofr_scnr_id) 
left join `fsa-{env}-cnsv`.`ewt14sgnp` ewt14sgnp_prnt 
on (ewt40ofrsc_prnt.sgnp_id = ewt14sgnp_prnt.sgnp_id) 
left join `fsa-{env}-cnsv-cdc`.`ewt40ofrsc` ewt40ofrsc_anstr 
on (ewt40ofrsc.anstr_ofr_scnr_id = ewt40ofrsc_anstr.ofr_scnr_id) 
left join `fsa-{env}-cnsv`.`ewt14sgnp` ewt14sgnp_anstr 
on (ewt40ofrsc_anstr.sgnp_id = ewt14sgnp_anstr.sgnp_id) 
where ewt14sgnp.op <> 'D'
) stg_all
) stg_unq
where row_num_part = 1

union
select distinct
ewt40ofrsc.pgm_yr pgm_yr,
ewt40ofrsc.adm_st_fsa_cd adm_st_fsa_cd,
ewt40ofrsc.adm_cnty_fsa_cd adm_cnty_fsa_cd,
ewt40ofrsc.tr_nbr tr_nbr,
ewt40ofrsc.ofr_scnr_nm ofr_scnr_nm,
null sgnp_type_desc,
null sgnp_stype_desc,
null sgnp_nbr,
null sgnp_stype_agr_nm,
ewt40ofrsc.farm_nbr farm_nbr,
ewt40ofrsc.prdr_ofr_acpt_ind prdr_ofr_acpt_ind,
ewt40ofrsc.prdr_ofr_sbmt_ind prdr_ofr_sbmt_ind,
ewt40ofrsc.sgnp_type_cd sgnp_type_cd,
ewt40ofrsc.clmt_fctr clmt_fctr,
ewt40ofrsc.rnfl_fctr rnfl_fctr,
ewt40ofrsc.crp_ctr_yr_end crp_ctr_yr_end,
ewt40ofrsc.land_type_cd land_type_cd,
ewt40ofrsc.crp_orgn_strt_dt crp_orgn_strt_dt,
ewt40ofrsc.ofr_sgn_ntfy_dt ofr_sgn_ntfy_dt,
ewt40ofrsc.loc_st_fsa_cd loc_st_fsa_cd,
ewt40ofrsc.loc_cnty_fsa_cd loc_cnty_fsa_cd,
ewt40ofrsc.crp_anl_pymt_amt crp_anl_pymt_amt,
ewt40ofrsc.crp_ctr_acrg crp_ctr_acrg,
ewt40ofrsc.crp_anl_rent_acrg crp_anl_rent_acrg,
ewt40ofrsc.ntl_huc_cd ntl_huc_cd,
ewt40ofrsc.wt_avg_soil_rnt_rt wt_avg_soil_rnt_rt,
ewt40ofrsc.soil_tot_acrg soil_tot_acrg,
ewt40ofrsc.soil_rnt_tot_amt soil_rnt_tot_amt,
ewt40ofrsc.prdr_tot_ofr_acrg prdr_tot_ofr_acrg,
ewt40ofrsc.ofr_tot_elg_acrg ofr_tot_elg_acrg,
ewt40ofrsc.cost_shr_exmp_ind cost_shr_exmp_ind,
ewt40ofrsc.cost_shr_rqst_ind cost_shr_rqst_ind,
ewt40ofrsc.hel_crp_elg_acrg hel_crp_elg_acrg,
ewt40ofrsc.elg_cpa_ntl_acrg elg_cpa_ntl_acrg,
ewt40ofrsc.st_cpa_elg_acrg st_cpa_elg_acrg,
ewt40ofrsc.wbp_expr_cpld_elg wbp_expr_cpld_elg,
ewt40ofrsc.crp_1_actv_acrg crp_1_actv_acrg,
ewt40ofrsc.ofr_stat_cd ofr_stat_cd,
ewt40ofrsc.tr_loc_dif_ind tr_loc_dif_ind,
ewt40ofrsc.opr_assc_ind opr_assc_ind,
ewt40ofrsc.ownr_assc_ind ownr_assc_ind,
ewt40ofrsc.oper_actv_ind oper_actv_ind,
ewt40ofrsc.ownr_actv_ind ownr_actv_ind,
ewt40ofrsc.farm_ivld_nbr_ind farm_ivld_nbr_ind,
ewt40ofrsc.tr_ivld_nbr_ind tr_ivld_nbr_ind,
ewt40ofrsc.tr_vld_rqr_ind tr_vld_rqr_ind,
ewt40ofrsc.trnsm_ind trnsm_ind,
ewt40ofrsc.last_trnsm_dt last_trnsm_dt,
ewt40ofrsc.ofr_last_chg_dt_tm ofr_last_chg_dt_tm,
ewt40ofrsc.n1b_wldlf_enhc n1b_wldlf_enhc,
ewt40ofrsc.wbp_cpld_acrg wbp_cpld_acrg,
ewt40ofrsc.wbp_ncpld_acrg wbp_ncpld_acrg,
ewt40ofrsc.wbp_ncpld_long wbp_ncpld_long,
ewt40ofrsc.long_expr_acrg long_expr_acrg,
ewt40ofrsc.new_cpld_acrg new_cpld_acrg,
ewt40ofrsc.long_prac_acrg long_prac_acrg,
ewt40ofrsc.wlhd_acrg wlhd_acrg,
ewt40ofrsc.mpl_acrg mpl_acrg,
ewt40ofrsc.mpl_wlhd_acrg mpl_wlhd_acrg,
ewt40ofrsc.ifsbl_to_farm_acrg ifsbl_to_farm_acrg,
ewt40ofrsc.cost_shr_tot_amt cost_shr_tot_amt,
ewt40ofrsc.cntr_latd cntr_latd,
ewt40ofrsc.cntr_lgtd cntr_lgtd,
ewt40ofrsc.ofr_scnr_mnt_rt ofr_scnr_mnt_rt,
ewt40ofrsc.ebi_rank_nbr ebi_rank_nbr,
ewt40ofrsc.ofr_dcsn_desc ofr_dcsn_desc,
ewt40ofrsc.crp_sip_amt crp_sip_amt,
ewt40ofrsc.crp_pip_amt crp_pip_amt,
ewt40ofrsc.tr_acrg tr_acrg,
ewt40ofrsc.ofr_pymt_mthd_cd ofr_pymt_mthd_cd,
ewt40ofrsc.enrl_intn_sgn_dt enrl_intn_sgn_dt,
ewt40ofrsc.site_rvw_rqst_dt site_rvw_rqst_dt,
ewt40ofrsc.crp_pln_rqst_dt crp_pln_rqst_dt,
ewt40ofrsc.crp_pln_apvl_dt crp_pln_apvl_dt,
ewt40ofrsc.tech_asst_rqst_dt tech_asst_rqst_dt,
ewt40ofrsc.prnt_ofr_scnr_id prnt_ofr_scnr_id,
ewt40ofrsc.cnsv_ctr_seq_nbr cnsv_ctr_seq_nbr,
ewt40ofrsc.cnsv_ctr_sufx_cd cnsv_ctr_sfx_cd,
ewt40ofrsc.cncl_rsn_desc cncl_rsn_desc,
ewt40ofrsc.anstr_ofr_scnr_id anstr_ofr_scnr_id,
ewt40ofrsc.gis_scnr_id gis_scnr_id,
ewt40ofrsc.gis_ofr_cre_ind gis_ofr_cre_ind,
ewt40ofrsc.ctr_strt_dt ctr_strt_dt,
ewt40ofrsc.ctr_apvl_dt ctr_apvl_dt,
ewt40ofrsc.ctr_pymt_amt ctr_pymt_amt,
ewt40ofrsc.cs_est_amt cs_est_amt,
ewt40ofrsc.ctr_end_dt ctr_end_dt,
ewt40ofrsc.crop_rotation_history_ind crop_rotation_history_ind,
ewt40ofrsc.ofr_rank_stat_cd ofr_rank_stat_cd,
ewt40ofrsc.dafp_approved_dafp_aprv_dt,
ewt40ofrsc.long_leaf_pine_plnt_ind long_leaf_pine_plnt_ind,
ewt40ofrsc.ofr_elg_ind ofr_elg_ind,
ewt40ofrsc.ofr_scnr_id ofr_scnr_id,
ewt40ofrsc.ofr_scnr_seq_nbr ofr_scnr_seq_nbr,
ewt40ofrsc.sgnp_id sgnp_id,
null prnt_pgm_yr,
null prnt_adm_st_fsa_cd,
null prnt_adm_cnty_fsa_cd,
null prnt_tr_nbr,
null prnt_ofr_scnr_nm,
null prnt_sgnp_type_desc,
null prnt_sgnp_stype_desc,
null prnt_sgnp_nbr,
null prnt_sgnp_stype_agr_nm,
null prnt_cnsv_ctr_seq_nbr,
null prnt_cnsv_ctr_sfx_cd,
null anstr_pgm_yr,
null anstr_adm_st_fsa_cd,
null anstr_adm_cnty_fsa_cd,
null anstr_tr_nbr,
null anstr_ofr_scnr_nm,
null anstr_sgnp_type_desc,
null anstr_sgnp_stype_desc,
null anstr_sgnp_nbr,
null anstr_sgnp_stype_agr_nm,
null anstr_cnsv_ctr_seq_nbr,
null anstr_cnsv_ctr_sfx_cd,
ewt40ofrsc.prac_mnt_resp_cd prac_mnt_resp_cd,
ewt40ofrsc.ncpld_acrg ncpld_acrg,
ewt40ofrsc.data_stat_cd data_stat_cd,
ewt40ofrsc.last_chg_dt last_chg_dt,
ewt40ofrsc.last_chg_user_nm last_chg_user_nm,
ewt40ofrsc.cre_dt cre_dt,
'D' cdc_oper_cd,
current_timestamp() as load_dt,
'ewt40ofrsc' as data_src_nm,
'{etl_start_date}' as cdc_dt,
1 as row_num_part
from `fsa-{env}-cnsv-cdc`.`ewt40ofrsc`
where ewt40ofrsc.op = 'D'