with tab_incr_dr_ID as
(

SELECT distinct FARM_H_ID incr_dr_id
FROM EDV.FARM_H 
WHERE CAST(cast(LOAD_DT as date) - 1 AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 

UNION

SELECT distinct FARM_H_ID incr_dr_id
FROM EDV.FARM_HS
WHERE CAST(DATA_EFF_STRT_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 
AND CAST(DATA_EFF_END_DT AS DATE) >  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')

UNION

SELECT distinct  FARM_H_ID incr_dr_id
FROM EDV.LOC_AREA_MRT_SRC_RS, EDV.FARM_H H
WHERE (CAST(DATA_EFF_STRT_DT AS DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 
      OR CAST(DATA_EFF_END_DT AS DATE) =   TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD'))
AND CTRY_DIV_MRT_CD = H.ST_FSA_CD
AND LOC_AREA_MRT_CD = H.CNTY_FSA_CD
AND LOC_AREA_MRT_CD_SRC_ACRO = 'FSA'
)
select FH.DURB_ID AS FARM_DURB_ID,
greatest( TO_TIMESTAMP(to_char(CAST(cast(FH.LOAD_DT as date) -1 AS DATE), 'YYYY-MM-DD'),'YYYY-MM-DD'),  
COALESCE(FHS.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),
COALESCE(LOS.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) ) DATA_EFF_STRT_DT, 
(current_date - 1) as CRE_DT,  
FH.ST_FSA_CD AS ST_FSA_CD ,  
FH.CNTY_FSA_CD As CNTY_FSA_CD ,
FH.FARM_NBR AS FARM_NBR,
LOS.CTRY_DIV_NM AS ST_FSA_NM,
LOS.LOC_AREA_NM CNTY_FSA_NM,
FHS.SRC_CRE_DT AS FARM_CRE_DT,
FHS.SRC_LAST_CHG_DT AS FARM_LAST_CHG_DT,
FHS.SRC_LAST_CHG_USER_NM AS FARM_LAST_CHG_USER_NM,
FHS.DATA_STAT_CD AS SRC_DATA_STAT_CD,
FHS.FARM_CMN_NM AS FARM_CMN_NM,
FHS.RCON_PEND_APVL_CD AS RCON_PEND_APVL_CD
FROM 
(
select * from  EDV.FARM_H 
WHERE  FARM_H_ID in (
select incr_dr_ID FROM tab_incr_dr_ID)
AND data_src_nm <> 'SYSGEN'
 ) FH  
LEFT JOIN EDV.FARM_HS FHS ON ( FH.FARM_H_ID = FHS.FARM_H_ID
                    and TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(FHS.data_eff_strt_dt AS DATE)
                    and TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') < CAST(FHS.data_eff_end_dt AS DATE)  
)
LEFT JOIN EDV.LOC_AREA_MRT_SRC_RS  LOS ON (FH.ST_FSA_CD = LOS.CTRY_DIV_MRT_CD  
        AND FH.CNTY_FSA_CD = LOS.LOC_AREA_MRT_CD  
        AND LOS.LOC_AREA_MRT_CD_SRC_ACRO = 'FSA'
 and TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') >= CAST(LOS.data_eff_strt_dt AS DATE)
                    and TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') < CAST(LOS.data_eff_end_dt AS DATE)  
); 
 
