with upsert_data as(
SELECT DISTINCT
DM.HEL_TR_DURB_ID,
DM.DATA_EFF_STRT_DT,
DM.HEL_TR_CD,
DM.HEL_TR_NM,
DM.HEL_TR_DESC
FROM (
SELECT 
HH.DURB_ID AS HEL_TR_DURB_ID,
COALESCE(HS.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')) DATA_EFF_STRT_DT,
HS.HEL_TR_CD,
HS.DMN_VAL_NM AS HEL_TR_NM,
HS.DMN_VAL_DESC AS HEL_TR_DESC,
ROW_NUMBER() OVER ( PARTITION BY COALESCE(HS.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')), HS.HEL_TR_CD ORDER BY HS.DATA_EFF_STRT_DT DESC) AS ROW_NUM_PART
FROM EDV.HEL_TR_RS HS
LEFT JOIN  EDV.HEL_TR_RH  HH  ON (COALESCE(HS.HEL_TR_CD,'[NULL IN SOURCE]') = HH.HEL_TR_CD)
WHERE CAST(HS.DATA_EFF_STRT_DT as DATE) =  TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD') 
AND EXISTS ( SELECT '1' FROM EDV.HEL_TR_RS HS_IN
             WHERE HS_IN.HEL_TR_CD = HS.HEL_TR_CD
             AND CAST(HS_IN.DATA_EFF_END_DT as DATE) > TO_TIMESTAMP('{V_CDC_DT}','YYYY-MM-DD')
		) 
AND HH.DURB_ID IS NOT NULL              
) DM
WHERE DM.ROW_NUM_PART = 1
)
select ud.hel_tr_durb_id,
	'1' as cur_rcd_ind,
	ud.data_eff_strt_dt,
	CAST('9999-12-31' as DATE) as data_eff_end_dt, 
	ud.data_eff_strt_dt AS cre_dt, 
	ud.hel_tr_cd,
	ud.hel_tr_nm,
	ud.hel_tr_desc
from upsert_data ud









