Merge into
EDV.TR_YR_WL_VLT_LS dv
using(select DISTINCT 
MD5(MD5(upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.FARM_NBR ,'--')))||'~~'||MD5(upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.TR_NBR, '-1')))) as FARM_TR_L_ID,
TR_YR_WL_VLT.TR_YR_WL_VLT_ID TR_YR_WL_VLT_ID,TR_YR_WL_VLT.LOAD_DT LOAD_DT,TR_YR_WL_VLT.CDC_DT DATA_EFF_STRT_DT,TR_YR_WL_VLT.DATA_SRC_NM DATA_SRC_NM,TR_YR_WL_VLT.DATA_STAT_CD DATA_STAT_CD,TR_YR_WL_VLT.CRE_DT SRC_CRE_DT,TR_YR_WL_VLT.LAST_CHG_DT SRC_LAST_CHG_DT,TR_YR_WL_VLT.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_YR_WL_VLT.TR_YR_ID TR_YR_ID,TR_YR_WL_VLT.WL_VLT_TYPE_CD SRC_WL_VLT_TYPE_CD,WL_VLT_TYPE_RS.DMN_VAL_NM WL_VLT_TYPE_NM,TR_YR_WL_VLT.PGM_YR PGM_YR ,
TR_YR_WL_VLT.CDC_OPER_CD,
MD5(upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.FARM_NBR ,'--'))||'~~'||upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.TR_NBR, '-1'))||'~~'||TR_YR_WL_VLT.TR_YR_WL_VLT_ID||'~~'||trim(both TR_YR_WL_VLT.DATA_STAT_CD)||'~~'||to_char(TR_YR_WL_VLT.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TR_YR_WL_VLT.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_YR_WL_VLT.LAST_CHG_USER_NM)||'~~'||TR_YR_WL_VLT.TR_YR_ID||'~~'||TR_YR_WL_VLT.WL_VLT_TYPE_CD||'~~'||WL_VLT_TYPE_RS.DMN_VAL_NM||'~~'||TR_YR_WL_VLT.PGM_YR) HASH_DIF
from SQL_FARM_RCD_STG.TR_YR_WL_VLT 
left join(select * from EDV.WL_VLT_TYPE_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) WL_VLT_TYPE_RS 
ON (TR_YR_WL_VLT.WL_VLT_TYPE_CD=WL_VLT_TYPE_RS.DMN_VAL_ID)
where TR_YR_WL_VLT.CDC_OPER_CD IN ('I','UN')
order by TR_YR_WL_VLT.CDC_DT)
stg
 on ( 
coalesce(stg.TR_YR_WL_VLT_ID,0) = coalesce(dv.TR_YR_WL_VLT_ID,0)
 ) 
WHEN MATCHED and dv.LOAD_DT <> stg.LOAD_DT and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') and stg.HASH_DIF <> dv.HASH_DIF THEN UPDATE 
set LOAD_END_DT = stg.LOAD_DT,
DATA_EFF_END_DT = stg.DATA_EFF_STRT_DT
;