INSERT into
EDV.TR_YR_WL_VLT_LS(FARM_TR_L_ID,TR_YR_WL_VLT_ID,LOAD_DT,
DATA_EFF_STRT_DT,
DATA_SRC_NM,
DATA_STAT_CD,
SRC_CRE_DT,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
TR_YR_ID,
SRC_WL_VLT_TYPE_CD,
WL_VLT_TYPE_NM,
PGM_YR, DATA_EFF_END_DT, LOAD_END_DT, HASH_DIF)
(SELECT stg.* from (SELECT DISTINCT 
MD5(MD5(upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.FARM_NBR ,'--')))||'~~'||MD5(upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.TR_NBR, '-1')))) as FARM_TR_L_ID,
TR_YR_WL_VLT.TR_YR_WL_VLT_ID TR_YR_WL_VLT_ID,TR_YR_WL_VLT.LOAD_DT LOAD_DT,TR_YR_WL_VLT.CDC_DT DATA_EFF_STRT_DT,TR_YR_WL_VLT.DATA_SRC_NM DATA_SRC_NM,TR_YR_WL_VLT.DATA_STAT_CD DATA_STAT_CD,TR_YR_WL_VLT.CRE_DT SRC_CRE_DT,TR_YR_WL_VLT.LAST_CHG_DT SRC_LAST_CHG_DT,TR_YR_WL_VLT.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_YR_WL_VLT.TR_YR_ID TR_YR_ID,TR_YR_WL_VLT.WL_VLT_TYPE_CD SRC_WL_VLT_TYPE_CD,WL_VLT_TYPE_RS.DMN_VAL_NM WL_VLT_TYPE_NM,TR_YR_WL_VLT.PGM_YR PGM_YR ,
to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.FARM_NBR ,'--'))||'~~'||upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.TR_NBR, '-1'))||'~~'||TR_YR_WL_VLT.TR_YR_WL_VLT_ID||'~~'||trim(both TR_YR_WL_VLT.DATA_STAT_CD)||'~~'||to_char(TR_YR_WL_VLT.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TR_YR_WL_VLT.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_YR_WL_VLT.LAST_CHG_USER_NM)||'~~'||TR_YR_WL_VLT.TR_YR_ID||'~~'||TR_YR_WL_VLT.WL_VLT_TYPE_CD||'~~'||WL_VLT_TYPE_RS.DMN_VAL_NM||'~~'||TR_YR_WL_VLT.PGM_YR) HASH_DIF
from SQL_FARM_RCD_STG.TR_YR_WL_VLT 
left join(select * from EDV.WL_VLT_TYPE_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) WL_VLT_TYPE_RS 
ON (TR_YR_WL_VLT.WL_VLT_TYPE_CD=WL_VLT_TYPE_RS.DMN_VAL_ID)
where TR_YR_WL_VLT.CDC_OPER_CD IN ('I','UN')
AND MD5(MD5(upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.FARM_NBR ,'--')))||'~~'||MD5(upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.TR_NBR, '-1'))))
IN (Select FARM_TR_L_ID FROM EDV.FARM_TR_L )
 

UNION
 
SELECT DISTINCT 
MD5('-1') as FARM_TR_L_ID,
TR_YR_WL_VLT.TR_YR_WL_VLT_ID TR_YR_WL_VLT_ID,TR_YR_WL_VLT.LOAD_DT LOAD_DT,TR_YR_WL_VLT.CDC_DT DATA_EFF_STRT_DT,TR_YR_WL_VLT.DATA_SRC_NM DATA_SRC_NM,TR_YR_WL_VLT.DATA_STAT_CD DATA_STAT_CD,TR_YR_WL_VLT.CRE_DT SRC_CRE_DT,TR_YR_WL_VLT.LAST_CHG_DT SRC_LAST_CHG_DT,TR_YR_WL_VLT.LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM,TR_YR_WL_VLT.TR_YR_ID TR_YR_ID,TR_YR_WL_VLT.WL_VLT_TYPE_CD SRC_WL_VLT_TYPE_CD,WL_VLT_TYPE_RS.DMN_VAL_NM WL_VLT_TYPE_NM,TR_YR_WL_VLT.PGM_YR PGM_YR ,
to_date('9999-12-31','YYYY-MM-DD') DATA_EFF_END_DT, to_date('9999-12-31','YYYY-MM-DD') LOAD_END_DT, 
MD5(upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.FARM_NBR ,'--'))||'~~'||upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.TR_NBR, '-1'))||'~~'||TR_YR_WL_VLT.TR_YR_WL_VLT_ID||'~~'||trim(both TR_YR_WL_VLT.DATA_STAT_CD)||'~~'||to_char(TR_YR_WL_VLT.CRE_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||to_char(TR_YR_WL_VLT.LAST_CHG_DT,'YYYY-MM-DD HH24:MI:SS.US')||'~~'||trim(both TR_YR_WL_VLT.LAST_CHG_USER_NM)||'~~'||TR_YR_WL_VLT.TR_YR_ID||'~~'||TR_YR_WL_VLT.WL_VLT_TYPE_CD||'~~'||WL_VLT_TYPE_RS.DMN_VAL_NM||'~~'||TR_YR_WL_VLT.PGM_YR) HASH_DIF
from SQL_FARM_RCD_STG.TR_YR_WL_VLT 
left join(select * from EDV.WL_VLT_TYPE_RS
where load_end_dt = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')) WL_VLT_TYPE_RS 
ON (TR_YR_WL_VLT.WL_VLT_TYPE_CD=WL_VLT_TYPE_RS.DMN_VAL_ID)
where TR_YR_WL_VLT.CDC_OPER_CD IN ('I','UN')
AND MD5(MD5(upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.FARM_NBR ,'--')))||'~~'||MD5(upper(coalesce(TR_YR_WL_VLT.ST_FSA_CD ,'--')||'~~'||coalesce(TR_YR_WL_VLT.CNTY_FSA_CD,'--')||'~~'||coalesce(TR_YR_WL_VLT.TR_NBR, '-1'))))
NOT IN (Select FARM_TR_L_ID FROM EDV.FARM_TR_L )
) stg
LEFT JOIN  EDV.TR_YR_WL_VLT_LS dv
ON (
stg.HASH_DIF = dv.HASH_DIF
and dv.LOAD_END_DT = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
)
where dv.HASH_DIF is null
and not exists (select 1 from EDV.TR_YR_WL_VLT_LS ls
				where stg.FARM_TR_L_ID = ls.FARM_TR_L_ID
				and stg.TR_YR_WL_VLT_ID = ls.TR_YR_WL_VLT_ID
				and stg.LOAD_DT = ls.LOAD_DT
			)
)
;

