WITH TMP_FARM_RCON_LS AS
(
    SELECT      DISTINCT FARM_RCON_L_ID
    FROM        EDV.FARM_RCON_LS FRLS
    WHERE       CAST(FRLS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
        
    UNION
    
    SELECT      DISTINCT FARM_RCON_L_ID
    FROM        EDV.FARM_RCON_LS FRLS
                LEFT JOIN EDV.RCON_RS RR ON (FRLS.RCON_ID = RR.RCON_ID)
    WHERE       CAST(RR.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
),
TMP_MIDAS_FARM_RCON_LS AS
(
    SELECT      DISTINCT FARM_RCON_L_ID
    FROM        EDV.MIDAS_FARM_RCON_LS MFRLS
    WHERE       CAST(MFRLS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
                
    UNION
    
    SELECT      DISTINCT MFRLS.FARM_RCON_L_ID
    FROM        (
                    SELECT      DISTINCT FARM_H_ID
                    FROM        EDV.FARM_YR_HS FYS
                    WHERE       CAST(FYS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
                        AND     CAST(FYS.DATA_EFF_END_DT AS DATE) > CAST(FYS.DATA_EFF_STRT_DT AS DATE)
                ) FYS
                LEFT JOIN EDV.FARM_H FH ON ( FH.FARM_H_ID = COALESCE(FYS.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') )
                LEFT JOIN EDV.FARM_RCON_L FRL ON ( COALESCE(FRL.RSLT_FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = FH.FARM_H_ID )
                LEFT JOIN EDV.MIDAS_FARM_RCON_LS MFRLS ON (COALESCE(MFRLS.FARM_RCON_L_ID,'37b55d7a24cd858ff9080194558b03bb') = FRL.FARM_RCON_L_ID)
),
del_data as 
(
SELECT sub1.*
from 
(
SELECT
    PGM_YR
   ,FSA_ST_CNTY_SRGT_ID
   ,FSA_ST_CNTY_DURB_ID
   ,PRNT_FARM_SRGT_ID
   ,PRNT_FARM_DURB_ID
   ,RSLT_FARM_SRGT_ID
   ,RSLT_FARM_DURB_ID
   ,RCON_TYPE_SRGT_ID
   ,RCON_TYPE_DURB_ID
   ,RCON_SEQ_NBR
   ,RCON_APVL_DT
   ,RCON_EFF_DT
   ,RCON_INIT_DT
   ,SRC_DATA_STAT_CD
   ,SRC_CRE_DT
   ,SRC_CRE_USER_NM
   ,SRC_LAST_CHG_DT
   ,SRC_LAST_CHG_USER_NM
   ,DATA_EFF_STRT_DT
FROM (
SELECT DISTINCT FRLS.PGM_YR PGM_YR
    ,COALESCE(FSD_ADM.FSA_ST_CNTY_SRGT_ID, -3) FSA_ST_CNTY_SRGT_ID
    ,COALESCE(FSD_ADM.FSA_ST_CNTY_DURB_ID, -3) FSA_ST_CNTY_DURB_ID
    ,COALESCE(FD_PRNT.FARM_SRGT_ID, -3) PRNT_FARM_SRGT_ID
    ,FD_PRNT.FARM_DURB_ID PRNT_FARM_DURB_ID
    ,COALESCE(FD_RSLT.FARM_SRGT_ID, -3) RSLT_FARM_SRGT_ID
    ,FD_RSLT.FARM_DURB_ID RSLT_FARM_DURB_ID
    ,COALESCE(RD.RCON_TYPE_SRGT_ID, -3) AS RCON_TYPE_SRGT_ID
    ,COALESCE(RD.RCON_TYPE_DURB_ID, -3) AS RCON_TYPE_DURB_ID
    ,RR.RCON_SEQ_NBR RCON_SEQ_NBR
    ,COALESCE(CAST(TO_CHAR(RR.RCON_APVL_DT, 'YYYYMMDD') AS INTEGER), -1) AS RCON_APVL_DT
    ,COALESCE(CAST(TO_CHAR(RR.RCON_EFF_DT, 'YYYYMMDD') AS INTEGER), -1) AS RCON_EFF_DT
    ,COALESCE(CAST(TO_CHAR(RR.RCON_INIT_DT, 'YYYYMMDD') AS INTEGER), -1) AS RCON_INIT_DT
    ,FRLS.DATA_STAT_CD SRC_DATA_STAT_CD
    ,FRLS.SRC_CRE_DT SRC_CRE_DT
    ,CAST('-1' as CHAR) SRC_CRE_USER_NM
    ,FRLS.SRC_LAST_CHG_DT SRC_LAST_CHG_DT
    ,FRLS.SRC_LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
     ,GREATEST(COALESCE(FRLS.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')), 
        COALESCE(RR.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD'))) DATA_EFF_STRT_DT,
     ROW_NUMBER() OVER (PARTITION BY FRLS.PGM_YR, FRH_PRNT.DURB_ID, FRH_RSLT.DURB_ID ORDER BY FRLS.DATA_EFF_STRT_DT DESC, RR.DATA_EFF_STRT_DT DESC ) AS  ROW_NUM_PART   
FROM TMP_FARM_RCON_LS TMP
INNER JOIN EDV.FARM_RCON_LS FRLS ON (TMP.FARM_RCON_L_ID = FRLS.FARM_RCON_L_ID)
LEFT JOIN EDV.FARM_RCON_L FRL ON (COALESCE(FRLS.FARM_RCON_L_ID,'0ab29d0d40925793c05370f0c246b8d6') = FRL.FARM_RCON_L_ID)
LEFT JOIN EDV.RCON_RS RR ON (FRLS.RCON_ID = RR.RCON_ID)
LEFT JOIN FARM_DM_STG.RCON_TYPE_DIM RD ON (RR.SRC_RCON_TYPE_CD= COALESCE(RD.RCON_TYPE_CD, '-1'))
LEFT JOIN CMN_DIM_DM_STG.FSA_ST_CNTY_DIM FSD_ADM ON (
        COALESCE(RR.ST_FSA_CD, '-1') = COALESCE(FSD_ADM.ST_FSA_CD, '-1')
        AND COALESCE(RR.CNTY_FSA_CD, '-1') = COALESCE(FSD_ADM.CNTY_FSA_CD, '-1')
        AND FSD_ADM.CUR_RCD_IND = 1
        )
LEFT JOIN EDV.FARM_H FRH_PRNT ON (COALESCE(FRL.PRNT_FARM_H_ID,'59dcc79c90990c5ef8f95c2fa08d0fae') = FRH_PRNT.FARM_H_ID)
LEFT JOIN CMN_DIM_DM_STG.FARM_DIM FD_PRNT ON (
        FRH_PRNT.DURB_ID = COALESCE(FD_PRNT.FARM_DURB_ID,-1)
        AND FD_PRNT.CUR_RCD_IND = 1
        )
LEFT JOIN EDV.FARM_H FRH_RSLT ON (COALESCE(FRL.RSLT_FARM_H_ID,'7fb82560b2d075a4962e5df9fad37602') = FRH_RSLT.FARM_H_ID)
LEFT JOIN CMN_DIM_DM_STG.FARM_DIM FD_RSLT ON (
        FRH_RSLT.DURB_ID = COALESCE(FD_RSLT.FARM_DURB_ID,'-1')
        AND FD_RSLT.CUR_RCD_IND = 1
        )
 WHERE 
  (
 (
 CAST(FRLS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
 )
 OR
 (
	CAST(RR.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
 )
 )
    AND CAST(FRLS.DATA_EFF_STRT_DT AS DATE) <=  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
    AND CAST(RR.DATA_EFF_STRT_DT AS DATE)  <=  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
    AND FRLS.PGM_YR IS NOT NULL
    AND FD_PRNT.FARM_DURB_ID IS NOT NULL
    AND FD_RSLT.FARM_DURB_ID IS NOT NULL
 )DM
 WHERE DM.ROW_NUM_PART = 1
 
 UNION
 
SELECT
    PGM_YR
   ,FSA_ST_CNTY_SRGT_ID
   ,FSA_ST_CNTY_DURB_ID
   ,PRNT_FARM_SRGT_ID
   ,PRNT_FARM_DURB_ID
   ,RSLT_FARM_SRGT_ID
   ,RSLT_FARM_DURB_ID
   ,RCON_TYPE_SRGT_ID
   ,RCON_TYPE_DURB_ID
   ,RCON_SEQ_NBR
   ,RCON_APVL_DT
   ,RCON_EFF_DT
   ,RCON_INIT_DT
   ,SRC_DATA_STAT_CD
   ,SRC_CRE_DT
   ,SRC_CRE_USER_NM
   ,SRC_LAST_CHG_DT
   ,SRC_LAST_CHG_USER_NM
   ,DATA_EFF_STRT_DT
FROM (
 SELECT /*+ PARALLEL(4) */ DISTINCT 
COALESCE(CAST(MFRLS.TM_PRD_NM AS INTEGER), FIRST_VALUE(FYS.PGM_YR) OVER (PARTITION BY FS.FARM_H_ID ORDER BY FYS.PGM_YR ASC )) AS PGM_YR
    ,COALESCE(FSD_ADM.FSA_ST_CNTY_SRGT_ID, -3) FSA_ST_CNTY_SRGT_ID
    ,COALESCE(FSD_ADM.FSA_ST_CNTY_DURB_ID, -3) FSA_ST_CNTY_DURB_ID
    ,COALESCE(FD_PRNT.FARM_SRGT_ID, -3) PRNT_FARM_SRGT_ID
    ,FD_PRNT.FARM_DURB_ID PRNT_FARM_DURB_ID
    ,COALESCE(FD_RSLT.FARM_SRGT_ID, -3) RSLT_FARM_SRGT_ID
    ,FD_RSLT.FARM_DURB_ID RSLT_FARM_DURB_ID
    ,COALESCE(RD.RCON_TYPE_SRGT_ID, -3) AS RCON_TYPE_SRGT_ID
    ,COALESCE(RD.RCON_TYPE_DURB_ID, -3) AS RCON_TYPE_DURB_ID
    ,MFRLS.RCON_SEQ_NBR RCON_SEQ_NBR
    ,COALESCE(CAST(TO_CHAR(MFRLS.RCON_APVL_DT, 'YYYYMMDD') AS INTEGER), -1) AS RCON_APVL_DT
    ,-1 AS RCON_EFF_DT
    ,COALESCE(CAST(TO_CHAR(MFRLS.RCON_INIT_DT, 'YYYYMMDD') AS INTEGER ), -1) AS RCON_INIT_DT
    ,MFRLS.DATA_STAT_CD SRC_DATA_STAT_CD
    ,MFRLS.SRC_CRE_DT SRC_CRE_DT
    ,MFRLS.SRC_CRE_USER_NM SRC_CRE_USER_NM
    ,MFRLS.SRC_LAST_CHG_DT SRC_LAST_CHG_DT
    ,MFRLS.SRC_LAST_CHG_USER_NM SRC_LAST_CHG_USER_NM
    ,GREATEST(COALESCE(MFRLS.DATA_EFF_STRT_DT, TO_TIMESTAMP('1111-12-31','YYYY-MM-DD')),
        COALESCE(FS.DATA_EFF_STRT_DT,TO_TIMESTAMP('1111-12-31','YYYY-MM-DD'))  ) DATA_EFF_STRT_DT
    ,ROW_NUMBER() OVER (PARTITION BY FYS.PGM_YR, FD_PRNT.FARM_DURB_ID, FD_RSLT.FARM_DURB_ID ORDER BY MFRLS.DATA_EFF_STRT_DT DESC, FS.DATA_EFF_STRT_DT DESC) AS  ROW_NUM_PART
 FROM TMP_MIDAS_FARM_RCON_LS TMP
 INNER JOIN EDV.MIDAS_FARM_RCON_LS MFRLS ON (TMP.FARM_RCON_L_ID = MFRLS.FARM_RCON_L_ID)
 LEFT JOIN EDV.FARM_RCON_L FRL ON (COALESCE(MFRLS.FARM_RCON_L_ID,'37b55d7a24cd858ff9080194558b03bb') = FRL.FARM_RCON_L_ID)
 LEFT JOIN  EDV.FARM_H FH_PRNT ON (COALESCE(FRL.PRNT_FARM_H_ID,'--') = FH_PRNT.FARM_H_ID)
 LEFT JOIN CMN_DIM_DM_STG.FARM_DIM FD_PRNT ON (FH_PRNT.DURB_ID = COALESCE(FD_PRNT.FARM_DURB_ID,-1)
                           AND FD_PRNT.CUR_RCD_IND = 1) 
 LEFT JOIN EDV.FARM_H FH_RSLT ON (COALESCE(FRL.RSLT_FARM_H_ID,'--') = FH_RSLT.FARM_H_ID)
 LEFT JOIN CMN_DIM_DM_STG.FARM_DIM FD_RSLT ON (FH_RSLT.DURB_ID = COALESCE(FD_RSLT.FARM_DURB_ID,-1)
                           AND FD_RSLT.CUR_RCD_IND = 1)
  LEFT JOIN EDV.FARM_H FH ON ( COALESCE(FRL.RSLT_FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = FH.FARM_H_ID
                            ) 
  LEFT JOIN EDV.FARM_YR_HS FYS ON (FH.FARM_H_ID = COALESCE(FYS.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') 
                           AND CAST(FYS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
                            ) 
  LEFT JOIN EDV.FARM_YR_HS FS ON (COALESCE(FYS.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') = COALESCE(FS.FARM_H_ID,'baf6dd71fe45fe2f5c1c0e6724d514fd') 
                           AND CAST(FS.DATA_EFF_END_DT AS DATE) = TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
                           )
LEFT JOIN CMN_DIM_DM_STG.FSA_ST_CNTY_DIM FSD_ADM ON (
        COALESCE(MFRLS.RSLT_ST_FSA_CD, '-1') = COALESCE(FSD_ADM.ST_FSA_CD, '-1')
        AND COALESCE(MFRLS.RSLT_CNTY_FSA_CD, '-1') = COALESCE(FSD_ADM.CNTY_FSA_CD, '-1')
        AND FSD_ADM.CUR_RCD_IND = 1
        )
 LEFT JOIN (
    SELECT FARM_RCON_L_ID
        ,RCON_TYP_CD
    FROM (
        SELECT CASE 
                WHEN L1.FARM_RCON_L_ID IS NOT NULL
                    THEN L1.FARM_RCON_L_ID
                WHEN L2.FARM_RCON_L_ID IS NOT NULL
                    THEN L2.FARM_RCON_L_ID
                END FARM_RCON_L_ID
            ,CASE 
                WHEN RCON_TYP_CD_T = 'D'
                    AND RCON_TYP_CD_M = 'C'
                    THEN 'I'
                WHEN RCON_TYP_CD_T = 'D'
                    AND RCON_TYP_CD_M IS NULL
                    THEN 'D'
                WHEN RCON_TYP_CD_T IS NULL
                    AND RCON_TYP_CD_M = 'C'
                    THEN 'C'
                ELSE ''
                END RCON_TYP_CD
        FROM /*GET 'D' RECORDS */ (
            SELECT LID1.FARM_RCON_L_ID
                ,LID2.RCON_TYP_CD_T
            FROM EDV.MIDAS_FARM_RCON_LS LID1
            INNER JOIN (
                SELECT DISTINCT PRNT_ST_FSA_CD
                    ,PRNT_CNTY_FSA_CD
                    ,PRNT_FARM_NBR
                    ,CASE 
                        WHEN COUNT(CONCAT (
                                    CONCAT (
                                        RSLT_ST_FSA_CD
                                        ,RSLT_CNTY_FSA_CD
                                        )
                                    ,RSLT_FARM_NBR
                                    )) > 1
                            THEN 'D'
                        END AS RCON_TYP_CD_T
                FROM EDV.MIDAS_FARM_RCON_LS
                WHERE DATA_EFF_END_DT = TO_TIMESTAMP('{ETL_DATE}', 'YYYY-MM-DD')
                GROUP BY PRNT_ST_FSA_CD
                    ,PRNT_CNTY_FSA_CD
                    ,PRNT_FARM_NBR
                ) LID2 ON (
                    LID1.PRNT_ST_FSA_CD = LID2.PRNT_ST_FSA_CD
                    AND LID1.PRNT_CNTY_FSA_CD = LID2.PRNT_CNTY_FSA_CD
                    AND LID1.PRNT_FARM_NBR = LID2.PRNT_FARM_NBR
                    )
            ) L1
        FULL JOIN (
        /*GET 'C' RECORDS */ 
            SELECT LID1.FARM_RCON_L_ID
                ,LID2.RCON_TYP_CD_M
            FROM EDV.MIDAS_FARM_RCON_LS LID1
            INNER JOIN (
                SELECT DISTINCT RSLT_ST_FSA_CD
                    ,RSLT_CNTY_FSA_CD
                    ,RSLT_FARM_NBR
                    ,CASE 
                        WHEN COUNT(CONCAT (
                                    CONCAT (
                                        PRNT_ST_FSA_CD
                                        ,PRNT_CNTY_FSA_CD
                                        )
                                    ,PRNT_FARM_NBR
                                    )) > 1
                            THEN 'C'
                        END AS RCON_TYP_CD_M
                FROM EDV.MIDAS_FARM_RCON_LS
                WHERE DATA_EFF_END_DT = TO_TIMESTAMP('{ETL_DATE}', 'YYYY-MM-DD')
                GROUP BY RSLT_ST_FSA_CD
                    ,RSLT_CNTY_FSA_CD
                    ,RSLT_FARM_NBR
                ) LID2 ON (
                    LID1.RSLT_ST_FSA_CD = LID2.RSLT_ST_FSA_CD
                    AND LID1.RSLT_CNTY_FSA_CD = LID2.RSLT_CNTY_FSA_CD
                    AND LID1.RSLT_FARM_NBR = LID2.RSLT_FARM_NBR
                    )
            ) L2 ON L1.FARM_RCON_L_ID = L2.FARM_RCON_L_ID
        ) sub_1
    ) RT ON (RT.FARM_RCON_L_ID = MFRLS.FARM_RCON_L_ID)
 LEFT JOIN FARM_DM_STG.RCON_TYPE_DIM RD ON (RD.RCON_TYPE_CD = RT.RCON_TYP_CD)
 WHERE 
  (
 (
 CAST(MFRLS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
 
 )
 OR
 (
 CAST(FS.DATA_EFF_END_DT AS DATE) =  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
 )
 )
    AND CAST(MFRLS.DATA_EFF_STRT_DT AS DATE) <=  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
    AND CAST(FYS.DATA_EFF_STRT_DT AS DATE)  <=  TO_TIMESTAMP('{ETL_DATE}','YYYY-MM-DD')
    AND FS.PGM_YR IS NOT NULL
    AND FD_PRNT.FARM_DURB_ID IS NOT NULL
    AND FD_RSLT.FARM_DURB_ID IS NOT NULL
 )DM
 WHERE DM.ROW_NUM_PART = 1
 ) sub1
)
select  
	(current_date) as cre_dt,
	(current_date) as last_chg_dt, 
	'I' as data_stat_cd, 
	pgm_yr, 
	fsa_st_cnty_srgt_id, 
	fsa_st_cnty_durb_id, 
	prnt_farm_srgt_id, 
	prnt_farm_durb_id, 
	rslt_farm_srgt_id, 
	rslt_farm_durb_id, 
	rcon_type_srgt_id, 
	rcon_type_durb_id, 
	rcon_seq_nbr, 
	rcon_apvl_dt, 
	rcon_eff_dt, 
	rcon_init_dt, 
	src_data_stat_cd, 
	src_cre_dt, 
	src_cre_user_nm, 
	src_last_chg_dt, 
	src_last_chg_user_nm
from del_data
where fsa_st_cnty_srgt_id > 0
order by fsa_st_cnty_srgt_id asc