SELECT      DISTINCT

            EXTENSION_TYPE.EXTENSION_TYPE_DESCRIPTION EXTN_TYPE_DESC,

            EXTENSION_TYPE.EXTENSION_TYPE_CODE EXTN_TYPE_CD,

            EXTENSION_TYPE.FISCAL_YEAR FSCL_YR,

            EXTENSION_TYPE.DATA_STATUS_CODE DATA_STAT_CD,

            EXTENSION_TYPE.CREATION_DATE CRE_DT,

            EXTENSION_TYPE.CREATION_USER_NAME CRE_USER_NM,

            EXTENSION_TYPE.LAST_CHANGE_DATE LAST_CHG_DT,

            EXTENSION_TYPE.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,

            EXTENSION_TYPE.EFFECTIVE_PERIOD_START_DATE EFF_PRD_STRT_DT,

            EXTENSION_TYPE.EFFECTIVE_PERIOD_END_DATE EFF_PRD_END_DT,

            OP AS CDC_OPER_CD,

            1 AS ROW_NUM_PART

FROM        EXTENSION_TYPE

WHERE       OP <> 'D'



UNION



SELECT      DISTINCT

            EXTENSION_TYPE.EXTENSION_TYPE_DESCRIPTION EXTN_TYPE_DESC,

            EXTENSION_TYPE.EXTENSION_TYPE_CODE EXTN_TYPE_CD,

            EXTENSION_TYPE.FISCAL_YEAR FSCL_YR,

            EXTENSION_TYPE.DATA_STATUS_CODE DATA_STAT_CD,

            EXTENSION_TYPE.CREATION_DATE CRE_DT,

            EXTENSION_TYPE.CREATION_USER_NAME CRE_USER_NM,

            EXTENSION_TYPE.LAST_CHANGE_DATE LAST_CHG_DT,

            EXTENSION_TYPE.LAST_CHANGE_USER_NAME LAST_CHG_USER_NM,

            EXTENSION_TYPE.EFFECTIVE_PERIOD_START_DATE EFF_PRD_STRT_DT,

            EXTENSION_TYPE.EFFECTIVE_PERIOD_END_DATE EFF_PRD_END_DT,

            'D' CDC_OPER_CD,

            1 AS ROW_NUM_PART

FROM       EXTENSION_TYPE

WHERE       OP = 'D'