INSERT into
EDV.FRS_DMN_RH(DMN_NM,
DATA_SRC_NM,
LOAD_DT)
(
SELECT 
stg.DMN_NM,
stg.DATA_SRC_NM,
stg.LOAD_DT
from (
SELECT DISTINCT
coalesce(DMN.DMN_NM, '[NULL IN SOURCE]') DMN_NM,
DMN.DATA_SRC_NM DATA_SRC_NM,
DMN.LOAD_DT LOAD_DT,
ROW_NUMBER() OVER (PARTITION BY DMN.DMN_NM ORDER BY DMN.CDC_DT desc, DMN.LOAD_DT desc) STG_EFF_DT_RANK
FROM SQL_FARM_RCD_STG.DMN

where DMN.cdc_oper_cd IN ('I','UN','D')
) stg 
LEFT JOIN  EDV.FRS_DMN_RH dv
 ON (
stg.DMN_NM = dv.DMN_NM
)
where (
dv.DMN_NM IS NULL
)
and stg.STG_EFF_DT_RANK = 1
);