SELECT PGM_YR,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
TR_NBR,
OFR_SCNR_NM,
MNL_RT_ENTR_IND,
WT_AVG_SOIL_RNT_RT,
OFR_SCNR_MNT_RT,
WT_AVG_INCTV_RT,
WT_AVG_SIP_RT_ACRG,
CRP_SIP_ACRG,
OFR_SCNR_ID,
OFR_MNL_RT_DTL_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
CDC_OPER_CD,
ITF_WT_AVG_SOIL_RNT_RT,
ITF_WT_AVG_INCTV_RT,
''  HASH_DIF,
current_timestamp LOAD_DT,
'CNSV'  DATA_SRC_NM,
'{ETL_START_DATE}' AS CDC_DT FROM ( SELECT * FROM 
(
SELECT DISTINCT PGM_YR,
ADM_ST_FSA_CD,
ADM_CNTY_FSA_CD,
SGNP_TYPE_DESC,
SGNP_STYPE_DESC,
SGNP_NBR,
SGNP_STYPE_AGR_NM,
TR_NBR,
OFR_SCNR_NM,
MNL_RT_ENTR_IND,
WT_AVG_SOIL_RNT_RT,
OFR_SCNR_MNT_RT,
WT_AVG_INCTV_RT,
WT_AVG_SIP_RT_ACRG,
CRP_SIP_ACRG,
OFR_SCNR_ID,
OFR_MNL_RT_DTL_ID,
DATA_STAT_CD,
CRE_DT,
LAST_CHG_DT,
LAST_CHG_USER_NM,
OP CDC_OPER_CD,
ROW_NUMBER() over ( partition by 
OFR_MNL_RT_DTL_ID
order by TBL_PRIORITY ASC, LAST_CHG_DT DESC ) AS row_num_part
FROM
(
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
OFFER_MANUAL_RATE_DETAIL.MNL_RT_ENTR_IND MNL_RT_ENTR_IND,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_SOIL_RNT_RT WT_AVG_SOIL_RNT_RT,
OFFER_MANUAL_RATE_DETAIL.OFR_SCNR_MNT_RT OFR_SCNR_MNT_RT,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_INCTV_RT WT_AVG_INCTV_RT,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_SIP_RT_ACRG WT_AVG_SIP_RT_ACRG,
OFFER_MANUAL_RATE_DETAIL.CRP_SIP_ACRG CRP_SIP_ACRG,
OFFER_MANUAL_RATE_DETAIL.OFR_SCNR_ID OFR_SCNR_ID,
OFFER_MANUAL_RATE_DETAIL.OFR_MNL_RT_DTL_ID OFR_MNL_RT_DTL_ID,
OFFER_MANUAL_RATE_DETAIL.ITF_WT_AVG_SOIL_RNT_RT ITF_WT_AVG_SOIL_RNT_RT,
OFFER_MANUAL_RATE_DETAIL.ITF_WT_AVG_INCTV_RT ITF_WT_AVG_INCTV_RT,
OFFER_MANUAL_RATE_DETAIL.DATA_STAT_CD DATA_STAT_CD,
OFFER_MANUAL_RATE_DETAIL.CRE_DT CRE_DT,
OFFER_MANUAL_RATE_DETAIL.LAST_CHG_DT LAST_CHG_DT,
OFFER_MANUAL_RATE_DETAIL.LAST_CHG_USER_NM LAST_CHG_USER_NM,
OFFER_MANUAL_RATE_DETAIL.OP,
1 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."OFFER_MANUAL_RATE_DETAIL" OFFER_MANUAL_RATE_DETAIL 
LEFT JOIN "fsa-{env}-cnsv".EWT40OFRSC 
ON (OFFER_MANUAL_RATE_DETAIL.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN "fsa-{env}-cnsv".EWT14SGNP 
ON (EWT14SGNP.SGNP_ID = EWT40OFRSC.SGNP_ID  ) 
WHERE OFFER_MANUAL_RATE_DETAIL.OP <> 'D' AND
OFFER_MANUAL_RATE_DETAIL.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
OFFER_MANUAL_RATE_DETAIL.MNL_RT_ENTR_IND MNL_RT_ENTR_IND,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_SOIL_RNT_RT WT_AVG_SOIL_RNT_RT,
OFFER_MANUAL_RATE_DETAIL.OFR_SCNR_MNT_RT OFR_SCNR_MNT_RT,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_INCTV_RT WT_AVG_INCTV_RT,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_SIP_RT_ACRG WT_AVG_SIP_RT_ACRG,
OFFER_MANUAL_RATE_DETAIL.CRP_SIP_ACRG CRP_SIP_ACRG,
OFFER_MANUAL_RATE_DETAIL.OFR_SCNR_ID OFR_SCNR_ID,
OFFER_MANUAL_RATE_DETAIL.OFR_MNL_RT_DTL_ID OFR_MNL_RT_DTL_ID,
OFFER_MANUAL_RATE_DETAIL.ITF_WT_AVG_SOIL_RNT_RT ITF_WT_AVG_SOIL_RNT_RT,
OFFER_MANUAL_RATE_DETAIL.ITF_WT_AVG_INCTV_RT ITF_WT_AVG_INCTV_RT,
OFFER_MANUAL_RATE_DETAIL.DATA_STAT_CD DATA_STAT_CD,
OFFER_MANUAL_RATE_DETAIL.CRE_DT CRE_DT,
OFFER_MANUAL_RATE_DETAIL.LAST_CHG_DT LAST_CHG_DT,
OFFER_MANUAL_RATE_DETAIL.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT40OFRSC.OP,
2 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."EWT40OFRSC" EWT40OFRSC 
JOIN "fsa-{env}-cnsv".OFFER_MANUAL_RATE_DETAIL 
ON (OFFER_MANUAL_RATE_DETAIL.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
LEFT JOIN "fsa-{env}-cnsv".EWT14SGNP 
ON (EWT14SGNP.SGNP_ID = EWT40OFRSC.SGNP_ID  ) 
WHERE EWT40OFRSC.OP <> 'D' AND
EWT40OFRSC.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

UNION
SELECT 
EWT40OFRSC.PGM_YR PGM_YR,
EWT40OFRSC.ADM_ST_FSA_CD ADM_ST_FSA_CD,
EWT40OFRSC.ADM_CNTY_FSA_CD ADM_CNTY_FSA_CD,
EWT14SGNP.SGNP_TYPE_DESC SGNP_TYPE_DESC,
EWT14SGNP.SGNP_STYPE_DESC SGNP_STYPE_DESC,
EWT14SGNP.SGNP_NBR SGNP_NBR,
EWT14SGNP.SGNP_STYPE_AGR_NM SGNP_STYPE_AGR_NM,
EWT40OFRSC.TR_NBR TR_NBR,
EWT40OFRSC.OFR_SCNR_NM OFR_SCNR_NM,
OFFER_MANUAL_RATE_DETAIL.MNL_RT_ENTR_IND MNL_RT_ENTR_IND,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_SOIL_RNT_RT WT_AVG_SOIL_RNT_RT,
OFFER_MANUAL_RATE_DETAIL.OFR_SCNR_MNT_RT OFR_SCNR_MNT_RT,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_INCTV_RT WT_AVG_INCTV_RT,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_SIP_RT_ACRG WT_AVG_SIP_RT_ACRG,
OFFER_MANUAL_RATE_DETAIL.CRP_SIP_ACRG CRP_SIP_ACRG,
OFFER_MANUAL_RATE_DETAIL.OFR_SCNR_ID OFR_SCNR_ID,
OFFER_MANUAL_RATE_DETAIL.OFR_MNL_RT_DTL_ID OFR_MNL_RT_DTL_ID,
OFFER_MANUAL_RATE_DETAIL.ITF_WT_AVG_SOIL_RNT_RT ITF_WT_AVG_SOIL_RNT_RT,
OFFER_MANUAL_RATE_DETAIL.ITF_WT_AVG_INCTV_RT ITF_WT_AVG_INCTV_RT,
OFFER_MANUAL_RATE_DETAIL.DATA_STAT_CD DATA_STAT_CD,
OFFER_MANUAL_RATE_DETAIL.CRE_DT CRE_DT,
OFFER_MANUAL_RATE_DETAIL.LAST_CHG_DT LAST_CHG_DT,
OFFER_MANUAL_RATE_DETAIL.LAST_CHG_USER_NM LAST_CHG_USER_NM,
EWT14SGNP.OP,
3 AS TBL_PRIORITY
FROM "fsa-{env}-cnsv-cdc"."EWT14SGNP" EWT14SGNP 
LEFT JOIN "fsa-{env}-cnsv".EWT40OFRSC 
ON (EWT14SGNP.SGNP_ID = EWT40OFRSC.SGNP_ID  ) 
JOIN "fsa-{env}-cnsv".OFFER_MANUAL_RATE_DETAIL 
ON (OFFER_MANUAL_RATE_DETAIL.OFR_SCNR_ID = EWT40OFRSC.OFR_SCNR_ID) 
WHERE EWT14SGNP.OP <> 'D' AND
EWT14SGNP.dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}'

) STG_ALL
) STG_UNQ
WHERE row_num_part = 1
AND (
 (COALESCE(CAST(CRE_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
    AND
    (COALESCE(CAST(LAST_CHG_DT AS DATE), DATE '1900-01-01') <= CAST('{ETL_START_DATE}'  AS DATE))
)
UNION
SELECT DISTINCT
NULL PGM_YR,
NULL ADM_ST_FSA_CD,
NULL ADM_CNTY_FSA_CD,
NULL SGNP_TYPE_DESC,
NULL SGNP_STYPE_DESC,
NULL SGNP_NBR,
NULL SGNP_STYPE_AGR_NM,
NULL TR_NBR,
NULL OFR_SCNR_NM,
OFFER_MANUAL_RATE_DETAIL.MNL_RT_ENTR_IND MNL_RT_ENTR_IND,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_SOIL_RNT_RT WT_AVG_SOIL_RNT_RT,
OFFER_MANUAL_RATE_DETAIL.OFR_SCNR_MNT_RT OFR_SCNR_MNT_RT,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_INCTV_RT WT_AVG_INCTV_RT,
OFFER_MANUAL_RATE_DETAIL.WT_AVG_SIP_RT_ACRG WT_AVG_SIP_RT_ACRG,
OFFER_MANUAL_RATE_DETAIL.CRP_SIP_ACRG CRP_SIP_ACRG,
OFFER_MANUAL_RATE_DETAIL.OFR_SCNR_ID OFR_SCNR_ID,
OFFER_MANUAL_RATE_DETAIL.OFR_MNL_RT_DTL_ID OFR_MNL_RT_DTL_ID,
OFFER_MANUAL_RATE_DETAIL.ITF_WT_AVG_SOIL_RNT_RT ITF_WT_AVG_SOIL_RNT_RT,
OFFER_MANUAL_RATE_DETAIL.ITF_WT_AVG_INCTV_RT ITF_WT_AVG_INCTV_RT,
OFFER_MANUAL_RATE_DETAIL.DATA_STAT_CD DATA_STAT_CD,
OFFER_MANUAL_RATE_DETAIL.CRE_DT CRE_DT,
OFFER_MANUAL_RATE_DETAIL.LAST_CHG_DT LAST_CHG_DT,
OFFER_MANUAL_RATE_DETAIL.LAST_CHG_USER_NM LAST_CHG_USER_NM,
'D' OP,
1 AS row_num_part
FROM "fsa-{env}-cnsv-cdc".OFFER_MANUAL_RATE_DETAIL OFFER_MANUAL_RATE_DETAIL
WHERE OP = 'D'
AND dart_filedate BETWEEN DATE '{ETL_START_DATE}' AND DATE '{ETL_END_DATE}' 
)