INSERT INTO pymt_dm_stg.DA_PRIM_CUST_ATRB_FACT(
PRPS_PYMT_ID,
PYMT_ATRB_ID,
CMDY_CD,
OBL_CNFRM_NBR,
OVRRD_SBSD_PRD_STRT_YR,
PROC_RQST_REF_NBR,
PRPS_PYMT_AMT,
PYMT_ATRB_RVRS_DT,
APP_3_OWNSHP_LVL_LMT_IND,
HRCH_PYMT_LMT_IND,
PRST_OPYMT_ATRB_IND,
PYMT_LMT_IND,
AGI_ELG_IND,
MBR_CTRB_ELG_IND,
SBST_CHG_ELG_IND,
PMIT_ENTY_ELG_IND,
FGN_PRSN_ELG_IND,
PYMT_LMT_YR,
RCD_REF_PRIM_ID,
RCD_REF_SCND_ID,
SBSD_PRD_STRT_YR,
SRC_CRE_DT,
SRC_CRE_USER_NM,
SRC_DATA_STAT_CD,
SRC_LAST_CHG_DT,
SRC_LAST_CHG_USER_NM,
NET_PYMT_AMT,
PYMT_ATRB_AMT,
RDN_AMT,
TAX_ID_TYPE_CD,
BUS_TYPE_CD,
PYMT_ATRB_BUS_CAT_CD,
PGM_INELG_RSN_TYPE_CD,
PYMT_PTY_RLT_CD,
CASH_RENT_CPLD_FCTR,
PYMT_ATRB_SHR_PCT,
CMB_PTY_PYMT_SHR_PCT,
PAID_PTY_SHR_PCT,
MBR_SHR_PCT,
OWNSHP_HRCH_LVL_SHR_PCT,
ACCT_PGM_DURB_ID,
ACCT_REF_PRIM_ID_TYPE_DURB_ID,
ACCT_REF_SCND_ID_TYPE_DURB_ID,
FSA_ST_CNTY_DURB_ID,
FSA_ST_CNTY_SRGT_ID,
CUST_DURB_ID,
CUST_SRGT_ID,
RPT_FSA_ST_CNTY_SRGT_ID,
RPT_FSA_ST_CNTY_DURB_ID,
LTD_PYMT_PGM_SRGT_ID,
LTD_PYMT_PGM_DURB_ID,
CRE_DT,
LAST_CHG_DT,
DATA_STAT_CD,
DART_ETL_LAST_CHG_DT
)
Select  /*+ parallel (12) */
 DV.PRPS_PYMT_ID,
 DV.PYMT_ATRB_ID,  
 DV.CMDY_CD , 
 DV.OBL_CNFRM_NBR, 
 DV.OVRRD_SBSD_PRD_STRT_YR, 
 DV.PROC_RQST_REF_NBR, 
 DV.PRPS_PYMT_AMT, 
 DV.PYMT_ATRB_RVRS_DT,
 DV.APP_3_OWNSHP_LVL_LMT_IND,
 DV.HRCH_PYMT_LMT_IND, 
 DV.PRST_OPYMT_ATRB_IND,
 DV.PYMT_LMT_IND,
 DV.AGI_ELG_IND,
 DV.MBR_CTRB_ELG_IND,
 DV.SBST_CHG_ELG_IND,
 DV.PMIT_ENTY_ELG_IND,
 DV.FGN_PRSN_ELG_IND,
 DV.PYMT_LMT_YR,
 DV.RCD_REF_PRIM_ID,
 DV.RCD_REF_SCND_ID,
 DV.SBSD_PRD_STRT_YR,
 DV.SRC_CRE_DT,
 DV.SRC_CRE_USER_NM,
 DV.SRC_DATA_STAT_CD,
 DV.SRC_LAST_CHG_DT,
 DV.SRC_LAST_CHG_USER_NM,
 DV.NET_PYMT_AMT,
 DV.PYMT_ATRB_AMT,
 DV.RDN_AMT,
 DV.TAX_ID_TYPE_CD,
 DV.BUS_TYPE_CD,
 DV.PYMT_ATRB_BUS_CAT_CD,
 DV.PGM_INELG_RSN_TYPE_CD,
 DV.PYMT_PTY_RLT_CD,
 DV.CASH_RENT_CPLD_FCTR,
 DV.PYMT_ATRB_SHR_PCT,
 DV.CMB_PTY_PYMT_SHR_PCT,
 DV.PAID_PTY_SHR_PCT,
 DV.MBR_SHR_PCT,
 DV.OWNSHP_HRCH_LVL_SHR_PCT,
 DV.ACCT_PGM_DURB_ID,
 DV.ACCT_REF_PRIM_ID_TYPE_DURB_ID,
 DV.ACCT_REF_SCND_ID_TYPE_DURB_ID,
 DV.FSA_ST_CNTY_DURB_ID,
 DV.FSA_ST_CNTY_SRGT_ID,
 DV.CUST_DURB_ID,
 DV.CUST_SRGT_ID,
 DV.RPT_FSA_ST_CNTY_SRGT_ID,
 DV.RPT_FSA_ST_CNTY_DURB_ID,
 DV.LTD_PYMT_PGM_SRGT_ID,
 DV.LTD_PYMT_PGM_DURB_ID,
 DV.CRE_DT,
 DV.LAST_CHG_DT,
 'A' DATA_STAT_CD,
 TO_TIMESTAMP('{ETL_START_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF') DART_ETL_LAST_CHG_DT
--  ,CASE
--    WHEN 
--         DV.PRPS_PYMT_ID IS NOT NULL
--    THEN 0
--    ELSE 1 
--    END DEF_ERR_IND
--  ,cast(DV.PRPS_PYMT_ID as numeric) BUS_KEY
--  /*used by DS job to detect multiple BK records (for single AK field, no hashing required) */
--  ,('PRPS_PYMT_ID:'||DV.PRPS_PYMT_ID ) BUS_KEY_ERR
 From (
 
 SELECT DV_ALL.* FROM (
 
 Select 
 DV_DR.PRPS_PYMT_ID,  
 PYMT_ATRB_LS.PYMT_ATRB_ID,
 DV_DR.CMDY_CD , 
 DV_DR.OBL_CNFRM_NBR, 
 DV_DR.OVRRD_SBSD_PRD_STRT_YR, 
 DV_DR.PROC_RQST_REF_NBR, 
 DV_DR.PYMT_AMT PRPS_PYMT_AMT, 
 DV_DR.PYMT_ATRB_RVRS_DT,
 Case UPPER(DV_DR.APP_3_OWNSHP_LVL_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS APP_3_OWNSHP_LVL_LMT_IND,
 Case  UPPER(DV_DR.HRCH_PYMT_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS HRCH_PYMT_LMT_IND,
 Case  UPPER(DV_DR.PRST_OPYMT_ATRB_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS PRST_OPYMT_ATRB_IND,
 Case  UPPER(DV_DR.PYMT_LMT_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS PYMT_LMT_IND,
 Case UPPER(PYMT_ATRB_LS.AGI_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS AGI_ELG_IND,
 Case UPPER(PYMT_ATRB_LS.MBR_CTRB_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS MBR_CTRB_ELG_IND,
 Case UPPER(PYMT_ATRB_LS.SBST_CHG_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS SBST_CHG_ELG_IND,
 Case UPPER(PYMT_ATRB_LS.PMIT_ENTY_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS PMIT_ENTY_ELG_IND,
 Case UPPER(PYMT_ATRB_LS.FGN_PRSN_ELG_IND) when 'Y' Then 1  when 'N' Then 0 else -1 END AS FGN_PRSN_ELG_IND,
 DV_DR.PYMT_LMT_YR,
 DV_DR.RCD_REF_PRIM_ID,
 DV_DR.RCD_REF_SCND_ID,
 coalesce(PGM_YR_DIM.PGM_YR,-1) SBSD_PRD_STRT_YR,
 DV_DR.SRC_CRE_DT,
 DV_DR.SRC_CRE_USER_NM,
 DV_DR.DATA_STAT_CD SRC_DATA_STAT_CD,
 DV_DR.SRC_LAST_CHG_DT,
 DV_DR.SRC_LAST_CHG_USER_NM,
 PYMT_ATRB.NET_PYMT_AMT,
 PYMT_ATRB.PYMT_ATRB_AMT,
 PYMT_ATRB_RDN.PYMT_ATRB_RDN_AMT RDN_AMT,
 PYMT_ATRB_LS.TAX_ID_TYPE_CD,
 PYMT_ATRB_LS.BUS_TYPE_CD,
 PYMT_ATRB_LS.PYMT_ATRB_BUS_CAT_CD,
 PYMT_ATRB_LS.PGM_INELG_RSN_TYPE_CD,
 PYMT_ATRB_LS.PYMT_PTY_RLT_CD,
 PYMT_ATRB_LS.CASH_RENT_CPLD_FCTR,
 PYMT_ATRB_LS.PYMT_ATRB_SHR_PCT,
 PYMT_ATRB_LS.CMB_PTY_PYMT_SHR_PCT,
 PYMT_ATRB_LS.PAID_PTY_SHR_PCT,
 PYMT_ATRB_LS.MBR_SHR_PCT,
 PYMT_ATRB_LS.OWNSHP_HRCH_LVL_SHR_PCT,
 coalesce(ACCT_PGM_DIM.ACCT_PGM_DURB_ID,-3) ACCT_PGM_DURB_ID,
 coalesce(ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_TYPE_DURB_ID,-3) ACCT_REF_PRIM_ID_TYPE_DURB_ID,
 coalesce(ACCT_REF_TYPE_SCND_DIM.ACCT_REF_TYPE_DURB_ID,-3) ACCT_REF_SCND_ID_TYPE_DURB_ID,
 coalesce(FSA_ST_CNTY_DIM.FSA_ST_CNTY_DURB_ID,-3) FSA_ST_CNTY_DURB_ID,
 coalesce(FSA_ST_CNTY_DIM.FSA_ST_CNTY_SRGT_ID,-3) FSA_ST_CNTY_SRGT_ID,
 coalesce(CUST_DIM.CUST_DURB_ID,-3) CUST_DURB_ID,
coalesce (CUST_DIM.CUST_SRGT_ID,-3) CUST_SRGT_ID,
coalesce (RPT_FSA_ST_CNTY_DIM.RPT_FSA_ST_CNTY_SRGT_ID,-3) RPT_FSA_ST_CNTY_SRGT_ID,
coalesce (RPT_FSA_ST_CNTY_DIM.RPT_FSA_ST_CNTY_DURB_ID,-3) RPT_FSA_ST_CNTY_DURB_ID,
coalesce (LTD_PYMT_PGM_DIM.LTD_PYMT_PGM_DURB_ID,-3) LTD_PYMT_PGM_DURB_ID,
coalesce (LTD_PYMT_PGM_DIM.LTD_PYMT_PGM_SRGT_ID,-3) LTD_PYMT_PGM_SRGT_ID
 , TO_TIMESTAMP ('{ETL_START_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF') CRE_DT 
 , TO_TIMESTAMP ('{ETL_START_DATE}', 'YYYY-MM-DD HH24:MI:SS.FF') LAST_CHG_DT
 ,RANK() over ( partition by      DV_DR.PRPS_PYMT_ID     order by DV_DR.PRPS_PYMT_ID asc,
         CASE DV_DR.DATA_STAT_CD
         WHEN 'A' THEN 1
         WHEN 'I' THEN 2
         WHEN 'D' THEN 3
         ELSE 4
         END ASC,
      DV_DR.SRC_CRE_DT DESC NULLS LAST
       )  as Rank_Part      
 
 From (Select * From EDV.DIR_ATRB_PRPS_PYMT_LS  
        where (DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')
        AND (DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
         --And PRPS_PYMT_ID IN (260300,985150,8981182)
      ) DV_DR
 
 Left Join 
          (
          Select PRPS_PYMT_ID, SUM(COALESCE(NET_PYMT_AMT,0)) NET_PYMT_AMT, SUM(COALESCE(PYMT_ATRB_AMT,0)) PYMT_ATRB_AMT  From (
            Select DV2.PRPS_PYMT_ID, SUM(COALESCE(DV2.NET_PYMT_AMT,0)) NET_PYMT_AMT ,SUM(COALESCE(PYMT_ATRB_AMT,0)) PYMT_ATRB_AMT  from  EDV.PYMT_ATRB_LS DV2 where DV2.DATA_STAT_CD <>'B'
             And (DV2.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') 
             AND (DV2.DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
             group by DV2.PRPS_PYMT_ID
           UNION ALL
            Select DV3.PRPS_PYMT_ID, SUM(COALESCE(DV3.NET_PYMT_AMT,0)) NET_PYMT_AMT ,SUM(COALESCE(PYMT_ATRB_AMT,0)) PYMT_ATRB_AMT  from  EDV.PR_PYMT_ATRB_LS DV3 where   DV3.DATA_STAT_CD <>'B'
             And (DV3.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') 
             AND (DV3.DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
             group by DV3.PRPS_PYMT_ID
          ) as t1 group by t1.PRPS_PYMT_ID
      ) PYMT_ATRB
 On DV_DR.PRPS_PYMT_ID = PYMT_ATRB.PRPS_PYMT_ID
 
 Left Join 
 (  
 Select * From (
 SELECT   PYMT_ATRB_UNION.*, ROW_NUMBER () OVER (PARTITION BY PRPS_PYMT_ID ORDER BY SRC_LAST_CHG_DT DESC) AS PRECEDENCE
  FROM   (SELECT   PYMT_ATRB_ID,PRPS_PYMT_ID,
                   TAX_ID_TYPE_CD,
                   BUS_TYPE_CD,
                   PYMT_ATRB_BUS_CAT_CD,
                   PGM_INELG_RSN_TYPE_CD,
                   PYMT_PTY_RLT_CD,
                   AGI_ELG_IND,
                   MBR_CTRB_ELG_IND,
                   SBST_CHG_ELG_IND,
                   PMIT_ENTY_ELG_IND,
                   FGN_PRSN_ELG_IND,
                   CASH_RENT_CPLD_FCTR,
                   PYMT_ATRB_SHR_PCT,
                   CMB_PTY_PYMT_SHR_PCT,
                   PAID_PTY_SHR_PCT,
                   MBR_SHR_PCT,
                   OWNSHP_HRCH_LVL_SHR_PCT,
                   SRC_LAST_CHG_DT
            FROM   EDV.PYMT_ATRB_LS
           WHERE   DATA_STAT_CD <> 'B'
                   AND  (DATA_EFF_END_DT) = TO_TIMESTAMP ('9999-12-31', 'YYYY-MM-DD')
                   AND (DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
          UNION
          SELECT  PYMT_ATRB_ID, PRPS_PYMT_ID,
                   TAX_ID_TYPE_CD,
                   BUS_TYPE_CD,
                   PYMT_ATRB_BUS_CAT_CD,
                   PGM_INELG_RSN_TYPE_CD,
                   PYMT_PTY_RLT_CD,
                   AGI_ELG_IND,
                   MBR_CTRB_ELG_IND,
                   SBST_CHG_ELG_IND,
                   PMIT_ENTY_ELG_IND,
                   FGN_PRSN_ELG_IND,
                   CASH_RENT_CPLD_FCTR,
                   PYMT_ATRB_SHR_PCT,
                   CMB_PTY_PYMT_SHR_PCT,
                   PAID_PTY_SHR_PCT,
                   MBR_SHR_PCT,
                   OWNSHP_HRCH_LVL_SHR_PCT,
                   SRC_LAST_CHG_DT
            FROM   EDV.PR_PYMT_ATRB_LS
           WHERE   DATA_STAT_CD <> 'B'
                   AND  (DATA_EFF_END_DT) = TO_TIMESTAMP ('9999-12-31', 'YYYY-MM-DD')
                   AND (DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
          )  PYMT_ATRB_UNION
    ) as t2 where t2.PRECEDENCE =1
 ) PYMT_ATRB_LS
 ON ( DV_DR.PRPS_PYMT_ID = PYMT_ATRB_LS.PRPS_PYMT_ID )
 
 Left Join 
 (
     Select  PRPS_PYMT_ID, SUM(COALESCE(PYMT_ATRB_RDN_AMT,0)) PYMT_ATRB_RDN_AMT  From 
     (
            Select DV4.PRPS_PYMT_ID, SUM(COALESCE(DV4.PYMT_ATRB_RDN_AMT,0)) PYMT_ATRB_RDN_AMT  from  EDV.PYMT_ATRB_RDN_LS DV4 where DV4.DATA_STAT_CD <>'B'
             And (DV4.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') 
             AND (DV4.DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
             group by DV4.PRPS_PYMT_ID
            UNION ALL
            Select DV5.PRPS_PYMT_ID, SUM(COALESCE(DV5.PYMT_ATRB_RDN_AMT,0)) PYMT_ATRB_RDN_AMT  from  EDV.PR_PYMT_ATRB_RDN_LS DV5 where   DV5.DATA_STAT_CD <>'B'
             And (DV5.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') 
             AND (DV5.DATA_EFF_STRT_DT) <=  TO_TIMESTAMP('{ETL_START_DATE}','YYYY-MM-DD')
             group by DV5.PRPS_PYMT_ID
     ) as t3 group by t3.PRPS_PYMT_ID
 ) PYMT_ATRB_RDN
 On ( DV_DR.PRPS_PYMT_ID = PYMT_ATRB_RDN.PRPS_PYMT_ID )
 
 Left Join cmn_dim_dm_stg.ACCT_PGM_DIM
 ON  ( DV_DR.ACCT_PGM_CD = ACCT_PGM_DIM.ACCT_PGM_CD And ACCT_PGM_DIM.DATA_STAT_CD ='A')
 
   
 Left Join pymt_dm_stg.ACCT_REF_TYPE_DIM  ACCT_REF_TYPE_PRIM_DIM
  ON (DV_DR.RCD_REF_PRIM_ID_TYPE_CD =ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_CD And ACCT_REF_TYPE_PRIM_DIM.DATA_STAT_CD ='A' And ACCT_REF_TYPE_PRIM_DIM.ACCT_REF_TYPE_DURB_ID > 0 )
  
  
 Left Join pymt_dm_stg.ACCT_REF_TYPE_DIM  ACCT_REF_TYPE_SCND_DIM
  ON( DV_DR.RCD_REF_SCND_ID_TYPE_CD =ACCT_REF_TYPE_SCND_DIM.ACCT_REF_CD And ACCT_REF_TYPE_SCND_DIM.DATA_STAT_CD ='A' And ACCT_REF_TYPE_SCND_DIM.ACCT_REF_TYPE_DURB_ID > 0)
  
LEFT  JOIN 
  (
        SELECT FSA_ST_CNTY_SRGT_ID,FSA_ST_CNTY_DURB_ID ,ST_FSA_CD ,CNTY_FSA_CD,ST_NM,CNTY_NM
        ,ROW_NUMBER() OVER ( PARTITION BY ST_FSA_CD  ,CNTY_FSA_CD ORDER BY CRE_DT DESC
        ) AS PRECEDENCE
        FROM cmn_dim_dm_stg.FSA_ST_CNTY_DIM
        WHERE CUR_RCD_IND = 1
  ) FSA_ST_CNTY_DIM 
ON ( DV_DR.ST_FSA_CD=FSA_ST_CNTY_DIM.ST_FSA_CD   And DV_DR.CNTY_FSA_CD = FSA_ST_CNTY_DIM.CNTY_FSA_CD AND FSA_ST_CNTY_DIM.PRECEDENCE = 1 )  
    
     Left join cmn_dim_dm_stg.CUST_DIM 
  On ( DV_DR.PAID_CORE_CUST_ID = CUST_DIM.CORE_CUST_ID
       And CUST_DIM.CUR_RCD_IND =1 And (CUST_DIM.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') 
        
      ) 
    
 Left Join 
   (
           Select * from (
        SELECT FSA_ST_CNTY_SRGT_ID RPT_FSA_ST_CNTY_SRGT_ID ,FSA_ST_CNTY_DURB_ID RPT_FSA_ST_CNTY_DURB_ID ,ST_FSA_CD ,CNTY_FSA_CD,ST_NM,CNTY_NM
        ,ROW_NUMBER() OVER ( PARTITION BY ST_FSA_CD  ,CNTY_FSA_CD ORDER BY CRE_DT DESC) AS PRECEDENCE
        FROM cmn_dim_dm_stg.FSA_ST_CNTY_DIM
        WHERE CUR_RCD_IND = 1   ) FSA_ST_CNTY_DIM JOIN cmn_dim_dm_stg.CUST_DIM  
                ON (FSA_ST_CNTY_DIM.ST_FSA_CD = CUST_DIM.RPT_ST_FSA_CD And FSA_ST_CNTY_DIM.CNTY_FSA_CD = CUST_DIM.RPT_CNTY_FSA_CD
                And   (CUST_DIM.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD')                 And  FSA_ST_CNTY_DIM.PRECEDENCE=1 
                    )
     ) RPT_FSA_ST_CNTY_DIM
ON (DV_DR.PAID_CORE_CUST_ID= RPT_FSA_ST_CNTY_DIM.CORE_CUST_ID) 
  
  Left Join EDV.PYMT_PGM_RS
   ON ( DV_DR.PYMT_PGM_ID = PYMT_PGM_RS.PYMT_PGM_ID And  (PYMT_PGM_RS.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )
   
   Left Join pymt_dm_stg.LTD_PYMT_PGM_DIM
   ON ( PYMT_PGM_RS.PYMT_PGM_NM = LTD_PYMT_PGM_NM And  (LTD_PYMT_PGM_DIM.DATA_EFF_END_DT) = TO_TIMESTAMP('9999-12-31','YYYY-MM-DD') )
   
    Left Join cmn_dim_dm_stg.PGM_YR_DIM
   on ( DV_DR.SBSD_PRD_STRT_YR = PGM_YR_DIM.PGM_YR And PGM_YR_DIM.DATA_STAT_CD ='A')
  
   Order by DV_DR.PRPS_PYMT_ID asc
 ) DV_ALL
 WHERE DV_ALL.Rank_Part = 1 
 ) dv 
 LEFT JOIN  pymt_dm_stg.DA_PRIM_CUST_ATRB_FACT dm
  on (
 (dv.PRPS_PYMT_ID,0) = (dm.PRPS_PYMT_ID,0)
 and dm.DATA_STAT_CD = 'A' 
 ) 
 where
  (
 dm.PRPS_PYMT_ID IS NULL
 )
 ORDER BY LAST_CHG_DT  asc 